### ISSUE TITLE
Large initial cost in ceres

### ISSUE THREAD

**Issue by At1a8** [ceres-solver/ceres-solver#1000]
My vins-fusion system has a large initial cost in some scenes. How can I find the causes of sensors or problems by some api in the ceres?

**Comment by At1a8** [comment]
![MicrosoftTeams-image (7)](https://github.com/ceres-solver/ceres-solver/assets/39615225/6bb9732b-1d90-4e52-ac21-c0595197f4d4)
Here is the full report

**Comment by sandwichmaker** [comment]
You can run Problem::Evaluate to see which cost function is contributing large residuals to the cost function.
