### ISSUE TITLE
Crash due to low system available memory when using ceres-solver do Bundle Adjustment

### ISSUE THREAD

**Issue by Vincent1923** [ceres-solver/ceres-solver#1001]
Recently I am trying to solve a large Bundle Adjustment problem. When the size of residual blocks exceed 50 million, ceres::solve() will apply for a very large memory. Program will crash because of low system available memory. I wonder if ceres will return some error when there is not enough available memory to solve large problem, such as catch an exception or other ways. I can terminate the program early to avoid program crash.
![image](https://github.com/ceres-solver/ceres-solver/assets/32729558/bf39d3c2-930d-43f2-949c-555620addee1)
![image](https://github.com/ceres-solver/ceres-solver/assets/32729558/a4aafe31-0586-4ddb-b00c-a3563710baaa)

**Comment by sandwichmaker** [comment]
@Vincent1923 what version of Ceres Solver are you using? If you try the version at head, I think you will find that it detects large memory allocs and handles them a bit more gracefully.

**Comment by Vincent1923** [comment]
@sandwichmaker the version I use is 2.1.0.

**Comment by sandwichmaker** [comment]
Try using the version at head. we checked in the graceful handling a couple of weeks ago.

**Comment by Vincent1923** [comment]
Thanks! I will try it using the version at head later.

**Comment by sandwichmaker** [comment]
any updated here?

**Comment by sandwichmaker** [comment]
Going to close due to lack of updates, please feel free to reopen as needed.
