### ISSUE TITLE
How does Google host Ceres Solver?

### ISSUE THREAD

**Issue by svanbodegraven** [ceres-solver/ceres-solver#1004]
Howdy all. Ceres Solver is used in production at Google. Is there any knowledge here how that hosting is done? I'd like to run Ceres Solver natively in the cloud and looking for tips. Thank you

**Comment by sandwichmaker** [comment]
@svanbodegraven  ceres solver is a library and not a hosted service. You build your application using it and run it like any other numerical library.

**Comment by svanbodegraven** [comment]
Thanks @sandwichmaker I am asking about what services are used to host the code running Ceres Solver. I'd like to run Ceres Solver so that the underlying compute scales gracefully, instead of on fixed VMs with hard failures when memory is exceeded. How have you seen Ceres Solver hosted so it scales without running out of resources. Would Cloud Functions be suitable for example.

**Comment by sandwichmaker** [comment]
Ceres itself depends on other libraries like suitesparse and eigen to do the heavy lifting of solving linear systems. I have no idea what cloud functions are and how you plan to use them.
