### ISSUE TITLE
Discrepancy between the LICENSE file in repo and the License page on the Ceres Solver website

### ISSUE THREAD

**Issue by chris24sahadeo** [ceres-solver/ceres-solver#1005]
The [repo's license](https://github.com/ceres-solver/ceres-solver/blob/master/LICENSE) states it is under Apache 2.0 but the [website's license](http://ceres-solver.org/license.html) says it is under the New BSD license (aka Clause-3)

**Comment by sandwichmaker** [comment]
There are pieces that are apache licensed that are included but Ceres
itself is released under bsd.

**Comment by chris24sahadeo** [comment]
Thanks for that insight @sandwichmaker :D 

Given that case, does the repo need to also include the BSD license info? Or is all good as is? (I am not familiar with licensing stuff).

**Comment by sandwichmaker** [comment]
I think the GitHub code that parses the license file is having some trouble. I will fix it. Thanks for bringing it to my attention.

**Comment by sandwichmaker** [comment]
@chris24sahadeo if you read the license file carefully you will see that the top part clearly says that ceres is bsd licensed.  Thats the text at the top of the license file. 

The two licenses at the bottom are from example and included code that come with mit and apache licenses.

**Comment by chris24sahadeo** [comment]
You are right! My bad. I was expecting to see the acronym "BSD" in the license header (as you would see with Apache 2.0) but I didn't realize that BSD licenses do not explicitly state "BSD" in the body of the license. Thanks for clarifying this :D. Closing issue.
