### ISSUE TITLE
Add support for Gauss-Newton Hessians besides Jacobians to Ceres

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#103]
Original [issue 102](https://code.google.com/p/ceres-solver/issues/detail?id=102) created by sandwichmaker on 2013-05-10T18:29:23.000Z:

Jacobians are nice, but for problems where the number of variables is MUCH smaller than the number of residuals, it makes more sense to directly compute J'J at eval time instead of storing J in memory.

We could start by just supporting crs and dense solvers via this route. 

The first step here would be to introduce the notion of a Model 

which has two subclasses, JacobianModel, GaussNewtonModel.

The former will store a jacobian and a residual vector
the latter will store a gauss-newton hessian matrix and a gradient vector. 

and then build the various trust region and line search algorithms in terms of the Model object..

**Comment by sinaaghli** [comment]
It has been many years since this post, but I was wondering if there is a feature for supplying hessian of very small problems where it could be calculated analytically?
maybe this feature is already available since 2015 ? 🤞

**Comment by sandwichmaker** [comment]
No, there is no plan to add this to ceres.

**Comment by zhangrong1722** [comment]
I was wondering how to implement this feature. Is there any idea?

**Comment by nemeshnorbert** [comment]
> It has been many years since this post, but I was wondering if there is a feature for supplying hessian of very small problems where it could be calculated analytically? maybe this feature is already available since 2015 ? crossed_fingers

Try this https://www.manopt.org/ or this https://www.math.fsu.edu/~whuang2/Indices/index_ROPTLIB.html but before read this https://www.youtube.com/watch?v=UjaoZE0GBpg
