### ISSUE TITLE
An optimization problem

### ISSUE THREAD

**Issue by YQ6666** [ceres-solver/ceres-solver#1035]
When I optimized the external parameters of the telecentric lens, it was more precisely called the rotation matrix, but the rotation matrix of the telecentric lens only had the first two rows and the first two columns, that is, there were only four parameters r11,r12,r21 and r22. I wanted to optimize these four parameters, but there was a problem, that is, **how to ensure that they still belonged to a rotation matrix after optimization. That is, how to ensure that they still conform to the rotation matrix constraint.**

**Comment by sandwichmaker** [comment]
What does it mean for r11, r12, r21, r22 to conform to a rotation matrix?

**Comment by sandwichmaker** [comment]
Closing because of lack of followup and I am not sure what to do about it either.
