### ISSUE TITLE
Do not force brewisms, rather make USE_HOMEBREW an explicit configure option

### ISSUE THREAD

**Issue by barracuda156** [ceres-solver/ceres-solver#1038]
It is wrong to force a specific package manager, even if it happens to be installed. There are several package managers on macOS, and while it is up to developers which to support if any, an assumption that macOS == Homebrew is incorrect and may lead to breakages. Specifically, `find_program(HOMEBREW_EXECUTABLE brew)` should not be done unconditionally but rather sit inside a macro.

**Comment by sandwichmaker** [comment]
This sound reasonable, we would be happy to accept a patch fixing this following instructions at 

http://ceres-solver.org/contributing.html

**Comment by barracuda156** [comment]
Thank you for addressing this!
