### ISSUE TITLE
Bazel build fails

### ISSUE THREAD

**Issue by joshi-bharat** [ceres-solver/ceres-solver#1043]
I tried to build bazel with tag 2.2.0 on Ubuntu 22.04 and it fails due to following reason:

Steps
`git clone git@github.com:ceres-solver/ceres-solver.git
cd ceres-solver
bazel build --cxxopt="-std=c++17" //:ceres
`
The error is 
`
ERROR: /home/bharatjoshi/code/ceres-solver/BUILD:36:14: Compiling internal/ceres/parallel_for.cc failed: missing input file '//:internal/ceres/parallel_for.cc'
`

On https://github.com/ceres-solver/ceres-solver/blob/095d483927d26bffc36d1fcc5fe8e2f1ef7da6b0/bazel/ceres.bzl#L98
parallel_for.cc is included in CERES_SRCS. However, internal/ceres/parallel_for.cc does not exist.

This needs to be removed. I can write a PR if my analysis is ok.

**Comment by sandwichmaker** [comment]
Hi @joshi-bharat thanks for reporting this and sorry for the inconvenience. This should be fixed at HEAD and will show up on github in a minute or two.
