### ISSUE TITLE
How to correctly call the official CUDA module of ceres?

### ISSUE THREAD

**Issue by LYK0520** [ceres-solver/ceres-solver#1045]
**options.dense_linear_algebra_library_type = ceres::CUDA;**
To call cuda, only the simple code above is needed to implement the three methods, respectively the **DENSE_QR, DENSE_NORMAL_CHOLESKY and DENSE_SCHUR**.
It is worth noting that without the line of code,the program runs normally and caculates the correct result. But after adding the call code, **DENSE_QR,DENSE_NORMAL_CHOLWSKY** will report an **error**, **DENSE_SCHUR** can run but the **gpu is not called**. I have confirmed that I have cuda installed.
![Snipaste_2024-01-25_16-27-59](https://github.com/ceres-solver/ceres-solver/assets/73179946/168e0e86-704c-4197-a804-091bf5b134dd)
Detailed examples of cuda calls are nowhere to be found in official documentation, and there doesn't seem to be much third-party explanation online. Is there a complete case explaining the call? I saw the official TEST in cuda_dense_cholesky_test.cc, but it was hard to understand.
If I have the honor to receive your reply, I will be very grateful! Thanks again!

**Comment by sandwichmaker** [comment]
you should not have to do anything other than set 
`Solver::Options::dense_linear_algebra_library = ceres::CUDA`.

What error are you getting when you enable CUDA?

**Comment by LYK0520** [comment]
I'm sorry I didn't follow you. The program runs smoothly when we don't use cuda; After cuda is used, only schur does not report errors, but also shows that the gpu usage is 0.
I'm sure I only added the line, but the cpu usage is always high and the gpu usage is 0. The IDE I use is 2022 visual studio. Is there any other configuration required for the program?

**Comment by sandwichmaker** [comment]
Have you tried using cuda with a smaller number of images?

**Comment by 838619643** [comment]
I have a similar problem. Looking forward to the official answer.

**Comment by sandwichmaker** [comment]
I think since you are trying to use this as part of colmap, I think you
should make sure that the colmap build environment is correct. It is hard
for me to diagnose this problem from here.

**Comment by AlexanderAKalinkin** [comment]
Hi Guys,
Have you ever thought about adding [cuDSS](https://developer.nvidia.com/cudss) as Direct Sparse Solver for GPU?
Thanks,

**Comment by sandwichmaker** [comment]
cuDSS is now part of Ceres Solver. Other than that there has not been any updates on this bug. so I am closing it.
