### ISSUE TITLE
Setting Parameter Weights or Covariance Values

### ISSUE THREAD

**Issue by xiaoguorui** [ceres-solver/ceres-solver#1047]
Hi,

I'm trying to use Ceres Solver for Bundle Adjustment. I don't see how to set weights for the parameters.  For instance, I want to say the intrinsic camera parameters (f, principle point) have fairly high confidence (low weights) and the extrinsic parameters should be adjusted more (high weights), by inputting weights for each parameter. Currently, I use the prior factor for a single parameter block. But, how to do such things for multiple parameter block as covariances are need in this case? Furthermore, is there any simple way if the covariance are obtained from anthor ceres problem?
Thank you,

**Comment by sandwichmaker** [comment]
Have a look at NormalPrior.
