### ISSUE TITLE
Failed to find Ceres - Missing required Ceres dependency: glog.  Searched   using GLOG_INCLUDE_DIR_HINTS: /usr/include and glog_DIR: .

### ISSUE THREAD

**Issue by xuanrun** [ceres-solver/ceres-solver#1053]
I use command **sudo apt-get install -y libgoogle-glog-dev and sudo apt-get install -y libatlas-base-dev**
afterward I use command 
**wget -O ~/Downloads/ceres.zip https://github.com/ceres-solver/ceres-solver/archive/1.14.0.zip
cd ~/Downloads/ && unzip ceres.zip -d ~/Downloads/
cd ~/Downloads/ceres-solver-1.14.0
mkdir ceres-bin && cd ceres-bin
cmake ..
sudo make install -j4**
all commands are successfully executed,
but when I complie this slam repo[https://github.com/TixiaoShan/LVI-SAM?tab=readme-ov-file](url)
execute **catkin_make**
the following cmake error came out 
![捕获](https://github.com/ceres-solver/ceres-solver/assets/104262060/0e0b9d6e-d590-46ef-86e9-e516bb28a405)
I tryed to solve this error by changed the **glog** version  to the 0.7 and 0.5,but other error came out ,
I also tryed to reset the **GLOG_INCLUDE_DIR_HINTS** and **glog_DIR** but nothing changed, this error came out all the same

**Comment by sandwichmaker** [comment]
1.14 is an ancient version of ceres solver and not supported anymore. Can you try something more recent?

**Comment by xuanrun** [comment]
> 1.14 is an ancient version of ceres solver and not supported anymore. Can you try something more recent?

thank you for your reply ,I just reinstall the glog version -- 0.4 from glog's github instead of using command "sudo apt-get install -y libgoogle-glog-dev"  and solved this problem.
