### ISSUE TITLE
Build error, marked "override", but does not override

### ISSUE THREAD

**Issue by hojjunekim** [ceres-solver/ceres-solver#1055]
Hi, thank you for providing good library.

I'm trying to upgrade ceres 1.13.0 to 2.1.0. So I'm trying to build and install 2.1.0, but it failed.

` $ cmake ../ceres-solver`
`$ make -j3`  

![Screenshot from 2024-03-06 19-26-58](https://github.com/ceres-solver/ceres-solver/assets/71844206/dedd5efc-0182-4837-b58c-ada50c545e8f)

I would appreciate for any help.

**Comment by sergiud** [comment]
It looks like you've updated to a development version of glog which recently removed deprecated methods. I suggest you use the release version of glog instead.

**Comment by hojjunekim** [comment]
You were correct. I degraded my glog from 0.7.0 to 0.6.0, and it works now!
Thank you for your help:)
