### ISSUE TITLE
how to optimize the BA with direct method?

### ISSUE THREAD

**Issue by zhang-qiang-github** [ceres-solver/ceres-solver#1057]
Is there example for direct method BA?

Actually, I have a cost function: `f( I(K*p) )`. There is a image interpolation. How can I optimize it with ceres? Is there any example?

**Comment by sandwichmaker** [comment]
We do not have an example in the codebase. We have support for interpolating grids like images. I suspect you should be able to use it to implement what you need.

**Comment by sandwichmaker** [comment]
I am going to close, this if you have further questions please feel free to reopen.
