### ISSUE TITLE
nvcc fatal   : Unknown option '-extended-lambda'

### ISSUE THREAD

**Issue by Guoc0529** [ceres-solver/ceres-solver#1064]
nvcc fatal   : Unknown option '-extended-lambda'
make[2]: *** [internal/ceres/CMakeFiles/ceres_cuda_kernels.dir/build.make:63：internal/ceres/CMakeFiles/ceres_cuda_kernels.dir/cuda_kernels_vector_ops.cu.cc.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1963：internal/ceres/CMakeFiles/ceres_cuda_kernels.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....

**Comment by isJHan** [comment]
You can use `cmake /path/to/Ceres -DUSE_CUDA=false` to disable CUDA support.

**Comment by sandwichmaker** [comment]
Closing because of lack of updates.

**Comment by mmalmeid** [comment]
> You can use `cmake /path/to/Ceres -DUSE_CUDA=false` to disable CUDA support.

What is the impact of disabling CUDA? I'm having this issue too, but I'd like to have CERES with CUDA acceleration, if possible

**Comment by sandwichmaker** [comment]
The impact on what kind of speedups you get will depend on the size and complexity of problems. Since it appears you are starting out with Ceres I would not worry about it and aim to get a high performing version working on CPU first.
