### ISSUE TITLE
Windows CI action fails

### ISSUE THREAD

**Issue by S-o-T** [ceres-solver/ceres-solver#1070]
CUDA 12.2 is not compatible with MSVC version that is provided by github's windows CI https://github.com/S-o-T/ceres-solver/actions/runs/9430699134/job/

While updating CUDA to 12.5 fixes the compilation issue, there still some problem with no-cuda runner https://github.com/S-o-T/ceres-solver/actions/runs/9435197643/job/25988292357

I can't reproduce that locally.

**Comment by sergiud** [comment]
A recent Github `windows-2022` runner update introduced an [issue](https://github.com/actions/runner-images/issues/10004) that causes SEH exceptions in test runs.

**Comment by sergiud** [comment]
New runner images have been deployed. The issue should no longer occur.
