### ISSUE TITLE
What's the difference between Ceres 1.14 and 2.0 for the method ':AddResidualBlock'?

### ISSUE THREAD

**Issue by iDonghq** [ceres-solver/ceres-solver#1073]
Issue description: 
 The same cost function and parameters, it can run in the 1.14 version, but when running in the 2.0 version, it gets a segmentation fault. I have compared the two  version, ceres-2.0 is more concise for AddResidualBlock(...).
The code snippet like this:
'double data[5][10]; // it has been assign before, just for issue description
problem.AddResidualBlock(user_define_factor, NULL, data[0])' // it rus 1.14 ok, but segmentation fault on ceres-2.0

Thanks
look forward to your replying

**Comment by sandwichmaker** [comment]
There should not no difference. If you are getting a segfault, it is most likely something that is happening in your code. Have you tried running your code through the debugger?

**Comment by iDonghq** [comment]
> There should not no difference. If you are getting a segfault, it is most likely something that is happening in your code. Have you tried running your code through the debugger?

Yes, issue update by using gdb （ program_ = nullptr ）, it is as followed:
This is CeresSolver2.0 code snippet:
// The default constructor is equivalent to the
// invocation Problem(Problem::Options()).
"problem.h"
class CERES_EXPORT Problem {
Problem();
explicit Problem(const Options& options);
Problem(Problem&&);
Problem& operator=(Problem&&);

Problem(const Problem&) = delete;
Problem& operator=(const Problem&) = delete;

~Problem();

 template <typename... Ts>
  ResidualBlockId AddResidualBlock(CostFunction* cost_function,
                                   LossFunction* loss_function,
                                   double* x0,
                                   Ts*... xs) {
    const std::array<double*, sizeof...(Ts) + 1> parameter_blocks{{x0, xs...}};
    return AddResidualBlock(cost_function,
                            loss_function,
                            parameter_blocks.data(),
                            static_cast<int>(parameter_blocks.size()));
  }

  // Add a residual block by providing a vector of parameter blocks.
  ResidualBlockId AddResidualBlock(
      CostFunction* cost_function,
      LossFunction* loss_function,
      const std::vector<double*>& parameter_blocks);
  
    void AddParameterBlock(double* values, int size);
      
...
...
 std::unique_ptr<internal::ProblemImpl> impl_;
}

"problem.cc"

Problem::Problem() : impl_(new internal::ProblemImpl) {
  std::cout << "Problem with no parameter-----------------------"<< "\n";
}
Problem::Problem(const Problem::Options& options)
    : impl_(new internal::ProblemImpl(options)) {
      std::cout << "Problem with parameter-----------------------"<< "\n";
    }
// Not inline defaulted in declaration due to use of std::unique_ptr.
Problem::Problem(Problem&&) = default;
Problem& Problem::operator=(Problem&&) = default;
Problem::~Problem() {}



"problem_impl.h"
class CERES_EXPORT_INTERNAL ProblemImpl {
 public:
  typedef std::map<double*, ParameterBlock*> ParameterMap;
  typedef std::unordered_set<ResidualBlock*> ResidualBlockSet;
  typedef std::map<CostFunction*, int> CostFunctionRefCount;
  typedef std::map<LossFunction*, int> LossFunctionRefCount;

  ProblemImpl();
  explicit ProblemImpl(const Problem::Options& options);
  ProblemImpl(const ProblemImpl&) = delete;
  void operator=(const ProblemImpl&) = delete;

  ~ProblemImpl();

...
...

 std::unique_ptr<internal::Program> program_;

}

"problem_impl.cc"
ProblemImpl::ProblemImpl()
    : options_(Problem::Options()), program_(new internal::Program) {
  InitializeContext(options_.context, &context_impl_, &context_impl_owned_);
}

ProblemImpl::ProblemImpl(const Problem::Options& options)
    : options_(options), program_(new internal::Program) {
  program_->evaluation_callback_ = options.evaluation_callback;
  InitializeContext(options_.context, &context_impl_, &context_impl_owned_);
}


When I used:

ceres::Problem  problem; //There is no any output, and program_ = nullptr

ubuntu 20.04(gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2) c++14) runs ok, ubuntu 18.04(gcc 7.5 c++14) crash with segmetation fault because program_ = nullptr

**Comment by iDonghq** [comment]
> There should not no difference. If you are getting a segfault, it is most likely something that is happening in your code. Have you tried running your code through the debugger?

I just upgrade my project from ceres 1.1.4 to ceres2.0

**Comment by iDonghq** [comment]
> > There should not no difference. If you are getting a segfault, it is most likely something that is happening in your code. Have you tried running your code through the debugger?
> 
> Yes, issue update by using gdb （ program_ = nullptr ）, it is as followed: This is CeresSolver2.0 code snippet: // The default constructor is equivalent to the // invocation Problem(Problem::Options()). "problem.h" class CERES_EXPORT Problem { Problem(); explicit Problem(const Options& options); Problem(Problem&&); Problem& operator=(Problem&&);
> 
> Problem(const Problem&) = delete; Problem& operator=(const Problem&) = delete;
> 
> ~Problem();
> 
> template <typename... Ts> ResidualBlockId AddResidualBlock(CostFunction* cost_function, LossFunction* loss_function, double* x0, Ts*... xs) { const std::array<double*, sizeof...(Ts) + 1> parameter_blocks{{x0, xs...}}; return AddResidualBlock(cost_function, loss_function, parameter_blocks.data(), static_cast(parameter_blocks.size())); }
> 
> // Add a residual block by providing a vector of parameter blocks. ResidualBlockId AddResidualBlock( CostFunction* cost_function, LossFunction* loss_function, const std::vector<double*>& parameter_blocks);
> 
> ```
> void AddParameterBlock(double* values, int size);
> ```
> 
> ... ... std::unique_ptrinternal::ProblemImpl impl_; }
> 
> "problem.cc"
> 
> Problem::Problem() : impl_(new internal::ProblemImpl) { std::cout << "Problem with no parameter-----------------------"<< "\n"; } Problem::Problem(const Problem::Options& options) : impl_(new internal::ProblemImpl(options)) { std::cout << "Problem with parameter-----------------------"<< "\n"; } // Not inline defaulted in declaration due to use of std::unique_ptr. Problem::Problem(Problem&&) = default; Problem& Problem::operator=(Problem&&) = default; Problem::~Problem() {}
> 
> "problem_impl.h" class CERES_EXPORT_INTERNAL ProblemImpl { public: typedef std::map<double*, ParameterBlock*> ParameterMap; typedef std::unordered_set<ResidualBlock*> ResidualBlockSet; typedef std::map<CostFunction*, int> CostFunctionRefCount; typedef std::map<LossFunction*, int> LossFunctionRefCount;
> 
> ProblemImpl(); explicit ProblemImpl(const Problem::Options& options); ProblemImpl(const ProblemImpl&) = delete; void operator=(const ProblemImpl&) = delete;
> 
> ~ProblemImpl();
> 
> ... ...
> 
> std::unique_ptrinternal::Program program_;
> 
> }
> 
> "problem_impl.cc" ProblemImpl::ProblemImpl() : options_(Problem::Options()), program_(new internal::Program) { InitializeContext(options_.context, &context_impl_, &context_impl_owned_); }
> 
> ProblemImpl::ProblemImpl(const Problem::Options& options) : options_(options), program_(new internal::Program) { program_->evaluation_callback_ = options.evaluation_callback; InitializeContext(options_.context, &context_impl_, &context_impl_owned_); }
> 
> When I used:
> 
> ceres::Problem problem; //There is no any output, and program_ = nullptr
> 
> ubuntu 20.04(gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2) c++14) runs ok, ubuntu 18.04(gcc 7.5 c++14) crash with segmetation fault because program_ = nullptr

I just upgrade my project from ceres 1.1.4 to ceres2.0; ceres2.0 is built by shared library, and it is installed the path where in my project, and have included and linked by message output in CMakelists.txt correctly

**Comment by iDonghq** [comment]
> There should not no difference. If you are getting a segfault, it is most likely something that is happening in your code. Have you tried running your code through the debugger?

I debugged it using gdb, here is the whole issue update:
This is CeresSolver2.0 code snippet:
// The default constructor is equivalent to the
// invocation Problem(Problem::Options()).
"problem.h"
class CERES_EXPORT Problem {
Problem();
explicit Problem(const Options& options);
Problem(Problem&&);
Problem& operator=(Problem&&);

Problem(const Problem&) = delete;
Problem& operator=(const Problem&) = delete;

~Problem();

 template <typename... Ts>
  ResidualBlockId AddResidualBlock(CostFunction* cost_function,
                                   LossFunction* loss_function,
                                   double* x0,
                                   Ts*... xs) {
    const std::array<double*, sizeof...(Ts) + 1> parameter_blocks{{x0, xs...}};
    return AddResidualBlock(cost_function,
                            loss_function,
                            parameter_blocks.data(),
                            static_cast<int>(parameter_blocks.size()));
  }

  // Add a residual block by providing a vector of parameter blocks.
  ResidualBlockId AddResidualBlock(
      CostFunction* cost_function,
      LossFunction* loss_function,
      const std::vector<double*>& parameter_blocks);
  
    void AddParameterBlock(double* values, int size);
      
...
...
 std::unique_ptr<internal::ProblemImpl> impl_;
}

"problem.cc"

Problem::Problem() : impl_(new internal::ProblemImpl) {
  std::cout << "Problem with no parameter-----------------------"<< "\n";
}
Problem::Problem(const Problem::Options& options)
    : impl_(new internal::ProblemImpl(options)) {
      std::cout << "Problem with parameter-----------------------"<< "\n";
    }
// Not inline defaulted in declaration due to use of std::unique_ptr.
Problem::Problem(Problem&&) = default;
Problem& Problem::operator=(Problem&&) = default;
Problem::~Problem() {}



"problem_impl.h"
class CERES_EXPORT_INTERNAL ProblemImpl {
 public:
  typedef std::map<double*, ParameterBlock*> ParameterMap;
  typedef std::unordered_set<ResidualBlock*> ResidualBlockSet;
  typedef std::map<CostFunction*, int> CostFunctionRefCount;
  typedef std::map<LossFunction*, int> LossFunctionRefCount;

  ProblemImpl();
  explicit ProblemImpl(const Problem::Options& options);
  ProblemImpl(const ProblemImpl&) = delete;
  void operator=(const ProblemImpl&) = delete;

  ~ProblemImpl();

...
...

 std::unique_ptr<internal::Program> program_;

}

"problem_impl.cc"
ProblemImpl::ProblemImpl()
    : options_(Problem::Options()), program_(new internal::Program) {
  InitializeContext(options_.context, &context_impl_, &context_impl_owned_);
}

ProblemImpl::ProblemImpl(const Problem::Options& options)
    : options_(options), program_(new internal::Program) {
  program_->evaluation_callback_ = options.evaluation_callback;
  InitializeContext(options_.context, &context_impl_, &context_impl_owned_);
}


When I used:

ceres::Problem  problem; //There is no any output, and program_ = nullptr

ubuntu 20.04(gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2) c++14) runs ok, ubuntu 18.04(gcc 7.5 c++14) crash with segmetation fault because program_ = nullptr;


I just upgrade my project from ceres 1.1.4 to ceres2.0; ceres2.0 is built by shared library, and it is installed the path where in my project, and have included and linked by message output in CMakelists.txt correctly

**Comment by iDonghq** [comment]
I debugged it using gdb, here is the whole issue update:
This is CeresSolver2.0 code snippet:
// The default constructor is equivalent to the
// invocation Problem(Problem::Options()).
"problem.h"
class CERES_EXPORT Problem {
Problem();
explicit Problem(const Options& options);
Problem(Problem&&);
Problem& operator=(Problem&&);

Problem(const Problem&) = delete;
Problem& operator=(const Problem&) = delete;

~Problem();

template <typename... Ts>
ResidualBlockId AddResidualBlock(CostFunction* cost_function,
LossFunction* loss_function,
double* x0,
Ts*... xs) {
const std::array<double*, sizeof...(Ts) + 1> parameter_blocks{{x0, xs...}};
return AddResidualBlock(cost_function,
loss_function,
parameter_blocks.data(),
static_cast(parameter_blocks.size()));
}

// Add a residual block by providing a vector of parameter blocks.
ResidualBlockId AddResidualBlock(
CostFunction* cost_function,
LossFunction* loss_function,
const std::vector<double*>& parameter_blocks);

void AddParameterBlock(double* values, int size);
...
...
std::unique_ptrinternal::ProblemImpl impl_;
}

"problem.cc"

Problem::Problem() : impl_(new internal::ProblemImpl) {
std::cout << "Problem with no parameter-----------------------"<< "\n";
}
Problem::Problem(const Problem::Options& options)
: impl_(new internal::ProblemImpl(options)) {
std::cout << "Problem with parameter-----------------------"<< "\n";
}
// Not inline defaulted in declaration due to use of std::unique_ptr.
Problem::Problem(Problem&&) = default;
Problem& Problem::operator=(Problem&&) = default;
Problem::~Problem() {}

"problem_impl.h"
class CERES_EXPORT_INTERNAL ProblemImpl {
public:
typedef std::map<double*, ParameterBlock*> ParameterMap;
typedef std::unordered_set<ResidualBlock*> ResidualBlockSet;
typedef std::map<CostFunction*, int> CostFunctionRefCount;
typedef std::map<LossFunction*, int> LossFunctionRefCount;

ProblemImpl();
explicit ProblemImpl(const Problem::Options& options);
ProblemImpl(const ProblemImpl&) = delete;
void operator=(const ProblemImpl&) = delete;

~ProblemImpl();

...
...

std::unique_ptrinternal::Program program_;

}

"problem_impl.cc"
ProblemImpl::ProblemImpl()
: options_(Problem::Options()), program_(new internal::Program) {
InitializeContext(options_.context, &context_impl_, &context_impl_owned_);
}

ProblemImpl::ProblemImpl(const Problem::Options& options)
: options_(options), program_(new internal::Program) {
program_->evaluation_callback_ = options.evaluation_callback;
InitializeContext(options_.context, &context_impl_, &context_impl_owned_);
}

The usage:

ceres::Problem problem; //There is no any output, and program_ = nullptr

ubuntu 20.04(gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2) c++14) runs ok, ubuntu 18.04(gcc 7.5 c++14) crash with  segmentation fault because program_ = nullptr;

I just upgrade my project from ceres 1.1.4 to ceres2.0; ceres2.0 is built by shared library, and it is installed the path where in my project, and have included and linked by message output in CMakelists.txt correctly

**Comment by sandwichmaker** [comment]
Two things.

1. Ceres Solver 2.0 is rather old, by multiple years at this point. I recommend version 2.2.0.
2. That said, are you saying that ProblemImpl has a nullptr for program_ ? that makes no sense since the constructor for ProblemImpl explicitly initializes it.

```
ProblemImpl::ProblemImpl()
: options_(Problem::Options()), program_(new internal::Program) {
InitializeContext(options_.context, &context_impl_, &context_impl_owned_);
}
```

**Comment by iDonghq** [comment]
for 1:
Taking into compatibility with my project considerations , I just want to upgrade from older 1.14 to 2.0 for my project smoothly. In the future I am going to upgrade Ceres2.2 for manifold optimization.
for 2:
ceres::Problem problem;// auto call the constructor Problem->impl_(new internal::ProblemImpl)->ProblemImpl::ProblemImpl(),
but program_=nullptr, maybe it is the issue of the build environment? or linux version?

**Comment by iDonghq** [comment]
for 1:
Taking compatibility  with my project into account, I just want to upgrade ceressolver from 1.14 to 2.0 smoothly. CeresSolver2.2.0 is the future update for manifold optimization.
for2:
After running this line: "ceres::Problem problem";  The expected output is ""Problem with no parameter-----------------------" from the code snippet: (Problem::Problem() : impl_(new internal::ProblemImpl) { std::cout << "Problem with no parameter-----------------------"<< "\n";
}), BUT not. The weird thing is: problem.AddParameterBlock(...) runs ok, problem.AddResidualBlock(...) crash down, find program_= nullptr by gdb in method "ProblemImpl::AddResidualBlock(
    CostFunction* cost_function,
    LossFunction* loss_function,
    double* const* const parameter_blocks,
    int num_parameter_blocks) "  the position of crashdown is "ResidualBlock* new_residual_block =
      new ResidualBlock(cost_function,
                        loss_function,
                        parameter_block_ptrs,
                        program_->residual_blocks_.size());" program_=nullptr

**Comment by iDonghq** [comment]
> for 1:
> Taking compatibility with my project into account, I just want to upgrade ceressolver from 1.14 to 2.0 smoothly. CeresSolver2.2.0 is the future update for manifold optimization.
> for2:
> After running this line: "ceres::Problem problem"; The expected output is ""Problem with no parameter-----------------------" from the code snippet: (Problem::Problem() : impl_(new internal::ProblemImpl) { std::cout << "Problem with no parameter-----------------------"<< "\n";
> }), BUT not. The weird thing is: problem.AddParameterBlock(...) runs ok, problem.AddResidualBlock(...) crash down, find program_= nullptr by gdb in method "ProblemImpl::AddResidualBlock(
> CostFunction* cost_function,
> LossFunction* loss_function,
> double* const* const parameter_blocks,
> int num_parameter_blocks) " the position of crashdown is "ResidualBlock* new_residual_block =
> new ResidualBlock(cost_function,
> loss_function,
> parameter_block_ptrs,
> program_->residual_blocks_.size());" program_=nullptr

for 1:
Taking compatibility with my project into account, I just want to upgrade ceressolver from 1.14 to 2.0 smoothly. CeresSolver2.2.0 is the future update for manifold optimization.
for2:
After running this line: "ceres::Problem problem"; The expected output is ""Problem with no parameter-----------------------" from the code snippet: (Problem::Problem() : impl_(new internal::ProblemImpl) { std::cout << "Problem with no parameter-----------------------"<< "\n";
}), BUT not. The weird thing is: problem.AddParameterBlock(...) runs ok, problem.AddResidualBlock(...) crash down, find program_= nullptr by gdb in method "ProblemImpl::AddResidualBlock(
CostFunction* cost_function,
LossFunction* loss_function,
double* const* const parameter_blocks,
int num_parameter_blocks) " the position of crashdown is "ResidualBlock* new_residual_block =
new ResidualBlock(cost_function,
loss_function,
parameter_block_ptrs,
program_->residual_blocks_.size());" program_=nullptr

**Comment by iDonghq** [comment]
> for 1:
> Taking compatibility with my project into account, I just want to upgrade ceressolver from 1.14 to 2.0 smoothly. CeresSolver2.2.0 is the future update for manifold optimization.
> for2:
> After running this line: "ceres::Problem problem"; The expected output is ""Problem with no parameter-----------------------" from the code snippet: (Problem::Problem() : impl_(new internal::ProblemImpl) { std::cout << "Problem with no parameter-----------------------"<< "\n";
> }), BUT not. The weird thing is: problem.AddParameterBlock(...) runs ok, problem.AddResidualBlock(...) crash down, find program_= nullptr by gdb in method "ProblemImpl::AddResidualBlock(
> CostFunction* cost_function,
> LossFunction* loss_function,
> double* const* const parameter_blocks,
> int num_parameter_blocks) " the position of crashdown is "ResidualBlock* new_residual_block =
> new ResidualBlock(cost_function,
> loss_function,
> parameter_block_ptrs,
> program_->residual_blocks_.size());" program_=nullptr

for 1:
Taking compatibility with my project into account, I just want to upgrade ceressolver from 1.14 to 2.0 smoothly. CeresSolver2.2.0 is the future update for manifold optimization.
for2:
After running this line: "ceres::Problem problem"; The expected output is ""Problem with no parameter-----------------------" from the code snippet: (Problem::Problem() : impl_(new internal::ProblemImpl) { std::cout << "Problem with no parameter-----------------------"<< "\n";
}), BUT not. The weird thing is: problem.AddParameterBlock(...) runs ok, problem.AddResidualBlock(...) crash down, find program_= nullptr by gdb in method "ProblemImpl::AddResidualBlock(
CostFunction* cost_function,
LossFunction* loss_function,
double* const* const parameter_blocks,
int num_parameter_blocks) " the position of crashdown is "ResidualBlock* new_residual_block =
new ResidualBlock(cost_function,
loss_function,
parameter_block_ptrs,
program_->residual_blocks_.size());" program_=nullptr

**Comment by iDonghq** [comment]
> for 1:
> Taking compatibility with my project into account, I just want to upgrade ceressolver from 1.14 to 2.0 smoothly. CeresSolver2.2.0 is the future update for manifold optimization.
> for2:
> After running this line: "ceres::Problem problem"; The expected output is ""Problem with no parameter-----------------------" from the code snippet: (Problem::Problem() : impl_(new internal::ProblemImpl) { std::cout << "Problem with no parameter-----------------------"<< "\n";
> }), BUT not. The weird thing is: problem.AddParameterBlock(...) runs ok, problem.AddResidualBlock(...) crash down, find program_= nullptr by gdb in method "ProblemImpl::AddResidualBlock(
> CostFunction* cost_function,
> LossFunction* loss_function,
> double* const* const parameter_blocks,
> int num_parameter_blocks) " the position of crashdown is "ResidualBlock* new_residual_block =
> new ResidualBlock(cost_function,
> loss_function,
> parameter_block_ptrs,
> program_->residual_blocks_.size());" program_=nullptr

for 1:
Taking compatibility with my project into account, I just want to upgrade ceressolver from 1.14 to 2.0 smoothly. CeresSolver2.2.0 is the future update for manifold optimization.
for2:
After running this line: "ceres::Problem problem"; The expected output is ""Problem with no parameter-----------------------" from the code snippet: (Problem::Problem() : impl_(new internal::ProblemImpl) { std::cout << "Problem with no parameter-----------------------"<< "\n";
}), BUT not. The weird thing is: problem.AddParameterBlock(...) runs ok, problem.AddResidualBlock(...) crash down, find program_= nullptr by gdb in method "ProblemImpl::AddResidualBlock(
CostFunction* cost_function,
LossFunction* loss_function,
double* const* const parameter_blocks,
int num_parameter_blocks) " the position of crashdown is "ResidualBlock* new_residual_block =
new ResidualBlock(cost_function,
loss_function,
parameter_block_ptrs,
program_->residual_blocks_.size());" program_=nullptr

**Comment by iDonghq** [comment]
> Two things.
> 
> 1. Ceres Solver 2.0 is rather old, by multiple years at this point. I recommend version 2.2.0.
> 2. That said, are you saying that ProblemImpl has a nullptr for program_ ? that makes no sense since the constructor for ProblemImpl explicitly initializes it.
> 
> ```
> ProblemImpl::ProblemImpl()
> : options_(Problem::Options()), program_(new internal::Program) {
> InitializeContext(options_.context, &context_impl_, &context_impl_owned_);
> }
> ```

for 1:
Taking compatibility with my project into account, I just want to upgrade ceressolver from 1.14 to 2.0 smoothly. CeresSolver2.2.0 is the future update for manifold optimization.
for2:
After running this line: "ceres::Problem problem"; The expected output is ""Problem with no parameter-----------------------" from the code snippet:
```
 (Problem::Problem() : impl_(new internal::ProblemImpl) { std::cout << "Problem with no parameter-----------------------"<< "\n";
}),
```
BUT not. The weird thing is: problem.AddParameterBlock(...) runs ok, problem.AddResidualBlock(...) crash down, find program_= nullptr by gdb in method "ProblemImpl::AddResidualBlock(
CostFunction* cost_function,
LossFunction* loss_function,
double* const* const parameter_blocks,
int num_parameter_blocks) " the position of crashdown is "ResidualBlock* new_residual_block =
new ResidualBlock(cost_function,
loss_function,
parameter_block_ptrs,
program_->residual_blocks_.size());" program_=nullptr
