### ISSUE TITLE
Why the library for linux is so big?

### ISSUE THREAD

**Issue by mhzhou2021** [ceres-solver/ceres-solver#1074]
Hi, I used the ceres-solver 2.2.0 to build the aarch64-poky-linux library, the libceres.so is up to 470MB. thanks！
cmake -DBUILD_SHARED_LIBS=ON -DMINIGLOG=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_CXX_STANDARD=14 -DEigen3_DIR=./eigen-3.3.9/build/ ..

**Comment by mhzhou2021** [comment]
@sergiud Thank you for your help. how to strip in cmake？
$ file libceres.so.2.2.0
libceres.so.2.2.0: ELF 64-bit LSB shared object, ARM aarch64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=65f93d6d59b196b4ecf96b47e1f136c37b5e02a7, with debug_info, not stripped

**Comment by sergiud** [comment]
Running the `install/strip` target is the CMake approach.

**Comment by mhzhou2021** [comment]
@sergiud Thank you for your help. It works very well.
