### ISSUE TITLE
Github actions fails due to googletest submodule is not checked out.

### ISSUE THREAD

**Issue by S-o-T** [ceres-solver/ceres-solver#1078]
https://github.com/ceres-solver/ceres-solver/actions/runs/9829014776/job/27133621021

**Comment by sergiud** [comment]
Thanks. I'm already on it. However, a proper fix will possibly take some time.

**Comment by sandwichmaker** [comment]
Sorry for the breakage folks,

**Comment by sergiud** [comment]
No problem, Sameer. This was expected.

**Comment by sergiud** [comment]
The issue was fixed in 540b1f2f7a9f6e30791954ca555870662dc36422 and e47a42c2957951c9fafcca9995d9927e15557069.
