### ISSUE TITLE
Error:make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by ccrrkk** [ceres-solver/ceres-solver#1080]
Hi，I'm using Ubuntu 20.04. I'm following the instructions from http://ceres-solver.org/ to install ceres-solver.However, when I run the command `make -j4`, I encounter the error message `make: *** No targets specified and no makefile found`.  Stop. Could you please advise on how to resolve this issue?

**Comment by sandwichmaker** [comment]
Please share more details. What version of Ceres solver and your cmake logs
