### ISSUE TITLE
Example code doesn't work

### ISSUE THREAD

**Issue by dolgae03** [ceres-solver/ceres-solver#1088]
The example hello word has problem

On 64 lines,

```
  ceres::CostFunction* cost_function =
      new ceres::AutoDiffCostFunction<CostFunctor, 1, 1>();
  problem.AddResidualBlock(cost_function, nullptr, &x);

```

the operator must contains new CostFunctor or something.

**Comment by sandwichmaker** [comment]
Are you just trying to use hello world or did you modify it?

**Comment by dolgae03** [comment]
I just tried to run hello world. I never modified it. However, without modifying the error occurs. However, if I add new CostFunctor, It works.

**Comment by sandwichmaker** [comment]
That is odd. Can you share your full build setup?

**Comment by chjXu** [comment]
// Ceres Solver - A fast non-linear least squares minimizer
// Copyright 2023 Google Inc. All rights reserved.
// http://ceres-solver.org/
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of source code must retain the above copyright notice,
//   this list of conditions and the following disclaimer.
// * Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
// * Neither the name of Google Inc. nor the names of its contributors may be
//   used to endorse or promote products derived from this software without
//   specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
//
// Author: keir@google.com (Keir Mierle)
//
// A simple example of using the Ceres minimizer.
//
// Minimize 0.5 (10 - x)^2 using jacobian matrix computed using
// automatic differentiation.
#include "absl/log/initialize.h"
#include "ceres/ceres.h"
// A templated cost functor that implements the residual r = 10 -
// x. The method operator() is templated so that we can then use an
// automatic differentiation wrapper around it to generate its
// derivatives.
struct CostFunctor {
    template <typename T>
    bool operator()(const T* const x, T* residual) const {
        residual[0] = 10.0 - x[0];
        return true;
    }
};
int main(int argc, char** argv) {
    absl::InitializeLog();
    // The variable to solve for with its initial value. It will be
    // mutated in place by the solver.
    double x = 0.5;
    const double initial_x = x;
    // Build the problem.
    ceres::Problem problem;
    // Set up the only cost function (also known as residual). This uses
    // auto-differentiation to obtain the derivative (jacobian).
    ceres::CostFunction* cost_function =
        new ceres::AutoDiffCostFunction<CostFunctor, 1, 1>();
    problem.AddResidualBlock(cost_function, nullptr, &x);
    // Run the solver!
    ceres::Solver::Options options;
    options.minimizer_progress_to_stdout = true;
    ceres::Solver::Summary summary;
    ceres::Solve(options, &problem, &summary);
    std::cout << summary.BriefReport() << "\n";
    std::cout << "x : " << initial_x << " -> " << x << "\n";
    return 0;
}


error: no matching function for call to ‘ceres::AutoDiffCostFunction<CostFunctor, 1, 1>::AutoDiffCostFunction()’

**Comment by chjXu** [comment]
@sandwichmaker

**Comment by sandwichmaker** [comment]
I am asking about your build environment. What compiler? Output of running cmake when you built Ceres solver

**Comment by chjXu** [comment]
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_BIGOBJ
-- Performing Test HAVE_BIGOBJ - Failed
-- Looking for pow in m
-- Looking for pow in m - found
-- Detected Ceres version: 2.2.0 from /workspaces/third_party/ceres-solver/include/ceres/version.h
-- Found Eigen version 3.3.7: /usr/lib/cmake/eigen3
-- Enabling use of Eigen as a sparse linear algebra library.
-- Did not find CUDA, disabling CUDA support.
-- Building without CUDA.
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /usr/lib/x86_64-linux-gnu/libopenblas.so  
-- Found LAPACK library: /usr/lib/x86_64-linux-gnu/libopenblas.so
-- Found CHOLMOD headers in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found SPQR headers in: /usr/include/suitesparse
-- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Found Config headers in: /usr/include/suitesparse
-- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Found AMD headers in: /usr/include/suitesparse
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found CAMD headers in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CCOLAMD headers in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found COLAMD headers in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
-- Looking for shm_open in rt
-- Looking for shm_open in rt - found
-- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Found METIS: /usr/include (found version "5.1.0") 
-- Looking for cholmod_metis
-- Looking for cholmod_metis - found
-- Found SuiteSparse: /usr/include/suitesparse (found suitable version "5.7.1", minimum required is "4.5.6") found components: CHOLMOD SPQR Partition Config AMD CAMD CCOLAMD COLAMD 
-- Found SuiteSparse 5.7.1, building with SuiteSparse.
-- Building without Apple's Accelerate sparse support.
-- Found Google Flags (gflags) version 2.2.2: /usr/lib/x86_64-linux-gnu/cmake/gflags
-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
-- Found Glog: /usr/include  
-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
-- Failed to find Google benchmark library, disabling build of benchmarks.
-- Building Ceres as a static library.
-- No build type specified; defaulting to CMAKE_BUILD_TYPE=Release.
-- Performing Test CHECK_CXX_FLAG_Wmissing_declarations
-- Performing Test CHECK_CXX_FLAG_Wmissing_declarations - Success
-- Performing Test CHECK_CXX_FLAG_Wno_unknown_pragmas
-- Performing Test CHECK_CXX_FLAG_Wno_unknown_pragmas - Success
-- Performing Test CHECK_CXX_FLAG_Wno_sign_compare
-- Performing Test CHECK_CXX_FLAG_Wno_sign_compare - Success
-- Performing Test CHECK_CXX_FLAG_Wno_unused_parameter
-- Performing Test CHECK_CXX_FLAG_Wno_unused_parameter - Success
-- Performing Test CHECK_CXX_FLAG_Wno_missing_field_initializers
-- Performing Test CHECK_CXX_FLAG_Wno_missing_field_initializers - Success
-- Creating configured Ceres config.h output directory: /workspaces/DrivingPaltform-DP/third_party/ceres-solver/build/include/ceres/internal
-- Enabling CERES_USE_EIGEN_SPARSE in Ceres config.h
-- Enabling CERES_NO_CUDA in Ceres config.h
-- Enabling CERES_NO_ACCELERATE_SPARSE in Ceres config.h
-- Performing Test CHECK_CXX_FLAG_Wno_missing_declarations
-- Performing Test CHECK_CXX_FLAG_Wno_missing_declarations - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Do not build any example.
-- Configuring done
-- Generating done
-- Build files have been written to: /workspaces/third_party/ceres-solver/build

The whole compilation process is OK, the header files and libraries will be generated. However, the above example will report a error.

**Comment by sandwichmaker** [comment]
Thank you.

And you are using the stable version or the version at HEAD?

Can you also share the exact command line that's failing?

**Comment by sandwichmaker** [comment]
One thing I noticed is that cmake was told not to build any examples. Did
you turn it off manually?

**Comment by chjXu** [comment]
After I git clone the code, I manually checkout to version 2.2.0. Will this cause the above problem?

In addition, I manually turned off the BUILD_EXAMPLES option. In fact, this is my second attempt to compile the header files and libraries. When I compiled for the first time, the process of "make test" was all ok.

**Comment by chjXu** [comment]
Scanning dependencies of target test_ceres
[ 50%] Built target test_thirdparty
[ 75%] Building CXX object CMakeFiles/test_ceres.dir/test/test_ceres.cpp.o
/workspaces/test/test_ceres.cpp: In function ‘int main(int, char**)’:
/workspaces/test/test_ceres.cpp:69:60: error: no matching function for call to ‘ceres::AutoDiffCostFunction<CostFunctor, 1, 1>::AutoDiffCostFunction()’
   69 |         new ceres::AutoDiffCostFunction<CostFunctor, 1, 1>();
      |                                                            ^
In file included from /workspaces/third_party/ceres-solver-2.2.0/include/ceres/ceres.h:38,
                 from /workspaces/test/test_ceres.cpp:36:
/workspaces/third_party/ceres-solver-2.2.0/include/ceres/autodiff_cost_function.h:182:3: note: candidate: ‘ceres::AutoDiffCostFunction<CostFunctor, kNumResiduals, Ns>::AutoDiffCostFunction(ceres::AutoDiffCostFunction<CostFunctor, kNumResiduals, Ns>&&) [with CostFunctor = CostFunctor; int kNumResiduals = 1; int ...Ns = {1}]’
  182 |   AutoDiffCostFunction(AutoDiffCostFunction&& other)
      |   ^~~~~~~~~~~~~~~~~~~~
/workspaces/third_party/ceres-solver-2.2.0/include/ceres/autodiff_cost_function.h:182:3: note:   candidate expects 1 argument, 0 provided
/workspaces/third_party/ceres-solver-2.2.0/include/ceres/autodiff_cost_function.h:172:3: note: candidate: ‘ceres::AutoDiffCostFunction<CostFunctor, kNumResiduals, Ns>::AutoDiffCostFunction(CostFunctor*, int, ceres::Ownership) [with CostFunctor = CostFunctor; int kNumResiduals = 1; int ...Ns = {1}]’
  172 |   AutoDiffCostFunction(CostFunctor* functor,
      |   ^~~~~~~~~~~~~~~~~~~~
/workspaces/third_party/ceres-solver-2.2.0/include/ceres/autodiff_cost_function.h:172:3: note:   candidate expects 3 arguments, 0 provided
/workspaces/third_party/ceres-solver-2.2.0/include/ceres/autodiff_cost_function.h:159:12: note: candidate: ‘ceres::AutoDiffCostFunction<CostFunctor, kNumResiduals, Ns>::AutoDiffCostFunction(CostFunctor*, ceres::Ownership) [with CostFunctor = CostFunctor; int kNumResiduals = 1; int ...Ns = {1}]’
  159 |   explicit AutoDiffCostFunction(CostFunctor* functor,
      |            ^~~~~~~~~~~~~~~~~~~~
/workspaces/third_party/ceres-solver-2.2.0/include/ceres/autodiff_cost_function.h:159:12: note:   candidate expects 2 arguments, 0 provided
/workspaces/test/test_ceres.cpp:49:14: warning: unused parameter ‘argc’ [-Wunused-parameter]
   49 | int main(int argc, char** argv) {
      |          ~~~~^~~~
/workspaces/test/test_ceres.cpp:49:27: warning: unused parameter ‘argv’ [-Wunused-parameter]
   49 | int main(int argc, char** argv) {
      |                    ~~~~~~~^~~~
make[2]: *** [CMakeFiles/test_ceres.dir/build.make:63: CMakeFiles/test_ceres.dir/test/test_ceres.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:116: CMakeFiles/test_ceres.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by dolgae03** [comment]
Exactly Same problem as I met. Sorry for late response

I tried it on Mac OS.
and this is the 2.2.0 version. 

I also checked 2.2.0 version example is exactly same.

/Users/mskim/Desktop/workspace/gtsam_gnss_project/src_ceres/helloworld.cpp:59:11: error: no matching constructor for initialization of 'ceres::AutoDiffCostFunction<CostFunctor, 1, 1>'
      new ceres::AutoDiffCostFunction<CostFunctor, 1, 1>();
          ^
/opt/homebrew/include/ceres/autodiff_cost_function.h:182:3: note: candidate constructor not viable: requires single argument 'other', but no arguments were provided
  AutoDiffCostFunction(AutoDiffCostFunction&& other)
  ^
/opt/homebrew/include/ceres/autodiff_cost_function.h:154:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 0 were provided
class AutoDiffCostFunction final
      ^
/opt/homebrew/include/ceres/autodiff_cost_function.h:159:12: note: candidate constructor not viable: requires at least argument 'functor', but no arguments were provided
  explicit AutoDiffCostFunction(CostFunctor* functor,
           ^
/opt/homebrew/include/ceres/autodiff_cost_function.h:172:3: note: candidate constructor not viable: requires at least 2 arguments, but 0 were provided
  AutoDiffCostFunction(CostFunctor* functor,
  ^

**Comment by chjXu** [comment]
I have solved this issue by using the master branch. The version of 2.2.0 is different with the master branch after the make install.

**Comment by sandwichmaker** [comment]
I think what was happening is that the version of hello world you are usinh
requires and updated autodiffcostfunction which is on the master branch and
not part of 2.2.0

If you use the hello world that comes with 2.2.0 it will work too but
mixing 2.2.0 with the hello world from master branch will not work.

**Comment by dolgae03** [comment]
I checked, and you are right. I think I got some mistake to check. Thank you for your help.
