### ISSUE TITLE
undefined reference to `ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)'

### ISSUE THREAD

**Issue by BEI11HAI** [ceres-solver/ceres-solver#1094]
Hello, I'm trying to install ceres1.14.0 on ubuntu20.04, and after installing ceres, when I try to run an example given by ceres, in the 'make' step, I meet up with the following error:

/usr/bin/ld: CMakeFiles/ceres_example.dir/ceres_example.cpp.o: in function `main':
ceres_example.cpp:(.text+0xaa): undefined reference to `ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*)'
/usr/bin/ld: ceres_example.cpp:(.text+0xd9): undefined reference to `ceres::Solver::Summary::Summary()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ceres_example.dir/build.make:112：ceres_example] error 1
make[1]: *** [CMakeFiles/Makefile2:83：CMakeFiles/ceres_example.dir/all] error 2
make: *** [Makefile:91：all] error 2

After searching a lot on the Internet, I nearly didn't find any related issues, could you please help me out? thx!

**Comment by sandwichmaker** [comment]
This version of Ceres solver is multiple years old, please use a more
recent version.

**Comment by sandwichmaker** [comment]
also it is hard to debug this without looking at your code.

**Comment by sandwichmaker** [comment]
Closing because of lack of response or actionable information.
