### ISSUE TITLE
catkin_make compile and report an error

### ISSUE THREAD

**Issue by DoongLi** [ceres-solver/ceres-solver#1101]
I installed ceres with the following command:
git clone --recurse-submodules https://github.com/ceres-solver/ceres-solver
But when I compile another project (direct_visual_lidar_calibration) with catkin_make, an error occurred: 

catkin_make
Base path: /home/doongli/catkin_ws_LIDAR-SLAM
Source space: /home/doongli/catkin_ws_LIDAR-SLAM/src
Build space: /home/doongli/catkin_ws_LIDAR-SLAM/build
Devel space: /home/doongli/catkin_ws_LIDAR-SLAM/devel
Install space: /home/doongli/catkin_ws_LIDAR-SLAM/install
####
####
####
####
[  3%] Building CXX object direct_visual_lidar_calibration/CMakeFiles/direct_visual_lidar_calibration.dir/src/vlcal/calib/visual_camera_calibration.cpp.o
/home/doongli/catkin_ws_LIDAR-SLAM/src/direct_visual_lidar_calibration/src/vlcal/calib/visual_camera_calibration.cpp: In member function ‘Eigen::Isometry3d vlcal::VisualCameraCalibration::estimate_pose_bfgs(const Isometry3d&)’:
/home/doongli/catkin_ws_LIDAR-SLAM/src/direct_visual_lidar_calibration/src/vlcal/calib/visual_camera_calibration.cpp:215:104: error: no matching function for call to ‘ceres::AutoDiffFirstOrderFunction<vlcal::MultiNIDCost, 7>::AutoDiffFirstOrderFunction(vlcal::MultiNIDCost*&)’
  215 |   auto cost = new ceres::AutoDiffFirstOrderFunction<MultiNIDCost, Sophus::SE3d::num_parameters>(sum_nid);
      |                                                                                                        ^
In file included from /usr/local/include/ceres/ceres.h:39,
                 from /home/doongli/catkin_ws_LIDAR-SLAM/src/direct_visual_lidar_calibration/src/vlcal/calib/visual_camera_calibration.cpp:7:
/usr/local/include/ceres/autodiff_first_order_function.h:125:12: note: candidate: ‘template<class ... Args, std::enable_if_t<is_constructible_v<vlcal::MultiNIDCost, Args&& ...>, void>* <anonymous> > ceres::AutoDiffFirstOrderFunction<FirstOrderFunctor, kNumParameters>::AutoDiffFirstOrderFunction(Args&& ...)’
  125 |   explicit AutoDiffFirstOrderFunction(Args&&... args)
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/ceres/autodiff_first_order_function.h:125:12: note:   template argument deduction/substitution failed:
In file included from /usr/include/c++/9/bits/move.h:55,
                 from /usr/include/c++/9/bits/stl_pair.h:59,
                 from /usr/include/c++/9/bits/stl_algobase.h:64,
                 from /usr/include/c++/9/memory:62,
                 from /home/doongli/catkin_ws_LIDAR-SLAM/src/direct_visual_lidar_calibration/include/camera/generic_camera_base.hpp:3,
                 from /home/doongli/catkin_ws_LIDAR-SLAM/src/direct_visual_lidar_calibration/include/vlcal/calib/visual_camera_calibration.hpp:3,
                 from /home/doongli/catkin_ws_LIDAR-SLAM/src/direct_visual_lidar_calibration/src/vlcal/calib/visual_camera_calibration.cpp:1:
/usr/include/c++/9/type_traits: In substitution of ‘template<bool _Cond, class _Tp> using enable_if_t = typename std::enable_if::type [with bool _Cond = std::is_constructible_v<vlcal::MultiNIDCost, vlcal::MultiNIDCost*&>; _Tp = void]’:
/usr/local/include/ceres/autodiff_first_order_function.h:124:69:   required from here
/usr/include/c++/9/type_traits:2378:11: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
 2378 |     using enable_if_t = typename enable_if<_Cond, _Tp>::type;
      |           ^~~~~~~~~~~
In file included from /usr/local/include/ceres/ceres.h:39,
                 from /home/doongli/catkin_ws_LIDAR-SLAM/src/direct_visual_lidar_calibration/src/vlcal/calib/visual_camera_calibration.cpp:7:
/usr/local/include/ceres/autodiff_first_order_function.h:116:12: note: candidate: ‘ceres::AutoDiffFirstOrderFunction<FirstOrderFunctor, kNumParameters>::AutoDiffFirstOrderFunction(std::unique_ptr<_Tp>) [with FirstOrderFunctor = vlcal::MultiNIDCost; int kNumParameters = 7]’
  116 |   explicit AutoDiffFirstOrderFunction(
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/ceres/autodiff_first_order_function.h:117:42: note:   no known conversion for argument 1 from ‘vlcal::MultiNIDCost*’ to ‘std::unique_ptr<vlcal::MultiNIDCost, std::default_delete<vlcal::MultiNIDCost> >’
  117 |       std::unique_ptr<FirstOrderFunctor> functor)
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/usr/local/include/ceres/autodiff_first_order_function.h:111:3: note: candidate: ‘ceres::AutoDiffFirstOrderFunction<FirstOrderFunctor, kNumParameters>::AutoDiffFirstOrderFunction(ceres::AutoDiffFirstOrderFunction<FirstOrderFunctor, kNumParameters>&&) [with FirstOrderFunctor = vlcal::MultiNIDCost; int kNumParameters = 7]’
  111 |   AutoDiffFirstOrderFunction(AutoDiffFirstOrderFunction&& other) noexcept =
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/ceres/autodiff_first_order_function.h:111:59: note:   no known conversion for argument 1 from ‘vlcal::MultiNIDCost*’ to ‘ceres::AutoDiffFirstOrderFunction<vlcal::MultiNIDCost, 7>&&’
  111 |   AutoDiffFirstOrderFunction(AutoDiffFirstOrderFunction&& other) noexcept =
      |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
make[2]: *** [direct_visual_lidar_calibration/CMakeFiles/direct_visual_lidar_calibration.dir/build.make:284: direct_visual_lidar_calibration/CMakeFiles/direct_visual_lidar_calibration.dir/src/vlcal/calib/visual_camera_calibration.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:990: direct_visual_lidar_calibration/CMakeFiles/direct_visual_lidar_calibration.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Invoking "make -j20 -l20" failed

**Comment by sandwichmaker** [comment]
I think this is because there was a recent change to the API for first
order function. Your code is using the old API.

I recommend using the stable release of Ceres rather than the version at
head.

**Comment by sandwichmaker** [comment]
Closing because of lack of response. Please re-open if my suggestion did not solve your problem.
