### ISSUE TITLE
I need support!

### ISSUE THREAD

**Issue by IlyaYakovenko** [ceres-solver/ceres-solver#1103]
Hello!
Please help me to fugure out how to work with your library.
I have a model of the triangulated paper sheet. In have matrix V with coordinates of vertices of triangulation and matrix F with edges between vertices.
I need to change z coordinate of one vertex slightly, but if I do so edges, that connected to this vertex will strech.
Hower because I need simulate a sheet of paper, my edges shouldn't be streched.
So I need to fix x and y coordinate of other vertices. I was trying to do this using your library, but I faced some problems.
I used this steps: 
1) I have a system of functions, the number of which is equal to the number of edges, which function is difference between original length and current length
2) I tried to minimize all of them using AddResidualBlock, but this gave no results.

Please help me, to understand how I can do this task using your library!

**Comment by sandwichmaker** [comment]
Have you worked through the tutorial and read the example code?

**Comment by IlyaYakovenko** [comment]
Yes, I have tried, but still do not understand, how to apply it to my problem.

**Comment by sandwichmaker** [comment]
The description of your problem is very confusing. Can write it down
mathematically and share the code for it?

**Comment by sandwichmaker** [comment]
gentle ping?

**Comment by sandwichmaker** [comment]
Closing because of lack of response, feel free to re-open if you have more info.
