### ISSUE TITLE
How to convert ceres::solver code to tinysolver

### ISSUE THREAD

**Issue by lianggangMei** [ceres-solver/ceres-solver#1108]
Hi
Could you help to let me know how to replace ceres::solver  with tinysolver for the below code,  Thanks a lot!

#include <iostream>
#include <opencv2/core/core.hpp>
#include <ceres/ceres.h>

using namespace std;
using namespace cv;
using namespace ceres;

//y=3.5x^3+1.6x^2+0.3x+7.8
vector<double> xs;
vector<double> ys;

struct CostFunctor{
  
  double x_guan,y_guan;

  CostFunctor(double x,double y)
  {
    x_guan = x;
    y_guan = y;
  }
  

  template <typename T>
  bool operator()(const T* const params,T* residual)const
  {
    residual[0]=y_guan-(params[0]*x_guan*x_guan*x_guan+params[1]*x_guan*x_guan+params[2]*x_guan+params[3]);
    return true;  
  }
};

void generateData()
{
  RNG rng;
  double w_sigma = 1.0;
  for(int i=0;i<100;i++)
  {
    double x = i;
    double y = 3.5*x*x*x+1.6*x*x+0.3*x+7.8;
    xs.push_back(x);
    ys.push_back(y+rng.gaussian(w_sigma));
  }
  for(int i=0;i<xs.size();i++)
  {
    cout<<"x:"<<xs[i]<<" y:"<<ys[i]<<endl;
  }
}

int main(int argc, char **argv) {
  
  generateData();
  

  double params[4]={1.0};

  Problem problem;
  for(int i=0;i<xs.size();i++)
  {
    CostFunction* cost_function = new AutoDiffCostFunction<CostFunctor,1,4>(new CostFunctor(xs[i],ys[i]));
    problem.AddResidualBlock(cost_function,NULL,params);
  }
  

  Solver::Options options;

  options.linear_solver_type=ceres::DENSE_QR;

  options.minimizer_progress_to_stdout=true;
  
  Solver::Summary summary;
  

  Solve(options,&problem,&summary);

  cout<<summary.BriefReport()<<endl;
  
  cout<<"p0:"<<params[0]<<endl;
  cout<<"p1:"<<params[1]<<endl;
  cout<<"p2:"<<params[2]<<endl;
  cout<<"p3:"<<params[3]<<endl;
  return 0;
}

**Comment by lianggangMei** [comment]
Any update? Thanks!

**Comment by sandwichmaker** [comment]
have you looked at the example code?

**Comment by lianggangMei** [comment]
i saw the example code, but I understood it supports only one ResidualBlock: I want to implement the similar feature of "problem.AddResidualBlock(cost_function,NULL,params)", 

example code:
TEST(TinySolverAutoDiffFunction, ResidualsDynamicAutoDiff) {
  **Eigen::Vector3d x0(0.76026643, -30.01799744, 0.55192142);**

  DynamicResidualsFunctor f;
  using AutoDiffCostFunctor = ceres::
      TinySolverAutoDiffFunction<DynamicResidualsFunctor, Eigen::Dynamic, 3>;
  AutoDiffCostFunctor f_autodiff(f);

  Eigen::Vector2d residuals;
  f_autodiff(x0.data(), residuals.data(), nullptr);
  EXPECT_GT(residuals.squaredNorm() / 2.0, 1e-10);

  TinySolver<AutoDiffCostFunctor> solver;
  solver.Solve(f_autodiff, &x0);
  EXPECT_NEAR(0.0, solver.summary.final_cost, 1e-10);
}

**Comment by sandwichmaker** [comment]
TinySolver does not support multiple residual blocks.  If you are not using a loss function then you can combine all your residual blocks into a single cost function.

**Comment by lianggangMei** [comment]
To combine all residual blocks into a single cost function, could you help give me some code/advices for my above application.Thanks!

**Comment by lianggangMei** [comment]
Another tinysolver example, how will I modify the code:

#include <iostream>
#include <ceres/tiny_solver_autodiff_function.h>
#include <ceres/tiny_solver.h>
 
using namespace std;
using namespace ceres;
 
struct MyFunctor {
    template<typename T>
    bool operator()(const T* const parameters, T* residuals) const {
      const T& x = parameters[0];
      const T& y = parameters[1];
      const T& z = parameters[2];
      residuals[0] = x + 2.*y + 4.*z;
      residuals[1] = y * z;
      residuals[2] = T(10) - x;
      **//How to combine all parameters and residuals**
      return true;
    }
  };
 
 
int main(){
  using AutoDiffFunction = TinySolverAutoDiffFunction<MyFunctor, 3, 3>;
  MyFunctor my_functor;
  AutoDiffFunction f(my_functor);
 
  Eigen::Vector3d x1(3,4,5);
  **_//add more parameters here_**
   **Eigen::Vector3d x2(6,7,8);
 ...
   Eigen::Vector3d x2(100,101,102);**
  TinySolver<AutoDiffFunction> solver;
  solver.Solve(f, &x1);
  cout << x << endl;
  return 0;
}

**Comment by sandwichmaker** [comment]
I do not understand what your code is trying to do. Can you explain what is it that you are trying to do with TinySolver and why?

**Comment by lianggangMei** [comment]
My application is trying to do function fitting for y=3.5x^3+1.6x^2+0.3x+7.8,  it has high lattency with ceres::solver.
as you said in https://github.com/ceres-solver/ceres-solver/issues/532
"Last but not the least if low latency is really important to you (as opposed to throughput, which is what ceres is really designed for) I suggest using TinySolver in ceres."

**Comment by lianggangMei** [comment]
the above  tinysolver example is only pseudo code，you can ignore it.

**Comment by sandwichmaker** [comment]
What are you trying to fit? The  coefficients of the polynomial?

**Comment by lianggangMei** [comment]
@sandwichmaker please see the below code:

 #include <opencv2/core/core.hpp>
#include <ceres/ceres.h>

using namespace std;
using namespace cv;
using namespace ceres;

//y=3.5x^3+1.6x^2+0.3x+7.8
vector xs;
vector ys;

struct CostFunctor{

double x_guan,y_guan;

CostFunctor(double x,double y)
{
x_guan = x;
y_guan = y;
}

template
bool operator()(const T* const params,T* residual)const
{
residual[0]=y_guan-(params[0]x_guanx_guan*x_guan+params[1]x_guanx_guan+params[2]*x_guan+params[3]);
return true;
}
};

void generateData()
{
RNG rng;
double w_sigma = 1.0;
for(int i=0;i<100;i++)
{
double x = i;
double y = 3.5xxx+1.6xx+0.3x+7.8;
xs.push_back(x);
ys.push_back(y+rng.gaussian(w_sigma));
}
for(int i=0;i<xs.size();i++)
{
cout<<"x:"<<xs[i]<<" y:"<<ys[i]<<endl;
}
}

int main(int argc, char **argv) {

generateData();

double params[4]={1.0};

Problem problem;
for(int i=0;i<xs.size();i++)
{
CostFunction* cost_function = new AutoDiffCostFunction<CostFunctor,1,4>(new CostFunctor(xs[i],ys[i]));
problem.AddResidualBlock(cost_function,NULL,params);
}

Solver::Options options;

options.linear_solver_type=ceres::DENSE_QR;

options.minimizer_progress_to_stdout=true;

Solver::Summary summary;

Solve(options,&problem,&summary);

cout<<summary.BriefReport()<<endl;

cout<<"p0:"<<params[0]<<endl;
cout<<"p1:"<<params[1]<<endl;
cout<<"p2:"<<params[2]<<endl;
cout<<"p3:"<<params[3]<<endl;
return 0;
}

**Comment by lianggangMei** [comment]
I deleted the above tinysolver example, please see  ceres::solver code, Thanks!

**Comment by lianggangMei** [comment]
Any update? Thanks!

**Comment by sandwichmaker** [comment]
If all you are trying to do is fit a polynomial to data, you do not need to use ceres solver or tiny solver. 
You can just do one QR factorization or a Cholesky factorization and solve your problem.
Any polynomial fitting library should do, e.g. https://github.com/andviane/polynomial_regression

**Comment by lianggangMei** [comment]
In fact, out project app is complicated(not shown here).  but Fit a polynomial is only a demo for you. 
Or could you provide me a example of combining all residual blocks into a single cost function.  Then I can extend based on it .

**Comment by lianggangMei** [comment]
@sandwichmaker  is there a example of combining all residual blocks into a single cost function with tinysovler?

**Comment by lianggangMei** [comment]
?
