### ISSUE TITLE
how to print the report for tiny solver?

### ISSUE THREAD

**Issue by zhang-qiang-github** [ceres-solver/ceres-solver#1110]
For `ceres` optimation, it can print some information to show the details. For examples:

```
ceres::Solver::Options options;
options.linear_solver_type = ceres::LinearSolverType::DENSE_SCHUR;
options.minimizer_progress_to_stdout = true;
options.num_threads = 4;
ceres::Solver::Summary summary;
ceres::Solve(options, &problem, &summary);
std::cout << summary.FullReport() << "\n";
```

However, for `tiny solver`. The code would be:

```
TinySolver<AutoDiffCostFunctor> solver;
solver.Solve(f_autodiff, &x0);
```

How to use `options.minimizer_progress_to_stdout = true` and `std::cout << summary.FullReport() << "\n"` for `TinySolver`? Any suggestion is appreciated~~~

**Comment by sandwichmaker** [comment]
There is no such method for TinySolver. However, TinySolver has a summary struct 
https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/tiny_solver.h#L179
which contains some of the information that you want.
