### ISSUE TITLE
Build error with cudSS

### ISSUE THREAD

**Issue by mattiasmar** [ceres-solver/ceres-solver#1125]
The below is a standard CUDA dockerfile with cudSS installed on top. When compiling ceres as part of it this error is generated:
```
`
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/cudss/cudss-targets.cmake:94 (message):
  The imported target "cudss" references the file

     "/usr/lib/x86_64-linux-gnu/./libcudss.so.0.3.0"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/x86_64-linux-gnu/cmake/cudss/cudss-targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/cudss/cudss-config.cmake:134 (include)
  CMakeLists.txt:355 (find_package)

`
```
**Dockerfile:**
````
ARG UBUNTU_VERSION=22.04
ARG NVIDIA_CUDA_VERSION=12.4.1
FROM nvidia/cuda:${NVIDIA_CUDA_VERSION}-devel-ubuntu${UBUNTU_VERSION} 

# Prevent stop building ubuntu at time zone selection.
ENV DEBIAN_FRONTEND=noninteractive

# Prepare and empty machine for building.
RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
    wget \ 
    vim \
    tmux \
    qtbase5-dev \
    python3.10-venv \
    python3-pip \
    python3 \
    nvidia-cuda-toolkit-gcc- \
    ninja-build \
    nano \ 
    libtbb-dev \
    libsuitesparse-dev \
    libsqlite3-dev \
    libqt5svg5-dev \
    libqt5opengl5-dev \
    libmetis-dev \
    libgtest-dev \
    libgoogle-glog-dev \
    libgmock-dev \
    libglew-dev \
    libgflags-dev \
    libfreeimage-dev \
    libflann-dev \
    libeigen3-dev \
    libcgal-dev \
    libboost-system-dev \
    libboost-program-options-dev \
    libboost-graph-dev \
    libboost-filesystem-dev \
    libboost-all-dev \
    libatlas-base-dev \
    git \
    cmake \
    build-essential 
    
WORKDIR /ceres
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
RUN  dpkg -i cuda-keyring_1.1-1_all.deb
RUN  apt-get update && apt-get -y install cudss

RUN apt-get update && \
    apt-get install -y --no-install-recommends libtbb-dev


RUN git clone --recurse-submodules https://github.com/ceres-solver/ceres-solver && \
    cd ceres-solver && \
    mkdir build && \
    cd build && \
    cmake .. -DBUILD_TESTING=ON -DBUILD_EXAMPLES=ON -DCMAKE_CUDA_ARCHITECTURES=70 && \
    make  && make install
`
```

**Comment by sergiud** [comment]
The error does not come from Ceres but from cuDSS directly. Your cuDSS installation is likely broken.

**Comment by mattiasmar** [comment]
Interesting. I just followed the instructions on NVIDIA's [web](https://developer.nvidia.com/cudss-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_network). I tried both the local and network installer.

Any suggestions? Do you know which previous installer version does work or if the cudSS should be done differently than what is expressed in the Dockerfile above?

**Comment by mattiasmar** [comment]
P.s. The cudss so file is found here:

```
 find / -name "libcudss.so*"
/usr/lib/x86_64-linux-gnu/libcudss/12/libcudss.so
/usr/lib/x86_64-linux-gnu/libcudss/12/libcudss.so.0.3.0
/usr/lib/x86_64-linux-gnu/libcudss/12/libcudss.so.0
/usr/lib/x86_64-linux-gnu/libcudss.so
/usr/lib/x86_64-linux-gnu/libcudss.so.0
/etc/alternatives/libcudss.so

```

**Comment by sergiud** [comment]
We use [this](https://github.com/ceres-solver/ceres-solver/blob/c29b5257e23f91d6a47c4db9d57350ed4985ea46/.github/workflows/linux.yml#L86-L88) setup in our Github workflow.

> P.s. The cudss so file is found here:
> 
> ```
>  find / -name "libcudss.so*"
> /usr/lib/x86_64-linux-gnu/libcudss/12/libcudss.so
> /usr/lib/x86_64-linux-gnu/libcudss/12/libcudss.so.0.3.0
> /usr/lib/x86_64-linux-gnu/libcudss/12/libcudss.so.0
> /usr/lib/x86_64-linux-gnu/libcudss.so
> /usr/lib/x86_64-linux-gnu/libcudss.so.0
> /etc/alternatives/libcudss.so
> ```


The `/usr/lib/x86_64-linux-gnu/./libcudss.so.0.3.0` symlink is clearly missing. You could try creating one yourself:

```bash
cd /usr/lib/x86_64-linux-gnu/
ln -s libcudss.so libcudss.so.0.3.0
```

**Comment by mattiasmar** [comment]
Right. Just noticed that:
The default installation goes to a subfolder ("12"); /usr/lib/x86_64-linux-gnu/libcudss/12 rather than just /usr/lib/x86_64-linux-gnu/libcudss

**Comment by mattiasmar** [comment]
Ceres compilation completes when mapping /usr/lib/x86_64-linux-gnu/libcudss to /usr/lib/x86_64-linux-gnu/libcudss/12

**Comment by mattiasmar** [comment]
cmake reports:
```
-- Enabling CERES_NO_CUDSS in Ceres config.h
-- Enabling CERES_NO_ACCELERATE_SPARSE in Ceres config.h
```

What does that mean? Would CUDSS be supported or not in this case?
I use the build flags:
` cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=ON -DCMAKE_CUDA_ARCHITECTURES=70`

**Comment by sergiud** [comment]
CMake was not able to locate cuDSS in the initial run, hence the support was disabled. Either remove the build directory or reinitialize it using the `--fresh` CMake option.

**Comment by sergiud** [comment]
The following output indicates again a broken cuDSS setup:
```console
/lib/x86_64-linux-gnu/cmake/cudss/cudss-config.cmake, version: unknown
```
The cuDSS package config version is not reported which makes the package unusable. Typically, the corresponding version is specified in an accompanying file `cudss-config-version.cmake` which seems to be missing.

**Comment by mattiasmar** [comment]
Bottom line:
This `CMakeLists.txt` below demonstrates the problem: By setting the specific cudss version in Ceres the build fails (because the specific cudss version cannot be identified). This is surprising as in the cudds cmake file `libcudss-linux-x86_64-0.3.0.9_cuda12-archive/lib/cmake/cudss/cudss-config.cmake` the version IS set:

(Line 41): `cudss set(cudss_VERSION 0.3.0) `

Example CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.22)
project(YourProjectName)
# Add this line to find and require the cudss package
find_package(cudss 0.3.0 REQUIRED)
```

**Comment by sergiud** [comment]
As previously noted, `cudss-config-version.cmake` is missing which makes it impossible for CMake to determine the package version. Setting `cudss_VERSION` in `cudss-config.cmake` is not sufficient.

Essentially, this is an upstream issue not a Ceres one. We need to detect compatible cuDSS versions somehow.

As a temporary workaround, you could remove the version from `find_dependency` call [here](https://github.com/ceres-solver/ceres-solver/blob/c29b5257e23f91d6a47c4db9d57350ed4985ea46/CMakeLists.txt#L357). However, I suggest reporting the problem to NVIDIA as the versioning support needs to be fixed in cuDSS.

**Comment by mattiasmar** [comment]
Thanks @sergiud for your help.
This is my solution for the time being:

```
ENV cudss_DIR /ceres/libcudss-linux-x86_64-0.3.0.9_cuda12-archive/lib/cmake/cudss
ENV LD_LIBRARY_PATH /ceres/libcudss-linux-x86_64-0.3.0.9_cuda12-archive/lib/:$LD_LIBRARY_PATH
RUN git clone --recurse-submodules https://github.com/ceres-solver/ceres-solver  && \
    sed -i 's/\${cudss_VERSION}//g' ceres-solver/CMakeLists.txt && cd ceres-solver && \
    mkdir build && \
    cd build && \
    cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=ON -DCMAKE_CUDA_ARCHITECTURES=native -DCMAKE_CUDA_COMPILER=$(which nvcc) && \
    make -j && make install
```

**Comment by DevinBayly** [comment]
@mattiasmar did you manage to complete the colmap build step after the ceres-solver build with this current solution? I'm getting stuck on absl and gtest dependency issues which are third party libraries provided in the ceres-solver repo that aren't visible when I focus on building the colmap repo.

In other words, would you let me know if you don't end up with this error building colmap?
```
-- Found cudss: (Version:0.3.0
               CMakePackageDir:/usr/lib/x86_64-linux-gnu/cmake/cudss
               IncludeDir:/usr/include
               LibraryDir:/usr/lib/x86_64-linux-gnu/.
               ComponentsFound:[cudss])
CMake Error at /usr/share/cmake-3.22/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Found package configuration file:

    /usr/local/lib/cmake/absl/abslConfig.cmake

  but it set absl_FOUND to FALSE so package "absl" is considered to be NOT
  FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  GTest::gmock

Call Stack (most recent call first):
  /usr/local/lib/cmake/Ceres/CeresConfig.cmake:197 (find_dependency)
  cmake/FindDependencies.cmake:41 (find_package)
  CMakeLists.txt:107 (include)

```

**Comment by mattiasmar** [comment]
@DevinBayly You avoid this error by cloning also the submodules:
`git clone --recurse-submodules https://github.com/ceres-solver/ceres-solver `
`git clone  --recurse-submodules https://github.com/colmap/colmap.git`

**Comment by DevinBayly** [comment]
I definitely needed to do that to build the ceres-solver so good point, but when I get these errors from the colmap repo build I wasn't sure they were related to a missing submodule.

I'm giving that another try either way.

**Comment by DevinBayly** [comment]
yea my colmap repo build still shows the same error as what I posted. 

Can I ask you what your cmake build command is for the colmap repo? It sounds like you made this work. If it's easier maybe the full docker build file so I can see how it works in context with everything else?

thanks for trying to help me out!

**Comment by DevinBayly** [comment]
forgot to go with @mattiasmar , but I know everyone's busy so perhaps I'll go ahead and make a new issue if I don't hear back next week.

**Comment by morita-koki** [comment]
I had same problem. I resolved it by adding option 

> -DBUILD_TESTING=OFF

 when building ceres-solver

**Comment by mattiasmar** [comment]
@DevinBayly 

```
WORKDIR /ceres
RUN wget https://developer.download.nvidia.com/compute/cudss/redist/libcudss/linux-x86_64/libcudss-linux-x86_64-0.3.0.9_cuda12-archive.tar.xz && \
    tar -xf libcudss-linux-x86_64-0.3.0.9_cuda12-archive.tar.xz  
ENV cudss_DIR /ceres/libcudss-linux-x86_64-0.3.0.9_cuda12-archive/lib/cmake/cudss
ENV LD_LIBRARY_PATH /ceres/libcudss-linux-x86_64-0.3.0.9_cuda12-archive/lib/:$LD_LIBRARY_PATH
RUN git clone --recurse-submodules https://github.com/ceres-solver/ceres-solver 
RUN sed -i 's/\${cudss_VERSION}//g' ceres-solver/CMakeLists.txt && cd ceres-solver && \
    mkdir build && \
    cd build && \
    cmake .. -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=ON -DCMAKE_CUDA_ARCHITECTURES=70 && \
    make -j && make install
  

# Build and install COLMAP.
WORKDIR /colmap
RUN git clone  --recurse-submodules https://github.com/colmap/colmap.git && cd colmap && \
    git fetch https://github.com/colmap/colmap.git ${COLMAP_GIT_COMMIT} && \
    git checkout FETCH_HEAD && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_CUDA_ARCHITECTURES=${CUDA_ARCHITECTURES} \
        -DCMAKE_INSTALL_PREFIX=/colmap-install && \
    make -j && make install

ENV PATH=/colmap-install/bin:${PATH}

WORKDIR /hloc
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN python3 -m pip install --upgrade setuptools==58.0.4 
RUN python3 -m venv /hloc/venv

RUN . /hloc/venv/bin/activate &&  pip install scikit-learn pyyaml  ruff pyyaml  
RUN . /hloc/venv/bin/activate && cd /colmap/colmap && pwd && ls && python3 -m pip install ./pycolmap/
# Clone and set up Hierarchical-Localization
RUN git clone --recursive https://github.com/cvg/Hierarchical-Localization/
RUN . /hloc/venv/bin/activate &&  cd Hierarchical-Localization/ && python3 -m pip install --upgrade setuptools && python3 -m pip install --no-build-isolation -e .

```

**Comment by DevinBayly** [comment]
> I had same problem. I resolved it by adding option
> 
> > -DBUILD_TESTING=OFF
> 
> when building ceres-solver

TY @morita-koki , I'll give this a test, and then I'll try out your dockerfile @mattiasmar 

you're making my setup for the spring all come true.

**Comment by DevinBayly** [comment]
Yes, it's working! Thanks so much!
