### ISSUE TITLE
Numeric differentiation should pay attention to the local parameterization of parameters when generating perturbations

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#139]
Original [issue 138](https://code.google.com/p/ceres-solver/issues/detail?id=138) created by sandwichmaker on 2013-11-19T20:03:36.000Z:

Title says it all.

**Comment by sandwichmaker** [comment]
@alexsmac and @keir I am wondering if I should just mark this as something to be wary of in the documentation for now. Fixing this requires making NumericDiffCostFunction be aware of the local parameterization associated with each of its parameter blocks and well that is a large amount of pain and API work for what is decidedly a corner case.

**Comment by alexsmac** [comment]
+1 for adding documentation on this, but otherwise punting.

**Comment by sandwichmaker** [comment]
https://ceres-solver-review.googlesource.com/#/c/6411/ addresses this.
