### ISSUE TITLE
FIND_PACKAGE(Eigen ${CERES_EIGEN_VERSION} EXACT QUIET) seems unnecessarily harsh.

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#155]
Original [issue 154](https://code.google.com/p/ceres-solver/issues/detail?id=154) created by sandwichmaker on 2015-01-16T10:16:51.000Z:

I'm using MacPorts and Ceres was built with Eigen 3.2.2 but Eigen has been updated to 3.2.3.

I get the error message:

CMake Error at /opt/local/share/Ceres/CeresConfig.cmake:85 (MESSAGE):
  Failed to find Ceres - Missing required Ceres dependency: Eigen version
  3.2.2, please set EIGEN_INCLUDE_DIR.

Is the keyword EXACT necessary. I realise Eigen ABI *could* change between versions, but are there places where Eigen objects are passed between user code and (not templated or inlined) Ceres code?

**Comment by alexsmac** [comment]
This issue has come up in various forms on the mailing list.  As explained by Keir recently (see link below), we are strict about the Eigen version matching to avoid One-Definition-Rule violations with external linkage Eigen objects which could otherwise cause lots of subtle bugs.

https://groups.google.com/d/msg/ceres-solver/o8W95uEjOGQ/iG_9exnEvN4J

**Comment by ahundt** [comment]
Can you remove "QUIET" then?

the error is much easier to figure out with quiet removed:

-- Could NOT find Eigen: Found unsuitable version "3.2.4", but required is exact version "3.2.3" (found /usr/local/include/eigen3)
CMake Error at /usr/local/share/Ceres/CeresConfig.cmake:85 (MESSAGE):
  Failed to find Ceres - Missing required Ceres dependency: Eigen version
  3.2.3, please set EIGEN_INCLUDE_DIR.

**Comment by alexsmac** [comment]
Removing QUIET would break user code where Ceres is an optional dependency, as it would mean the QUIET in a find_package(Ceres QUIET) invocation would not be respected.

We have however updated the message output via CERES_REPORT_NOT_FOUND() in master for this case to make it clearer what has happened, and why this is an issue which should make things clearer.
