### ISSUE TITLE
Shlwapi should be used by gflags if available for WIN32.

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#156]
Shlwapi library is used by gflags if available, as mentioned in the FindGflags.cmake file. But the check is only done for MSVC compiler and not for WIN32. But gflags uses this library also when building with mingw-w64. The cmake file should be modified to handle this.

**Comment by alexsmac** [comment]
Should be fixed in: https://ceres-solver-review.googlesource.com/6440

**Comment by alexsmac** [comment]
https://ceres-solver-review.googlesource.com/6440 is now merged into master, as this is the same patch confirmed by Simeon (the reporter) as fixing the issue, I'm going to go ahead and close this out.
