### ISSUE TITLE
small_blas_test fails on i686 architecture

### ISSUE THREAD

**Issue by nocnokneo** [ceres-solver/ceres-solver#158]
It looks like the computed value differs from the expected expected by just a little more than the current tolerance threshold. See build log:

http://koji.fedoraproject.org/koji/getfile?taskID=9403521&name=build.log

**Comment by sandwichmaker** [comment]
we just increased this value further.

https://ceres-solver.googlesource.com/ceres-solver/+/c8eeaf4ad9008c8bcf9d22b96cd1a64fe9ead4c8

That should fix this problem.

Sameer

**Comment by nocnokneo** [comment]
Thanks!
