### ISSUE TITLE
covariance_test fails (crashes) on RHEL7, ppc64 architecture

### ISSUE THREAD

**Issue by nocnokneo** [ceres-solver/ceres-solver#159]
See build log at:
https://kojipkgs.fedoraproject.org//work/tasks/4538/9414538/build.log

This is with release 1.10.0.

Note that everything builds/passes on x86_64 architecture:
https://kojipkgs.fedoraproject.org//work/tasks/4537/9414537/build.log

**Comment by nocnokneo** [comment]
Ya, I saw that but figured I'd start with a ceres-solver bug report in case it was maybe due to invalid usage of Eigen. If it turns out to be a bug in Eigen itself, we can pass on the bug report to the Eigen team. Thanks for looking into it.

**Comment by sandwichmaker** [comment]
anyhope of getting access to a ppc machine so that I can poke at it?

**Comment by r4f4** [comment]
Hi,
you can request access to a ppc machine through this link https://fit-rhlab.rhcloud.com/powerlinux-openpower-development-hosting/.

Please, let me know in case you have any problems.

**Comment by sandwichmaker** [comment]
@nocnokneo is this still a problem?

**Comment by sandwichmaker** [comment]
Closing and will deal with new issues on more recent issues.
