### ISSUE TITLE
Uninitialized pointer being used in dense jacobian writer

### ISSUE THREAD

**Issue by mvitus** [ceres-solver/ceres-solver#162]
I might be missing something, but I think there is a bug in the [dense jacobian writer](https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/dense_jacobian_writer.h#L73).

If the jacobian is equal to NULL, then it seems ```dense_jacobian``` is left uninitialized, but it is later used on line 96.

**Comment by sandwichmaker** [comment]
Michael,
Write is guaranteed to be called with non-null Jacobian. The code in question is badly written and seems to imply that a null pointer maybe input. Thats not possible.  I have modified the code to be a bit simpler and less confusing.

https://ceres-solver-review.googlesource.com/#/c/6551/

**Comment by mvitus** [comment]
@sandwichmaker I assumed it was fine, but the code was awkward and generating warnings on android.  Thank you for the fast upstream fix!
