### ISSUE TITLE
FindEigen.cmake does not detect eigen3 directory on Windows

### ISSUE THREAD

**Issue by bvanevery** [ceres-solver/ceres-solver#163]
I'm using Windows 7, Visual Studio 2013 Community Edition, CMake 3.2.3, ceres-solver from github repository.  My Eigen installation is in the standard place for a 64-bit Windows system, "C:/Program Files/Eigen".  FindEigen.cmake should be able to identify the "C:/Program Files/Eigen/include/eigen3" directory without problem, as it is trivially easy to find, but it does not.  The file contains a comment, "# TODO: Add standard Windows search locations for Eigen."  Although that may not be the source of the error, it seems reasonable to take it at face value.  

This bug is easily worked around by manually specifying the directory in the CMake GUI interface.  However, it is also the very 1st impression of the ceres-solver build, this failure to do the trivial.  Hopefully you will be interested in correcting Find*.cmake modules so that they do what they should on Windows.  Below is the CMake output.  I don't know if anyone else has reported this bug.  But if people haven't reported it, possibly they are just "following along" with your error message and dutifully adding an EIGEN_INCLUDE_DIR path.  But like I said, a Find*.cmake module is supposed to find stuff, especially if it's trivial stuff....

Sorry for the tone... just went through a debate about this with a downstream consumer / borrower of your FindEigen.cmake module.

CMake Error at cmake/FindEigen.cmake:77 (MESSAGE):
  Failed to find Eigen - Could not find eigen3 include directory, set
  EIGEN_INCLUDE_DIR to path to eigen3 include directory, e.g.
  /usr/local/include/eigen3.
Call Stack (most recent call first):
  cmake/FindEigen.cmake:115 (EIGEN_REPORT_NOT_FOUND)
  CMakeLists.txt:263 (FIND_PACKAGE)

Configuring incomplete, errors occurred!
See also "C:/Users/BVANEVRY/devel/build/ceres-solver/CMakeFiles/CMakeOutput.log".

**Comment by alexsmac** [comment]
Ben, please try this CL: https://ceres-solver-review.googlesource.com/6811

**Comment by alexsmac** [comment]
Ben can you confirm if the CL fixes your issue? - thanks

**Comment by bvanevery** [comment]
It works!

**Comment by sandwichmaker** [comment]
CL is in at master.
