### ISSUE TITLE
Ceres can't be built as a git submodule

### ISSUE THREAD

**Issue by chris-cooper** [ceres-solver/ceres-solver#164]
Hi,

If you bring in Ceres as a git submodule on another project it can no longer be built.  To repro...

    mkdir test
    cd test
    git init .
    git submodule add https://github.com/ceres-solver/ceres-solver.git
    cd ceres-solver
    mkdir build
    cd build
    cmake ..

this gives...

    -- Configuring incomplete, errors occurred!

This seems related to references to .git as a directory in [CMakeLists.txt](https://github.com/ceres-solver/ceres-solver/blob/master/CMakeLists.txt#L44) (.git is a file when Ceres is a submodule).

**Comment by alexsmac** [comment]
Chris, please can you try this CL: https://ceres-solver-review.googlesource.com/#/c/6812/

**Comment by chris-cooper** [comment]
Thanks Alex.  I've tested using the repro above and also in OpenDroneMap and the CL works in both cases.

**Comment by sandwichmaker** [comment]
CL is submitted. Marking as closed.
