### ISSUE TITLE
FindGflags.cmake does not detect gflags directory on Windows

### ISSUE THREAD

**Issue by bvanevery** [ceres-solver/ceres-solver#165]
I'm using Windows 7, Visual Studio 2013 Community Edition, CMake 3.2.3, ceres-solver from github repository. My gflags installation is in the standard place for a 64-bit Windows system, "C:/Program Files/gflags". FindGflags.cmake should be able to identify the directory without problem, as it is trivially easy to find, but it does not. The file contains a comment, "# TODO: Add standard Windows search locations for gflags." Although that may not be the source of the error, it seems reasonable to take it at face value.

The problem can be worked around by manually specifying the gflags include and library locations in the CMake GUI.

**Comment by alexsmac** [comment]
Ben, please try this CL: https://ceres-solver-review.googlesource.com/#/c/6802/3

**Comment by alexsmac** [comment]
Ben can you confirm if the CL fixes your issue? - thanks

**Comment by bvanevery** [comment]
Unfortunately it now seems to be starting a search from my
build/ceres-solver directory, and inappropriately detecting a ../gflags
directory.  I don't know if that's your implemented behavior or a standard
CMake FIND behavior, to search a parallel directory.  I call it either a
bug or total misfeature.  I have all kinds of build directories under
/build, for all sorts of projects, that rightly speaking have nothing to do
with each other.  Worse, they may be slightly different builds of the same
software, and fishing out stuff from them would make a real mess.

The directory that should be detected, is C:\Program Files\gflags .  The
CMake configuration files are located at C:\Program Files\gflags\CMake .  I
don't see anything hardwired into the files that would refer back to
C:\Users\bvanevry\devel\build\gflags , so it may be an error in which
particular variable is used to get a directory prefix.  If those *.cmake
files are even being used at all.  I honestly haven't tried to figure out
the program flow.

**Comment by alexsmac** [comment]
@bvanevery, please try the updated patch: https://ceres-solver-review.googlesource.com/#/c/6802/5

This is down to the order of precedence in CMake's [find_package()](http://www.cmake.org/cmake/help/v2.8.12/cmake.html#command:find_package), specifically, items #6 & #7 in the search order; not Ceres.  By default, package build directories exported using CMake's export() are searched first (#6) by find_package() and the system install locations specified in CMAKE_SYSTEM_PREFIX_PATH are searched next (#7), and gflags exports its build directory in addition to being optionally installed.

On Linux & OS X, where the typical install path of /usr/local is usually on the PATH environment variable which is searched even earlier (#4), installed versions of gflags are usually detected first.  However, on Windows as there isn't a PATH var, this is not the case.

The latest version of the CL explicitly searches for installed packages in precedence to exported package build directories.

**Comment by bvanevery** [comment]
I'm confused as to the policy result.  Because I'm not that skilled at Git,
I nuked my tree, cloned the repository again, and then did git pull
https://ceres-solver.googlesource.com/ceres-solver refs/changes/02/6802/5
.  The resulting code still looks in my parallel user build directory for
gflags, not in C:\Program Files\gflags .  In fact, now it's looking in a
place it *really* shouldn't look.  My w64 subdirectory is for mingw-w64
based builds only, and is completely incompatible with the VS2013 build I'm
currently trying to do.

No preference for use of exported gflags CMake configuration set, and no
hints for include/library directories provided. Defaulting to preferring an
installed/exported gflags CMake configuration if available.

Found installed version of gflags: C:/Users/BVANEVRY/devel/build/w64/gflags

Detected gflags version: 2.2.0

Found Gflags: C:/Users/BVANEVRY/devel/build/w64/gflags/Include

-- Found Google Flags header in:
C:/Users/BVANEVRY/devel/build/w64/gflags/Include, in namespace: google


Personally I think if the user expresses "no preference", one should not be
defaulting to installed / exported CMake configuration files, as I think
that invites chaos.  Rather, if there's no preference, libs should be
identified in an extremely predictable and deterministic way.  i.e. look in
standard installation directories first.  On Unix that would be like
looking for usr/include or usr/local/include first.  On Windows it's
%HOMEDRIVE%\Program Files, then %HOMEDRIVE%\Program Files (x86) .

**Comment by bvanevery** [comment]
On Sun, Jul 12, 2015 at 7:36 PM, Brandon Van Every <bvanevery@gmail.com>
wrote:

>
> Personally I think if the user expresses "no preference", one should not
> be defaulting to installed / exported CMake configuration files, as I think
> that invites chaos.
>

Actually I've realized that CMake configuration files have nothing to do
with it.  find_path is aggressively looking in directories parallel to the
build directory, before looking in C:\Program Files .  I say that's a bug.
I wonder if other people in the CMake universe consider it a feature.

**Comment by alexsmac** [comment]
@bvanevery please can you try this patch: https://ceres-solver-review.googlesource.com/#/c/6802/6

I think the problem with the last patch was that projects built recently with the CMake GUI are searched preferentially to installed & exported libraries, which is why your other gflags directories were getting picked up.

You could also clear out your local CMake package registry: HKEY_CURRENT_USER\Software\Kitware\CMake\Packages\gflags directory, it will contain files with SHA code (esque) filenames, each of which contain the path to a gflags build directory (as gflags exports itself).  This *should* ensure that they won't be picked up by other projects, although the preferential searching of projects build with the CMake GUI might still remain, I suspect there is an option in it somewhere to trash (selectively) what projects are remembered.

**Comment by bvanevery** [comment]
I cloned ceres-solver and then pulled your changes, since I'm still a Git cripple about merge conflicts.  I nuked my build directory.  Gflags is now correctly identified at  C:/Program Files/gflags/Include !

I did not change the Windows registry in any way, nor do I feel that anyone ever should.  I really hope that is not considered standard, typical, and accepted CMake behavior nowadays.  If so, that's actively promoting a build system version of DLL Hell.

**Comment by alexsmac** [comment]
The CL has now been merged into master.

I'm not a Windows user, but the local CMake package registry (which is ~/.cmake/packages on *nix) is where CMake always stores exported build directories.  It can definitely be necessary sometimes to remove legacy builds from here, and users are intended to be able do this.

The key benefit of exporting a build directory is not having to install (e.g to a system location like /usr/local) to use a project, the local CMake package registry is meant to be a user-specific scratch space for tracking available projects.

As I'm not a Windows user, I don't know whether: HKEY_CURRENT_USER\Software\Kitware\CMake\Packages is a good analogue of: ~/.cmake/packages, but it is meant to be.
