### ISSUE TITLE
FindGflags.cmake does not detect gflags namespace on Windows

### ISSUE THREAD

**Issue by bvanevery** [ceres-solver/ceres-solver#166]
I'm using Windows 7, Visual Studio 2013 Community Edition, CMake 3.2.3, ceres-solver from github repository.  I'm using a current, stock gflags 2.1.2 from its github repository.  My gflags installation is in the standard place for a 64-bit Windows system, "C:/Program Files/gflags".  Assuming one manually specifies the location of the gflags include directory and library file, gflags namespace detection is attempted.  However on Windows it fails.  I suspect that gflags has changed and the namespace testing is now inadequate.

Performing Test GFLAGS_IN_GOOGLE_NAMESPACE_RELEASE
Performing Test GFLAGS_IN_GOOGLE_NAMESPACE_RELEASE - Failed
Performing Test GFLAGS_IN_GFLAGS_NAMESPACE_RELEASE
Performing Test GFLAGS_IN_GFLAGS_NAMESPACE_RELEASE - Failed
Performing Test GFLAGS_IN_GOOGLE_NAMESPACE_DEBUG
Performing Test GFLAGS_IN_GOOGLE_NAMESPACE_DEBUG - Failed
Performing Test GFLAGS_IN_GFLAGS_NAMESPACE_DEBUG
Performing Test GFLAGS_IN_GFLAGS_NAMESPACE_DEBUG - Failed
Failed to find gflags namespace using using check_cxx_source_compiles(), trying namespace regex instead, this is expected on Windows.
-- Failed to find gflags - Failed to extract valid gflags namespace from header file: C:/Program Files/gflags/Include/gflags/gflags.h, result: GFLAGS is not google or gflags.
-- Failed to find gflags - Failed to determine gflags namespace either by check_cxx_source_compiles(), or namespace regex.
Could NOT find Gflags (missing:  GFLAGS_INCLUDE_DIRS GFLAGS_LIBRARIES GFLAGS_NAMESPACE) 
-- Did not find Google Flags (gflags), Building without gflags - no tests or tools will be built!

**Comment by alexsmac** [comment]
Ben, this should also be fixed in this CL: https://ceres-solver-review.googlesource.com/#/c/6802/3

The check_cxx_source_compiles() tests fail on Windows due to a bug in how CMake & msbuild interact when CMake performs a try_compile().  The regex method in master currently fails with the latest version of gflags as the point at which the gflags namespace is defined has changed (although the default has now gone back to google).  The CL above should fix the regex method (and other things).

**Comment by alexsmac** [comment]
Ben can you confirm if the CL fixes your issue? - thanks

**Comment by bvanevery** [comment]
Who is Ben?  Do you mean me?

**Comment by alexsmac** [comment]
@bvanevery - yes I meant you, I misread your handle originally.

**Comment by bvanevery** [comment]
Namespace "google" is now detected.  I suppose that's correct for the stock
build.  Their notions of "primary" and "secondary" namespaces are confusing.

**Comment by alexsmac** [comment]
The CL has now been merged into master.
