### ISSUE TITLE
Improve the polynomial solvers 

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#168]
The current implementation of polynomial solvers used by the dogleg and line search routines is based on a mix of analytic formulae for up to quadratic equations and then a companion matrix based solver.

The companion matrix based solver is slow, because it requires the solution of an eigenvalue problem. Since the equations we are solving only involve a quartic of lower, it should be replaced by a numerically stable analytic solver.

This should be done for the cubic equation too. Further, the implementation of the quadratic solver can be improved too. Currently it uses the rather naive quadratic formula which is known to be not particularly numerically stable.

**Comment by sweeneychris** [comment]
I'd be happy to take a stab at this if you're not already working on it. I have closed-form quadratic, cubic, and quartic solvers in my SfM library: https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/math/closed_form_polynomial_solver.cc

Not saying to copy/paste that code but it could be used as a reference for the new solvers.

I also have general polynomial solvers like Sturm bracketing, but I have found that these (Sturm in particular) are not very stable.

**Comment by sandwichmaker** [comment]
Thanks Chris. I am not working on it yet. 

First it is not clear to me what the best methods are for cubic and the quartic equations. The interwebs say conflicting things.

http://scicomp.stackexchange.com/questions/3202/solution-of-quartic-equation

For quadratic there seems be agreement that the method  you use in your code is the way to go. 

So,  since the entire exercise is aimed at improving numerical and runtime performance, I'd like to start this effort by adding some tests where the existing routines do not do very well and then systematically replace them.

We can start by doing the quadratic solver first as an example and then move up.

Also it is not clear to me what the best methods are for the cubic and the quartic equations. The interwebs say conflicting things.

http://scicomp.stackexchange.com/questions/3202/solution-of-quartic-equation

 For quadratic there seems be agreement that the method

**Comment by sweeneychris** [comment]
What about closed form solvers for degree 2 - 4 along with a root polishing step using Laguerre's method? Seems like an appropriate combination of speed and numerical stability/accuracy

**Comment by sandwichmaker** [comment]
Actually I just went back and looked at the code, and for quadratics we are already doing the right thing. We are using the stable solution. 

I am not an expert on this, so I am hesitant to confirm this plan. But more importantly, how do you plan to test your improvements?

**Comment by sweeneychris** [comment]
The speed benefits from a closed-form solution are clear. The unknowns are the numeric stability when the roots are not well-distributed. Is my understanding correct that the dogleg strategy is almost surely ill-conditioned since the leading term is the squared radius (which can be huge)? I think we may be able to avoid numerical instabilities of the closed-form solvers if we use long doubles internally in the cubic and quartic solvers.

Short of running a comprehensive experiment to test the accuracy of roots (by checking the function residual) I'm not sure what we can do to test the improvements in a general sense.

**Comment by sweeneychris** [comment]
Actually I just looked at the quartic in the dogleg strategy again -- it probably is not ill-conditioned since most coefficients have an r^2 term in it.

**Comment by sandwichmaker** [comment]
I remember the quartics having odd tiny coefficients. You could easily generate a bunch of these polynomials by logging the output when using a subspace dogleg solver Or the LBFGS solver.

**Comment by sandwichmaker** [comment]
more_garbow_hillstrom -logtostderr -v=3 2>&1 | grep "Input polynomial"

will dump out a crap ton of polynomials to play with, and similarly when running any other solver.

**Comment by sweeneychris** [comment]
Ok I've tested the polynomials from that program on companion matrix, closed form, and [durand-kerner]( https://en.wikipedia.org/wiki/Durand%E2%80%93Kerner_method) solvers. So this is only testing up-to-4 degree polynomials. I think the results are quite informative (to me at least). 

Regarding accuracy: for nearly all cases, the companion matrix has the most stable results (as measured by the residuals of the functions from the solved roots). The closed form solvers predictably are less stable as the degree increases and DK has comparable accuracy to companion matrix but is much less stable.

Regarding timing: closed form solutions are about 3x as fast as the companion matrix method, and DK is about twice as fast. But all of them run in the order of microseconds so I'm not sure that the speed difference really matters at all. I think the companion matrix is somewhat fast for these small polynomials because Eigen has specialized/closed form solutions for eigensolvers of 4x4 or smaller (if I'm remembering correctly).

I'd be happy to integrate the closed form solvers, or the DK iterative solver if you'd like. But in my opinion it doesn't seem to improve performance much. I supposed the closed-form solvers could be improved by adding 1 or 2 newton steps to the computed roots...

**Comment by sweeneychris** [comment]
Some numbers for quartic polynomials:

Residuals:
Companion Residual statistics:
	Mean: 1.0775e+33
	Median: 1.06096e-12
	Std. Dev: 2.25825e+34
	Min: 0
	Max: 4.98853e+35
Closed Form Residual statistics:
	Mean: 2.29545e+42
	Median: 1.39522
	Std. Dev: 4.6252e+43
	Min: 0
	Max: 1.09953e+45
Durand-Kerner Residual statistics:
	Mean: 7.28839e+32
	Median: 2.71265e-14
	Std. Dev: 1.85833e+34
	Min: 0
	Max: 5.6768e+35


And timing results for quartics (in nanoseconds):
Companion Timing statistics:
	Mean: 3067
	Median: 3114
	Std. Dev: 824.114
	Min: 1463
	Max: 23783
Closed Form Timing statistics:
	Mean: 1217.72
	Median: 1159
	Std. Dev: 296.27
	Min: 516
	Max: 27027
Durand-Kerner Timing statistics:
	Mean: 2511.53
	Median: 2124
	Std. Dev: 1333.9
	Min: 413
	Max: 9527

**Comment by sandwichmaker** [comment]
Thanks Chris for the numbers. This is quite useful. I think closed form solvers are out.
As for as eigen's eigensolvers go, as far as I understand only the symmetric 3x3 solver is optimized for fixed size. Everything else (and we are not even using the symmetric solver) is one implementation.

I would not trade solution quality over execution speed at all. So suppose we were willing to trade some more time, is it worth polishing the roots with say the laguerre's solver starting from what the companion matrix solver gives us? And is that a sufficient improvement to be worth it?

**Comment by sweeneychris** [comment]
I haven't forgotten about this, just backlogged a bit. One observation I've already made: no, running Laguerre's solver does not make a huge difference. The roots that are of high quality from the companion matrix method are not dramatically improved from laguerre's, and the ones that are not high quality cannot recover to good solutions with laguerre's.

I am going to spend some time today looking into whether Jenkins-Traub is viable.

**Comment by sweeneychris** [comment]
Ok Sameer I have some encouraging news. I have completed an implementation of the Jenkins Traub algorithm that is working pretty well. You can find it here: https://github.com/sweeneychris/RpolyPlusPlus

Here are the cumulative distributions of errors for cubic and quartics.
![Cubic residuals](http://imgur.com/kpO5i4j,Np7JmUa#1 "Cubic Residuals")

![Quartic residuals](http://imgur.com/kpO5i4j,Np7JmUa "Quartic Residuals")

So it appears that Jenkins Traub does better for most of the roots, and is also 3x or faster. I think some small tweaking could be done to get the "bad" solutions of Jenkins Traub to be much better. Right now I am not doing anything to adjust poorly conditioned polynomials.

Do you know of any methods to scale polynomials for stability during root-finding (similar to the companion matrix balancing)?

**Comment by sandwichmaker** [comment]
@sweeneychris if I am reading the graphs correctly, then isn't the companion matrix method still beating the Jenkin's Traub method handily? as in both graphs, the red line saturates to 1 way before the Jenkins Traub solver.

**Comment by sweeneychris** [comment]
Yes, however, 60-70% of the time Jenkin's Traub performs better and more often than the Companion Matrix it will be 0 within machine precision. That fact is encouraging to me in the sense that I think some parameter tuning can lead to better overall performance. One area I feel can be improved is the scaling of polynomial coefficients -- do you know of any methods to scale polynomials for stability during root-finding (similar to the companion matrix balancing)?

**Comment by sandwichmaker** [comment]
I have no clue about preconditioning polynomials for numerical root finding. Not sure if such a thing even exists. I am not sure if that can be done independent of solution method.

**Comment by sweeneychris** [comment]
Ok I found a flaw in my experiments and have new results. New results show that Jenkins Traub is indeed superior!

Here are the correct, updated results:

Considering the real values of roots (ignoring the imaginary component):
http://imgur.com/KI7F3rG,4TKuddn,f2lNntq,QibwyBs#0
http://imgur.com/KI7F3rG,4TKuddn,f2lNntq,QibwyBs#2

Considering only real roots (only roots where imaginary part == 0):
http://imgur.com/KI7F3rG,4TKuddn,f2lNntq,QibwyBs#1
http://imgur.com/KI7F3rG,4TKuddn,f2lNntq,QibwyBs#3

**Comment by sandwichmaker** [comment]
Very interesting.  What did you have to change to get these results? This is looking very interesting indeed.

**Comment by sandwichmaker** [comment]
Are you re-implementing RPOLY?

**Comment by sweeneychris** [comment]
The error was that I was using only real roots (imaginary == 0) for the companion matrix, and the real **components** (ignoring imaginary) for the jenkins traub. As the new graphs show, this makes quite a difference.

Yes, I re-implemented RPOLY. I had used the [standard C-version](http://www.crbond.com/download/misc/rpoly.cpp) previously and found it often crashed and the code was extremely difficult to follow and debug. My version uses Eigen so it's a lot simpler to follow and gets some SSE optimization for free.

**Comment by sandwichmaker** [comment]
and how are you testing your implementation for both solution quality and convergence speed? is there a benchmark set of polynomials for jenkins-traub code?

**Comment by sweeneychris** [comment]
So far I have been using the polynomials generated from 

more_garbow_hillstrom -logtostderr -v=3 2>&1 | grep "Input polynomial"

as well as some other data I have from SfM stuff.

I think Append A in [this paper](http://homepages.neiu.edu/~zzeng/Papers/zrootpak.pdf) is the closest thing to a polynomial root-finding benchmark.

**Comment by sandwichmaker** [comment]
That paper is about multiple roots though.

**Comment by sandwichmaker** [comment]
what is the set of polynomials Jenkins & Traub report performance on?

**Comment by sweeneychris** [comment]
The Jenkins and Traub paper is from 1968 so they only state "The program has been tested on a large number of polynomials, some chosen to test weaknesses common to zerofinding routines, others randomly generated by a number of techniques."

**Comment by sandwichmaker** [comment]
Two things to consider

http://octopus.library.cmu.edu/Collections/traub62/box00042/fld00024/bdl0002/doc0001/doc_42b24f2b1.pdf

and

http://math-blog.com/2008/03/06/polynomial-root-finding-with-the-jenkins-traub-algorithm/

talks about jenkin's phd thesis perhaps? or I think a cs tech report from stanford.

But I think the first pdf above is the way to go.

**Comment by sweeneychris** [comment]
Yes, those are the same polynomials as Appendix A in the earlier paper I referenced. I purchased Jenkins' thesis in order to understand RPOLY better and it has a only subset of examples of the 1975 paper for testing root-finding.

**Comment by sandwichmaker** [comment]
The first paper also talks about how to generate random polynomials to test your polynomial solver.

**Comment by sandwichmaker** [comment]
Closing as this bug has not seen any action for three years now.
