### ISSUE TITLE
Improve the performance of covariance estimation

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#172]
Some ideas
1. Enable multithreading in SuiteSparseQR using TBB.
2. Expose block sparsity to the reordering routines. 
3. Implement a custom schur complement based algorithm for SfM problems.

**Comment by ttnguyenUBP** [comment]
Hi Sameer,
I have a multicore computer and TBB is enable in my installed SuiteSparseQR.
But Ceres run with only one thread.

**Comment by sandwichmaker** [comment]
Yes the TBB support needs to be enabled when we call SuitesparseQR. If you would like to go ahead modify ceres code and send me a CL I'd be happy to review it.

**Comment by ttnguyenUBP** [comment]
Hi Sameer,
According to spqr_user_guide.pdf, TBB conflicts with BLAS multithreading.
If we enable TBB, have to be sure to disable BLAS multithreading.

I thought that we just need to add
_cholmod_common cc;
cholmod_l_start(&cc); 

cc.SPQR_nthreads = options_.num_threads;
cc.SPQR_grain = 2 * options_.num_threads;_

but it doesn't work.

**Comment by sandwichmaker** [comment]
You control the blas multithreading on your platform, Ceres does not tell
blas to be threaded.

**Comment by sandwichmaker** [comment]
This is a duplicate of https://github.com/ceres-solver/ceres-solver/issues/280 at this point.
