### ISSUE TITLE
Improve documentation on how to debug modeling problems

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#176]
1. How to check that your cost function implementation is correct.
2. How to debug with NaN/infinities
3. How to check/test that your overall problem construction is correct.
4. General statistical modeling advice.

**Comment by ziyangli** [comment]
Look forward to this doc.

**Comment by sandwichmaker** [comment]
Closing this ancient bug in favor or more granular bugs.
