### ISSUE TITLE
polynomial_test fails on rawhide

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#177]
https://bugzilla.redhat.com/show_bug.cgi?id=1239397
https://bugzilla.redhat.com/attachment.cgi?id=1046512

Looks like a tolerance issue. @nocnokneo @keir @alexsmac

**Comment by sandwichmaker** [comment]
368fa5d - Increase tolerance for a test in polynomial_test 

should fix this.

@nocnokneo can you cherrypick and confirm please?

**Comment by nocnokneo** [comment]
Cool, I'll test it out tomorrow morning.

**Comment by sandwichmaker** [comment]
err that and the commit after it. I was a doofus and broke the build instead.

**Comment by nocnokneo** [comment]
Nope - you can revert both of those commits. This is the fix:

http://pkgs.fedoraproject.org/cgit/ceres-solver.git/commit/?id=84c43511badc69c246e9205ab7fadff826f3cd2a

**Comment by sandwichmaker** [comment]
you are right, I screwed up again. I will fix.

**Comment by sandwichmaker** [comment]
https://github.com/ceres-solver/ceres-solver/commit/cbdecc588a6a854b480b931ccc20977699f895ef

should do it for reals. which is the same thing you did.

**Comment by nocnokneo** [comment]
Great. I think this issue issue is resolved.

**Comment by sandwichmaker** [comment]
Thanks Taylor.
