### ISSUE TITLE
FindGlog.cmake does not detect glog directory on Windows

### ISSUE THREAD

**Issue by bvanevery** [ceres-solver/ceres-solver#178]
On 64-bit Windows 7, my glog directory is C:\Program Files\Glog .  It has \include and \lib subdirectories.  Include files of interest are, for instance, C:\Program Files\Glog\include\glog\config.h .

FindGlog.cmake file contains the following notation:
# TODO: Add standard Windows search locations for glog.
Given other bugs of this type that have recently been fixed / improved, it probably just needs the same thing done to it.

**Comment by alexsmac** [comment]
@bvanevery please can you try this CL: https://ceres-solver-review.googlesource.com/6860

**Comment by bvanevery** [comment]
I pulled the change to my existing repo, no merge errors reported.  C:\Program Files\glog is now detected!

**Comment by alexsmac** [comment]
Great, the CL has now been merged into master.
