### ISSUE TITLE
DetectStructure is over optimistic

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#179]
From Werner Tobin on the ceres mailinglist

The current implementation returns as soon as it hits the first row that does not contain a reference to an E block (line 54). In my case this results in a <-1, 3, 6> configuration for the Schur complement solver. However, my model contains F blocks with a size != 6 but these are not linked to any E block. The (incorrectly) fixed F block size leads to problems; the first one is around line 197 in internal/ceres/schur_eliminator_impl.h

**Comment by sandwichmaker** [comment]
https://ceres-solver-review.googlesource.com/#/c/6930/

**Comment by keir** [comment]
Now fixed in master.
