### ISSUE TITLE
Linking ceres-solver libraries to Matlab mex environment

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [ceres-solver/ceres-solver#181]
Hi;

I am trying to compile a project using mex-compiler in Matlab. My project is using Ceres-solver, and I get the following error in Matlab after running : mex mex_solve_translation.cpp -largeArrayDims

Warning: You are using gcc version "4.8.4".  The version
         currently supported with MEX is "4.4.x".
         For a list of currently supported compilers see: 
         http://www.mathworks.com/support/compilers/current_release/

mex_solve_translation.o: In function `solve_translations_problem(int const*, double const*, double const*, int, double, double*, double, double, int)':
mex_solve_translation.cpp:(.text+0x702): undefined reference to `ceres::Problem::Problem()'
mex_solve_translation.cpp:(.text+0x736): undefined reference to `ceres::Problem::AddParameterBlock(double*, int)'
mex_solve_translation.cpp:(.text+0x8c4): undefined reference to `ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*, double*)'
mex_solve_translation.cpp:(.text+0x8f7): undefined reference to `vtable for ceres::HuberLoss'
mex_solve_translation.cpp:(.text+0x930): undefined reference to `ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, double*, double*)'
mex_solve_translation.cpp:(.text+0xc9f): undefined reference to `ceres::Solver::Summary::Summary()'
mex_solve_translation.cpp:(.text+0xd22): undefined reference to `ceres::Solve(ceres::Solver::Options const&, ceres::Problem*, ceres::Solver::Summary*)'
mex_solve_translation.cpp:(.text+0xd35): undefined reference to `ceres::Solver::Summary::FullReport() const'
mex_solve_translation.cpp:(.text+0x1037): undefined reference to `ceres::Problem::~Problem()'
mex_solve_translation.cpp:(.text+0x1097): undefined reference to `ceres::Problem::~Problem()'

mex_solve_translation.o: In function `std::string* google::MakeCheckOpString<int, ceres::DimensionType>(int const&, ceres::DimensionType const&, char const*)':
mex_solve_translation.cpp:(.text._ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc]+0x19): undefined reference to `google::base::CheckOpMessageBuilder::CheckOpMessageBuilder(char const*)'
mex_solve_translation.cpp:(.text._ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc]+0x2f): undefined reference to `google::base::CheckOpMessageBuilder::ForVar2()'
mex_solve_translation.cpp:(.text._ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc]+0x42): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
mex_solve_translation.cpp:(.text._ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc]+0x50): undefined reference to `google::base::CheckOpMessageBuilder::~CheckOpMessageBuilder()'
mex_solve_translation.cpp:(.text._ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc]+0x64): undefined reference to `google::base::CheckOpMessageBuilder::~CheckOpMessageBuilder()'
collect2: error: ld returned 1 exit status

    mex: link of ' "mex_solve_translation.mexa64"' failed.

Error using mex (line 206)
Unable to complete successfully.

Error in demo_trans_averaging (line 31)
mex mex_solve_translation.cpp -largeArrayDims

Would you advice how to compile a mex file by including Ceres libraries ?  given that  ceres/ceres.h has been included successfully and is not generating any compile errors.

Thanks

**Comment by sandwichmaker** [comment]
This is not a compilation error, but a linking error. I think you need to tell mex where to find libceres.

**Comment by Tariq-Abuhashim** [comment]
I tried linking ceres libraries by including them into the compile command:
mex mex_solve_translation.cpp -largeArrayDims -L/path/ceres-bin/lib
that's where libceres.so and libceres.so.1 are.

I also tried to include them by setting up dynamic environmental variables in matlab using:
setenv('DYLD_LIBRARY_PATH','/path/ceres-bin/lib');
setenv('CERES_LIBRARY_PATH','/path/ceres-bin/lib');

It returned the same error both times.

**Comment by sandwichmaker** [comment]
I think you also need to add something like -lceres, just pointing to the
directory won't work, the compiler also need to know the actual name of the
library to use.

**Comment by Tariq-Abuhashim** [comment]
By using :   
mex mex_solve_translation.cpp -largeArrayDims -lceres
The compiler linked Ceres libraries, but the google linking problem remain:

mex_solve_translation.o: In function `std::string* google::MakeCheckOpString<int, ceres::DimensionType>(int const&, ceres::DimensionType const&, char const*)':
mex_solve_translation.cpp:(.text._ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc]+0x19): undefined reference to `google::base::CheckOpMessageBuilder::CheckOpMessageBuilder(char const*)'
mex_solve_translation.cpp:(.text._ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc]+0x2f): undefined reference to `google::base::CheckOpMessageBuilder::ForVar2()'
mex_solve_translation.cpp:(.text._ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc]+0x42): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
mex_solve_translation.cpp:(.text._ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc]+0x50): undefined reference to `google::base::CheckOpMessageBuilder::~CheckOpMessageBuilder()'
mex_solve_translation.cpp:(.text._ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiN5ceres13DimensionTypeEEEPSsRKT_RKT0_PKc]+0x64): undefined reference to `google::base::CheckOpMessageBuilder::~CheckOpMessageBuilder()'

Which libraries should I include to link google ?

**Comment by Tariq-Abuhashim** [comment]
I added -lglog and that solved the problem:

mex mex_solve_translation.cpp -largeArrayDims -lceres -lglog

Thank you
Tariq
