### ISSUE TITLE
Unable to find shared_ptr

### ISSUE THREAD

**Issue by ClemensHa** [ceres-solver/ceres-solver#182]
I tried to build ceres for android with cmake and android-cmake(https://github.com/taka-no-me/android-cmake), but I ran into a problem. Cmake cannot find the shared_ptr
![ceres-cmake-24082015](https://cloud.githubusercontent.com/assets/13884251/9437416/847e372a-4a56-11e5-8d13-01f3323a1bad.png)

I was using the compiler of the android NDK android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc.exe

**Comment by sandwichmaker** [comment]
@alexsmac can say more, but I do not think we actually support building on android using cmake yet.

**Comment by alexsmac** [comment]
We don't explicitly support using android-cmake, although I don't *think* we are doing anything that would explicitly prevent its use.  However, the problem appears to be that 'make' is not being properly detected when CMake invokes the check_cxx_source_compiles() macro (which under the hood uses the try_compile() CMake function).  Hence you see stuff like: "execution of make failed. Make command was "" "cmTC_5b431/fast", the first empty quotes being the issue, the latter is likely the semi-random directory created by CMake for the temporary project created for check_cxx_source_compiles().

See here: https://github.com/taka-no-me/android-cmake#building-on-windows

I suspect that this part in particular:

- Add path to your make.exe to system PATH or always use full path;

is your problem.  As make is not on the system path, although it might be known to the Ceres CMake project you are trying to build, it is not known to the temporary test project CMake creates to run check_cxx_source_compiles().

**Comment by ClemensHa** [comment]
Thank you for your help!

I tried it again in the windows shell and now I could configure and generate the make files forceres. I don't know why I couldn't set the make.exe in the cmakeLists.txt, but it worked with the windows shell.

But if I want to build ceres , I get the following errors:

![errors build process](https://cloud.githubusercontent.com/assets/13884251/9521150/549634da-4ccd-11e5-9912-bcacece11a4d.PNG)
![errors build process2](https://cloud.githubusercontent.com/assets/13884251/9521151/5556e5e0-4ccd-11e5-893f-68674ed014cf.PNG)
Do you know the reason for this?

**Comment by alexsmac** [comment]
I would assume this is because you are missing: $NDK/platforms/android<version>/arch-arm/usr/include from the list of include paths.

**Comment by pmoulon** [comment]
The error seems to be linked to pthread here.
pthread must be used it OpenMP have beend detected https://github.com/ceres-solver/ceres-solver/blob/master/CMakeLists.txt#L428
BTW: just for a try you can try force to not used multitreading with using CERES_NO_THREADS

**Comment by keir** [comment]
Also note that OpenMP is not supported on Android; I suggest disabling it.
At least this was the case a year ago, perhaps OpenMP is now supported but
I doubt it.

**Comment by sandwichmaker** [comment]
OpenMP is now supported, but I have not been able to make it work without crashing.

**Comment by ClemensHa** [comment]
I diasbled OpenMP and then Gflags.

I don't know how to solve this problem:
![errors build process3](https://cloud.githubusercontent.com/assets/13884251/9542583/532c5714-4d72-11e5-84a6-2d84ade0095b.PNG)

**Comment by ClemensHa** [comment]
I had to add this line 
list(APPEND CERES_LIBRARY_PUBLIC_DEPENDENCIES log)
and now I built it as a shared library.

Thanks guys!

**Comment by keir** [comment]
Hi Clemens,

Would you be willing to prepare a fix for this in our build system so
others can benefit from your work? See the guide to contributing
<http://ceres-solver.org/contributing.html>.

Thanks,
Keir

**Comment by ClemensHa** [comment]
Quick overview about what I did:
Download:
Android-Cmake: https://github.com/taka-no-me/android-cmake
Android NDK:https://developer.android.com/ndk/downloads/index.html
Cmake: https://cmake.org/download/
Gflags: https://github.com/gflags/gflags
Eigen: http://eigen.tuxfamily.org/index.php?title=Main_Page
Ceres-solver: https://github.com/ceres-solver/ceres-solver
I safed all files in the directory: "D:\Ceres"

set environment variable ANDROID_NDK
Name: "ANDROID_NDK"
Value: "D:\Ceres\android-ndk-r10e"

Change in D:\Ceres\ceres-solver\CMakeLists.txt the following statements:

Add before project(Ceres C CXX) 
https://github.com/ceres-solver/ceres-solver/blob/master/CMakeLists.txt#L39
added: SET(EIGEN_INCLUDE_DIR D:/Ceres/Eigen)
            SET(GFLAGS_INCLUDE_DIR D:/Ceres/Gflags)

Turn Miniglog ON
https://github.com/ceres-solver/ceres-solver/blob/master/CMakeLists.txt#L89
modified: option(MINIGLOG "Use a stripped down version of glog." ON)

Turn OpenMP OFF
https://github.com/ceres-solver/ceres-solver/blob/master/CMakeLists.txt#L102
modified: option(OPENMP "Enable threaded solving in Ceres (requires OpenMP)" OFF)

Turn CXX11 ON
https://github.com/ceres-solver/ceres-solver/blob/master/CMakeLists.txt#L125
modified: option(CXX11 "Enable use of C++11 headers if available (requires client code use C++11)." ON)

Turn BUILD_SHARED_LIBS ON
https://github.com/ceres-solver/ceres-solver/blob/master/CMakeLists.txt#L132
modified: option(BUILD_SHARED_LIBS "Build Ceres as a shared library." ON)

Add after set(GLOG_INCLUDE_DIRS internal/ceres/miniglog)
https://github.com/ceres-solver/ceres-solver/blob/master/CMakeLists.txt#L349
added: list(APPEND CERES_LIBRARY_PUBLIC_DEPENDENCIES log)

Comment those lines: 
https://github.com/ceres-solver/ceres-solver/blob/master/CMakeLists.txt#L807
commented: #configure_file("${CMAKE_SOURCE_DIR}/cmake/uninstall.cmake.in"
               #"${CMAKE_BINARY_DIR}/cmake/uninstall.cmake"
               #@ONLY)

Open cmd, change directory to D:/Ceres and enter command :
cmake -G "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE=D:\Ceres\android-cmake-master\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=D:\Ceres\android-ndk-r10e\prebuilt\windows-x86_64\bin\make.exe ceres-solver
(maybe you have to execute the command above twice, because it cannot find gflags on the first attempt)

Then:
cmake --build D:\Ceres
