### ISSUE TITLE
Homebrew install ceres segfaults on all examples

### ISSUE THREAD

**Issue by etano** [ceres-solver/ceres-solver#183]
Simply I tried:

    brew tap homebrew/science
    brew install ceres-solver --HEAD

Then tried compiling the example (https://ceres-solver.googlesource.com/ceres-solver/+/master/examples/helloworld.cc) with:

    g++ -std=c++11 helloworld.cc -I/usr/local/include -I/usr/local/include/eigen3 -L/usr/local/lib -lceres -lglog

which produces:

    E0826 00:04:11.548545 1942315776 solver.cc:486] Terminating: Invalid configuration. Solver::Options::gradient_check_relative_precision = 0. Violated constraint: Solver::Options::gradient_check_relative_precision > 0.0
    Segmentation fault: 11

Please help!

**Comment by sandwichmaker** [comment]
Ethan, I tried
brew install ceres-solver --HEAD
g++ -std=c++11 helloworld.cc -I/usr/local/include -I/usr/local/include/eigen3 -L/usr/local/lib -lceres -lglog

and it worked just fine for me.

**Comment by etano** [comment]
Hmm... yeah doesn't work for me. Pretty sure I have a clean install of everything. I'm using gcc 4.9.1 with OS X 10.10.5 if that helps.

Again the output after compiling and running is:

    E0827 14:13:41.655524 2008105728 solver.cc:486] Terminating: Invalid configuration. Solver::Options::gradient_check_relative_precision = 0. Violated constraint: Solver::Options::gradient_check_relative_precision > 0.0
    0
    helloworld(17503,0x7fff77b14300) malloc: *** error for object 0x2ffffffff: pointer being freed was not allocated
    *** set a breakpoint in malloc_error_break to debug
    Abort trap: 6

I should note that compiling from source on another machine (a linux server), everything is fine.

Any other relevant information that would be useful?

**Comment by sandwichmaker** [comment]
Can you try clang on osx? maybe you are mixing standard libraries or libraries compiled with different compilers?

**Comment by etano** [comment]
Yes clang++ seems to be working. Could it be that homebrew defaults to clang?

**Comment by sandwichmaker** [comment]
yes, I believe that is the case. I am going to mark this issue closed, please re-open it if you still think its a problem that ceres solver developers need to solve.
