### ISSUE TITLE
Incomplete sentence in documentation

### ISSUE THREAD

**Issue by abrock** [ceres-solver/ceres-solver#189]
The [tutorial on bundle adjustment](http://ceres-solver.org/nnls_tutorial.html#bundle-adjustment) contains the following sentence:

> Since this large sparse problem (well large for DENSE_QR anyways), one way to solve this problem is to set Solver::Options::linear_solver_type to SPARSE_NORMAL_CHOLESKY and call Solve

I think there is a part of the sentence missing before "one way", something like "is symmetric and positive definite".

**Comment by sandwichmaker** [comment]
Thanks, this  is a malformed sentence, but not in the way you suggest. All that is missing is "is a" before large. The problem being referred to is a non-linear least squares problem so it is not symmetric or positive definite. The normal equations for any non-linear least squares problem are always symmetric positive semi-definite. 

I have just pushed a fix to the repo, it should be reflected in the actual website in a couple of days (as soon as I have a chance to push a documentation build).
