### ISSUE TITLE
ceres requires C++11 (even with CXX11=OFF)

### ISSUE THREAD

**Issue by severin-lemaignan** [ceres-solver/ceres-solver#191]
Due to the use of `va_copy` in `internal/ceres/stringprintf.cc`, `ceres` does not compile without c++11 suport. This is an issue for non-C++11 applications that attempt to link with `ceres` (and incidentally, it defeats the purpose of the `CXX11` option).

Step to reproduce:
- add `-std=c++03` to the C++ compiler flags (tested with `g++-5.2`)
- `make`

Tested at commit cb467d83fe6ea8e082 (Jan 8, 2016)

**Comment by alexsmac** [comment]
Hi Severin,

This should be fixed by this CL: https://ceres-solver-review.googlesource.com/#/c/7290/ - please give it a whirl.  It fixes the issue for me on Ubuntu 14.04, with GCC 4.8.4 & Clang 3.4 (which also previously broke if using -std=c++03).

**Comment by severin-lemaignan** [comment]
I've tested the patch: this fixes nicely my issue! Thanks for the quick response!

**Comment by alexsmac** [comment]
Closing, as the fix is now merged into master
