### ISSUE TITLE
Install cmake targets to arch-dependent path

### ISSUE THREAD

**Issue by jpgr87** [ceres-solver/ceres-solver#194]
CeresConfig and the CeresTargets files generated by CMake contain architecture-specific paths to libraries (e.g. /usr/lib64/libceres.so.1,) but they are being installed to an architecture-independent location under /usr/share. On systems that support installation of packages from multiple architectures, like Fedora and Debian, this can lead to the following types of errors:
1. On a 64-bit system, if a 32-bit ceres-solver is installed by mistake cmake may try to link a 64-bit executable against the 32-bit ceres-solver library, causing an error.
2. On a 64-bit system, it becomes impossible to build both 64-bit and 32-bit code against ceres-solver without changing the installed ceres-solver-dev subpackage for the correct architecture.

To resolve this, ceres-solver should change the installation location of the CMake files to one of the architecure-dependent paths described in the [find_package](https://cmake.org/cmake/help/v3.0/command/find_package.html) documentation.  The Fedora ceres-solver package is using [this patch](http://pkgs.fedoraproject.org/cgit/rpms/ceres-solver.git/tree/ceres-solver-1.11.0-cmakedir.patch?h=f23) to do so, feel free to adopt or modify it if you decide to use a similar solution.

**Comment by alexsmac** [comment]
Please try this CL: https://ceres-solver-review.googlesource.com/#/c/7330/ 

Note that the install path for CeresConfig.cmake was changed to lib/cmake/Ceres after 1.11 in master, the CL updates it to include LIB_SUFFIX and moves the auto-detection logic into the main CMakeLists.txt

**Comment by alexsmac** [comment]
@jpgr87 have you had a chance to test the CL to confirm if it fixes your problem?

**Comment by jpgr87** [comment]
Sorry I haven't yet, I'll try to get to it this week.

**Comment by alexsmac** [comment]
Closing, as the fix has now been merged into master.
