### ISSUE TITLE
Jacobian evaluation is very slow in my own project

### ISSUE THREAD

**Issue by libing64** [ceres-solver/ceres-solver#195]
I create a new project and just copy the code of simple_bundle_adjuster from the examples. However, the performance is really different with the code built in ceres examples.

**1. the output of simple_bundle_adjuster built in ceres examples**

Solver Summary (v 1.11.0-eigen-(3.2.0)-lapack-suitesparse-(4.4.6)-cxsparse-(3.1.4)-eigensparse-openmp)

                                     Original                  Reduced
Parameter blocks                        22122                    22122
Parameters                              66462                    66462
Residual blocks                         83718                    83718
Residual                               167436                   167436

Minimizer                        TRUST_REGION

Dense linear algebra library            EIGEN
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver                     DENSE_SCHUR              DENSE_SCHUR
Threads                                     1                        1
Linear solver threads                       1                        1
Linear solver ordering              AUTOMATIC                22106, 16

Cost:
Initial                          4.185660e+06
Final                            1.803390e+04
Change                           4.167626e+06

Minimizer iterations                        6
Successful steps                            6
Unsuccessful steps                          0

Time (in seconds):
Preprocessor                           0.2350

  Residual evaluation                  0.1535
  Jacobian evaluation                  0.8997
  Linear solver                        0.8333
Minimizer                              2.0321

Postprocessor                          0.0042
Total                                  2.2713

Termination:                      CONVERGENCE (Function tolerance reached. |cost_change|/cost: 1.769759e-09 <= 1.000000e-06)

**2. the output of simple_bundle_adjuster built in my own project**

`Solver Summary (v 1.11.0-eigen-(3.2.0)-lapack-suitesparse-(4.4.6)-cxsparse-(3.1.4)-eigensparse-openmp)

                                     Original                  Reduced
Parameter blocks                        22122                    22122
Parameters                              66462                    66462
Residual blocks                         83718                    83718
Residual                               167436                   167436

Minimizer                        TRUST_REGION

Dense linear algebra library            EIGEN
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver                     DENSE_SCHUR              DENSE_SCHUR
Threads                                     1                        1
Linear solver threads                       1                        1
Linear solver ordering              AUTOMATIC                22106, 16

Cost:
Initial                          4.185660e+06
Final                            1.803390e+04
Change                           4.167626e+06

Minimizer iterations                        6
Successful steps                            6
Unsuccessful steps                          0

Time (in seconds):
Preprocessor                           0.1392

  Residual evaluation                  0.1440
  Jacobian evaluation                 52.8442
  Linear solver                        0.4761
Minimizer                             53.5685

Postprocessor                          0.0057
Total                                 53.7134`

**3. this is my CMakeLists.txt**
`cmake_minimum_required(VERSION 2.8)
project(simple_bundle_adjuster)

set(DCMAKE_BUILD_TYPE "release")
set(CMAKE_CXX_FLAGS "-std=c++11 -march=native")

find_package(Eigen3 REQUIRED)
find_package(Ceres REQUIRED)

include_directories(${CERES_INCLUDE_DIRS})
add_executable(simple_bundle_adjuster simple_bundle_adjuster.cc)
target_link_libraries( simple_bundle_adjuster  ceres )`

**Can anyone give some advice to improve the performance of binary? **

**Comment by libing64** [comment]
Since the code is the same, I guess that it is caused by the build option, but I don't know how to improve it?

**Comment by sandwichmaker** [comment]
-DCMAKE_BUILD_TYPE=Release on the command line when calling cmake should
fix this.

**Comment by libing64** [comment]
@sandwichmaker  great thanks, it works.
In fact, I added a line to set the build type option, set(DCMAKE_BUILD_TYPE "release"), but it's wrong. 
It should be like this set(CMAKE_BUILD_TYPE "release")
