### ISSUE TITLE
Repeated conversion of angles

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#199]
https://ceres-solver.googlesource.com/ceres-solver/+/master/internal/ceres/rotation_test.cc#669

Reported by @fgcallari

**Comment by sandwichmaker** [comment]
also https://ceres-solver.googlesource.com/ceres-solver/+/master/internal/ceres/rotation_test.cc#714

**Comment by keir** [comment]
Fix for one part:

https://ceres-solver-review.googlesource.com/#/c/7380/1

**Comment by keir** [comment]
Fix for double conversion:

https://ceres-solver-review.googlesource.com/#/c/7382/

**Comment by keir** [comment]
All merged; closing. Thanks for the report!
