### ISSUE TITLE
when i build shared lib for android have some issues

### ISSUE THREAD

**Issue by 781238222** [ceres-solver/ceres-solver#200]
my system: ubuntukylin-15.10-enhanced-release-amd64
I run ndk-build from inside the jni directory and cereate a libceres.a file. I use my jni_part.cpp and libceres.a to build a shared lib.
jni_part.cpp:

#include <jni.h>
#include "ceres/ceres.h"
using ceres::AutoDiffCostFunction;
using ceres::CostFunction;
using ceres::Problem;
using ceres::Solver;
using ceres::Solve;
struct CostFunctor {
	template <typename T> bool operator()(const T* const x, T* residual) const {
		residual[0] = T(10.0) - x[0];
		return true;
	}
};

#ifdef __cplusplus
extern "C" {
#endif
	JNIEXPORT jint JNICALL Java_com_qiwei_samples_JniDemo_add(JNIEnv *env, jclass cls)
	{
		jdouble initial_x = 5.0;
		jdouble x = initial_x;
		Problem problem;
		CostFunction* cost_function =
			new AutoDiffCostFunction<CostFunctor, 1, 1>(new CostFunctor);
		problem.AddResidualBlock(cost_function, NULL, &x);

		Solver::Options options;
		options.linear_solver_type = ceres::DENSE_QR;
		options.minimizer_progress_to_stdout = true;
		Solver::Summary summary;
		Solve(options, &problem, &summary);
		std::cout << summary.BriefReport() << "\n";
		std::cout << "x : " << initial_x
			<< " -> " << x << "\n";
		return 0;
	}
#ifdef __cplusplus
}
#endif

android.mk:
  LOCAL_PATH := $(call my-dir)
  LOCAL_ALLOW_UNDEFINED_SYMBOLS := true
  include $(CLEAR_VARS)
  LOCAL_MODULE    := ceres
  LOCAL_SRC_FILES := libceres.a
  include $(PREBUILT_STATIC_LIBRARY)
  include $(CLEAR_VARS)
  LOCAL_C_INCLUDES += /home/meng/Desktop/android-ndk-r9d/sources/cxx-stl/stlport/stlport
  LOCAL_C_INCLUDES += ../config
  LOCAL_C_INCLUDES += ../include
  LOCAL_C_INCLUDES += ../internal/ceres/miniglog
  LOCAL_MODULE    := myproject
  LOCAL_SRC_FILES := jni_part.cpp
  LOCAL_STATIC_LIBRARIES  =  ceres
  LOCAL_LDLIBS +=  -llog -ldl
  include $(BUILD_SHARED_LIBRARY)

when I run ndk-build:
meng@ubuntu:~/Desktop/ceres-solver-1.11.0/jni$ '/home/meng/Desktop/android-ndk-r9d/ndk-build' 
[armeabi-v7a] Compile++ thumb: myproject <= jni_part.cpp
In file included from ../include/ceres/jet.h:166:0,
                 from ../include/ceres/internal/autodiff.h:145,
                 from ../include/ceres/autodiff_cost_function.h:132,
                 from ../include/ceres/ceres.h:37,
                 from /home/meng/Desktop/ceres-solver-1.11.0/jni/jni_part.cpp:3:
../include/ceres/fpclassify.h: In function 'bool ceres::IsNormal(double)':
../include/ceres/fpclassify.h:64:48: error: expected unqualified-id before '(' token
In file included from ../internal/ceres/miniglog/glog/logging.h:109:0,
                 from ../include/ceres/internal/fixed_array.h:39,
                 from ../include/ceres/internal/autodiff.h:147,
                 from ../include/ceres/autodiff_cost_function.h:132,
                 from ../include/ceres/ceres.h:37,
                 from /home/meng/Desktop/ceres-solver-1.11.0/jni/jni_part.cpp:3:
../include/ceres/internal/port.h: At global scope:
../include/ceres/internal/port.h:50:12: error: 'std::shared_ptr' has not been declared
In file included from ../include/ceres/ceres.h:40:0,
                 from /home/meng/Desktop/ceres-solver-1.11.0/jni/jni_part.cpp:3:
../include/ceres/cost_function_to_functor.h: In constructor 'ceres::CostFunctionToFunctor<kNumResiduals, N0, N1, N2, N3, N4, N5, N6, N7, N8, N9>::CostFunctionToFunctor(ceres::CostFunction*)':
../include/ceres/cost_function_to_functor.h:146:5: error: there are no arguments to 'accumulate' that depend on a template parameter, so a declaration of 'accumulate' must be available [-fpermissive]
../include/ceres/cost_function_to_functor.h:146:5: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from ../include/ceres/ceres.h:44:0,
                 from /home/meng/Desktop/ceres-solver-1.11.0/jni/jni_part.cpp:3:
../include/ceres/dynamic_numeric_diff_cost_function.h: In member function 'virtual bool ceres::DynamicNumericDiffCostFunction<CostFunctor, method>::Evaluate(double const* const*, double*, double**) const':
../include/ceres/dynamic_numeric_diff_cost_function.h:137:79: error: there are no arguments to 'accumulate' that depend on a template parameter, so a declaration of 'accumulate' must be available [-fpermissive]
In file included from ../include/ceres/ceres.h:55:0,
                 from /home/meng/Desktop/ceres-solver-1.11.0/jni/jni_part.cpp:3:
../include/ceres/solver.h: At global scope:
../include/ceres/solver.h:499:5: error: 'shared_ptr' does not name a type
../include/ceres/solver.h:630:5: error: 'shared_ptr' does not name a type
make: *** [/home/meng/Desktop/ceres-solver-1.11.0/obj/local/armeabi-v7a/objs/myproject/jni_part.o] Error 1

Can you tell me where the problem? Thank you

**Comment by keir** [comment]
It appears you did not define a CostFunctor. Take a look at the autodiff examples (e.g. simple bundle adjuster) to see how you must define your own (with operator()). I suggest first making your code compile outside of JNI as a normal C++ application, then move it to JNI.
