### ISSUE TITLE
Link error LNK2019 in VisualStudio2015

### ISSUE THREAD

**Issue by MamoonNomaan** [ceres-solver/ceres-solver#201]
Hi, I am trying to run the example code "simple_bundle_adjuster.cc" on VisualStudio2015, but I get Link errors which I am simply unable to resolve. I face the same problem even when I am trying to run the basic "helloworld.cc" example. Any help will be appreciated. Thanks 

Error   19  error LNK1120: 18 unresolved externals  E:\Ninebot\LMA\LMA\Debug\LMA.exe
Error   1   error LNK2019: unresolved external symbol "__declspec(dllimport) void __cdecl google::InitGoogleLogging(char const *)" (__imp_?InitGoogleLogging@google@@YAXPBD@Z) referenced in function _main E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   2   error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall google::base::CheckOpMessageBuilder::CheckOpMessageBuilder(char const *)" (__imp_??0CheckOpMessageBuilder@base@google@@QAE@PBD@Z) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > \* __cdecl google::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@google@@YAPAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABH0PBD@Z) E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   3   error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall google::base::CheckOpMessageBuilder::~CheckOpMessageBuilder(void)" (__imp_??1CheckOpMessageBuilder@base@google@@QAE@XZ) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > \* __cdecl google::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@google@@YAPAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABH0PBD@Z)   E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   4   error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > \* __thiscall google::base::CheckOpMessageBuilder::ForVar1(void)" (__imp_?ForVar1@CheckOpMessageBuilder@base@google@@QAEPAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > \* __cdecl google::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@google@@YAPAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABH0PBD@Z) E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   5   error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > \* __thiscall google::base::CheckOpMessageBuilder::ForVar2(void)" (__imp_?ForVar2@CheckOpMessageBuilder@base@google@@QAEPAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > \* __cdecl google::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@google@@YAPAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABH0PBD@Z) E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   6   error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > \* __thiscall google::base::CheckOpMessageBuilder::NewString(void)" (__imp_?NewString@CheckOpMessageBuilder@base@google@@QAEPAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > \* __cdecl google::MakeCheckOpString<int,int>(int const &,int const &,char const *)" (??$MakeCheckOpString@HH@google@@YAPAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABH0PBD@Z)   E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   7   error LNK2019: unresolved external symbol "__declspec(dllimport) public: class std::basic_ostream<char,struct std::char_traits<char> > & __thiscall google::LogMessage::stream(void)" (__imp_?stream@LogMessage@google@@QAEAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@XZ) referenced in function "void __cdecl ceres::internal::Make1stOrderPerturbation<struct ceres::Jet<double,1>,double,1>(int,double const *,struct ceres::Jet<double,1> *)" (??$Make1stOrderPerturbation@U?$Jet@N$00@ceres@@N$00@internal@ceres@@YAXHPBNPAU?$Jet@N$00@1@@Z)  E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   8   error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall google::LogMessageFatal::LogMessageFatal(char const *,int)" (__imp_??0LogMessageFatal@google@@QAE@PBDH@Z) referenced in function "void __cdecl ceres::internal::Make1stOrderPerturbation<struct ceres::Jet<double,1>,double,1>(int,double const *,struct ceres::Jet<double,1> *)" (??$Make1stOrderPerturbation@U?$Jet@N$00@ceres@@N$00@internal@ceres@@YAXHPBNPAU?$Jet@N$00@1@@Z)   E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   9   error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall google::LogMessageFatal::LogMessageFatal(char const *,int,struct google::CheckOpString const &)" (__imp_??0LogMessageFatal@google@@QAE@PBDHABUCheckOpString@1@@Z) referenced in function "public: __thiscall ceres::AutoDiffCostFunction<struct CostFunctor,1,1,0,0,0,0,0,0,0,0,0>::AutoDiffCostFunction<struct CostFunctor,1,1,0,0,0,0,0,0,0,0,0>(struct CostFunctor *)" (??0?$AutoDiffCostFunction@UCostFunctor@@$00$00$0A@$0A@$0A@$0A@$0A@$0A@$0A@$0A@$0A@@ceres@@QAE@PAUCostFunctor@@@Z)    E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   10  error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall google::LogMessageFatal::~LogMessageFatal(void)" (__imp_??1LogMessageFatal@google@@QAE@XZ) referenced in function "void __cdecl ceres::internal::Make1stOrderPerturbation<struct ceres::Jet<double,1>,double,1>(int,double const *,struct ceres::Jet<double,1> *)" (??$Make1stOrderPerturbation@U?$Jet@N$00@ceres@@N$00@internal@ceres@@YAXHPBNPAU?$Jet@N$00@1@@Z)  E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   11  error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall google::LogMessageVoidify::LogMessageVoidify(void)" (__imp_??0LogMessageVoidify@google@@QAE@XZ) referenced in function "void __cdecl ceres::internal::Make1stOrderPerturbation<struct ceres::Jet<double,1>,double,1>(int,double const *,struct ceres::Jet<double,1> *)" (??$Make1stOrderPerturbation@U?$Jet@N$00@ceres@@N$00@internal@ceres@@YAXHPBNPAU?$Jet@N$00@1@@Z) E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   12  error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __thiscall google::LogMessageVoidify::operator&(class std::basic_ostream<char,struct std::char_traits<char> > &)" (__imp_??ILogMessageVoidify@google@@QAEXAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z) referenced in function "void __cdecl ceres::internal::Make1stOrderPerturbation<struct ceres::Jet<double,1>,double,1>(int,double const *,struct ceres::Jet<double,1> *)" (??$Make1stOrderPerturbation@U?$Jet@N$00@ceres@@N$00@internal@ceres@@YAXHPBNPAU?$Jet@N$00@1@@Z) E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   13  error LNK2019: unresolved external symbol "public: __thiscall ceres::Problem::Problem(void)" (??0Problem@ceres@@QAE@XZ) referenced in function _main    E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   14  error LNK2019: unresolved external symbol "public: __thiscall ceres::Problem::~Problem(void)" (??1Problem@ceres@@QAE@XZ) referenced in function _main   E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   15  error LNK2019: unresolved external symbol "public: class ceres::internal::ResidualBlock \* __thiscall ceres::Problem::AddResidualBlock(class ceres::CostFunction *,class ceres::LossFunction *,double *)" (?AddResidualBlock@Problem@ceres@@QAEPAVResidualBlock@internal@2@PAVCostFunction@2@PAVLossFunction@2@PAN@Z) referenced in function _main   E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   16  error LNK2019: unresolved external symbol "public: __thiscall ceres::Solver::Summary::Summary(void)" (??0Summary@Solver@ceres@@QAE@XZ) referenced in function _main E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   17  error LNK2019: unresolved external symbol "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall ceres::Solver::Summary::BriefReport(void)const " (?BriefReport@Summary@Solver@ceres@@QBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) referenced in function _main  E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj
Error   18  error LNK2019: unresolved external symbol "void __cdecl ceres::Solve(struct ceres::Solver::Options const &,class ceres::Problem *,struct ceres::Solver::Summary *)" (?Solve@ceres@@YAXABUOptions@Solver@1@PAVProblem@1@PAUSummary@31@@Z) referenced in function _main   E:\Ninebot\LMA\LMA\LMA\LMA_ceres_1.obj

**Comment by alexsmac** [comment]
1) Are you building Ceres with glog, or with the MINIGLOG option enabled?

2) Who generated the build scripts for simple_bundle_adjuster & helloworld that you are trying to use?  Was it CMake when you built Ceres, or are you trying to do it separately yourself?

If you are trying to generate your own build scripts, then you are not going to get the target dependency information for Ceres populated for you by CMake, in which case you will have to manually add the link dependencies required by Ceres - at least glog in this case.

If you are using MINIGLOG (and building your own build script) then the problem could also be that you have the include path for glog in the include list and are either missing the miniglog include path (see CERES_INCLUDE_DIRS), or it appears *after* the include path for (full) glog as per a previous issue #196.

**Comment by alexsmac** [comment]
Closing this issue as no follow up information was provided, please re-open this issue providing more information about your setup if this is still an issue.
