### ISSUE TITLE
How to Use Ceres-Solver Library for Android

### ISSUE THREAD

**Issue by 781238222** [ceres-solver/ceres-solver#202]
I have created libceres.a file,I  should how to use this file for android app? can you give me a demo?

**Comment by keir** [comment]
You need to use the NDK. Unfortunately we don't have any documentation around this, and interfacing is not trivial. The general approach is to write your own application-specific solving code in C++ that calls Ceres, then write a JNI wrapper around your own code and call that from Java.

**Comment by keir** [comment]
I opened a separate ticket to track adding documentation: https://github.com/ceres-solver/ceres-solver/issues/204
