### ISSUE TITLE
Add documentation showing how to use Ceres from Android

### ISSUE THREAD

**Issue by keir** [ceres-solver/ceres-solver#204]
Currently there is no documentation on how to do this, or examples. The general approach is to write your own application-specific solving code in C++ that calls Ceres, then write a JNI wrapper around your own code and call that from Java. However, we should document this properly and have an example.

**Comment by lujun2445** [comment]
Dear Dr Keir, I have found that many articles cited this article: Ceres Solver: Tutorial & Reference, but I can not find it anywhere, would you kind enough to send  it to me throung e-mail. jpkc_lujun@126.com
Thanks very much!

**Comment by sandwichmaker** [comment]
That used to be our old pdf manual, now everything is at ceres-solver.org.

**Comment by lujun2445** [comment]
Thanks very much sandwichmaker!

**Comment by sandwichmaker** [comment]
Closing this as cmake build should allow you to build an executable and run it on android.
