### ISSUE TITLE
bundle adjustment using control points variable weight

### ISSUE THREAD

**Issue by lujun2445** [ceres-solver/ceres-solver#205]
How to use ceres with Ground Control Points  with a variable weight over the residual? thank you!

**Comment by pmoulon** [comment]
You must add a weight variable inside your residual cost functor and set the 3D point as contant.
So your cost_functor will return residual*my_weight_factor;
You are free to udpate your internal weight between the BA steps.

**Comment by keir** [comment]
Thanks for responding Pierre. Closing since this is the responsibility of the user.

**Comment by lujun2445** [comment]
Thanks very much!
