### ISSUE TITLE
OpenMP collapse directive MSVC 2013 2015 compilation error

### ISSUE THREAD

**Issue by nkyriazis** [ceres-solver/ceres-solver#206]
The collapse directive used in https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/covariance_impl.cc#L340 leads to a compilation error in Visual Studio 2013 and 2015, due to lack of support for OpenMP v3.

**Comment by keir** [comment]
Can you tell me what _MSC_VER is and also _OPENMP? Ideally on both 2013 and 2015?

**Comment by nkyriazis** [comment]
VS2013:
_MSC_VER=1800
_OPENMP=200203

VS2015:
_MSC_VER=1900
_OPENMP=200203

**Comment by keir** [comment]
Thanks; I made a patch:

https://ceres-solver-review.googlesource.com/7400

Can you check to see if it solves your issue?

**Comment by nkyriazis** [comment]
Yes it does. Thnx for looking at it.

**Comment by keir** [comment]
Great; thanks for the report!
