### ISSUE TITLE
Use parallel primitives from thrust

### ISSUE THREAD

**Issue by nkyriazis** [ceres-solver/ceres-solver#207]
[Thrust](https://github.com/thrust/thrust) is a STL-like library with focus on parallelism. Through its API It provides an elegant way to factor out, now in code and in the future also in runtime, the parallelization details and focus on the algorithm. Instead of employing OPENMP with explicit use of its directives, one can use thrust. Combined with the C++11 lambdas, so as to inline loop body code instead of moving it away from the loop, rewriting loops to use thrust is greatly facilitated.

Thrust readily provides backends to OpenMP and TBB. It is also straightforward to provide [tailored backends](https://github.com/thrust/thrust/blob/master/examples/minimal_custom_backend.cu).

As a side note, the more one employs THRUST the more the code becomes susceptible to CUDA acceleration too.

**Comment by sandwichmaker** [comment]
Nikolaos, this is interesting but we are unlikely to go down this path.  It introduces on more library dependency and requires c++11.

**Comment by sandwichmaker** [comment]
Closing for now.
