### ISSUE TITLE
EulerAnglesToRotationMatrix does a cast from degrees

### ISSUE THREAD

**Issue by atroyn** [ceres-solver/ceres-solver#211]
Euler angles are typically represented in radians with ranges [−π, π]. This function assumes it is passed Euler angles in degrees. [https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/rotation.h#L426](url)

This cast isn't referenced in the API docs. Much hair was pulled out wondering why pose estimates had a 0.2 radian / 11 degree rotation while the translation estimate was correct. 

Is the degree case the common use case?

**Comment by sandwichmaker** [comment]
This is likely for historical reasons in the codebase. I understand the confusion but the documentation is explicit even if the expectations are a little unfair :/. My apologies.
