### ISSUE TITLE
Ceres dependency not working transitively when building from source

### ISSUE THREAD

**Issue by pedrolf** [ceres-solver/ceres-solver#215]
I have a Library B depending on Ceres. After cloning from GitHub and running `sudo make install`, libceres.a gets installed in /usr/local/lib/libceres.a.

Using find_package(Ceres REQUIRED), Library B compiles without any issues. However, I have a different Library A depending on Library B. Library A fails to compile because it doesn't properly link Ceres unless I do find_package(Ceres Required) in the cmake file of Library A. 

The Ceres dependency should be pulled transparently to Library A.

**Comment by alexsmac** [comment]
This is a feature of how CMake works.  Please see here:

http://ceres-solver.org/building.html#installing-exporting-a-project-that-uses-ceres

for how you should structure your CMakeLists to resolve this.
