### ISSUE TITLE
graph_test failing on VS2015x64 Release

### ISSUE THREAD

**Issue by Ardavel** [ceres-solver/ceres-solver#216]
"NonExistentEdge" test from graph_test.cc fails on VS2015x64 Release version. The problem is in "FindWithDefault" method (from map_util.h) which gets "value" parameter by reference and returns a reference to it. When "0.0" literal is passed in "EdgeWeight" method (from graph.h) the returned value is invalid. If Collection::value_type::second_type is double you could just remove & from return type of "FindWithDefault" method. The current code is unsafe if we pass an explicit value such as "0.0".
I didn't manage to reproduce the error on VS2013x64 Release and VS2015x64 Debug.

**Comment by sandwichmaker** [comment]
Thanks for reporting this, this is a subtle and pervasive bug in the code. I will work on fixing it.

**Comment by sandwichmaker** [comment]
@Ardavel Could you try https://ceres-solver-review.googlesource.com/#/c/8700/ and verify that this fixes the issue.

**Comment by Ardavel** [comment]
I can confirm that it helps with the issue. Thank you for fixing that.

**Comment by sandwichmaker** [comment]
Great, the fix has been submitted. Thank you for reporting and testing.
