### ISSUE TITLE
Error compiling Ceres with gflags on Ubuntu 16.04

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [ceres-solver/ceres-solver#219]
I have made decision to upgrade from Ubuntu 14.04 to 16.04. Hence, I had to recompile many of my libraries. This is mainly due to the fact that the content of the folder /usr/lib in 14.04 has been moved to /usr/lib/x86_64-linux-gnu in 16.04 :

locate libglog.so
/usr/lib/x86_64-linux-gnu/libglog.so
/usr/lib/x86_64-linux-gnu/libglog.so.0
/usr/lib/x86_64-linux-gnu/libglog.so.0.0.0

locate libgflags.so
/usr/lib/x86_64-linux-gnu/libgflags.so
/usr/lib/x86_64-linux-gnu/libgflags.so.2
/usr/lib/x86_64-linux-gnu/libgflags.so.2.1.2

I did encounter a few errors while recompiling Ceres, and I managed to solve them, but this error remains unsolved:

[ 87%] Linking CXX executable ../bin/helloworld_numeric_diff
../lib/libceres.so.1.12.0: undefined reference to `google::FlagRegisterer::FlagRegisterer(char const_, char const_, char const_, char const_, void_, void_)'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/helloworld_numeric_diff.dir/build.make:96: recipe for target 'bin/helloworld_numeric_diff' failed
make[2]: **\* [bin/helloworld_numeric_diff] Error 1
CMakeFiles/Makefile2:3034: recipe for target 'examples/CMakeFiles/helloworld_numeric_diff.dir/all' failed
make[1]: **\* [examples/CMakeFiles/helloworld_numeric_diff.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: **\* [all] Error 2

I did recompile both glog and gflags, and I can locate both .so libraries as shown above.

**Comment by alexsmac** [comment]
What is the output from CMake when configuring?  What it looks like is that you have enabled the MINIGLOG option, but using the full glog headers.

**Comment by Tariq-Abuhashim** [comment]
I checked, MINIGLOG is set OFF

Here is the output of   :   cmake ../ceres-solver

-- Detected Ceres version: 1.12.0 from /home/tabuhashim/Dev/ceres-solver/include/ceres/version.h
-- Found Eigen version 3.2.7: /usr/local/include/eigen3

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

-- A library with BLAS API found.
-- A library with LAPACK API found.
-- Found LAPACK library: /usr/lib/libopenblas.so;/usr/lib/libopenblas.so
-- Found BLAS library: /usr/lib/libopenblas.so
-- A library with BLAS API found.
-- Found AMD library: /usr/local/lib/libamd.a
-- Found AMD header in: /usr/local/include
-- Found CAMD library: /usr/local/lib/libcamd.a
-- Found CAMD header in: /usr/local/include
-- Found COLAMD library: /usr/local/lib/libcolamd.a
-- Found COLAMD header in: /usr/local/include
-- Found CCOLAMD library: /usr/local/lib/libccolamd.a
-- Found CCOLAMD header in: /usr/local/include
-- Found CHOLMOD library: /usr/local/lib/libcholmod.a
-- Found CHOLMOD header in: /usr/local/include
-- Found SuiteSparseQR library: /usr/local/lib/libspqr.a
-- Found SuiteSparseQR header in: /usr/local/include
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
-- Found SuiteSparse_config library: /usr/local/lib/libsuitesparseconfig.a
-- Found SuiteSparse_config header in: /usr/local/include
-- Adding librt: /usr/lib/x86_64-linux-gnu/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Did not find METIS library (optional SuiteSparse dependency)
-- Found SuiteSparse 4.4.6, building with SuiteSparse.
-- Found CXSparse version: 3.1.4, building with CXSparse.
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: /usr/local/lib/cmake/gflags
-- Detected gflags version: 2.2.0
-- Found Google Flags header in: /usr/local/include, in namespace: google
-- Found Google Log header in: /usr/local/include
-- Building with OpenMP.
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - not found
-- Looking for C++ include tr1/unordered_map
-- Looking for C++ include tr1/unordered_map - found
-- Found tr1/unordered_map/set in std::tr1 namespace.
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Failed
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE - Failed
-- Looking for C++ include tr1/memory
-- Looking for C++ include tr1/memory - found
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER - Success
-- Found shared_ptr in std::tr1 namespace using <tr1/memory> header.
-- Building Ceres as a shared library.
-- Enabling CERES_USE_OPENMP in Ceres config.h
-- Enabling CERES_HAVE_PTHREAD in Ceres config.h
-- Enabling CERES_HAVE_RWLOCK in Ceres config.h
-- Enabling CERES_TR1_UNORDERED_MAP in Ceres config.h
-- Enabling CERES_TR1_MEMORY_HEADER in Ceres config.h
-- Enabling CERES_TR1_SHARED_PTR in Ceres config.h
-- Enabling CERES_USING_SHARED_LIBRARY in Ceres config.h
-- Build the examples.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tabuhashim/Dev/ceres-bin

**Comment by Tariq-Abuhashim** [comment]
@alexsmac I solved this linking problem by giving a path hint using:
ccmake ../ceres-solver/ -DGFLAGS_LIBRARY_DIR_HINTS /usr/lib/x86_64-linux-gnu -DGFLAGS_PREFER_EXPORTED_GFLAGS_CMAKE_CONFIGURATION=OFF

**Comment by alexsmac** [comment]
How many versions of gflags & glog do you have installed?  It appears that you have two, one in /usr and one in /usr/local.  What is the value of GLOG_LIBRARY (visible in the advanced CMake ncurses GUI view accessible via <t>)?  Is it /usr/local/lib/libglog.so ?

**Comment by Tariq-Abuhashim** [comment]
-- Found Google Log header in: /usr/local/include, and Libraries in: /usr/local/lib/libglog.a
those are the values of ${GLOG_INCLUDE_DIRS} and ${GLOG_LIBRARY}, respectively.

**Comment by alexsmac** [comment]
Closing as this was a CMake configuration issue which has been resolved.

**Comment by Amazingren** [comment]
I also came across this problem ,and I find it is because
the VERSION of gcc/g++ is too low,
so I switch the VERSION
from 4.8 to 5.5,
then the problem was solved!
Hope could be help to you gays~
