### ISSUE TITLE
polynomial_test is failing

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#220]
https://people.debian.org/~debalance/ceres-solver_1.11.0.1-1_amd64.build

@debalance

**Comment by sandwichmaker** [comment]
@debalance can you try https://ceres-solver-review.googlesource.com/#/c/8680/

**Comment by debalance** [comment]
I just did: "100% tests passed, 0 tests failed out of 68"

**Comment by sandwichmaker** [comment]
@debalance could you test out the updated version of this CL. It now fixes the array comparison method, which is a more robust change but will also affect rotation_test.cc

**Comment by debalance** [comment]
Will do.

**Comment by debalance** [comment]
Works just as well: builds and tests successfully. :+1:

**Comment by sandwichmaker** [comment]
Should  be fixed at head.
