### ISSUE TITLE
gradient_checker_test failing on non-amd64 architectures

### ISSUE THREAD

**Issue by debalance** [ceres-solver/ceres-solver#222]
gradient_checker_test is failing on all of Debian's architectures except for amd64,
as you can see here: https://buildd.debian.org/status/package.php?p=ceres-solver

Build logs are linked there as well.

**Comment by debalance** [comment]
The relevant part:


22/68 Test #25: gradient_checker_test .......................***Failed    0.10 sec
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from GradientChecker
[ RUN      ] GradientChecker.SmokeTest
[       OK ] GradientChecker.SmokeTest (0 ms)
[ RUN      ] GradientChecker.TestCorrectnessWithLocalParameterizations
/«BUILDDIR»/ceres-solver-1.11.0+git20160903/internal/ceres/gradient_checker_test.cc:507: Failure
Value of: results.local_jacobians.at(0) == (j0 + j0_offset) * global_J_local
  Actual: false
Expected: true
E0904 13:38:16.147534 16393 gradient_checking_cost_function.cc:144] Gradient error detected. Terminating solver.
[  FAILED  ] GradientChecker.TestCorrectnessWithLocalParameterizations (3 ms)
[----------] 2 tests from GradientChecker (3 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (3 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] GradientChecker.TestCorrectnessWithLocalParameterizations

 1 FAILED TEST

**Comment by sandwichmaker** [comment]
Could you try the master branch please? it should be fixed.

**Comment by debalance** [comment]
Hi,
it already worked with Patchset 4 from https://ceres-solver-review.googlesource.com/#/c/8740/ and there's no difference to the commit in master.

I will upload latest HEAD in 3 days when the current upload has migrated to Testing.

**Comment by sandwichmaker** [comment]
sweet, closing this then.
