### ISSUE TITLE
gradient_checker_test fails on on i386

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#223]
build logs are available here:
https://buildd.debian.org/status/fetch.php?pkg=ceres-solver&arch=i386&ver=1.11.0%2Bgit20160903-1&stamp=1472996344
https://buildd.debian.org/status/fetch.php?pkg=ceres-solver&arch=kfreebsd-i386&ver=1.11.0%2Bgit20160903-1&stamp=1472996844

**Comment by sandwichmaker** [comment]
@dgossow can you look into this please, seems like a straightforward issue of exact equality being tested. Also I noticed that there is isApprox being used in this test, which can also be replaced by IsClose or ExpectClose..

**Comment by sandwichmaker** [comment]
same as https://github.com/ceres-solver/ceres-solver/issues/222 with more detailed logs there.

**Comment by dgossow** [comment]
I'll look into it, sorry for the snafu.

**Comment by dgossow** [comment]
CL open: https://ceres-solver-review.googlesource.com/#/c/8740/ 

IsClose and ExpectClose don't work directly on matrices, or am I missing something.

I would say calling IsApprox on an Eigen matrix is generally a good way to compare it to another matrix. Maybe there should be a macro or function definition for this in Ceres?
