### ISSUE TITLE
Solver fails to build with GCC on macos

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#224]
Steps to reproduce
1. Install gcc using homebrew.
2. cmake ../  -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/Users/sameeragarwal/homebrew/bin/g++-6 -DCMAKE_C_COMPILER=/Users/sameeragarwal/homebrew/bin/gcc-6
3. ninja cubic_interpolation_test leads to 

[master] build: ninja cubic_interpolation_test
[1/1] Linking CXX executable bin/cubic_interpolation_test
FAILED: bin/cubic_interpolation_test 
: && /Users/sameeragarwal/homebrew/bin/g++-6   -fopenmp -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -O3 -DNDEBUG  -msse3 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  internal/ceres/CMakeFiles/cubic_interpolation_test.dir/cubic_interpolation_test.cc.o  -o bin/cubic_interpolation_test  lib/libtest_util.a lib/libceres.a lib/libgtest.a /Users/sameeragarwal/homebrew/lib/libspqr.dylib /Users/sameeragarwal/homebrew/lib/libtbb.dylib /Users/sameeragarwal/homebrew/lib/libtbbmalloc.dylib /Users/sameeragarwal/homebrew/lib/libcholmod.dylib /Users/sameeragarwal/homebrew/lib/libccolamd.dylib /Users/sameeragarwal/homebrew/lib/libcamd.dylib /Users/sameeragarwal/homebrew/lib/libcolamd.dylib /Users/sameeragarwal/homebrew/lib/libamd.dylib -framework Accelerate /Users/sameeragarwal/homebrew/lib/libsuitesparseconfig.dylib /Users/sameeragarwal/homebrew/lib/libmetis.dylib /Users/sameeragarwal/homebrew/lib/libcxsparse.dylib -framework Accelerate /Users/sameeragarwal/homebrew/lib/libsuitesparseconfig.dylib /Users/sameeragarwal/homebrew/lib/libmetis.dylib /Users/sameeragarwal/homebrew/lib/libcxsparse.dylib -lgomp /Users/sameeragarwal/homebrew/lib/libgflags.2.1.2.dylib /Users/sameeragarwal/homebrew/lib/libglog.dylib -Wl,-rpath,/Users/sameeragarwal/homebrew/lib && :
Undefined symbols for architecture x86_64:
  "google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()", referenced from:
      std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >\* google::MakeCheckOpString<int, int>(int const&, int const&, char const*) in cubic_interpolation_test.cc.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

**Comment by alexsmac** [comment]
Was your version of glog here: /Users/sameeragarwal/homebrew/lib/libglog.dylib built with C++11 enabled?  I'm assuming it was built with OS X Clang, which does not by default pass -std=c++11, unless you configure it to do so in Homebrew.

**Comment by sandwichmaker** [comment]
its the default homebrew version.

**Comment by sandwichmaker** [comment]
[master] build: brew info glog
glog: stable 0.3.4 (bottled)
Application-level logging library
https://github.com/google/glog
/Users/sameeragarwal/homebrew/Cellar/glog/0.3.4 (24 files, 434.4K) *
  Built from source on 2015-06-29 at 15:13:54
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/glog.rb
==> Dependencies
Required: gflags ✔
[master] build:

**Comment by sandwichmaker** [comment]
cmake ../ -G Ninja -DCMAKE_CXX_COMPILER=/Users/sameeragarwal/homebrew/bin/g++-6 -DCMAKE_C_COMPILER=/Users/sameeragarwal/homebrew/bin/gcc-6 -DCXX11=ON

and 

cmake ../ -G Ninja -DCMAKE_CXX_COMPILER=/Users/sameeragarwal/homebrew/bin/g++-6 -DCMAKE_C_COMPILER=/Users/sameeragarwal/homebrew/bin/gcc-6

fail with the same error too.

**Comment by keir** [comment]
Is this still relevant?

**Comment by sandwichmaker** [comment]
Closing.
