### ISSUE TITLE
Some errors when built in vs2015

### ISSUE THREAD

**Issue by tmac1002** [ceres-solver/ceres-solver#227]
Hi,
When I was ready to built ceres in vs2015, there are always some errors seemed like unlinking lib. But I have already generate sln by cmake successfully. I have no idea why always encounter these errors. Could you help me look at it.

Severity    Code    Description Project File    Line    Suppression State

Error   LNK2019 unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageVoidify::LogMessageVoidify(void)" (__imp_??0LogMessageVoidify@google@@QEAA@XZ) referenced in function "bool __cdecl ceres::`anonymous namespace'::LineSearchOptionsAreValid(struct ceres::Solver::Options const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?LineSearchOptionsAreValid@?A0x91b87f78@ceres@@YA_NAEBUOptions@Solver@2@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) ceres   D:\Theia\ceres-solver-1.11.0\build\internal\ceres\solver.obj    1  
Error   LNK2001 unresolved external symbol "__declspec(dllimport) public: __cdecl google::LogMessageVoidify::LogMessageVoidify(void)" (__imp_??0LogMessageVoidify@google@@QEAA@XZ)  ceres   D:\Theia\ceres-solver-1.11.0\build\internal\ceres\trust_region_minimizer.obj    1   

Error   LNK2019 unresolved external symbol "__declspec(dllimport) public: void __cdecl google::LogMessageVoidify::operator&(class std::basic_ostream<char,struct std::char_traits<char> > &)" (__imp_??ILogMessageVoidify@google@@QEAAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z) referenced in function "bool __cdecl ceres::`anonymous namespace'::LineSearchOptionsAreValid(struct ceres::Solver::Options const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?LineSearchOptionsAreValid@?A0x91b87f78@ceres@@YA_NAEBUOptions@Solver@2@PEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)    ceres   D:\Theia\ceres-solver-1.11.0\build\internal\ceres\solver.obj    1  
Error   LNK2001 unresolved external symbol "__declspec(dllimport) public: void __cdecl google::LogMessageVoidify::operator&(class std::basic_ostream<char,struct std::char_traits<char> > &)" (__imp_??ILogMessageVoidify@google@@QEAAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@@Z) ceres   D:\Theia\ceres-solver-1.11.0\build\internal\ceres\trust_region_minimizer.obj    1   

Error   LNK2019 unresolved external symbol __imp_PathMatchSpecA referenced in function "public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl google::`anonymous namespace'::CommandLineFlagParser::ProcessOptionsFromStringLocked(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,enum google::FlagSettingMode)" (?ProcessOptionsFromStringLocked@CommandLineFlagParser@?A0x97e428f6@google@@QEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV45@W4FlagSettingMode@3@@Z)  ceres   D:\Theia\ceres-solver-1.11.0\build\internal\ceres\gflags_static.lib(gflags.obj) 1   

Error   LNK1120 3 unresolved externals  ceres   D:\Theia\ceres-solver-1.11.0\build\bin\Release\ceres.dll    1

**Comment by NeroBurner** [comment]
I don't know if it is the same problem but try to put the following into your projects cmake file
```
if(WIN32)
	add_definitions(/DGOOGLE_GLOG_DLL_DECL=)
endif()
```

with it I get 904 warnings, but my project compiles successfully (msvc2012)

**Comment by alexsmac** [comment]
Are you trying to compile Ceres, Theia (which uses Ceres), or something else that uses Theia (and thus Ceres)?

The CMake rules for building Ceres should always link glog if it is available (and Ceres is not configured to use MINIGLOG).  Although the Ceres examples depend on gflags, Ceres itself does not, glog however can (and typically does) depend on gflags.

If you are trying to build a project which *uses* Ceres, then you should ideally use CMake to build that project, and use find_package(Ceres) as detailed [here](http://ceres-solver.org/building.html#using-ceres-with-cmake) as then CMake will handle adding Ceres' public dependencies (such as glog if enabled) to the build requirements for the project using Ceres.  If you do this manually, you need to add glog, not just the Ceres library as dependencies if you built Ceres with glog.

**Comment by alexsmac** [comment]
Closing this issue as no follow up information was provided, please re-open this issue providing more information about your setup if this is still an issue.

**Comment by wguo68** [comment]
I have the same problem. But the link can't open.

**Comment by csc-std** [comment]
`// This class is used to explicitly ignore values in the conditional
// logging macros.  This avoids compiler warnings like "value computed
// is not used" and "statement has no effect".

class GOOGLE_GLOG_DLL_DECL LogMessageVoidify {
 public:
  LogMessageVoidify() { }
  // This has to be an operator with a precedence lower than << but
  // higher than ?:
  void operator&(std::ostream&) { }
};`
actually,' LogMessageVoidify' is not necessary. maybe VS can't accept '__declspec(dllexport))' for inline function

**Comment by shanexn** [comment]
I met the same problem, and figured it out under both Release and Debug in VS2017 by doing two steps:
1. define "GOOGLE_GLOG_DLL_DECL" before including logging.h;
2. link "shlwapi.lib" in your project.
 I hope this will help.
