### ISSUE TITLE
Summary.initial_cost inaccurate?

### ISSUE THREAD

**Issue by NeroBurner** [ceres-solver/ceres-solver#228]
I was playing around with ceres 1.11.0 on Ubuntu 14.04 and 16.04 (amd64)

I was trying to solve a problem and then using the resulting values as start values for a second optimization run. Even though the difference of the output values is in the range of e-12 to e-15 the initial cost returned by summary.initial_cost is much higher than the final cost. I was expecting to have nearly the same for initial and final cost.

The reported final cost of the two runs is nearly identical

**Comment by sandwichmaker** [comment]
Could you provide more details or a reproduction please. Or at least a log. I do not quite understand the behaviour you are observing.

**Comment by NeroBurner** [comment]
Thanks for the reply. I've created a Gist with a small example creating some 3D points, rotate them and let ceres find out what the rotation was.

The output of `ceres_sample` sample is
```
$ ./ceres_sample
summary.initial_cost: 0.000246192
summary.final_cost:   2.02339e-18
summary.iterations:   3
roll:  1.3
pitch: 1.2
yaw:   1.1
tx:    -3.00428e-10
ty:    -1.2917e-09
tz:    5
```
As you can see, even though the start values are exactly the right values the initial cost ist different to the final cost.

Even If I set the tx, ty, tz values to the output values (as seen below) the initial cost is still not the same as the final cost
```
translation[0] = -3.00428e-10;
translation[1] = -1.2917e-09;
translation[2] = 5;
```
and the execution
```
$ make && ./ceres_sample 
summary.initial_cost: 0.000246192
summary.final_cost:   2.02339e-18
summary.iterations:   3
roll:  1.3
pitch: 1.2
yaw:   1.1
tx:    -3.00427e-10
ty:    -1.2917e-09
tz:    5
```

**Comment by sandwichmaker** [comment]
as you can see there is a small difference in tx, it is entirely possible that your objective function is sensitive to small changes.

**Comment by NeroBurner** [comment]
you are right. the initial values are a bit off and therefore produce a different initial_cost. Using `cout.precision(17);` to print the full double precision on my pc to set them as initial values for the next run. Then ceres only needs one iteration and has identical initial and final_cost
