### ISSUE TITLE
Compiling rotation_test.cc fails in Fedora 24 with gcc 6.1.1

### ISSUE THREAD

**Issue by andreasg123** [ceres-solver/ceres-solver#229]
There are compiler errors in Fedora 24 with gcc 6.1.1.  After adding `Wno-error=address -Wno-error=nonnull-compare` to `CMakeLists.txt`, the errors are replaced by warnings and everything builds and tests fine:

	IF (UNIX)
	  # GCC is not strict enough by default, so enable most of the warnings.
	  SET(CMAKE_CXX_FLAGS
	    "${CMAKE_CXX_FLAGS} -Werror=all -Werror=extra -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-error=address -Wno-error=nonnull-compare")
	ENDIF (UNIX)

Is there a reason why you turned all warnings into errors (`-Werror=all` instead of `-Wall`)?

Compiler errors:

	Scanning dependencies of target dynamic_compressed_row_sparse_matrix_test
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc: In instantiation of ‘bool ceres::internal::IsNearAngleAxisMatcherP<expected_type>::gmock_Impl<arg_type>::MatchAndExplain(arg_type, testing::MatchResultListener*) const [with arg_type = const double (&)[3]; expected_type = const double*]’:
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:1129:1:   required from here
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:134:11: error: the compiler can assume that the address of ‘arg’ will never be NULL [-Werror=address]
	   if (arg == NULL) {
	           ^
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc: In instantiation of ‘bool ceres::internal::IsNear3x3MatrixMatcherP<expected_type>::gmock_Impl<arg_type>::MatchAndExplain(arg_type, testing::MatchResultListener*) const [with arg_type = const double (&)[9]; expected_type = double*]’:
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:1129:1:   required from here
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:204:11: error: the compiler can assume that the address of ‘arg’ will never be NULL [-Werror=address]
	   if (arg == NULL) {
	           ^
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc: In instantiation of ‘bool ceres::internal::IsOrthonormalMatcher::gmock_Impl<arg_type>::MatchAndExplain(arg_type, testing::MatchResultListener*) const [with arg_type = const double (&)[9]]’:
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:1129:1:   required from here
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:175:11: error: the compiler can assume that the address of ‘arg’ will never be NULL [-Werror=address]
	   if (arg == NULL) {
	           ^
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc: In instantiation of ‘bool ceres::internal::IsNearAngleAxisMatcherP<expected_type>::gmock_Impl<arg_type>::MatchAndExplain(arg_type, testing::MatchResultListener*) const [with arg_type = const double (&)[3]; expected_type = double*]’:
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:1129:1:   required from here
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:134:11: error: the compiler can assume that the address of ‘arg’ will never be NULL [-Werror=address]
	   if (arg == NULL) {
	           ^
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc: In instantiation of ‘bool ceres::internal::IsNearQuaternionMatcherP<expected_type>::gmock_Impl<arg_type>::MatchAndExplain(arg_type, testing::MatchResultListener*) const [with arg_type = const double (&)[4]; expected_type = double*]’:
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:1129:1:   required from here
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:85:11: error: the compiler can assume that the address of ‘arg’ will never be NULL [-Werror=address]
	   if (arg == NULL) {
	           ^
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc: In instantiation of ‘bool ceres::internal::IsNormalizedQuaternionMatcher::gmock_Impl<arg_type>::MatchAndExplain(arg_type, testing::MatchResultListener*) const [with arg_type = const double (&)[4]]’:
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:1129:1:   required from here
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:65:11: error: the compiler can assume that the address of ‘arg’ will never be NULL [-Werror=address]
	   if (arg == NULL) {
	           ^
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc: In member function ‘bool ceres::internal::IsNear3x3MatrixMatcherP<expected_type>::gmock_Impl<arg_type>::MatchAndExplain(arg_type, testing::MatchResultListener*) const [with arg_type = const double (&)[9]; expected_type = double*]’:
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:204:3: error: nonnull argument ‘arg’ compared to NULL [-Werror=nonnull-compare]
	   if (arg == NULL) {
	   ^~
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc: In member function ‘bool ceres::internal::IsOrthonormalMatcher::gmock_Impl<arg_type>::MatchAndExplain(arg_type, testing::MatchResultListener*) const [with arg_type = const double (&)[9]]’:
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:175:3: error: nonnull argument ‘arg’ compared to NULL [-Werror=nonnull-compare]
	   if (arg == NULL) {
	   ^~
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc: In member function ‘bool ceres::internal::IsNearQuaternionMatcherP<expected_type>::gmock_Impl<arg_type>::MatchAndExplain(arg_type, testing::MatchResultListener*) const [with arg_type = const double (&)[4]; expected_type = double*]’:
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:85:3: error: nonnull argument ‘arg’ compared to NULL [-Werror=nonnull-compare]
	   if (arg == NULL) {
	   ^~
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc: In member function ‘bool ceres::internal::IsNormalizedQuaternionMatcher::gmock_Impl<arg_type>::MatchAndExplain(arg_type, testing::MatchResultListener*) const [with arg_type = const double (&)[4]]’:
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:65:3: error: nonnull argument ‘arg’ compared to NULL [-Werror=nonnull-compare]
	   if (arg == NULL) {
	   ^~
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc: In member function ‘bool ceres::internal::IsNearAngleAxisMatcherP<expected_type>::gmock_Impl<arg_type>::MatchAndExplain(arg_type, testing::MatchResultListener*) const [with arg_type = const double (&)[3]; expected_type = double*]’:
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:134:3: error: nonnull argument ‘arg’ compared to NULL [-Werror=nonnull-compare]
	   if (arg == NULL) {
	   ^~
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc: In member function ‘bool ceres::internal::IsNearAngleAxisMatcherP<expected_type>::gmock_Impl<arg_type>::MatchAndExplain(arg_type, testing::MatchResultListener*) const [with arg_type = const double (&)[3]; expected_type = const double*]’:
	.../ceres-solver-1.10.0/internal/ceres/rotation_test.cc:134:3: error: nonnull argument ‘arg’ compared to NULL [-Werror=nonnull-compare]
	   if (arg == NULL) {
	   ^~

**Comment by sandwichmaker** [comment]
This has been fixed on the master branch I believe.

**Comment by andreasg123** [comment]
Confirmed.  The current version does not specify `-Werror=all`.  Sorry for reporting an issue for an older version.

**Comment by sandwichmaker** [comment]
No problem.
