### ISSUE TITLE
bundle_adjustment_test never finishes on armel

### ISSUE THREAD

**Issue by debalance** [ceres-solver/ceres-solver#231]
Hi,

if you look at the build logs on https://buildd.debian.org/status/package.php?p=ceres-solver you see that ceres-solver fails to build on armel because bundle_adjustment_test never finishes.

It has never successfully built on armel before, so that's not a regression.

If you need more detailed information I can access an armel porterbox from Debian and run tests for you.

**Comment by sandwichmaker** [comment]
Phillip,
what is armel? I will take a look.

**Comment by debalance** [comment]
"The ARM EABI (armel) port targets a range of older 32-bit ARM devices, particularly those used in NAS hardware and a variety of *plug computers." - https://www.debian.org/ports/arm/index.en.html

See also https://wiki.debian.org/ArmEabiPort

**Comment by sandwichmaker** [comment]
I looked at the logs and as expected its not the build but the test that is failing, or rather timing out. It is likely the case that this test is too heavy duty for this cpu to execute. This is already evident in how long it takes for this CPU to execute the rotation test, which is the second heaviest test in ceres but is significantly faster than bundle_adjustment_test.

**Comment by sandwichmaker** [comment]
on my mac bundle adjustment test is 8x slower than rotation test. since it is taking 4 mins on the machine you are using, this is likely not workable on armel.

**Comment by debalance** [comment]
Is there a way to make the test more verbose? The buildd kills it because there's no output for 2.5 half hours. I've just started a manual build on https://db.debian.org/machines.cgi?host=abel to see what happens there.

**Comment by debalance** [comment]
The test passes alright, after 11353 seconds, that's ~3.1 hours.

**Comment by sandwichmaker** [comment]
sorry the google test framework we use prides itself on being silent when there are no errors.  But are you okay with closing this issue inlight of the manual build.

**Comment by debalance** [comment]
yeah that's fine
