### ISSUE TITLE
Openmp multi-thread not allowed in Evaluation() function

### ISSUE THREAD

**Issue by weipengxumpi** [ceres-solver/ceres-solver#232]
When calling CostFunction::Evaluation(), ceres assigned a thread to each residual block, and in each thread, it's not allowed to run anything in parallel. Even though options.num_threads is set to 1, the issue still exists. I suggest not to use openmp to create threads when calling Evaluation(), if options.num_threads is set to 1.

Weipeng Xu

**Comment by sandwichmaker** [comment]
Closing this based on the discussion on the mailinglist.
