### ISSUE TITLE
how to add dependency libraries for ceres-solver in cmake-gui

### ISSUE THREAD

**Issue by jagadish482** [ceres-solver/ceres-solver#238]
I read the documentation of ceres-solver library from http://ceres-solver.org/building.html#options-controlling-ceres-configuration.
i done according your documentation for dependency. now i am confused adding paths to 

GLOG_LIBRARY_DIR_HINTS,
GFLAGS_LIBRARY_DIR_HINTS,
SUITESPARSE_LIBRARY_DIR_HINTS,
CXSPARSE_LIBRARY_DIR_HINTS

for the dependency libraries of <NAME>_INCLUDE_DIR_HINTS i added direct build packages.

**Comment by sandwichmaker** [comment]
@alexsmac is this actionable? if not please close it.
