### ISSUE TITLE
ceres solver installation fails on compiling helloworld

### ISSUE THREAD

**Issue by ramanpreet9** [ceres-solver/ceres-solver#239]
I followed all the steps on the website to install ceres-solver on ubuntu 14.04 LTS. All the tests worked and even the example in bin folder ran properly.

Next I wanted to compile helloworld in the example folder. I commented out everything other than the following:

`#include "ceres/ceres.h"
#include "glog/logging.h"

using ceres::AutoDiffCostFunction;
using ceres::CostFunction;
using ceres::Problem;
using ceres::Solver;
using ceres::Solve;

int main(int argc, char** argv) {

 google::InitGoogleLogging(argv[0]);

  double x = 0.5;
  const double initial_x = x;

  std::cout << "x : " << initial_x
            << " -> " << x << "\n";

  return 0;
}` 

i used gcc to run it by :   g++ helloworld.cc -lceres -std=c++11 -I/usr/include/eigen3/
I get the following error:
/tmp/ccdovdLF.o: In function `main':
helloworld.cc:(.text+0x1a): undefined reference to `google::InitGoogleLogging(char const*)'
collect2: error: ld returned 1 exit status

I am not sure why thats happening. I installed both glog and gflags as mentioned in the steps for ceres solver installation. Any suggestions what to do here?

**Comment by alexsmac** [comment]
As explained here: http://ceres-solver.org/building.html#understanding-the-cmake-package-system

Ceres exports/installs itself as a CMake target, which includes all the information required to link against Ceres, including its headers and its public link dependencies.  It is not sufficient to link against just the Ceres library itself, as you will be missing the public link dependencies, in this case: glog.  The exported Ceres CMake target will also include required compile flags (such as enabling C++11 if Ceres was built with CXX11 enabled).

You should use CMake to build the hello_world example as shown here: http://ceres-solver.org/building.html#using-ceres-with-cmake

**Comment by ramanpreet9** [comment]
Thank you for your reply. I somehow missed the cmake example in the reference page. It runs fine with the cmake example.

**Comment by calocedrus** [comment]
@alexsmac the link http://ceres-solver.org/building.html#understanding-the-cmake-package-system you make reference to doesn't exist anymore. Is there a new page similar to the gone one? As @ramanpreet9 I'm struggling to compile a single standalone ceres program.

**Comment by alexsmac** [comment]
@calocedrus the updated links are now in the Installation section of the Ceres documentation [here](http://ceres-solver.org/installation.html#using-ceres-with-cmake) and [here](http://ceres-solver.org/installation.html#installing-a-project-with-cmake-vs-exporting-its-build-directory).

**Comment by calocedrus** [comment]
Thanks Alex!
