### ISSUE TITLE
New stable version?

### ISSUE THREAD

**Issue by ilovezfs** [ceres-solver/ceres-solver#240]
Since the current stable release is no longer compatible with the current stable release of eigen, downstream for Homebrew we're considering vendoring a lower version of eigen into the ceres-solver formula as a stop-gap measure until a new stable release comes out. Any idea on the ETA until there's an actual release not a release candidate?

Specifically, I'd like to avoid merging this craziness if at all possible:
https://github.com/Homebrew/homebrew-science/pull/4626

**Comment by sandwichmaker** [comment]
We are cutting another release candiate in the next few mins. So as soon as it stabilizes we will cut a release. Basically, bug fixes are the only things going in at this point.

**Comment by sandwichmaker** [comment]
RC3 is out for people to test. If nothing major shows up, I will plan on cutting a release in the first week of december.

**Comment by sandwichmaker** [comment]
There is now a new stable version :)

**Comment by ilovezfs** [comment]
Thanks! New version shipped: https://github.com/Homebrew/homebrew-science/pull/4676.
