### ISSUE TITLE
NO_CONVERGENCE  using NumericDiffCostFunction

### ISSUE THREAD

**Issue by wangwei19900806** [ceres-solver/ceres-solver#243]
When I applyed the solver,the iter gradient was zero; Anybody can tell me why?

**Comment by sandwichmaker** [comment]
@wangwei19900806 there is no way to diagnose the problem you are describing without more details of your implementation and an execution log.

**Comment by sandwichmaker** [comment]
Closing this issue as it does not have enough details, please feel free to open it with more details.
