### ISSUE TITLE
Bounds constrained optimization fails on a simple optimization problem.

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#245]
https://gist.github.com/anonymous/cbe4374ba39fad458fe7b1827183cacd

**Comment by dgossow** [comment]
Is this the same as #187?

**Comment by sandwichmaker** [comment]
Sort of. It's not clear if the correct implementation of that algorithm
will solve this, but that would be the first thing I would try.

**Comment by sandwichmaker** [comment]
Closing this one as a dup.
