### ISSUE TITLE
GradientProblemSolver::Options does not support update_state_every_iteration

### ISSUE THREAD

**Issue by bchretien** [ceres-solver/ceres-solver#246]
While implementing a callback for `GradientProblemSolver`, I realized that `update_state_every_iteration` is not supported for that kind of solver. Yet, `GradientProblemSolver::Options::callbacks`'s documentation hints at the contrary ([here](https://github.com/ceres-solver/ceres-solver/blob/f21c17064bbcdf9b2db0b50805eef51a609d61d4/include/ceres/gradient_problem_solver.h#L262-L268)):

```cpp
// Callbacks are executed in the order that they are specified in
// this vector. By default, parameter blocks are updated only at
// the end of the optimization, i.e when the Minimizer
// terminates. This behaviour is controlled by
// update_state_every_variable. If the user wishes to have access
// to the update parameter blocks when his/her callbacks are
// executed, then set update_state_every_iteration to true.
```

Are there any plans to support this option, or am I missing something? Otherwise, the documentation should probably be updated. Also, `update_state_every_variable` is referenced, but I'm assuming this is a typo/legacy name for  `update_state_every_iteration` (it is also present in some other parts of the documentation).

This was tested with Ceres 1.12.0.

**Comment by sandwichmaker** [comment]
@bchretien thanks for reporting this, yes this is a bug in gradientproblemsolver, even though the underlying machinery actually supports this. You can either submit a patch or I can look into it soonish.

**Comment by bchretien** [comment]
@sandwichmaker thanks for the quick reply, I probably won't have the time to work on a patch during the next few weeks, but I'll keep you posted if that changes.

**Comment by bchretien** [comment]
I think I solved the issue (cf. [this](https://github.com/ceres-solver/ceres-solver/compare/master...bchretien:fix/issue-246)). I'll forward this to Gerrit when I find the time.

**Comment by sandwichmaker** [comment]
@bchretien that CL looks pretty good. Please do consider sending it to gerrit, I will review as soon as I can.

**Comment by sandwichmaker** [comment]
@bchretien gentle ping :)

**Comment by aecins** [comment]
@bchretien Another gentle ping. Ran into this issue this week. It would be really great to see per iteration updates with the gradient solver.

**Comment by keir** [comment]
@bchretien Would happy review your patch in Gerrit; can you please push it over there so we can get it submitted? Due to the CLA issue we can't accept GitHub pull requests (and we want to keep our review history centralized).

**Comment by brentmorgan1987** [comment]
Is there a quick fix to see my solution per every iteration?  This is needed for me :)....
I could technically write the solution for every Evaluate() call but it would probably slow it down, compared to a "real" fix.  Thanks,

Best,
Brent

**Comment by sandwichmaker** [comment]
https://ceres-solver-review.googlesource.com/c/ceres-solver/+/11780 is out for review.

**Comment by brentmorgan1987** [comment]
I implemented the changes.  What am I supposed to see?  I do not see any changes in the stdout.

I set the 
update_state_every_iteration = true 
in gradient_problem_solver.h

Best,
Brent
