### ISSUE TITLE
Example "pose_graph_3d" failed with link error

### ISSUE THREAD

**Issue by riyueshi** [ceres-solver/ceres-solver#247]
I have built the ceres-solver 1.2.1, everything seems fine while building the ceres.lib. But the example project failed with the foltlowing error:
pose_graph_3d.obj : error LNK2001: Unresolved External Symbol "public: virtual bool __cdecl ceres::EigenQuaternionParameterization::Plus(double const *,double const *,double *)const " (?Plus@EigenQuaternionParameterization@ceres@@UEBA_NPEBN0PEAN@Z)
1>pose_graph_3d.obj : error LNK2001: Unresolved External Symbol "public: virtual bool __cdecl ceres::EigenQuaternionParameterization::ComputeJacobian(double const *,double *)const " (?ComputeJacobian@EigenQuaternionParameterization@ceres@@UEBA_NPEBNPEAN@Z)
Is there any tips for this problem?
PS. other examples just work well, and the Eigen version is 3.3.1.

**Comment by riyueshi** [comment]
I find that all the examples can successfully build but can not run which is caused by the golglib linked both static and dynamic. After fixed that problem the example "pose_graph_3d" can successfully build

**Comment by hollow857** [comment]
hello,how to fix this problem?
