### ISSUE TITLE
FindGlog.cmake cannot find installed glog on windows

### ISSUE THREAD

**Issue by jasjuang** [ceres-solver/ceres-solver#250]
I am on Visual studio 2015 and Windows 10.

When I install [glog](https://github.com/google/glog) through the standard procedure of 

``````
git clone https://github.com/google/glog/
mkdir build 
cd build
cmake -A x64 ..
``````

It generates a solution file called google-glog.sln. The problem is when I build the entire solution and build the INSTALL project, glog got installed to C:\Program Files (x86)\google-glog

but

FindGlog.cmake in Ceres is expecting glog to be installed in C:\Program Files (x86)\glog, thus causing it to fail to find glog for me. I understand I can use cmake-gui to specify and get pass it, but I have to install this for multiple computers and I need this to be automatic.

**Comment by alexsmac** [comment]
As noted in #249 this is because the default install location on windows is: C:/Program Files/<PROJECT_NAME> and so if glog (which has the project name google-glog) is installed via CMake on Windows, then the install location will include google-glog, whereas if it is installed via a different mechanism it would just be glog.

This should be fixed in this CL: https://ceres-solver-review.googlesource.com/#/c/9300/

**Comment by alexsmac** [comment]
This has just been merged into master, but please test that it works for you there.

**Comment by jasjuang** [comment]
When I run `cmake -A x64 ..` There is a new error "Failed to find installed glog CMake configuration", which I believe is because it is looking for the file glog-config.cmake but it is not there. When I look at the INSTALL folder of gflags there is the "include" folder, "lib" folder and "cmake" folder, whereas in glog there is only the "include" folder and "lib" folder, so I think it might be a glog problem. I will file an issue at glog and see what they say.

**Comment by jasjuang** [comment]
Actually, glog-config.cmake is in C:\Program Files (x86)\google-glog\lib\cmake\glog, could you fix FindGlog.cmake so it's able to locate it?

**Comment by alexsmac** [comment]
Please try this CL: https://ceres-solver-review.googlesource.com/#/c/9340/ - it should fix the problem for you, albeit this is really a glog issue, the project name should match the installed name.

**Comment by jasjuang** [comment]
Thanks. I tested and it solves it for me.
