### ISSUE TITLE
Alignment Issue with Eigen 3.3.1, C++11

### ISSUE THREAD

**Issue by groundmelon** [ceres-solver/ceres-solver#251]
Hi, I've met a problem when running my code (a small scale Structure-From-Motion problem with auto-differentiation).

Environments and configures:
* ceres version 1.12.0 commit 029799d757b4ed2be5af64899178928f18cb6e28
* Eigen 3.3.1 f562a193118d
* g++ (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4
* CXX11=on when compiling ceres

My code crashed at ```ceres::Solve(options, &problem, &summary);```. The stdout is:
```
/usr/local/include/eigen3/Eigen/src/Core/DenseStorage.h:128: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 32>::plain_array() [with T = double; int Size = 16; int MatrixOrArrayOptions = 0]: Assertion `(internal::UIntPtr(eigen_unaligned_array_assert_workaround_gcc47(array)) & (31)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.
```

After checking the trackback and sources, I suspect that [these lines of code](https://github.com/ceres-solver/ceres-solver/blob/1.12.0/include/ceres/jet.h#L243-L251) in [include/ceres/jet.h](https://github.com/ceres-solver/ceres-solver/blob/1.12.0/include/ceres/jet.h) causes the problem:
```c++
  static constexpr bool kShouldAlignMatrix =
      16 <= ::ceres::port_constants::kMaxAlignBytes;
  static constexpr int kAlignHint = kShouldAlignMatrix ?
      Eigen::AutoAlign : Eigen::DontAlign;
  // Default to the native alignment of double if 16-byte alignment is not
  // supported.  We cannot use alignof(T) as if we do, GCC complains that the
  // alignment 'is not an integer constant', although Clang accepts it.
  static constexpr size_t kAlignment = kShouldAlignMatrix ? 16 : alignof(double);
  alignas(kAlignment) Eigen::Matrix<T, N, 1, kAlignHint> v;
```

In previous versions of Eigen(3.2.x), it only takes advantage of SSE instructions, which need 16-bytes alignment. However, in newer version of Eigen(3.3.x), it supports AVX instructions, which need 32-bytes alignment. I'm not sure whether the **hard-coded 16** in [these lines of code](https://github.com/ceres-solver/ceres-solver/blob/1.12.0/include/ceres/jet.h#L243-L251) will cause some compatibility issues with Eigen 3.3.1 and CXX11=on.

By the way, for reference, I've also changed all the 16 into 32 in [these lines of code](https://github.com/ceres-solver/ceres-solver/blob/1.12.0/include/ceres/jet.h#L243-L251), recompiled my program and rerun it. The program was able to successfully solve the problem. But this modification must not be compatible with Eigen 3.2.x.

I'm guessing about there might need some code for compatibility between Eigen 3.2.x and Eigen 3.3.x near  [these lines of code](https://github.com/ceres-solver/ceres-solver/blob/1.12.0/include/ceres/jet.h#L243-L251).

Thanks!

**Comment by alexsmac** [comment]
This should now be fixed in master.
