### ISSUE TITLE
Build fail - jet.h ScalarBinaryOpTraits

### ISSUE THREAD

**Issue by AustinDeric** [ceres-solver/ceres-solver#252]
Commit d05515b3eb27e2f3880884a878354db035006999 is the last version i am able to build.

Here is a snippet of the build error:
/home/aderic/industrial_cal_ws/src/ceres-solver/include/ceres/jet.h:887:8: error: ‘ScalarBinaryOpTraits’ is not a class template

I have the following build environment and warning:
-- Found Eigen version 3.2.92: /usr/include/eigen3

   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm
   which can still use the EIGEN_SPARSE_QR algorithm.

-- Found LAPACK library: /usr/lib/liblapack.so;/usr/lib/libblas.so
-- Found BLAS library: /usr/lib/libblas.so
-- Found SuiteSparse 4.4.6, building with SuiteSparse.
-- Failed to find CXSparse - Could not find CXSparse include directory, set CXSPARSE_INCLUDE_DIR to directory containing cs.h
-- Did not find CXSparse, Building without CXSparse.
-- Found Google Flags header in: /usr/include, in namespace: google
-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
-- Building with OpenMP.
-- Found tr1/unordered_map/set in std::tr1 namespace.
-- Found shared_ptr in std::tr1 namespace using <tr1/memory> header.
-- Building Ceres as a static library.
-- No build type specified; defaulting to CMAKE_BUILD_TYPE=Release.
-- Build the examples.

I love ceres-solver, thank you all for your hard work!

**Comment by alexsmac** [comment]
Please can you try this CL: https://ceres-solver-review.googlesource.com/#/c/9480 - it should fix the build for your Eigen version.

**Comment by alexsmac** [comment]
I was able to replicate this with Eigen 3.2.9 and the CL fixed it so I have merged it into master.

**Comment by suho0515** [comment]
@alexsmac 
it worked for me, thanks! :)
