### ISSUE TITLE
EXPORT_BUILD_DIR and MINIGLOG

### ISSUE THREAD

**Issue by spinicist** [ceres-solver/ceres-solver#253]
Hello,

I am trying to build Ceres from source to use in my own project via CMake. I switched on the `EXPORT_BUILD_DIR` and `MINIGLOG` options. I added `find_package(Ceres 1.2.3 REQUIRED COMPONENTS C++11)` to my projects CMakeLists.txt, then ran `ccmake` and specified the directory I used to build ceres. `ccmake` then gives the following error:

```CMake Error at External/ceres-solver/build/CeresConfig.cmake:88 (message):
   Failed to find Ceres - Ceres include directory:
   /***snip***/ceres-solver/include does not include
   miniglog, but Ceres was compiled with MINIGLOG enabled (in place of Glog).
 Call Stack (most recent call first):
   External/ceres-solver/build/CeresConfig.cmake:240 (ceres_report_not_found)
   CMakeLists.txt:24 (find_package)```

I am about to download glog and rebuild, but I think the above ought to work? I am using a clone of the ceres repo with tag 1.12.0 checked out.

**Comment by alexsmac** [comment]
This is a bug, please try this CL:

https://ceres-solver-review.googlesource.com/#/c/9640/ <https://ceres-solver-review.googlesource.com/#/c/9640/>

which should fix the problem.

-Alex

**Comment by alexsmac** [comment]
The fix has now been merged into master.

**Comment by spinicist** [comment]
Thanks, I confirm it works.
