### ISSUE TITLE
Logging issue

### ISSUE THREAD

**Issue by nosleduc** [ceres-solver/ceres-solver#255]
I cannot prevent ceres from logging despite the following confuration:

options.linear_solver_type = ceres::SPARSE_SCHUR;
options.minimizer_progress_to_stdout=false
options.logging_type = ceres::SILENT;

I've tested with the last release and the dev version, I got the same thing. I'm working on OSX 10.9. I'm using glog and set the following command in the main google::SetCommandLineOption("GLOG_minloglevel", "2");
I think this log comes from inner resolution:

iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time
   0  5,149614e+03    0,00e+00    2,30e+06   0,00e+00   0,00e+00  1,00e+04        0    8,23e-03    1,42e-02
   1  5,146780e+03    2,83e+00    4,33e+03   1,44e-04   1,00e+00  3,00e+04        0    1,84e-02    3,41e-02
   2  5,146705e+03    7,49e-02    6,35e+02   6,46e-05   1,00e+00  9,00e+04        0    1,77e-02    5,18e-02

Solver Summary (v 1.12.0-eigen-(3.3.1)-lapack-suitesparse-(4.5.4)-no_openmp)

                                     Original                  Reduced
Parameter blocks                            1                        1
Parameters                                  6                        6
Residual blocks                         11868                    11868
Residual                                23736                    23736

Minimizer                        TRUST_REGION

Dense linear algebra library            EIGEN
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver                     DENSE_SCHUR              DENSE_SCHUR
Threads                                     1                        1
Linear solver threads                       1                        1
Linear solver ordering              AUTOMATIC                        1
Schur structure                         2,6,0                    2,d,d

Cost:
Initial                          5,149614e+03
Final                            5,146705e+03
Change                           2,909051e+00

Minimizer iterations                        3
Successful steps                            3
Unsuccessful steps                          0

Time (in seconds):
Preprocessor                           0,0060

  Residual evaluation                  0,0057
  Jacobian evaluation                  0,0237
  Linear solver                        0,0159
Minimizer                              0,0556

Postprocessor                          0,0004
Total                                  0,0620

Termination:                      CONVERGENCE (Function tolerance reached. |cost_change|/cost: 3,395743e-07 <= 1,000000e-06)

**Comment by liweiyap** [comment]
Hey there, I'm really late, but I'm just wondering if you managed to find a solution to your problem? I'm facing the same issue; I've been unable to disable the ceres messages. I've used a very similar configuration to yours (albeit on Ubuntu 16.04):

```
ceres::Solver::Options options;
options.minimizer_progress_to_stdout = false;
options.linear_solver_type = ceres::LinearSolverType::DENSE_QR;
options.logging_type = ceres::SILENT;
```

The only way I could suppress these messages was by directing them from `std::cout` to `/dev/null`.

Thanks in advance!
