### ISSUE TITLE
GradientProblemSolver: Summary does not provide optimal cost, but cost from penultimate cost function evaluation

### ISSUE THREAD

**Issue by dweindl** [ceres-solver/ceres-solver#256]
Hi, I am experiencing the following problem with `GradientProblemSolver`:

*Expected behavior:*
`GradientProblemSolver::Summary.final_cost` contains the optimal cost value.

*Actual behavior:*
`GradientProblemSolver::Summary.final_cost` contains the cost value from penultimate cost function evaluation.

See here for an example: https://gist.github.com/dweindl/41787e6cffe682a155a95df2e2b7a08e

Is this behavior intended?

The gradient norm reported in the report is the one for the optimal parameters, as expected. However, the reported cost function value is from the previous iteration.

**Comment by sandwichmaker** [comment]
@dweindl this looks like a bug in the line search minimizer loop. I will take a look.

**Comment by sandwichmaker** [comment]
@dweindl 
https://ceres-solver-review.googlesource.com/#/c/9680/
is out for review. Thanks for reporting this.

**Comment by dweindl** [comment]
@sandwichmaker Great! Thank you for taking care of this so quickly.
