### ISSUE TITLE
OpenMP alternatives

### ISSUE THREAD

**Issue by ivan-ushakov** [ceres-solver/ceres-solver#258]
As I understand current version uses OpenMP only for `parallel for` operation. Not all platforms support OpenMP. For example Android and iOS doesn't. On the other hand it is possible build Intel TBB library for that platforms.
So my idea is to have abstraction for parallel processing or maybe we can switch to Intel TBB (Apache license). What do you think?

**Comment by pmoulon** [comment]
Does anyone can be interested also in considering using the c++11 thread features?

**Comment by ivan-ushakov** [comment]
I guess we need high level solution not just plain threads because in this case we have to create `parallel for` from zero. Also I think that TBB uses C++11 features.

**Comment by sandwichmaker** [comment]
This comes up regularly. Up till now we have held the line on not requiring the use of c++11 in the code base. @keir can say more.

**Comment by keir** [comment]
We are still holding the line on no C++11 features in the core, but I'm happy for us to support C++11 optionally if it provides clear benefits to some users. The issue we've had in the past is that it is hard to replace OpenMP's parallel for in straight C++11; you need to replicate all the scheduling and batching logic. TBB is the most likely candidate, but it's a heavy dependency. It's also awkward to support multiple concurrency approaches in the same codebase. So here is how I feel about it.

1. OpenMP support must remain; it's still a good solution even today and works out-of-the-box without dependencies on several platforms.
2. C++11 optional implementations are welcome.
3. TBB optional implementations are welcome.

The key question is how to add #2 and #3 without either making multiple copies of the evaluator and schur eliminator, and without making the code horribly complex and brittle. Ideas or patches are welcome.

**Comment by keir** [comment]
More discussion on this old mailing list thread:
https://groups.google.com/forum/#!topic/ceres-solver/miRlSAy8hcM

**Comment by keir** [comment]
More discussion:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ceres-solver/FIl-kQFHZFA/eE0a-uMsGQAJ

Patch adding threading using TBB, with optional OpenMP, but then requires C++11 in all cases:
https://github.com/yprokazov/ceres-solver/commit/429335555577fab2970817f6f36da56264b8b086

**Comment by sandwichmaker** [comment]
TBB support has been added to ceres!
