### ISSUE TITLE
unresolved external symbols

### ISSUE THREAD

**Issue by chrisluu** [ceres-solver/ceres-solver#260]
The error message is as follows:
unresolved external symbol "__declspec(dllimport) public: class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > * __cdecl google::base::CheckOpMessageBuilder::NewString(void)" (__imp_?NewString@CheckOpMessageBuilder@base@google@@QEAAPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)

I add ceres c++ include dir and linker lib dir, and input ceres.lib in linker input option. I also put ceres.dll into my release dir together with exe file. But always got the error message described above. Can somebody help out? Thanks.

**Comment by alexsmac** [comment]
You are missing the public link dependencies for Ceres, specifically glog.  If you used CMake to build your project, then the imported Ceres CMake target will contain all the public link dependencies automatically, if you are manually adding Ceres as a dependency to your project, you will need to add them yourself.

The public link dependencies will be specified in CeresTargets-release.cmake (installed into /usr/local/lib/cmake/Ceres, from <BUILD>/CMakeFiles/Export/lib/cmake/Ceres).  Note that these may themselves be CMake targets (e.g. glog & gflags), in which case you would have to manually iterate through their CMake to find all public link dependencies for them.

**Comment by chrisluu** [comment]
@alexsmac Hi, I add all the libraries to my configuration "ceres.lib glog.lib gflags_static.lib CXSparse.lib liblapack.lib libblas.lib". But the error message is still the same.

**Comment by chrisluu** [comment]
@alexsmac  Can you send me ceres.lib build with vs2015 x64 Release mode? It really drive me crazy.

**Comment by chrisluu** [comment]
@alexsmac  I finished it by myself. Thanks.

**Comment by xiaofeiwu** [comment]
I'm compiling ceres on Windows 7 with VS 2015 with glog also compiled in VS 2015. I met similar problem with 4 errors showing:

Error LNK2019	unresolved external symbol "void __cdecl ceres::internal::GetBestSchurTemplateSpecialization(int *,int *,int *)" (?GetBestSchurTemplateSpecialization@internal@ceres@@YAXPAH00@Z) referenced in function "public: virtual void __thiscall ceres::Solver::Solve(struct ceres::Solver::Options const &,class ceres::Problem *,struct ceres::Solver::Summary *)" (?Solve@Solver@ceres@@UAEXABUOptions@12@PAVProblem@2@PAUSummary@12@@Z)	ceres	E:\Codes\ceres-windows-master\win\solver.obj	1	

Error LNK1120: 1 unresolved externals	ceres E:\Codes\ceres-windows-master\Win32\Debug\ceres.dll	1	

Appriciate if there is any cues on how to solve it!

**Comment by LingjieLi** [comment]
How do you solver the problem? @chrisluu

**Comment by Jarvisss** [comment]
Fixed by setting the build architecture from 'x86' to 'x64' solved my problem, as ceres is build under x64 by cmake
