### ISSUE TITLE
Clarify remaining uses of nondeterministic functions

### ISSUE THREAD

**Issue by nh2** [ceres-solver/ceres-solver#261]
@sandwichmaker In https://ceres-solver.googlesource.com/ceres-solver/+/36c73c26bb3fd9b319435aa9702a110678239d9c you write:

> I have chosen not to delete the existing unstable implementations of these functions as they are used by the inner iteration minimizer.
> 
> Sometime in the near future I will clean up some of the duplicate code and see if we can move all the code to using a stable ordering.

In which part of the code are the unstable implementations still used? Grepping for `ComputeSchurOrdering` in commit 36c73c26bb3fd9b319435aa9702a110678239d9c, there seems to be no use of it besides in tests.

**Comment by nh2** [comment]
(Asking this because I've encountered nondeterminism when using the automatic inner iteration ordering.)

**Comment by nh2** [comment]
Hmm, I suspect it's this bit, am I right?

https://github.com/ceres-solver/ceres-solver/blob/01e23e3d33178fdd050973666505c1080cfe04c3/internal/ceres/parameter_block_ordering.cc#L111

**Comment by sandwichmaker** [comment]
Going to close this. as no further progress on this is expected.
