### ISSUE TITLE
FindCXSparse.cmake doesn't find cs.h in Debian

### ISSUE THREAD

**Issue by josch** [ceres-solver/ceres-solver#262]
Hi,

`FindCXSparse.cmake` doesn't look for `cs.h` in `/usr/include/suitesparse` where this header is shipped by Fedora as well as by Debian and derivatives. Please consider adding the path to `CXSPARSE_CHECK_INCLUDE_DIRS`.

Thanks!

**Comment by alexsmac** [comment]
This is now fixed in master.
