### ISSUE TITLE
Use of CMAKE_SOURCE_DIR and CMAKE_BINARY_DIR prohibits inclusion of Ceres with add_subdirectory

### ISSUE THREAD

**Issue by ttencate** [ceres-solver/ceres-solver#267]
`CMAKE_SOURCE_DIR` and `CMAKE_BINARY_DIR` point to the directory of the _root_ `CMakeLists.txt`, the one that `cmake` was invoked upon. The use of these variables make it impossible to include Ceres as a subdirectory (or Git submodule) of another CMake project.

Could this be changed to use `CMAKE_CURRENT_SOURCE_DIR` and `CMAKE_CURRENT_BINARY_DIR` instead? These [are available in CMake 2.8.0](https://cmake.org/cmake/help/v2.8.0/cmake.html#command:include), which is the minimum version currently required by Ceres.

This would make the following setup possible (I'm no CMake wizard, so there may be room for improvement):

```
my_project/
  CMakeLists.txt
  ceres-solver/
    CMakeLists.txt
    ... other Ceres files/dirs ...
```

**`my_project/CMakeLists.txt`**
```
option(EXPORT_BUILD_DIR "" ON) # Override option from included Ceres CMakeLists.txt
add_subdirectory(ceres)
set(Ceres_DIR ${CMAKE_CURRENT_BINARY_DIR}/ceres-solver)
find_package(Ceres REQUIRED)
```

There are no drawbacks to this change, as far as I'm aware, but again, I'm no CMake wizard.

**Comment by alexsmac** [comment]
We actually had a CL out for this previously: https://ceres-solver-review.googlesource.com/#/c/7230 that was abandoned, I will have a look at resurrecting it.

**Comment by ttencate** [comment]
Thank you Alex! That CL is clearly better and more comprehensive than my naive proposal, too :)

**Comment by alexsmac** [comment]
@ttencate please try this (updated) CL: https://ceres-solver-review.googlesource.com/#/c/9780

**Comment by ttencate** [comment]
LGTM!

**Comment by alexsmac** [comment]
Thanks, I have merged the CL into master.
