### ISSUE TITLE
Latest PR change prohibits a succesful ceres build

### ISSUE THREAD

**Issue by StevenPuttemans** [ceres-solver/ceres-solver#272]
The latest PR that was merged, makes ceres head build crashing on my Ubuntu16.04 x64 bit system.

https://ceres-solver.googlesource.com/ceres-solver/+/9a4f554b85ecbc3174c75006d943301207dbf68a%5E%21/#F0

The raised error is

```
/home/spu/Github/ceres-solver/internal/ceres/compressed_row_sparse_matrix.cc: In function ‘ceres::internal::CompressedRowSparseMatrix* ceres::internal::CreateRandomCompressedRowSparseMatrix(const ceres::internal::RandomMatrixOptions&)’:
/home/spu/Github/ceres-solver/internal/ceres/compressed_row_sparse_matrix.cc:875:28: error: request for member ‘empty’ in ‘tsm_values.std::vector<_Tp, _Alloc>::size<double, std::allocator<double> >()’, which is of non-class type ‘std::vector<double>::size_type {aka long unsigned int}’
   while (tsm_values.size().empty()) {
                            ^
```

Can this be reverted or fixed?

**Comment by StevenPuttemans** [comment]
Also just confirmed that if I reverse this change, the build works just fine!

**Comment by StevenPuttemans** [comment]
@sandwichmaker Since you provided the adaptation, you might want to look into this.

**Comment by creuther** [comment]
Confirmed, this breaks the build for me as well (Xubuntu 16.04 x64, gcc 5.4.0).

**Comment by sandwichmaker** [comment]
I will fix it shortly. Sorry about the trouble, not sure how this made it
past the build process.

**Comment by sandwichmaker** [comment]
Thanks for reporting, this is fixed now.
