### ISSUE TITLE
Adding C++11 directives through CMAKE for the pkg config

### ISSUE THREAD

**Issue by StevenPuttemans** [ceres-solver/ceres-solver#273]
As discussed in this [OpenCV issue](https://github.com/opencv/opencv_contrib/issues/1122), when enabling C++11 directives in the ceres-solver build, ceres does not automatically specify this through the use of the `target_compile_features` or `INTERFACE_COMPILE_FEATURES` feature.

More info on this can be found on https://cmake.org/cmake/help/v3.8/command/target_compile_features.html and https://cmake.org/cmake/help/v3.8/prop_tgt/INTERFACE_COMPILE_FEATURES.html.

This generates issues in secondary packages who depend on ceres, but do not get a notification that ceres is built with C++11 support and thus CMAKE does not automatically activates this (still disabled by default in CMAKE builds to support older compilers).

Can this be considered, that when the C++11 directive is enabled in ceres-solver cmake config, that these flags are set properly?

**Comment by alexsmac** [comment]
What errors are you encountering specifically?  This should already be present in Ceres, albeit via the [INTERFACE_COMPILE_OPTIONS](https://cmake.org/cmake/help/v3.8/prop_tgt/INTERFACE_COMPILE_OPTIONS.html) target property that was also supported in earlier versions of CMake (target_compile_features() came in in 3.1).

I'm not averse to adding target_compile_features(), but as this will add extra complexity to support older versions of CMake as well, I would like to understand why the current solution isn't working for you when it is working for other users.

It's also easy to verify what features Ceres was compiled with, including C++11 by checking the CERES_COMPILED_COMPONENTS variable defined after a call to find_package(Ceres).  [You can also specify C++11 explicitly as a COMPONENT for Ceres in the find_package(Ceres) call if required](http://ceres-solver.org/installation.html#specify-ceres-components).

**Comment by crmoore** [comment]
Here's a simple case that breaks with the existing ceres CMakeLists.txt.  It works when I hack it to use INTERFACE_COMPILE_FEATURES.

This project requires gnu-extensions (-std=gnu++14), and cmake sets it accordingly.  Ceres sets -std=c++11, and both flags get added to the command line.  gcc seems to behave as if gnu-extensions are disabled.  Oddly, using c++14 features works.  That is "-std=c++11 -std=gnu++14" behaves like "-std=c++14".

```
cmake_minimum_required(VERSION 3.6)
project(hello)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED True)

find_package( Ceres REQUIRED )

add_executable( hello hello.cpp)
target_link_libraries( hello ${CERES_LIBRARIES})
```

```
int main(){
	auto pi = 3.15Q; // gnu extension for float128 literal
	return 0;
}
```

For my use, my compiler's defaults are gnu++14, so I can just set CXX11=OFF in Ceres and be on my way.

**Comment by StevenPuttemans** [comment]
@alexsmac well actually the errors I get is that when building the structure from motion module inside OpenCV, which depends on Ceres solver (which I built with C++11 support) the following appears:

```
In file included from /usr/local/include/ceres/jet.h:167:0,
                 from /usr/local/include/ceres/internal/autodiff.h:145,
                 from /usr/local/include/ceres/autodiff_cost_function.h:132,
                 from /usr/local/include/ceres/ceres.h:37,
                 from /home/spu/Github/opencv_contrib/modules/sfm/src/libmv_light/libmv/multiview/fundamental.cc:24:
/usr/local/include/ceres/internal/port.h:49:12: error: ‘std::shared_ptr’ has not been declared
 using std::shared_ptr;
            ^
/usr/local/include/ceres/internal/port.h:63:8: error: ‘constexpr’ does not name a type
 static constexpr size_t kMaxAlignBytes =
        ^
/usr/local/include/ceres/internal/port.h:63:8: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
In file included from /usr/local/include/ceres/internal/autodiff.h:145:0,
                 from /usr/local/include/ceres/autodiff_cost_function.h:132,
                 from /usr/local/include/ceres/ceres.h:37,
                 from /home/spu/Github/opencv_contrib/modules/sfm/src/libmv_light/libmv/multiview/fundamental.cc:24:
/usr/local/include/ceres/jet.h:252:10: error: ‘constexpr’ does not name a type
   static constexpr int kAlignOrNot =
          ^
/usr/local/include/ceres/jet.h:252:10: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/usr/local/include/ceres/jet.h:272:10: error: ‘constexpr’ does not name a type
   static constexpr size_t kAlignment = kAlignOrNot == Eigen::AutoAlign
          ^
/usr/local/include/ceres/jet.h:272:10: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
/usr/local/include/ceres/jet.h:275:11: error: ‘kAlignment’ has not been declared
   alignas(kAlignment) Eigen::Matrix<T, N, 1, kAlignOrNot> v;
           ^
/usr/local/include/ceres/jet.h:275:21: error: expected ‘;’ at end of member declaration
   alignas(kAlignment) Eigen::Matrix<T, N, 1, kAlignOrNot> v;
                     ^
/usr/local/include/ceres/jet.h:275:46: error: ‘kAlignOrNot’ was not declared in this scope
   alignas(kAlignment) Eigen::Matrix<T, N, 1, kAlignOrNot> v;
                                              ^
/usr/local/include/ceres/jet.h:275:57: error: template argument 4 is invalid
   alignas(kAlignment) Eigen::Matrix<T, N, 1, kAlignOrNot> v;
                                                         ^
/usr/local/include/ceres/jet.h: In constructor ‘ceres::Jet<T, N>::Jet()’:
/usr/local/include/ceres/jet.h:181:7: error: request for member ‘setZero’ in ‘((ceres::Jet<T, N>*)this)->ceres::Jet<T, N>::v’, which is of non-class type ‘int’
     v.setZero();
       ^
/usr/local/include/ceres/jet.h: In constructor ‘ceres::Jet<T, N>::Jet(const T&)’:
/usr/local/include/ceres/jet.h:187:7: error: request for member ‘setZero’ in ‘((ceres::Jet<T, N>*)this)->ceres::Jet<T, N>::v’, which is of non-class type ‘int’
     v.setZero();
       ^
/usr/local/include/ceres/jet.h: In constructor ‘ceres::Jet<T, N>::Jet(const T&, int)’:
/usr/local/include/ceres/jet.h:193:7: error: request for member ‘setZero’ in ‘((ceres::Jet<T, N>*)this)->ceres::Jet<T, N>::v’, which is of non-class type ‘int’
     v.setZero();
       ^
/usr/local/include/ceres/jet.h:194:8: error: invalid types ‘int[int]’ for array subscript
     v[k] = T(1.0);
        ^

```

Whenever I explicitly tell CMAKE to use C++11, in the CMAKE of OpenCV with an extra entry, these issues get resolved.

The weird thing is however, when running CMAKE in OpenCV I get the following output when Ceres is detected:

```
Ceres version 1.12.0 detected here: /usr/local was built with C++11. Ceres target will add C++11 flags to compile options for targets using it.
Found Ceres version: 1.12.0 installed in: /usr/local with components: [LAPACK, SuiteSparse, SparseLinearAlgebraLibrary, CXSparse, SchurSpecializations, C++11, OpenMP]
```

But after generating the build issues arise.

**Comment by alexsmac** [comment]
@StevenPuttemans your problem actually looks like a bug in the OpenCV SfM CMake.  Looking at the latest master branch, you're compiling fundamental.cc [which is part of the multiview library](https://github.com/opencv/opencv_contrib/blob/e8c109bf408cac6a85b363a2fd34600958bb1015/modules/sfm/src/libmv_light/libmv/multiview/CMakeLists.txt#L20), however despite (optionally) using Ceres that library never declares that it is dependent upon Ceres via target_link_libraries().  It apparently only depends on the 'numeric' library, which does not depend on Ceres.

The 'simple_pipeline' library [does declare that it uses Ceres](https://github.com/opencv/opencv_contrib/blob/246ea8f3bdf174a2aad6216c2601e3a93bf75c29/modules/sfm/src/libmv_light/libmv/simple_pipeline/CMakeLists.txt#L20), and so the '-std=c++11' flag from the Ceres target should be being appended to that target's compile definitions, but this will not recurse back up the tree of dependencies to the 'multiview' library.

Given this issue, I don't think that Ceres using target_compile_features() would actually solve your problem.  If you fix the OpenCV SfM CMake, the current solution should work for you.  However, in general I would advise against compiling OpenCV without C++11 if Ceres is compiled with it - although the language is ABI compatible, parts of the STL are not and mixing them can be problematic.  YMMV, but in general it is not advisable.

**Comment by StevenPuttemans** [comment]
Thanks for the response. I will take this back to the OpenCV forum and keep you informed.

**Comment by alexsmac** [comment]
@crmoore although target_compile_features() came in in CMake 3.1, the [cxx_std_11 feature](https://cmake.org/cmake/help/v3.8/prop_gbl/CMAKE_CXX_KNOWN_FEATURES.html#prop_gbl:CMAKE_CXX_KNOWN_FEATURES) didn't come in until CMake 3.8, and the features available in older versions do not reflect Ceres' requirements, so the current target_compile_options() solution is required for all versions < 3.8 in order that the C++11 dependency be exported in the CMake target, as [the values of the target properties: CXX_STANDARD & CXX_STANDARD_REQUIRED are *not* (bizarrely) exported](https://github.com/drbenmorgan/cmake-compile-features).

I've added a CL [here](https://ceres-solver-review.googlesource.com/#/c/10020/) which should use target_compile_features() and cxx_std_11 instead of the target_compile_options() solution if they are available (CMake >= 3.8).  Assuming that you are using CMake 3.8+ please try the CL and let me know if this works for you.

**Comment by crmoore** [comment]
@alexsmac Thanks.  That appears to do the right thing, when using CMake 3.8.

**Comment by sergiud** [comment]
@alexsmac Are you sure that `cxx_std_11` from CMake 3.8 is required? `cxx_constexpr` and `cxx_alignas` perfectly reflect the compile features required by Ceres public interface. I'm pretty sure that if `cxx_constexpr` and `cxx_alignas` are available, one can strongly assume that TR1 features of the standard C++ library are available as well. At least I'm not aware of any compiler and standard C++ library implementation combination for which this is not the case.

**Comment by alexsmac** [comment]
@sergiud that seems reasonable, I've updated the CL accordingly [here](https://ceres-solver-review.googlesource.com/#/c/10020/).  @crmoore if you could please confirm this still works as expected for you that would be helpful - thanks.

**Comment by crmoore** [comment]
Works great.

**Comment by alexsmac** [comment]
Closing, as the CL has now been merged into master.
