### ISSUE TITLE
Example for 2D Panorama

### ISSUE THREAD

**Issue by skn123** [ceres-solver/ceres-solver#275]
I was wondering if there is any example in Ceres-Solver for building a 2D panorama without estimation of camera intrinsic parameters. An example of a 2D panorama would be a microscope whole slide image or a whole slide image of an IC chip. Any help / pointers would be appreciated.

**Comment by pmoulon** [comment]
You can stitch all the images by using homographies registration.
-> You can use Hugin with a large focal length or constraint the registration to be on a plane.

If you want to do it yourself:
- you can perform an incremental registration
  - robust estimation of homographies + warping see demo here https://github.com/openMVG/openMVG/blob/master/src/openMVG_Samples/multiview_robust_homography/robust_homography.cpp
- or use a global registration
   - see the paper "Closed-form solutions to multiple-view homography estimation"

**Comment by skn123** [comment]
Pierre
Thanks for the response. I am aware of the last link and I found it interesting. However, I am unable to translate the terminologies of that paper with my example. I direct your attention to the problem I am looking at:
www.maths-in-industry.org/miis/id/eprint/173/contents
Sec. 1. 3. 2
I am able to estimate the pair wise displacements between neighboring tiles using any suitable method. However, what I am seeking is the final minimization for global optimization as shown in the above paper. Is there any example in ceres-solver that can do is?
I am looking for a batch solution; so the incremental approach may not suit my needs. However, I will look into that also.

**Comment by sandwichmaker** [comment]
@skn123 I am going to close this issue as this is not really ceres related.
