### ISSUE TITLE
Add support for fabs(Jet) in addition to abs(Jet)

### ISSUE THREAD

**Issue by ttencate** [ceres-solver/ceres-solver#283]
[The situation with `::abs` is messy](http://stackoverflow.com/questions/21392627/abs-vs-stdabs-what-does-the-reference-say): the `<cmath>` header may or may not declare `::abs(double)`. If you need portable overloads for floats and doubles, the recommendation is to either use `std::abs` or `fabs` instead.

However, for automatic derivatives, neither will work. `std::abs` disables argument-dependent lookup, so it won't find `ceres::abs(Jet)` anymore. `fabs` does not have a Jet overload to begin with. Maybe we could use `ei_abs` (I haven't tried) but it's not very discoverable or intuitive.

To solve this, would it make sense to add `ceres::fabs(Jet)`?

**Comment by sergiud** [comment]
Why not simply
```cpp
using std::abs;
T a = abs(/*...*/);
```
This way the appropriate overload will be discovered through ADL.

**Comment by ttencate** [comment]
Thanks! Good idea, hadn't thought of that. Feel free to close this if that's the recommended approach.

**Comment by alexsmac** [comment]
Using ceres::abs() should also work regardless of T.
