### ISSUE TITLE
Problem Using GradientChecker on Windows Build (with included potential solution)

### ISSUE THREAD

**Issue by oracle3001** [ceres-solver/ceres-solver#284]
I found that when building Ceres on a windows machine using VS2015, that if I attempted to make use of the GradientChecker functionality in my code I would get the following error (despite ceres.lib being properly linked in the project).

```
1>main.obj : error LNK2019: unresolved external symbol "public: __cdecl ceres::GradientChecker::GradientChecker(class ceres::CostFunction const *,class std::vector<class ceres::LocalParameterization const *,class std::allocator<class ceres::LocalParameterization const *> > const *,struct ceres::NumericDiffOptions const &)" (??0GradientChecker@ceres@@QEAA@PEBVCostFunction@1@PEBV?$vector@PEBVLocalParameterization@ceres@@V?$allocator@PEBVLocalParameterization@ceres@@@std@@@std@@AEBUNumericDiffOptions@1@@Z) referenced in function main
1>main.obj : error LNK2019: unresolved external symbol "public: bool __cdecl ceres::GradientChecker::Probe(double const * const *,double,struct ceres::GradientChecker::ProbeResults *)const " (?Probe@GradientChecker@ceres@@QEBA_NPEBQEBNNPEAUProbeResults@12@@Z) referenced in function main
```

After conversing with Tal Ben-Nun who maintains the Visual Studio port for ceres, we believe the following code should be altered. 

> This is actually an issue in (or an intended feature of) ceres-solver. If you go to "include/ceres/gradient_checker.h", line 67, and replace:
> 
> `class GradientChecker {`
> 
> with:
> 
> `class CERES_EXPORT GradientChecker {`

**Comment by sandwichmaker** [comment]
Yes that seems like an oversight, please submit a change on gerrrit.

**Comment by sandwichmaker** [comment]
https://ceres-solver-review.googlesource.com/#/c/10160/ has been submitted. It should fix the problem. Please let me know and I will close this issue.

**Comment by sandwichmaker** [comment]
Closing, please re-open if ceres at HEAD does not solve your problem.
