### ISSUE TITLE
Custom Eigen path

### ISSUE THREAD

**Issue by hcjghr** [ceres-solver/ceres-solver#285]
Hi,

I'm trying to use a custom eigen path when building ceres and as far as I understood I should set variables:
- EIGEN_INCLUDE_DIR_HINTS to where I have eigen installed
- EIGEN_PREFER_EXPORTED_EIGEN_CMAKE_CONFIGURATION=FALSE

With this, ceres still selects the default eigen installed in /usr/local/include/eigen3 . I have noticed that in FindEigen.cmake the path is added to the search as: PATHS ${EIGEN_INCLUDE_DIR_HINTS} (line 150) which from my understanding gets searched after the system locations causing the selection of eigen from default location. If I change PATHS to HINTS (which indicates to search before the system paths) eigen is correctly selected from my custom location. I was wondering if I'm doing something wrong (or not setting the right variables) or there is actually a problem with that.

Thanks,
Klemen

**Comment by alexsmac** [comment]
@hcjghr - this looks like a bug, I'll push a fix for this later today.

**Comment by hcjghr** [comment]
@alexsmac great! I also noticed the same problem with suitesparse (SUITESPARSE_CHECK_LIBRARY_DIRS) and cxsparse (CXSPARSE_INCLUDE_DIR_HINTS).

**Comment by alexsmac** [comment]
@hcjghr - I've added a CL which should fix this issue [here](https://ceres-solver-review.googlesource.com/10180) - please give it a try.  This also includes a fairly substantial cleanup of FindSuiteSparse to reduce the number of code blocks calling find_path/library().

**Comment by alexsmac** [comment]
@hcjghr - please can you confirm that this CL fixes the issue for you.

**Comment by alexsmac** [comment]
The fix (across all our find package scripts) has now been merged into master.

**Comment by hcjghr** [comment]
Hi,

sorry for not responding sooner but I can confirm that I tested the newest code and the issue is now fixed. 

Thanks for such a quick response!
