### ISSUE TITLE
Broken `dynamic_sparsity` with addition of `crsb_rows_` and `crsb_cols_`

### ISSUE THREAD

**Issue by rstebbing** [ceres-solver/ceres-solver#287]
The commit [`Optimize J' * J in sparse_normal_cholesky_solver.`](https://github.com/ceres-solver/ceres-solver/commit/07dbf31eca6851aadaed0dc337e05c8bb5965850) extended `CompressedRowSparseMatrix ` with `block_offsets_`, `crsb_rows_`, and `csrb_cols_`, where the latter two are set in `CompressedRowJacobianWriter::CreateJacobian`.

Unfortunately, the corresponding additions have *not* been added to `DynamicCompressedRowSparseMatrix::Finalize` (where I *think*, at first glance, this is required). As a result, the `ellipse_approximation` example fails because of the failed assertion [`CHECK_EQ(crsb_rows_.size(), row_blocks_.size() + 1);`](https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/compressed_row_sparse_matrix.cc#L381).

**Comment by sandwichmaker** [comment]
Thanks @rstebbing for reporting. 
Looking now.

**Comment by sandwichmaker** [comment]
https://ceres-solver-review.googlesource.com/#/c/10242/ is out for review. 
I have added you as a reviewer to it. Please take a look.
