### ISSUE TITLE
Bundle adjustment test fails on aarch64

### ISSUE THREAD

**Issue by clalancette** [ceres-solver/ceres-solver#289]
I'm running ceres-solver on Ubuntu 16.04 on an aarch64 machine (a Pine64 board).  When I try to run the bundle_adjustment_test on that architecture, the first test (DenseSchurWithAutomaticOrdering) fails with the following:

```
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from BundleAdjustmentTest
[ RUN      ] BundleAdjustmentTest.DenseSchurWithAutomaticOrdering
/home/ubuntu/ceres-tests/ceres-solver/internal/ceres/test_util.h:165: Failure
The difference between final_residuals[i] and expected_final_residuals_[i] is 0.28509468021827222, which exceeds SystemTestProblem::kResidualTolerance, where
final_residuals[i] evaluates to 0.66154853102510147,
expected_final_residuals_[i] evaluates to 0.94664321124337369, and
SystemTestProblem::kResidualTolerance evaluates to 0.0001.
Not close enough residual:0
```

(there are thousands more errors like that, I just chose the first one).

All of the other tests pass.  Let me know if you need more information, I'm happy to provide it (or try patches).

**Comment by sandwichmaker** [comment]
what version of Eigen are you using? this looks like there is either a correctness or a precision bug in the underlying linear algebra library. I had an earlier report about this and upgrading to the latest version of eigen fixed the problem for them.

**Comment by clalancette** [comment]
It's the version that is in Ubuntu 16.04, so it looks like 3.3~beta1-2 .  What's interesting is that the test works just fine on x86_64 with this same version of Eigen; it only fails on aarch64.

**Comment by clalancette** [comment]
So, I just rebuilt ceres-solver with Eigen 3.3.4 on my aarch64 board, and the bundle adjustment tests do seem to be passing now.  It might be nice in CMakeLists.txt to detect when it is on aarch64, and require Eigen 3.3.4 or above.  That being said, feel free to close this out.  Thanks.

**Comment by sandwichmaker** [comment]
@alexsmac WDYT? also @clalancette we will happily take a patch to the effect.

**Comment by sandwichmaker** [comment]
@alexsmac is this actionable?

**Comment by alexsmac** [comment]
@clalancette can you please try this CL: https://ceres-solver-review.googlesource.com/#/c/ceres-solver/+/12040 - it should check that the Eigen version is >= 3.3.4 on aarch64 - thanks.

**Comment by clalancette** [comment]
@alexsmac Sorry for the delay here.  I was able to test this out on my aarch64 board, and it does indeed throw an error as expected when building against the system version.  It also seems to work fine when building against a newer version of Eigen, so I would say that that patch looks good to me.  Thank you!

**Comment by tianxinyu0509** [comment]
I'm also running ceres-solver on Ubuntu 16.04 with ROS on an aarch64 machine(NVIDIA jetson TX1) with eigen 3.3.4 or with eigen 3.3.5.when I make, I failed with the following:

c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
examples/CMakeFiles/nist.dir/build.make:62: recipe for target 'examples/CMakeFiles/nist.dir/nist.cc.o' failed
make[2]: *** [examples/CMakeFiles/nist.dir/nist.cc.o] Error 4
CMakeFiles/Makefile2:7566: recipe for target 'examples/CMakeFiles/nist.dir/all' failed
make[1]: *** [examples/CMakeFiles/nist.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

"examples/CMakeFiles/nist.dir/nist.cc.o" is it important? Can I delete it?

**Comment by Minipada** [comment]
@tianxinyu0509 you likely lack memory on your machine. Try creating some swap

**Comment by tianxinyu0509** [comment]
@Minipada Thank you very much for your help. I used command "top" to check the memory usage.It is really the lack of memory that causes this problem. I successfully resolved this issue by using command "make" instead of " make -j4". Finally, I sincerely thank you for your help.
