### ISSUE TITLE
[GradientProblem] Objective is evaluated twice at each iteration

### ISSUE THREAD

**Issue by svenpilz** [ceres-solver/ceres-solver#296]
It seems the objective function (`GradientProblem::Evaluate`) of a general unconstrained minimization (`GradientProblemSolver`) is evaluated twice with the same parameter during each iteration, first for the line search and afterwards for the actual evaluation. This would double the optimization time (ignoring additional line search steps), and may be a problem depending on the objective's computational cost.

This can be tested with `examples/rosenbrock.cc`, and adding additional output to `Evaluate`.

Is there a workaround?

**Comment by sandwichmaker** [comment]
@svenpilz there maybe a way of saving this extra eval, but would likely require work. What kind of problem are you solving where this is an issue, can you share more details?

**Comment by svenpilz** [comment]
@sandwichmaker photo-consistency based multi-view reconstruction of faces, i.e. comparing L^p metrics of captured and rendered camera views. Which takes about two minutes per evaluation (rendering, error and gradient) at the highest image resolution.

**Comment by svenpilz** [comment]
At the moment we cache the last evaluation and return that result, when the previous parameters are given. As the parameters are binary-wise the same, this is a good workaround for us :-).

**Comment by sandwichmaker** [comment]
interesting, thanks for the background. I will take a look.

**Comment by sandwichmaker** [comment]
@svenpilz I looked this briefly, fixing this is going to require an architectural change in the way the main loop of the line search minimizer talks to the line search routines themselves. I need to think about how to do this without breaking the abstraction completely. That said I agree, this would be a nice performance improvement so it is worth doing.

**Comment by sandwichmaker** [comment]
@svenpilz as part of this work, the first thing is to fix and count correctly the time and number of calls spent in evaluations. so, 
https://ceres-solver-review.googlesource.com/#/c/10580/ is out for review. Once that is in, I will use that to track down every function evaluation and see what I can do about it.

**Comment by sandwichmaker** [comment]
https://ceres-solver-review.googlesource.com/#/c/10600/
https://ceres-solver-review.googlesource.com/#/c/10620/

are out for review.

You are welcome to patch them and try them out.

**Comment by sandwichmaker** [comment]
Fixed upstream :). Thank you for reporting this.
