### ISSUE TITLE
CMake error installing as Shared library

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [ceres-solver/ceres-solver#298]
I get this error when running "sudo make install" :

[100%] Built target pose_graph_3d
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/autodiff_cost_function.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/autodiff_local_parameterization.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/c_api.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/ceres.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/conditioned_cost_function.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/cost_function.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/cost_function_to_functor.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/covariance.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/crs_matrix.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/cubic_interpolation.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/dynamic_autodiff_cost_function.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/dynamic_cost_function.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/dynamic_cost_function_to_functor.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/dynamic_numeric_diff_cost_function.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/fpclassify.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/gradient_checker.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/gradient_problem.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/gradient_problem_solver.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/iteration_callback.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/jet.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/local_parameterization.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/loss_function.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/normal_prior.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/numeric_diff_cost_function.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/numeric_diff_options.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/ordered_groups.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/problem.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/rotation.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/sized_cost_function.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/solver.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/types.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/version.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/autodiff.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/disable_warnings.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/eigen.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/fixed_array.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/macros.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/manual_constructor.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/numeric_diff.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/port.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/reenable_warnings.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/scoped_ptr.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/variadic_evaluate.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/config.h
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/lib/cmake/Ceres/CeresTargets.cmake
-- Installing: /home/tariq/Dev/ceres-solver/build/lib/cmake/Ceres/CeresTargets-release.cmake
-- Installing: /home/tariq/Dev/ceres-solver/build/lib/cmake/Ceres/CeresConfig.cmake
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/lib/cmake/Ceres/CeresConfigVersion.cmake
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/lib/cmake/Ceres/FindEigen.cmake
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/lib/cmake/Ceres/FindGlog.cmake
-- Up-to-date: /home/tariq/Dev/ceres-solver/build/lib/cmake/Ceres/FindGflags.cmake
CMake Error at internal/ceres/cmake_install.cmake:48 (file):
  file INSTALL cannot find
  "/home/tariq/Dev/ceres-solver/build/lib/libceres.so.1.12.0".
Call Stack (most recent call first):
  cmake_install.cmake:126 (include)
  

Makefile:71: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by alexsmac** [comment]
I can't reproduce this on either OS X or Ubuntu with either master or the 1.12 release tarball, and the installation is performed using the standard CMake functions (which also handle the naming of the library based on the stated version).

Given that all but the library type specific files are listed as up-to-date, I'm assuming that you already installed a version of Ceres built from the same source (which I assume was statically linked), and have then reconfigured the build directory to link dynamically.  I tried this permutation as well and still could not reproduce this issue.

What is the contents of /home/tariq/Dev/ceres-solver/build/lib when the this failure occurs, what are the details of the system you are building this on, and what are the exact steps required from a clean build directory to reproduce this issue?

**Comment by Tariq-Abuhashim** [comment]
I have pulled the new release and compiled it:

mkdir build
cd build
ccmake ..   
I set SHARED=ON, EIGENSPARSE=ON, CMAKE_INSTAL_PREFIX=/home/tariq/Dev/ceres-solver/build
make
sudo make install

I get the same error:
[100%] Built target pose_graph_3d
Install the project...
-- Install configuration: "Release"
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/autodiff_cost_function.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/autodiff_local_parameterization.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/c_api.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/ceres.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/conditioned_cost_function.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/cost_function.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/cost_function_to_functor.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/covariance.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/crs_matrix.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/cubic_interpolation.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/dynamic_autodiff_cost_function.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/dynamic_cost_function.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/dynamic_cost_function_to_functor.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/dynamic_numeric_diff_cost_function.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/fpclassify.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/gradient_checker.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/gradient_problem.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/gradient_problem_solver.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/iteration_callback.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/jet.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/local_parameterization.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/loss_function.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/normal_prior.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/numeric_diff_cost_function.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/numeric_diff_options.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/ordered_groups.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/problem.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/rotation.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/sized_cost_function.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/solver.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/types.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/version.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/autodiff.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/disable_warnings.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/eigen.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/fixed_array.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/macros.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/manual_constructor.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/numeric_diff.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/port.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/reenable_warnings.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/scoped_ptr.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/variadic_evaluate.h
-- Installing: /home/tariq/Dev/ceres-solver/build/include/ceres/internal/config.h
-- Installing: /home/tariq/Dev/ceres-solver/build/lib/cmake/Ceres/CeresTargets.cmake
-- Installing: /home/tariq/Dev/ceres-solver/build/lib/cmake/Ceres/CeresTargets-release.cmake
-- Installing: /home/tariq/Dev/ceres-solver/build/lib/cmake/Ceres/CeresConfig.cmake
-- Installing: /home/tariq/Dev/ceres-solver/build/lib/cmake/Ceres/CeresConfigVersion.cmake
-- Installing: /home/tariq/Dev/ceres-solver/build/lib/cmake/Ceres/FindEigen.cmake
-- Installing: /home/tariq/Dev/ceres-solver/build/lib/cmake/Ceres/FindGlog.cmake
-- Installing: /home/tariq/Dev/ceres-solver/build/lib/cmake/Ceres/FindGflags.cmake
CMake Error at internal/ceres/cmake_install.cmake:48 (file):
  file INSTALL cannot find
  "/home/tariq/Dev/ceres-solver/build/lib/libceres.so.1.13.0".
Call Stack (most recent call first):
  cmake_install.cmake:126 (include)
  
Makefile:71: recipe for target 'install' failed
make: *** [install] Error 1

/home/tariq/Dev/ceres-solver/build/lib  has the following:
cmake  libceres.so  libceres.so.1  libgtest.so  libtest_util.so

I am running:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	        16.04
Codename:	xenial

**Comment by alexsmac** [comment]
First off, you appear to be trying to install to the build directory, that's not a good idea or intended CMake usage.  If you want to use Ceres without having to install it (and are using CMake for your own dependent project) then you can use the EXPORT_BUILD_DIR option as detailed [here](http://ceres-solver.org/installation.html#options-controlling-ceres-configuration).  I can replicate this issue on Ubuntu 14.04 using CMake 3.5.2 when installing to the build directory, albeit not on OS X with the same CMake version.

The fix is that you should either use the EXPORT_BUILD_DIR option, or install to a separate (i.e. not the build directory) location.
