### ISSUE TITLE
libcholmod should be passed to linker before its dependencies

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#3]
Original [issue 2](https://code.google.com/p/ceres-solver/issues/detail?id=2) created by sandwichmaker on 2012-05-02T00:28:15.000Z:

<b>What steps will reproduce the problem?</b>
1. Install all ceres dependencies besides lapack and blas from source (all static libraries)
2. mkdir build &amp;&amp; cd build &amp;&amp; cmake .. &amp;&amp; make

<b>What is the expected output? What do you see instead?</b>

Expected: make succeeds
Instead: Works until iterative_schur_complement_solver_test, then:

Linking CXX executable iterative_schur_complement_solver_test  
/usr/local/lib/libcholmod.a(cholmod_colamd.o):cholmod_colamd.c:function cholmod_colamd: error: undefined reference to 'colamd_recommended'  
/usr/local/lib/libcholmod.a(cholmod_colamd.o):cholmod_colamd.c:function cholmod_colamd: error: undefined reference to 'colamd_set_defaults'
/usr/local/lib/libcholmod.a(cholmod_colamd.o):cholmod_colamd.c:function cholmod_colamd: error: undefined reference to 'colamd_printf'
/usr/local/lib/libcholmod.a(cholmod_colamd.o):cholmod_colamd.c:function cholmod_colamd: error: undefined reference to 'colamd'
/usr/local/lib/libcholmod.a(cholmod_super_numeric.o):cholmod_super_numeric.c:function cholmod_super_numeric: error: undefined reference to 'dsyrk_'
/usr/local/lib/libcholmod.a(cholmod_super_numeric.o):cholmod_super_numeric.c:function cholmod_super_numeric: error: undefined reference to 'dgemm_'
/usr/local/lib/libcholmod.a(cholmod_super_numeric.o):cholmod_super_numeric.c:function cholmod_super_numeric: error: undefined reference to 'dtrsm_'
/usr/local/lib/libcholmod.a(cholmod_super_numeric.o):cholmod_super_numeric.c:function cholmod_super_numeric: error: undefined reference to 'zherk_'
/usr/local/lib/libcholmod.a(cholmod_super_numeric.o):cholmod_super_numeric.c:function cholmod_super_numeric: error: undefined reference to 'zgemm_'
/usr/local/lib/libcholmod.a(cholmod_super_numeric.o):cholmod_super_numeric.c:function cholmod_super_numeric: error: undefined reference to 'ztrsm_'
/usr/local/lib/libcholmod.a(cholmod_super_numeric.o):cholmod_super_numeric.c:function cholmod_super_numeric: error: undefined reference to 'zherk_'
/usr/local/lib/libcholmod.a(cholmod_super_numeric.o):cholmod_super_numeric.c:function cholmod_super_numeric: error: undefined reference to 'zgemm_'
/usr/local/lib/libcholmod.a(cholmod_super_numeric.o):cholmod_super_numeric.c:function cholmod_super_numeric: error: undefined reference to 'ztrsm_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_lsolve: error: undefined reference to 'dtrsm_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_lsolve: error: undefined reference to 'dgemm_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_lsolve: error: undefined reference to 'dtrsm_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_lsolve: error: undefined reference to 'dtrsv_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_lsolve: error: undefined reference to 'dgemv_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_lsolve: error: undefined reference to 'ztrsm_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_lsolve: error: undefined reference to 'zgemm_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_lsolve: error: undefined reference to 'ztrsm_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_lsolve: error: undefined reference to 'ztrsv_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_lsolve: error: undefined reference to 'zgemv_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_ltsolve: error: undefined reference to 'dgemm_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_ltsolve: error: undefined reference to 'dtrsm_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_ltsolve: error: undefined reference to 'dgemv_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_ltsolve: error: undefined reference to 'dtrsv_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_ltsolve: error: undefined reference to 'zgemm_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_ltsolve: error: undefined reference to 'zgemv_'
/usr/local/lib/libcholmod.a(cholmod_super_solve.o):cholmod_super_solve.c:function cholmod_super_ltsolve: error: undefined reference to 'ztrsv_'
/usr/local/lib/libcholmod.a(cholmod_camd.o):cholmod_camd.c:function cholmod_camd: error: undefined reference to 'camd_malloc'
/usr/local/lib/libcholmod.a(cholmod_camd.o):cholmod_camd.c:function cholmod_camd: error: undefined reference to 'camd_free'
/usr/local/lib/libcholmod.a(cholmod_camd.o):cholmod_camd.c:function cholmod_camd: error: undefined reference to 'camd_calloc'
/usr/local/lib/libcholmod.a(cholmod_camd.o):cholmod_camd.c:function cholmod_camd: error: undefined reference to 'camd_realloc'
/usr/local/lib/libcholmod.a(cholmod_camd.o):cholmod_camd.c:function cholmod_camd: error: undefined reference to 'camd_printf'
/usr/local/lib/libcholmod.a(cholmod_camd.o):cholmod_camd.c:function cholmod_camd: error: undefined reference to 'camd_2'
/usr/local/lib/libcholmod.a(cholmod_amd.o):cholmod_amd.c:function cholmod_amd: error: undefined reference to 'amd_malloc'
/usr/local/lib/libcholmod.a(cholmod_amd.o):cholmod_amd.c:function cholmod_amd: error: undefined reference to 'amd_free'
/usr/local/lib/libcholmod.a(cholmod_amd.o):cholmod_amd.c:function cholmod_amd: error: undefined reference to 'amd_calloc'
/usr/local/lib/libcholmod.a(cholmod_amd.o):cholmod_amd.c:function cholmod_amd: error: undefined reference to 'amd_realloc'
/usr/local/lib/libcholmod.a(cholmod_amd.o):cholmod_amd.c:function cholmod_amd: error: undefined reference to 'amd_printf'
/usr/local/lib/libcholmod.a(cholmod_amd.o):cholmod_amd.c:function cholmod_amd: error: undefined reference to 'amd_2'
/usr/local/lib/libcholmod.a(cholmod_ccolamd.o):cholmod_ccolamd.c:function cholmod_ccolamd: error: undefined reference to 'ccolamd_recommended'
/usr/local/lib/libcholmod.a(cholmod_ccolamd.o):cholmod_ccolamd.c:function cholmod_ccolamd: error: undefined reference to 'ccolamd_set_defaults'
/usr/local/lib/libcholmod.a(cholmod_ccolamd.o):cholmod_ccolamd.c:function cholmod_ccolamd: error: undefined reference to 'ccolamd'
/usr/local/lib/libcholmod.a(cholmod_csymamd.o):cholmod_csymamd.c:function cholmod_csymamd: error: undefined reference to 'ccolamd_set_defaults'
/usr/local/lib/libcholmod.a(cholmod_csymamd.o):cholmod_csymamd.c:function cholmod_csymamd: error: undefined reference to 'csymamd'
collect2: ld returned 1 exit status

<b>What version of the product are you using? On what operating system?</b>

git commit 17fbc8ebb8, Ubuntu 12.04.

<b>Please provide any additional information below.</b>

I built SuiteSparse from source.  By default, it builds static libraries for e.g. libcholmod, and these libraries depend on one another.  If the libraries are not self-contained, you need to pass them to the linker such that all libraries that use a symbol are passed before libraries that define the symbol.  libcholmod depends on a lot of the other libraries, so it needs to be much earlier in CERES_LIBRARY_DEPENDENCES in internal/ceres/CMakeLists.txt.  The patch below solves most of the dependencies, but still errors out on undefined references to blas symbols.  I'll file a separate issue to fix that.

diff --git a/internal/ceres/CMakeLists.txt b/internal/ceres/CMakeLists.txt
index 8c4023e..92b30ee 100644
--- a/internal/ceres/CMakeLists.txt
+++ b/internal/ceres/CMakeLists.txt
@@ -105,14 +105,15 @@ ADD_LIBRARY(ceres

 # TODO(keir): Make linking gomp optional for e.g. Windows.
 SET(CERES_LIBRARY_DEPENDENCIES
-  ${CHOLMOD_LIB}
  ${GLOG_LIB}
  ${GFLAGS_LIB}
  ${LAPACK_LIB}
  ${CAMD_LIB}
  ${AMD_LIB}
  ${CCOLAMD_LIB}
-  ${COLAMD_LIB}
-  ${CHOLMOD_LIB})
-  ${COLAMD_LIB})
  
  IF (EXISTS ${METIS_LIB})
   SET(CERES_LIBRARY_DEPENDENCIES

**Comment by archenroot** [comment]
I just faced this issue on Gentoo system with sci-libs/ceres-solver-1.11.0

**Comment by alexsmac** [comment]
@archenroot what is the linker error you are encountering?
