### ISSUE TITLE
Error when use libceres.a

### ISSUE THREAD

**Issue by Doodleshr** [ceres-solver/ceres-solver#300]
I generated a libceres.a using NDK 10d by executing ./ndk-build in /jni , but when I tried to test it by using 

`g++ filename.cpp -L. -lceres`

 I got tons of errors like what followed below:

 to `google::LogMessageFatal::~LogMessageFatal()'
partitioned_matrix_view_2_3_3.cc:(.text._ZN5ceres8internal21PartitionedMatrixViewILi2ELi3ELi3EEC2ERKNS0_17BlockSparseMatrixEi[_ZN5ceres8internal21PartitionedMatrixViewILi2ELi3ELi3EEC5ERKNS0_17BlockSparseMatrixEi]+0x1b6): undefined reference to `google::LogMessageFatal::~LogMessageFatal()'
//usr/local/lib/libceres.a(partitioned_matrix_view_2_2_4.cc.o): In function `ceres::internal::PartitionedMatrixView<2, 2, 4>::PartitionedMatrixView(ceres::internal::BlockSparseMatrix const&, int)':
partitioned_matrix_view_2_2_4.cc:(.text._ZN5ceres8internal21PartitionedMatrixViewILi2ELi2ELi4EEC2ERKNS0_17BlockSparseMatrixEi[_ZN5ceres8internal21PartitionedMatrixViewILi2ELi2ELi4EEC5ERKNS0_17BlockSparseMatrixEi]+0x152): undefined reference to `google::LogMessageFatal::LogMessageFatal(char const*, int, google::CheckOpString const&)'
partitioned_matrix_view_2_2_4.cc:(.text._ZN5ceres8internal21PartitionedMatrixViewILi2ELi2ELi4EEC2ERKNS0_17BlockSparseMatrixEi[_ZN5ceres8internal21PartitionedMatrixViewILi2ELi2ELi4EEC5ERKNS0_17BlockSparseMatrixEi]+0x15a): undefined reference to `google::LogMessage::stream()'
partitioned_matrix_view_2_2_4.cc:(.text._ZN5ceres8internal21PartitionedMatrixViewILi2ELi2ELi4EEC2ERKNS0_17BlockSparseMatrixEi[_ZN5ceres8internal21PartitionedMatrixViewILi2ELi2ELi4EEC5ERKNS0_17BlockSparseMatrixEi]+0x162): undefined reference to `google::LogMessageFatal::~LogMessageFatal()'
partitioned_matrix_view_2_2_4.cc:(.text._ZN5ceres8internal21PartitionedMatrixViewILi2ELi2ELi4EEC2ERKNS0_17BlockSparseMatrixEi[_ZN5ceres8internal21PartitionedMatrixViewILi2ELi2ELi4EEC5ERKNS0_17BlockSparseMatrixEi]+0x1a6): undefined reference to `google::LogMessageFatal::LogMessageFatal(char const*, int, google::CheckOpString const&)'
partitioned_matrix_view_2_2_4.cc:(.text._ZN5ceres8internal21PartitionedMatrixViewILi2ELi2ELi4EEC2ERKNS0_17BlockSparseMatrixEi[_ZN5ceres8internal21PartitionedMatrixViewILi2ELi2ELi4EEC5ERKNS0_17BlockSparseMatrixEi]+0x1ae): undefined reference to `google::LogMessageFatal::~LogMessageFatal()'
partitioned_matrix_view_2_2_4.cc:(.text._ZN5ceres8internal21PartitionedMatrixViewILi2ELi2ELi4EEC2ERKNS0_17BlockSparseMatrixEi[_ZN5ceres8internal21PartitionedMatrixViewILi2ELi2ELi4EEC5ERKNS0_17BlockSparseMatrixEi]+0x1b6): undefined reference to `google::LogMessageFatal::~LogMessageFatal()'
//usr/local/lib/libceres.a(partitioned_matrix_view_4_4_2.cc.o): In function `ceres::internal::PartitionedMatrixView<4, 4, 2>::PartitionedMatrixView(ceres::internal::BlockSparseMatrix const&, int)':
partitioned_matrix_view_4_4_2.cc:(.text._ZN5ceres8internal21PartitionedMatrixViewILi4ELi4ELi2EEC2ERKNS0_17BlockSparseMatrixEi[_ZN5ceres8internal21PartitionedMatrixViewILi4ELi4ELi2EEC5ERKNS0_17BlockSparseMatrixEi]+0x152): undefined reference to `google::LogMessageFatal::LogMessageFatal(char const*, int, google::CheckOpString const&)'
partitioned_matrix_view_4_4_2.cc:(.text._ZN5ceres8internal21PartitionedMatrixViewILi4ELi4ELi2EEC2ERKNS0_17BlockSparseMatrixEi[_ZN5ceres8internal21PartitionedMatrixViewILi4ELi4ELi2EEC5ERKNS0_17BlockSparseMatrixEi]+0x15a): undefined reference to `google::LogMessage::stream()'
partitioned_matrix_view_4_4_2.cc:(.text._ZN5ceres8internal21PartitionedMatrixViewILi4ELi4ELi2EEC2ERKNS0_17BlockSparseMatrixEi[_ZN5ceres8internal21PartitionedMatrixViewILi4ELi4ELi2EEC5ERKNS0_17BlockSparseMatrixEi]+0x162): undefined reference to `google::LogMessageFatal::~LogMessageFatal()'
partitioned_matrix_view_4_4_2.cc:(.text._ZN5ceres8internal21PartitionedMatrixViewILi4ELi4ELi2EEC2ERKNS0_17BlockSparseMatrixEi[_ZN5ceres8internal21PartitionedMatrixViewILi4ELi4ELi2EEC5ERKNS0_17BlockSparseMatrixEi]+0x1a6): undefined reference to `google::LogMessageFatal::LogMessageFatal(char const*, int, google::CheckOpString const&)'
partitioned_matrix_view_4_4_2.cc:(.text._ZN5ceres8internal21PartitionedMatrixViewILi4ELi4ELi2EEC2ERKNS0_17BlockSparseMatrixEi[_ZN5ceres8internal21PartitionedMatrixViewILi4ELi4ELi2EEC5ERKNS0_17BlockSparseMatrixEi]+0x1ae): undefined reference to `google::LogMessageFatal::~LogMessageFatal()'
partitioned_matrix_view_4_4_2.cc:(.text._ZN5ceres8internal21PartitionedMatrixViewILi4ELi4ELi2EEC2ERKNS0_17BlockSparseMatrixEi[_ZN5ceres8internal21PartitionedMatrixViewILi4ELi4ELi2EEC5ERKNS0_17BlockSparseMatrixEi]+0x1b6): undefined reference to `google::LogMessageFatal::~LogMessageFatal()

It seems that errors were related to glog, but judging by android.mk I found glog related files were included. So I don't know where these errors come from.

Can anyone help me with it? Appreciate your help!!

**Comment by alexsmac** [comment]
It looks like you are trying to link against actual glog when compiling for Android, instead of using the MINIGLOG option in Ceres which compiles a minimal replacement for glog.  Only the latter is supported.

In MINIGLOG, LogMessageFatal() is a function, not a class.  Whereas the errors you are seeing relate to the LogMessageFatal destructor which should only be present in actual glog where LogMessageFatal is a class.
