### ISSUE TITLE
BundleAdjustmentTest fails on mips, mipsel and mips64el

### ISSUE THREAD

**Issue by debalance** [ceres-solver/ceres-solver#305]
BundleAdjustmentTest.SparseNormalCholeskyWithAutomaticOrderingUsingCXSparse fails on the architectures mips, mipsel and mips64el:

> [ RUN      ] BundleAdjustmentTest.SparseNormalCholeskyWithAutomaticOrderingUsingCXSparse
E0728 14:26:41.787685 13464 trust_region_minimizer.cc:91] Terminating: Number of consecutive invalid steps more than Solver::Options::max_num_consecutive_invalid_steps: 5
F0728 14:26:41.889307 13464 test_util.h:175] Check failed: summary.termination_type != ceres::FAILURE (2 vs. 2) 
*** Check failure stack trace: ***
    @ 0x76afc880  google::LogMessage::Fail()
    @ 0x76aff40c  google::LogMessage::SendToLog()
    @ 0x76afc2cc  google::LogMessage::Flush()
    @ 0x76afff5c  google::LogMessageFatal::~LogMessageFatal()
    @ 0x5640eea0  (unknown)
    @ 0x56406c5c  (unknown)
    @ 0x565a9b10  (unknown)
    @ 0x56597630  (unknown)
    @ 0x56597a58  (unknown)
    @ 0x56597d48  (unknown)
    @ 0x56598e08  (unknown)
    @ 0x56599308  (unknown)
    @ 0x5640610c  (unknown)
    @ 0x7671f4c8  __libc_start_main
  99% tests passed, 1 tests failed out of 75
  Total Test time (real) = 905.83 sec
  The following tests FAILED:
	 75 - bundle_adjustment_test (OTHER_FAULT)
 Errors while running CTest
 Makefile:88: recipe for target 'test' failed

I don't know whether that test is new or changed in ceres 1.13 compared to ceres 1.12, but with 1.12.0 all ceres tests passed on those architectures, see
https://buildd.debian.org/status/package.php?p=ceres-solver

The full build logs for all versions of ceres on the 3 mips* architectures are available here:
https://buildd.debian.org/status/logs.php?pkg=ceres-solver&arch=mips
https://buildd.debian.org/status/logs.php?pkg=ceres-solver&arch=mipsel
https://buildd.debian.org/status/logs.php?pkg=ceres-solver&arch=mips64el

**Comment by sandwichmaker** [comment]
@debalance how do you suggest we approach debugging this? I am guessing that this has something to do with the newly done sparsenormalcholeskysolver.  But somehow the tests for sparse normal cholesky solver are not catching it. But without access to a MIPs machine and poking at the internal this is impossible to debug.

**Comment by sandwichmaker** [comment]
@debalance I'd also like to know if this is worth holding the 1.13.0 release back for. WDYT?

**Comment by debalance** [comment]
@sandwichmaker I would not hold back the release for this, you could either make a point-release later or I can simply add a patch to the Debian package if this get fixed.

As for access to mips* hardware, I can help you out if you add a GPG key to your github profile and then follow 
https://dsa.debian.org/doc/guest-account/
using that key.

Another possibility is to emulate a MIPS system using Qemu:
http://thinking-electron.blogspot.de/2016/12/qemu-installing-debian-on-qemu-emulated.html

**Comment by sandwichmaker** [comment]
thanks @debalance that makes sense. I will cut a release and then look into this.
BTW could you try a debug build on MIPS to see if that throws up anything? I suspect this has to do with eigen (before thats the only place we have platform specific code AFAIK).

**Comment by debalance** [comment]
So I ran a manual build on mips with -DCMAKE_BUILD_TYPE=Debug and now bundle_adjustment_test has been running for 12+ hours and counting.
I don't think there's anything helpful in the build log so far, but here it is anyway:
[ceres-solver_1.13.0\~rc1\~dfsg0-1_mips.debug-build.txt](https://github.com/ceres-solver/ceres-solver/files/1189597/ceres-solver_1.13.0.rc1.dfsg0-1_mips.debug-build.txt)

**Comment by debalance** [comment]
The Debug build finally finished exactly like the release build on the buildd before:

> 75/75 Test #75: bundle_adjustment_test .......................***Exception: Other82080.50 sec
Running main() from gmock_main.cc
[==========] Running 36 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 36 tests from BundleAdjustmentTest
[ RUN      ] BundleAdjustmentTest.DenseSchurWithAutomaticOrdering
[       OK ] BundleAdjustmentTest.DenseSchurWithAutomaticOrdering (4562295 ms)
[ RUN      ] BundleAdjustmentTest.DenseSchurWithUserOrdering
[       OK ] BundleAdjustmentTest.DenseSchurWithUserOrdering (4538189 ms)
[ RUN      ] BundleAdjustmentTest.IterativeSchurWithJacobiAndAutomaticOrdering
[       OK ] BundleAdjustmentTest.IterativeSchurWithJacobiAndAutomaticOrdering (6130029 ms)
[ RUN      ] BundleAdjustmentTest.IterativeSchurWithJacobiAndUserOrdering
[       OK ] BundleAdjustmentTest.IterativeSchurWithJacobiAndUserOrdering (6127989 ms)
[ RUN      ] BundleAdjustmentTest.IterativeSchurWithSchurJacobiAndAutomaticOrdering
[       OK ] BundleAdjustmentTest.IterativeSchurWithSchurJacobiAndAutomaticOrdering (5760677 ms)
[ RUN      ] BundleAdjustmentTest.IterativeSchurWithSchurJacobiAndUserOrdering
[       OK ] BundleAdjustmentTest.IterativeSchurWithSchurJacobiAndUserOrdering (5652222 ms)
[ RUN      ] BundleAdjustmentTest.SparseNormalCholeskyWithAutomaticOrderingUsingSuiteSparse
[       OK ] BundleAdjustmentTest.SparseNormalCholeskyWithAutomaticOrderingUsingSuiteSparse (5197885 ms)
[ RUN      ] BundleAdjustmentTest.SparseNormalCholeskyWithUserOrderingUsingSuiteSparse
[       OK ] BundleAdjustmentTest.SparseNormalCholeskyWithUserOrderingUsingSuiteSparse (5042945 ms)
[ RUN      ] BundleAdjustmentTest.SparseSchurWithAutomaticOrderingUsingSuiteSparse
[       OK ] BundleAdjustmentTest.SparseSchurWithAutomaticOrderingUsingSuiteSparse (4549532 ms)
[ RUN      ] BundleAdjustmentTest.SparseSchurWithUserOrderingUsingSuiteSparse
[       OK ] BundleAdjustmentTest.SparseSchurWithUserOrderingUsingSuiteSparse (4542087 ms)
[ RUN      ] BundleAdjustmentTest.IterativeSchurWithClusterJacobiAndAutomaticOrderingUsingSuiteSparse
[       OK ] BundleAdjustmentTest.IterativeSchurWithClusterJacobiAndAutomaticOrderingUsingSuiteSparse (5903101 ms)
[ RUN      ] BundleAdjustmentTest.IterativeSchurWithClusterJacobiAndUserOrderingUsingSuiteSparse
[       OK ] BundleAdjustmentTest.IterativeSchurWithClusterJacobiAndUserOrderingUsingSuiteSparse (5925677 ms)
[ RUN      ] BundleAdjustmentTest.IterativeSchurWithClusterTridiagonalAndAutomaticOrderingUsingSuiteSparse
[       OK ] BundleAdjustmentTest.IterativeSchurWithClusterTridiagonalAndAutomaticOrderingUsingSuiteSparse (6316219 ms)
[ RUN      ] BundleAdjustmentTest.IterativeSchurWithClusterTridiagonalAndUserOrderingUsingSuiteSparse
[       OK ] BundleAdjustmentTest.IterativeSchurWithClusterTridiagonalAndUserOrderingUsingSuiteSparse (6916857 ms)
[ RUN      ] BundleAdjustmentTest.SparseNormalCholeskyWithAutomaticOrderingUsingCXSparse
E0801 16:51:06.775589 27784 trust_region_minimizer.cc:91] Terminating: Number of consecutive invalid steps more than Solver::Options::max_num_consecutive_invalid_steps: 5
F0801 16:51:06.933979 27784 test_util.h:175] Check failed: summary.termination_type != ceres::FAILURE (2 vs. 2) 
*** Check failure stack trace: ***
    @ 0x77030880  google::LogMessage::Fail()
    @ 0x7703340c  google::LogMessage::SendToLog()
    @ 0x770302cc  google::LogMessage::Flush()
    @ 0x77033f5c  google::LogMessageFatal::~LogMessageFatal()
    @ 0x562d6978  (unknown)
    @ 0x562ced5c  (unknown)
    @ 0x5648d428  (unknown)
    @ 0x5647c654  (unknown)
    @ 0x5647ca0c  (unknown)
    @ 0x5647cc78  (unknown)
    @ 0x5647d258  (unknown)
    @ 0x5647d76c  (unknown)
    @ 0x562ce204  (unknown)
    @ 0x76c554c8  __libc_start_main
99% tests passed, 1 tests failed out of 75
Total Test time (real) = 84463.75 sec
The following tests FAILED:
         75 - bundle_adjustment_test (OTHER_FAULT)
Errors while running CTest
Makefile:76: recipe for target 'test' failed

**Comment by alexsmac** [comment]
@debalance I notice that the successful 1.12 build was using Eigen 3.3.2, but the failing 1.13 build was using Eigen 3.3.4.  Both of them appear to be using CXSparse 3.1.9 and SuiteSparse 4.5.5.  Is it possible to rebuild 1.13 with Eigen 3.3.2 (or the converse, i.e. 1.12 with 3.3.4) so that we can isolate whether the Eigen version is a factor?

**Comment by debalance** [comment]
Good thinking! I'm currently doing a build in a Debian Stretch chroot (which ships Eigen 3.3.2).

**Comment by debalance** [comment]
The rebuild on Stretch has exactly the same result, so the slightly different version of Eigen is unlikely to be the cause.

**Comment by sandwichmaker** [comment]
@debalance is this still a thing?

**Comment by debalance** [comment]
Yes it is, with the current release the output is a bit more specific:

> The following tests FAILED:
	112 - ba_sparsecholesky_cxsparse_auto_test (Child aborted)
	113 - ba_sparsecholesky_cxsparse_auto_threads_test (Child aborted)
	114 - ba_sparsecholesky_cxsparse_user_test (Child aborted)
	115 - ba_sparsecholesky_cxsparse_user_threads_test (Child aborted)

**Comment by sandwichmaker** [comment]
interesting, so this seems like a cxsparse problem more than anything else.

**Comment by sandwichmaker** [comment]
I am going to close this, as this is rather old at this point, and if this continues to be an issue please reopen.
