### ISSUE TITLE
Failing tests on Release Build on Windows x64 

### ISSUE THREAD

**Issue by happypepper** [ceres-solver/ceres-solver#308]
Built lib file successfully on windows with Eigen 3.3.4, but it fails a bunch of tests. I've listed them here:

1>16/75 Test #16: corrector_test ...............................***Failed    0.08 sec
1>18/75 Test #18: covariance_test ..............................***Failed    0.10 sec
1>34/75 Test #34: graph_test ...................................***Failed    0.06 sec
1>46/75 Test #46: local_parameterization_test ..................***Failed    0.09 sec
1>51/75 Test #51: ordered_groups_test ..........................***Failed    0.03 sec
1>52/75 Test #52: parameter_block_test .........................***Failed    0.10 sec
1>56/75 Test #56: problem_test .................................***Failed    0.52 sec
1>70/75 Test #70: triplet_sparse_matrix_test ...................***Failed    0.03 sec

here's the output from corrector_test:

Running main() from gmock_main.cc
[==========] Running 7 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 7 tests from Corrector
[ RUN      ] Corrector.ZeroGradientDeathTest
Running main() from gmock_main.cc
C:\Users\lawson\ceres\ceres-solver-1.13.0\internal\ceres\corrector_test.cc(48):
error: Death test: {Corrector c(1.0, kRho);}
    Result: died but not with expected exit code:
            Exited with exit status 0
Actual msg:
[  DEATH   ] *** Check failure stack trace: ***
[  DEATH   ]     @   000000013FE1EA45  (unknown)
[  DEATH   ]     @   000000013FE1E192  (unknown)
[  DEATH   ]     @   000000013FE007C8  (unknown)
[  DEATH   ]     @   000000013FDF4614  (unknown)
[  DEATH   ]     @   000000013FE01E4C  (unknown)
[  DEATH   ]     @   000000013FE01CAF  (unknown)
[  DEATH   ]     @   000000013FE18220  (unknown)
[  DEATH   ]     @   000000013FE189D5  (unknown)
[  DEATH   ]     @   000000013FE01EEC  (unknown)
[  DEATH   ]     @   000000013FE01E0F  (unknown)
[  DEATH   ]     @   000000013FE184D0  (unknown)
[  DEATH   ]     @   000000013FE2438B  (unknown)
[  DEATH   ]     @   000000013FE23469  (unknown)
[  DEATH   ]     @   000000007744652D  BaseThreadInitThunk
[  DEATH   ]     @   000000007757C541  RtlUserThreadStart
**[  DEATH   ] F0813 23:18:26.479892  3776 corrector.cc:93] Check failed: rho[1] >
 0.0 (0 vs. 0)**
[  DEATH   ]
[  FAILED  ] Corrector.ZeroGradientDeathTest (41 ms)
[ RUN      ] Corrector.NegativeGradientDeathTest
Running main() from gmock_main.cc
C:\Users\lawson\ceres\ceres-solver-1.13.0\internal\ceres\corrector_test.cc(55):
error: Death test: {Corrector c(1.0, kRho);}
    Result: died but not with expected exit code:
            Exited with exit status 0
Actual msg:
[  DEATH   ] *** Check failure stack trace: ***
[  DEATH   ]     @   000000013FE1EA45  (unknown)
[  DEATH   ]     @   000000013FE1E192  (unknown)
[  DEATH   ]     @   000000013FE007C8  (unknown)
[  DEATH   ]     @   000000013FDF4898  (unknown)
[  DEATH   ]     @   000000013FE01E4C  (unknown)
[  DEATH   ]     @   000000013FE01CAF  (unknown)
[  DEATH   ]     @   000000013FE18220  (unknown)
[  DEATH   ]     @   000000013FE189D5  (unknown)
[  DEATH   ]     @   000000013FE01EEC  (unknown)
[  DEATH   ]     @   000000013FE01E0F  (unknown)
[  DEATH   ]     @   000000013FE184D0  (unknown)
[  DEATH   ]     @   000000013FE2438B  (unknown)
[  DEATH   ]     @   000000013FE23469  (unknown)
[  DEATH   ]     @   000000007744652D  BaseThreadInitThunk
[  DEATH   ]     @   000000007757C541  RtlUserThreadStart
**[  DEATH   ] F0813 23:18:26.518894 11908 corrector.cc:93] Check failed: rho[1] >
 0.0 (-0.1 vs. 0)**
[  DEATH   ]
[  FAILED  ] Corrector.NegativeGradientDeathTest (40 ms)
[ RUN      ] Corrector.ScalarCorrection
[       OK ] Corrector.ScalarCorrection (0 ms)
[ RUN      ] Corrector.ScalarCorrectionZeroResidual
[       OK ] Corrector.ScalarCorrectionZeroResidual (0 ms)
[ RUN      ] Corrector.ScalarCorrectionAlphaClamped
[       OK ] Corrector.ScalarCorrectionAlphaClamped (0 ms)
[ RUN      ] Corrector.MultidimensionalGaussNewtonApproximation
[       OK ] Corrector.MultidimensionalGaussNewtonApproximation (39 ms)
[ RUN      ] Corrector.MultidimensionalGaussNewtonApproximationZeroResidual
[       OK ] Corrector.MultidimensionalGaussNewtonApproximationZeroResidual (17
ms)
[----------] 7 tests from Corrector (146 ms total)

[----------] Global test environment tear-down
[==========] 7 tests from 1 test case ran. (150 ms total)
[  PASSED  ] 5 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] Corrector.ZeroGradientDeathTest
[  FAILED  ] Corrector.NegativeGradientDeathTest

 2 FAILED TESTS

And here's the output from covariance_test:

Running main() from gmock_main.cc
[==========] Running 15 tests from 3 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from CovarianceImpl
[ RUN      ] CovarianceImpl.ComputeCovarianceSparsity
[       OK ] CovarianceImpl.ComputeCovarianceSparsity (1 ms)
[ RUN      ] CovarianceImpl.ComputeCovarianceSparsityWithConstantParameterBlock
[       OK ] CovarianceImpl.ComputeCovarianceSparsityWithConstantParameterBlock
(0 ms)
[ RUN      ] CovarianceImpl.ComputeCovarianceSparsityWithFreeParameterBlock
[       OK ] CovarianceImpl.ComputeCovarianceSparsityWithFreeParameterBlock (0 m
s)
[----------] 3 tests from CovarianceImpl (4 ms total)

[----------] 11 tests from CovarianceTest
[ RUN      ] CovarianceTest.NormalBehavior
[       OK ] CovarianceTest.NormalBehavior (10 ms)
[ RUN      ] CovarianceTest.ThreadedNormalBehavior
[       OK ] CovarianceTest.ThreadedNormalBehavior (8 ms)
[ RUN      ] CovarianceTest.ConstantParameterBlock
[       OK ] CovarianceTest.ConstantParameterBlock (4 ms)
[ RUN      ] CovarianceTest.LocalParameterization
[       OK ] CovarianceTest.LocalParameterization (6 ms)
[ RUN      ] CovarianceTest.LocalParameterizationInTangentSpace
[       OK ] CovarianceTest.LocalParameterizationInTangentSpace (5 ms)
[ RUN      ] CovarianceTest.LocalParameterizationInTangentSpaceWithConstantBlock
s
[       OK ] CovarianceTest.LocalParameterizationInTangentSpaceWithConstantBlock
s (2 ms)
[ RUN      ] CovarianceTest.TruncatedRank
[       OK ] CovarianceTest.TruncatedRank (7 ms)
[ RUN      ] CovarianceTest.DenseCovarianceMatrixFromSetOfParameters
[       OK ] CovarianceTest.DenseCovarianceMatrixFromSetOfParameters (5 ms)
[ RUN      ] CovarianceTest.DenseCovarianceMatrixFromSetOfParametersThreaded
[       OK ] CovarianceTest.DenseCovarianceMatrixFromSetOfParametersThreaded (5
ms)
[ RUN      ] CovarianceTest.DenseCovarianceMatrixFromSetOfParametersInTangentSpa
ce
[       OK ] CovarianceTest.DenseCovarianceMatrixFromSetOfParametersInTangentSpa
ce (4 ms)
[ RUN      ] CovarianceTest.ComputeCovarianceFailure
Running main() from gmock_main.cc
C:\Users\lawson\ceres\ceres-solver-1.13.0\internal\ceres\covariance_test.cc(1090
): error: Death test: covariance.Compute(parameter_blocks, &problem_)
    Result: died but not with expected exit code:
            Exited with exit status 0
Actual msg:
[  DEATH   ] *** Check failure stack trace: ***
[  DEATH   ]     @   0000000140023D85  (unknown)
[  DEATH   ]     @   00000001400234E2  (unknown)
[  DEATH   ]     @   000000013FFD9686  (unknown)
[  DEATH   ]     @   000000013FFED7D9  (unknown)
[  DEATH   ]     @   000000013FFC66A3  (unknown)
[  DEATH   ]     @   000000014000581C  (unknown)
[  DEATH   ]     @   000000014000567F  (unknown)
[  DEATH   ]     @   000000014001D8B0  (unknown)
[  DEATH   ]     @   000000014001E065  (unknown)
[  DEATH   ]     @   00000001400058BC  (unknown)
[  DEATH   ]     @   00000001400057DF  (unknown)
[  DEATH   ]     @   000000014001DB60  (unknown)
[  DEATH   ]     @   00000001400297FB  (unknown)
[  DEATH   ]     @   00000001400283D9  (unknown)
[  DEATH   ]     @   000000007744652D  BaseThreadInitThunk
[  DEATH   ]     @   000000007757C541  RtlUserThreadStart
[  DEATH   ] F0813 23:19:03.785027 10340 covariance_impl.cc:118] Covariance::Com
pute called with duplicate blocks at indices (0, 1) and (2, 3)
[  DEATH   ]
Running main() from gmock_main.cc
C:\Users\lawson\ceres\ceres-solver-1.13.0\internal\ceres\covariance_test.cc(1098
): error: Death test: covariance.Compute(covariance_blocks, &problem_)
    Result: died but not with expected exit code:
            Exited with exit status 0
Actual msg:
[  DEATH   ] *** Check failure stack trace: ***
[  DEATH   ]     @   0000000140023D85  (unknown)
[  DEATH   ]     @   00000001400234E2  (unknown)
[  DEATH   ]     @   000000013FFD9D40  (unknown)
[  DEATH   ]     @   000000013FFED932  (unknown)
[  DEATH   ]     @   000000013FFC68F6  (unknown)
[  DEATH   ]     @   000000014000581C  (unknown)
[  DEATH   ]     @   000000014000567F  (unknown)
[  DEATH   ]     @   000000014001D8B0  (unknown)
[  DEATH   ]     @   000000014001E065  (unknown)
[  DEATH   ]     @   00000001400058BC  (unknown)
[  DEATH   ]     @   00000001400057DF  (unknown)
[  DEATH   ]     @   000000014001DB60  (unknown)
[  DEATH   ]     @   00000001400297FB  (unknown)
[  DEATH   ]     @   00000001400283D9  (unknown)
[  DEATH   ]     @   000000007744652D  BaseThreadInitThunk
[  DEATH   ]     @   000000007757C541  RtlUserThreadStart
**[  DEATH   ] F0813 23:19:03.817028 13712 covariance_impl.cc:118] Covariance::Com
pute called with duplicate blocks at indices (0, 1) and (2, 3)**
[  DEATH   ]
[  FAILED  ] CovarianceTest.ComputeCovarianceFailure (63 ms)
[----------] 11 tests from CovarianceTest (129 ms total)

[----------] 1 test from RankDeficientCovarianceTest
[ RUN      ] RankDeficientCovarianceTest.AutomaticTruncation
[       OK ] RankDeficientCovarianceTest.AutomaticTruncation (2 ms)
[----------] 1 test from RankDeficientCovarianceTest (3 ms total)

[----------] Global test environment tear-down
[==========] 15 tests from 3 test cases ran. (140 ms total)
[  PASSED  ] 14 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CovarianceTest.ComputeCovarianceFailure

 1 FAILED TEST

**Comment by sandwichmaker** [comment]
The common thing here seems to be that every one of these is a death test and the macro in question is EXPECT_DEATH_IF_SUPPORTED. What is your build environment? can you share your cmake log? I suspect this has to do with gunit/the testing framework and your dev environment interacting poorly.

**Comment by happypepper** [comment]
I'm using Visual Studio 2017 Community. I just tested with Eigen 3.2.10 and it fails on the same tests.

Here's the cmake log using Eigen 3.3.4:

Detected Ceres version: 1.13.0 from C:/Users/lawson/ceres/ceres-solver-1.13.0/include/ceres/version.h
No preference for use of exported Eigen CMake configuration set, and no hints for include directory provided. Defaulting to preferring an installed/exported Eigen CMake configuration if available.
Failed to find installed Eigen CMake configuration, searching for Eigen build directories exported with CMake.
Failed to find an installed/exported CMake configuration for Eigen, will perform search for installed Eigen components.
Found Eigen: C:/Users/lawson/ceres/Eigen (found version "3.3.4") 
-- Found Eigen version 3.3.4: C:/Users/lawson/ceres/Eigen

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

-- Building without LAPACK.
-- Building without SuiteSparse.
-- Building without CXSparse.
   ===============================================================
   Compiling without any sparse library: SuiteSparse, CXSparse 
   & Eigen (Sparse) are all disabled or unavailable.  No sparse 
   linear solvers (SPARSE_NORMAL_CHOLESKY & SPARSE_SCHUR)
   will be available when Ceres is used.
   ===============================================================
No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
Found installed version of gflags: C:/Users/lawson/ceres/gflags/build64
Detected gflags version: 2.2.1
-- Found Google Flags header in: C:/Users/lawson/ceres/gflags/build64/include, in namespace: google
No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
Found installed version of glog: C:/Users/lawson/ceres/google-glog/build64
Detected glog version: 0.3.5
-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
-- Building with OpenMP.
Looking for C++ include unordered_map
Looking for C++ include unordered_map - found
Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE
Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE - Success
-- Found unordered_map/set in std namespace.
Looking for C++ include memory
Looking for C++ include memory - found
Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
-- Found shared_ptr in std namespace using <memory> header.
-- Building Ceres as a static library.
Enabling CERES_NO_LAPACK in Ceres config.h
Enabling CERES_NO_SUITESPARSE in Ceres config.h
Enabling CERES_NO_CXSPARSE in Ceres config.h
Enabling CERES_USE_OPENMP in Ceres config.h
Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
Enabling CERES_MSVC_USE_UNDERSCORE_PREFIXED_BESSEL_FUNCTIONS in Ceres config.h
-- Build the examples.
Configuring done

**Comment by sandwichmaker** [comment]
Thanks for sharing. I am going to need @alexsmac ' s help in this matter. This is not an Eigen issue. This is most likely a gunit issue.

**Comment by happypepper** [comment]
Thank you for your quick reply. If it is just a testing issue, does this mean that the produced ceres lib is usable?

**Comment by sandwichmaker** [comment]
@happypepper I do not know. I am guessing it should be okay.

**Comment by happypepper** [comment]
I disabled GTEST_HAS_DEATH_TEST and all tests passed!
