### ISSUE TITLE
Segmentation fault when Solver::Summary deconstruct

### ISSUE THREAD

**Issue by ytzhao** [ceres-solver/ceres-solver#309]
Hi all,

I'm fresh to Ceres, I met a problem but could find any solution till now.
I followed the tutorial document on the official [Ceres page](http://ceres-solver.org/nnls_tutorial.html#numeric-derivatives) and tried the example in "Numeric Derivatives" part without any change at all.
When I run this code, I can get the correct answer and brief report printed in the terminal of the problem _f(x) -10_. But then, at the end of the code, when return back, the program crashed with segmentation fault message 

> in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6

My environment : 
Ubuntu1604
Qt 5.7
g++ (GCC) (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
libstdc++.so.6.0.21
the program is compiled with -fPIC, and -D_GLIBCXX_USE_CXX11_ABI=0.

I have no ideas what happened, could some has any solutions to address this problem. Thanks! :)

**Comment by alexsmac** [comment]
@ytzhao do you mean that you tried to run the helloworld_numeric_diff example from <CERES_BUILD_DIR>/bin?  Or do you mean that you created a separate project outside of Ceres and copied helloworld_numeric_diff.cc into it and tried to compile it against Ceres?  If you did the latter, how did you find Ceres, via a find_package(Ceres) with CMake [as per this example](http://ceres-solver.org/installation.html#using-ceres-with-cmake)?

I assume that this is an ABI mismatch related to C++11.  Specifically that you are compiling (I assume) helloworld_numeric_diff.cc separately (i.e. outside the Ceres project) and linking it against Ceres, however you are passing:

_GLIBCXX_USE_CXX11_ABI=0.

when compiling helloworld_numeric_diff, [but the default in GCC5 is](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html):

_GLIBCXX_USE_CXX11_ABI=1

and so Ceres itself would have been compiled with _GLIBCXX_USE_CXX11_ABI=1, thus you are getting an ABI conflict.

**Comment by ytzhao** [comment]
@alexsmac Hi Alex, thanks first. I didn't run the helloworld_numeric_diff. I've made a new project to test Ceres with Qt5.7. The problem is to find the minimal value of (1/2) * (10-x)^2. I run the same without change in another environment:
Ubuntu1404
Qt5.7
g++ (GCC) (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
libstdc++.so.6.0.19
the program is still compiled with -fPIC, and -D_GLIBCXX_USE_CXX11_ABI=0.

BUT, everything goes well without any problems. But I'll try to test the code with _GLIBCXX_USE_CXX11_ABI=1, :)

**Comment by sandwichmaker** [comment]
@ytzhao any updates on this?

**Comment by ytzhao** [comment]
@sandwichmaker sorry to reply you late, this solution works well for me. Thank you! :)
