### ISSUE TITLE
Can't build on iOS 11

### ISSUE THREAD

**Issue by elviskuo07** [ceres-solver/ceres-solver#313]
clang: error: invalid iOS deployment version '-miphoneos-version-min=11.0', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]
clang: error: invalid iOS deployment version '-miphoneos-version-min=11.0', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]

**Comment by sandwichmaker** [comment]
ping @alexsmac ?

**Comment by alexsmac** [comment]
@elviskuo07 this should be fixed in this CL: https://ceres-solver-review.googlesource.com/c/ceres-solver/+/12580

**Comment by alexsmac** [comment]
The fix has now been merged into master.
