### ISSUE TITLE
Subcommand fails when building Ceres with ninja

### ISSUE THREAD

**Issue by msy22** [ceres-solver/ceres-solver#317]
I am trying to install Ceres for use with Google Cartgographer. I've been following the installation instructions provided on the Cartographer [read the docs page](https://google-cartographer.readthedocs.io/en/latest/), which uses `ninja` to build it. Unfortunately, the build fails at this line:

    user@computer:~/ceres-solver/build$ ninja

with a fairly lengthy error:

    [309/344] Building CXX object internal/ceres/CMakeFiles/tiny_solver_test.dir/tiny_solver_test.cc.o ...
    .
    .
    .
    ninja: build stopped: subcommand failed.

The full error is in this text file here: [ceres_solver_ninja_error](https://drive.google.com/open?id=0B1KZT92BcdVNMjg5VDVYYUtZQmc). 

I'm not sure if this is an issue with Ceres or the ninja builder, but I figured I should post this issue here first. Any help or advice on how to solve this issue and proceed with the build is greatly appreciated.

**Comment by keir** [comment]
Hi M@t,

Yep, master is broken. Thanks for the report; I'll try to fix this now.

Cheers,
Keir

**Comment by keir** [comment]
In the interim, you can just use the latest stable or go back a couple of
patches, and everything should work.

**Comment by keir** [comment]
Fixed:
https://ceres-solver-review.googlesource.com/c/ceres-solver/+/11240

**Comment by msy22** [comment]
Fantastic, I can confirm that everything at my ends installs properly now and seems to be working.

**Comment by Yxxxb** [comment]
I met a similar error while making ceres, do u know how to deal with it?

> [1/293] Linking CXX executable bin/trust_region_minimizer_test
FAILED: bin/trust_region_minimizer_test 
: && /usr/bin/c++  -Wmissing-declarations -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -O3 -DNDEBUG   internal/ceres/CMakeFiles/trust_region_minimizer_test.dir/trust_region_minimizer_test.cc.o  -o bin/trust_region_minimizer_test  lib/libgtest.a  lib/libtest_util.a  lib/libceres.a  /usr/lib/x86_64-linux-gnu/libspqr.so  lib/libgtest.a  lib/libceres.a  /usr/lib/x86_64-linux-gnu/libspqr.so  /usr/lib/x86_64-linux-gnu/libtbb.so  /usr/lib/x86_64-linux-gnu/libglog.so  /usr/lib/x86_64-linux-gnu/libcholmod.so  /usr/lib/x86_64-linux-gnu/libamd.so  /usr/lib/x86_64-linux-gnu/libcamd.so  /usr/lib/x86_64-linux-gnu/libccolamd.so  /usr/lib/x86_64-linux-gnu/libcolamd.so  /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so  -lrt  /usr/lib/x86_64-linux-gnu/liblapack.so  /usr/lib/x86_64-linux-gnu/libf77blas.so  /usr/lib/x86_64-linux-gnu/libatlas.so  /usr/lib/x86_64-linux-gnu/libgflags.so.2.2.2  -lpthread && :
/usr/bin/ld: lib/libceres.a(eigensparse.cc.o): undefined reference to symbol 'METIS_NodeND'
/usr/bin/ld: /lib/x86_64-linux-gnu/libmetis.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by Yxxxb** [comment]
> 

I finally use "make .." and then ninja, it works.
