### ISSUE TITLE
Revisit #251: Alignment Issue with Eigen 3.3.1

### ISSUE THREAD

**Issue by daemacles** [ceres-solver/ceres-solver#319]
This is sort of re-opening https://github.com/ceres-solver/ceres-solver/issues/251

I'm having a similar problem with 1.12, and see that in change 1271 (https://ceres-solver-review.googlesource.com/c/ceres-solver/+/1271) the `EIGEN_MAKE_ALIGNED_OPERATOR` was removed from `FixedArray::InnerContainer`, along with setting `Jet::v` to `Eigen::DontAlign`.

At some point later with C++11, the `DontAlign` requirement was removed from `Jet`, however `FixedArray::InnerContainer` did not get `EIGEN_MAKE_ALIGNED_OPERATOR` back (and it's still that way in master).  The result is that when I tried to solve a particular problem, the heap allocated storage for `FixedArray` (https://ceres-solver.googlesource.com/ceres-solver/+/master/include/ceres/internal/fixed_array.h#168) is not appropriately aligned for the `Jet::v`, and I get the dreaded Eigen failed alignment assertion.

```
Eigen/src/Core/DenseStorage.h:128: Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 32>::plain_array() [with T = double; int Size = 20; int MatrixOrArrayOptions = 0]: Assertion `(internal::UIntPtr(eigen_unaligned_array_assert_workaround_gcc47(array)) & (31)) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"' failed.
```

The simple fix in my case is to stick `EIGEN_MAKE_ALIGNED_OPERATOR_NEW` back in.  But I'm not intimately familiar with Ceres' internals, and am not sure if this introduces subtle errors elsewhere, as change 1271 was put in place to avoid.

**Comment by sandwichmaker** [comment]
@keir can you take a look?

**Comment by keir** [comment]
I've spent some time digging into this, and a proper fix is not trivial. I have a patch underway but it will require some further work.

**Comment by daemacles** [comment]
Thanks for taking the time to look into this.  Let me know if I can help with it, e.g. running tests before your patch goes in, etc.

**Comment by keir** [comment]
My belief is that the current code is already broken, strictly speaking, even though it mostly works. I may split the patch to add a workaround for the specific issue in this case, which is essentially the suggested patch, and then have a followup to reconsider the alignment issue more broadly.

**Comment by sandwichmaker** [comment]
ping? @keir

**Comment by keir** [comment]
I spent some time digging into this but could not figure out a satisfying resolution. I'll have to circle back next year.

**Comment by sandwichmaker** [comment]
ping?

**Comment by keir** [comment]
Sorry, I haven't had a chance to dive back into this yet.

**Comment by BrannonKing** [comment]
What's wrong with utilizing EIGEN_MAKE_ALIGNED_OPERATOR_NEW to repair this issue?

**Comment by sandwichmaker** [comment]
@keir can you take a look at this please?

**Comment by BrannonKing** [comment]
Bump!

**Comment by sandwichmaker** [comment]
https://github.com/ceres-solver/ceres-solver/commit/939253c208718689c8f141a2aa97ba0827478a93 should fix it.
