### ISSUE TITLE
Use of Taylor expansions in rotation.h

### ISSUE THREAD

**Issue by NikolausDemmel** [ceres-solver/ceres-solver#320]
All resources I know state that for the rotation conversion formulae such as the ones in [rotation.h](https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/rotation.h) you should use the Taylor expansion for small angles, to avoid numerical instabilities. The implementation in Ceres uses the first order Taylor expansion for `angle > 0` for some and `angle > numerical_limits::epsilon` for others.

I was wondering if (higher order) Tayler expansions should not be used for other small angles. The question is of course, how small angles, and what order Taylor expansion is needed.

Sophus for example does [Taylor expansion up to `theta^4` terms](https://github.com/strasdat/Sophus/blob/3f84e42a7a796bb6c9a1f57f5708911459a49221/sophus/so3.hpp#L334) and uses as [epsilon `1e-10` for double and `1e-5` for float](https://github.com/strasdat/Sophus/blob/3f84e42a7a796bb6c9a1f57f5708911459a49221/sophus/common.hpp#L139-L147).

Does anyone know how much of a difference this really makes, for example in manifold optimization, where the converted angles for parameter-updates are always small close to convergence? Does it make sense to update the conversions in `rotation.h`?

References:
* http://ingmec.ual.es/~jlblanco/papers/jlblanco2010geometry3D_techrep.pdf
* www.iri.upc.edu/people/jsola/JoanSola/objectes/notes/kinematics.pdf
* http://ethaneade.com/lie.pdf

**Comment by NikolausDemmel** [comment]
This is related: https://ceres-solver-review.googlesource.com/c/ceres-solver/+/4180

**Comment by sandwichmaker** [comment]
@NikolausDemmel since you are raising the issue, perhaps you can run some tests and report back?

**Comment by NikolausDemmel** [comment]
@sandwichmaker, fair enough, I will see what I can do as time permits.

I was still wondering what peoples wisdom from practice is. It could be that some say it's fine as is implemented, or that there are specific reasons for `angle > 0` vs `angle > numerical_limits::epsilon`. Or it is mostly incidental and when this was implement the question didn't come up, it worked fine, and noone had time to consider this more. I myself have no clue.

How would you test this?

Ideas:
- generate small lie algebra objects `x` randomly, and check `abs(x - log(exp(x))` which we would expect to grow larger for really small x if the current implementation has numerical issue close to 0. However, there might be correlated errors in exp and log that you might not capture with this test. Alternatively you could look at `abs(x - log<double>(exp<float>(x))` 
- Check `norm(exp<float>(x) - exp<double>(x))` for small x. You should see if and when numerical issue arise for single-precision floats by increasing difference for decreasing x.
- The above tests should then be repeated by Taylor-expansions of different orders.

Am I missing something obvious?

**Comment by sandwichmaker** [comment]
mostly incidental if I recall correctly. If it is not, then changing that threshold should cause one of the tests to fail. 

The taylor expansion matters at two places. 
1. The value of f(x)
2. The value of Df(x)

The way to do this IMO is to compute values of f(x) and Df(x) for various small values of x, using an extended precision method (say mathematica/maple) and then compare it to the values you are getting out of rotation.h

**Comment by sandwichmaker** [comment]
ping?

**Comment by NikolausDemmel** [comment]
I haven't yet had the time to add the Taylor expansion implementation and unit tests. It's still on my agenda, but I can't tell when I'll get to it unfortunately...

**Comment by sandwichmaker** [comment]
Closing as there is no response. Please reopen if you come back to it.
