### ISSUE TITLE
Ceres headers leak the glog macros

### ISSUE THREAD

**Issue by cbeck88** [ceres-solver/ceres-solver#323]
Ceres uses either `glog` or `miniglog` for logging, which is fine.

What is bad is that including Ceres headers into your project leaks the `#define`'s of glog everywhere, and miniglog brings in many of the same defines.

This is a really big problem for any large project that is using Ceres and not glog, or is using something else with similar macros, or wants to migrate from something else to glog, or from glog to something else, without breaking everything.

It is bad form for a library to leak extremely common preprocessor symbols like `LOG` and `ERROR` -- historically the `windows.h` headers have always done annoying things like this but this is not an example to follow.

Suggested remedy:

- Any preprocessor symbol that Ceres leaks from its headers, should be prefixed with `CERES_` to avoid collisions in namespace of consumer. `CERES_LOG_INFO`, `CERES_LOG_WARNING`, `CERES_LOG_FATAL`, `CERES_LOG`, etc. And all Ceres logging should be done by such macros.
- Ceres should provide a `ceres_logging.cc`(or similar) file containing implementation of functions wrapped by these macros, which forwards to glog interface if configured that way, or to miniglog if configured that way. On a modern compiler with link-time optimizations, all of these forwarding calls are most likely inlined and no run-time overhead occurs, but the glog interface is only included in a `.cc` or `.cpp` file rather than in a ceres header.
- Ceres could provide the option for the user to override the `CERES_LOG_INFO` etc. macros. This can be done by defining the macros like so:
    ```
    // begin hypothetical "ceres_logging.h"
    #pragma once
    #include "ceres/config.h"

    #ifndef CERES_LOG_INFO
    #define CERES_LOG_INFO ...
    #endif
    
    #ifndef CERES_LOG_WARNING
    #define CERES_LOG_WARNING ...
    #endif
    
    ...
    ```

Then the user can reconfigure ceres logging very easily, by going into `ceres/config.h` and including their own logging infrastructure and defining these macros in terms of their own logging. They could create a special channel for Ceres messages and use that in the macros.

- There would be no imposed runtime overhead or significant cost to ceres maintanence (prefixing your preprocessor symbols with your libname is standard fare among open source library projects)
- The users of Ceres would have much more flexibility to manage ceres' (quite useful) text logs
- Ceres would be able to allow "dependency injection" here without e.g. asking the user for function pointers to a custom logging infrastructure, or using other more complicated / costly language constructs.
- It would become much simpler to "just turn off all the Ceres logs in release, period", without disabling glog
- Ceres would have much better hygeine from the point of view of global namespace pollution
- It would be much easier to use Ceres alongside a logging library that is not glog but is similar to (and incompatible with) glog.
- Maintaining such a configuration cannot be more work than maintaining `miniglog` and for any users that were interested in miniglog option in the first place, this is probably a lot more attractive.

**Comment by sandwichmaker** [comment]
@cbeck88 you make a good point. I believe the bulk of these problems arise in headers which are using templates like autodiff_cost_function.h etc.

I'd also like to understand what is it that you are trying to do in your application. Which of the various problems you are talking about is most relevant to you. 

Last but not the least, would you be willing to work on this?

**Comment by cbeck88** [comment]
> Which of the various problems you are talking about is most relevant to you.

We (tesla) are using Ceres in various parts of autopilot firmware. We are also using glog for our primary logging. However, we have a heavily patched / modified version of glog, because we have a real-time critical safety criteria, and we are not supposed to make dynamic allocations e.g. while the car is moving.

We therefore have a heavily modified version of glog. We generally only use the "raw_logging" stuff, and we have redefined some of the traditional glog macros in terms of the raw_logging framework.

In our code we only use the `printf`-style interface, and anything that is streamed into the log, e.g `LOG(INFO) << "foobar"`, just turns into a no-op (since `std::ostream` makes allocations in general).

Most if not all of Ceres logging gets wiped out by that AFAIU. However, it appears that we also do things like, turn off all glog logging before we get to Ceres (except when in "developer" mode, which means that someone at their desk wants to read the Ceres optimization report for instance).

It appears, on reading our code, that we sometimes manually turn off all the glog logging (via the flags) before calling into Ceres, and then restore the settings (except when in developer mode).

---

This is all going to change now, because we even the glog raw_logging is not really safe in real-time critical context -- it writes to pipe using a system call, for instance, and a system call can block. It also makes several call to `snprintf` in the hot path.

We are moving to a framework where logging will be done by using `memcpy` to place the log entries directly into ring buffer slots in a shared memory ring buffer. A logger process running at lower priority will later run over these ring buffers and clean them up (formatting them and writing them out to disk).

We've decided not to just completely gut / hack up glog in order to somehow make the glog header call into this -- we're just going to make our own logger library, and only seek compatibility with the glog-like macros we previously exposed.

An additional complication is that there is a "sim" team which runs software-in-the-loop simulations of the autopilot stack, and they want to use glog for their logger, because their existing logger is somehow incompatible with a multithreading technology that they are using. They really want autopilot to be completely off of glog because it is awkward if sim software cannot keep its logs separate from the firmware under test, or set its log levels independently from the code under test. And AP is generally ready to get off of glog.

We would really like not to have to change all of the log macros used throughout our code, which we basically hijacked from glog...

At the same time, TBH, given that ceres was already leaking the unmodified glog macros directly to us, I'm really not completely sure how it was working before. I think that there was likely a "race condition" of header includes where, if ceres was included before our text logger was included, then ceres would use unmodified glog macros, but if ceres was included after our text logger was included, then ceres would use our modified (mostly compatible) macros. (Because, previously, our text logger worked by, first include glog, then undef most of the macros, then define substitutes. So if our text logger was included before ceres, then when ceres tries to include glog, the include guard stops it, and it gets our macros instead.) Because our macros are mostly compatible with glog, and cause a no-op when streaming is used, this likely all would have compiled and worked out fine "in practice", although it's ripe for ODR violations and all sorts of other problems :(

---

Anyways, I would really like to clean this up in the process of getting off of glog. If I can get a patch upstream into ceres that would give us a clean way to prevent the macro collisions, that would be great. So yes, I would be willing to work on this. :)

**Comment by keir** [comment]
Hi Chris,

First off thank you for the detailed comment. Fundamentally I agree with you about the transitive log includes in Ceres being a bad idea. I remember when those logs were first introduced to Ceres and I was not happy about it for the exact reasons you raise. We decided to do it anyway because while gross, the logs and check macros are helpful in common practical cases and we decided the pragmatic utility exceeded the purity argument.

With that said, I would be happy to support a logging indirection mechanism in Ceres. Ceres exists to support the users and it is a practical reality that some users will require a more sophisticated or different logging solution.

- For the public headers, the logs are not used much but the CHECK_* macros are. I agree with your assessment, and support a public ceres/logging.h and ceres/check.h or similar to implement those macros as CERES_CHECK_* and CERES_LOG_* for use in the public Ceres headers.
- For Ceres-private files, it's tricky since right now Ceres is fairly liberal in our use of the log macros and so on, and it would be an invasive change to alter that. What I suggest here is that the public ceres/logging.h file could have some #define magic that would allow selecting a different set of macros than the default glog/miniglog.
- In terms of having a ceres_logging.cc, I'm less inclined to do this. Ceres has very wide usage, and so adding indirection to the logging and then expecting link-time optimizations to do the right thing is not realistic given the wide deployment. It's just reality that many projects do not have LTO enabled, and we cannot break them. Any indirection would need to be done in the preprocessor.

With that said, if you would work on this we would welcome the change. Would you be willing to put together a more specific proposal and maybe even a sample implementation? That would be great. One thing to consider is that for this change, we will be picky since this will have wide-ranging impact to the Ceres user base, so please be patient with the review process.

**Comment by cbeck88** [comment]
Yea, i still need to look in more detail at ceres code and think about it. I think a simple macro redirection mechanism and a way to configure it with a config header would be more than adequate, and i agree that a logging.cc file is probably inappropriate. I'll try to make a patch soon with the understanding that it will take time to review.

**Comment by keir** [comment]
Have you had a chance to think about this more? We would welcome the change.

**Comment by cbeck88** [comment]
Yeah, sorry, I got bogged down with other stuff at work, but I'm likely to have time to work on this for real next week. I'm glad to hear back from you :)

**Comment by keir** [comment]
We're working on some nice perf improvements in Ceres; you'll probably want to get to this so you can upgrade to new upstream versions easy and fast in the future :)

**Comment by HackAttack** [comment]
> It's also reasonable to say, the best outcome is that glog should have prefixed their macros with `GLOG_LOG_...` or something. But that change obviously isn't going to happen.

@alexkaratarakis and I did exactly this (in Bazel), which enabled us to remove the original workaround of always including Ceres headers before our logging headers. Here’s the script in case it’s helpful to someone.

```bazel
glog_macros = [
    "LOG",
    "LOG_IF",
    # etc.
]
http_archive(
    name = "ceres",
    patch_cmds = [r"find -type f -exec sed -Ei 's/\b({})\(/GLOG_\1\(/g' {{}} \+".format("|".join(glog_macros))],
    # etc.
)
```
Better late than never!

**Comment by erichlf** [comment]
Why is this a won't fix? This is an issue with projects that create their own `LOG` macro. I am having exactly this issue and all I had done was `#include <ceres/ceres.h>`. Instead of patching the code I created a new macro that could tell the difference between our internal `LOG` and `GLOG_LOG`.
