### ISSUE TITLE
Add a penalty to loss function or cost function?

### ISSUE THREAD

**Issue by jakexie** [ceres-solver/ceres-solver#324]
I'm quite new to Ceres, so there are probably some simple questions.  
I want to add a penalty to a problem, perhaps like :
   argmin:Huber(E(x))    ==>  argmin:Huber(E(x)) + λR(f)
I have not find a API to add a penalty to this least-squares problem. Where should I add the penalty to ?
Just add a item  behind cost function, like:
     reprojection[0] = rep[0] - feature_x ==> reprojection[0] = rep[0] - feature_x + λR(f)
     reprojection[1] = rep[1] - feature_x ==> reprojection[1] = rep[1] - feature_x + λR(f)
or add a item behind loss function , like:
           rho[0] +=  λR(f)
help me ~~~~.~~~~

**Comment by sandwichmaker** [comment]
@jakexie  add another residualblock/cost function for the penalty terms.
