### ISSUE TITLE
How can I run Ceres after making changes to the template code?

### ISSUE THREAD

**Issue by salimoha** [ceres-solver/ceres-solver#326]
I am using Ceres to solve a nonlinear LS problem. To get familiar with Ceres I made some changes in robsenbrock.cc. How can I compile the modified code? Thanks!

**Comment by sandwichmaker** [comment]
@salimoha this seems like a cmake/build question rather than a ceres question.

**Comment by salimoha** [comment]
I resolved the issue. We have to do make all in ceres-bin folder. Thanks
