### ISSUE TITLE
Running ceres in parallel to solve a nonlinear least square problem

### ISSUE THREAD

**Issue by salimoha** [ceres-solver/ceres-solver#328]
How can I run ceres in parallel using multiple starting points? I read this post: https://github.com/mapillary/OpenSfM/issues/102
But I couldn't find out how to do Ceres in parallel. I appropriate if you could point out how it is possible to run Ceres in parallel? I found out that we can use openmp to do so. But do you @sandwichmaker have any test example to make Ceres optimization run in parallel?

**Comment by sandwichmaker** [comment]
you will have to construct multiple problems and solve them. There is nothing ceres specific to be done here. You can't share the same problem object between multiple parallel solves though.

Questions like these are not really issues, please consider joining the ceres-solver@googlegroups.com.
