### ISSUE TITLE
openmp doesn't work on Android + NDK compiling

### ISSUE THREAD

**Issue by yang0773** [ceres-solver/ceres-solver#329]
guys,

http://www.ceres-solver.org/installation.html tells that openmp should be turned off on Android. And we actually find the ChangeNumThreadsIfNeeded() to force num_linear_solver_threads as 1. But I encountered a performance issue when running SLAM on Android and hope to turn on openmp with multi-threading. After enabling openmp by hand, we got different results compared to single-thread mechanism. Can I know the reason openmp doesn't work? 

I also notice TBB added into Ceres Solver. Can it supported on Android platform?

Cheers,
Frank

**Comment by sandwichmaker** [comment]
@yang0773 The advice around openmp and android is likely stale. More recent versions of NDK have openmp support that works. That said threading changes the order of operations, which for a poorly conditioned problem can sometimes lead to differing results. 

The TBB support is quite new, but yes it should work on android also. We would love to hear of your progress.

**Comment by sandwichmaker** [comment]
ping? is this still open?

**Comment by sandwichmaker** [comment]
Closing based on on-mailinglist discussion and we now have c++11 threading support too.
