### ISSUE TITLE
Ceres should have a Apple Sparse Solver backend

### ISSUE THREAD

**Issue by keir** [ceres-solver/ceres-solver#330]
Apple has created their own set of high-performance sparse solvers[1] available on iOS and Mac OS X devices. While Ceres generally favors of open source solutions, there is no reason there couldn't be an optional Apple Sparse Solver backend. This might lead to higher performance overall solves due to Apple's device-specific optimizations.

[1] https://developer.apple.com/documentation/accelerate/sparse_solvers

**Comment by sandwichmaker** [comment]
I have been meaning to try it out. I think this would be a cool addition.

**Comment by ogrex** [comment]
The same idea occurs to me. however, not much info about the performance of Sparse Solver is given on Internet.

**Comment by alexsmac** [comment]
Support for Apple's Accelerate sparse solvers has now been merged into master
