### ISSUE TITLE
Building with Suitesparse

### ISSUE THREAD

**Issue by yonelay11** [ceres-solver/ceres-solver#331]
Hello, I want to know how to build ceres-solver with Suitesparse on Window 10. I had a libblas.lib and liblapack.lib  and I put libblas.lib into the BLAS_blas_LIBRARY. But, they said, **Did not find BLAS library, disabling LAPACK support.**

**Comment by sandwichmaker** [comment]
@yonelay11 could you provide more details of cmake logs?

**Comment by jasjuang** [comment]
@yonelay11 The easiest way to build ceres-solver with Suitesparse on Window 10 is use [vcpkg](https://github.com/Microsoft/vcpkg/). It will be as simple as `vcpkg install ceres`

**Comment by sandwichmaker** [comment]
ping?

**Comment by sandwichmaker** [comment]
Closing because of no response.
