### ISSUE TITLE
Android Link Error

### ISSUE THREAD

**Issue by lz199144** [ceres-solver/ceres-solver#333]
`Error:(511) undefined reference to 'ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, std::vector<double*, std::allocator<double*> > const&)'
Error:(685) undefined reference to 'ceres::Problem::GetResidualBlocks(std::vector<ceres::internal::ResidualBlock*, std::allocator<ceres::internal::ResidualBlock*> >*) const'
F:\android-ndk-r13b\sources\cxx-stl\llvm-libc++\include\istream
Error:(338) undefined reference to 'std::__ndk1::ios_base::~ios_base()'
Error:(338) undefined reference to 'std::__ndk1::ios_base::~ios_base()'
Error:(338) undefined reference to 'std::__ndk1::ios_base::~ios_base()'
Error:(338) undefined reference to 'std::__ndk1::ios_base::~ios_base()'
F:\android-ndk-r13b\sources\cxx-stl\llvm-libc++\include\__locale
Error:(188) undefined reference to 'std::__ndk1::locale::use_facet(std::__ndk1::locale::id&) const'
Error:(188) undefined referenc
Error:(188) undefined reference to 'std::__ndk1::locale::use_facet(std::__ndk1::locale::id&) const'
Error:(188) undefined reference to 'std::__ndk1::locale::use_facet(std::__ndk1::locale::id&) const'
F:\android-ndk-r13b\sources\cxx-stl\llvm-libc++\include\stdexcept
Error:(127) undefined reference to 'std::logic_error::logic_error(char const*)'
Error:(127) undefined reference to 'std::logic_error::logic_error(char const*)'
Error:(127) undefined reference to 'std::logic_error::logic_error(char const*)'
Error:(127) undefined reference to 'std::logic_error::logic_error(char const*)'
F:\android-ndk-r13b\sources\cxx-stl\llvm-libc++\include\ios
Error:(739) undefined reference to 'std::__ndk1::ios_base::getloc() const'
Error:(739) undefined reference to 'std::__ndk1::locale::~locale()'
Error:(529) undefined reference to 'std::__ndk1::ios_base::clear(unsigned int)'
Error:(739) undefined reference to 'std::__ndk1::ios_base::getloc() const'
Error:(529) undefined reference to 'std::__ndk1::ios_base::
Error:(529) undefined reference to 'std::__ndk1::ios_base::clear(unsigned int)'
Error:(529) undefined reference to 'std::__ndk1::ios_base::clear(unsigned int)'
Error:(673) undefined reference to 'std::__ndk1::ios_base::init(void*)'
Error:(768) undefined reference to 'std::__ndk1::ios_base::__call_callbacks(std::__ndk1::ios_base::event)'
Error:(769) undefined reference to 'std::__ndk1::ios_base::copyfmt(std::
Error:(772) undefined reference to 'std::__ndk1::ios_base::__call_callbacks(std::__ndk1::ios_base::event)'
Error:(673) undefined reference to 'std::__ndk1::ios_base::init(void*)'
Error:(673) undefined reference to 'std::__ndk1::ios_base::init(void*)'
Error:(673) undefined reference to 'std::__ndk1::ios_base::init(void*)'
F:\android-ndk-r13b\sources\cxx-stl\llvm-libc++\include\streambuf
Error:(220) undefined reference to 'std::__ndk1::locale::~locale()'
Error:(220) undefined reference to 'std::__ndk1::locale::~locale()'
Error:(163) undefined reference to 'std::__ndk1::locale::locale()'
Error:(163) undefined reference to 'std::__ndk1::locale::locale()'
Error:(163) undefined reference to 'std::__ndk1::locale::locale()'
Error:(163) undefined reference to 'std::__ndk1::locale::local
Error:error: undefined reference to 'std::__ndk1::__shared_weak_count::__add_shared()'
F:\android-ndk-r13b\sources\cxx-stl\llvm-libc++\include\ostream
Error:(491) undefined reference to 'std::__ndk1::ios_base::getloc() const'
Error:(491) undefined reference to 'std::__ndk1::locale::~locale()'
Error:(506) undefined reference to 'std::__ndk1::num_put<char, std::__ndk1::ostreambuf_iterator<char, std::__ndk1::char_traits<char> > >::id'
Error:(506) undefined reference to 'std::__ndk1::ctype<char>::id'
Error:(773) undefined reference to 'std::__ndk1::ctype<char>::id'
Error:(728) undefined reference to 'std::__ndk1::ios_base::getloc() const'
Error:(740) undefined reference to 'std::__ndk1::num_put<char, std::__ndk1::ostreambuf_iterator<char, std::__ndk1::char_traits<char> > >::id'
Error:(740) undefined reference to 'std::__ndk1::ctype<char>::id'
Error:(688) undefined reference to 'std::__ndk1::num_put<char, std::__ndk1::ostreambuf_iterator<char, std::__ndk1::char_traits<char> > >::id'
Error:(688) undefined reference to 'std::__ndk1::ctype<char>::id'
Error:(532) undefined reference to 'std::__ndk1::num_put<char, std::__ndk1::ostreambuf_iterator<char, std::__ndk1::char_traits<char> > >::id'
F:\android-ndk-r13b\sources\cxx-stl\llvm-libc++\include\__hash_table
Error:(2117) undefined reference to 'std::__ndk1::__next_prime(unsigned int)'
Error:(2127) undefined reference to 'std::__ndk1::__next_prime(unsigned int)'
Error:(2117) undefined reference to 'std::__ndk1::__next_prime(unsigned int)'
Error:(2127) undefined reference to 'std::__ndk1::__next_prime(unsigned int)'
Error:error: undefined reference to 'std::__ndk1::__shared_weak_count::~__shared_weak_count()'
F:\android-ndk-r13b\sources\cxx-stl\llvm-libc++\include\memory
Error:(4287) undefined reference to 'std::__ndk1::__shared_weak_count::__add_shared()'
Error:(4600) undefined reference to 'std::__ndk1::__shared_weak_count::__release_shared()'
Error:(4600) undefined reference to 'std::__ndk1::__shared_weak_count::__release_shared()'
Error:(4600) undefined reference to 'std::__ndk1::__shared_weak_count::__release_shared()'
Error:(4600) undefined reference to 'std::__ndk1::__shared_weak_count::__release_shared()'
Error:(4287) undefined reference to 'std::__ndk1::__shared_weak_count::__add_shared()'
Error:(4287) undefined reference to 'std::__ndk1::__shared_weak_count::__add_shared()'
Error:(3741) undefined reference to 'std::__ndk1::__shared_weak_count::~__shared_weak_count()'
Error:(3741) undefined reference to 'std::__ndk1::__shared_weak_count::~__shared_weak_count()'
Error:(3741) undefined reference to 'std::__ndk1::__shared_weak_count::~__shared_weak_count()'
E:\mr\code\kernel\Dependencies\ceres-solver\internal\ceres\callbacks.cc
Error:(108) undefined reference to 'std::__ndk1::cout'
F:\android-ndk-r13b\sources\cxx-stl\llvm-libc++\include\algorithm
Error:(3100) undefined reference to 'std::__ndk1::__rs_get()'
Error:(3107) undefined reference to 'std::__ndk1::__rs_default::~__rs_default()'
Error:(2935) undefined reference to 'std::__ndk1::__rs_default::operator()()'
Error:(2935) undefined reference to 'std::__ndk1::__rs_default::operator()()'
Error:(3100) undefined reference to 'std::__ndk1::__rs_get()'
Error:(3107) undefined reference to 'std::__ndk1::__rs_default::~__rs_default()'
Error:(3100) undefined reference to 'std::__ndk1::__rs_get()'
Error:(3107) undefined reference to 'std::__ndk1::__rs_default::~__rs_default()'
Error:(3100) undefined reference to 'std::__ndk1:
Error:(3107) undefined reference to 'std::__ndk1::__rs_default::~__rs_default()'
F:\AndroidStudio\bin
Error:error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by keir** [comment]
This does not give us sufficient information. Please explain:
- Your development OS & version
- The NDK version
- Your command to compile

**Comment by lz199144** [comment]
Sorry, I use ndk r13b and the origin Android.mk to make the libceres.a file, when I use it in my Android Studio project, it shows link errors.

Part of my Android project configs:
```
include $(CLEAR_VARS)
LOCAL_MODULE    := ceres
LOCAL_SRC_FILES := ${DEPENDENCIES_DIR}/ceres-solver/ceres-bin/Android/libceres.a
include $(PREBUILT_STATIC_LIBRARY)
```

```
LOCAL_STATIC_LIBRARIES += ceres

LOCAL_CFLAGS := -DAndroid -mfpu=neon -std=c++11 -Os
LOCAL_LDLIBS += -llog -ljnigraphics -landroid -lGLESv2
LOCAL_ARM_NEON := true
```

**Comment by keir** [comment]
I'm sorry, I am not sure what is going on. You'll likely have to debug this yourself. It looks like somehow parts of Ceres are not getting linked in, which is very weird:

```
error:(511) undefined reference to 'ceres::Problem::AddResidualBlock(ceres::CostFunction*, ceres::LossFunction*, std::vector<double*, std::allocator<double*> > const&)' Error:(685) undefined reference to 'ceres::Problem::GetResidualBlocks(std::vector<ceres::internal::ResidualBlock*, std::allocator<ceres::internal::ResidualBlock*> >*)
```

The `std::logic_error` type is used to throw exceptions. Ceres does not use exceptions. However, perhaps you are using some other code that relies on C++ exceptions but you are not linking a version of libc++ or libstdc++ that supports exceptions?

**Comment by keir** [comment]
Also, are you able to compile libceres.a independently (without your surrounding project)? As in, directly from the Ceres upstream source?

**Comment by lz199144** [comment]
I fixed this error by changint APP_STL to c++_static in Application.mk of my project.
