### ISSUE TITLE
CMake errors when enabling TBB

### ISSUE THREAD

**Issue by anuppari** [ceres-solver/ceres-solver#334]
The main `CMakeLists.txt` and `cmake/FindTBB.cmake` have a few errors. Here's a diff of the changes I made to get it working (I can't use gerrit to make a pull request).

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index f12d5ed..8d90d33 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -425,9 +425,13 @@ if (TBB)
     message("-- Building with TBB (version: ${TBB_VERSION}).")
     list(APPEND CERES_COMPILE_OPTIONS CERES_USE_TBB)
     include_directories(${TBB_INCLUDE_DIRS})
+       message("-- Enabling CXX11 (C++11) option required by TBB=ON.")
     if (NOT CXX11)
-      message("-- Enabling CXX11 (C++11) option required by TBB=ON.")
-      update_cache_variable(CXX11 ON)
+      if (NOT DEFINED CXX11)
+        set(CXX11 ON CACHE BOOL "Enable use of C++11 headers if available (requires client code use C++11).")
+      else ()
+          update_cache_variable(CXX11 ON)
+      endif()
     endif()
   else (TBB_FOUND)
     message("-- Failed to find TBB, disabling.")
diff --git a/cmake/FindTBB.cmake b/cmake/FindTBB.cmake
index 8d57c80..d3e2852 100644
--- a/cmake/FindTBB.cmake
+++ b/cmake/FindTBB.cmake
@@ -89,7 +89,7 @@ if(NOT TBB_FOUND)
   ##################################

   if(NOT DEFINED TBB_USE_DEBUG_BUILD)
-    if(CMAKE_BUILD_TYPE MATCHES "[Debug|DEBUG|debug|RelWithDebInfo|RELWITHDEBINFO|relwithdebinfo]")
+    if(CMAKE_BUILD_TYPE MATCHES "(Debug|DEBUG|debug|RelWithDebInfo|RELWITHDEBINFO|relwithdebinfo)")
       set(TBB_USE_DEBUG_BUILD TRUE)
     else()
       set(TBB_USE_DEBUG_BUILD FALSE)
@@ -175,12 +175,12 @@ if(NOT TBB_FOUND)
     find_library(TBB_${_comp}_LIBRARY_RELEASE ${_comp}
         HINTS ${TBB_LIBRARY} ${TBB_SEARCH_DIR}
         PATHS ${TBB_DEFAULT_SEARCH_DIR}
-        PATH_SUFFIXES "${TBB_LIB_PATH_SUFFIX}")
+        PATH_SUFFIXES ${TBB_LIB_PATH_SUFFIX})

     find_library(TBB_${_comp}_LIBRARY_DEBUG ${_comp}_debug
         HINTS ${TBB_LIBRARY} ${TBB_SEARCH_DIR}
         PATHS ${TBB_DEFAULT_SEARCH_DIR} ENV LIBRARY_PATH
-        PATH_SUFFIXES "${TBB_LIB_PATH_SUFFIX}")
+        PATH_SUFFIXES ${TBB_LIB_PATH_SUFFIX})

```

**Comment by keir** [comment]
Hi Anup,

Thanks for the patch. We try to make the Gerrit process as painless as possible; is there a part of it that is making it hard to contribute? If there is a problem with our docs, we'd like to fix it.

Thanks,
Keir

**Comment by alexsmac** [comment]
Can you expand on what the error you encountered was?  I can't replicate any issues with TBB on master and this:

```
if (NOT DEFINED CXX11)
```

should definitely not be necessary.  CXX11 is declared as a CMake option, as such `if (CXX11)` is fine.

**Comment by anuppari** [comment]
I had a few issues on a Win10x64 with Visual Studio 2015.

1. I have the `TBBROOT` environment variable set, so the `TBB_SEARCH_DIR` has the correct parent directory of my TBB, however, the `find_library` calls would not find the library without the right `PATH_SUFFIXES` argument. From my testing, if that argument is supplied with a cmake variable, it should be without quotes, else it doesn't work.

2. Regex apparently requires parenthesis for matching whole words. With square brackets, I think it matches any letter, so even if `CMAKE_BUILD_TYPE` was Release, the match would return true and `TBB_USE_DEBUG_BUILD` would be set true.

3. The CX11 option is only defined for non-MSVC. On MSVC, `update_cache_variable(CXX11 ON)` crashes. Specifically, the `get_property` call crashes if CX11 is not defined.

**Comment by sandwichmaker** [comment]
ping?

**Comment by anuppari** [comment]
Yep this works.

By the way, for anyone interested (and maybe worth putting in the installation instructions), if you're using the intel MKL and TBB libraries for BLAS/LAPACK, the FindBLAS and FindLAPACK provided with cmake and used by ceres rely on the "LIB" environment variable, which should be set to the library directories of both, e.g.,
```
C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2017.4.210\windows\mkl\lib\intel64;C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2017.4.210\windows\compiler\lib\intel64
```
Also, before configuring ceres with cmake, one should create the cmake variable `BLA_VENDOR` and set it to `Intel10_64lp` for the recent versions of MKL/TBB.

These steps should also be taken when building SuiteSparse with MKL/TBB BLAS/LAPACK routines.

**Comment by alexsmac** [comment]
Thanks - the fix has now been merged into master.
