### ISSUE TITLE
Make Ceres Bazel build configureable

### ISSUE THREAD

**Issue by keir** [ceres-solver/ceres-solver#335]
Currently the Ceres Bazel build only supports a basic config without SuiteSparse or other handy utilities. The fix is to make a Skylark macro that allows depending on different configurations of Ceres.

**Comment by chenkan1994** [comment]
@keir is there any work that has been done?

**Comment by an-kumar** [comment]
@keir bump on this issue -- any updates? Otherwise i'll start working on my own version, but would prefer not to double up the work.

**Comment by keir** [comment]
an-kumar, we'd love contributions here.

**Comment by liujack1019** [comment]
@keir any updates now?

**Comment by sandwichmaker** [comment]
Currently no plan to do this, if and when someone wants to do this, we will re-open this.
