### ISSUE TITLE
Remove glog/logging.h from header

### ISSUE THREAD

**Issue by brunobg** [ceres-solver/ceres-solver#338]
glog is included in several headers that are eventually used by applications, such as:

https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/internal/autodiff.h
https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/internal/fixed_array.h
https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/internal/variadic_evaluation.h

I had problems compiling a software due to this (long story short: I used https://github.com/tbennun/ceres-windows/, it has glog, it conflicted with another glog in the system when compiling the final program). It seems that me that removing the #include line should not affect anything (if necessary, add to the .cc) and would not require glog headers when using ceres as an external dependency.

**Comment by keir** [comment]
It's not true; the CHECK and DCHECK macros rely on glog. There is a separate thread discussing this issue:
https://github.com/ceres-solver/ceres-solver/issues/323

**Comment by brunobg** [comment]
Sorry, closing the issue.
