### ISSUE TITLE
Segmentation Fault at ceres::Solver::Solve. Ubuntu 16.04

### ISSUE THREAD

**Issue by rachillesf** [ceres-solver/ceres-solver#339]
Hi, i'm dealing with a strange segmentation fault when trying to optimize a problem, calling ceres::Solver::Solve.

I'm running at ubuntu 16.04, when running at ubuntu 14.04 with the same code the problem does not happen. 
When running a different application with the same residuals (but compiled with ROS) the problem also does not happen. 

here is the error and gdb backtrace 
`Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd7a8a700 (LWP 25401)]
assignPacket<32, 32, __vector(4) double> (index=0, this=<synthetic pointer>)
    at /usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:598
598	    m_functor.template assignPacket<StoreMode>(&m_dst.coeffRef(index), m_src.template packet<LoadMode,PacketType>(index));
(gdb) backtrace
#0  assignPacket<32, 32, __vector(4) double> (index=0, this=<synthetic pointer>)
    at /usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:598
#1  run (kernel=<synthetic pointer>) at /usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:386
#2  call_dense_assignment_loop<Eigen::Matrix<double, -1, 1>, Eigen::Matrix<double, -1, 1>, Eigen::internal::assign_op<double> > (func=..., src=..., dst=...)
    at /usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:653
#3  run (func=..., src=..., dst=...) at /usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:790
#4  Eigen::internal::call_assignment_no_alias<Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, Eigen::internal::assign_op<double> > (dst=..., src=..., func=...)
    at /usr/include/eigen3/Eigen/src/Core/AssignEvaluator.h:747
#5  0x00000000005a9850 in ceres::internal::TrustRegionMinimizer::HandleSuccessfulStep() ()
#6  0x00000000005ab4f6 in ceres::internal::TrustRegionMinimizer::Minimize(ceres::internal::Minimizer::Options const&, double*, ceres::Solver::Summary*) ()
#7  0x000000000057c483 in ceres::Solver::Solve(ceres::Solver::Options const&, ceres::Problem*, ceres::Solver::Summary*) ()
#8  0x000000000057d3f9 in ceres::Solve(ceres::Solver::Options const&, ceres::Problem*, ceres::Solver::Summary*) ()
`

**Comment by sandwichmaker** [comment]
@rachillesf this looks like something funny is going on with Eigen. The code in question is not doing anything funny or interesting, it is a straight assignment.. hard to say more from this trace.

**Comment by keir** [comment]
Are you able to run in Valgrind or ASAN? It could be that the code is
broken even in the working case, but it's only triggering a segfault in one.

**Comment by sandwichmaker** [comment]
gentle ping?

**Comment by sandwichmaker** [comment]
Closing because of no response, please re-open if you have new information.
