### ISSUE TITLE
How to reset a problem?

### ISSUE THREAD

**Issue by mojovski** [ceres-solver/ceres-solver#342]
I would like to clean a problem before filling it with new residuum blocks etc.
Right now, I delete the pointer to ceres::Problem* but after I create a new one,
```
problem->SetParameterization(...
```
exists with SIGSEGV.
Can someone suggest me a way how to reset a problem?

Thank you very much in advance!

**Comment by alexsmac** [comment]
There is no mechanism to reset a problem.  Creating a new problem is the correct way to 'reset' as it stands.  I think the problem you are encountering is because by default the Problem assumes ownership of all LocalParameterisations (and CostFunctions) given to it.  You can change that behaviour by setting Problem::Options::local_parameterization_ownership as described [here](http://ceres-solver.org/nnls_modeling.html#_CPPv2N5ceres7ProblemE).  However, note that this behaviour applies to *all* objects (i.e. the Problem will either take ownership of *all* LocalParameterizations (the default) or none).

**Comment by mojovski** [comment]
thank you very much!
I came further and the SIGSEGV is not thrown on adding a new parameterization.
However, when I try to solve the problem at the second time (after the Problem* has been deleted and created again)
```
ceres::Solve(options, problem, &summary);
```
again a SIGSEGV is thrown.
Is there something I might miss?

This is the code how I re-create my ceres::Problem:
```
void PoseSolver::setupNewProblem()
{
    if (problem!=NULL)
    {
        delete problem;
        delete quaternion_local_parameterization;
    }
    ceres::Problem::Options ceres_problem_options;
    ceres_problem_options.local_parameterization_ownership=ceres::Ownership::DO_NOT_TAKE_OWNERSHIP;
    problem=new ceres::Problem(ceres_problem_options); // reset
    quaternion_local_parameterization = new ceres::EigenQuaternionParameterization;

}
```

**Comment by alexsmac** [comment]
I don't see any obvious problems in the snippet you posted.  I would imagine that you might have a similar problem to the previous problem with your LocalParameterisation with your residuals.  Are you retaining them via a pointer after adding them to the Problem?

You could try recompiling Ceres (and your project) in Debug and running it in GDB/LLDB.  If you are using Clang, then you can also add the `-fsanitize=address` compiler flag to enable the [AddressSanitizer](https://clang.llvm.org/docs/AddressSanitizer.html) that will usually catch invalid access patterns.

**Comment by mojovski** [comment]
retaining residuals might be the reason. Is there another way than using
```
RemoveResidualBlock(...)
```
? I read about it somewhere in old google-community posts but there were no example about what it means to retain them. 
Thanks again!

**Comment by alexsmac** [comment]
Just like the LocalParameterizations, it's controllable via `Problem::Options::cost_function_ownership`.  By default Problem will take ownership and delete the cost functions given to it on destruction.

**Comment by mojovski** [comment]
Thanks! This did the trick.
```cpp
void PoseSolver::setupNewProblem()
{
    if (problem!=NULL)
    {
        delete problem;
        //Memory leak?? deleting fails..
        delete quaternion_local_parameterization;
    }
    ceres::Problem::Options ceres_problem_options;
    ceres_problem_options.local_parameterization_ownership=ceres::Ownership::DO_NOT_TAKE_OWNERSHIP;
    ceres_problem_options.loss_function_ownership=ceres::Ownership::DO_NOT_TAKE_OWNERSHIP;
    ceres_problem_options.cost_function_ownership=ceres::Ownership::DO_NOT_TAKE_OWNERSHIP;
    problem=new ceres::Problem(ceres_problem_options); // reset
    quaternion_local_parameterization = new ceres::EigenQuaternionParameterization;

}
```
