### ISSUE TITLE
covariance_test fails on arm64 (rpi3)

### ISSUE THREAD

**Issue by Minipada** [ceres-solver/ceres-solver#344]
I am working with a raspberrypi3 in 64 bits and tried to run the tests apps, covariance_test fails and is `Killed`

My setup:
* rpi3 aarch64
* ceres-solver commit: [e5dceb3ab0c32e3682c0effb2d856c78f52bf8a9](https://ceres-solver.googlesource.com/ceres-solver/+/e5dceb3ab0c32e3682c0effb2d856c78f52bf8a9)
* compilation options: default
* Ceres build log:

      -- A library with BLAS API found.
      -- Found LAPACK library: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/lib/liblapack.so;/home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/lib/libblas.so
      -- A library with BLAS API found.
      -- Found AMD headers in: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/include/suitesparse
      -- Found AMD library: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/lib/libamd.so
      -- Found CAMD headers in: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/include/suitesparse
      -- Found CAMD library: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/lib/libcamd.so
      -- Found COLAMD headers in: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/include/suitesparse
      -- Found COLAMD library: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/lib/libcolamd.so
      -- Found CCOLAMD headers in: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/include/suitesparse
      -- Found CCOLAMD library: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/lib/libccolamd.so
      -- Found CHOLMOD headers in: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/include/suitesparse
      -- Found CHOLMOD library: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/lib/libcholmod.so
      -- Found SUITESPARSEQR headers in: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/include/suitesparse
      -- Found SUITESPARSEQR library: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/lib/libspqr.so
      -- Found Intel Thread Building Blocks (TBB) library (2017.0) assuming SuiteSparseQR was compiled with TBB.
      -- Found SUITESPARSE_CONFIG headers in: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/include
      -- Found SUITESPARSE_CONFIG library: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/lib/libsuitesparseconfig.so
      -- Found LIBRT library: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/lib/librt.so
      -- Adding librt: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/lib/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
      -- Did not find METIS library (optional SuiteSparse dependency)
      -- Found SuiteSparse: TRUE (found version "4.5.5") 
      -- Found SuiteSparse 4.5.5, building with SuiteSparse.
      -- Found CXSparse: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/include/suitesparse/cxsparse (found version "3.1.9") 
      -- Found CXSparse version: 3.1.9, building with CXSparse.
      -- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
      -- Found installed version of gflags: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/lib/cmake/gflags
      -- Detected gflags version: 2.2.0
      -- Found Gflags: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/include  
      -- Found Google Flags header in: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/include, in namespace: google
      -- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
      -- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
      -- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
      -- Found Glog: /home/yocto/yocto_topdir/tmp/sysroots/raspberrypi3-64/usr/include  
      -- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
      -- Building with OpenMP.
      -- Performing Test COMPILER_HAS_CXX11_FLAG
      -- Performing Test COMPILER_HAS_CXX11_FLAG - Success
      -- Looking for C++ include unordered_map
      -- Looking for C++ include unordered_map - not found
      -- Looking for C++ include tr1/unordered_map
      -- Looking for C++ include tr1/unordered_map - found
      -- Found tr1/unordered_map/set in std::tr1 namespace.
      -- Looking for C++ include memory
      -- Looking for C++ include memory - found
      -- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
      -- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Failed
      -- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE
      -- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE - Failed
      -- Looking for C++ include tr1/memory
      -- Looking for C++ include tr1/memory - found
      -- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER
      -- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER - Success
      -- Found shared_ptr in std::tr1 namespace using <tr1/memory> header.
      -- Building Ceres as a static library.
      -- No build type specified; defaulting to CMAKE_BUILD_TYPE=Release.
      -- Creating configured Ceres config.h output directory: /home/yocto/yocto_topdir/tmp/work/aarch64-poky-linux/ceres-solver/15012018-r0/build/config/ceres/internal
      -- Enabling CERES_USE_EIGEN_SPARSE in Ceres config.h
      -- Enabling CERES_USE_OPENMP in Ceres config.h
      -- Enabling CERES_HAVE_PTHREAD in Ceres config.h
      -- Enabling CERES_HAVE_RWLOCK in Ceres config.h
      -- Enabling CERES_TR1_UNORDERED_MAP in Ceres config.h
      -- Enabling CERES_TR1_MEMORY_HEADER in Ceres config.h
      -- Enabling CERES_TR1_SHARED_PTR in Ceres config.h
      -- Build the examples.
      -- Configuring done
      -- Generating done

Here is the log:

    root@raspberrypi3-64:~# /opt/test_apps/ceres-solver/covariance_test 
    Running main() from gmock_main.cc
    [==========] Running 16 tests from 4 test cases.
    [----------] Global test environment set-up.
    [----------] 3 tests from CovarianceImpl
    [ RUN      ] CovarianceImpl.ComputeCovarianceSparsity
    [       OK ] CovarianceImpl.ComputeCovarianceSparsity (11 ms)
    [ RUN      ] CovarianceImpl.ComputeCovarianceSparsityWithConstantParameterBlock
    [       OK ] CovarianceImpl.ComputeCovarianceSparsityWithConstantParameterBlock (0 ms)
    [ RUN      ] CovarianceImpl.ComputeCovarianceSparsityWithFreeParameterBlock
    [       OK ] CovarianceImpl.ComputeCovarianceSparsityWithFreeParameterBlock (1 ms)
    [----------] 3 tests from CovarianceImpl (12 ms total)

    [----------] 11 tests from CovarianceTest
    [ RUN      ] CovarianceTest.NormalBehavior
    [       OK ] CovarianceTest.NormalBehavior (92 ms)
    [ RUN      ] CovarianceTest.ThreadedNormalBehavior
    [       OK ] CovarianceTest.ThreadedNormalBehavior (61 ms)
    [ RUN      ] CovarianceTest.ConstantParameterBlock
    [       OK ] CovarianceTest.ConstantParameterBlock (38 ms)
    [ RUN      ] CovarianceTest.LocalParameterization
    [       OK ] CovarianceTest.LocalParameterization (50 ms)
    [ RUN      ] CovarianceTest.LocalParameterizationInTangentSpace
    [       OK ] CovarianceTest.LocalParameterizationInTangentSpace (46 ms)
    [ RUN      ] CovarianceTest.LocalParameterizationInTangentSpaceWithConstantBlocks
    [       OK ] CovarianceTest.LocalParameterizationInTangentSpaceWithConstantBlocks (21 ms)
    [ RUN      ] CovarianceTest.TruncatedRank
    [       OK ] CovarianceTest.TruncatedRank (32 ms)
    [ RUN      ] CovarianceTest.DenseCovarianceMatrixFromSetOfParameters
    [       OK ] CovarianceTest.DenseCovarianceMatrixFromSetOfParameters (53 ms)
    [ RUN      ] CovarianceTest.DenseCovarianceMatrixFromSetOfParametersThreaded
    [       OK ] CovarianceTest.DenseCovarianceMatrixFromSetOfParametersThreaded (54 ms)
    [ RUN      ] CovarianceTest.DenseCovarianceMatrixFromSetOfParametersInTangentSpace
    [       OK ] CovarianceTest.DenseCovarianceMatrixFromSetOfParametersInTangentSpace (46 ms)
    [ RUN      ] CovarianceTest.ComputeCovarianceFailure

    [WARNING] /usr/src/debug/ceres-solver/15012018-r0/git/ceres-solver/internal/ceres/gmock_gtest_all.cc:7666:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test detected 4 threads.

    [WARNING] /usr/src/debug/ceres-solver/15012018-r0/git/ceres-solver/internal/ceres/gmock_gtest_all.cc:7666:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test detected 4 threads.
    [       OK ] CovarianceTest.ComputeCovarianceFailure (66 ms)
    [----------] 11 tests from CovarianceTest (561 ms total)

    [----------] 1 test from RankDeficientCovarianceTest
    [ RUN      ] RankDeficientCovarianceTest.AutomaticTruncation
    [       OK ] RankDeficientCovarianceTest.AutomaticTruncation (13 ms)
    [----------] 1 test from RankDeficientCovarianceTest (13 ms total)

    [----------] 1 test from LargeScaleCovarianceTest
    [ RUN      ] LargeScaleCovarianceTest.Parallel
    Killed

Is there any flag that I should use at compile time?

**Comment by Minipada** [comment]
Seems a duplicate. I didn't see #312 . Will try the flag

**Comment by Minipada** [comment]
In case anyone comes by here, the solution offered in the mentioned PR works.

**Comment by williammc** [comment]
@Minipada  
I've been exploring solution or recipe for SuiteSparse on yocto. 
Is your solution from a public yocto recipe ? 
If not, can you share hints about building SuiteSparse on yocto ?

**Comment by Minipada** [comment]
@williammc it is unfortunately not. I didn't find the time to push it to upstream. As it is buildable with makefiles, the recipe was straightforward.

**Comment by williammc** [comment]
@Minipada thanks for quick response! Mostly, i'm stuck with gfortran compiler on yocto. 
But this patch seems to be right for gcc-7.2.0 : https://patchwork.openembedded.org/patch/146603
