### ISSUE TITLE
Warning C4267 in dynamic_autodiff_cost_function.h

### ISSUE THREAD

**Issue by cnovel** [ceres-solver/ceres-solver#346]
In include/dynamic_autodiff_cost_function.h, at line 108:
``    const int num_parameter_blocks = parameter_block_sizes().size();``
creates a  `warning C4267: 'initializing': conversion from 'size_t' to 'const int'`.

This patch fix the warning:
``    const int num_parameter_blocks = static_cast<int>(parameter_block_sizes().size());``

**Comment by keir** [comment]
I believe we have a flag on to disable this warning (it fires in many more places also). What compiler are you using?

**Comment by cnovel** [comment]
I'm using Visual Studio 2017 (15.5.6). Which flag would be able to disable these warnings?

**Comment by keir** [comment]
This commit probably shouldn't have gone in. Ceres takes the stance (as does most Google code) that the following is valid:

int x = y; // y is size_t

Perhaps we should try and make the Ceres public headers compile with this warning on (e.g. keep the fix as is)?

**Comment by cnovel** [comment]
So I read the Google guidelines for C++, and while I understand the idea beneath them, compilers will still output warnings (I'm pretty sure gcc will raise the same warning). I don't have a strong opinion on the solution (ie between static_cast and compilation flags, even if I think static_cast is a better solution), it's just that for code quality, this warnings should be taken into account and dealt with.
