### ISSUE TITLE
What are the right semantics for LocalParameterization with local_size = 0.

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#347]
Currently these are disallowed, but they lead to weird semantics if you are using subset parameterization and set the entire parameter block constant via subset parameterization, it leads to a crash.

On the other hand, a localparameterization which is not subset parameterization and has a tangent space size of zero is most likely an error, and we have been biased towards detecting that.

Would it make more sense to detect tangent space of size zero and treat that parameter block as constant?

**Comment by emilk** [comment]
The most confusing thing to me as a user is that `SubsetParameterization` is used to freeze parameters, but you can't use it to freeze _all_ parameters:

```
double params[3];
Problem problem;
problem.AddResidualBlock(some_cost_function, nullptr, params);

// Freeze nothing – works:
problem.SetParameterization(params, new SubsetParameterization(3, {}));

// Freeze one parameter – works:
problem.SetParameterization(params, new SubsetParameterization(3, {0}));

// Freeze two parameters – works:
problem.SetParameterization(params, new SubsetParameterization(3, {0, 1}));

// Freeze all parameters – crashes with unhelpful error message:
problem.SetParameterization(params, new SubsetParameterization(3, {0, 1, 2}));
```

The most consistent rule would be that all these worked, i.e. to allow freezing all parameters with `SubsetParameterization`. This is the solution I would vote for.

If we do not go this path, then the last example should at least give a helpful error message suggesting the use of `SetParameterBlockConstant`. In this case I have two patches for improving the error message:
https://ceres-solver-review.googlesource.com/c/ceres-solver/+/11320
https://ceres-solver-review.googlesource.com/c/ceres-solver/+/11360

**Comment by sandwichmaker** [comment]
@emilk I agree with you about this being inconsistent and I am happy to tell you that I have finally started working on this.

**Comment by patrikhuber** [comment]
I started needing & using `SubsetParameterization` too. I also think it would be useful if all the cases worked as expected: freeze nothing (empty vector), freeze some, and freeze all parameters.

**Comment by sandwichmaker** [comment]
Patrick I have this mostly working (it turned out to be a subtle change), I only have to do some testing to enable this.

**Comment by patrikhuber** [comment]
No worries, it's working great as it is! It would just be a convenience improvement (code simplification on the caller's end). :) Great to hear and thanks for the update!

**Comment by sandwichmaker** [comment]
I consider a wart in the API (in fact I have written code at google to get around it myself, so share your  and @emilk 's pain), but it has weirdo consequences underneath, as to how we handle constant parameter blocks so it had to be done delicately. I have a CL sitting in my one of my git clients, lemme see if I can push it out.

**Comment by sandwichmaker** [comment]
https://ceres-solver-review.googlesource.com/c/ceres-solver/+/16420 is out for review.
