### ISSUE TITLE
Sanitize & document all Ceres preprocessor defines needed by custom builds

### ISSUE THREAD

**Issue by keir** [ceres-solver/ceres-solver#348]
Currently, Ceres has a somewhat inconsistent pattern of preprocessor defines, like CERES_USE_EIGEN_SPARSE vs CERES_NO_SUITE_SPARSE. They are opposite-sensed for historical reasons that could be fixed now.

Additionally, those defines should get documented, maybe in a new page of the docs. Then guidance can be provided on when to enable or disable the flags for people who have integrated Ceres into their build system.

**Comment by alexsmac** [comment]
These are already documented [in the config.h.in](https://github.com/ceres-solver/ceres-solver/blob/master/cmake/config.h.in) file, what are the docs there missing that's relevant?

**Comment by sandwichmaker** [comment]
this refers to things like the EIGEN_SPARSE macro versus the SUITESPARSE
macro which have opposing semantics.

Also we should document this on the web. config.h.in is not the place most
people will go looking.

**Comment by sandwichmaker** [comment]
@keir can you take a pass at this and articulate what needs done to resolve this issue for 2.0?

**Comment by sandwichmaker** [comment]
@keir is this something we should block on for 2.0?

**Comment by sandwichmaker** [comment]
Likely not something we are going to do anything about.
