### ISSUE TITLE
Compiling error in test parallel_utils_test.cc introduced with latest commit

### ISSUE THREAD

**Issue by oliviersoares** [ceres-solver/ceres-solver#351]
Last commit:
https://github.com/ceres-solver/ceres-solver/commit/21f519d009b2123ad328e5f5e0f6523939519d6a

introduced a compiling error (using gcc 5.4.0, Ubuntu 16.04 environment).

[ 56%] Building CXX object internal/ceres/CMakeFiles/parallel_utils_test.dir/parallel_utils_test.cc.o
internal/ceres/parallel_utils_test.cc: In member function ‘virtual void ceres::internal::LinearIndexToUpperTriangularIndexTest_UniqueAndValid_Test::TestBody()’:
internal/ceres/parallel_utils_test.cc:45:32: error: ‘>>’ should be ‘> >’ within a nested template argument list
     std::set<std::pair<int, int>> seen_pairs;
                                ^
internal/ceres/CMakeFiles/parallel_utils_test.dir/build.make:62: recipe for target 'internal/ceres/CMakeFiles/parallel_utils_test.dir/parallel_utils_test.cc.o' failed

**Comment by pmoulon** [comment]
This `>>` should compile fine if c++11 is active, else it will give trouble.

**Comment by oliviersoares** [comment]
It's fine if you enforce the flag "-std=c++11", make c++11 a requirement for Ceres and have cmake fail if no c++11 compiler is found.

As far as I can tell, everywhere else in Ceres code base, "> >" (with a space) is used for templates so I  assumed that the use of ">>" was an error.

**Comment by sandwichmaker** [comment]
Thanks for reporting. Fixed at head now.
