### ISSUE TITLE
const correctness for LossFunction*

### ISSUE THREAD

**Issue by strasdat** [ceres-solver/ceres-solver#352]
AddResidualBlock takes in a **pointer of non-const LossFunction**

```
ResidualBlockId Problem::AddResidualBlock(
    CostFunction* cost_function,
    LossFunction* loss_function,
    const vector<double*>& parameter_blocks) {
```
 
However, it seems like internally it is delegated to ResidualBlock with takes in **a pointer of const LossFuntion**.

```
ResidualBlock(const CostFunction* cost_function,
              const LossFunction* loss_function,
              const std::vector<ParameterBlock*>& parameter_blocks,
              int index);
```

Can we consider this as a "const-correctness" bug? 

In other word, is it always safe to do:

```
problem->AddResidualBlock(cost, const_cast<LossFunction*>(loss), ...);
```

?

**Comment by sandwichmaker** [comment]
The reason AddResidualBlock does not take const pointers is because in the common case Ceres takes ownership of these pointers and will destroy them when the Problem object is destroyed.

**Comment by strasdat** [comment]
@sandwichmaker there might be some misunderstanding. I was not talking about **a const pointer of Foo** (``Foo * const``) but a **pointer of const Foo** (``const Foo *``). 

Clearly, the latte *can* be deleted:
https://stackoverflow.com/questions/755196/deleting-a-pointer-to-const-t-const

**Comment by keir** [comment]
Hi Hauke,

You may be correct here. Thanks for pointing it out. I'll think about this
a bit more and reply later.

Cheers,
Keir

**Comment by keir** [comment]
Hi Hauke,

After some debate, we agree with you that technically, AddResidualBlock() could take const Foo* arguments and still delete Foo. However, we feel it is not in the spirit of const Foo* arguments that the receiver will delete Foo. In other words, adopting your suggestion will lead to violating the principle of least surprise for many C++ programmers.

For that reason, I'm closing this bug. However, thank you for raising the issue.

Happy optimizing,
Keir
