### ISSUE TITLE
Unable to work on Ubuntu 14.04?

### ISSUE THREAD

**Issue by soulslicer** [ceres-solver/ceres-solver#353]
Hi all,

I am attempting to run my project with Ceres on Ubuntu 14.04. I have compiled it with SuiteSparse. Yet, when I run my program, it crashes with:

Termination:                          FAILURE (Can't use SPARSE_NORMAL_CHOLESKY with SUITESPARSE because SuiteSparse was not enabled when Ceres was built.)

This error does not happen on Ubuntu 16.04. Why is this the case?

**Comment by sandwichmaker** [comment]
@alexsmac can you take a look please?

**Comment by alexsmac** [comment]
@soulslicer please can you share the output of the CMake when you configured Ceres, and the corresponding: <BUILD_DIR>/CMakeFiles/CMakeOutput.log

**Comment by sandwichmaker** [comment]
I am going to close this, if you have an update on this bug, please re-open it.
