### ISSUE TITLE
Windows/Andorid/iOS performance Issue

### ISSUE THREAD

**Issue by Changseob** [ceres-solver/ceres-solver#354]
Hi, I am developing Mobile SLAM from [VINS-Mobile](https://github.com/HKUST-Aerial-Robotics/VINS-Mobile)

But, I have some question or issue.

In iOS (VINS-Mobile), ceres-solver has any problem for SLAM
However, in Windows(or Android), there are some problems.

Although windows machine has better hardware definitely,  performance is lower than iOS.

I don't know it is lower performance or different working.

![image](https://user-images.githubusercontent.com/9537237/37574261-0453e676-2b63-11e8-8bf1-7a379d2042d1.png)

Console message is like image above.

I understand the message talks there is no convergence in optimization and timed out.
(also, I wonder why there is '-nan(nid)', furthermore, it is randomly appeared!)

But in iOS, there is no delay  with same video sequence.

is there some advice for me?

**Comment by sandwichmaker** [comment]
Can you share the output of ceres::Solver::Summary::FulReport() in the two cases please?
also worth talking to the original VINS developers about the nans.

**Comment by Changseob** [comment]
---------------------------- ↓ Windows 3 attempts FullReport() --------------------------------------------
Solver Summary (v 1.13.0-eigen-(3.3.4)-no_lapack-eigensparse-openmp-no_tbb)

                                     Original                  Reduced
Parameter blocks                          139                      136
Parameters                                428                      418
Effective parameters                      417                      408
Residual blocks                           372                      372
Residuals                                 744                      744

Minimizer                        TRUST_REGION

Dense linear algebra library            EIGEN
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver                     DENSE_SCHUR              DENSE_SCHUR
Threads                                     1                        1
Linear solver ordering              AUTOMATIC                   115,21
Schur structure                         2,3,3                    2,3,3

Cost:
Initial                          8.400891e+01
Final                            1.274951e+01
Change                           7.125941e+01

Minimizer iterations                       11
Successful steps                            4
Unsuccessful steps                          7

Time (in seconds):
Preprocessor                         0.009768

  Residual only evaluation           0.214953 (10)
  Jacobian & residual evaluation     0.001451 (4)
  Linear solver                      0.014061 (10)
Minimizer                            0.361510

Postprocessor                        0.000025
Total                                0.371304

Termination:                   NO_CONVERGENCE (Maximum solver time reached. Total solver time: 3.556620e-01 >= 3.000000e-01.)


Solver Summary (v 1.13.0-eigen-(3.3.4)-no_lapack-eigensparse-openmp-no_tbb)

                                     Original                  Reduced
Parameter blocks                          145                      142
Parameters                                446                      436
Effective parameters                      435                      426
Residual blocks                           476                      476
Residuals                                 952                      952

Minimizer                        TRUST_REGION

Dense linear algebra library            EIGEN
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver                     DENSE_SCHUR              DENSE_SCHUR
Threads                                     1                        1
Linear solver ordering              AUTOMATIC                   123,19
Schur structure                         2,3,3                    2,3,3

Cost:
Initial                          7.351487e+00
Final                            7.351487e+00
Change                           0.000000e+00

Minimizer iterations                        6
Successful steps                            1
Unsuccessful steps                          5

Time (in seconds):
Preprocessor                         0.008481

  Residual only evaluation           0.264667 (5)
  Jacobian & residual evaluation     0.000388 (1)
  Linear solver                      0.009515 (5)
Minimizer                            0.352624

Postprocessor                        0.000033
Total                                0.361139

Termination:                   NO_CONVERGENCE (Maximum solver time reached. Total solver time: 3.548857e-01 >= 3.000000e-01.)
Solver Summary (v 1.13.0-eigen-(3.3.4)-no_lapack-eigensparse-openmp-no_tbb)

                                     Original                  Reduced
Parameter blocks                          157                      154
Parameters                                482                      472
Effective parameters                      471                      462
Residual blocks                           503                      503
Residuals                                1006                     1006

Minimizer                        TRUST_REGION

Dense linear algebra library            EIGEN
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver                     DENSE_SCHUR              DENSE_SCHUR
Threads                                     1                        1
Linear solver ordering              AUTOMATIC                   135,19
Schur structure                         2,3,3                    2,3,3

Cost:
Initial                         -1.000000e+00

Minimizer iterations                        0
Successful steps                            0
Unsuccessful steps                          0

Time (in seconds):
Preprocessor                         0.009455

  Residual only evaluation           0.000000 (0)
  Jacobian & residual evaluation     0.069667 (1)
  Linear solver                      0.000000 (0)
Minimizer                            0.074617

Postprocessor                        0.000052
Total                                0.084125

Termination:                          FAILURE (Residual and Jacobian evaluation failed.)

---------------------------- ↑ Windows 4 attempts FullReport() --------------------------------------------
---------------------------- ↓ iOS 4 attempts FullReport() --------------------------------------------
olver Summary (v 1.12.0-eigen-(3.3.0)-no_lapack-no_openmp)

                                     Original                  Reduced
Parameter blocks                          147                      144
Parameters                                452                      442
Effective parameters                      441                      432
Residual blocks                           424                      424
Residual                                  848                      848

Minimizer                        TRUST_REGION

Dense linear algebra library            EIGEN
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver                     DENSE_SCHUR              DENSE_SCHUR
Threads                                     1                        1
Linear solver threads                       1                        1
Linear solver ordering              AUTOMATIC                  125, 19

Cost:
Initial                         -1.000000e+00

Minimizer iterations                        0
Successful steps                            0
Unsuccessful steps                          0

Time (in seconds):
Preprocessor                           0.0027

  Residual evaluation                  0.0000
  Jacobian evaluation                  0.0001
  Linear solver                        0.0000
Minimizer                              0.0002

Postprocessor                          0.0000
Total                                  0.0029

Termination:                          FAILURE (Residual and Jacobian evaluation failed.)


Solver Summary (v 1.12.0-eigen-(3.3.0)-no_lapack-no_openmp)

                                     Original                  Reduced
Parameter blocks                          130                      127
Parameters                                401                      391
Effective parameters                      390                      381
Residual blocks                           474                      474
Residual                                  948                      948

Minimizer                        TRUST_REGION

Dense linear algebra library            EIGEN
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver                     DENSE_SCHUR              DENSE_SCHUR
Threads                                     1                        1
Linear solver threads                       1                        1
Linear solver ordering              AUTOMATIC                  108, 19

Cost:
Initial                         -1.000000e+00

Minimizer iterations                        0
Successful steps                            0
Unsuccessful steps                          0

Time (in seconds):
Preprocessor                           0.0011

  Residual evaluation                  0.0000
  Jacobian evaluation                  0.0001
  Linear solver                        0.0000
Minimizer                              0.0001

Postprocessor                          0.0000
Total                                  0.0012

Termination:                          FAILURE (Residual and Jacobian evaluation failed.)


Solver Summary (v 1.12.0-eigen-(3.3.0)-no_lapack-no_openmp)

                                     Original                  Reduced
Parameter blocks                          133                      130
Parameters                                410                      400
Effective parameters                      399                      390
Residual blocks                           499                      499
Residual                                  998                      998

Minimizer                        TRUST_REGION

Dense linear algebra library            EIGEN
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver                     DENSE_SCHUR              DENSE_SCHUR
Threads                                     1                        1
Linear solver threads                       1                        1
Linear solver ordering              AUTOMATIC                  111, 19

Cost:
Initial                         -1.000000e+00

Minimizer iterations                        0
Successful steps                            0
Unsuccessful steps                          0

Time (in seconds):
Preprocessor                           0.0015

  Residual evaluation                  0.0000
  Jacobian evaluation                  0.0001
  Linear solver                        0.0000
Minimizer                              0.0001

Postprocessor                          0.0000
Total                                  0.0017

Termination:                          FAILURE (Residual and Jacobian evaluation failed.)
Solver Summary (v 1.12.0-eigen-(3.3.0)-no_lapack-no_openmp)

                                     Original                  Reduced
Parameter blocks                          152                      149
Parameters                                467                      457
Effective parameters                      456                      447
Residual blocks                           497                      497
Residual                                  994                      994

Minimizer                        TRUST_REGION

Dense linear algebra library            EIGEN
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver                     DENSE_SCHUR              DENSE_SCHUR
Threads                                     1                        1
Linear solver threads                       1                        1
Linear solver ordering              AUTOMATIC                  130, 19

Cost:
Initial                          1.791761e+02
Final                            1.397508e+00
Change                           1.777786e+02

Minimizer iterations                       17
Successful steps                            7
Unsuccessful steps                         10

Time (in seconds):
Preprocessor                           0.0019

  Residual evaluation                  0.0010
  Jacobian evaluation                  0.0020
  Linear solver                        0.0063
Minimizer                              0.0103

Postprocessor                          0.0000
Total                                  0.0122

Termination:                      CONVERGENCE (Function tolerance reached. |cost_change|/cost: 1.092564e-07 <= 1.000000e-06)
---------------------------- ↑ iOS 4 attempts FullReport() --------------------------------------------

**Comment by sandwichmaker** [comment]
@Changseob notice that the first three of your ios solves are actually failures. Looks like the residual/jacobian evaluation failed for some reason. Which is why it quits so early. 
The last ios iteration is more interesting, but there notice that you are using multiple threads while you are not using any threads in the windows solve. That should explain the performance difference you are observing.
