### ISSUE TITLE
Update FixedArray to use absl::FixedArray and deprecate ManualConstructor 

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#357]

**Comment by sandwichmaker** [comment]
This should fix https://github.com/ceres-solver/ceres-solver/issues/319

**Comment by keir** [comment]
While I agree we should fix #319, I'm less convinced we want to depend on absl. I'll first re-visit the alignment issue now that C++11 is required.

**Comment by sandwichmaker** [comment]
I meant pulling it out of absl and using it, instead of depending on absl.

**Comment by sandwichmaker** [comment]
@keir can you take a look please? I'd like to see this fixed for the 2.0 release.

**Comment by sandwichmaker** [comment]
https://github.com/ceres-solver/ceres-solver/commit/25e1cdbb6f5e0544f98c5b613e490716cbcabecf   fixes it.
