### ISSUE TITLE
install -> parallel_for_tbb.cc.o has no symbols

### ISSUE THREAD

**Issue by pmoulon** [ceres-solver/ceres-solver#359]
I noticed this `warning` message when I compiled and setup ceres on MacOS (CXX11 Threads ON, TBB OFF)

```
-- Installing: /usr/local/lib/libceres.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /usr/local/lib/libceres.a(parallel_for_tbb.cc.o) has no symbols
```

Here my question:
Do we want to include `parallel_for_tbb.cc` to the list of compiled files if we did not ask for TBB threading or do we just want to ignore this?

**Comment by sandwichmaker** [comment]
@pmoulon just ignore this for now. I hate the thought of making the cmake file even more complicated than it is already.
