### ISSUE TITLE
why the result of "RotationMatrixToAngleAxis"  differ from "Rodrigues" in OpenCV by a sign?

### ISSUE THREAD

**Issue by antonaaa** [ceres-solver/ceres-solver#360]
I use ceres to do Bundle Adjustment to optimize my SFM  program，but result always wrong.
After debugging, I find that problem occurs in function `RotationMatrixToAngleAxis`.
And I do the same testing,  and I find that the result of `RotationMatrixToAngleAxis` differs from  `Rodrigues` by a sign.

Below is my testing code, and the output:

below is my testing code. 
`#include <opencv2/opencv.hpp>
#include <ceres/ceres.h>
#include <ceres/rotation.h>
#include <Eigen/Core>
#include <Eigen/Geometry>

using namespace cv;
using namespace std;
using namespace Eigen;

void RotationMatrixToAngleAxis(double * R)
{
	// Opencv
	Mat R1(3, 3, CV_64F, R);
	cout <<"Opencv Rotation Matrix : " << endl;
	cout << R1 << endl;
	Mat rvec;
	Rodrigues(R1, rvec);
	cout << "Opencv Rotation Vector : " << endl;
	cout << rvec.t() << endl;
	cout << endl;

	//Eigen
	Matrix3d R2 = Matrix3d(R).transpose();
	cout <<"Eigen Rotation Matrix : " << endl;
	cout << R2 << endl;
	AngleAxisd rotationVector; 
	rotationVector = rotationVector.fromRotationMatrix(R2);
	cout <<"Eigen Rotation Vector axis : " << endl;
	cout << rotationVector.axis()[0] << " " << rotationVector.axis()[1] << " " << rotationVector.axis()[2] << endl;
	Vector3d rotationVector2 = rotationVector.axis() * rotationVector.angle();
	cout << rotationVector2(0) << " " << rotationVector2(1) << " " << rotationVector2(2) << endl;
	cout << endl;

	//Ceres
	double angleAxis[3];
	ceres::RotationMatrixToAngleAxis<double>(R, angleAxis);
	cout << "Ceres Rotation Vector : " << endl;
	cout << angleAxis[0] << " " << angleAxis[1] << " " << angleAxis[2] << endl;
}
int main()
{
	Vector3d axis = Vector3d(1,2,3).normalized();
	/* Vector3d axis = Vector3d(0, 0, 1); */
	AngleAxisd rotationVector(M_PI/4, axis);
	cout <<"----------------------------------------------"<<endl;

	Matrix3d rotationMatrix = rotationVector.matrix();
	double R[9] = {0};
	for(size_t i = 0; i < 3; ++i)
	{
		for(size_t j = 0; j < 3; ++j)
		{
			R[i * 3 + j] = rotationMatrix(i, j);
		}
	}
	RotationMatrixToAngleAxis(R);
	return 0;
}
`

And the output  is
`----------------------------------------------
Opencv Rotation Matrix : 
[0.7280277253875085, -0.525104821111919, 0.4407273056121099;
 0.6087885979157627, 0.7907905579903911, -0.06345657129884827;
 -0.3152016404063445, 0.3145079017103789, 0.8953952789951956]
Opencv Rotation Vector : 
[0.2099064885453392, 0.4198129770906784, 0.6297194656360178]

Eigen Rotation Matrix : 
  0.728028  -0.525105   0.440727
  0.608789   0.790791 -0.0634566
 -0.315202   0.314508   0.895395
Eigen Rotation Vector axis : 
0.267261 0.534522 0.801784
0.209906 0.419813 0.629719

Ceres Rotation Vector : 
-0.209906 -0.419813 -0.629719
`

**Comment by sxtiann** [comment]
> I use ceres to do Bundle Adjustment to optimize my SFM program，but result always wrong.
> After debugging, I find that problem occurs in function `RotationMatrixToAngleAxis`.
> And I do the same testing, and I find that the result of `RotationMatrixToAngleAxis` differs from `Rodrigues` by a sign.
> 
> Below is my testing code, and the output:
> 
> below is my testing code.
> `#include <opencv2/opencv.hpp>
> #include <ceres/ceres.h>
> #include <ceres/rotation.h>
> #include <Eigen/Core>
> #include <Eigen/Geometry>
> 
> using namespace cv;
> using namespace std;
> using namespace Eigen;
> 
> void RotationMatrixToAngleAxis(double * R)
> {
> // Opencv
> Mat R1(3, 3, CV_64F, R);
> cout <<"Opencv Rotation Matrix : " << endl;
> cout << R1 << endl;
> Mat rvec;
> Rodrigues(R1, rvec);
> cout << "Opencv Rotation Vector : " << endl;
> cout << rvec.t() << endl;
> cout << endl;
> 
> ```
> //Eigen
> Matrix3d R2 = Matrix3d(R).transpose();
> cout <<"Eigen Rotation Matrix : " << endl;
> cout << R2 << endl;
> AngleAxisd rotationVector; 
> rotationVector = rotationVector.fromRotationMatrix(R2);
> cout <<"Eigen Rotation Vector axis : " << endl;
> cout << rotationVector.axis()[0] << " " << rotationVector.axis()[1] << " " << rotationVector.axis()[2] << endl;
> Vector3d rotationVector2 = rotationVector.axis() * rotationVector.angle();
> cout << rotationVector2(0) << " " << rotationVector2(1) << " " << rotationVector2(2) << endl;
> cout << endl;
> 
> //Ceres
> double angleAxis[3];
> ceres::RotationMatrixToAngleAxis<double>(R, angleAxis);
> cout << "Ceres Rotation Vector : " << endl;
> cout << angleAxis[0] << " " << angleAxis[1] << " " << angleAxis[2] << endl;
> ```
> 
> }
> int main()
> {
> Vector3d axis = Vector3d(1,2,3).normalized();
> /* Vector3d axis = Vector3d(0, 0, 1); */
> AngleAxisd rotationVector(M_PI/4, axis);
> cout <<"----------------------------------------------"<<endl;
> 
> ```
> Matrix3d rotationMatrix = rotationVector.matrix();
> double R[9] = {0};
> for(size_t i = 0; i < 3; ++i)
> {
> 	for(size_t j = 0; j < 3; ++j)
> 	{
> 		R[i * 3 + j] = rotationMatrix(i, j);
> 	}
> }
> RotationMatrixToAngleAxis(R);
> return 0;
> ```
> 
> }
> `
> 
> And the output is
> `----------------------------------------------
> Opencv Rotation Matrix :
> [0.7280277253875085, -0.525104821111919, 0.4407273056121099;
> 0.6087885979157627, 0.7907905579903911, -0.06345657129884827;
> -0.3152016404063445, 0.3145079017103789, 0.8953952789951956]
> Opencv Rotation Vector :
> [0.2099064885453392, 0.4198129770906784, 0.6297194656360178]
> 
> Eigen Rotation Matrix :
> 0.728028 -0.525105 0.440727
> 0.608789 0.790791 -0.0634566
> -0.315202 0.314508 0.895395
> Eigen Rotation Vector axis :
> 0.267261 0.534522 0.801784
> 0.209906 0.419813 0.629719
> 
> Ceres Rotation Vector :
> -0.209906 -0.419813 -0.629719
> `

I find the  same problem. And it is more weird. Some values are the same. Some are opposite. Have you solved the problem?

**Comment by qianqian121** [comment]
Ceres reads the rotation matrix in col major by default. OpenCV is row major. Eigen is col major by default.
[antonaaa](https://github.com/antonaaa) testing code used the opposite row/column major.
