### ISSUE TITLE
make test failed on iterative_refiner_test 

### ISSUE THREAD

**Issue by hj-pony** [ceres-solver/ceres-solver#361]
output following:

Test project /home/×××/4git/ceres-solver/ceres-bin
        Start   1: array_utils_test
  1/128 Test   #1: array_utils_test .........................................   Passed    0.00 sec
        Start   2: autodiff_test
  2/128 Test   #2: autodiff_test ............................................   Passed    0.00 sec
        Start   3: autodiff_cost_function_test
  3/128 Test   #3: autodiff_cost_function_test ..............................   Passed    0.00 sec
        Start   4: autodiff_local_parameterization_test
  4/128 Test   #4: autodiff_local_parameterization_test .....................   Passed    0.00 sec
        Start   5: block_jacobi_preconditioner_test
  5/128 Test   #5: block_jacobi_preconditioner_test .........................   Passed    0.00 sec
        Start   6: block_random_access_dense_matrix_test
  6/128 Test   #6: block_random_access_dense_matrix_test ....................   Passed    0.00 sec
        Start   7: block_random_access_diagonal_matrix_test
  7/128 Test   #7: block_random_access_diagonal_matrix_test .................   Passed    0.00 sec
        Start   8: block_random_access_sparse_matrix_test
  8/128 Test   #8: block_random_access_sparse_matrix_test ...................   Passed    0.00 sec
        Start   9: block_sparse_matrix_test
  9/128 Test   #9: block_sparse_matrix_test .................................   Passed    0.00 sec
        Start  10: c_api_test
 10/128 Test  #10: c_api_test ...............................................   Passed    0.01 sec
        Start  11: canonical_views_clustering_test
 11/128 Test  #11: canonical_views_clustering_test ..........................   Passed    0.00 sec
        Start  12: compressed_col_sparse_matrix_utils_test
 12/128 Test  #12: compressed_col_sparse_matrix_utils_test ..................   Passed    0.00 sec
        Start  13: compressed_row_sparse_matrix_test
 13/128 Test  #13: compressed_row_sparse_matrix_test ........................   Passed    0.04 sec
        Start  14: concurrent_queue_test
 14/128 Test  #14: concurrent_queue_test ....................................   Passed    0.00 sec
        Start  15: conditioned_cost_function_test
 15/128 Test  #15: conditioned_cost_function_test ...........................   Passed    0.00 sec
        Start  16: conjugate_gradients_solver_test
 16/128 Test  #16: conjugate_gradients_solver_test ..........................   Passed    0.00 sec
        Start  17: corrector_test
 17/128 Test  #17: corrector_test ...........................................   Passed    0.20 sec
        Start  18: cost_function_to_functor_test
 18/128 Test  #18: cost_function_to_functor_test ............................   Passed    0.00 sec
        Start  19: covariance_test
 19/128 Test  #19: covariance_test ..........................................   Passed    5.61 sec
        Start  20: cubic_interpolation_test
 20/128 Test  #20: cubic_interpolation_test .................................   Passed    0.07 sec
        Start  21: dense_linear_solver_test
 21/128 Test  #21: dense_linear_solver_test .................................   Passed    0.00 sec
        Start  22: dense_sparse_matrix_test
 22/128 Test  #22: dense_sparse_matrix_test .................................   Passed    0.00 sec
        Start  23: detect_structure_test
 23/128 Test  #23: detect_structure_test ....................................   Passed    0.00 sec
        Start  24: dogleg_strategy_test
 24/128 Test  #24: dogleg_strategy_test .....................................   Passed    0.00 sec
        Start  25: dynamic_autodiff_cost_function_test
 25/128 Test  #25: dynamic_autodiff_cost_function_test ......................   Passed    0.00 sec
        Start  26: dynamic_compressed_row_sparse_matrix_test
 26/128 Test  #26: dynamic_compressed_row_sparse_matrix_test ................   Passed    0.00 sec
        Start  27: dynamic_numeric_diff_cost_function_test
 27/128 Test  #27: dynamic_numeric_diff_cost_function_test ..................   Passed    0.00 sec
        Start  28: dynamic_sparse_normal_cholesky_solver_test
 28/128 Test  #28: dynamic_sparse_normal_cholesky_solver_test ...............   Passed    0.00 sec
        Start  29: dynamic_sparsity_test
 29/128 Test  #29: dynamic_sparsity_test ....................................   Passed    1.17 sec
        Start  30: evaluation_callback_test
 30/128 Test  #30: evaluation_callback_test .................................   Passed    0.01 sec
        Start  31: evaluator_test
 31/128 Test  #31: evaluator_test ...........................................   Passed    0.01 sec
        Start  32: gradient_checker_test
 32/128 Test  #32: gradient_checker_test ....................................   Passed    0.00 sec
        Start  33: gradient_checking_cost_function_test
 33/128 Test  #33: gradient_checking_cost_function_test .....................   Passed    0.00 sec
        Start  34: gradient_problem_test
 34/128 Test  #34: gradient_problem_test ....................................   Passed    0.00 sec
        Start  35: gradient_problem_solver_test
 35/128 Test  #35: gradient_problem_solver_test .............................   Passed    0.00 sec
        Start  36: graph_test
 36/128 Test  #36: graph_test ...............................................   Passed    0.25 sec
        Start  37: graph_algorithms_test
 37/128 Test  #37: graph_algorithms_test ....................................   Passed    0.00 sec
        Start  38: householder_vector_test
 38/128 Test  #38: householder_vector_test ..................................   Passed    0.00 sec
        Start  39: implicit_schur_complement_test
 39/128 Test  #39: implicit_schur_complement_test ...........................   Passed    0.00 sec
        Start  40: inner_product_computer_test
 40/128 Test  #40: inner_product_computer_test ..............................   Passed    0.09 sec
        Start  41: invert_psd_matrix_test
 41/128 Test  #41: invert_psd_matrix_test ...................................   Passed    0.00 sec
        Start  42: is_close_test
 42/128 Test  #42: is_close_test ............................................   Passed    0.00 sec
        Start  43: iterative_refiner_test
 43/128 Test  #43: iterative_refiner_test ...................................***Failed    0.00 sec
        Start  44: iterative_schur_complement_solver_test
 44/128 Test  #44: iterative_schur_complement_solver_test ...................   Passed    0.00 sec
        Start  45: jet_test
 45/128 Test  #45: jet_test .................................................   Passed    0.00 sec
        Start  46: levenberg_marquardt_strategy_test
 46/128 Test  #46: levenberg_marquardt_strategy_test ........................   Passed    0.00 sec
        Start  47: line_search_minimizer_test
 47/128 Test  #47: line_search_minimizer_test ...............................   Passed    0.00 sec
        Start  48: line_search_preprocessor_test
 48/128 Test  #48: line_search_preprocessor_test ............................   Passed    0.00 sec
        Start  49: local_parameterization_test
 49/128 Test  #49: local_parameterization_test ..............................   Passed    0.33 sec
        Start  50: loss_function_test
 50/128 Test  #50: loss_function_test .......................................   Passed    0.00 sec
        Start  51: minimizer_test
 51/128 Test  #51: minimizer_test ...........................................   Passed    0.00 sec
        Start  52: normal_prior_test
 52/128 Test  #52: normal_prior_test ........................................   Passed    0.00 sec
        Start  53: numeric_diff_cost_function_test
 53/128 Test  #53: numeric_diff_cost_function_test ..........................   Passed    0.00 sec
        Start  54: ordered_groups_test
 54/128 Test  #54: ordered_groups_test ......................................   Passed    0.08 sec
        Start  55: parallel_for_test
 55/128 Test  #55: parallel_for_test ........................................   Passed    0.02 sec
        Start  56: parallel_utils_test
 56/128 Test  #56: parallel_utils_test ......................................   Passed    0.02 sec
        Start  57: parameter_block_test
 57/128 Test  #57: parameter_block_test .....................................   Passed    0.41 sec
        Start  58: parameter_block_ordering_test
 58/128 Test  #58: parameter_block_ordering_test ............................   Passed    0.00 sec
        Start  59: partitioned_matrix_view_test
 59/128 Test  #59: partitioned_matrix_view_test .............................   Passed    0.00 sec
        Start  60: polynomial_test
 60/128 Test  #60: polynomial_test ..........................................   Passed    0.00 sec
        Start  61: problem_test
 61/128 Test  #61: problem_test .............................................   Passed    2.30 sec
        Start  62: program_test
 62/128 Test  #62: program_test .............................................   Passed    0.00 sec
        Start  63: reorder_program_test
 63/128 Test  #63: reorder_program_test .....................................   Passed    0.00 sec
        Start  64: residual_block_test
 64/128 Test  #64: residual_block_test ......................................   Passed    0.00 sec
        Start  65: residual_block_utils_test
 65/128 Test  #65: residual_block_utils_test ................................   Passed    0.00 sec
        Start  66: rotation_test
 66/128 Test  #66: rotation_test ............................................   Passed    6.72 sec
        Start  67: schur_complement_solver_test
 67/128 Test  #67: schur_complement_solver_test .............................   Passed    0.00 sec
        Start  68: schur_eliminator_test
 68/128 Test  #68: schur_eliminator_test ....................................   Passed    0.00 sec
        Start  69: single_linkage_clustering_test
 69/128 Test  #69: single_linkage_clustering_test ...........................   Passed    0.00 sec
        Start  70: small_blas_test
 70/128 Test  #70: small_blas_test ..........................................   Passed    0.00 sec
        Start  71: solver_test
 71/128 Test  #71: solver_test ..............................................   Passed    0.00 sec
        Start  72: sparse_cholesky_test
 72/128 Test  #72: sparse_cholesky_test .....................................   Passed    0.06 sec
        Start  73: sparse_normal_cholesky_solver_test
 73/128 Test  #73: sparse_normal_cholesky_solver_test .......................   Passed    0.00 sec
        Start  74: subset_preconditioner_test
 74/128 Test  #74: subset_preconditioner_test ...............................   Passed    0.00 sec
        Start  75: system_test
 75/128 Test  #75: system_test ..............................................   Passed    0.00 sec
        Start  76: tiny_solver_test
 76/128 Test  #76: tiny_solver_test .........................................   Passed    0.00 sec
        Start  77: tiny_solver_autodiff_function_test
 77/128 Test  #77: tiny_solver_autodiff_function_test .......................   Passed    0.00 sec
        Start  78: tiny_solver_cost_function_adapter_test
 78/128 Test  #78: tiny_solver_cost_function_adapter_test ...................   Passed    0.00 sec
        Start  79: thread_pool_test
 79/128 Test  #79: thread_pool_test .........................................   Passed    0.00 sec
        Start  80: triplet_sparse_matrix_test
 80/128 Test  #80: triplet_sparse_matrix_test ...............................   Passed    0.08 sec
        Start  81: trust_region_minimizer_test
 81/128 Test  #81: trust_region_minimizer_test ..............................   Passed    0.01 sec
        Start  82: trust_region_preprocessor_test
 82/128 Test  #82: trust_region_preprocessor_test ...........................   Passed    0.00 sec
        Start  83: visibility_test
 83/128 Test  #83: visibility_test ..........................................   Passed    0.00 sec
        Start  84: visibility_based_preconditioner_test
 84/128 Test  #84: visibility_based_preconditioner_test .....................   Passed    0.00 sec
        Start  85: ba_denseschur_auto_test
 85/128 Test  #85: ba_denseschur_auto_test ..................................   Passed    3.02 sec
        Start  86: ba_denseschur_auto_threads_test
 86/128 Test  #86: ba_denseschur_auto_threads_test ..........................   Passed    2.49 sec
        Start  87: ba_denseschur_user_test
 87/128 Test  #87: ba_denseschur_user_test ..................................   Passed    2.73 sec
        Start  88: ba_denseschur_user_threads_test
 88/128 Test  #88: ba_denseschur_user_threads_test ..........................   Passed    2.37 sec
        Start  89: ba_iterschur_jacobi_auto_test
 89/128 Test  #89: ba_iterschur_jacobi_auto_test ............................   Passed    3.79 sec
        Start  90: ba_iterschur_jacobi_auto_threads_test
 90/128 Test  #90: ba_iterschur_jacobi_auto_threads_test ....................   Passed    3.25 sec
        Start  91: ba_iterschur_jacobi_user_test
 91/128 Test  #91: ba_iterschur_jacobi_user_test ............................   Passed    3.48 sec
        Start  92: ba_iterschur_jacobi_user_threads_test
 92/128 Test  #92: ba_iterschur_jacobi_user_threads_test ....................   Passed    3.11 sec
        Start  93: ba_iterschur_schurjacobi_auto_test
 93/128 Test  #93: ba_iterschur_schurjacobi_auto_test .......................   Passed    3.56 sec
        Start  94: ba_iterschur_schurjacobi_auto_threads_test
 94/128 Test  #94: ba_iterschur_schurjacobi_auto_threads_test ...............   Passed    3.05 sec
        Start  95: ba_iterschur_schurjacobi_user_test
 95/128 Test  #95: ba_iterschur_schurjacobi_user_test .......................   Passed    3.34 sec
        Start  96: ba_iterschur_schurjacobi_user_threads_test
 96/128 Test  #96: ba_iterschur_schurjacobi_user_threads_test ...............   Passed    2.96 sec
        Start  97: ba_iterschur_suitesparse_clustjacobi_auto_test
 97/128 Test  #97: ba_iterschur_suitesparse_clustjacobi_auto_test ...........   Passed    3.86 sec
        Start  98: ba_iterschur_suitesparse_clustjacobi_auto_threads_test
 98/128 Test  #98: ba_iterschur_suitesparse_clustjacobi_auto_threads_test ...   Passed    3.32 sec
        Start  99: ba_iterschur_suitesparse_clustjacobi_user_test
 99/128 Test  #99: ba_iterschur_suitesparse_clustjacobi_user_test ...........   Passed    3.55 sec
        Start 100: ba_iterschur_suitesparse_clustjacobi_user_threads_test
100/128 Test #100: ba_iterschur_suitesparse_clustjacobi_user_threads_test ...   Passed    3.02 sec
        Start 101: ba_iterschur_suitesparse_clusttri_auto_test
101/128 Test #101: ba_iterschur_suitesparse_clusttri_auto_test ..............   Passed    3.99 sec
        Start 102: ba_iterschur_suitesparse_clusttri_auto_threads_test
102/128 Test #102: ba_iterschur_suitesparse_clusttri_auto_threads_test ......   Passed    3.28 sec
        Start 103: ba_iterschur_suitesparse_clusttri_user_test
103/128 Test #103: ba_iterschur_suitesparse_clusttri_user_test ..............   Passed    3.86 sec
        Start 104: ba_iterschur_suitesparse_clusttri_user_threads_test
104/128 Test #104: ba_iterschur_suitesparse_clusttri_user_threads_test ......   Passed    3.07 sec
        Start 105: ba_sparsecholesky_suitesparse_auto_test
105/128 Test #105: ba_sparsecholesky_suitesparse_auto_test ..................   Passed    3.44 sec
        Start 106: ba_sparsecholesky_suitesparse_auto_threads_test
106/128 Test #106: ba_sparsecholesky_suitesparse_auto_threads_test ..........   Passed    3.27 sec
        Start 107: ba_sparsecholesky_suitesparse_user_test
107/128 Test #107: ba_sparsecholesky_suitesparse_user_test ..................   Passed    3.62 sec
        Start 108: ba_sparsecholesky_suitesparse_user_threads_test
108/128 Test #108: ba_sparsecholesky_suitesparse_user_threads_test ..........   Passed    3.29 sec
        Start 109: ba_sparsecholesky_eigensparse_auto_test
109/128 Test #109: ba_sparsecholesky_eigensparse_auto_test ..................   Passed    4.47 sec
        Start 110: ba_sparsecholesky_eigensparse_auto_threads_test
110/128 Test #110: ba_sparsecholesky_eigensparse_auto_threads_test ..........   Passed    3.94 sec
        Start 111: ba_sparsecholesky_eigensparse_user_test
111/128 Test #111: ba_sparsecholesky_eigensparse_user_test ..................   Passed    4.17 sec
        Start 112: ba_sparsecholesky_eigensparse_user_threads_test
112/128 Test #112: ba_sparsecholesky_eigensparse_user_threads_test ..........   Passed    4.02 sec
        Start 113: ba_sparsecholesky_cxsparse_auto_test
113/128 Test #113: ba_sparsecholesky_cxsparse_auto_test .....................   Passed    4.08 sec
        Start 114: ba_sparsecholesky_cxsparse_auto_threads_test
114/128 Test #114: ba_sparsecholesky_cxsparse_auto_threads_test .............   Passed    3.86 sec
        Start 115: ba_sparsecholesky_cxsparse_user_test
115/128 Test #115: ba_sparsecholesky_cxsparse_user_test .....................   Passed    4.09 sec
        Start 116: ba_sparsecholesky_cxsparse_user_threads_test
116/128 Test #116: ba_sparsecholesky_cxsparse_user_threads_test .............   Passed    4.26 sec
        Start 117: ba_sparseschur_suitesparse_auto_test
117/128 Test #117: ba_sparseschur_suitesparse_auto_test .....................   Passed    3.07 sec
        Start 118: ba_sparseschur_suitesparse_auto_threads_test
118/128 Test #118: ba_sparseschur_suitesparse_auto_threads_test .............   Passed    2.45 sec
        Start 119: ba_sparseschur_suitesparse_user_test
119/128 Test #119: ba_sparseschur_suitesparse_user_test .....................   Passed    3.09 sec
        Start 120: ba_sparseschur_suitesparse_user_threads_test
120/128 Test #120: ba_sparseschur_suitesparse_user_threads_test .............   Passed    2.49 sec
        Start 121: ba_sparseschur_eigensparse_auto_test
121/128 Test #121: ba_sparseschur_eigensparse_auto_test .....................   Passed    3.14 sec
        Start 122: ba_sparseschur_eigensparse_auto_threads_test
122/128 Test #122: ba_sparseschur_eigensparse_auto_threads_test .............   Passed    2.54 sec
        Start 123: ba_sparseschur_eigensparse_user_test
123/128 Test #123: ba_sparseschur_eigensparse_user_test .....................   Passed    3.10 sec
        Start 124: ba_sparseschur_eigensparse_user_threads_test
124/128 Test #124: ba_sparseschur_eigensparse_user_threads_test .............   Passed    2.52 sec
        Start 125: ba_sparseschur_cxsparse_auto_test
125/128 Test #125: ba_sparseschur_cxsparse_auto_test ........................   Passed    3.01 sec
        Start 126: ba_sparseschur_cxsparse_auto_threads_test
126/128 Test #126: ba_sparseschur_cxsparse_auto_threads_test ................   Passed    2.62 sec
        Start 127: ba_sparseschur_cxsparse_user_test
127/128 Test #127: ba_sparseschur_cxsparse_user_test ........................   Passed    2.93 sec
        Start 128: ba_sparseschur_cxsparse_user_threads_test
128/128 Test #128: ba_sparseschur_cxsparse_user_threads_test ................   Passed    2.44 sec

99% tests passed, 1 tests failed out of 128

Total Test time (real) = 162.70 sec

The following tests FAILED:
	 43 - iterative_refiner_test (Failed)
Errors while running CTest
Makefile:127: recipe for target 'test' failed
make: *** [test] Error 8

**Comment by hj-pony** [comment]
@sandwichmaker 
output is following, it seems like what you said. and what should i do to pass the test.

Running main() from gmock_main.cc
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from IterativeRefinerTest
[ RUN      ] IterativeRefinerTest.RandomSolutionWithExactFactorizationConverges
[       OK ] IterativeRefinerTest.RandomSolutionWithExactFactorizationConverges (0 ms)
[ RUN      ] IterativeRefinerTest.RandomSolutionWithApproximationFactorizationConverges
/home/junhu/4git/ceres-solver/internal/ceres/iterative_refiner_test.cc:169: Failure
The difference between (lhs_ * refined_solution - rhs_).norm() and 0.0 is 2.9373740229761033e-16, which exceeds std::numeric_limits<double>::epsilon(), where
(lhs_ * refined_solution - rhs_).norm() evaluates to 2.9373740229761033e-16,
0.0 evaluates to 0, and
std::numeric_limits<double>::epsilon() evaluates to 2.2204460492503131e-16.
[  FAILED  ] IterativeRefinerTest.RandomSolutionWithApproximationFactorizationConverges (0 ms)
[----------] 2 tests from IterativeRefinerTest (0 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] IterativeRefinerTest.RandomSolutionWithApproximationFactorizationConverges

 1 FAILED TEST

**Comment by sandwichmaker** [comment]
I just pushed a change, this should be fixed at HEAD.

**Comment by hj-pony** [comment]
thx, it works.
