### ISSUE TITLE
Build problem in 1.14 Android

### ISSUE THREAD

**Issue by SummerPoon928** [ceres-solver/ceres-solver#362]
For Android.mk in version 1.14, **thread_token_provider.cc** and **parallel_utils.cc** are missing in **LOCAL_SRC_FILES**. Therefore unresolved reference of **ThreadTokenProvider** and **LinearIndexToUpperTriangularIndex** occurs in libceres.a respectively when these 2 classes are called by other application.

**Comment by sandwichmaker** [comment]
@SummerPoon928 thanks for reporting, I will fix this shortly.

**Comment by sandwichmaker** [comment]
could you try 

https://ceres-solver-review.googlesource.com/c/ceres-solver/+/13440 

which has the fix and a few other changes.

**Comment by SummerPoon928** [comment]
Ok! I will try but I would like to ask a question. For your update, it is mentioned that OpenMP is enabled. However, from the official website, it states that OpenMP is not support. If Android is not able to use OpenMP as multi-threading, is it necessary to add it on Android.mk file?

Update Android.mk

1. Add some missing files.
2. Add support for EIGEN_SPARSE.
**3. Enable OpenMP threading by default.**

**OPENMP [Default: ON]: On certain platforms like Android, multi-threading with OpenMP is not supported. Turn this OFF to disable multi-threading.**

**Comment by SummerPoon928** [comment]
I use android-ndk-r10e to build but it fails. 

For Android.mk **-DCERES_STD_UNORDERED_MAP** is disabled so that the following error message occurs.

ceres-solver/jni/../internal/ceres/collections_port.h:66:4: error: **#error One of: CERES_NO_UNORDERED_MAP, CERES_TR1_UNORDERED_MAP, CERES_STD_UNORDERED_MAP, CERES_STD_UNORDERED_MAP_IN_TR1_NAMESPACE** must be defined!

**Comment by sandwichmaker** [comment]
What version of Ceres are you using?
Use the version at head.

**Comment by SummerPoon928** [comment]
I use version 1.14.0

**Comment by sandwichmaker** [comment]
@SummerPoon928 is this still open? have a look at HEAD, cmake support should be straightforward to use now.

**Comment by sandwichmaker** [comment]
I am going to close this, please re-open if this is still an issue.

**Comment by Glavnokoman** [comment]
cmake build still does not work for me
`Performing Test CXX11_MATH_FUNCTIONS_FOUND
-- Performing Test CXX11_MATH_FUNCTIONS_FOUND - Success
-- Looking for pthread.h
-- Looking for pthread.h - not found
CMake Error at /usr/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.12/Modules/FindThreads.cmake:205 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:553 (find_package`
In the same config gtest cmake build does find threads.

flags used:
`-DBUILD_TESTING=OFF \
            -DBUILD_EXAMPLES=OFF \
            -DBUILD_BENCHMARKS=OFF \
            -DMINIGLOG=ON \
            -DGFLAGS=OFF \
            -DSUITESPARSE=OFF \
            -DCXSPARSE=OFF \
            -DLAPACK=OFF \
            -DSCHUR_SPECIALIZATIONS=OFF \
            -DCUSTOM_BLAS=OFF`
