### ISSUE TITLE
The example "nist" couldn't be built under windows10 + msvc2017 + cmake3.10

### ISSUE THREAD

**Issue by SerIgFed** [ceres-solver/ceres-solver#368]
the linker says that the obj-file is too big, and I had to fix it in the "examples\CMakeLists.txt" file:
after the line:
     add_executable(nist nist.cc)

I've inserted the 3 lines:
    if(MSVC)
        set_target_properties(nist PROPERTIES COMPILE_FLAGS "${COMPILE_FLAGS} /bigobj")
    endif()
, and then it was built successfully. It would be nice to get this fix from you.

**Comment by sergiud** [comment]
This does not seem to be a proper fix. Where does the variable `${COMPILE_FLAGS}` come from? Also, the `COMPILE_FLAGS` property is deprecated and `COMPILE_OPTIONS` should be used instead.

**Comment by alexsmac** [comment]
If this is *only* required for nist, then (as @sergiud already said) this would be a better fix:

```
if (MSVC)
   target_compile_options(nist PRIVATE "/bigobj")
endif()
```

If you can confirm that fixes the problem we can create a CL to add this to master.

**Comment by SerIgFed** [comment]
Thanks for the correction, it works fine.

**Comment by alexsmac** [comment]
This fix has now been merged into master.
