### ISSUE TITLE
Build failed in android 2.3.2 with ceres_solver 1.14

### ISSUE THREAD

**Issue by month612** [ceres-solver/ceres-solver#369]
Build failed in android 2.3.2 use ceres_solver 1.14

I'm trying to use the Ceres solver 1.14 for a project in Android.I strictly follow the installation(http://www.ceres-solver.org/installation.html)，but I'm running into some "undefined reference" linker errors and I was hoping somebody could help me figure out what's wrong.
I  defined the CERES_GLOG_DIR=/D:/Ceres_ndk/ceres-solver-1.14.0/jni/glog ndk-build -j 
in Android.mk and this is my Application.mk :
APP_BUILD_SCRIPT := $(call my-dir)/Android.mk
APP_PROJECT_PATH := $(call my-dir)
APP_OPTIM := release
APP_CPPFLAGS += -frtti 
APP_CPPFLAGS += -fexceptions
APP_CPPFLAGS += -std=c++11
APP_STL := gnustl_static

APP_ABI := armeabi-v7a
 The Android.mk and Application.mk I Mentioned are all in D:\Ceres_ndk\ceres-solver-1.14.0\jni

This is my Cmakelist.txt in Android Studio
#工程路径
set(pathToProject E:/AS/Android-Demo)

#CMake版本信息
cmake_minimum_required(VERSION 3.4.1)

set(CMAKE_VERBOSE_MAKEFILE on)
set(CMAKE_STATIC_LINKER_FLAGS "${CMAKE_STATIC_LINKER_FLAGS} -Wl,--gc-sections")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -fPIC -fno-rtti -fno-exceptions -DDebug   ")

#配置加载native依赖
include_directories(${pathToProject}/app/src/main/cpp/include/opencv)
include_directories(${pathToProject}/app/src/main/cpp/include/CL)
include_directories(${pathToProject}/app/src/main/cpp/include/eigen3)
include_directories(${pathToProject}/app/src/main/cpp/include/)
include_directories(${pathToProject}/app/src/main/cpp/include/ceres-solver/include)
include_directories(${pathToProject}/app/src/main/cpp/include/ceres-solver/internal)
include_directories(${pathToProject}/app/src/main/cpp/include/ceres-solver/internal/ceres/miniglog)
include_directories(${pathToProject}/app/src/main/cpp/include/ceres-solver/config)

#静态方式加载

add_library( opencv SHARED IMPORTED )
set_target_properties(opencv PROPERTIES IMPORTED_LOCATION ${pathToProject}/app/src/main/jniLibs/armeabi-v7a/libopencv_java3.so)

add_library(lib-ceres STATIC IMPORTED)
set_target_properties(lib-ceres PROPERTIES IMPORTED_LOCATION ${pathToProject}/app/src/main/jniLibs/armeabi-v7a/libceres.a)

#C++日志
find_library( log-lib log )

#CPP文件夹下带编译的cpp文件
add_library( native-lib SHARED src/main/cpp/native-lib.cpp)
target_link_libraries( native-lib
                        opencv
                        ${log-lib}
                        lib-ceres                  )

The native-lib.cpp is as follows:

#include <jni.h>
#include <string>
#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/core/ocl.hpp>
#include <ceres/ceres.h>
#include <Eigen/Dense>
#include <android/log.h>
#define LOG_TAG "Test"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

void testCeres(void)
{

    double initial_x = 5.0;
    double x = initial_x;

    ceres::Problem problem;

    ceres::CostFunction* cost_function =
            new ceres::AutoDiffCostFunction<CostFunctor, 1, 1>(new CostFunctor);
    problem.AddResidualBlock(cost_function, NULL, &x);

    ceres::Solver::Options options;
    options.linear_solver_type = ceres::DENSE_QR;
    options.minimizer_progress_to_stdout = true;
    ceres::Solver::Summary summary;
    ceres::Solve(options, &problem, &summary);

    LOGD("sfm X: %f -> %f",initial_x,x);

}
//图像处理
extern "C"
JNIEXPORT jintArray JNICALL
Java_com_hezhaoxin_solomon_vins_1android_NDKloader_getGrayImage(
        JNIEnv *env,
        jclass type,
        jintArray pixels_,
        jint w, jint h) {
    jint *pixels = env->GetIntArrayElements(pixels_, NULL);
    // TODO
    if(pixels==NULL){
        return NULL;
    }
    cv::Mat imgData(h, w, CV_8UC4, pixels);
    uchar *ptr = imgData.ptr(0);
    for (int i = 0; i < w * h; i++) {
        int grayScale = (int) (ptr[4 * i + 2] * 0.299 + ptr[4 * i + 1] * 0.587
                               + ptr[4 * i + 0] * 0.114);
        ptr[4 * i + 1] = (uchar) grayScale;
        ptr[4 * i + 2] = (uchar) grayScale;
        ptr[4 * i + 0] = (uchar) grayScale;
    }

    int size = w * h;
    jintArray result = env->NewIntArray(size);
    env->SetIntArrayRegion(result, 0, size, pixels);
    env->ReleaseIntArrayElements(pixels_, pixels, 0);

    testCeres();

     LOGD("sfm TEST LOG");

    return result;
}
Compilation works fine, linking fails with the following error messages:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
Error while executing process C:\Users\Administrator\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build E:\AS\Android-Demo\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target native-lib}
[1/1] Linking CXX shared library ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libnative-lib.so
FAILED: cmd.exe /C "cd . && C:\Users\Administrator\AppData\Local\Android\sdk\ndk-bundle\android-ndk-r15c\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi --gcc-toolchain=C:/Users/Administrator/AppData/Local/Android/sdk/ndk-bundle/android-ndk-r15c/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=C:/Users/Administrator/AppData/Local/Android/sdk/ndk-bundle/android-ndk-r15c/sysroot -fPIC -isystem C:/Users/Administrator/AppData/Local/Android/sdk/ndk-bundle/android-ndk-r15c/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -std=c++11 -fPIC -fno-rtti -fno-exceptions -DDebug -std=c++11 -fPIC -fno-rtti -fno-exceptions -DDebug    -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a --sysroot C:/Users/Administrator/AppData/Local/Android/sdk/ndk-bundle/android-ndk-r15c/platforms/android-21/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--exclude-libs,libunwind.a -LC:/Users/Administrator/AppData/Local/Android/sdk/ndk-bundle/android-ndk-r15c/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ..\..\..\..\build\intermediates\cmake\debug\obj\armeabi-v7a\libnative-lib.so CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o  ../../../../src/main/jniLibs/armeabi-v7a/libopencv_java3.so -llog ../../../../src/main/jniLibs/armeabi-v7a/libopencv_calib3d.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_core.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_features2d.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_flann.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_highgui.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_imgcodecs.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_imgproc.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_ml.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_objdetect.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_photo.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_shape.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_stitching.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_superres.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_video.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_videoio.a ../../../../src/main/jniLibs/armeabi-v7a/libopencv_videostab.a ../../../../src/main/jniLibs/armeabi-v7a/libceres.a -lm "C:/Users/Administrator/AppData/Local/Android/sdk/ndk-bundle/android-ndk-r15c/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++.a" && cd ."
D:/Ceres_ndk/ceres-solver-1.14.0/jni/../internal\ceres/program_evaluator.h:188: error: undefined reference to 'ceres::internal::ThreadTokenProvider::ThreadTokenProvider(int)'
  D:/Ceres_ndk/ceres-solver-1.14.0/jni/../internal\ceres/scoped_thread_token.h:44: error: undefined reference to 'ceres::internal::ThreadTokenProvider::Acquire()'
  D:/Ceres_ndk/ceres-solver-1.14.0/jni/../internal\ceres/scoped_thread_token.h:46: error: undefined reference to 'ceres::internal::ThreadTokenProvider::Release(int)'
  D:/Ceres_ndk/ceres-solver-1.14.0/jni/../internal\ceres/program_evaluator.h:188: error: undefined reference to 'ceres::internal::ThreadTokenProvider::ThreadTokenProvider(int)'
  D:/Ceres_ndk/ceres-solver-1.14.0/jni/../internal\ceres/scoped_thread_token.h:44: error: undefined reference to 'ceres::internal::ThreadTokenProvider::Acquire()'
  D:/Ceres_ndk/ceres-solver-1.14.0/jni/../internal\ceres/scoped_thread_token.h:46: error: undefined reference to 'ceres::internal::ThreadTokenProvider::Release(int)'
  D:/Ceres_ndk/ceres-solver-1.14.0/jni/../internal\ceres/program_evaluator.h:188: error: undefined reference to 'ceres::internal::ThreadTokenProvider::ThreadTokenProvider(int)'
  D:/Ceres_ndk/ceres-solver-1.14.0/jni/../internal\ceres/scoped_thread_token.h:44: error: undefined reference to 'ceres::internal::ThreadTokenProvider::Acquire()'
  D:/Ceres_ndk/ceres-solver-1.14.0/jni/../internal\ceres/scoped_thread_token.h:46: error: undefined reference to 'ceres::internal::ThreadTokenProvider::Release(int)'
  D:/Ceres_ndk/ceres-solver-1.14.0/jni/../internal\ceres/program_evaluator.h:188: error: undefined reference to 'ceres::internal::ThreadTokenProvider::ThreadTokenProvider(int)'
  D:/Ceres_ndk/ceres-solver-1.14.0/jni/../internal\ceres/scoped_thread_token.h:44: error: undefined reference to 'ceres::internal::ThreadTokenProvider::Acquire()'
  D:/Ceres_ndk/ceres-solver-1.14.0/jni/../internal\ceres/scoped_thread_token.h:46: error: undefined reference to 'ceres::internal::ThreadTokenProvider::Release(int)'
  clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Any suggestions where is wrong?Thank you very much!

**Comment by alexsmac** [comment]
You're hitting the issue fixed this by [this commit](https://github.com/ceres-solver/ceres-solver/commit/c6cf24cb1bfe205173fb9f41b7cf929c57745113#diff-276d9f119640e5ce234cead6a37a559c), can you try this with the master branch of Ceres instead of the 1.14 release - that should fix this problem.

**Comment by month612** [comment]
Thank you very much for your help. It was very useful to me and now  ceres_solver do works fine on Android.Thank you very much！

**Comment by non-void** [comment]
I am also struggling with the ceres-on-android problem, can you please share the android source code with me?
I want to compare your project with mine and find where I do wrong.

Very thanks if you are so glad to share it with me.

Email: panxiaoyu6@gmail.com
