### ISSUE TITLE
Is MiniGLOG still needed?

### ISSUE THREAD

**Issue by sweeneychris** [ceres-solver/ceres-solver#370]
It seems GLOG is now supporting Android: https://github.com/google/glog/issues/280

**Comment by alexsmac** [comment]
Interestingly, most users on the mailing list about MINIGLOG seems to be running Windows, not Android, as a result I think its outgrown its original intended use-case of compensating for glog not being available on Android.

**Comment by sandwichmaker** [comment]
closing for now, as there is no real way this is going away.
