### ISSUE TITLE
Ubuntu 14.04 configuring incomplete ceres 1.13

### ISSUE THREAD

**Issue by nicole-antoine** [ceres-solver/ceres-solver#372]
Hello, 
I'm currently trying to install ceres-solver but even though I tried to follow some guides/steps (I followed the "official instructions" as well as https://chaitanyaandhare.wordpress.com/2015/01/25/how-to-install-google-ceres-solver-and-1dsfm-on-ubuntu-14-04/ in vain.) I end up with errors, some I could deal with but I'm a bit of idea right now. I also tried with different version but I don’t see any difference concerning the error. 

If I try with the 1.13 version with cmake -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF ../ceres-solver-1.13.0/ the output is:

-- Detected Ceres version: 1.13.0 from /home/vclab/build/ceres-solver-1.13.0/include/ceres/version.h
-- No preference for use of exported Eigen CMake configuration set, and no hints for include directory provided. Defaulting to preferring an installed/exported Eigen CMake configuration if available.
CMake Error at /home/vclab/eigen-eigen-5a0156e40feb/build/Eigen3Config.cmake:20 (include):
  include could not find load file:

    /home/vclab/eigen-eigen-5a0156e40feb/build/Eigen3Targets.cmake
Call Stack (most recent call first):
  cmake/FindEigen.cmake:149 (find_package)
  CMakeLists.txt:206 (find_package)

-- Found installed version of Eigen: /home/vclab/eigen-eigen-5a0156e40feb/build
-- Found Eigen: /home/include/eigen3 (found version "3.3.4") 
-- Found Eigen version 3.3.4: /home/include/eigen3

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

-- Looking for dgemm_
-- Looking for dgemm_ - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- Found LAPACK library: /usr/lib/liblapack.so;/usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- Found BLAS library: /usr/lib/libf77blas.so;/usr/lib/libatlas.so
-- A library with BLAS API found.
-- Found AMD headers in: /usr/include/suitesparse
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found CAMD headers in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found COLAMD headers in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found CCOLAMD headers in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found CHOLMOD headers in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found SUITESPARSEQR headers in: /usr/include/suitesparse
-- Found SUITESPARSEQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Did not find TBB library (optional SuiteSparse dependency)
-- Did not find Intel TBB library, assuming SuiteSparseQR was not compiled with TBB.
-- Found SUITESPARSE_CONFIG headers in: /usr/include/suitesparse
-- Found SUITESPARSE_CONFIG library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.a
-- Found LIBRT library: /usr/lib/x86_64-linux-gnu/librt.so
-- Adding librt: /usr/lib/x86_64-linux-gnu/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Did not find METIS library (optional SuiteSparse dependency)
-- Found SuiteSparse: TRUE (found version "4.2.1") 
-- Found SuiteSparse 4.2.1, building with SuiteSparse.
-- Found CXSparse: /usr/include/suitesparse (found version "3.1.2") 
-- Found CXSparse version: 3.1.2, building with CXSparse.
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
-- Performing Test GFLAGS_IN_GOOGLE_NAMESPACE
-- Performing Test GFLAGS_IN_GOOGLE_NAMESPACE - Success
-- Found Gflags: /usr/local/include  
-- Found Google Flags header in: /usr/local/include, in namespace: google
-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
-- Found exported glog build directory: /home/vclab/glog/build
-- Detected glog version: 0.3.5
-- Found Glog: glog::glog  
-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
-- Building with OpenMP.
-- Performing Test COMPILER_HAS_CXX11_FLAG
-- Performing Test COMPILER_HAS_CXX11_FLAG - Success
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - not found
-- Looking for C++ include tr1/unordered_map
-- Looking for C++ include tr1/unordered_map - found
-- Found tr1/unordered_map/set in std::tr1 namespace.
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Failed
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE - Failed
-- Looking for C++ include tr1/memory
-- Looking for C++ include tr1/memory - found
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER - Success
-- Found shared_ptr in std::tr1 namespace using <tr1/memory> header.
-- Building Ceres as a shared library.
-- No build type specified; defaulting to CMAKE_BUILD_TYPE=Release.
-- Creating configured Ceres config.h output directory: /home/vclab/build/ceres-bin/config/ceres/internal
-- Enabling CERES_USE_OPENMP in Ceres config.h
-- Enabling CERES_HAVE_PTHREAD in Ceres config.h
-- Enabling CERES_HAVE_RWLOCK in Ceres config.h
-- Enabling CERES_TR1_UNORDERED_MAP in Ceres config.h
-- Enabling CERES_TR1_MEMORY_HEADER in Ceres config.h
-- Enabling CERES_TR1_SHARED_PTR in Ceres config.h
-- Enabling CERES_USING_SHARED_LIBRARY in Ceres config.h
-- Build the examples.
-- Configuring incomplete, errors occurred!
See also "/home/vclab/build/ceres-bin/CMakeFiles/CMakeOutput.log".
See also "/home/vclab/build/ceres-bin/CMakeFiles/CMakeError.log".

I'm not sure if it really comes from these pthread/shared ptr error because I think at some point I got rid of it but it still failed.. I attached the 2 output files created by cmake in case it could help. 

Regards, 

[CMakeOutput.log](https://github.com/ceres-solver/ceres-solver/files/2005897/CMakeOutput.log)
[CMakeError.log](https://github.com/ceres-solver/ceres-solver/files/2005896/CMakeError.log)

**Comment by alexsmac** [comment]
@nicole-antoine this section is the error that is preventing CMake from configuring Ceres:

```
CMake Error at /home/vclab/eigen-eigen-5a0156e40feb/build/Eigen3Config.cmake:20 (include):
include could not find load file:

/home/vclab/eigen-eigen-5a0156e40feb/build/Eigen3Targets.cmake
Call Stack (most recent call first):
cmake/FindEigen.cmake:149 (find_package)
CMakeLists.txt:206 (find_package)
```

The problem is specifically that the `Eigen3Targets.cmake` file has been deleted from your Eigen build directory.  I checked a fresh build of eigen-eigen-5a0156e40feb (3.3.4) and Eigen's CMake will correctly create that file so for some reason it was deleted in your build.  Rebuilding in `/home/vclab/eigen-eigen-5a0156e40feb/build` should regenerate it.

The output in the CMakeError.log related to shared_ptrs are expected, Ceres performs multiple tests via CMake to determine the combination of namespace and path for shared_ptr on the current system - any of those tests which fail will be recorded in CMakeError.log.  However, only one combination is expected to pass for any given system, for your system the following lines specify which combination was detected:

```
-- Found tr1/unordered_map/set in std::tr1 namespace.
...
-- Found shared_ptr in std::tr1 namespace using <tr1/memory> header.
```
