### ISSUE TITLE
C++17 removes random_shuffle breaks ceres-solver

### ISSUE THREAD

**Issue by NeroBurner** [ceres-solver/ceres-solver#373]
Ceres-Solver with C++17 won't compile.

C++14 deprecates `random_shuffle`, C++17 removes `random_shuffle`
As replacement since C++11 `std::shuffle` is provided
Source: http://en.cppreference.com/w/cpp/algorithm/random_shuffle

In current master only `schur_eliminator_impl.h` seems to use random_shuffle https://github.com/ceres-solver/ceres-solver/blob/5d8b494557e17992b64d8df548f49ef1f9ef4e05/internal/ceres/schur_eliminator_impl.h#L155
Since https://github.com/ceres-solver/ceres-solver/commit/282b8b5f35de02d653292c480796a1a53946c16c ceres-solver requires at least C++11. Therefore this change should make no problems

CC: @norbertwenzel

**Comment by sandwichmaker** [comment]
@NeroBurner that line can likely just be dropped. Please feel free to send a CL.
