### ISSUE TITLE
 Residual and Jacobian evaluation failed.

### ISSUE THREAD

**Issue by ZhengPan2014** [ceres-solver/ceres-solver#375]
I'm doing PnP problem with ceres-solver, but I got the problem mentioned in the title, the residual is inf.
## **code is as follow:**
```
struct MinReprojectionError{
    MinReprojectionError(Point3f p0, Point2f p1)
    : point_3d(p0), point_2d(p1){}

    template<typename T>
    bool operator()(const T* pose, T* residuals) const{

        T p_world[3];
        p_world[0] = T(point_3d.x);
        p_world[1] = T(point_3d.y);
        p_world[2] = T(point_3d.z);
        std::cout<<"p_world: "<<p_world[0]<<", "<<p_world[1]<<", "<<p_world[2]<<std::endl<<std::flush;
        T p_camera[3];
        ceres::AngleAxisRotatePoint(pose, p_world, p_camera);
        p_camera[0] = p_camera[0] + pose[3];
        p_camera[1] = p_camera[1] + pose[4];
        p_camera[2] = p_camera[2] + pose[5];

        std::cout<<"p_camera: "<<p_camera[0]<<", "<<p_camera[1]<<", "<<p_camera[2]<<std::endl<<std::flush;
        T predicted_x = T(fx) * p_camera[0]/p_camera[3] + T(cx);
        T predicted_y = T(fy) * p_camera[1]/p_camera[3] + T(cy);

        T observed_x = T(point_2d.x);
        T observed_y = T(point_2d.y);

        residuals[0] = predicted_x - observed_x;
        residuals[1] = predicted_y - observed_y;
        return true;
    }

    static ceres::CostFunction* Create(const Point3f point_world,
                                       const Point2f keypoint){
        return (new ceres::AutoDiffCostFunction<MinReprojectionError, 2, 6>(
                new MinReprojectionError(point_world, keypoint)));
   }

   Point3f point_3d;
   Point2f point_2d;
};

int main()
{
 .......// preprocessed code
 // Non-linear Least Squares optimization
             double pose_[6];
             pose_[0] = r_vec.at<float>(0);
             pose_[1] = r_vec.at<float>(1);
             pose_[2] = r_vec.at<float>(2);
             pose_[3] = t_vec.at<float>(0);
             pose_[4] = t_vec.at<float>(1);
             pose_[5] = t_vec.at<float>(2);

             ceres::Problem problem;
             for(int i=0; i < refPoints.size(); i++)
             {
                 ceres::CostFunction* cost_function = MinReprojectionError::Create(refPoints.at(i), KPS.at(i));
                 problem.AddResidualBlock(cost_function,
                                          NULL,
                                          pose_);
             }

             ceres::Solver::Options options;
             options.linear_solver_type = ceres::SPARSE_NORMAL_CHOLESKY;
             options.minimizer_progress_to_stdout = true;
             ceres::Solver::Summary summary;
             ceres::Solve(options, &problem, &summary);
            .....// other code.
}
```

## **Error in terminator:**
Residual Block size: 1 parameter blocks x 2 residuals

For each parameter block, the value of the parameters are printed in the first column   
and the value of the jacobian under the corresponding residual. If a ParameterBlock was 
held constant then the corresponding jacobian is printed as 'Not Computed'. If an entry 
of the Jacobian/residual array was requested but was not written to by user code, it is 
indicated by 'Uninitialized'. This is an error. Residuals or Jacobian values evaluating 
to Inf or NaN is also an error.  

Residuals:             -inf         -inf 

Parameter Block 0, size: 6

 3.27566e-07 |          inf          inf 
 4.57748e-41 |          inf          inf 
 3.27566e-07 |          inf          inf 
 3.27569e-07 |          inf          inf 
 4.57748e-41 |          inf          inf 
 3.27569e-07 |          inf          inf 

E0521 19:10:38.071343 11097 trust_region_minimizer.cc:73] Terminating: Residual and Jacobian evaluation failed.
p_world: [-0.436771 ; 0, 0, 0, 0, 0, 0], [-2.79137 ; 0, 0, 0, 0, 0, 0], [10.7564 ; 0, 0, 0, 0, 0, 0]
p_camera: [461.563 ; 0, 10.7564, 2.79137, 1, 0, 0], [106.209 ; -10.7564, 0, -0.436771, 0, 1, 0], [563.956 ; -2.79137, 0.436771, 0, 0, 0, 1]
W0521 19:10:38.086251 11097 residual_block.cc:131] 

Error in evaluating the ResidualBlock.

There are two possible reasons. Either the CostFunction did not evaluate and fill all    
residual and jacobians that were requested or there was a non-finite value (nan/infinite)
generated during the or jacobian computation.

**Comment by sergiud** [comment]
Obviously, you're doing something wrong. These lines look suspicious:

```c++
T predicted_x = T(fx) * p_camera[0]/p_camera[3] + T(cx);
T predicted_y = T(fy) * p_camera[1]/p_camera[3] + T(cy);
```
There's an out-of-bounds access to `p_camera[3]`.

**Comment by ZhengPan2014** [comment]
@sergiud thank you!  such a stupid mistake I have made and I even can't find it out myself just because I wrote it.
