### ISSUE TITLE
GCC_VERSION is blank on cmake, -march=native not set

### ISSUE THREAD

**Issue by v01d** [ceres-solver/ceres-solver#377]
I was building ceres on ubuntu 16.04 with CMAKE_BUILD_TYPE=Release and found out it does not set march=native. I traced the problem to the GCC_VERSION variable not being set. I found out that the recommended way to test gcc version is using CMAKE_CXX_COMPILER_VERSION variable. Changing this in the cmake file makes it correctly detect the version as being above 4.2 and enables the corresponding flag.

**Comment by sandwichmaker** [comment]
@alexsmac can you take a look please?

**Comment by alexsmac** [comment]
This should be fixed in [this CL](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/13662) which should be landing soon.

**Comment by alexsmac** [comment]
This should now be fixed in master.
