### ISSUE TITLE
target_compile_features support for not-so-old compilers

### ISSUE THREAD

**Issue by DmitriyKorchemkin** [ceres-solver/ceres-solver#378]
Hello,

282b8b5f3 adds 
```
target_compile_features(ceres PUBLIC ${REQUIRED_PUBLIC_CXX_FEATURES})
```
to internal/ceres/CMakeLists.txt , which breaks configuration with relatively new compiler coupled with non-bleeding-edge CMake (i.e gcc 7 will be unsupported with cmake < ~ KitWare/CMake@8570dc7f64928ec7896197394f089f5ad063c6ca ).

Is there any solution to overcome this (without updating cmake)?

**Comment by sergiud** [comment]
What's your CMake version?

Without removing this line, I don't believe there's a drop-in replacement for this functionality. Besides, `target_compile_features` was introduced with `CMake 3.1` in 2014. You don't need a bleeding-edge CMake.

> i.e gcc 7 will be unsupported with cmake

I don't understand this. Can you elaborate?

**Comment by DmitriyKorchemkin** [comment]
I'm using `cmake` 3.11.2 and `gcc` 7.3  (with error `target_compile_features no known features for CXX compiler "GNU"`); unable to reproduce on a clean install, though.

Supposedly, just my cmake installation is broken.
