### ISSUE TITLE
update_Every_state_iteration documentation has errors

### ISSUE THREAD

**Issue by pbeeson** [ceres-solver/ceres-solver#380]
http://ceres-solver.org/nnls_solving.html#_CPPv2N5ceres6Solver7Options28update_state_every_iterationE

The enumerated list has the same values set to false for both cases.

**Comment by sandwichmaker** [comment]
Thanks for catching this @pbeeson I will fix this shortly.

**Comment by sandwichmaker** [comment]
https://ceres-solver-review.googlesource.com/c/ceres-solver/+/13860 is out for review.
