### ISSUE TITLE
Build failed in android 3.0.1 with the latest version

### ISSUE THREAD

**Issue by wzxchy** [ceres-solver/ceres-solver#382]
I'm trying to build ceres for android with the latest version but have some trouble. I would be appreciate if you could help me solve it.
My Application.mk is as follows:
-----------------------------------------------------
APP_BUILD_SCRIPT := $(call my-dir)/Android.mk
APP_PROJECT_PATH := $(call my-dir)

APP_CPPFLAGS += -fno-exceptions
APP_CPPFLAGS += -fno-rtti
APP_CPPFLAGS += -std=c++11

APP_OPTIM := release

APP_STL := gnustl_static 
APP_ABI := arm64-v8a

-----------------------------------------------------
I run ndk-build and get libceres.a.  However when I use it in androidstudio for a project, I get some "undefined reference":

> FAILED: cmd.exe /C "cd . && C:\Users\wzx\AppData\Local\Android\Sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=aarch64-none-linux-android --gcc-toolchain=C:/Users/wzx/AppData/Local/Android/Sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 --sysroot=C:/Users/wzx/AppData/Local/Android/Sdk/ndk-bundle/sysroot -fPIC -std=c++11 -O3 -DNDEBUG  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot C:/Users/wzx/AppData/Local/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ..\..\..\..\build\intermediates\cmake\debug\obj\arm64-v8a\libnative-lib.so CMakeFiles/native-lib.dir/src/main/cpp/RectsBinPack.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/Types.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/SceneTexture.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/Scene.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/SceneRefine.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -LF:/Code/Android/mpfr-4.0.1/lib  -LF:/Code/Android/gmp-6.1.2/lib -lmpfr -lgmp -llog E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_videostab.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_videoio.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_video.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_superres.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_stitching.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_shape.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_photo.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_objdetect.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_ml.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_imgproc.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_imgcodecs.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_highgui.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_flann.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_features2d.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_core.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_calib3d.a F:/Code/Android/boost_1_65_1_build/out/arm64-v8a/lib/libboost_graph-clang-mt-1_65_1.a F:/Code/Android/ceres-solver-master/obj/local/arm64-v8a/libceres.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_features2d.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_ml.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_highgui.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_videoio.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_imgcodecs.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/3rdparty/libs/arm64-v8a/liblibjpeg.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/3rdparty/libs/arm64-v8a/liblibwebp.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/3rdparty/libs/arm64-v8a/liblibpng.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/3rdparty/libs/arm64-v8a/liblibtiff.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/3rdparty/libs/arm64-v8a/liblibjasper.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/3rdparty/libs/arm64-v8a/libIlmImf.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_flann.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_video.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_imgproc.a E:/opencv_sdk/OpenCV-android-sdk/sdk/native/libs/arm64-v8a/libopencv_core.a -lz -llog E:/opencv_sdk/OpenCV-android-sdk/sdk/native/3rdparty/libs/arm64-v8a/libtbb.a -lc -ldl -lm -latomic -lm "C:/Users/wzx/AppData/Local/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/libgnustl_static.a" && cd ."
  F:/Code/Android/ceres-solver-master/obj/local/arm64-v8a/libceres.a(wall_time.o): In function `ceres::internal::WallTimeInSeconds()':
  F:/Code/Android/ceres-solver-master/jni/../internal/ceres/wall_time.cc:50: undefined reference to `omp_get_wtime'
  F:/Code/Android/ceres-solver-master/jni/../internal/ceres/wall_time.cc:50: undefined reference to `omp_get_wtime'
  F:/Code/Android/ceres-solver-master/jni/../internal/ceres/wall_time.cc:50: undefined reference to `omp_get_wtime'
  F:/Code/Android/ceres-solver-master/jni/../internal/ceres/wall_time.cc:50: undefined reference to `omp_get_wtime'
  F:/Code/Android/ceres-solver-master/obj/local/arm64-v8a/libceres.a(thread_token_provider.o): In function `ceres::internal::ThreadTokenProvider::Acquire()':
  F:/Code/Android/ceres-solver-master/jni/../internal/ceres/thread_token_provider.cc:59: undefined reference to `omp_get_thread_num'
  clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)

Thank you very very much!

**Comment by sandwichmaker** [comment]
looks like you need to link to the openmp runtime.

**Comment by sandwichmaker** [comment]
@wzxchy try using cmake at head instead of the JNI version.

**Comment by sandwichmaker** [comment]
Will close, please re-open if this continues to be a problem.
