### ISSUE TITLE
Why the library for android is so big?

### ISSUE THREAD

**Issue by jackyfriend** [ceres-solver/ceres-solver#385]
Hello, I used the most recent ceres-solver to build the android library, and modified the APP_STL to gnustl_static and with '-std=c++11' and '-DCERES_RESTRICT_SCHUR_SPECIALIZATION'. After built, the static library is up to 140MB. How can I make it smaller? The static library for ios is just 17MB which is so smaller than android.

**Comment by sandwichmaker** [comment]
are you sure you are not building with debugging symbols?

**Comment by jackyfriend** [comment]
@sandwichmaker Thank you for your reply, I' m sure building with the release symbol because in the default ceres-solver/jni folder, the Application.mk is using 'APP_OPTIM := release', and I did not change that.

**Comment by sandwichmaker** [comment]
@alexsmac any ideas?

**Comment by linusmartensson** [comment]
I can't tell why you get that package size, but I had the same issue and found that removing debug symbols using strip reduces the library size by several orders of magnitude:
```
$NDK_DIR/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip -g libceres.so 
```

**Comment by jackyfriend** [comment]
@linusmartensson Thank you for your help. It works very well. Great job.

**Comment by elegracer** [comment]
CMake should build ceres without debugging symbols `if(ANDROID)`, but it seems that the final `libceres.a` is still huge.
