### ISSUE TITLE
Handling NULL permutation from SuiteSparseQR

### ISSUE THREAD

**Issue by paulinus** [ceres-solver/ceres-solver#389]
When computing covariances using SuiteSparse, the method `SuiteSparseQR` is called. One of the outputs of that method is a permutation. 

Ceres checks that this permutation is not NULL
https://github.com/ceres-solver/ceres-solver/blob/1e8e9452d0a7dfaf5697b544810798a58e35443e/internal/ceres/covariance_impl.cc#L654

From the source code of SuiteSparse, it seems that NULL is a valid output that is meant to represent the identity permutation
https://github.com/PetterS/SuiteSparse/blob/27e5a8516464a6ac40bd3fa0e5b46e51b11f4765/SPQR/Include/SuiteSparseQR.hpp#L394

Should I modify Ceres to handle that case instead of checking that it does not happen? or is NULL not a valid output for some other reason?

(asking because i'm seeing this happening sparsely and it is difficult to handle from outside since the check stops the program)

thanks so much for such a great lib!

**Comment by sandwichmaker** [comment]
@paulinus interesting catch. I had not realized that NULL is a valid output. This is definitely a bug. Yes modifying/fixing ceres to not check fail and to deal with correctly would be the way to go.

**Comment by paulinus** [comment]
good, thanks for the quick response. I've submitted a patch for review in gerrit https://ceres-solver-review.googlesource.com/c/ceres-solver/+/13640

**Comment by sandwichmaker** [comment]
merged!
