### ISSUE TITLE
ParallelFor Function Already Defined Error

### ISSUE THREAD

**Issue by oracle3001** [ceres-solver/ceres-solver#391]
Building with the latest version of the code with Visual Studio 2017 + Intel MKL  / TBB on Windows 10, I get the following error. The basis for the windows solution is from https://github.com/tbennun/ceres-windows, which the latest code swapped into the relevant directory. Doing this before, I haven't had any issues compiling.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"void __cdecl ceres::internal::ParallelFor(class ceres::internal::ContextImpl *,int,int,int,class std::function<void __cdecl(int)> const &)" (?ParallelFor@internal@ceres@@YAXPEAVContextImpl@12@HHHAEBV?$function@$$A6AXH@Z@std@@@Z) already defined in parallel_for_nothreads.obj	ceres	D:\sdks\x64\ceres-windows-forked-64bit-vs2017\win\parallel_for_tbb.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"void __cdecl ceres::internal::ParallelFor(class ceres::internal::ContextImpl *,int,int,int,class std::function<void __cdecl(int,int)> const &)" (?ParallelFor@internal@ceres@@YAXPEAVContextImpl@12@HHHAEBV?$function@$$A6AXHH@Z@std@@@Z) already defined in parallel_for_nothreads.obj	ceres	D:\sdks\x64\ceres-windows-forked-64bit-vs2017\win\parallel_for_tbb.obj	1	
```

**Comment by alexsmac** [comment]
This looks odd.  Although [this CL](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/13664) should 'fix' the issue in that the nothreads variant will be #ifdef-ed out, its definition should already be excluded from the build by [these lines](https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/CMakeLists.txt#L33).

If I had to guess, I would suspect that this is a problem in the CMake MSVC generator in that on the first configure by default current Ceres master would be configured with *no* threading backend which would result in parallel_for_nothreads.cc being added to the Ceres target source list, then when you reconfigure with TBB it should be updating the source list to now only include: parallel_for_tbb.cc, and on other OSs that is indeed what happens.

**Comment by oracle3001** [comment]
In the config.h I just have 
`#define CERES_USE_TBB`

If one adds 
`#define CERES_NO_THREADS`

you get a huge number of errors stating 

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1189	#error:  CERES_USE_TBB is mutually exclusive to CERES_USE_OPENMP, CERES_USE_CXX11_THREADS and CERES_NO_THREADS (compiling source file ..\ceres-solver\internal\ceres\blas.cc)	ceres	d:\sdks\x64\ceres-windows-forked-64bit-vs2017_latest\ceres-solver\include\ceres\internal\port.h	43

**Comment by oracle3001** [comment]
I partially misread your post. 

You are correct it is that the msvc generated project I am using is based on an old version of ceres and up until now it is possible to crowbar in update code, but that has now changed such that it is including these dupes.

**Comment by sandwichmaker** [comment]
@oracle3001 can you confirm that this is fixed at head?

**Comment by oracle3001** [comment]
I can confirm it isn't an issue with ceres code and I can now successfully build. 

It is related to outdated solution provided by 

https://github.com/tbennun/ceres-windows,
