### ISSUE TITLE
evaluation_callback_test failing on arm64 ppc64el

### ISSUE THREAD

**Issue by debalance** [ceres-solver/ceres-solver#392]
Hi!
The evaluation_callback_test introduced in 1.14 fails on arm64 and ppc64el:
https://buildd.debian.org/status/fetch.php?pkg=ceres-solver&arch=arm64&ver=1.14.0-1&stamp=1529085054&raw=0
https://buildd.debian.org/status/fetch.php?pkg=ceres-solver&arch=ppc64el&ver=1.14.0-1&stamp=1529082790&raw=0

With 1.13 all tests succeeded on those platforms.

**Comment by sandwichmaker** [comment]
@keir can you take a look please.

**Comment by sandwichmaker** [comment]
@debalance I think this maybe an uninitialized memory error. 

can you try 

https://github.com/ceres-solver/ceres-solver/commit/923fddcd0eabd7902092122b8cdca45800609870

and see if it fixes the problem.

**Comment by debalance** [comment]
That did not make a difference,
see
https://buildd.debian.org/status/fetch.php?pkg=ceres-solver&arch=arm64&ver=1.14.0-2&stamp=1532030431&raw=0
and
https://buildd.debian.org/status/fetch.php?pkg=ceres-solver&arch=ppc64el&ver=1.14.0-2&stamp=1532029756&raw=0

**Comment by sandwichmaker** [comment]
hmm :/ thanks for testing @debalance 

@keir back to you!

**Comment by keir** [comment]
The EvaluationCallback code recently got reworked; is this still happening?

**Comment by debalance** [comment]
I'll have to do test builds on the affected platforms.

**Comment by brawer** [comment]
As of February 2020, Ceres might run into the same problem on Alpine Linux for x86-64, but I’m not 100% sure if it’s really the same bug. See #562 for instructions how to reproduce the failure on a local machine.

**Comment by sandwichmaker** [comment]
This should be fixed at head.
