### ISSUE TITLE
 Cross-compile ceres-solver error

### ISSUE THREAD

**Issue by ZhiyuLiu1993** [ceres-solver/ceres-solver#398]
Hello, I tried to cross-compile ceres-solver，my build system is Ubuntu 16.04, 64bit, host system is armv7,  cross toolchain is arm-linux-gnueabihf-g++-5, 32bit.
but the following error occurred.

**configure output from CMake:**
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc-5
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc-5 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++-5
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected Ceres version: 1.13.0 from /home/lzy/google_carto_ws/src/ceres-solver/include/ceres/version.h
-- No preference for use of exported Eigen CMake configuration set, and no hints for include directory provided. Defaulting to preferring an installed/exported Eigen CMake configuration if available.
-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found Eigen: /usr/include/eigen3 (found version "3.2.92")
-- Found Eigen version 3.2.92: /usr/include/eigen3

===============================================================
Disabling the use of Eigen as a sparse linear algebra library.
This does not affect the covariance estimation algorithm
which can still use the EIGEN_SPARSE_QR algorithm.

-- Found LAPACK library: /home/lzy/car_cc/lib/liblapack.a;/usr/arm-linux-gnueabihf/lib/libgfortran.so.3
-- Found BLAS library: /home/lzy/car_cc/lib/libblas.a
-- Found AMD headers in: /home/lzy/car_cc/include
-- Found AMD library: /home/lzy/car_cc/lib/libamd.a
-- Found CAMD headers in: /home/lzy/car_cc/include
-- Found CAMD library: /home/lzy/car_cc/lib/libcamd.a
-- Found COLAMD headers in: /home/lzy/car_cc/include
-- Found COLAMD library: /home/lzy/car_cc/lib/libcolamd.a
-- Found CCOLAMD headers in: /home/lzy/car_cc/include
-- Found CCOLAMD library: /home/lzy/car_cc/lib/libccolamd.a
-- Found CHOLMOD headers in: /home/lzy/car_cc/include
-- Found CHOLMOD library: /home/lzy/car_cc/lib/libcholmod.a
-- Found SUITESPARSEQR headers in: /home/lzy/car_cc/include
-- Found SUITESPARSEQR library: /home/lzy/car_cc/lib/libspqr.a
-- Found TBB library: /home/lzy/car_cc/lib/libtbb.so
-- Found Intel Thread Building Blocks (TBB) library: /home/lzy/car_cc/lib/libtbb.so, assuming SuiteSparseQR was compiled with TBB.
-- Found TBB_MALLOC library: /home/lzy/car_cc/lib/libtbbmalloc.so
-- Found Intel Thread Building Blocks (TBB) Malloc library: /home/lzy/car_cc/lib/libtbbmalloc.so
-- Found SUITESPARSE_CONFIG headers in: /home/lzy/car_cc/include
-- Found SUITESPARSE_CONFIG library: /home/lzy/car_cc/lib/libsuitesparseconfig.a
-- Found LIBRT library: /usr/arm-linux-gnueabihf/lib/librt.so
-- Adding librt: /usr/arm-linux-gnueabihf/lib/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Found METIS library: /home/lzy/car_cc/lib/libmetis.a
-- Found SuiteSparse: TRUE (found version "4.4.6")
-- Found SuiteSparse 4.4.6, building with SuiteSparse.
-- Found CXSparse: /home/lzy/car_cc/include (found version "3.1.4")
-- Found CXSparse version: 3.1.4, building with CXSparse.
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: /home/lzy/car_cc/lib/cmake/gflags
-- Detected broken gflags install in: /home/lzy/car_cc/lib/cmake/gflags, version: 2.1.2 <= 2.1.2 which defines gflags_LIBRARIES = gflags which is not an imported CMake target, see: gflags/gflags#110. Attempting to fix by detecting correct gflags target.
-- Found valid gflags target: gflags-static, updating gflags_LIBRARIES.
-- Detected gflags version: 2.1.2
-- Found Gflags: /home/lzy/car_cc/include
-- Found Google Flags header in: /home/lzy/car_cc/include, in namespace: google
-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
-- Found Glog: /home/lzy/car_cc/include
-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
-- Building with OpenMP.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE
-- Performing Test COMPILER_HAS_CXX11_FLAG
-- Performing Test COMPILER_HAS_CXX11_FLAG - Success
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - not found
-- Looking for C++ include tr1/unordered_map
-- Looking for C++ include tr1/unordered_map - found
-- Found tr1/unordered_map/set in std::tr1 namespace.
-- Looking for C++ include memory
-- Looking for C++ include memory - found
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Failed
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE - Failed
-- Looking for C++ include tr1/memory
-- Looking for C++ include tr1/memory - found
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER
-- Performing Test HAVE_SHARED_PTR_IN_TR1_NAMESPACE_FROM_TR1_MEMORY_HEADER - Success
-- Found shared_ptr in std::tr1 namespace using <tr1/memory> header.
-- Building Ceres as a static library.
-- No build type specified; defaulting to CMAKE_BUILD_TYPE=Release.
-- Creating configured Ceres config.h output directory: /home/lzy/google_carto_ws/src/ceres-solver/build/config/ceres/internal
-- Enabling CERES_USE_OPENMP in Ceres config.h
-- Enabling CERES_HAVE_PTHREAD in Ceres config.h
-- Enabling CERES_HAVE_RWLOCK in Ceres config.h
-- Enabling CERES_TR1_UNORDERED_MAP in Ceres config.h
-- Enabling CERES_TR1_MEMORY_HEADER in Ceres config.h
-- Enabling CERES_TR1_SHARED_PTR in Ceres config.h
-- Build the examples.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lzy/google_carto_ws/src/ceres-solver/build

**It is the output:**
[ 75%] Linking CXX static library ../../lib/libceres.a
cd /home/lzy/google_carto_ws/src/ceres-solver/build/internal/ceres && /usr/bin/cmake -P CMakeFiles/ceres.dir/cmake_clean_target.cmake
cd /home/lzy/google_carto_ws/src/ceres-solver/build/internal/ceres && /usr/bin/cmake -E cmake_link_script CMakeFiles/ceres.dir/link.txt --verbose=1
/usr/bin/ar qc ../../lib/libceres.a CMakeFiles/ceres.dir/array_utils.cc.o CMakeFiles/ceres.dir/blas.cc.o CMakeFiles/ceres.dir/block_evaluate_preparer.cc.o CMakeFiles/ceres.dir/block_jacobi_preconditioner.cc.o CMakeFiles/ceres.dir/block_jacobian_writer.cc.o CMakeFiles/ceres.dir/block_random_access_dense_matrix.cc.o CMakeFiles/ceres.dir/block_random_access_diagonal_matrix.cc.o CMakeFiles/ceres.dir/block_random_access_matrix.cc.o CMakeFiles/ceres.dir/block_random_access_sparse_matrix.cc.o CMakeFiles/ceres.dir/block_sparse_matrix.cc.o CMakeFiles/ceres.dir/block_structure.cc.o CMakeFiles/ceres.dir/c_api.cc.o CMakeFiles/ceres.dir/canonical_views_clustering.cc.o CMakeFiles/ceres.dir/cgnr_solver.cc.o CMakeFiles/ceres.dir/callbacks.cc.o CMakeFiles/ceres.dir/compressed_col_sparse_matrix_utils.cc.o CMakeFiles/ceres.dir/compressed_row_jacobian_writer.cc.o CMakeFiles/ceres.dir/compressed_row_sparse_matrix.cc.o CMakeFiles/ceres.dir/conditioned_cost_function.cc.o CMakeFiles/ceres.dir/conjugate_gradients_solver.cc.o CMakeFiles/ceres.dir/coordinate_descent_minimizer.cc.o CMakeFiles/ceres.dir/corrector.cc.o CMakeFiles/ceres.dir/covariance.cc.o CMakeFiles/ceres.dir/covariance_impl.cc.o CMakeFiles/ceres.dir/cxsparse.cc.o CMakeFiles/ceres.dir/dense_normal_cholesky_solver.cc.o CMakeFiles/ceres.dir/dense_qr_solver.cc.o CMakeFiles/ceres.dir/dense_sparse_matrix.cc.o CMakeFiles/ceres.dir/detect_structure.cc.o CMakeFiles/ceres.dir/dogleg_strategy.cc.o CMakeFiles/ceres.dir/dynamic_compressed_row_jacobian_writer.cc.o CMakeFiles/ceres.dir/dynamic_compressed_row_sparse_matrix.cc.o CMakeFiles/ceres.dir/dynamic_sparse_normal_cholesky_solver.cc.o CMakeFiles/ceres.dir/evaluator.cc.o CMakeFiles/ceres.dir/eigensparse.cc.o CMakeFiles/ceres.dir/file.cc.o CMakeFiles/ceres.dir/function_sample.cc.o CMakeFiles/ceres.dir/gradient_checker.cc.o CMakeFiles/ceres.dir/gradient_checking_cost_function.cc.o CMakeFiles/ceres.dir/gradient_problem.cc.o CMakeFiles/ceres.dir/gradient_problem_solver.cc.o CMakeFiles/ceres.dir/implicit_schur_complement.cc.o CMakeFiles/ceres.dir/inner_product_computer.cc.o CMakeFiles/ceres.dir/is_close.cc.o CMakeFiles/ceres.dir/iterative_schur_complement_solver.cc.o CMakeFiles/ceres.dir/levenberg_marquardt_strategy.cc.o CMakeFiles/ceres.dir/lapack.cc.o CMakeFiles/ceres.dir/line_search.cc.o CMakeFiles/ceres.dir/line_search_direction.cc.o CMakeFiles/ceres.dir/line_search_minimizer.cc.o CMakeFiles/ceres.dir/line_search_preprocessor.cc.o CMakeFiles/ceres.dir/linear_least_squares_problems.cc.o CMakeFiles/ceres.dir/linear_operator.cc.o CMakeFiles/ceres.dir/linear_solver.cc.o CMakeFiles/ceres.dir/local_parameterization.cc.o CMakeFiles/ceres.dir/loss_function.cc.o CMakeFiles/ceres.dir/low_rank_inverse_hessian.cc.o CMakeFiles/ceres.dir/minimizer.cc.o CMakeFiles/ceres.dir/normal_prior.cc.o CMakeFiles/ceres.dir/parameter_block_ordering.cc.o CMakeFiles/ceres.dir/partitioned_matrix_view.cc.o CMakeFiles/ceres.dir/polynomial.cc.o CMakeFiles/ceres.dir/preconditioner.cc.o CMakeFiles/ceres.dir/preprocessor.cc.o CMakeFiles/ceres.dir/problem.cc.o CMakeFiles/ceres.dir/problem_impl.cc.o CMakeFiles/ceres.dir/program.cc.o CMakeFiles/ceres.dir/reorder_program.cc.o CMakeFiles/ceres.dir/residual_block.cc.o CMakeFiles/ceres.dir/residual_block_utils.cc.o CMakeFiles/ceres.dir/schur_complement_solver.cc.o CMakeFiles/ceres.dir/schur_eliminator.cc.o CMakeFiles/ceres.dir/schur_jacobi_preconditioner.cc.o CMakeFiles/ceres.dir/schur_templates.cc.o CMakeFiles/ceres.dir/scratch_evaluate_preparer.cc.o CMakeFiles/ceres.dir/single_linkage_clustering.cc.o CMakeFiles/ceres.dir/solver.cc.o CMakeFiles/ceres.dir/solver_utils.cc.o CMakeFiles/ceres.dir/sparse_matrix.cc.o CMakeFiles/ceres.dir/sparse_cholesky.cc.o CMakeFiles/ceres.dir/sparse_normal_cholesky_solver.cc.o CMakeFiles/ceres.dir/split.cc.o CMakeFiles/ceres.dir/stringprintf.cc.o CMakeFiles/ceres.dir/suitesparse.cc.o CMakeFiles/ceres.dir/triplet_sparse_matrix.cc.o CMakeFiles/ceres.dir/trust_region_preprocessor.cc.o CMakeFiles/ceres.dir/trust_region_minimizer.cc.o CMakeFiles/ceres.dir/trust_region_step_evaluator.cc.o CMakeFiles/ceres.dir/trust_region_strategy.cc.o CMakeFiles/ceres.dir/types.cc.o CMakeFiles/ceres.dir/visibility.cc.o CMakeFiles/ceres.dir/visibility_based_preconditioner.cc.o CMakeFiles/ceres.dir/wall_time.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_2_2_3.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_2_2_3.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_2_2_4.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_2_4_3.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_2_3_3.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_2_2_2.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_d_d_d.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_2_4_3.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_4_4_d.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_2_d_d.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_2_3_d.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_2_4_8.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_4_4_2.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_2_4_d.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_4_4_2.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_4_4_4.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_2_3_6.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_2_3_3.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_2_2_2.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_2_4_9.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_4_4_4.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_2_3_6.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_2_4_9.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_2_3_9.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_2_2_4.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_2_3_d.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_2_2_d.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_2_4_8.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_2_3_4.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_d_d_d.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_2_4_4.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_2_2_d.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_2_4_4.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_2_3_4.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_2_d_d.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_4_4_3.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_4_4_d.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_2_4_d.cc.o CMakeFiles/ceres.dir/generated/schur_eliminator_2_3_9.cc.o CMakeFiles/ceres.dir/generated/partitioned_matrix_view_4_4_3.cc.o
/usr/bin/ranlib ../../lib/libceres.a
make[2]: Leaving directory '/home/lzy/google_carto_ws/src/ceres-solver/build'
[ 75%] Built target ceres
make -f examples/CMakeFiles/simple_bundle_adjuster.dir/build.make examples/CMakeFiles/simple_bundle_adjuster.dir/depend
make[2]: Entering directory '/home/lzy/google_carto_ws/src/ceres-solver/build'
cd /home/lzy/google_carto_ws/src/ceres-solver/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/lzy/google_carto_ws/src/ceres-solver /home/lzy/google_carto_ws/src/ceres-solver/examples /home/lzy/google_carto_ws/src/ceres-solver/build /home/lzy/google_carto_ws/src/ceres-solver/build/examples /home/lzy/google_carto_ws/src/ceres-solver/build/examples/CMakeFiles/simple_bundle_adjuster.dir/DependInfo.cmake --color=
Dependee "/home/lzy/google_carto_ws/src/ceres-solver/build/examples/CMakeFiles/simple_bundle_adjuster.dir/DependInfo.cmake" is newer than depender "/home/lzy/google_carto_ws/src/ceres-solver/build/examples/CMakeFiles/simple_bundle_adjuster.dir/depend.internal".
Dependee "/home/lzy/google_carto_ws/src/ceres-solver/build/examples/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/lzy/google_carto_ws/src/ceres-solver/build/examples/CMakeFiles/simple_bundle_adjuster.dir/depend.internal".
Scanning dependencies of target simple_bundle_adjuster
make[2]: Leaving directory '/home/lzy/google_carto_ws/src/ceres-solver/build'
make -f examples/CMakeFiles/simple_bundle_adjuster.dir/build.make examples/CMakeFiles/simple_bundle_adjuster.dir/build
make[2]: Entering directory '/home/lzy/google_carto_ws/src/ceres-solver/build'
[ 76%] Building CXX object examples/CMakeFiles/simple_bundle_adjuster.dir/simple_bundle_adjuster.cc.o
cd /home/lzy/google_carto_ws/src/ceres-solver/build/examples && /usr/bin/arm-linux-gnueabihf-g++-5 -DCERES_GFLAGS_NAMESPACE=google -DEIGEN_MPL2_ONLY -D_GLIBCXX_USE_CXX11_ABI=0 -I/home/lzy/google_carto_ws/src/ceres-solver/build/config -I/home/lzy/google_carto_ws/src/ceres-solver/include -I/home/lzy/google_carto_ws/src/ceres-solver/internal -I/home/lzy/google_carto_ws/src/ceres-solver/internal/ceres -I/home/lzy/car_cc/include -isystem /usr/include/eigen3 -fopenmp -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -O3 -DNDEBUG -o CMakeFiles/simple_bundle_adjuster.dir/simple_bundle_adjuster.cc.o -c /home/lzy/google_carto_ws/src/ceres-solver/examples/simple_bundle_adjuster.cc
[ 77%] Linking CXX executable ../bin/simple_bundle_adjuster
cd /home/lzy/google_carto_ws/src/ceres-solver/build/examples && /usr/bin/cmake -E cmake_link_script CMakeFiles/simple_bundle_adjuster.dir/link.txt --verbose=1
/usr/bin/arm-linux-gnueabihf-g++-5 -fopenmp -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -O3 -DNDEBUG CMakeFiles/simple_bundle_adjuster.dir/simple_bundle_adjuster.cc.o -o ../bin/simple_bundle_adjuster -rdynamic ../lib/libceres.a /home/lzy/car_cc/lib/libglog.a /home/lzy/car_cc/lib/libgflags.a -lpthread /home/lzy/car_cc/lib/libspqr.a /home/lzy/car_cc/lib/libtbb.so /home/lzy/car_cc/lib/libtbbmalloc.so /home/lzy/car_cc/lib/libcholmod.a /home/lzy/car_cc/lib/libccolamd.a /home/lzy/car_cc/lib/libcamd.a /home/lzy/car_cc/lib/libcolamd.a /home/lzy/car_cc/lib/libamd.a /home/lzy/car_cc/lib/liblapack.a /usr/arm-linux-gnueabihf/lib/libgfortran.so.3 /home/lzy/car_cc/lib/libblas.a /home/lzy/car_cc/lib/libsuitesparseconfig.a -lrt /home/lzy/car_cc/lib/libmetis.a /home/lzy/car_cc/lib/libcxsparse.a /home/lzy/car_cc/lib/liblapack.a /usr/arm-linux-gnueabihf/lib/libgfortran.so.3 /home/lzy/car_cc/lib/libblas.a /home/lzy/car_cc/lib/libsuitesparseconfig.a -lrt /home/lzy/car_cc/lib/libmetis.a /home/lzy/car_cc/lib/libcxsparse.a -lgomp -Wl,-rpath,/home/lzy/car_cc/lib
../lib/libceres.a(parameter_block_ordering.cc.o): In function std::string* google::MakeCheckOpString<unsigned int, int>(unsigned int const&, int const&, char const*)': parameter_block_ordering.cc:(.text._ZN6google17MakeCheckOpStringIjiEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIjiEEPSsRKT_RKT0_PKc]+0x34): undefined reference togoogle::base::CheckOpMessageBuilder::NewString()'
../lib/libceres.a(reorder_program.cc.o): In function std::string* google::MakeCheckOpString<int, unsigned int>(int const&, unsigned int const&, char const*)': reorder_program.cc:(.text._ZN6google17MakeCheckOpStringIijEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIijEEPSsRKT_RKT0_PKc]+0x34): undefined reference togoogle::base::CheckOpMessageBuilder::NewString()'
../lib/libceres.a(schur_complement_solver.cc.o): In function std::string* google::MakeCheckOpString<ceres::PreconditionerType, ceres::PreconditionerType>(ceres::PreconditionerType const&, ceres::PreconditionerType const&, char const*)': schur_complement_solver.cc:(.text._ZN6google17MakeCheckOpStringIN5ceres18PreconditionerTypeES2_EEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIN5ceres18PreconditionerTypeES2_EEPSsRKT_RKT0_PKc]+0x34): undefined reference togoogle::base::CheckOpMessageBuilder::NewString()'
../lib/libceres.a(problem_impl.cc.o): In function std::string* google::MakeCheckOpString<int, int>(int const&, int const&, char const*)': problem_impl.cc:(.text._ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc]+0x34): undefined reference togoogle::base::CheckOpMessageBuilder::NewString()'
../lib/libceres.a(problem_impl.cc.o): In function std::string* google::MakeCheckOpString<unsigned int, unsigned int>(unsigned int const&, unsigned int const&, char const*)': problem_impl.cc:(.text._ZN6google17MakeCheckOpStringIjjEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIjjEEPSsRKT_RKT0_PKc]+0x34): undefined reference togoogle::base::CheckOpMessageBuilder::NewString()'
../lib/libceres.a(problem_impl.cc.o):problem_impl.cc:(.text._ZN6google17MakeCheckOpStringIPN5ceres8internal14ParameterBlockES4_EEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIPN5ceres8internal14ParameterBlockES4_EEPSsRKT_RKT0_PKc]+0x34): more undefined references to `google::base::CheckOpMessageBuilder::NewString()' follow
collect2: error: ld returned 1 exit status
examples/CMakeFiles/simple_bundle_adjuster.dir/build.make:119: recipe for target 'bin/simple_bundle_adjuster' failed
make[2]: *** [bin/simple_bundle_adjuster] Error 1
make[2]: Leaving directory '/home/lzy/google_carto_ws/src/ceres-solver/build'
CMakeFiles/Makefile2:211: recipe for target 'examples/CMakeFiles/simple_bundle_adjuster.dir/all' failed
make[1]: *** [examples/CMakeFiles/simple_bundle_adjuster.dir/all] Error 2
make[1]: Leaving directory '/home/lzy/google_carto_ws/src/ceres-solver/build'
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

And the contents of CeresTargets.cmake:

Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------

Generated CMake target import file.

#----------------------------------------------------------------

Commands may need to know the format version.

set(CMAKE_IMPORT_FILE_VERSION 1)

Protect against multiple inclusion, which would fail when already imported targets are added once more.

set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget ceres)
list(APPEND _expectedTargets ${_expectedTarget})
if(NOT TARGET ${_expectedTarget})
list(APPEND _targetsNotDefined ${_expectedTarget})
endif()
if(TARGET ${_expectedTarget})
list(APPEND _targetsDefined ${_expectedTarget})
endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)

Compute the installation prefix relative to this file.

get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
set(_IMPORT_PREFIX "")
endif()

Create imported target ceres

add_library(ceres STATIC IMPORTED)

Load information for each installed configuration.

get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/CeresTargets-*.cmake")
foreach(f ${CONFIG_FILES})
include(${f})
endforeach()

Cleanup temporary variables.

set(_IMPORT_PREFIX)

Loop over all imported files and verify that they actually exist

foreach(target ${_IMPORT_CHECK_TARGETS} )
foreach(file ${IMPORT_CHECK_FILES_FOR${target}} )
if(NOT EXISTS "${file}" )
message(FATAL_ERROR "The imported target "${target}" references the file
"${file}"
but this file does not exist. Possible reasons include:

The file was deleted, renamed, or moved to another location.
An install or uninstall procedure did not complete successfully.
The installation package was faulty and contained
"${CMAKE_CURRENT_LIST_FILE}"
but not all the files it references.
")
endif()
endforeach()
unset(IMPORT_CHECK_FILES_FOR${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)
This file does not depend on other imported targets which have

been exported from the same project but in a separate export set.

Commands beyond this point should not need to know the version.

set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)

**Comment by alexsmac** [comment]
I don't see anything wrong with the link line:

```
CMakeFiles/simple_bundle_adjuster.dir/simple_bundle_adjuster.cc.o -o ../bin/simple_bundle_adjuster -rdynamic ../lib/libceres.a /home/lzy/car_cc/lib/libglog.a /home/lzy/car_cc/lib/libgflags.a -lpthread /home/lzy/car_cc/lib/libspqr.a /home/lzy/car_cc/lib/libtbb.so /home/lzy/car_cc/lib/libtbbmalloc.so /home/lzy/car_cc/lib/libcholmod.a /home/lzy/car_cc/lib/libccolamd.a /home/lzy/car_cc/lib/libcamd.a /home/lzy/car_cc/lib/libcolamd.a /home/lzy/car_cc/lib/libamd.a /home/lzy/car_cc/lib/liblapack.a /usr/arm-linux-gnueabihf/lib/libgfortran.so.3 /home/lzy/car_cc/lib/libblas.a /home/lzy/car_cc/lib/libsuitesparseconfig.a -lrt /home/lzy/car_cc/lib/libmetis.a /home/lzy/car_cc/lib/libcxsparse.a /home/lzy/car_cc/lib/liblapack.a /usr/arm-linux-gnueabihf/lib/libgfortran.so.3 /home/lzy/car_cc/lib/libblas.a /home/lzy/car_cc/lib/libsuitesparseconfig.a -lrt /home/lzy/car_cc/lib/libmetis.a /home/lzy/car_cc/lib/libcxsparse.a -lgomp -Wl,-rpath,/home/lzy/car_cc/lib
```

That includes libceres.a first, then libglog.a, so when the symbols are undefined after it parses libceres.a they should be resolved when the linker parses libglog.a.  Which of the examples/tests fail to build, is it just simple_bundle_adjuster ?

**Comment by ZhiyuLiu1993** [comment]
No, Other examples such as nist have the same error.  I am trying to use the ceres library, still the same error when linking.

**Comment by alexsmac** [comment]
I can't replicate any issues with Ceres when it and its dependencies are all statically built without cross-compiling so I think that this is probably an artefact of your cross-compilation setup.

Are you sure that the glog build you are trying to link against (`/home/lzy/car_cc/lib/libglog.a`) was also cross-compiled?  You can verify the architecture with: `objdump -f <PATH_TO_LIBRARY>`.

**Comment by ZhiyuLiu1993** [comment]
Yes，I tried using the glog library on the arm to include this function, it's OK. I commented on the logging.h file 672 lines of this NewString function,  just return nullptr,  because I didn't see using this function.  The library can now link normally but I have not tested.

**Comment by JinglinZhang** [comment]
Hi Zhiyu，想请教一下你们是如何交叉编译Suitesparse、lapack、BLAS的，可以在不带Fortran的情况下编译ceres+Suitesparse吗
@ZhiyuLiu1993
