### ISSUE TITLE
Ceres solver mac which path is needed to be added in matlab environment

### ISSUE THREAD

**Issue by krishnakumarrs** [ceres-solver/ceres-solver#404]
I have installed ceres, but when i compile matlab mex file which require

 mex ceres****.cpp /usr/local/lib/libceres_shared.so /usr/local/lib/libglog.so -I/usr/include/eigen3;
   mex ceres****.cpp /usr/local/lib/libceres_shared.so /usr/local/lib/libglog.so -I/usr/include/eigen3;

it shows me error that
fatal error: 'ceres/ceres.h' file not found
#include "ceres/ceres.h"
         ^~~~~~~~~~~~~~~
1 error generated.

   mex ceres****.cpp /usr/local/lib/libceres_shared.so /usr/local/lib/libglog.so
   -I/usr/include/eigen3; 

I cannot able to find .so files in the ceres build folder.
Please need help with this issue.
thanks

**Comment by alexsmac** [comment]
You have several issues here:

1) The library name for Ceres (even when built as a shared library) is libceres.so/dylib
2) You should specify the directories containing the external libraries to be linked against with -L<PATH> then the libraries themselves with -l<NAME> (note: lower-case 'L', not capital 'i').  This means that your MEX command should be something like:

`mex -I/usr/local/include -I/usr/include/eigen3 -L/usr/local/lib -lglog -lceres <PATH_TO_MEX_SOURCE_CPP_FILE>`

3) The include path for Ceres (to be added via -I<PATH>) depends upon the installation path, assuming that you installed Ceres to /usr/local, then it would be '/usr/local/include' - you can verify this is correct by checking that /usr/local/include/ceres/ceres.h exists.

**Comment by krishnakumarrs** [comment]
Thanks for the solution it worked.
