### ISSUE TITLE
Ceres headers cannot stand alone

### ISSUE THREAD

**Issue by osadowskyphd** [ceres-solver/ceres-solver#410]
in an attempt to get finer-grain control over the inclusion of ceres headers, I found out that some of them do not stand alone, and generate compiler errors if they are included not from ceres.h.

Some examples:
evaluation_callback.h
loss_function.h

In addition, it looks like somewhere in the chain of ceres.h it includes iostream.  Although this is not necessarily a bad thing, I think it's better if this dependency is not part of the headers.

**Comment by sandwichmaker** [comment]
Thanks @osadowskyphd this is definitely a bug, I will take a look.

**Comment by sandwichmaker** [comment]
As for the iostream header, jet.h includes it because it is needed to define operator<< for Jets. That is likely going to remain the same.

**Comment by sandwichmaker** [comment]
I do not see loss_function.h having any problems. evaluation_callback.h was missing an include. which I will fix shortly.
can you share the error you are getting?

**Comment by sandwichmaker** [comment]
I am going to close this, please feel free to re-open if you find any other headers which are problematic.

**Comment by osadowskyphd** [comment]
I think that I mistook thr error of something else with this include.  It's
just evaluation_callback, it seems.

בתאריך יום ד׳, 8 באוג׳ 2018, 16:54, מאת Sameer Agarwal ‏<
notifications@github.com>:

**Comment by osadowskyphd** [comment]
I am wondering if ostream alone is not sufficient for this.

As i wrote, I tried to use finer grain includes. Then std::cout was no
longer recognized. But for  operator << std::ostrem should suffice.

בתאריך יום ד׳, 8 באוג׳ 2018, 14:57, מאת Sameer Agarwal ‏<
notifications@github.com>:
