### ISSUE TITLE
Include <ostream> instead of <iostream>

### ISSUE THREAD

**Issue by osadowskyphd** [ceres-solver/ceres-solver#411]
This is a followup to #410 - sorry I could not figure out how to reopen the issue.

>> As for the iostream header, jet.h includes it because it is needed to define operator<< for Jets. That is likely going to remain the same.

> I am wondering if ostream alone is not sufficient for this.
> As i wrote, I tried to use finer grain includes. Then std::cout was no longer recognized. But for  operator << std::ostrem should suffice.

**Comment by sandwichmaker** [comment]
good point. actially iosfwd suffices.

**Comment by sandwichmaker** [comment]
@keir had some opinions on this.

**Comment by sandwichmaker** [comment]
@keir ping?

**Comment by sandwichmaker** [comment]
This is likely not going to happen.
