### ISSUE TITLE
32-bit integers used in block_sparse_matrix.cc

### ISSUE THREAD

**Issue by TobiasNFrames** [ceres-solver/ceres-solver#412]
Hi!

I was asked on your Google Group to file a bug related to the fact that signed integers are used throughout the code of block_sparse_matrix.cc for types that should be unsigned. I came across this issue due to an integer overflow in num_nonzeros_ that would lead to an assertion triggering as the condition num_non_zeros_  >= 0 doesn't apply any more.

When looking at this class it's in fact the case that signed types are used for storing, calculating with, looping over and returning things like num_nonzeros_, num_rows_, num_cols_, min_col_block_size, etc. It would definitely make sense to switch to unsigned data types for these kind of variables.

Thanks a lot for your consideration!
Tobias

**Comment by alexsmac** [comment]
The use of signed integers is deliberate, as explained in the [Google Style Guide here](https://google.github.io/styleguide/cppguide.html#Integer_Types), use of unsigned integers is bad practice outside of very limited cases (bitfields and modular arithmetic).  The core issue here is really the length of the integer type used rather than whether it is signed, so I have updated the title accordingly.

**Comment by NikolausDemmel** [comment]
Ceres crashed on me with this assertion:

```
F0919 03:10:55.493451 41816 block_sparse_matrix.cc:79] Check failed: num_nonzeros_ >= 0 (-2114449544 vs. 0) 
*** Check failure stack trace: ***
    @     0x7fc1574480cd  google::LogMessage::Fail()
    @     0x7fc157449f33  google::LogMessage::SendToLog()
    @     0x7fc157447c28  google::LogMessage::Flush()
    @     0x7fc15744a999  google::LogMessageFatal::~LogMessageFatal()
    @           0x70ce9a  ceres::internal::BlockSparseMatrix::BlockSparseMatrix()
    @           0x7336d9  ceres::internal::BlockJacobianWriter::CreateJacobian()
    @           0x72a867  ceres::internal::TrustRegionPreprocessor::Preprocess()
    @           0x7036f2  ceres::Solver::Solve()
    @           0x704b5d  ceres::Solve()
[...]
    @           0x44f54b  main
    @     0x7fc154ed6b97  __libc_start_main
    @           0x45459a  _start
```

Looks like I might be running into this case, i.e. overflow of the counters. I have a hard time debugging, since the problem is too big for my dev machine (memory). But if I do run into this bug, the conclusion would be, that my problem is too big for ceres to handle without updating these (and possibly other) counters to 64bit, right?

**Comment by sandwichmaker** [comment]
I am working on this, but it requires some subtle changes to ceres and very careful testing due to lax narrowing rules in c++.

https://ceres-solver-review.googlesource.com/c/ceres-solver/+/14861

**Comment by seth-planet** [comment]
Thanks for looking at this, I just found the problem pop up in my own Ceres work.

**Comment by sandwichmaker** [comment]
I have been exploring solutions to this, and fixing it for real requires a very large change to ceres internals and it is not clear if the resulting code churn and performance hit -- memory increase in indexing is worth it.

**Comment by sandwichmaker** [comment]
I spent a lot of time working on this, turns out that this is not a small change and correctly making this change requires a very large internal change to ceres. Which will also affect the amount of memory used and the way SuiteSparse is called. As a result we have decided not to act on this.

**Comment by MrMabulous** [comment]
I'm running into the same problem.

It would be good to support long ints, not just for this, but also in order to use GPU acceleration with SuiteSparse (SuiteSpare can use GPU acceleration for cholmod, but only for the long-int version of the calls)

**Comment by shapovalov** [comment]
@sandwichmaker Does it make sense to at least convert these ints to unsigned types: https://github.com/ceres-solver/ceres-solver/blob/d3201798ea27ee6402114d0b0aca2f2cb7e652b7/internal/ceres/block_sparse_matrix.h#L141 ?

It will allow 2x bigger problems.

**Comment by sandwichmaker** [comment]
Roman,
That can be done but we used signed integers everywhere and it would a
careful change to make sure that we are not introducing errors. I am happy
to consider a patch, but it's a nontrivial amount of work.

**Comment by NikolausDemmel** [comment]
If this is changed to unsigned, IMHO it would be important to ensure it still catches overflow and not silently uses wrong overflowing indices.

**Comment by wshur-thordrive** [comment]
32-bit is too small to solve real-world large-scale problems. An upgrade to 64-bit indices is desperately needed.

**Comment by bpoebiapl** [comment]
32-bit is too small to solve real-world large-scale problems. An upgrade to 64-bit indices is desperately needed.

**Comment by deckeogh** [comment]
Many thanks for your work on this project and I see that this is not an easy feature to implement...
I am running into the overflow issue on num_nonzeros_ when processing large datasets using photogrammetry.
This would be an amazing upgrade.

**Comment by dllu** [comment]
It should definitely be upgraded to 64 bit indices. And this easy (though tedious) change of changing all the `int` to `int64_t` should have been done a long time ago. The longer you wait, the more annoying and harder it is. 

Real-world problems routinely have billions of elements.

Until this is fixed, maybe the maintainers should update the first sentence on https://ceres-solver.org

```diff
-Ceres Solver is an open source C++ library for modeling and solving large, complicated optimization problems.
+Ceres Solver is an open source C++ library for modeling and solving medium-sized, complicated optimization problems.
```

**Comment by sandwichmaker** [comment]
@dllu your comment is rude and disrespectful.

Ceres Solver is open source software.  If you think this change is so easy, please send me a well tested pull request, instead of telling us how we should or should not talk about the software.

**Comment by sandwichmaker** [comment]
Thanks @dllu, work and life kept me away from substantial ceres work lately, I hope to get back to it. In the interim patches are welcome. The subtlety here is that we most likely want to keep ceres running well on 32bit systems too, which requires introducing a macro and careful testing to make sure we are not mixing types and overflowing.  It will also require changes to how we call suitesparse since its interface/function names for int64 indexed matrices is different from int32 indexed matrices.

**Comment by dllu** [comment]
> Keep ceres running well on 32bit systems

I think we can use `std::ptrdiff_t` by default, which will be 32 bit or 64 bit depending on system. This is also the [default in Eigen](https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/util/Macros.h#L34), where they have

```cpp
#ifndef EIGEN_DEFAULT_DENSE_INDEX_TYPE
#define EIGEN_DEFAULT_DENSE_INDEX_TYPE std::ptrdiff_t
#endif
```

and

```cpp
typedef EIGEN_DEFAULT_DENSE_INDEX_TYPE Index;
```

The macro allows the user to override it at compile time if needed.

> require changes to how we call suitesparse since its interface/function names for int64 indexed matrices is different from int32 indexed matrices

One solution would be to wrap each call with templated functions specialized for 64 bit and 32 bit integers. A trivial example is shown here:

```cpp
#include <iostream>

using index_t = std::ptrdiff_t;

void ptrdiff_length(int32_t i) { std::cerr << "32 bit: " << i << std::endl; }

void ptrdiff_length(int64_t i) { std::cerr << "64 bit: " << i << std::endl; }

int main() {
    const index_t asdf = 0;
    ptrdiff_length(asdf);
}
```

You are quite right, of course, that the challenge lies in careful testing to make sure we are not mixing types and overflowing. So this change will definitely take lots of work.

**Comment by sandwichmaker** [comment]
The maintainers and I talked, and we have a plan. https://github.com/ceres-solver/ceres-solver/issues/960
