### ISSUE TITLE
Ceres Jets are hard to use together with numeric literals

### ISSUE THREAD

**Issue by allo-** [ceres-solver/ceres-solver#414]
The operators of the ``Jet`` class are complicated to use with standard numeric literals. For example a ``Jet<double, 4> x`` does not work with

    T x;
   if( x == 0) { ... }

but you need to use

    T x;
    if(x == static_cast<T>(0)) { ... }

This is especially a problem, when you use types like ``std::complex<T>``, which are evaluated as ``std::complex<Jet<double, 4>>``. E.g. the MSVC stdlib contains code in the ``std::complex::_Div`` method like

    else if ((_Rightimag < 0 ? -_Rightimag : +_Rightimag) // line 665

which fails for ``Jet<double, 4>``:

```
error C2678: binary '<': no operator found which takes a left-hand operand of type 'ceres::Jet<T,4>' (or there is no acceptable conversion)
          with
          [
              T=double
          ]
(...)
complex(665): note: while trying to match the argument list '(ceres::Jet<T,4>, int)'
```

This could possibly fixed by defining the operators as friend ADL operators.

**Comment by allo-** [comment]
When we have the example:

```
class SomeCostFunctor {
  template <typename T>
  bool operator()(const T* const x , const T* const y, T* e) const {
    if(x[0] == 0) {
        // something
    }
    return true;
  }

 private:
  double k_;
};
```

You get a compiler error at ``if(x[0] == 0)``, because JetT cannot be cast to integer. so you need to use:

    if(x[0] == static_cast<T>(0))

And it works.

Now try to use ``std::complex``:

    std::complex<T> var1(x[0], x[1]);
    std::complex<T> var2 = variable / 2.0;

Then you get the error from my post above, because ``std::complex`` has an implementation, which does ``_Rightimag < 0``.

The operation using different types of 0:

    // Implementation from the STL
    _Rightimag < 0 // error, because JetT does not implement operator< for int
    // variants NOT used in the STL
    _Rightimag < 0.0 // valid, as ceres implements operations on floats
    _Rightimag < static_cast<T>(0) // valid, because both types are JetT

I asked for a way to allow an implicit conversion on StackOverflow: https://stackoverflow.com/questions/52260248/make-c-automatically-convert-int-to-double

And a commenter suggested using ADL operators: https://stackoverflow.com/questions/52260248/make-c-automatically-convert-int-to-double#comment91468595_52260248

The commenter on SO suggested implementing the operators like:

    friend bool operator op(const Jet& f, const T& s) { return f.a op s; }


The question itself is resolved by the answer, that the STL does not guarantee to support ``std::complex`` for general types, but it would probably support ceres types, if ceres would have the ``operator<`` for int or an option for programmers to implement the missing operators.

ADL operators seem to provide exactly this option: https://en.cppreference.com/w/cpp/language/adl

I currently implemented the complex operations I need in an own class to avoid this problem, but I think it would be nice if ceres types would allow for more implicit casts.

**Comment by keir** [comment]
Way back in the origins of Ceres at Google, we had more implicit conversions for ints and related types. However, these ended up introducing nasty and hard to track down bugs, which is why we don't have those today.

However, it's been awhile and maybe we could reconsider. Would you be willing to throw up a patch on our Gerrit instance?

**Comment by allo-** [comment]
Currently I am on holiday, but I can have a look when I am working on it again.

**Comment by keir** [comment]
Any update here?

**Comment by allo-** [comment]
I still have this issue in mind, but currently the project I am using Ceres with complex numbers for is postponed, so I did not change anything in my current implementation (using my own ``complex`` type), yet.

**Comment by sandwichmaker** [comment]
Since there is no expected activity on this issue, I am going to close it.

**Comment by sandwichmaker** [comment]
https://gitlab.com/libeigen/eigen/-/issues/1912

**Comment by sergiud** [comment]
@allo- You might want to test [these changes](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/19321) and see if they solve your problem.

**Comment by sergiud** [comment]
@sandwichmaker I believe this issue  can be closed now.

**Comment by sandwichmaker** [comment]
Indeed!
