### ISSUE TITLE
http://ceres-solver.org/index.html does not use HTTPS

### ISSUE THREAD

**Issue by csukuangfj** [ceres-solver/ceres-solver#418]
The connection is not secure.

Are there any reasons not to use https ?

**Comment by sandwichmaker** [comment]
@keir maintains the server that hosts ceres-solver.org, he can comment.

**Comment by sandwichmaker** [comment]
@keir ?

**Comment by keir** [comment]
It's annoying to configure https, and ceres-solver.org is a static site; there isn't any need for https. Is there a particular reason this is wanted?

**Comment by sandwichmaker** [comment]
Closing because of no response.
