### ISSUE TITLE
inefficient code for computing residuals when Jacobian is not needed

### ISSUE THREAD

**Issue by csukuangfj** [ceres-solver/ceres-solver#419]
See the code
https://github.com/ceres-solver/ceres-solver/blob/72d8e1cdb1e7cdfbd662892f2a04f9af792a9be7/include/ceres/internal/autodiff.h#L231
https://github.com/ceres-solver/ceres-solver/blob/72d8e1cdb1e7cdfbd662892f2a04f9af792a9be7/include/ceres/internal/autodiff.h#L288-L290
https://github.com/ceres-solver/ceres-solver/blob/72d8e1cdb1e7cdfbd662892f2a04f9af792a9be7/include/ceres/internal/autodiff.h#L294

It uses Jet to compute the residual even if Jacobian is not needed.

It will be more efficient if we pass the parameters directly to the functor for computing residuals
when Jacobian is not needed.

----

PS: Are there any reasons to support only 10 parameter blocks instead of 9 or 11, or more ?

**Comment by csukuangfj** [comment]
Moreover, the check for `N0` is **missing**, see the code below
https://github.com/ceres-solver/ceres-solver/blob/72d8e1cdb1e7cdfbd662892f2a04f9af792a9be7/include/ceres/internal/autodiff.h#L216-L225

**Comment by sandwichmaker** [comment]
Please take a look at:
https://github.com/ceres-solver/ceres-solver/blob/72d8e1cdb1e7cdfbd662892f2a04f9af792a9be7/include/ceres/autodiff_cost_function.h#L205

which only calls the Differentiate method if jacobians are asked for. 

as for the check, it is for trailing zeros after the first parameter, you are right that test can be made stricter by checking for N0 is not zero.

**Comment by csukuangfj** [comment]
@sandwichmaker 
yes, I see. thanks for the reply.
