### ISSUE TITLE
Windows build gflags error

### ISSUE THREAD

**Issue by charelstoncrabb** [ceres-solver/ceres-solver#420]
I seem to be having trouble building ceres on Windows, and it seems to be related to related to searching for the gflags path?  

I am on a 64 bit Windows 10 machine using VS 2017, cmake version 3.11. I am trying to build ceres with Eigen, gflags, and glog and NOT suitesparse.

I have attached the output of the gflags cmake/build outputs as well as the ceres cmake output.

It looks like that during running cmake on ceres-solver, it is throwing an 'Invalid escape character \U' error, which is completely confusing me.

The issue is likely user-error, but in any case I would really like to figure this out and use ceres. Any help would be appreciated. 

Thanks.
[ceres_build.txt](https://github.com/ceres-solver/ceres-solver/files/2404159/ceres_build.txt)
[gflags_build.txt](https://github.com/ceres-solver/ceres-solver/files/2404160/gflags_build.txt)

**Comment by sandwichmaker** [comment]
@alexsmac PTAL.

**Comment by sandwichmaker** [comment]
@charelstoncrabb ping?

**Comment by JianpingCAI** [comment]
I just used vcpkg for installation, which is  @handy.
