### ISSUE TITLE
ConditionedCostFunction does not allow duplicate cost function pointers.

### ISSUE THREAD

**Issue by csukuangfj** [ceres-solver/ceres-solver#422]
See the code
https://github.com/ceres-solver/ceres-solver/blob/72d8e1cdb1e7cdfbd662892f2a04f9af792a9be7/internal/ceres/conditioned_cost_function.cc#L70-L72
https://github.com/ceres-solver/ceres-solver/blob/72d8e1cdb1e7cdfbd662892f2a04f9af792a9be7/internal/ceres/stl_util.h#L51-L54

It causes runtime errors when
https://github.com/ceres-solver/ceres-solver/blob/72d8e1cdb1e7cdfbd662892f2a04f9af792a9be7/include/ceres/conditioned_cost_function.h#L91
contains duplicate pointers since they are freed multiple times.

**Comment by sandwichmaker** [comment]
https://ceres-solver-review.googlesource.com/c/ceres-solver/+/14340
