### ISSUE TITLE
Check max time within an iteration

### ISSUE THREAD

**Issue by jasonfly07** [ceres-solver/ceres-solver#424]
In solver options, we set the `max_solver_time_in_seconds` to something like 50 milliseconds, but it seems that the actual running time always goes over this budget, such as 50-60 milliseconds with just 1 iteration. This is undesirable, since we plan to use this in a real-time system with tight computation budget.

Is there a way to query the time within an iteration, so we can just terminate the solver if time budget is reached, before one iteration finishes? I googled around and couldn't find such an option, so I am wondering if such mechanism is implemented.

**Comment by sandwichmaker** [comment]
@jasonfly07 you are right, the semantics are more like, we terminate at the first iteration that goes past this bound. Ceres is not really designed for a hard realtime system, in that it is not interruptible. 
It is possible to add more fine grained checks, there are essentially three places where you can check.

1. Before you compute the newton step.
2. Before you evaluate the new step
3. Before you compute the new Jacobian.

The current check is basically (1).  adding a checking at (3) maybe worth it, but it will also add some cost  and complicate the semantics of what is already a relatively complicated loop.

**Comment by sandwichmaker** [comment]
Closing this for now since the bug has been inactive, please re-open if this is still relevant.
