### ISSUE TITLE
Terminating: Residual and Jacobian evaluation failed.

### ISSUE THREAD

**Issue by JHzss** [ceres-solver/ceres-solver#426]
When I use ceres to optimize the problem , the terminal show : Terminating: Residual and Jacobian evaluation failed. I have checked the size of residual and jacobian matrix. There is no problem. It will not break down but just will not optimize the problem. What is the problem ? Thank you!

**Comment by sandwichmaker** [comment]
@JHzss have a look at the output on stderr, there is detailed information printed about the exact values at which the Jacobian/residual evaluation is failing.

**Comment by JHzss** [comment]
@sandwichmaker But I check the stderr , there is no detailed information printed about the exact values and I print it using 'cout' and find the values of Jacobian/residual are normal.

**Comment by sandwichmaker** [comment]
That is odd. What platform are you on?

**Comment by JHzss** [comment]
@sandwichmaker I'm on Ubuntu 14.04，the version of ceres is ‘ceres-solver-1.12.0’. I use the ceres to optimize the camera and IMU error . I don't know   if it is because I use two different types residual or other reason. It have confused me a few days...

**Comment by alexsmac** [comment]
@JHzss do any of your CostFunctions return false (from Evaluate()) ?

**Comment by JHzss** [comment]
@alexsmac At the beginning, it only show ''Terminating: Residual and Jacobian evaluation failed." and it will not break down, but just doesn't optimize the problem. Later, it shows "Linear solver failure. Failed to compute a step: Eigen failure. Unable to perform dense Cholesky factorization.". The first error message  always appear.

**Comment by JHzss** [comment]
@sandwichmaker @alexsmac I find the problem! I forget to return true in Evaluate(). Thank you very much!

**Comment by wenixang** [comment]
thank you,i'v met the same problem and i works!
