### ISSUE TITLE
UTF-8 chars in the project

### ISSUE THREAD

**Issue by huangqinjin** [ceres-solver/ceres-solver#427]
The UTF-8 char "–" (Hexadecimal: E28093) lies in some files, for example:

include/ceres/types.h(224):  // Algorithms,"; J. Inst. Maths. Applics., Vol. 6, pp 76–90, 1970.

In my visual studio (code page 936) , it causes the warning C4819.

**Comment by sandwichmaker** [comment]
Thanks @huangqinjin  I will take a look.

**Comment by sandwichmaker** [comment]
@huangqinjin would you be willing to submit a CL to fix this? since I do not have visual studio and this warning is not triggered on any of my machines.

**Comment by huangqinjin** [comment]
@sandwichmaker I've created a branch to show the [changes](https://github.com/huangqinjin/ceres-solver/commit/bf506302ff1cb062ba7a6c3ef9bcf0c45fa7dae6).

**Comment by sandwichmaker** [comment]
@huangqinjin can you submit your pull request to gerrit, following the instructions in

http://ceres-solver.org/contributing.html

**Comment by huangqinjin** [comment]
@sandwichmaker [14920](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/14920).

**Comment by sandwichmaker** [comment]
Thank you. Merged.
