### ISSUE TITLE
ScaledLoss

### ISSUE THREAD

**Issue by jcarpent** [ceres-solver/ceres-solver#432]
Dear Ceres developers,

I'm currently solving problems where the factor of the ScaledLoss has to be changed when solving several Problems.
I know the existence of LossFunctionWrapper to change the current ScaledLoss object by a new one. But is there any reason to not directly allow a modification of the scaled parameter of ScaledLoss struct?

**Comment by sandwichmaker** [comment]
@jcarpent are you trying to anneal the loss function somehow? you are free to implement your loss function which provides this ability and use it.

**Comment by jcarpent** [comment]
I wanted to know why you chose to no make it modifiable across Problem resolutions.
I can indeed implement my own ScalingLoss.

@sandwichmaker Thanks for the reply.
