### ISSUE TITLE
Bazel Dependency: Ceres is re-building every time

### ISSUE THREAD

**Issue by klemense1** [ceres-solver/ceres-solver#434]
I've included ceres in the WORKSPACE file as follows:
```
http_archive(
    name = "com_ceres_solver",
    strip_prefix = "ceres-solver-1.14.0",
    urls = ["https://github.com/ceres-solver/ceres-solver/archive/1.14.0.zip"],
)

```

However, every time I call `bazel build`, ceres is build as well. Does anybody has experienced this issue as well? Any ideas to solve it?

Many thanks

**Comment by keir** [comment]
That's odd. Have you tried adding the file hash to the workspace entry?

**Comment by sandwichmaker** [comment]
Closing due to lack of more information. Please re-open if you have additional info.

**Comment by klemense1** [comment]
Sorry for not replying for so long.

I've included the hash but without any improvement.
`http_archive(
    name = "com_google_ceres_solver",
    strip_prefix = "ceres-solver-1.14.0",
    sha256 = "5ba6d0db4e784621fda44a50c58bb23b0892684692f0c623e2063f9c19f192f1",
    urls = ["https://github.com/ceres-solver/ceres-solver/archive/1.14.0.zip"],
)`

When I call bazel build //... and afterwards bazel test //..., ceres get's built again (without any code changes in between). 
My expectation would be that bazel realizes that ceres has already been build with the build call before.
