### ISSUE TITLE
How to use ceres in windows matlab?

### ISSUE THREAD

**Issue by krishnakumarrs** [ceres-solver/ceres-solver#436]
I need to run mex by using ceres and eigen, but when the program is executed it shows error.

mex ceresRigidError.cpp /usr/local/lib/libceres_shared.so /usr/local/lib/libglog.so -I/usr/include/eigen3;
    mex ceresNonrigidError.cpp /usr/local/lib/libceres_shared.so /usr/local/lib/libglog.so -I/usr/include/eigen3;
i have added the path of ceres but i don't know it is correct.
please help.
thanks

**Comment by sandwichmaker** [comment]
sorry @krishnakumarrs I have no idea about your build environment or what the error is here. This likely needs help with someone who can help with your matlab build environment.
