### ISSUE TITLE
Ceres Incompatible with dev branch of Eigen 

### ISSUE THREAD

**Issue by oracle3001** [ceres-solver/ceres-solver#443]
Just so you are aware, ceres appears like it will need some adjustment in the future to work with the latest developments within Eigen. 

Upon trying to build using VS2017 with the latest dev fork from the official repo, produces a large number of errors relating to mathematical operators in genericpacketmathfunctions.h  e.g.

`binary '+': 'const Packet' does not define this operator or a conversion to a type acceptable to the predefined operator`

**Comment by sandwichmaker** [comment]
Thanks, I think there is an iterator related problem too. I will take a look.

**Comment by sandwichmaker** [comment]
@oracle3001 could you try now please? I just updated the version of gtest in ceres. If you still get errors, please share the error log.

**Comment by sandwichmaker** [comment]
closing because of no response. please open if this is still an issue.
