### ISSUE TITLE
undefined reference when using ceres in TX2

### ISSUE THREAD

**Issue by jycccccccc** [ceres-solver/ceres-solver#448]
Appreciate your work but I encountered some problems.
I am trying to use ceres in my project.
I installed the dependencies and ceres got built successfully.
I ran make test and all the tests were successful.
I am using ceres-1.13 on ubuntu 16.04.
When I use libceres.a in my project I get the following error while building:

/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::~CXSparse()':
cxsparse.cc:(.text+0x28): undefined reference to `cs_di_free'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::Cholesky(cs_di_sparse*, cs_di_symbolic*)':
cxsparse.cc:(.text+0x40): undefined reference to `cs_di_chol'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::Solve(cs_di_symbolic*, cs_di_numeric*, double*)':
cxsparse.cc:(.text+0xa4): undefined reference to `cs_di_ipvec'
cxsparse.cc:(.text+0xb4): undefined reference to `cs_di_lsolve'
cxsparse.cc:(.text+0xc4): undefined reference to `cs_di_ltsolve'
cxsparse.cc:(.text+0xdc): undefined reference to `cs_di_pvec'
cxsparse.cc:(.text+0x11c): undefined reference to `cs_di_free'
cxsparse.cc:(.text+0x128): undefined reference to `cs_di_malloc'
cxsparse.cc:(.text+0x144): undefined reference to `cs_di_ipvec'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::SolveCholesky(cs_di_sparse*, double*)':
cxsparse.cc:(.text+0x314): undefined reference to `cs_di_cholsol'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::AnalyzeCholesky(cs_di_sparse*)':
cxsparse.cc:(.text+0x32c): undefined reference to `cs_di_schol'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::AnalyzeCholeskyWithNaturalOrdering(cs_di_sparse*)':
cxsparse.cc:(.text+0x334): undefined reference to `cs_di_schol'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::BlockAnalyzeCholesky(cs_di_sparse*, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&)':
cxsparse.cc:(.text+0x3d4): undefined reference to `cs_di_amd'
cxsparse.cc:(.text+0x430): undefined reference to `cs_di_free'
cxsparse.cc:(.text+0x454): undefined reference to `cs_di_calloc'
cxsparse.cc:(.text+0x464): undefined reference to `cs_di_pinv'
cxsparse.cc:(.text+0x47c): undefined reference to `cs_di_symperm'
cxsparse.cc:(.text+0x488): undefined reference to `cs_di_etree'
cxsparse.cc:(.text+0x494): undefined reference to `cs_di_post'
cxsparse.cc:(.text+0x4ac): undefined reference to `cs_di_counts'
cxsparse.cc:(.text+0x4b8): undefined reference to `cs_di_free'
cxsparse.cc:(.text+0x4c0): undefined reference to `cs_di_spfree'
cxsparse.cc:(.text+0x4d0): undefined reference to `cs_di_malloc'
cxsparse.cc:(.text+0x4e0): undefined reference to `cs_di_cumsum'
cxsparse.cc:(.text+0x4ec): undefined reference to `cs_di_free'
cxsparse.cc:(.text+0x55c): undefined reference to `cs_di_sfree'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::CreateSparseMatrix(ceres::internal::TripletSparseMatrix*)':
cxsparse.cc:(.text+0x7d4): undefined reference to `cs_di_compress'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::ApproximateMinimumDegreeOrdering(cs_di_sparse*, int*)':
cxsparse.cc:(.text+0x8c4): undefined reference to `cs_di_amd'
cxsparse.cc:(.text+0x8f4): undefined reference to `cs_di_free'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::TransposeMatrix(cs_di_sparse*)':
cxsparse.cc:(.text+0x900): undefined reference to `cs_di_transpose'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::MatrixMatrixMultiply(cs_di_sparse*, cs_di_sparse*)':
cxsparse.cc:(.text+0x910): undefined reference to `cs_di_multiply'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::Free(cs_di_sparse*)':
cxsparse.cc:(.text+0x91c): undefined reference to `cs_di_spfree'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::Free(cs_di_symbolic*)':
cxsparse.cc:(.text+0x924): undefined reference to `cs_di_sfree'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::Free(cs_di_numeric*)':
cxsparse.cc:(.text+0x92c): undefined reference to `cs_di_nfree'
collect2: error: ld returned 1 exit status
cartographer_ros/cartographer_ros/cartographer_ros/CMakeFiles/cartographer_start_trajectory.dir/build.make:204: recipe for target '/home/nvidia/Workspace/ROS/catkin_ws/devel/lib/cartographer_ros/cartographer_start_trajectory' failed
make[2]: *** [/home/nvidia/Workspace/ROS/catkin_ws/devel/lib/cartographer_ros/cartographer_start_trajectory] Error 1
CMakeFiles/Makefile2:4348: recipe for target 'cartographer_ros/cartographer_ros/cartographer_ros/CMakeFiles/cartographer_start_trajectory.dir/all' failed
make[1]: *** [cartographer_ros/cartographer_ros/cartographer_ros/CMakeFiles/cartographer_start_trajectory.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::~CXSparse()':
cxsparse.cc:(.text+0x28): undefined reference to `cs_di_free'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::Cholesky(cs_di_sparse*, cs_di_symbolic*)':
cxsparse.cc:(.text+0x40): undefined reference to `cs_di_chol'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::Solve(cs_di_symbolic*, cs_di_numeric*, double*)':
cxsparse.cc:(.text+0xa4): undefined reference to `cs_di_ipvec'
cxsparse.cc:(.text+0xb4): undefined reference to `cs_di_lsolve'
cxsparse.cc:(.text+0xc4): undefined reference to `cs_di_ltsolve'
cxsparse.cc:(.text+0xdc): undefined reference to `cs_di_pvec'
cxsparse.cc:(.text+0x11c): undefined reference to `cs_di_free'
cxsparse.cc:(.text+0x128): undefined reference to `cs_di_malloc'
cxsparse.cc:(.text+0x144): undefined reference to `cs_di_ipvec'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::SolveCholesky(cs_di_sparse*, double*)':
cxsparse.cc:(.text+0x314): undefined reference to `cs_di_cholsol'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::AnalyzeCholesky(cs_di_sparse*)':
cxsparse.cc:(.text+0x32c): undefined reference to `cs_di_schol'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::AnalyzeCholeskyWithNaturalOrdering(cs_di_sparse*)':
cxsparse.cc:(.text+0x334): undefined reference to `cs_di_schol'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::BlockAnalyzeCholesky(cs_di_sparse*, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&)':
cxsparse.cc:(.text+0x3d4): undefined reference to `cs_di_amd'
cxsparse.cc:(.text+0x430): undefined reference to `cs_di_free'
cxsparse.cc:(.text+0x454): undefined reference to `cs_di_calloc'
cxsparse.cc:(.text+0x464): undefined reference to `cs_di_pinv'
cxsparse.cc:(.text+0x47c): undefined reference to `cs_di_symperm'
cxsparse.cc:(.text+0x488): undefined reference to `cs_di_etree'
cxsparse.cc:(.text+0x494): undefined reference to `cs_di_post'
cxsparse.cc:(.text+0x4ac): undefined reference to `cs_di_counts'
cxsparse.cc:(.text+0x4b8): undefined reference to `cs_di_free'
cxsparse.cc:(.text+0x4c0): undefined reference to `cs_di_spfree'
cxsparse.cc:(.text+0x4d0): undefined reference to `cs_di_malloc'
cxsparse.cc:(.text+0x4e0): undefined reference to `cs_di_cumsum'
cxsparse.cc:(.text+0x4ec): undefined reference to `cs_di_free'
cxsparse.cc:(.text+0x55c): undefined reference to `cs_di_sfree'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::CreateSparseMatrix(ceres::internal::TripletSparseMatrix*)':
cxsparse.cc:(.text+0x7d4): undefined reference to `cs_di_compress'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::ApproximateMinimumDegreeOrdering(cs_di_sparse*, int*)':
cxsparse.cc:(.text+0x8c4): undefined reference to `cs_di_amd'
cxsparse.cc:(.text+0x8f4): undefined reference to `cs_di_free'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::TransposeMatrix(cs_di_sparse*)':
cxsparse.cc:(.text+0x900): undefined reference to `cs_di_transpose'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::MatrixMatrixMultiply(cs_di_sparse*, cs_di_sparse*)':
cxsparse.cc:(.text+0x910): undefined reference to `cs_di_multiply'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::Free(cs_di_sparse*)':
cxsparse.cc:(.text+0x91c): undefined reference to `cs_di_spfree'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::Free(cs_di_symbolic*)':
cxsparse.cc:(.text+0x924): undefined reference to `cs_di_sfree'
/usr/local/lib/libceres.a(cxsparse.cc.o): In function `ceres::internal::CXSparse::Free(cs_di_numeric*)':
cxsparse.cc:(.text+0x92c): undefined reference to `cs_di_nfree'
collect2: error: ld returned 1 exit status
cartographer_ros/cartographer_ros/cartographer_ros/CMakeFiles/cartographer_offline_node.dir/build.make:204: recipe for target '/home/nvidia/Workspace/ROS/catkin_ws/devel/lib/cartographer_ros/cartographer_offline_node' failed
make[2]: *** [/home/nvidia/Workspace/ROS/catkin_ws/devel/lib/cartographer_ros/cartographer_offline_node] Error 1
CMakeFiles/Makefile2:4385: recipe for target 'cartographer_ros/cartographer_ros/cartographer_ros/CMakeFiles/cartographer_offline_node.dir/all' failed
make[1]: *** [cartographer_ros/cartographer_ros/cartographer_ros/CMakeFiles/cartographer_offline_node.dir/all] Error 2

Looking forward to your answers. Thanks!

**Comment by jycccccccc** [comment]
thx! problems solved!

**Comment by craftindo** [comment]
how to turn it off if building using eclipse?
