### ISSUE TITLE
Question about square root information computed in pose_graph_2d example

### ISSUE THREAD

**Issue by versatran01** [ceres-solver/ceres-solver#449]
In line 85 of pose_graph_2d.cc
The square root information matrix is computed as
```
const Eigen::Matrix3d sqrt_information =
        constraint.information.llt().matrixL()
```
and in pose_graph_error_2d.h
This is multiplied to the left of the residual
```
residuals_map = sqrt_information_.template cast<T>() * residuals_map;
```
However, in Bundle Adjustment A Modern Synthesis page 308 Section 3.2 the paragraph describing standardized residual, it says z_i should be pre multiplied by L_i^T.
From my understanding, we should get matrixU from llt instead of matrixL? 
Please advise. Thanks!

**Comment by versatran01** [comment]
I realized it doesn't matter at the end of the day once you multiple r^T r together, because information matrix is symmetric.

**Comment by jinkunw** [comment]
Using `Lr` leads to an information matrix `L^TL`. Although information matrix is symmetric, `L^TL != LL^T`. 
For your reference, GTSAM uses `L^T` https://github.com/borglab/gtsam/blob/4ac78953ae6d0708da958765bd5be19d0fc192ac/gtsam/linear/NoiseModel.cpp#L106
