### ISSUE TITLE
How to use OpenMP in Ceres Solver?

### ISSUE THREAD

**Issue by Ayangdanny** [ceres-solver/ceres-solver#450]
I use AnalyticCostfunction. In the "virtual bool Evaluate()" function I have some code used to calculate residuals and jacobians. In these code I try to use "#pragma omp parallel for" to improve the performance, but it dons't make any sense. If I run the same code in other place (mine rather than ceres‘s functions),the OpenMP make sense very well. I concer about whether there are some tricks when use OpenMP in Ceres functions.

**Comment by alexsmac** [comment]
You will need to be more specific, what do you mean that it doesn't make any sense?

**Comment by sandwichmaker** [comment]
Closing this issue as there is no information available. Please re-open with additional information.
