### ISSUE TITLE
make install failed

### ISSUE THREAD

**Issue by ZHAORANWU1** [ceres-solver/ceres-solver#452]
make and make test has no problem.
but when I try to make install,it'll be like this:

proprak8@I81PC79:~/Pangolin/build$ sudo make install
[sudo] Passwort für proprak8: 
/bin/sh: 1: cd: can't cd to /home/proprak8/Pangolin/build
src/CMakeFiles/pangolin.dir/build.make:2401: recipe for target 'src/CMakeFiles/pangolin.dir/depend' failed
make[2]: *** [src/CMakeFiles/pangolin.dir/depend] Error 2
CMakeFiles/Makefile2:135: recipe for target 'src/CMakeFiles/pangolin.dir/all' failed
make[1]: *** [src/CMakeFiles/pangolin.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alexsmac** [comment]
Unless you have renamed Ceres 'Pangolin', you do not appear to be installing Ceres.  Your problem is likely with Pangolin and has nothing to do with Ceres.
