### ISSUE TITLE
Multithreading support on Android

### ISSUE THREAD

**Issue by hhu006** [ceres-solver/ceres-solver#456]
I am trying to build ceres (ver 1.14.0) with Android NDK (r17c) standalone toolchain. Since OpenMP is not supported by the clang compiler of Android NDK any longer, I attempted to use CXX11 threads for ceres multithreading.

For example, with the following cmake options "-DOPENMP=OFF -DCXX11_THREADS=ON",  an build error on Mutex is seen as follows. No idea why ceres requires a new mutex implementation, but not use the mutex from std.

cmake .. -DCMAKE_FIND_ROOT_PATH=<Dependency library location> -DCMAKE_C_COMPILER=${NDK_STANDALONE_TOOLCHAIN}/bin/aarch64-linux-android-clang -DCMAKE_CXX_COMPILER=${NDK_STANDALONE_TOOLCHAIN}/bin/aarch64-linux-android-clang++ -DEIGEN_INCLUDE_DIR_HINTS=<Dependency library location>/include/eigen3  -DCXSPARSE_INCLUDE_DIR_HINTS=/<Dependency library location>/include/ -DCXSPARSE_LIBRARY_DIR_HINTS=<Dependency library location>/lib  -DSUITESPARSE=OFF -DEIGENSPARSE=OFF -DGFLAGS=OFF -DCXX11=ON -DMINIGLOG=ON -DLAPACK=OFF -DCMAKE_INSTALL_PREFIX=/<install location> -DSUITESPARSE=OFF -DEIGENSPARSE=OFF -DGFLAGS=OFF -DCXX11=ON -DMINIGLOG=ON -DLAPACK=OFF -DCMAKE_INSTALL_PREFIX=/home/perceptin/Downloads/android_lib -DMINIGLOG_MAX_LOG_LEVEL=0  -DOPENMP=OFF -DCXX11_THREADS=ON

ceres-solver-1.14.0/internal/ceres/mutex.h:136:3: error: Need to implement mutex.h for your architecture, or #define NO_THREADS
# error Need to implement mutex.h for your architecture, or #define NO_THREADS
  ^
internal/ceres/mutex.h:176:3: error: unknown type name 'MutexType'
  MutexType mutex_;
  ^

Also, if the CXX11 threads doesn't work for ceres on Android, please advise what will be the right approach to enable multi-threading on Android with Android NDK clang compiler.

**Comment by alexsmac** [comment]
We did not support multithreading in 1.14 on Android.  If you switch to master (which will become Ceres 2.0) then C++11 multithreading is supported on Android, and the supported build environment on Android has also been updated to CMake.  Build instructions are [available here](https://github.com/ceres-solver/ceres-solver/blob/master/docs/source/installation.rst#android).
