### ISSUE TITLE
Lack of clarity whether Grid/BiCubicInterpolator cause an error when out-of-bounds

### ISSUE THREAD

**Issue by patrikhuber** [ceres-solver/ceres-solver#457]
Hi!

There is an inconsistency and lack of clarity whether `Grid` (e.g. `Grid2D`) and `BiCubicInterpolator` support accessing values out of the grid boundary or not.

Here it says that `BiCubicInterpolator` will return `false` if r or c are out of bounds:
https://github.com/ceres-solver/ceres-solver/blob/e51e9b46f6ca88ab8b2266d0e362771db6d98067/include/ceres/cubic_interpolation.h#L266-L269
But that function returns `void` so that part of the docs would need fixing.

And the documentation of `Grid1D` and `Grid2D` says the grid is infinite and it uses the value from the nearest edge when accessed with indices that are outside the boundaries:
https://github.com/ceres-solver/ceres-solver/blob/e51e9b46f6ca88ab8b2266d0e362771db6d98067/include/ceres/cubic_interpolation.h#L363-L365

I believe this is true and it indeed supports accessing out of bounds values. `Grid2D::GetValue(...)` seems to clamp the values if they're outside the grid range:
https://github.com/ceres-solver/ceres-solver/blob/e51e9b46f6ca88ab8b2266d0e362771db6d98067/include/ceres/cubic_interpolation.h#L404-L407

So I think that all that might be needed is a documentation fix for the wrong documentation of `BiCubicInterpolator` and maybe add a short sentence there making clear that accessing out-of-bound values is indeed okay.

Any thoughts? I'd be happy to submit a PR.

**Comment by sandwichmaker** [comment]
Yes the documentation needs fixed. We are using a constant boundary condition, where the boundary value comes from the nearest point on the boundary. The documentation reflects an older reality.

**Comment by sandwichmaker** [comment]
Please send a pull request on gerrit, following the instructions at 

http://ceres-solver.org/contributing.html

**Comment by patrikhuber** [comment]
Great, thanks, will do! 👍

**Comment by patrikhuber** [comment]
I'll close this, we can continue the discussion [in the Gerrit PR](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/14820) if needed.
