### ISSUE TITLE
Update docs to add package-manager based installation for windows

### ISSUE THREAD

**Issue by thclark** [ceres-solver/ceres-solver#458]
The docs currently give the impression that there's an epic number of steps to build from source when it comes to using ceres on windows. There's a [port out there](https://github.com/tbennun/ceres-windows) which supplies binaries, but is a bit out of date now and isn't being maintained.

I had a very smart intern struggling for a long while to build on windows, whereas on a mac, I just `brew install` in a one-liner, as per the Installation docs.

I just came across [this post](https://github.com/ceres-solver/ceres-solver/issues/420) in which one responder said they had no problems installing using [vcpkg](https://devblogs.microsoft.com/cppblog/vcpkg-a-tool-to-acquire-and-build-c-open-source-libraries-on-windows/). Since [ceres is on the list of packages](https://devblogs.microsoft.com/cppblog/vcpkg-a-tool-to-acquire-and-build-c-open-source-libraries-on-windows/) that can be pretty straightforwardly installed with that, perhaps that could be included in the [windows installation section of the docs](http://ceres-solver.org/installation.html#windows) please?

**Comment by keir** [comment]
We don't have any maintainers on Windows for Ceres currently; would you be willing to help out? We'd much rather have these random side-efforts join the main Ceres developers to properly support Windows.

**Comment by thclark** [comment]
Hi @keir, I think it's a case of willing but not able! I actually don't work on windows at all, and haven't for many years, so me becoming the de-facto windows maintainer might be a very bad idea!

I'm dabbling just now to try and get Travis for Windows to build a library of mine which depends on ceres. If I can get that working, I'll happily submit a PR to update the docs, if you'd like? 

Unrelated - a huge thank you to both you and @sandwichmaker for your brilliant efforts here. I've learned just so much from going through the ceres code.

**Comment by sandwichmaker** [comment]
This has been fixed for a while now.
