### ISSUE TITLE
Disable Trust Region?

### ISSUE THREAD

**Issue by soulslicer** [ceres-solver/ceres-solver#462]
Is there a way to do pure Gauss Newton and disable the LM trust region approach?

**Comment by sandwichmaker** [comment]
Not right now. I am curious as to why you would want to do that? That will result in a non-convergent algorithm.

**Comment by soulslicer** [comment]
It's not needed. I am trying to find a GPU port of the LM trust region solver. I find Ceres to be too slow, can you recommend something that accepts Residual, Parameters, and a Jacobian to find delta_parameters?

**Comment by sandwichmaker** [comment]
Try http://optlang.org/

**Comment by soulslicer** [comment]
I have taken a brief look at this, but it looks like it needs some explicit formulation. I need something at a lower level based on what I have described above. Currently, I only find only one library that does this:

https://github.com/gpufit/Gpufit
