### ISSUE TITLE
Bazel build fails due to deprecated http_archive rule

### ISSUE THREAD

**Issue by ewhitmire** [ceres-solver/ceres-solver#463]
The `http_archive` and `new_http_archive` Bazel rules are deprecated and it looks like they were removed in Bazel version 0.23.0. As a result, it is unable to parse the `WORKSPACE` file.

**Comment by sandwichmaker** [comment]
don't use bazel :). Its an incomplete build anyways.
That said, @keir can you look at fixing this.

**Comment by keir** [comment]
I have a patch up to fix this:
https://ceres-solver-review.googlesource.com/c/ceres-solver/+/15120
