### ISSUE TITLE
Error compling:No rule to make target '/usr/lib/x86_64-linux-gnu/libspqr.so

### ISSUE THREAD

**Issue by Savviitar** [ceres-solver/ceres-solver#465]
When i try build the ceres-solver, i confront a problem!
No rule to make target '/usr/lib/x86_64-linux-gnu/libspqr.so', needed by 'bin/simple_bundle_adjuster'.  Stop.

suitesparse version 4.4.6

[  0%] Built target gtest
[ 29%] Built target ceres
[ 30%] Built target test_util
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libspqr.so', needed by 'bin/simple_bundle_adjuster'.  Stop.
CMakeFiles/Makefile2:7037: recipe for target 'examples/CMakeFiles/simple_bundle_adjuster.dir/all' failed
make[1]: *** [examples/CMakeFiles/simple_bundle_adjuster.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libspqr.so', needed by 'bin/robust_curve_fitting'.  Stop.
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libspqr.so', needed by 'bin/rosenbrock'.  Stop.
CMakeFiles/Makefile2:7074: recipe for target 'examples/CMakeFiles/robust_curve_fitting.dir/all' failed
make[1]: *** [examples/CMakeFiles/robust_curve_fitting.dir/all] Error 2
CMakeFiles/Makefile2:7111: recipe for target 'examples/CMakeFiles/rosenbrock.dir/all' failed
make[1]: *** [examples/CMakeFiles/rosenbrock.dir/all] Error 2
Makefile:140: recipe for target 'all' failed

**Comment by alexsmac** [comment]
This looks like you configured Ceres when the suitesparse package was installed, then removed it before building (or rebuilding).
