### ISSUE TITLE
Trajectory optimization problem does not converge

### ISSUE THREAD

**Issue by TimKlaas** [ceres-solver/ceres-solver#466]
Hello everyone,

I am currently working on using ceres solver for optimizing a robotic path trajectory, which consists of 2-Dim position nodes. I use different cost functions to form constraints for these position nodes, in order to optimize the trajectory in terms of for example achieving a shortest path solution.  I already solved the problem in Matlab which worked fine. However when using ceres I encounter the following problem:

Even if I only include the simplest cost function of optimizing towards the shortest path, which takes the distance between two consecutive position nodes as an error the problem does not converge to the minima, which in this case would just be a straight line.

I implemented the cost function and the problem initialization as follows:

```
// Class for shortest path cost function
class CF_ShortestPath {
public:
  // Constructor
  explicit CF_ShortestPath(double d):d(d){}

  // Cost function implemented as an () operator
  template <typename T>
  bool operator()(const T* const pos1_ptr, const T* const pos2_ptr,T* F_ptr) const {
    // Map values behind pointer to eigen classes
    Eigen::Map<const Eigen::Matrix<T, 2, 1> > pos1(pos1_ptr);
    Eigen::Map<const Eigen::Matrix<T, 2, 1> > pos2(pos2_ptr);
    //Eigen::Map<Eigen::Matrix<T, 1, 1> > residual(F_ptr);

    // Calculate the distance between two points and return as residual
    *F_ptr =  WEIGHT_ShortestPath * (pos1 - pos2).norm()-d;
    return true;
  }


  static ceres::CostFunction* CreateAutoDiff(double d){
      return new ceres::AutoDiffCostFunction<CF_ShortestPath,1,2,2>(new CF_ShortestPath(d));
  }

    EIGEN_MAKE_ALIGNED_OPERATOR_NEW
protected:
    const double d;
};
```

```
/*
   * Costfunction initialisation
   */

  /*
   * Costfunction for shortest path
   *
   * Takes smallest possible distance d between each node as initialization parameter
   * Creates one edge between every Robot position
   */

  double d = (double)(x_hat_initial[0].get_pos() - x_hat_initial[NUM_RoboPos-1].get_pos()).norm()/(NUM_RoboPos);

  CostFunction* CF_ShortestPath = CF_ShortestPath::CreateAutoDiff(d);
  for(int i = 1; i < NUM_RoboPos; i++){
    problem.AddResidualBlock(CF_ShortestPath, nullptr /*loss function*/,
       x_hat_opt[i-1].get_pos().data(), x_hat_opt[i].get_pos().data());
    // Set start and end Node const
    if(i == 1){
      problem.SetParameterBlockConstant(x_hat_opt[i-1].get_pos().data());
    }
    if(i == NUM_RoboPos-1){
      problem.SetParameterBlockConstant(x_hat_opt[i].get_pos().data());
    }
  }
```
,where x_hat_initial stores the initial robot position nodes and x_hat_opt the ones to be optimized.

When executing I am receiving the following report:

[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Modules
[ RUN      ] Modules.Ceres
iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time
   0  1.020210e-02    0.00e+00    1.04e-01   0.00e+00   0.00e+00  1.00e+04        0    1.30e-04    2.67e-04
   1  3.869092e-03    6.33e-03    6.01e-02   2.76e-01   6.21e-01  1.01e+04        1    1.92e-04    5.01e-04
   2  8.187426e-03   -4.32e-03    0.00e+00   1.63e-01  -1.12e+00  5.07e+03        1    2.60e-05    5.40e-04
   3  8.184286e-03   -4.32e-03    0.00e+00   1.63e-01  -1.12e+00  1.27e+03        1    2.10e-05    5.70e-04
   4  8.165495e-03   -4.30e-03    0.00e+00   1.62e-01  -1.11e+00  1.58e+02        1    2.00e-05    5.98e-04
   5  7.993743e-03   -4.12e-03    0.00e+00   1.61e-01  -1.07e+00  9.91e+00        1    2.00e-05    6.26e-04
   6  5.823475e-03   -1.95e-03    0.00e+00   1.45e-01  -5.08e-01  3.10e-01        1    1.91e-05    6.52e-04
   7  1.986723e-03    1.88e-03    3.77e-02   4.38e-02   8.28e-01  4.32e-01        1    1.30e-04    7.90e-04
   8  1.538219e-03    4.49e-04    2.02e-02   4.51e-02   6.09e-01  4.36e-01        1    1.31e-04    9.30e-04
   9  1.301264e-03    2.37e-04    1.86e-02   3.05e-02   5.29e-01  4.36e-01        1    1.34e-04    1.08e-03
  10  1.111863e-03    1.89e-04    1.32e-02   3.66e-02   6.07e-01  4.40e-01        1    1.36e-04    1.23e-03
  11  1.614145e-03   -5.02e-04    0.00e+00   5.39e-02  -1.89e+00  2.20e-01        1    2.41e-05    1.26e-03
  12  1.178027e-03   -6.62e-05    0.00e+00   3.11e-02  -4.22e-01  5.51e-02        1    2.10e-05    1.29e-03
  13  1.083531e-03    2.83e-05    1.31e-02   9.02e-03   6.09e-01  5.56e-02        1    1.30e-04    1.42e-03
  14  1.071787e-03    1.17e-05    1.08e-02   1.65e-02   2.37e-01  4.86e-02        1    1.34e-04    1.57e-03
  15  1.033572e-03    3.82e-05    1.11e-02   6.57e-03   7.97e-01  6.15e-02        1    1.33e-04    1.71e-03
  16  1.009950e-03    2.36e-05    1.11e-02   5.94e-03   8.00e-01  7.84e-02        1    1.33e-04    1.85e-03
  17  9.851299e-04    2.48e-05    9.49e-03   1.01e-02   7.59e-01  9.11e-02        1    1.36e-04    2.00e-03
  18  9.587254e-04    2.64e-05    9.86e-03   9.56e-03   5.94e-01  9.17e-02        1    1.32e-04    2.15e-03
  19  9.348044e-04    2.39e-05    7.66e-03   1.17e-02   5.48e-01  9.18e-02        1    1.40e-04    2.30e-03
  20  9.090036e-04    2.58e-05    8.49e-03   1.06e-02   5.52e-01  9.19e-02        1    1.32e-04    2.44e-03
  21  8.842122e-04    2.48e-05    7.33e-03   9.70e-03   6.38e-01  9.39e-02        1    1.34e-04    2.59e-03
  22  8.639329e-04    2.03e-05    7.45e-03   1.01e-02   5.47e-01  9.39e-02        1    1.35e-04    2.73e-03
  23  8.432280e-04    2.07e-05    7.22e-03   1.14e-02   4.86e-01  9.39e-02        1    1.34e-04    2.88e-03
  24  8.230165e-04    2.02e-05    7.16e-03   1.28e-02   4.28e-01  9.37e-02        1    1.33e-04    3.02e-03
  25  8.023494e-04    2.07e-05    7.12e-03   1.24e-02   4.37e-01  9.35e-02        1    1.34e-04    3.17e-03
  26  7.836320e-04    1.87e-05    7.09e-03   1.40e-02   3.91e-01  9.25e-02        1    1.37e-04    3.32e-03
  27  8.240720e-04   -4.04e-05    0.00e+00   2.34e-02  -7.57e-01  4.62e-02        1    2.29e-05    3.35e-03
  28  7.790823e-04    4.55e-06    7.07e-03   1.23e-02   1.57e-01  3.50e-02        1    1.27e-04    3.49e-03
  29  7.668452e-04    1.22e-05    7.07e-03   3.71e-03   8.79e-01  6.21e-02        1    1.36e-04    3.63e-03
  30  7.504276e-04    1.64e-05    6.98e-03   7.50e-03   7.96e-01  7.84e-02        1    1.32e-04    3.78e-03
  31  7.361985e-04    1.42e-05    6.81e-03   1.83e-02   5.68e-01  7.86e-02        1    1.30e-04    3.92e-03
  32  8.253465e-04   -8.91e-05    0.00e+00   3.42e-02  -1.61e+00  3.93e-02        1    2.31e-05    3.95e-03
  33  7.433420e-04   -7.14e-06    0.00e+00   1.79e-02  -2.43e-01  9.83e-03        1    2.19e-05    3.99e-03
  34  7.309156e-04    5.28e-06    6.80e-03   4.61e-03   6.85e-01  1.04e-02        1    1.33e-04    4.14e-03
  35  7.410354e-04   -1.01e-05    0.00e+00   1.12e-02  -1.46e+00  5.18e-03        1    2.19e-05    4.17e-03
  36  7.316881e-04   -7.72e-07    0.00e+00   5.63e-03  -2.21e-01  1.29e-03        1    1.69e-05    4.20e-03
  37  7.303064e-04    6.09e-07    6.80e-03   1.41e-03   6.95e-01  1.37e-03        1    1.20e-04    4.32e-03
  38  7.298285e-04    4.78e-07    6.79e-03   1.77e-03   5.70e-01  1.38e-03        1    1.26e-04    4.46e-03
  39  7.290950e-04    7.34e-07    6.79e-03   1.08e-03   8.17e-01  1.85e-03        1    1.27e-04    4.60e-03
  40  7.283405e-04    7.55e-07    6.79e-03   3.64e-04   9.86e-01  5.56e-03        1    1.27e-04    4.73e-03
  41  7.262137e-04    2.13e-06    6.79e-03   9.79e-04   9.52e-01  1.67e-02        1    2.06e-04    4.97e-03
  42  7.215436e-04    4.67e-06    6.77e-03   4.42e-03   7.44e-01  1.89e-02        1    1.93e-04    5.19e-03
  43  7.169168e-04    4.63e-06    6.76e-03   5.56e-03   4.78e-01  1.89e-02        1    2.52e-04    5.49e-03
  44  7.121094e-04    4.81e-06    6.76e-03   5.12e-03   5.72e-01  1.89e-02        1    3.13e-04    5.86e-03
  45  7.165245e-04   -4.42e-06    0.00e+00   1.63e-02  -5.33e-01  9.46e-03        1    1.02e-04    6.01e-03
  46  7.110187e-04    1.09e-06    6.76e-03   8.18e-03   2.60e-01  8.52e-03        1    3.64e-04    6.41e-03
  47  7.074705e-04    3.55e-06    6.77e-03   2.16e-03   9.09e-01  1.88e-02        1    4.30e-04    7.04e-03
  48  7.027780e-04    4.69e-06    6.78e-03   7.91e-03   5.16e-01  1.88e-02        1    4.47e-04    7.57e-03
  49  7.210636e-04   -1.83e-05    0.00e+00   1.64e-02  -1.32e+00  9.41e-03        1    1.77e-04    7.86e-03
  50  7.037864e-04   -1.01e-06    0.00e+00   8.29e-03  -1.43e-01  2.35e-03        1    6.58e-05    7.97e-03

Solver Summary (v 2.0.0-eigen-(3.3.90)-lapack-suitesparse-(4.4.6)-cxsparse-(3.1.4)-eigensparse-no_openmp)

                                     Original                  Reduced
Parameter blocks                           10                        8
Parameters                                 20                       16
Residual blocks                             9                        9
Residuals                                   9                        9

Minimizer                        TRUST_REGION

Sparse linear algebra library    SUITE_SPARSE
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver          SPARSE_NORMAL_CHOLESKY   SPARSE_NORMAL_CHOLESKY
Threads                                     1                        1
Linear solver ordering              AUTOMATIC                        8

Cost:
Initial                          1.020210e-02
Final                            7.027780e-04
Change                           9.499323e-03

Minimizer iterations                       51
Successful steps                           36
Unsuccessful steps                         15

Time (in seconds):
Preprocessor                         0.000137

  Residual only evaluation           0.000757 (50)
  Jacobian & residual evaluation     0.004569 (36)
  Linear solver                      0.000890 (50)
Minimizer                            0.007896

Postprocessor                        0.000066
Total                                0.008099

Termination:                   NO_CONVERGENCE (Maximum number of iterations reached. Number of iterations: 50.)

[       OK ] Modules.Ceres (90 ms)
[----------] 1 test from Modules (90 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (90 ms total)
[  PASSED  ] 1 test.

Process finished with exit code 0

I also plotted the resulting trajectory, which shows the ceres is optimizing in the right direction, however it does not converge to the optimal solution of a straight line.

I hope I presented all the information needed if anything is missing please let me know. Your help with this issue would be appreciated very much!

Best regards

Tim 

UPDATE:

So I tried increasing the maximum amount of iterations as well as decreasing the function tolerance, which brings me to the correct solution, however the processing time for such a small problem is tremendous. Does ceres always need so many iterations or am I missing another thing? Here is the solver summary:

Solver Summary (v 2.0.0-eigen-(3.3.90)-lapack-suitesparse-(4.4.6)-cxsparse-(3.1.4)-eigensparse-no_openmp)

                                     Original                  Reduced
Parameter blocks                           10                        8
Parameters                                 20                       16
Residual blocks                             9                        9
Residuals                                   9                        9

Minimizer                        TRUST_REGION

Sparse linear algebra library    SUITE_SPARSE
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver          SPARSE_NORMAL_CHOLESKY   SPARSE_NORMAL_CHOLESKY
Threads                                    10                        4
Linear solver ordering              AUTOMATIC                        8

Cost:
Initial                          8.555556e-02
Final                            5.556230e-02
Change                           2.999325e-02

Minimizer iterations                      353
Successful steps                          304
Unsuccessful steps                         49

Time (in seconds):
Preprocessor                         0.000237

  Residual only evaluation           0.006451 (353)
  Jacobian & residual evaluation     0.016121 (304)
  Linear solver                      0.002969 (353)
Minimizer                            0.029697

Postprocessor                        0.000010
Total                                0.029945

Termination:                      CONVERGENCE (Function tolerance reached. |cost_change|/cost: 6.402127e-08 <= 1.000000e-07)

[       OK ] Modules.Ceres (76 ms)
[----------] 1 test from Modules (76 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (76 ms total)
[  PASSED  ] 1 test.

Process finished with exit code 0

Anyone any further thoughts?

**Comment by TimKlaas** [comment]
UPDATE:

Using .norm() seems to be the issue for my problem. For further detail see:
https://groups.google.com/forum/#!searchin/ceres-solver/Gradient$20Error$20detected%7Csort:date/ceres-solver/cPMgCxiMSig/hgIGPTRTBQAJ

**Comment by sandwichmaker** [comment]
Since we are discussing this on the mailinglist, I am going to close this issue.
