### ISSUE TITLE
bundle_adjuster.cc on more datasets

### ISSUE THREAD

**Issue by yf13** [ceres-solver/ceres-solver#473]
I am rather new to this tool and the BAL problem, I can build and run the simple_bundle_adjuster sample successfully with problem-16-22106.

Now I am wondering how to use the bunder_adjuster.cc example successfully with other data sets such as problem-182-116770 or problem-356-226730?

It seems the following command doesn't work:

```bin/bundle_adjuster --input=../data/problem-182-116770-pre.txt --linear-solver=dense_schur --num-iterations=50```

However the following command converges after 50 iterations:

```bin/simple_bundle_adjuster ../data/problem-182-116770-pre.txt```

Are the two examples using different criterias for convergence? What are the proper use for bundle_adjuster example for other complex data sets?

thanks,
yf13

**Comment by sandwichmaker** [comment]
@yf13 what do you mean that command does not work? what happens when you run it?

**Comment by yf13** [comment]
@sandwichmaker the command works but it didn't converge. Guess the problem-182-116770 might be more complex and needs proper options to get converged.

**Comment by sandwichmaker** [comment]
as you can see, it has essentially converged. The exact convergence behaviour is tunable and I would not worry about the solver returning converged status or not.
