### ISSUE TITLE
Accessing gradient / residuals (/ jacobians) in IterationCallback

### ISSUE THREAD

**Issue by NikolausDemmel** [ceres-solver/ceres-solver#476]
I'm would like access the gradient (in tangent space, see #475) and residual vector in my IterationCallback for a) optional logging and b) custom abort criteria.

Could an additional API to (optionally) get access to the gradient and residual vector from the callbacks be considered? I personally don't need jacobians, but one might consider the add those as well.

I currently work around the issue by creating a second `Problem` object and calling `Evaluate` on that in the callback. For one, this can be significant additional computational cost, but moreover, this way I cannot compute these values for non-successful Levenberg Marquart steps, since then the state vector is not updated.

**Comment by sandwichmaker** [comment]
do you need access to the residual and gradient vectors or some norms of these vectors? accessing the gradient and residuals vectors directly is not a great idea since internally the problem gets reordered and reduced so interpreting the residual vector and the gradient vector anything other than just vectors will be hard without also having the reordering information.

What kind of termination are you trying to implement?

**Comment by NikolausDemmel** [comment]
Thanks for the quick response.

> do you need access to the residual and gradient vectors or some norms of these vectors? accessing the gradient and residuals vectors directly is not a great idea since internally the problem gets reordered and reduced so interpreting the residual vector and the gradient vector anything other than just vectors will be hard without also having the reordering information.

Good point, the ordering would be important. In what form could that be passed to the user? An array of the user supplied parameter block pointers and residualBlockIds, respectively? Is the order fixed during the optimization?

By "reduced" you mean constant parameter blocks or residuals with no non-constant parameters are missing? That would be fine. I see this as an advanced API where the user would need some understanding of the internal workings of the solver to interpret the data.

> What kind of termination are you trying to implement?

I'm looking at the block-wise gradient (interpreting different kind of parameter blocks differently, e.g. poses vs. points).

The other thing is logging block-wise gradient norm historgrams and residual histograms and checking for unexpected distributions (of outliers).

I'm still experimenting here.

**Comment by sandwichmaker** [comment]
@NikolausDemmel we do not use one Jacobian representation inside ceres but rather solver specific ones.
Yes the order is fixed during the optimization. 
I suggest you modify your copy of ceres to enable this if you want.  I strongly doubt we are going to leak the internal representations as part of the public API. This is going to create a maintenance nightmare long term.

**Comment by NikolausDemmel** [comment]
Looks like the full gradient vector is available explicitly in both the TrustRegion and LineSearch minimizer, but maybe not the residual vector (and jacobians).

But I can appreciate your reluctance to expose the internals for maintenance reasons.

Thanks anyway.
