### ISSUE TITLE
Simple "projection after update" for bounds 

### ISSUE THREAD

**Issue by NikolausDemmel** [ceres-solver/ceres-solver#477]
I have some simple bounds constraints (inverse depth parameterization for 3D points where the parameters should be >= 0). I was using Ceres' LowerBound, but I noticed decreased overall performance, and researching the issue I noticed that the implementation is currently somewhat broken (#187).

Conventional wisdom (among my colleagues) is that simply projecting the inverse depths onto the domain in each GN iteration, but ignoring them otherwise, works well enough. Could we consider a solver option to disable the line-search
https://github.com/ceres-solver/ceres-solver/blob/3ff12a878bf335dd3ea15944fe20648757c1bad8/internal/ceres/trust_region_minimizer.cc#L99
and whatever else the algorithm might do beyond projecting onto the domain in `Plus`? It seems to me that would be a simple-to-implement workaround until #187 is addressed.

I currently work around the issue with the following local parameterization, which I guess achieves the same thing. It works for me, but seems unnecessarily complicated. 

```cpp
class InverseDistanceParameterization : public ceres::LocalParameterization {
 public:
  bool Plus(const double *x, const double *delta,
            double *x_plus_delta) const override {
    *x_plus_delta = std::max(0.0, *x + *delta);
    return true;
  }

  bool ComputeJacobian(double const *T_raw,
                       double *jacobian_raw) const override {
    *jacobian_raw = 1;
    return true;
  }

  int GlobalSize() const override { return 1; }

  int LocalSize() const override { return 1; }
};
```

**Comment by sandwichmaker** [comment]
There are two different things here. The way the algorithm is broken has to do with its ability to find good solutions. I finds reasonable solutions but it can do better. That does not mean line search itself should not be done. The conventional wisdom around disabling the line search is wrong.

**Comment by NikolausDemmel** [comment]
> There are two different things here. The way the algorithm is broken has to do with its ability to find good solutions. I finds reasonable solutions but it can do better.

My evidence (and also that of other issues that have been raised around #187) suggests that it does find worse solutions. For me its worse in terms of a (cost-independent) error metric. Its worse than both an unconstrained version and the workaround above with the LocalParameterization that has the projection. (The reason the unconstrained version also works well here may be that the percentage of points that go out of the domain if unconstrained is quite low in this example, i.e. they may just be treated as outliers and due to robust norms not have a large influence on the result).

I have to admit my experiments here are not a thorough evaluation, but this is my observation on test data, nevertheless.

> That does not mean line search itself should not be done.

I didn't claim that the line search (if properly implemented) should not be done (I didn't read the referenced paper). What I'm saying is:

1. Not doing the line search ("just" projecting) works sufficiently well for some problems (from empirical evidence). It may very well work even better with a "properly" implemented line-search, I don't know.
2. Doing the line search as implemented right now leads to worse solutions.

So while properly fixing #187 may be significant effort, adding an option for this simplified variant seems to be simple (default can be as is now). IMHO this is a reasonable option even if #187 is addressed properly.

> The conventional wisdom around disabling the line search is wrong.

The conventional wisdom is not that the line search is wrong, but that for certain problems a simple projection can (also) work well. This is supported by working algorithms (not using Ceres). Moreover, while I'm not an expert for optimization at all, my mathematician colleague who is tells me, "simply doing the projection" is "reasonable" for my problem (BA-type optimization with inverse-distance point parameterization).

**Comment by sandwichmaker** [comment]
Turns out there a way to do this without affecting the API/introducing new variants. CL forth coming.

**Comment by sandwichmaker** [comment]
Set Solver::Options::max_num_line_search_step_size_iterations = 0 and you are good to go.

**Comment by NikolausDemmel** [comment]
I appreciate the followup very much, thank you!. I'll give it a try.
