### ISSUE TITLE
Build Error with VS2017 - Attempting to Reference Deleted Function

### ISSUE THREAD

**Issue by oracle3001** [ceres-solver/ceres-solver#480]
When I attempt to build off the latest commit on the master branch, I get the following error when using a Windows 10 box with VS2017 (v15.9.12) in 64-bit mode.

`Error	C2280	'std::unique_ptr<ceres::LocalParameterization,std::default_delete<_Ty>> &std::unique_ptr<_Ty,std::default_delete<_Ty>>::operator =(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)': attempting to reference a deleted function	ceres	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\xutility	2414`

**Comment by sandwichmaker** [comment]
can you provide more details about the file that was being compiled etc?

**Comment by sandwichmaker** [comment]
https://ceres-solver-review.googlesource.com/c/ceres-solver/+/15300 should fix this.
