### ISSUE TITLE
Build Issue with VS2017 due to change in VS handling of std:aligned_storage

### ISSUE THREAD

**Issue by oracle3001** [ceres-solver/ceres-solver#481]
When I attempt to build off the latest commit on the master branch, I get the following error when using a Windows 10 box with VS2017 (v15.9.12) in 64-bit mode.

`Error	C2338	You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior.	bundle_adjuster	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\type_traits	1271	`

**Comment by sandwichmaker** [comment]
@JohannesBeck can you take a look please?

**Comment by JohannesBeck** [comment]
I think, one have one of the following possibilities to fix it:

1. Use `#define _ENABLE_EXTENDED_ALIGNED_STORAGE`
This would make the alignment work correctly but has the drawback, that the compiled library is no longer ABI compatible to code compiled with an older version of MSVC.
2. Use `#define _DISABLE_EXTENDED_ALIGNED_STORAG`
This would use the wrong alignment but mixing the code with code compiled from a different version would work.
3. Disable Eigen alignment
I think, this would prevent Eigen from vectorization and all code using Ceres also need to disable alignment.

I think, the default choice should be option 1 (and maybe emitting a warning stating, that the library is not compatible with older versions of MSVC). One could also add a CMake flag to make it configurable.

**Comment by sandwichmaker** [comment]
@alexsmac wdyt?

**Comment by patrikhuber** [comment]
I get the same error when I try to compile a project that depends on Ceres. Latest VS 2019, 16.3.10 (not Preview), `cl.exe` `19.23.28107 for x64`.

I need to `#define` either of these two variables. Is it safe to define the first / either?

**Comment by moizsajid** [comment]
I also get the same error message in VS 2019

**Comment by JohannesBeck** [comment]
This should now be fixed (https://github.com/ceres-solver/ceres-solver/commit/f26f954105e0489b5d9963662791c29f88e3d122).
