### ISSUE TITLE
Missing cast in rotation.h

### ISSUE THREAD

**Issue by deutschepost** [ceres-solver/ceres-solver#497]
[In Line 310 of rotation.h](https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/rotation.h#L310) the `0.0` should be cast to T, because the `operator<` may not be defined if the the type of `0.0` differs from the type T.

` T(2.0) * ((cos_theta < 0.0)`
Change to:
`T(2.0) * ((cos_theta < T(0.0))`

**Comment by sandwichmaker** [comment]
This is fixed at head now. Thanks for the bug report!
