### ISSUE TITLE
docker version runs even faster than on native os?

### ISSUE THREAD

**Issue by ZhaoqunZhong** [ceres-solver/ceres-solver#503]
Hi guys, 

I wanted to test cere-solver in docker environment, so I built an image with this docker file:

```
FROM ubuntu:16.04

MAINTAINER Zhaoqun Zhong <zhongzhaoqun1991@gmail.com>

USER root
ARG NUM_CORES=4

RUN apt-get update -q && \
    apt-get install -y --fix-missing --no-install-recommends \
    # Basics
    ca-certificates wget curl build-essential checkinstall unzip autoconf automake libtool g++ yasm cmake git \
    # google-glog + gflags
    libgoogle-glog-dev \
    # BLAS & LAPACK
    libatlas-base-dev \
    # Eigen3
    libeigen3-dev \
    # SuiteSparse and CXSparse (optional)
    # - If you want to build Ceres as a *static* library (the default)
    #   you can use the SuiteSparse package in the main Ubuntu package
    #   repository:
    libsuitesparse-dev \
    # - However, if you want to build Ceres as a *shared* library, you must
    #   add the following PPA:
    #sudo add-apt-repository ppa:bzindovic/suitesparse-bugfix-1319687
    #sudo apt-get update
    #sudo apt-get install libsuitesparse-dev
    # Sphinx (for documentation)
    python-sphinx


WORKDIR /tmp

COPY ./ceres-solver-1.14.0 ./ceres-solver-1.14.0

RUN cd ceres-solver-1.14.0 && \
    mkdir build && \
    cd build && \
    cmake -DOPENMP=OFF \
          -DCXX11=ON \
          -DBUILD_DOCUMENTATION=ON \
          .. && \
    make -j $NUM_CORES && \
    make test && \
    make install
```

And I tried to run the example:
 
`bin/simple_bundle_adjuster ../ceres-solver-1.14.0/data/problem-16-22106-pre.txt`

on both Mac and Ubuntu16. Surprisingly, this is the performance matrix(time in seconds) I got:

|   | Mac | Ubuntu16   |
| :------------: | :------------: | :------------: |
| Run in docker   | 1.5s  |  0.84s |
| Run on host OS |50.5s   | 1.10s  |

Run with docker is supposed to reduce the performance, but on both systems the performance actually improved. Can anyone tell me what happened here? Appreciate the help!

**Comment by sandwichmaker** [comment]
Different compiler/flag setting is all I can think of. It should certainly not take 50 seconds, that indicates a problem.

**Comment by ZhaoqunZhong** [comment]
> Different compiler/flag setting is all I can think of. It should certainly not take 50 seconds, that indicates a problem.
Thanks, 

I installed ceres with homebrew on Mac, so I don't know exactly what happened there. But with Ubuntu16 host OS, the major difference I noticed is the cmake flag -DOPENMP=OFF and -DCXX11=ON. So I guess the problem comes from openmp? I wonder why these flags value are not set in this way by default, since they can bring such obvious performance improvement.

**Comment by sandwichmaker** [comment]
I am having some xcode trouble, will replicate as soon as I can.

**Comment by sandwichmaker** [comment]
@alexsmac are you able to replicate this problem?

**Comment by sandwichmaker** [comment]
@ZhaoqunZhong on my mac, building from source I see 1.1s on that example. Am I understanding this correctly that you see the problem with openmp enabled?

**Comment by ZhaoqunZhong** [comment]
@sandwichmaker Thanks for your follow-up, but openmp is used for multi threading, right? So this means turning on openmp actually downgrades the performance?

**Comment by sandwichmaker** [comment]
@ZhaoqunZhong are you sure that you are not running this in debug mode? also what happens if you use a single thread?

**Comment by sandwichmaker** [comment]
Closing because of lack of response. Please re-open when you have more information.
