### ISSUE TITLE
When I run Program on ceres2.0.0(arm64-v8a), the program crashed

### ISSUE THREAD

**Issue by PotterSu** [ceres-solver/ceres-solver#505]
Hello,
I solve my problem on ceres2.0.0（arm64-v8a）, the program crashed, but it works on armeabi-v7a.
This is my code for adding AutoDiffCostFunction and solve process by SPARSE_NORMAL_CHOLESKY.
![image](https://user-images.githubusercontent.com/26756937/64851911-ef2ae300-d64a-11e9-81bf-274c5847c265.png)
![image](https://user-images.githubusercontent.com/26756937/64851985-1681b000-d64b-11e9-84b1-e9b3f36d80e3.png)
And it crashed directly.
![image](https://user-images.githubusercontent.com/26756937/64851556-39f82b00-d64a-11e9-8246-7bd7aeeb64b8.png)
I guess the memory leads to the crash. Because I decrease the number of Parameter blocks to 724, it can work well. And when I increase the number of Parameter blocks to 7000, it break down. But no matter 7000 or 724, both of them work well on armeabi-v7a platform.
![image](https://user-images.githubusercontent.com/26756937/64852340-c6571d80-d64b-11e9-81e9-d74e2f1916f8.png)
![image](https://user-images.githubusercontent.com/26756937/64852369-d66efd00-d64b-11e9-8aac-c1c534a38496.png)

Hope for your response and best wishes.

**Comment by sandwichmaker** [comment]
@PotterSu these questions are better posted on the mailinglist. Also not enough detail here to debug this.

**Comment by sandwichmaker** [comment]
Going to close it since there are no further details.
