### ISSUE TITLE
Installation fails at `make install`  on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by normscully** [ceres-solver/ceres-solver#506]
Hi, 

im trying to install ceres-solver following [this](http://ceres-solver.org/installation.html#local-installations) guide. 
I´m running Ubuntu 16.04.5 LTS, dependencies are all installed and up-to-date.

Eigen 3.3~beta1-2
Cmake 3.5.1
gcc 5.4
Suitparse 1:4.4.6-1

Compilation runs through without errors as does make test. 
`make install` fails at installing the project with a CMake Error: 

```
`CMake Error at cmake_install.cmake:36 (file):
  file INSTALL cannot copy file
  "/home/user1/ceres-solver/include/ceres/autodiff_cost_function.h" to
  "/usr/local/include/ceres/autodiff_cost_function.h".



Makefile:71: recipe for target 'install' failed
make: *** [install] Error 1
```
`sudo make install` fails without even building:
```
CMake Error: The source directory "/home/user1/ceres-solver" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Makefile:2866: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
```
~/ceres-solver does contain CMakeLists.txt

This is when cloning the GIT repository, following the link in the installation guide and downloading the tar version, the installation also fails with a `permission denied` when trying to copy files to /usr/local/, sudo make install fails with the same error as above. 

Would be thankful for any help, 
best regards

**Comment by alexsmac** [comment]
I can't replicate this on a default 16.04 install, but I would assume that this is a file permissions issue depending upon your system configuration/filesystem.  Try `sudo ls /home/user1/ceres-solver`, if that fails then that's your problem.

Depending upon what you are/are not able to change in terms of the permissions/configuration of your machine, you can also install Ceres to any location via the `CMAKE_INSTALL_PREFIX` variable, and you can also export the build directory to the CMake cache via `EXPORT_BUILD_DIR`, both of which are covered in more detail in the Ceres docs

**Comment by normscully** [comment]
@alexsmac Thanks for the quick reply, that really seems to be the problem.
