### ISSUE TITLE
Wrong dependency paths are recorded in CeresConfig.cmake

### ISSUE THREAD

**Issue by avostrik** [ceres-solver/ceres-solver#507]
When building Ceres as part of Poky SDK for cross-compilation, generated CeresConfig.cmake records either:
 - absolute path of current user, for example: /home/${USER}/${POKY_DIR}/build/tmp/work/aarch64-poky-linux/ceres-solver/1.14-r0/recipe-sysroot/usr/share/eigen3/cmake
 - absolute path as if running on host, for example: /usr/share/eigen3/cmake

Both paths are wrong when Poky SDK unpacked on another PC for cross-compilation.
In first case path does not exist.
In second case build fails with -Werror due to: 'cc1plus: error: include location "/usr/include/eigen3" is unsafe for cross-compilation [-Werror=poison-system-directories]'

Affected variables all that are resolved with value from current build:
Eigen3: @Eigen3_DIR@ and @EIGEN_INCLUDE_DIR@
GLOG: @glog_DIR@
GFLAGS: @gflags_DIR@ and @GFLAGS_INCLUDE_DIR@

May be others, following same pattern.

CMake command find_dependency() may be a better way to implement dependency lookup.

Or at least recorded paths must take into account CMAKE_SYSROOT that is set by poky SDK environment setup script and other dependency resolution variables like CMAKE_FIND_ROOT_PATH*

Poky SDK installer built as described here: https://www.yoctoproject.org/docs/2.1/sdk-manual/sdk-manual.html chapter A.2

**Comment by axiguaa** [comment]
could you tell me where to find CeresConfig.cmake or  ceres-config.cmake, thank you!

**Comment by avostrik** [comment]
It is generated during install step from: https://github.com/ceres-solver/ceres-solver/blob/master/cmake/CeresConfig.cmake.in

See CMakeLists.txt line 728

**Comment by sandwichmaker** [comment]
@alexsmac PTAL

**Comment by alexsmac** [comment]
In conjunction with the updates that were merged to master previously, [this CL](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/17381) should remove all paths from CeresConfig *provided that a new enough version of glog built with CMake is available* - this is not the case on at least 18.04 and so we will not be removing support for the FindGlog.cmake module that ships with Ceres.

**Comment by alexsmac** [comment]
Closing as the CL has been merged into master
