### ISSUE TITLE
Pose Estimation in ceres

### ISSUE THREAD

**Issue by SubMishMar** [ceres-solver/ceres-solver#508]
Ceres works fine for me. I am using to estimate [R,T]  but I do not understand where in the code (internally) or when does ceres apply the constraints on R being a rotation matrix? I just simply solve it in a least square way without telling ceres that R is a rotation matrix and has some special characteristics. Although I am getting correct results, I am curious to know if this is rather fortuitous or ceres does something internally and knows in advance that R is a rotation matrix. Here is the chunk of code where I am using ceres: https://github.com/SubMishMar/cam_lidar_calib/blob/7684abb9dcbfdcc5cf46a129cd3a5dda32832f73/src/cam_lidar_calib_node.cpp#L285-L331.

Please help me understand how ceres handles rotation matrices, just as any other data points or as a special construct which has certain constraints to respect.

**Comment by sandwichmaker** [comment]
Closing as it is already addressed on the mailinglist,
