### ISSUE TITLE
Question about support for iterative linear solver

### ISSUE THREAD

**Issue by Beniko95J** [ceres-solver/ceres-solver#510]
Hi,

I need to solve an ultra large normal equation Hx=b,. and I want to use iterative linear solver to speed up. Does ceres-solver support iterative linear solver like the Gauss–Seidel method?

Thank you.

**Comment by sandwichmaker** [comment]
Ceres does support iterative solves. But it does not support Gauss Seidel. 
Have a look at CGNR and either JACOBI or SUBSET preconditioners.
