### ISSUE TITLE
CX_SPARSE faster than SUITE_SPARSE? 

### ISSUE THREAD

**Issue by copyme** [ceres-solver/ceres-solver#511]
Is there any reason why `CX_SPARSE` is much faster than `SUITE_SPARSE` while using `SPARSE_NORMAL_CHOLESKY`? No extra options set to the solver. Does `SUITE_SPARSE` work better with problems of certain structure?

**Comment by sandwichmaker** [comment]
This should not happen. Unless your BLAS is compiled in debug mode is reference BLAS for some reason. It is possible that the matrix is tiny.. could you share more details?

**Comment by copyme** [comment]
@sandwichmaker for now it looks like a bug in openSUSE 15.1, I just ran my code on the newest Ubuntu and the problem does not exist there. I will contact openSUSE developers and try to figure out with them what is going on. Switching to something like Ubuntu is far from being an option.

**Comment by copyme** [comment]
@sandwichmaker should I close the issue?

**Comment by sandwichmaker** [comment]
Yes this sounds like reference BLAS is being linked into SuiteSparse rather than an optimized BLAS.

**Comment by copyme** [comment]
@sandwichmaker  It looks like there is a problem with openBLAS in general, SuiteSparse from version 5.6 does not recommend it anymore. See here. https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/1 It looks like openBLAS slows things down.

**Comment by copyme** [comment]
I just recompiled SuiteSparse with MKL. The speed up is indeed significant.

**Comment by DrTimothyAldenDavis** [comment]
CXSparse doesn't use the BLAS.  It's part of SuiteSparse.  By the term "SUITE_SPARSE" above, I assume you mean CHOLMOD (also in SuiteSparse).  It uses the BLAS, so if the BLAS is slow, CHOLMOD will be slow but CXSparse will be unaffected.

**Comment by copyme** [comment]
@DrTimothyAldenDavis you are right. In my case switching from openBLAS 0.2 series to 0.3 helped but after moving to MKL I noticed even bigger improvement.
