### ISSUE TITLE
segment fault

### ISSUE THREAD

**Issue by garlinplus** [ceres-solver/ceres-solver#512]
When I run cartographer,there is a segment fault on ceres as followed:
Thread 2 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 572.576]
Eigen::internal::gemm_pack_rhs<double, int, Eigen::internal::const_blas_data_mapper<double, int, 0>, 4, 0, false, false>::operator() (
    this=this@entry=0xb68975ac, blockB=0xb687d500, rhs=..., 
    depth=depth@entry=48, cols=228, stride=stride@entry=0, 
    offset=offset@entry=0)
    at /home/samuel/Append/code/allwinner_r16/out/astar-robotvacuum_laser/staging_dir/target/usr/include/eigen3/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1995
1995	        blockB[count+0] = cj(dm0(k));
(gdb) bt
#0  Eigen::internal::gemm_pack_rhs<double, int, Eigen::internal::const_blas_data_mapper<double, int, 0>, 4, 0, false, false>::operator() (
    this=this@entry=0xb68975ac, blockB=0xb687d500, rhs=..., 
    depth=depth@entry=48, cols=228, stride=stride@entry=0, 
    offset=offset@entry=0)
    at /home/samuel/Append/code/allwinner_r16/out/astar-robotvacuum_laser/staging_dir/target/usr/include/eigen3/Eigen/src/Core/products/GeneralBlockPanelKernel.h:1995
#1  0x001bb170 in Eigen::internal::product_triangular_matrix_matrix<double, int, 1, true, 0, false, 0, false, 0, 0>::run (_rows=<optimized out>, 
    _cols=<optimized out>, _depth=<optimized out>, _lhs=<optimized out>, 
    lhsStride=<optimized out>, _rhs=<optimized out>, 
    rhsStride=<optimized out>, _res=<optimized out>, 
    resStride=<optimized out>, alpha=<optimized out>, blocking=...)
    at /home/samuel/Append/code/allwinner_r16/out/astar-robotvacuum_laser/staging_dir/target/usr/include/eigen3/Eigen/src/Core/products/TriangularMatrixMatrix.h:171
#2  0x0034e398 in Eigen::internal::householder_qr_inplace_blocked<Eigen::Matrix<double, -1, -1, 0, -1, -1>, Eigen::Matrix<double, -1, 1, 0, -1, 1>, double, true>::run(Eigen::Matrix<double, -1, -1, 0, -1, -1>&, Eigen::Matrix<double, -1, 1, 0, -1, 1>&, int, double*) ()
#3  0x0034e600 in Eigen::HouseholderQR<Eigen::Matrix<double, -1, -1, 0, -1, -1> >::HouseholderQR<Eigen::Matrix<double, -1, -1, 0, -1, -1> >(Eigen::EigenBase<Eig---Type <return> to continue, or q <return> to quit---
en::Matrix<double, -1, -1, 0, -1, -1> > const&) ()
#4  0x0034c0b8 in ceres::internal::DenseQRSolver::SolveUsingEigen(ceres::internal::DenseSparseMatrix*, double const*, ceres::internal::LinearSolver::PerSolveOptions const&, double*) ()
#5  0x0034c250 in ceres::internal::DenseQRSolver::SolveImpl(ceres::internal::DenseSparseMatrix*, double const*, ceres::internal::LinearSolver::PerSolveOptions const&, double*) ()
#6  0x0034b778 in ceres::internal::TypedLinearSolver<ceres::internal::DenseSparseMatrix>::Solve(ceres::internal::LinearOperator*, double const*, ceres::internal::LinearSolver::PerSolveOptions const&, double*) ()
#7  0x002fd100 in ceres::internal::LevenbergMarquardtStrategy::ComputeStep(ceres::internal::TrustRegionStrategy::PerSolveOptions const&, ceres::internal::SparseMatrix*, double const*, double*) ()
#8  0x002eaa80 in ceres::internal::TrustRegionMinimizer::ComputeTrustRegionStep() ()

#9  0x002eae90 in ceres::internal::TrustRegionMinimizer::Minimize(ceres::internal::Minimizer::Options const&, double*, ceres::Solver::Summary*) ()
#10 0x002d5208 in ceres::Solver::Solve(ceres::Solver::Options const&, ceres::Problem*, ceres::Solver::Summary*) ()
#11 0x002d55c8 in ceres::Solve(ceres::Solver::Options const&, ceres::Problem*, ceres::Solver::Summary*) ()

#12 0x001bfa04 in cartographer::mapping::optimization::OptimizationProblem2D::Solve (this=this@entry=0x4130a0, constraints=..., trajectories_state=..., 
---Type <return> to continue, or q <return> to quit---
    landmark_nodes=...)
    at /home/samuel/Append/code/allwinner_r16/out/astar-robotvacuum_laser/compile_dir/target/cartographer/cartographer/mapping/internal/optimization/optimization_problem_2d.cc:308
#13 0x00204df8 in cartographer::mapping::PoseGraph2D::RunOptimization (
    this=this@entry=0x40ac10)
    at /home/samuel/Append/code/allwinner_r16/out/astar-robotvacuum_laser/compile_dir/target/cartographer/cartographer/mapping/internal/2d/pose_graph_2d.cc:828
#14 0x00205264 in cartographer::mapping::PoseGraph2D::HandleWorkQueue (
    this=0x40ac10, result=...)
    at /home/samuel/Append/code/allwinner_r16/out/astar-robotvacuum_laser/compile_dir/target/cartographer/cartographer/mapping/internal/2d/pose_graph_2d.cc:442
#15 0x0027abcc in std::function<void (std::vector<cartographer::mapping::PoseGraphInterface::Constraint, std::allocator<cartographer::mapping::PoseGraphInterface::Constraint> > const&)>::operator()(std::vector<cartographer::mapping::PoseGraphInterface::Constraint, std::allocator<cartographer::mapping::PoseGraphInterface::Constraint> > const&) const (__args#0=..., this=<optimized out>)
    at /home/samuel/Append/code/allwinner_r16/prebuilt/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain/arm-openwrt-linux-muslgnueabi/include/c++/6.4.1/functional:2127
#16 cartographer::mapping::constraints::ConstraintBuilder2D::RunWhenDoneCallback (this=0x40ac98)
    at /home/samuel/Append/code/allwinner_r16/out/astar-robotvacuum_laser/compil---Type <return> to continue, or q <return> to quit---
e_dir/target/cartographer/cartographer/mapping/internal/constraints/constraint_builder_2d.cc:291
#17 0x00271098 in std::function<void ()>::operator()() const (this=0x406a40)
    at /home/samuel/Append/code/allwinner_r16/prebuilt/gcc/linux-x86/arm/toolchain-sunxi-musl/toolchain/arm-openwrt-linux-muslgnueabi/include/c++/6.4.1/functional:2127
#18 cartographer::common::Task::Execute (this=0x406a40)
    at /home/samuel/Append/code/allwinner_r16/out/astar-robotvacuum_laser/compile_dir/target/cartographer/cartographer/common/task.cc:96
#19 0x0026e928 in cartographer::common::ThreadPoolInterface::Execute (
    this=this@entry=0x407fec, task=<optimized out>)
    at /home/samuel/Append/code/allwinner_r16/out/astar-robotvacuum_laser/compile_dir/target/cartographer/cartographer/common/thread_pool.cc:33
#20 0x0026eba8 in cartographer::common::ThreadPool::DoWork (this=0x407fec)
    at /home/samuel/Append/code/allwinner_r16/out/astar-robotvacuum_laser/compile_dir/target/cartographer/cartographer/common/thread_pool.cc:102
#21 0xb6b97ea0 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by sandwichmaker** [comment]
Sorry this is not enough to replicate this. Maybe start with the cartographer team and maybe they can produce a replication?

**Comment by sandwichmaker** [comment]
Closing because there isn't enough information to replicate.
