### ISSUE TITLE
MacOS make test Segmentation fault: 11 on test 24(dogleg_strategy_test)

### ISSUE THREAD

**Issue by RaymondYu94** [ceres-solver/ceres-solver#513]
./dogleg_strategy_test
Running main() from gmock_main.cc
[==========] Running 6 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 4 tests from DoglegStrategyFixtureEllipse
[ RUN      ] DoglegStrategyFixtureEllipse.TrustRegionObeyedTraditional
[       OK ] DoglegStrategyFixtureEllipse.TrustRegionObeyedTraditional (0 ms)
[ RUN      ] DoglegStrategyFixtureEllipse.TrustRegionObeyedSubspace
Segmentation fault: 11

**Comment by sandwichmaker** [comment]
thats odd, do you have any local modifications? also can you share the build log and any other replication instructions?

**Comment by keir** [comment]
Yes; this is unexpected. We'd like to fix this!

**Comment by alexsmac** [comment]
What version of macOS are you using @RaymondYu94?  Are you running the initial release of Catalina with Xcode 11?

I've also discovered segfaults in the dogleg tests with Eigen 3.3.7, the problem appears to originate within Eigen itself when invoking some SSE instructions and/or BLAS substitutions.  Interestingly, when using Eigen's master branch the dogleg test passes but the schur tests fail (again within Eigen).  Interestingly, using the 3.3 branch (which appears to be ahead of 3.3.7, but behind master) is even worse in terms of the number of Ceres test failures - both the schur tests *and* the dogleg test fail.

I have the following test matrix with Eigen 3.3.7 and Ceres master:

1) Catalina 10.15.0, Xcode 10.2.1, targetting sdk 10.14 (with 10.14 base SDK): all ceres tests pass :white_tick:
2) Catalina 10.15.0, XCode 11, targetting sdk 10.15 (with 10.15 base SdK): some ceres tests fail :x:
3) Catalina 10.15.0, XCode 11, targetting sdk 10.14 (with 10.15 base SDK): some ceres tests fail :x:
4) Mojave 10.14.6, Xcode 11, targetting sdk 10.14 (using 10.15 as base sdk): all ceres tests pass :white_tick:

I can't find any issues raised in Eigen's Bugzilla related to this yet, or anything on their mailing list.  However, a number of their tests are either failing to compile, or failing to run on (at least) a default Catalina test machine.

**Comment by alexsmac** [comment]
I've also just checked with the latest Catalina update (10.15.1) and at least the behaviour with Eigen 3.3.7 is unchanged.

**Comment by RaymondYu94** [comment]
@keir I use Catalina 10.15 with Xcode11.1 and latest ceres on homebrew.

**Comment by RaymondYu94** [comment]
@alexsmac 

> @keir I use Catalina 10.15 with Xcode11.1 and latest ceres on homebrew.

**Comment by alexsmac** [comment]
OK, this is actually a bug in the combination of macOS Catalina 10.15 and Xcode 11 which enabled `-fstack-check` by default which breaks alignment which in turn results in segfaults around SIMD instructions.  A CL is out for review [here](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/15940) to explicitly disable `-fstack-check` to avoid this problem.

**Comment by alexsmac** [comment]
The fix has now been merged into master, @RaymondYu94 please test and reopen if required.
