### ISSUE TITLE
Why Ceres uses SuiteSparse API without GPU support

### ISSUE THREAD

**Issue by copyme** [ceres-solver/ceres-solver#514]
My question is why Ceres does not use `cholmod` API over long it which can leverage GPU acceleration? Would not that speed up computations on machines with SuiteSparse compiled with CUDA and `CHOLMOD_USE_GPU` set to 1?

**Comment by sandwichmaker** [comment]
Hi @copyme mostly because none of us have experience with building CHOLMOD with GPU support, detecting it and using it. We will happily accept a patch that adds this capability along with  appropriate tests.

**Comment by copyme** [comment]
In this case I will have a look at this and try to see if I can be of any use.

**Comment by sandwichmaker** [comment]
That would be fantastic.!

**Comment by copyme** [comment]
@sandwichmaker a couple of weeks ago I had a look at the issue but the code was crashing without an obvious reason, and I did not have time to figure out what was wrong. I should have more time in January so hopefully I will make it work then.

**Comment by zjd1988** [comment]
Hi @sandwichmaker  , have you successfully compiled and used ceres with suitesparse(long integer version)?

**Comment by sandwichmaker** [comment]
no, we use the regular integer API.

**Comment by copyme** [comment]
@zjd1988 yes I did but the solver is crashing after just a few iterations from no clear reasons. Unfortunately, I have not had time to dig into this. I am busy with some other projects since weeks. Once I am done with the current work I will try to solve the problems.

**Comment by Seanmatthews** [comment]
@copyme Do you have a fork with your current progress?

**Comment by rancheng** [comment]
any progress?

**Comment by bellomo** [comment]
any progress?
