### ISSUE TITLE
Cholesky decomposition of covariance matrix block

### ISSUE THREAD

**Issue by Solonets** [ceres-solver/ceres-solver#515]
in the [example of 3d pose graph slam](https://github.com/ceres-solver/ceres-solver/blob/master/examples/slam/pose_graph_3d/pose_graph_3d.cc) a cholesky decomposition of constraint between 2 poses is used
```
const Eigen::Matrix<double, 6, 6> sqrt_information =
        constraint.information.llt().matrixL();
```
while this is a block of a full covariance matrix, which is not guaranteed to be positive-defined. Can you please clarify that?

**Comment by sandwichmaker** [comment]
@mvitus your code I believe?

**Comment by mvitus** [comment]
Ah, yes, we can only be guaranteed it is positive semi-definite. I used the LLT decomposition which requires positive definite because it was an easy one linear to compute a matrix to scale the errors that works except in degenerate cases.  I can switch it to something that works for positive semi-definite.  I'll send a CL later this week (need to set my machine back up).

**Comment by Solonets** [comment]
@mvitus I think I made my point poorly, the question is not about degenerate cases. 

Let's imagine pose graph with 2 poses, then covariance is 12x12 matrix and guaranteed to be positive-semi definite. The variance between 1st and second block though(top right corner), which is a variance of poses doesn't have any specific properties, in general, I can't see why the Cholesky decomposition is performed on this block(information of the constraint matrix).

I also run some tests (on c++ though) and eigen lot decomposition yields garbage for non-positive-definite matrices.

**Comment by mvitus** [comment]
> @mvitus I think I made my point poorly, the question is not about degenerate cases.
>
> Let's imagine pose graph with 2 poses, then covariance is 12x12 matrix and guaranteed to be positive-semi definite. The variance between 1st and second block though(top right corner), which is a variance of poses doesn't have any specific properties, in general, I can't see why the Cholesky decomposition is performed on this block(information of the constraint matrix).
>
> I also run some tests (on c++ though) and eigen lot decomposition yields garbage for non-positive-definite matrices.

I received this via email and I am not sure why this isn't showing up in the thread.  I wanted to post it before I responded.

**Comment by mvitus** [comment]
The covariance that is read from the g2o constraint files is the covariance of the measurement of the transformation between pose A and pose B.  It is not the cross covariance between the pose A and pose B.  

Let's take your example and let's assume a 1D example to make the notation easier.  Let's says someone gave you the pose of A and B, p_a and p_b respectively, with a covariance matrix of size 2x2.  Then the pose graph constraint measurement would be: y = p_b - p_a.  In matrix notation that would be

y = p_b - p_a = [1 -1] * [p_a p_b]^T = [1 -1] * X^T

we are given the covariance matrix of X as C_x.  To compute the covariance of y, C_y, you only need to apply the linear transformation rules, so the covariance of y is:

C_y = [1 -1] * C_x * [1 - 1]^T = C_a - 2 * C_ab + C_b

You can show that C_y is also positive semidefinite.

A quick note about the full 3D case. You need to take care when computing the difference between the rotation.  It isn't always a simple difference.

**Comment by Solonets** [comment]
> It is not the cross covariance between the pose A and pose B.

Yes, I got this. That why I deleted the message. But thank you for your clarification, it's very useful.
