### ISSUE TITLE
Segmentation fault on Solve()

### ISSUE THREAD

**Issue by thezest76** [ceres-solver/ceres-solver#517]
Thanks for the nice SW,

I am having a weird segmentation fault issue when Solve() is called in my custom function.
However, the same pieces of code runs perfectly OK when the code is written as an independent cpp and compiled to an executable file.

For example, Example (1) below runs OK.
However, Example (2) crashes with a segmentation fault message when ceres::Solve(options, &problem, &summary) line is called. The only difference is that Example (2) is called from somewhere in my SLAM system.
I use Ubuntu 16.04 + ROS Kinetic + CeresSolver 1.14.0

Could you please help me to resolve this issue ?
Please let me know if more information is needed.

Best, 

#########################################################
#      Example (1)           main.cpp below runs ok
#########################################################

int main(int argc, char** argv )
{
	ceres::Problem problem;
	ceres::LossFunction* loss_function = new ceres::HuberLoss(2.0) ;

	ifstream ceres_data ;
	ceres_data.open("data.txt");

	double campose[6] = {0,};
	double xn, yn, Xw, Yw, Zw;
	std::string line;
	while (std::getline(ceres_data, line))
	{
	    std::istringstream iss(line);
	    if (!(iss >> xn >> yn >> Xw >> Yw >> Zw )) { break; } 

		ceres::CostFunction* cost_function =
				imgProj_Rt::Create(xn, yn, Xw, Yw, Zw);
		problem.AddResidualBlock(cost_function,
								loss_function, 
								&campose[0] );
	}

    // solve problem
	ceres::Solver::Options options;
	options.linear_solver_type = ceres::DENSE_SCHUR;
	ceres::Solver::Summary summary;

cout << "problem:" << problem.NumParameterBlocks() <<  "\n"
				   << problem.NumParameters() << "\n"
				   << problem.NumResidualBlocks() << "\n"
				   << problem.NumResiduals() << endl;
	ceres::Solve(options, &problem, &summary) ;

	std::cout << summary.FullReport() << "\n";
	return 1;
}

############################################################################
#     Example (2)     
#     The same code wrapped with a subfunction below crashes  w/ a segmentation fault message on Sove()
############################################################################

int MyCeresFunc()
{
	ceres::Problem problem;
	ceres::LossFunction* loss_function = new ceres::HuberLoss(2.0) ;

	ifstream ceres_data ;
	ceres_data.open("data.txt");

	double campose[6] = {0,};
	double xn, yn, Xw, Yw, Zw;
	std::string line;
	while (std::getline(ceres_data, line))
	{
	    std::istringstream iss(line);
	    if (!(iss >> xn >> yn >> Xw >> Yw >> Zw )) { break; }

		ceres::CostFunction* cost_function =
				imgProj_Rt::Create(xn, yn, Xw, Yw, Zw);
		problem.AddResidualBlock(cost_function,
								loss_function, 
								&campose[0] );
	}

    // solve problem
	ceres::Solver::Options options;
	options.linear_solver_type = ceres::DENSE_SCHUR;
	ceres::Solver::Summary summary;

cout << "problem:" << problem.NumParameterBlocks() <<  "\n"
				   << problem.NumParameters() << "\n"
				   << problem.NumResidualBlocks() << "\n"
				   << problem.NumResiduals() << endl;
	ceres::Solve(options, &problem, &summary) ;

	std::cout << summary.FullReport() << "\n";
	return 1;
}

**Comment by sandwichmaker** [comment]
can you compile in debug mode and look at the stack trace?

**Comment by NeroBurner** [comment]
@thezest76 could you provide a minimal compile-able and run-able project with example data

something like that https://github.com/NeroBurner/hunter_ceres_example but also with `data.txt`

**Comment by sandwichmaker** [comment]
Closing because of lack of response.

**Comment by GoroYeh-HRI** [comment]
Hi,

I got aborted error when running COLMAP bundle_adjuster:

![image](https://github.com/ceres-solver/ceres-solver/assets/137837175/9d1e4a3f-3ed5-45f4-b5ac-d20bea0d44c8)

The output message I got from `ceres::Solve()` is very short:
![image](https://github.com/ceres-solver/ceres-solver/assets/137837175/4b518a50-dc53-40a0-877f-4ce34899f258)

However, I do not know why ceres::Solve() aborted because I cannot see what's going on in ceres::Solve().
Do you have idea on what might go wrong?

**Comment by NeroBurner** [comment]
How was colmap built? Which version of cereal silver, suite sparse, Metis

Which Soler type was enabled? I had a problem with ceres-solver 2..2.0 with suitesparse-metis 5.4.0 with Metis 5.1.0 if NESDIS was enabled

See: https://github.com/jlblancoc/suitesparse-metis-for-windows/issues/123

I also recommend opening another issue, as this one was already closed and I see no mention of colmap in here
