### ISSUE TITLE
My Android build error

### ISSUE THREAD

**Issue by bittergourd1224** [ceres-solver/ceres-solver#518]
**I want to get libceres.so and use it in Android. My building environment is Ubuntu 16.04. 
The complete command I used for building is:**
`git clone https://ceres-solver.googlesource.com/ceres-solver`
`export NDK_DIR=~/Android/Sdk/ndk-bundle`
`cd ceres-solver`
`mkdir build`
`cd build`

`cmake \`
`-DCMAKE_TOOLCHAIN_FILE=$NDK_DIR/build/cmake/android.toolchain.cmake \`
`-DEIGEN_INCLUDE_DIR=/usr/local/include/eigen3/ \`
`-DANDROID_ABI=armeabi-v8a \`
`-DANDROID_STL=c++_shared \`
`-DANDROID_NATIVE_API_LEVEL=android-27 \`
`-DBUILD_SHARED_LIBS=ON \`
`-DMINIGLOG=ON \`
`~/packages/ceres-solver/`

`make`

**An error appeared in the last step:**
`[ 28%] Linking CXX shared library ../../lib/libgtest.so
/usr/bin/ld: /usr/local/lib/libgflags_nothreads.a(gflags.cc.o): relocation R_X86_64_32 against '.bss' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libgflags_nothreads.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
internal/ceres/CMakeFiles/gtest.dir/build.make:122: recipe for target 'lib/libgtest.so' failed
make[2]: *** [lib/libgtest.so] Error 1
CMakeFiles/Makefile2:1048: recipe for target 'internal/ceres/CMakeFiles/gtest.dir/all' failed
make[1]: *** [internal/ceres/CMakeFiles/gtest.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2`

**It seems that the error is caused linking with libgtest or libgflags. I installed them using apt-get install, so it's weird the make process doesn't pass. And there aren't any similar problems asked. Hope you can help me with this.**

**Comment by alexsmac** [comment]
If gflags is compiled statically without `-fPIC` then you will not be able to link against it in a shared library.  However, if you're trying to link a version of Ceres compiled for ARM against a version of gflags compiled for x86 from your host you have a second problem - those are incompatible architectures.  This shouldn't actually be happening, as the `android.toolchain.cmake` sets the `CMAKE_FIND_ROOT_PATH` and `CMAKE_SYSTEM_LIBRARY_PATH` vars amongst others to exclude the host system paths - however that doesn't appear to be working in your case for some reason.

The version of gtest used by Ceres is shipped with, and compiled by, Ceres to ensure that it is compiled with exactly the same options as Ceres as recommend by the gtest docs, so having it installed in the system isn't actually relevant or required.

You can remove the requirement to use gflags by disabling `BUILD_TESTING` in Ceres' CMake configuration.  I'm going to close this issue, as although there may be an issue here, it doesn't appear to be an issue with Ceres.

**Comment by bittergourd1224** [comment]
Thanks very much for your advice, especially for the reason behind it :smile: I disabled gflags in cmake and now everything went well. Very appreciate for your help!
