### ISSUE TITLE
Building with clang-cl on windows, cmake error about msvc compiler version

### ISSUE THREAD

**Issue by elegracer** [ceres-solver/ceres-solver#521]
When I used clang-cl frontend and msvc backend to build ceres, a cmake fatal error occured

```
Invalid CMAKE_CXX_COMPILER_VERSION: 8.0.1.  Ceres requires at least MSVC 2013 Update 4+
```

and the reason is

```
if (MSVC AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 12.0)
  message(FATAL_ERROR "Invalid CMAKE_CXX_COMPILER_VERSION: "
    "${CMAKE_CXX_COMPILER_VERSION}. Ceres requires at least MSVC 2013 Update 4+")
endif()
```

Even if I use clang-cl as frontend, `MSVC` will be defined.

The right way to deal with this kind of situation is to replace `MSVC` to `CMAKE_CXX_COMPILER_ID MATCHES MSVC`, so the final version will be

```
if (CMAKE_CXX_COMPILER_ID MATCHES MSVC AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 12.0)
  message(FATAL_ERROR "Invalid CMAKE_CXX_COMPILER_VERSION: "
    "${CMAKE_CXX_COMPILER_VERSION}. Ceres requires at least MSVC 2013 Update 4+")
endif()
```

**Comment by sandwichmaker** [comment]
@elegracer please consider sending us a change on gerrit.

**Comment by alexsmac** [comment]
CL raised [here](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/17380)

**Comment by alexsmac** [comment]
Closing as the CL has been merged in master
