### ISSUE TITLE
cross-compile : ‘is_trivially_default_constructible’ is not a member of ‘std’

### ISSUE THREAD

**Issue by awdsxs123** [ceres-solver/ceres-solver#524]
when I use  gcc 4.9.4(arm-linux-gnueabi) to  make ceres-solver ,  it send me some error   ‘is_trivially_default_constructible’ is not a member of ‘std’
but wo write "set(CMAKE_CXX_STANDARD 11)" in cmakelist, command has already showed "Building with c++11"
then I don't now how to solve this error

**Comment by awdsxs123** [comment]
I find 'tyoe_traits.h' is different bettwen in gcc 5.4 and gcc 4.9.4 .

**Comment by alexsmac** [comment]
As you've identified, the problem is that old versions of GCC were not fully C++11 compliant and the master branch of Ceres (and all future releases) require a fully C++11 compliant compiler.
