### ISSUE TITLE
Handling of paths with whitespaces in generated CeresConfig.cmake

### ISSUE THREAD

**Issue by patrikhuber** [ceres-solver/ceres-solver#526]
Hi,

CMake gives me the following warning during the Configure phase:

```
CMake Warning (dev) at C:/Users/Patrik/ceres/build-vs2019/CeresConfig.cmake:176:
  Syntax Warning in cmake code at column 90

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  C:/Users/Patrik/vcpkg/scripts/buildsystems/vcpkg.cmake:247 (_find_package)
  CMakeLists.txt:46 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

If I go to line 176 in my generated `CeresConfig.cmake`, it's the following:

```
list(APPEND EIGEN_INCLUDE_DIR_HINTS C:/Users/Patrik/my path here with whitespaces (and parentheses)/external/something/eigen)
```

I am not sure how this line is generated but my Eigen is in a path on the disk that contains whitespaces as well as parenthesis - and it looks to me like either of these is generating the warning.

My guess is that Ceres should probably use quotes when generating these paths?

I'd consider this minor as it still all seems to work but I thought it'd be a good idea to report it nonetheless.

**Comment by patrikhuber** [comment]
Actually, I'm not sure what changed (perhaps that I am now trying to use Ceres from the build directory with `EXPORT_BUILD_DIR=TRUE`), but this now turned into a hard error when trying to import Ceres into my own project.

```

CMake Error at C:/Users/Patrik/ceres/build-vs2019/CeresConfig.cmake:176 (list):
  Syntax error in cmake code at

    C:/Users/Patrik/ceres/build-vs2019/CeresConfig.cmake:176

  when parsing string

    C:\Users\Patrik\my

  Invalid character escape '\U'.
```

Anyway I will just migrate to a directory without whitespace in it to work around this.

**Comment by patrikhuber** [comment]
Actually the second issue is a different one. The error comes from parsing the `C:\U` in `C:\Users\...`.

These should be forward slashes (or perhaps a quoted string).

**Comment by alexsmac** [comment]
@patrikhuber please try [this CL](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/16100), I think it will fix your problem.
