### ISSUE TITLE
Cmake script modification for "make install"

### ISSUE THREAD

**Issue by WsbPro** [ceres-solver/ceres-solver#527]
The new version of Ceres uses separate folder "Codegen" after commit https://github.com/ceres-solver/ceres-solver/commit/d1703db45a760c490072caf6f0b0894a68422976. But if you install the new version of ceres using "make install", the default configuration in cmakelist.txt (main cmakelist.txt in ceres root folder) forgets to copy the files in "Codegen" folder to Ceres install dir, and thus results in build errors in your applications.

I suggest add these after line 654 of cmakelist.txt:

file(GLOB CERES_PUBLIC_CODEGEN_HDRS ${Ceres_SOURCE_DIR}/include/ceres/codegen/*.h)
install(FILES ${CERES_PUBLIC_CODEGEN_HDRS} DESTINATION include/ceres/codegen)
file(GLOB CERES_PUBLIC_CODEGEN_INTERNAL_HDRS ${Ceres_SOURCE_DIR}/include/ceres/codegen/internal/*.h)
install(FILES ${CERES_PUBLIC_CODEGEN_INTERNAL_HDRS} DESTINATION include/ceres/codegen/internal)

**Comment by sandwichmaker** [comment]
Thanks for the suggestion.

https://github.com/ceres-solver/ceres-solver/commit/c56702aacc310c69078bcf2794e3cdaf823d7bbb

should fix this.

**Comment by wine3603** [comment]
I used the new version, 
but still faild in " make install"
```
CMake Error at cmake_install.cmake:154 (file):
  file INSTALL cannot find
  "/home/zhang-u16/deps/ceres-solver/cmake/codegen_include.h.in".
```

**Comment by sandwichmaker** [comment]
This is likely related to the patch that was just added to ceres today. @darglein  can you take a look please.

**Comment by darglein** [comment]
Thanks for opening this issue. This should be fixed with https://ceres-solver-review.googlesource.com/c/ceres-solver/+/16660

**Comment by wine3603** [comment]
THanks a lot  @darglein @sandwichmaker 
this fixed my problem!
