### ISSUE TITLE
Make ceres::Problem movable

### ISSUE THREAD

**Issue by jbriales** [ceres-solver/ceres-solver#528]
I saw Ceres 2.0 is expected to leverage more of C++11.
I wonder if getting move-semantics for ceres::Problem is in the roadmap.
The main motivation is to be able to do sth like:

```
#include <ceres/ceres.h>

ceres::Problem createCeresProblem() {
  ceres::Problem problem{};
  // ...
  return problem;
}

int main(int argc, char* argv[]) {
  ceres::Problem problem = createCeresProblem();
  // ...
  return 0;
}
```

**Comment by sandwichmaker** [comment]
That sounds like a great idea, want to send us a change?

**Comment by jbriales** [comment]
I can give it a try when I get a spare moment (which I cannot ensure will be anytime soon though... :( ).
But I'm happy to know you'd be willing to take this change in.

From a quick look to the definition of `ceres::Problem` it seems like all the information lies within `internal::scoped_ptr<internal::ProblemImpl> problem_impl_;`, so that's what we'd need to move.
I'm not familiar with your `internal::scoped_ptr` but from a quick look it seems to me this aligns with a `std::unique_ptr`? If that's the case, would it be possible to refactor `internal::scoped_ptr` to `std::unique_ptr` as this already implements move semantics?

**Comment by sandwichmaker** [comment]
what version of ceres are you looking at? since we moved to c++11, there is no scoped_ptr anymore. Its just unique_ptr. 

https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/problem.h#L524

**Comment by jbriales** [comment]
Oops sorry, my fault. Sure, I should look into this on the master version. The version I was looking at is probably much older.
