### ISSUE TITLE
Choosing SPARSE_NORMAL_CHOLESKY, crash occurs when using suitesparse (5.6.0), but is ok when using cxsparse or eigen.

### ISSUE THREAD

**Issue by luoyin500** [ceres-solver/ceres-solver#529]
linear_solver_type = SPARSE_NORMAL_CHOLESKY;

It works regularly when using cxsparse or eigen:
options.sparse_linear_algebra_library_type = ceres::SparseLinearAlgebraLibraryType::EIGEN_SPARSE;
or
options.sparse_linear_algebra_library_type = ceres::SparseLinearAlgebraLibraryType::CX_SPARSE;
(And CX_SPARSE is a little faster than EIGEN_SPARSE)

However, it crashes when using suitesparse:
options.sparse_linear_algebra_library_type = ceres::SparseLinearAlgebraLibraryType::SUITE_SPARSE;

The version of suitesparse is 5.6.0.

I checked the calling process:
(In ceres)
SparseNormalCholeskySolver::SolveImpl ->
SparseCholesky::FactorAndSolve ->
SuiteSparseCholesky::Factorize ->
SuiteSparse::Cholesky ->
(In suitesparse)
cholmod_factorize ->
cholmod_factorize_p ->
cholmod_super_numeric ->
t_cholmod_super_numeric ->
(In CLAPACK)
LAPACK_dpotrf

I found the problem is in t_cholmod_super_numeric 's calling of LAPACK_dpotrf. In 864 lines of SuiteSparse/CHOLMOD/Supernodal/t_cholmod_super_numeric .c. The key is the cross-border access of "Lx + L_ENTRY*psx".

More information:
1. I have test more versions of suitesparse: 5.5.0, 4.5.0. It crashed agian.
2. My platform is Android.

I am thinking of these questions:
1. Is there some options to be changed when using suitesparse, compared to those when using eigen or cxparse ? 
2. My suitesparse's version is 5.6.0, the version of current ceres's matched suitesparse is? Does the version of suitesparse influence the work ?

**Comment by sandwichmaker** [comment]
@luoyin500 this looks like a bug in suitesparse, it has nothing to do with ceres IMO. It would be good to reach out to Prof. Tim Davis with a reproduction if possible.

**Comment by luoyin500** [comment]
@sandwichmaker, thank you. what's the version of suitesparse which is recommended by the current ceres ? Is there any example calling suitesparse's CHOLMOD to prove the calling process in ceres is regular? Currently, I am doubt whether ceres' interface to suitesparse is right.

**Comment by sandwichmaker** [comment]
@luoyin500 we have been using suitesparse using roughly the same code for almost a decade. so I doubt that the calling code has bugs.

**Comment by luoyin500** [comment]
@sandwichmaker , thank you. You mean the bug is in the cere's calling code ?

**Comment by sandwichmaker** [comment]
No I am saying the opposite, I do not think there is a bug in how ceres is calling the code. I think there is a bug in suitesparse/cholmod.

**Comment by luoyin500** [comment]
@sandwichmaker , thank you. I am basically confirm the problem lies in the suitesparse. Because running its demo also crashes.
