### ISSUE TITLE
ceres.lib(ceres.dll) Error LNK2005

### ISSUE THREAD

**Issue by sealiutree7** [ceres-solver/ceres-solver#531]
Sorry for my stupid question. When I was trying to compile COLMAP with myself, here comes errors with ceres somthing like this:

ceres.lib(ceres.dll) : error LNK2005: "public: __cdecl ceres::Problem::~Problem(void)" (??1Problem@ceres@@QEAA@XZ) 已在 c
eres.lib(problem.obj) 中定義過了 [D:\COLMAP\colmap_36_rev\colmap_36_dev2\build\colmap\__build__\src\optim\bundle_adjustment_
test.vcxproj]
ceres.lib(ceres.dll) : error LNK2005: "public: __cdecl ceres::Solver::Options::Options(void)" (??0Options@Solver@ceres@
@QEAA@XZ) 已在 colmap.lib(pose.cc.obj) 中定義過了 [D:\COLMAP\colmap_36_rev\colmap_36_dev2\build\colmap\__build__\src\optim\bun
dle_adjustment_test.vcxproj]
ceres.lib(ceres.dll) : error LNK2005: "public: __cdecl ceres::Solver::Options::~Options(void)" (??1Options@Solver@ceres
@@QEAA@XZ) 已在 colmap.lib(bundle_adjustment.cc.obj) 中定義過了 [D:\COLMAP\colmap_36_rev\colmap_36_dev2\build\colmap\__build__
\src\optim\bundle_adjustment_test.vcxproj]
ceres.lib(ceres.dll) : error LNK2005: "public: __cdecl ceres::Solver::Summary::~Summary(void)" (??1Summary@Solver@ceres
@@QEAA@XZ) 已在 colmap.lib(bundle_adjustment.cc.obj) 中定義過了 [D:\COLMAP\colmap_36_rev\colmap_36_dev2\build\colmap\__build__
\src\optim\bundle_adjustment_test.vcxproj]

And I tried to find some solutions but still can't know what was going on. If you have any idea or suggestion please let me know and thank you so much.
The platform I use now is Visual Studio 2017, thank you so much again.

**Comment by alexsmac** [comment]
[LNK2005](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk2005?view=vs-2019) is when you have violated the ODR, but the methods that it references - e.g. ~Problem() are not defined in the header, only in problem.cc.  I'm not sure how you got into this, it could be that you are trying to link two different versions of Ceres, one static and one dynamic - it could be that you are trying to link two different versions of Ceres, maybe one version via COLMAP and another version directly for example.  Either way, I think this is an issue specific to your build and not a Ceres issue so I'm going to close this ticket.

**Comment by sealiutree7** [comment]
Thank you so much. It's true and it was solved.
