### ISSUE TITLE
Remove FindGlog.cmake and use glogConfig.cmake instead

### ISSUE THREAD

**Issue by NeroBurner** [ceres-solver/ceres-solver#535]
It would be possible to remove `FindGlog.cmake` as glog provides a cmake config file since `v0.4.0`. Unfortunately Distributions don't use the cmake configuration, rather stick to the autoconfig toolchain.

Open Bugs I've found
- [ ] [Arch Linux Tasks](https://bugs.archlinux.org/task/55185)
- [ ] [Ubuntu Launchpad Bug](https://bugs.launchpad.net/ubuntu/+source/google-glog/+bug/1815110)

**Comment by sandwichmaker** [comment]
https://ceres-solver-review.googlesource.com/c/ceres-solver/+/17381 should address this to the extend it can be done right now.
