### ISSUE TITLE
Generating Backward Automatic Derivatives

### ISSUE THREAD

**Issue by darglein** [ceres-solver/ceres-solver#536]
Using the new expression system it would be possible to generate backward autodiff code (=back propagation). I'm currently wondering, if it is worth implementing that, because intuitively it should increase performance if  `num_parameters >> num_residuals`.

What is your opinion on generating backward autodiff code? Should we implement it after the codegen stuff is working?

**Comment by sandwichmaker** [comment]
Isn't the total amount of arithmetic the same?

**Comment by darglein** [comment]
I thought forwards requires more multiplications, because there is a scalar-vector multiplication of size #numParameters in each operation. In backward mode there are #numResiduals multiplications for each operations.

**Comment by sandwichmaker** [comment]
To be honest, I am not sure. 

https://www.amazon.com/Evaluating-Derivatives-Principles-Algorithmic-Differentiation/dp/0898716594

I believe is the seminal reference on this.

**Comment by darglein** [comment]
I also not an expert, but I think the difference is easy to spot in various forwards-backwards implementations. 
Forward:
```
inline Jet<T, N> sin(const Jet<T, N>& f) {
  return Jet<T, N>(sin(f.a), cos(f.a) * f.v);
}
```
The arithmetic operations are `sin + cos + N mults`.

Backward (from https://github.com/autodiff/autodiff/blob/master/autodiff/reverse/reverse.hpp):
```
    virtual void propagate(DerivativesMap& derivatives, double wprime) const
    {
        x->propagate(derivatives, wprime * std::cos(x->val));
    }
```
Here `sin(x)` was computed in the forward path so the arithmetic operations are only `sin + cos + 1 mult`. Of course, this has to be evaluated for every residual (k) so we get `sin + cos + k mults)` (assuming that we also store cos(x->val) somewhere). 

If you expand everything you get something like this:

Forward:
dx_0 = ((((x_0 * c1) * c2) * c3) * c4)
dx_1 = ((((x_1 * c1) * c2) * c3) * c4)
Backward
tmp = c3 * c4
tmp = c2 * tmp
tmp = c1 * tmp
dx_0 = x_0 * tmp
dx_1 = x_1 * tmp

**Comment by sandwichmaker** [comment]
What I meant was, that these are two different algorithms for computing the same quantity given the same inputs. so the "optimal" amount of arithmetic operations to compute said quantity is constant. My understanding is that depending on the specifics of the function being differentiated, forward/backward/or mixed mode may get close to the minimum amount of arithmetic operations needed.

**Comment by darglein** [comment]
This also matches my understanding. It would still be interesting to see which algorithm (forward/backward/mixed) gets closer to the minimum for a few common problems. We most likely need the code optimizer and benchmarks for a meaningful comparison.

**Comment by sandwichmaker** [comment]
That sounds about right.

**Comment by sandwichmaker** [comment]
Closing as this is likely not something we are going to do in ceres.
