### ISSUE TITLE
can't convert T to basic data type of c++

### ISSUE THREAD

**Issue by chennuo0125** [ceres-solver/ceres-solver#537]
code as follows:
```
operator()(const T* const a, T* residual) const
{
     double k = static_cast<double>(a[0]);
     return true;
}
```
but during compilation, static_cast error !!!!! how to implement the cast ???

**Comment by alexsmac** [comment]
Assuming that this is part of a functor that you are using with auto-diff, then T will be a templated Jet type when the jacobian is evaluated.  Jets cannot be sensibly cast to doubles as you are trying to do here, although you can cast a double to a Jet.

You should use `T`, not double, as the type for all local variables used in operator().  See the [tutorials and examples](http://ceres-solver.org/nnls_tutorial.html#powell-s-function) for some sample code.

**Comment by ZhengPan2014** [comment]
> Assuming that this is part of a functor that you are using with auto-diff, then T will be a templated Jet type when the jacobian is evaluated. Jets cannot be sensibly cast to doubles as you are trying to do here, although you can cast a double to a Jet.
> 
> You should use `T`, not double, as the type for all local variables used in operator(). See the [tutorials and examples](http://ceres-solver.org/nnls_tutorial.html#powell-s-function) for some sample code.

I got the problem you mention above, But it seems I must convert T to double or some other type, 
and I find the same situation in [cartographer](https://github.com/cartographer-project/cartographer/blob/2f60378140a1b8229a68311f1c5383f30a379ecc/cartographer/mapping/internal/2d/scan_matching/occupied_space_cost_function_2d.cc#L57l)
Is world[0] to be converted to double here?
