### ISSUE TITLE
Autodiff Codegen Documentation

### ISSUE THREAD

**Issue by darglein** [ceres-solver/ceres-solver#538]
How would you structure the rst documentation of the autodiff codegen system?

We can integrate it into the current structure
- On Derivatives > Generated Automatic Derivatives
- Modeling Non-linear Least Squares > CodegenCostFunction
- Tutorial > Non-linear Least Squares > Code generation example

or create a new parent node
- Code Generation > Overview
- Code Generation > User Interface
- Code Generation > Technical Description
- Code Generation > Example

I probably prefer the second version, similar to how we have separated the codegen code into a new sub directory.

**Comment by sandwichmaker** [comment]
I do not think we should split further. I think it should just be a section in modeling nonlinear least squares.

on derivatives is meant to be a stand alone article that explains how various derivative computation methods work, it should also be expanded to include codegen, but it is not a guide to using codegen.

**Comment by darglein** [comment]
We can start with a section in modeling nonlinear least squares after the cmake integration is done. This is mostly a user guide isn't it? So not that much technical description how the system works.

**Comment by sandwichmaker** [comment]
yes.

**Comment by sandwichmaker** [comment]
CodeGen is being deleted.
