### ISSUE TITLE
How to build ceres master with user's eigen?

### ISSUE THREAD

**Issue by narutojxl** [ceres-solver/ceres-solver#539]
Hi, My OS is ubuntu16.04,  with `sudo apt install libeigen3-dev﻿` installed is 3.2.92, which can be see by ` pkg-config --modversion eigen3`, but the ceres master need eigen >=3.3.  I download eigen 3.3.7 into`/home/jxl/third_softwares/eigen_3_3_7`. With cmake gui, set  `Eigen3_DIR = /home/jxl/third_softwares/eigen_3_3_7/`,  configure failed.  Set by command line also failed!
>  
      jxl@dell:~/third_softwares/ceres-solver/build_dir$ cmake .. -DLAPACK=ON -DSUITESPARSE=ON -DCXSPARSE=ON -DEIGENSPARSE=ON -DGFLAGS=ON -DMINIGLOG=OFF -DSCHUR_SPECIALIZATIONS=ON  -DCERES_THREADING_MODEL=CXX11_THREADS  -DCXX11=ON -DBUILD_SHARED_LIBS=OFF -DEXPORT_BUILD_DIR=OFF -DBUILD_DOCUMENTATION=OFF -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF﻿​ -DEigen3_DIR=/home/jxl/third_softwares/eigen_3_3_7/

The output is:
>
  -- Detected Ceres version: 2.0.0 from /home/jxl/third_softwares/ceres-solver/include/ceres/version.h
	-- Detected available Ceres threading models: [CXX11_THREADS, OPENMP, NO_THREADS]
	-- Building with C++11
	CMake Error at CMakeLists.txt:243 (find_package):
	  Could not find a configuration file for package "Eigen3" that is compatible
	  with requested version "3.3".

	  The following configuration files were considered but not accepted:

	    /usr/lib/cmake/eigen3/Eigen3Config.cmake, version: unknown

	-- Configuring incomplete, errors occurred!
	See also "/home/jxl/third_softwares/ceres-solver/build_dir/CMakeFiles/CMakeOutput.log".

So how to build ceres master with user's eigen?  or how to upgrade `/usr/include/eigen3` into 3.3?
Thanks very much, appreciate for your help a lot !

**Comment by narutojxl** [comment]
Thanks @sandwichmaker  and @alexsmac!  BTW,  set eigen in ceres CMakeLists.txt like this `set(EIGEN3_ROOT "/home/jxl/third_softwares/eigen_3_3_7/")` or `set(EIGEN3_ROOT_DIR "/home/jxl/third_softwares/eigen_3_3_7/")` before use find_package() to find eigen3, it also failed to find the eigen_3_3_7.  In eigen_3_3_7/cmake/, there is only a `Eigen3Config.cmake.in` file,  not have a `Eigen3Config.cmake` file. Thanks very much!

**Comment by alexsmac** [comment]
@narutojxl [this listing](https://packages.ubuntu.com/xenial/all/libeigen3-dev/filelist) shows that the libeigen3-dev package in Xenial should include:

`/usr/lib/cmake/eigen3/Eigen3Config.cmake`

are you sure that file does not exist?  If not, where are you pulling the package from instead of mainline?  If it exists, it should be being automatically detected by CMake.

If you want to use a local install of Eigen, that is fine and will work, but you will have to actually 'build' and install Eigen in order to do so as Eigen does not generate an Eigen3Config.cmake suitable for exporting its build directory, so it cannot be used directly from there.  Eigen3Config.cmake.in is the template from which a valid Eigen3Config.cmake is generated and is not itself a valid config file.

You can install this version of Eigen wherever you choose, but the default /usr/local is generally sensible.  If you install it there it should be automatically detected by CMake, if you want to install it somewhere else then you will need to pass `-DEigen3_DIR=<PATH_TO_ROOT_INSTALL_DIR>/lib/cmake/eigen3`.

**Comment by narutojxl** [comment]
Hi @alexsmac, thanks for your reply :) . Yes, with  `sudo apt install libeigen3-dev`, eigen 3.2.92 installed in /usr/ path, and /usr/lib/cmake/eigen3/Eigen3Config.cmake exist.  After build and install eigen_3_3_7 locally, set  `-DEigen3_DIR=<PATH_TO_ROOT_INSTALL_DIR>/share/eigen3/cmake`, ceres can find it correctlly, thanks for your help!  
BTW, how do you know the variable name to be set is  "Eigen3_DIR" :) ?

**Comment by ihamieh** [comment]
@alexsmac you seem to know what's going on with this package! To be honest, i'm not sure how to properly install eigen! I checked my system ($ pkg-config --modversion eigen3) and I have 3.2.92 version. For my project, I need to install eigen3 from the following link: http://eigen.tuxfamily.org/index.php?title=Main_Page but I don't know what to do after I git clone https://gitlab.com/libeigen/eigen.git ? The instruction seems to be confusing and I'm not sure what are the proper steps to install after I git clone! Regardless, I tried couple things and I got the following error messages: 

-- Configuring incomplete, errors occurred!
See also "/home/yz2qmq/ORB_SLAM3/Thirdparty/g2o/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
Uncompress vocabulary ...
Configuring and building ORB_SLAM3 ...
mkdir: cannot create directory ‘build’: File exists
Build type: Release
-- Using flag -std=c++11.
OPENCV VERSION:
3.3.1
CMake Error at CMakeLists.txt:47 (find_package):
  Could not find a configuration file for package "Eigen3" that is compatible
  with requested version "3.1.0".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/eigen3/Eigen3Config.cmake, version: unknown

-- Configuring incomplete, errors occurred!
See also "/home/yz2qmq/ORB_SLAM3/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.

Please let me know if you know what do you think?

**Comment by narutojxl** [comment]
Hi @ihamieh, the INSTALL file in the source of eigen:
>
	Method 2. Installing using CMake
	********************************
	Let's call this directory 'source_dir' (where this INSTALL file is).
	Before starting, create another directory which we will call 'build_dir'.

	Do:

	  cd build_dir
	  cmake source_dir
	  make install

	The "make install" step may require administrator privileges.

	You can adjust the installation destination (the "prefix")
	by passing the -DCMAKE_INSTALL_PREFIX=myprefix option to cmake, as is
	explained in the message that cmake prints at the end.

when after installed locally, set `-DEigen3_DIR=<PATH_TO_ROOT_INSTALL_DIR>/share/eigen3/cmake` to let your CMakeLists.txt to found yourself's eigen not the system's eigen 3.2.92.

**Comment by ihamieh** [comment]
I got this one resolved yesterday! The fix is to build --> cmake --> sudo install and it worked!

**Comment by ghanta1996** [comment]
Hi, I'm trying to `catkin build` the `ceres-solver` from my ros workspace. I'm getting this message.

```
  Could not find a configuration file for package "Eigen3" that is compatible
  with requested version "3.3".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/eigen3/Eigen3Config.cmake, version: unknown

```
I'm using ubuntu16.04. Any help would be appreciated. Thanks
