### ISSUE TITLE
ceres -1.14.0 enable openmp build OK, but link against ceres, not  have components [OpenMP]

### ISSUE THREAD

**Issue by narutojxl** [ceres-solver/ceres-solver#540]
Hi, my system is ubuntu16.04,  build ceres -1.14.0 enable openmp  OK, like this.
>
	jxl@dell:~/third_softwares/ceres-solver-1.14.0/build_dir$ cmake .. -DLAPACK=ON -DSUITESPARSE=ON -DCXSPARSE=ON -DEIGENSPARSE=ON -DGFLAGS=ON -DMINIGLOG=OFF -DSCHUR_SPECIALIZATIONS=ON -DOPENMP=ON -DCXX11_THREADS=OFF -DCXX11=ON -DBUILD_SHARED_LIBS=OFF -DEXPORT_BUILD_DIR=OFF -DBUILD_DOCUMENTATION=OFF -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF
	-- The C compiler identification is GNU 5.4.0
	-- The CXX compiler identification is GNU 5.4.0
	-- Check for working C compiler: /usr/bin/cc
	-- Check for working C compiler: /usr/bin/cc -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Detecting C compile features
	-- Detecting C compile features - done
	-- Check for working CXX compiler: /usr/bin/c++
	-- Check for working CXX compiler: /usr/bin/c++ -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Detecting CXX compile features
	-- Detecting CXX compile features - done
	-- Detected Ceres version: 1.14.0 from /home/jxl/third_softwares/ceres-solver-1.14.0/include/ceres/version.h
	-- No preference for use of exported Eigen CMake configuration set, and no hints for include directory provided. Defaulting to preferring an installed/exported Eigen CMake configuration if available.
	-- Found installed version of Eigen: /usr/lib/cmake/eigen3
	-- Found Eigen: /usr/include/eigen3 (found version "3.2.92") 
	-- Found Eigen version 3.2.92: /usr/include/eigen3
	-- Enabling use of Eigen as a sparse linear algebra library.
	-- Looking for sgemm_
	-- Looking for sgemm_ - not found
	-- Looking for pthread.h
	-- Looking for pthread.h - found
	-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
	-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
	-- Looking for pthread_create in pthreads
	-- Looking for pthread_create in pthreads - not found
	-- Looking for pthread_create in pthread
	-- Looking for pthread_create in pthread - found
	-- Found Threads: TRUE  
	-- Looking for dgemm_
	-- Looking for dgemm_ - found
	-- Found BLAS: /usr/lib/libf77blas.so;/usr/lib/libatlas.so  
	-- Found LAPACK library: /usr/lib/liblapack.so;/usr/lib/libf77blas.so;/usr/lib/libatlas.so
	-- Found AMD headers in: /usr/include/suitesparse
	-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
	-- Found CAMD headers in: /usr/include/suitesparse
	-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
	-- Found COLAMD headers in: /usr/include/suitesparse
	-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
	-- Found CCOLAMD headers in: /usr/include/suitesparse
	-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
	-- Found CHOLMOD headers in: /usr/include/suitesparse
	-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
	-- Found SUITESPARSEQR headers in: /usr/include/suitesparse
	-- Found SUITESPARSEQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
	-- Found Intel Thread Building Blocks (TBB) library (4.4) assuming SuiteSparseQR was compiled with TBB.
	-- Found SUITESPARSE_CONFIG headers in: /usr/include/suitesparse
	-- Found SUITESPARSE_CONFIG library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
	-- Found LIBRT library: /usr/lib/x86_64-linux-gnu/librt.so
	-- Adding librt: /usr/lib/x86_64-linux-gnu/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
	-- Found METIS library: /usr/local/lib/libmetis.so
	-- Found SuiteSparse: TRUE (found version "4.4.6") 
	-- Found SuiteSparse 4.4.6, building with SuiteSparse.
	-- Found CXSparse: /usr/include/suitesparse (found version "3.1.4") 
	-- Found CXSparse version: 3.1.4, building with CXSparse.
	-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
	-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
	-- Found exported gflags build directory: /home/jxl/segmap_ws/build/gflags_catkin/gflags_src-prefix/src/gflags_src
	-- Detected broken gflags install in: /home/jxl/segmap_ws/build/gflags_catkin/gflags_src-prefix/src/gflags_src, version: 2.1.2 <= 2.1.2 which defines gflags_LIBRARIES = gflags which is not an imported CMake target, see: https://github.com/gflags/gflags/issues/110.  Attempting to fix by detecting correct gflags target.
	-- Found valid gflags target: gflags-shared, updating gflags_LIBRARIES.
	-- Detected gflags version: 2.1.2
	-- Found Gflags: /home/jxl/segmap_ws/build/gflags_catkin/gflags_src-prefix/src/gflags_src/include  
	-- Found Google Flags header in: /home/jxl/segmap_ws/build/gflags_catkin/gflags_src-prefix/src/gflags_src/include, in namespace: google
	-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
	-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
	-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
	-- Found Glog: /usr/include  
	-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
	-- Building with OpenMP.
	-- Performing Test COMPILER_HAS_CXX11_FLAG
	-- Performing Test COMPILER_HAS_CXX11_FLAG - Success
	-- Looking for C++ include unordered_map
	-- Looking for C++ include unordered_map - found
	-- Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE
	-- Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE - Success
	-- Found unordered_map/set in std namespace.
	-- Looking for C++ include memory
	-- Looking for C++ include memory - found
	-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
	-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
	-- Found shared_ptr in std namespace using <memory> header.
	-- Performing Test CXX11_MATH_FUNCTIONS_FOUND
	-- Performing Test CXX11_MATH_FUNCTIONS_FOUND - Success
	   ==============================================================
	   Compiling Ceres using C++11.  This will result in a version 
	   of Ceres that will require the use of C++11 in client code.
	   ==============================================================
	-- Failed to find Google benchmark library, disabling build of benchmarks.
	-- Building Ceres as a static library.
	-- Creating configured Ceres config.h output directory: /home/jxl/third_softwares/ceres-solver-1.14.0/build_dir/config/ceres/internal
	-- Enabling CERES_USE_EIGEN_SPARSE in Ceres config.h
	-- Enabling CERES_USE_CXX11 in Ceres config.h
	-- Enabling CERES_USE_OPENMP in Ceres config.h
	-- Enabling CERES_HAVE_PTHREAD in Ceres config.h
	-- Enabling CERES_HAVE_RWLOCK in Ceres config.h
	-- Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
	-- Do not build any example.
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/jxl/third_softwares/ceres-solver-1.14.0/build_dir
	jxl@dell:~/third_softwares/ceres-solver-1.14.0/build_dir$ 

Its output 
> -- Building with OpenMP.

but when link against ceres `find_package(Ceres REQUIRED COMPONENTS OpenMP)`,  not  have components [OpenMP]. 
> CMake Error at /usr/local/lib/cmake/Ceres/CeresConfig.cmake:88 (message):
  Failed to find Ceres - Missing requested Ceres components: [OpenMP]
  (components requested: [OpenMP]).  Detected Ceres version: 1.14.0 installed
  in: /usr/local with components: [LAPACK, SuiteSparse,
  SparseLinearAlgebraLibrary, CXSparse, SchurSpecializations].
Call Stack (most recent call first):
  /usr/local/lib/cmake/Ceres/CeresConfig.cmake:390 (ceres_report_not_found)

What do you think of this? I will next to  try to enable TBB or  CXX11_THREADS  to  see,  whether they can find or not?

**Comment by narutojxl** [comment]
**Config 1**
openmp=OFF,  CXX11_THREADS= ON,  CXX11 =ON, it says  `-- Found Threads: TRUE` and `-- Building with C++11 threads.`, built Ok. But `find_package(Ceres REQUIRED COMPONENTS Multithreading)` also failed! 
>
	jxl@dell:~/third_softwares/ceres-solver-1.14.0/build_dir$  cmake .. -DLAPACK=ON -DSUITESPARSE=ON -DCXSPARSE=ON -DEIGENSPARSE=ON -DGFLAGS=ON -DMINIGLOG=OFF -DSCHUR_SPECIALIZATIONS=ON -DOPENMP=OFF -DTBB=OFF  -DCXX11_THREADS=ON -DCXX11=ON -DBUILD_SHARED_LIBS=OFF -DEXPORT_BUILD_DIR=OFF -DBUILD_DOCUMENTATION=OFF -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF
	-- The C compiler identification is GNU 5.4.0
	-- The CXX compiler identification is GNU 5.4.0
	-- Check for working C compiler: /usr/bin/cc
	-- Check for working C compiler: /usr/bin/cc -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Detecting C compile features
	-- Detecting C compile features - done
	-- Check for working CXX compiler: /usr/bin/c++
	-- Check for working CXX compiler: /usr/bin/c++ -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Detecting CXX compile features
	-- Detecting CXX compile features - done
	-- Detected Ceres version: 1.14.0 from /home/jxl/third_softwares/ceres-solver-1.14.0/include/ceres/version.h
	-- No preference for use of exported Eigen CMake configuration set, and no hints for include directory provided. Defaulting to preferring an installed/exported Eigen CMake configuration if available.
	-- Found installed version of Eigen: /usr/lib/cmake/eigen3
	-- Found Eigen: /usr/include/eigen3 (found version "3.2.92") 
	-- Found Eigen version 3.2.92: /usr/include/eigen3
	-- Enabling use of Eigen as a sparse linear algebra library.
	-- Looking for sgemm_
	-- Looking for sgemm_ - not found
	-- Looking for pthread.h
	-- Looking for pthread.h - found
	-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
	-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
	-- Looking for pthread_create in pthreads
	-- Looking for pthread_create in pthreads - not found
	-- Looking for pthread_create in pthread
	-- Looking for pthread_create in pthread - found
	-- Found Threads: TRUE  
	-- Looking for dgemm_
	-- Looking for dgemm_ - found
	-- Found BLAS: /usr/lib/libf77blas.so;/usr/lib/libatlas.so  
	-- Found LAPACK library: /usr/lib/liblapack.so;/usr/lib/libf77blas.so;/usr/lib/libatlas.so
	-- Found AMD headers in: /usr/include/suitesparse
	-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
	-- Found CAMD headers in: /usr/include/suitesparse
	-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
	-- Found COLAMD headers in: /usr/include/suitesparse
	-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
	-- Found CCOLAMD headers in: /usr/include/suitesparse
	-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
	-- Found CHOLMOD headers in: /usr/include/suitesparse
	-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
	-- Found SUITESPARSEQR headers in: /usr/include/suitesparse
	-- Found SUITESPARSEQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
	-- Found Intel Thread Building Blocks (TBB) library (4.4) assuming SuiteSparseQR was compiled with TBB.
	-- Found SUITESPARSE_CONFIG headers in: /usr/include/suitesparse
	-- Found SUITESPARSE_CONFIG library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
	-- Found LIBRT library: /usr/lib/x86_64-linux-gnu/librt.so
	-- Adding librt: /usr/lib/x86_64-linux-gnu/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
	-- Found METIS library: /usr/local/lib/libmetis.so
	-- Found SuiteSparse: TRUE (found version "4.4.6") 
	-- Found SuiteSparse 4.4.6, building with SuiteSparse.
	-- Found CXSparse: /usr/include/suitesparse (found version "3.1.4") 
	-- Found CXSparse version: 3.1.4, building with CXSparse.
	-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
	-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
	-- Found exported gflags build directory: /home/jxl/segmap_ws/build/gflags_catkin/gflags_src-prefix/src/gflags_src
	-- Detected broken gflags install in: /home/jxl/segmap_ws/build/gflags_catkin/gflags_src-prefix/src/gflags_src, version: 2.1.2 <= 2.1.2 which defines gflags_LIBRARIES = gflags which is not an imported CMake target, see: https://github.com/gflags/gflags/issues/110.  Attempting to fix by detecting correct gflags target.
	-- Found valid gflags target: gflags-shared, updating gflags_LIBRARIES.
	-- Detected gflags version: 2.1.2
	-- Found Gflags: /home/jxl/segmap_ws/build/gflags_catkin/gflags_src-prefix/src/gflags_src/include  
	-- Found Google Flags header in: /home/jxl/segmap_ws/build/gflags_catkin/gflags_src-prefix/src/gflags_src/include, in namespace: google
	-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
	-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
	-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
	-- Found Glog: /usr/include  
	-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
	-- Building without OpenMP, disabling.
	-- Performing Test COMPILER_HAS_CXX11_FLAG
	-- Performing Test COMPILER_HAS_CXX11_FLAG - Success
	-- Looking for C++ include unordered_map
	-- Looking for C++ include unordered_map - found
	-- Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE
	-- Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE - Success
	-- Found unordered_map/set in std namespace.
	-- Looking for C++ include memory
	-- Looking for C++ include memory - found
	-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
	-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
	-- Found shared_ptr in std namespace using <memory> header.
	-- Performing Test CXX11_MATH_FUNCTIONS_FOUND
	-- Performing Test CXX11_MATH_FUNCTIONS_FOUND - Success
	   ==============================================================
	   Compiling Ceres using C++11.  This will result in a version 
	   of Ceres that will require the use of C++11 in client code.
	   ==============================================================
	-- Looking for C++ include atomic
	-- Looking for C++ include atomic - found
	-- Building with C++11 threads.
	-- Failed to find Google benchmark library, disabling build of benchmarks.
	-- Building Ceres as a static library.
	-- Creating configured Ceres config.h output directory: /home/jxl/third_softwares/ceres-solver-1.14.0/build_dir/config/ceres/internal
	-- Enabling CERES_USE_EIGEN_SPARSE in Ceres config.h
	-- Enabling CERES_USE_CXX11 in Ceres config.h
	-- Enabling CERES_USE_CXX11_THREADS in Ceres config.h
	-- Enabling CERES_HAVE_PTHREAD in Ceres config.h
	-- Enabling CERES_HAVE_RWLOCK in Ceres config.h
	-- Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
	-- Do not build any example.
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/jxl/third_softwares/ceres-solver-1.14.0/build_dir
	jxl@dell:~/third_softwares/ceres-solver-1.14.0/build_dir$ 


**Config 2**
 openmp=OFF,  CXX11_THREADS= OFF,  CXX11 =ON,  TBB=ON, it says  `-- Found Threads: TRUE` and `-- Building with TBB (version: 4.4).`, built Ok. But `find_package(Ceres  REQUIRED COMPONENTS TBB) ` also failed!
>
	jxl@dell:~/third_softwares/ceres-solver-1.14.0/build_dir$ cmake .. -DLAPACK=ON -DSUITESPARSE=ON -DCXSPARSE=ON -DEIGENSPARSE=ON -DGFLAGS=ON -DMINIGLOG=OFF -DSCHUR_SPECIALIZATIONS=ON  -DTBB=ON -DOPENMP=OFF  -DCXX11_THREADS=OFF -DCXX11=ON -DBUILD_SHARED_LIBS=OFF -DEXPORT_BUILD_DIR=OFF -DBUILD_DOCUMENTATION=OFF -DLIB_SUFFIX=64 -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF
	-- The C compiler identification is GNU 5.4.0
	-- The CXX compiler identification is GNU 5.4.0
	-- Check for working C compiler: /usr/bin/cc
	-- Check for working C compiler: /usr/bin/cc -- works
	-- Detecting C compiler ABI info
	-- Detecting C compiler ABI info - done
	-- Detecting C compile features
	-- Detecting C compile features - done
	-- Check for working CXX compiler: /usr/bin/c++
	-- Check for working CXX compiler: /usr/bin/c++ -- works
	-- Detecting CXX compiler ABI info
	-- Detecting CXX compiler ABI info - done
	-- Detecting CXX compile features
	-- Detecting CXX compile features - done
	-- Detected Ceres version: 1.14.0 from /home/jxl/third_softwares/ceres-solver-1.14.0/include/ceres/version.h
	-- No preference for use of exported Eigen CMake configuration set, and no hints for include directory provided. Defaulting to preferring an installed/exported Eigen CMake configuration if available.
	-- Found installed version of Eigen: /usr/lib/cmake/eigen3
	-- Found Eigen: /usr/include/eigen3 (found version "3.2.92") 
	-- Found Eigen version 3.2.92: /usr/include/eigen3
	-- Enabling use of Eigen as a sparse linear algebra library.
	-- Looking for sgemm_
	-- Looking for sgemm_ - not found
	-- Looking for pthread.h
	-- Looking for pthread.h - found
	-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
	-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
	-- Looking for pthread_create in pthreads
	-- Looking for pthread_create in pthreads - not found
	-- Looking for pthread_create in pthread
	-- Looking for pthread_create in pthread - found
	-- Found Threads: TRUE  
	-- Looking for dgemm_
	-- Looking for dgemm_ - found
	-- Found BLAS: /usr/lib/libf77blas.so;/usr/lib/libatlas.so  
	-- Found LAPACK library: /usr/lib/liblapack.so;/usr/lib/libf77blas.so;/usr/lib/libatlas.so
	-- Found AMD headers in: /usr/include/suitesparse
	-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
	-- Found CAMD headers in: /usr/include/suitesparse
	-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
	-- Found COLAMD headers in: /usr/include/suitesparse
	-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
	-- Found CCOLAMD headers in: /usr/include/suitesparse
	-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
	-- Found CHOLMOD headers in: /usr/include/suitesparse
	-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
	-- Found SUITESPARSEQR headers in: /usr/include/suitesparse
	-- Found SUITESPARSEQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
	-- Found Intel Thread Building Blocks (TBB) library (4.4) assuming SuiteSparseQR was compiled with TBB.
	-- Found SUITESPARSE_CONFIG headers in: /usr/include/suitesparse
	-- Found SUITESPARSE_CONFIG library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
	-- Found LIBRT library: /usr/lib/x86_64-linux-gnu/librt.so
	-- Adding librt: /usr/lib/x86_64-linux-gnu/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
	-- Found METIS library: /usr/local/lib/libmetis.so
	-- Found SuiteSparse: TRUE (found version "4.4.6") 
	-- Found SuiteSparse 4.4.6, building with SuiteSparse.
	-- Found CXSparse: /usr/include/suitesparse (found version "3.1.4") 
	-- Found CXSparse version: 3.1.4, building with CXSparse.
	-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
	-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
	-- Found exported gflags build directory: /home/jxl/segmap_ws/build/gflags_catkin/gflags_src-prefix/src/gflags_src
	-- Detected broken gflags install in: /home/jxl/segmap_ws/build/gflags_catkin/gflags_src-prefix/src/gflags_src, version: 2.1.2 <= 2.1.2 which defines gflags_LIBRARIES = gflags which is not an imported CMake target, see: https://github.com/gflags/gflags/issues/110.  Attempting to fix by detecting correct gflags target.
	-- Found valid gflags target: gflags-shared, updating gflags_LIBRARIES.
	-- Detected gflags version: 2.1.2
	-- Found Gflags: /home/jxl/segmap_ws/build/gflags_catkin/gflags_src-prefix/src/gflags_src/include  
	-- Found Google Flags header in: /home/jxl/segmap_ws/build/gflags_catkin/gflags_src-prefix/src/gflags_src/include, in namespace: google
	-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
	-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
	-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
	-- Found Glog: /usr/include  
	-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
	-- Building without OpenMP, disabling.
	-- Performing Test COMPILER_HAS_CXX11_FLAG
	-- Performing Test COMPILER_HAS_CXX11_FLAG - Success
	-- Looking for C++ include unordered_map
	-- Looking for C++ include unordered_map - found
	-- Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE
	-- Performing Test HAVE_UNORDERED_MAP_IN_STD_NAMESPACE - Success
	-- Found unordered_map/set in std namespace.
	-- Looking for C++ include memory
	-- Looking for C++ include memory - found
	-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE
	-- Performing Test HAVE_SHARED_PTR_IN_STD_NAMESPACE - Success
	-- Found shared_ptr in std namespace using <memory> header.
	-- Performing Test CXX11_MATH_FUNCTIONS_FOUND
	-- Performing Test CXX11_MATH_FUNCTIONS_FOUND - Success
	   ==============================================================
	   Compiling Ceres using C++11.  This will result in a version 
	   of Ceres that will require the use of C++11 in client code.
	   ==============================================================
	-- Looking for C++ include atomic
	-- Looking for C++ include atomic - found
	-- Building with TBB (version: 4.4).
	-- Failed to find Google benchmark library, disabling build of benchmarks.
	-- Building Ceres as a static library.
	-- Creating configured Ceres config.h output directory: /home/jxl/third_softwares/ceres-solver-1.14.0/build_dir/config/ceres/internal
	-- Enabling CERES_USE_EIGEN_SPARSE in Ceres config.h
	-- Enabling CERES_USE_CXX11 in Ceres config.h
	-- Enabling CERES_USE_TBB in Ceres config.h
	-- Enabling CERES_HAVE_PTHREAD in Ceres config.h
	-- Enabling CERES_HAVE_RWLOCK in Ceres config.h
	-- Enabling CERES_STD_UNORDERED_MAP in Ceres config.h
	-- Do not build any example.
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/jxl/third_softwares/ceres-solver-1.14.0/build_dir
	jxl@dell:~/third_softwares/ceres-solver-1.14.0/build_dir$

**Comment by alexsmac** [comment]
I can't replicate this with the 1.14 release on an 18.04 machine.

I think your problem is that you had an original Ceres install in `/usr/local` which was not built with any multithreading and you are not re-installing, and thus replacing, that original version after you rebuild Ceres with a different configuration in `/home/jxl/third_softwares/ceres-solver-1.14.0/build_dir`.  You can verify this by checking the contents of `/home/jxl/third_softwares/ceres-solver-1.14.0/build_dir/CeresConfig-install.cmake` vs `/usr/local/lib/cmake/Ceres/CeresConfig.cmake` - they should be the same, and `CERES_COMPILED_COMPONENTS` will contain the components that Ceres was compiled with.  That list will include OpenMP (and Multithreading) if Ceres was compiled with it enabled.

**Comment by narutojxl** [comment]
Hi @alexsmac, i removed all ceres installed in system clearly by `sudo make uninstall`  in build directory. When only enable openmp, the two files  `CeresConfig-install.cmake`  and `/usr/local/lib/cmake/Ceres/CeresConfig.cmake` are the same, `CERES_COMPILED_COMPONENTS` is
> 
     #The list of (optional) components this version of Ceres was compiled with.
     set(CERES_COMPILED_COMPONENTS "EigenSparse;SparseLinearAlgebraLibrary;LAPACK;SuiteSparse;CXSparse;SchurSpecializations;C++11;OpenMP;Multithreading")
It's  indeed built by OpenMP,  thanks for your help a lot! 
When only enable `-DCXX11_THREADS=ON`, the `CERES_COMPILED_COMPONENTS` doesn't hava a commponent named  `Multithreading`.
