### ISSUE TITLE
dataset.g2o

### ISSUE THREAD

**Issue by Sun1307010608** [ceres-solver/ceres-solver#542]
hello, 
I am learning the ceres libraries, I want to test "/path/to/bin/pose_graph_2d /path/to/dataset/dataset.g2o", do you provide the test dataset yet? and when I compile the pose_graph_2d, after I add the cmake_minimum_version, eigen include dir, it finally has the following error occurs: 
CMakeFiles/read_test.dir/read_test.o: In function `bool ceres::examples::ReadG2oFile<ceres::examples::Pose2d, ceres::examples::Constraint2d, std::allocator<std::pair<int const, ceres::examples::Pose2d> >, std::allocator<ceres::examples::Constraint2d> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<int, ceres::examples::Pose2d, std::less<int>, std::allocator<std::pair<int const, ceres::examples::Pose2d> > >*, std::vector<ceres::examples::Constraint2d, std::allocator<ceres::examples::Constraint2d> >*)':
read_test.cpp:(.text._ZN5ceres8examples11ReadG2oFileINS0_6Pose2dENS0_12Constraint2dESaISt4pairIKiS2_EESaIS3_EEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt3mapIiT_St4lessIiET1_EPSt6vectorIT0_T2_E[_ZN5ceres8examples11ReadG2oFileINS0_6Pose2dENS0_12Constraint2dESaISt4pairIKiS2_EESaIS3_EEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt3mapIiT_St4lessIiET1_EPSt6vectorIT0_T2_E]+0x67): undefined reference to `google::LogMessageFatal::LogMessageFatal(char const*, int)'
read_test.cpp:(.text._ZN5ceres8examples11ReadG2oFileINS0_6Pose2dENS0_12Constraint2dESaISt4pairIKiS2_EESaIS3_EEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt3mapIiT_St4lessIiET1_EPSt6vectorIT0_T2_E[_ZN5ceres8examples11ReadG2oFileINS0_6Pose2dENS0_12Constraint2dESaISt4pairIKiS2_EESaIS3_EEEbRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt3mapIiT_St4lessIiET1_EPSt6vectorIT0_T2_E]+0x7b): undefined reference to `google::LogMessage::stream()'

do you know what happen, how to solve this problem. Thank you.

**Comment by sandwichmaker** [comment]
you need to link to glog.

**Comment by Sun1307010608** [comment]
@sandwichmaker thank you, I solved this problem by add glog, do you know what's the problem of this: 
/usr/bin/ld: CMakeFiles/pose_graph_2d.dir/pose_graph_2d.cc.o: undefined reference to symbol '_ZN6google21ParseCommandLineFlagsEPiPPPcb'
//usr/lib/x86_64-linux-gnu/libgflags.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/pose_graph_2d.dir/build.make:94: recipe for target 'pose_graph_2d' failed
make[2]: *** [pose_graph_2d] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pose_graph_2d.dir/all' failed
make[1]: *** [CMakeFiles/pose_graph_2d.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sandwichmaker** [comment]
you are missing gflags.

**Comment by Sun1307010608** [comment]
@sandwichmaker  thanks a lot.
