### ISSUE TITLE
how to set 3D rotation param bound?

### ISSUE THREAD

**Issue by narutojxl** [ceres-solver/ceres-solver#543]
Hi, how to set 3D rotation param LowerBound and UpperBound? For example, we can set params in vector space like the following. If we want to set the pitch angle in a lower and upper bound, how should we do this, thanks a lot your help!
>
	double constraint_raw[7] = {0, 0, 0, 1, 0, 0, 0}; 

	Eigen::Map<Eigen::Quaterniond> q = Eigen::Map<Eigen::Quaterniond>(constraint_raw);
	Eigen::Map<Eigen::Vector3d> t = Eigen::Map<Eigen::Vector3d>(constraint_raw + 4);

	ceres::LocalParameterization* q_parameterization = new ceres::EigenQuaternionParameterization();
	problem.AddParameterBlock(constraint_raw, 4, q_parameterization);
	problem.AddParameterBlock(constraint_raw + 4, 3);

	//set y bound
	problem.SetParameterLowerBound(constraint_raw + 4, 1, -t_bound);
	problem.SetParameterUpperBound(constraint_raw + 4, 1, +t_bound);

**Comment by sandwichmaker** [comment]
you cannot do this with a quaternion. use an euler angle parameterization of rotations.
