### ISSUE TITLE
replace bessel functions with C++17 equivalent

### ISSUE THREAD

**Issue by NeroBurner** [ceres-solver/ceres-solver#545]
If we push the minimum required version of C++ to C++17 we could replace the msvc underscored and not underscored `_j0` bessel function usages in `jet.h`

https://github.com/ceres-solver/ceres-solver/blob/edb8322bdabef336db290be1cc557145b6d4bf80/include/ceres/jet.h#L592-L618

C++ reference for the new mathematical special functions like `cyl_bessel_j`
https://en.cppreference.com/w/cpp/numeric/special_functions/cyl_bessel_j

```cpp
// Bessel functions of the first kind with integer order equal to 0, 1, n.
inline double BesselJ0(double x) {
  return cyl_bessel_j(0.0, x);
}
inline double BesselJ1(double x) {
  return cyl_bessel_j(1.0, x);
}
inline double BesselJn(int n, double x) {
  return cyl_bessel_j(static_cast<double>(n), x);
}
```

**Comment by sandwichmaker** [comment]
Sorry, c++11 is all we support for now.
