### ISSUE TITLE
Not using optimized inverse for dynamic-sized small matrix?

### ISSUE THREAD

**Issue by versatran01** [ceres-solver/ceres-solver#546]
https://github.com/ceres-solver/ceres-solver/blob/8def196166ddd56be2e8e547d9df1c73d0ad3391/internal/ceres/invert_psd_matrix.h#L63

Just looking at this code and it checks whether to use inverse based on the matrix size at compile time. 
Would this miss the case when the matrix is small but is of size Eigen::Dynamic (kSize=-1)?
If that's the case then this line should be
```c++
if (size > 0 && size < 5) return m.inverse()
```

**Comment by sandwichmaker** [comment]
in that case there is nothing to be gained by that code. The optimized code path AFAIK only works for the statically known dimensions.
