### ISSUE TITLE
Unresolved External ceres::ProductParameterization

### ISSUE THREAD

**Issue by oracle3001** [ceres-solver/ceres-solver#549]
I have just updated from ceres solver 1.14 to the latest code from Github (built using VS2019 on Windows 10). My code which previously compiled and ran without issue now has the following build error,
```
ceresDeltaModelFit.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) const ceres::ProductParameterization::`vftable' (__imp_??_7ProductParameterization@ceres@@6B@)
```
relating to the following line of code,
```
vector<int> id_constant_parameter = { 0 };
LocalParameterization* local_parameterization =
		new ceres::ProductParameterization(
			new ceres::SubsetParameterization(1, id_constant_parameter),
			new ceres::QuaternionParameterization());
```
I use other local paramaterizations elsewhere in the my code that work fine e.g.
```
LocalParameterization* other_local_parameterization =
		new ceres::SubsetParameterization(4, id_constant_parameter);
```

but there seems to be an issue with the ProductParameterization operator.

**Comment by sandwichmaker** [comment]
@alexsmac

**Comment by alexsmac** [comment]
As I don't use Windows I'm not sure what's going on here, however [this post](https://stackoverflow.com/questions/11261072/unresolved-external-symbol-vftable-c/11554907#11554907) suggests that the issue might be related to a CRT version mismatch which can be controlled via the Ceres build option: `MSVC_USE_STATIC_CRT`

**Comment by oracle3001** [comment]
I don't believe this is the issue. I have everything involved building using /MD flag and I can build ceres 1.14 (also built with /MD flag and all the same required libraries) and build my project with this old version of ceres without issue.

I can build and use ceres as a static library with my project, but for distribution reasons I would prefer to be able to use it as a dll.

**Comment by sandwichmaker** [comment]
it may have to do with the fact that product parameterization uses
templates, but I do not have any experience with msvc.

**Comment by alexsmac** [comment]
@oracle3001 please can you try removing the `CERES_EXPORT` prefix from the declaration of `ProductParameterization`, i.e. change (in `<CERES_SOURCE_DIR>/include/ceres/local_parameterization.h`):
```
class CERES_EXPORT ProductParameterization : public LocalParameterization
```
to:
```
class ProductParameterization : public LocalParameterization
```
and rebuild Ceres - I *think* from some reading that the issue may indeed be that templated classes cannot be exported in DLLs unless they are explicitly instantiated in the exporting library.  However, as that is not the case here, and as we don't for example use CERES_EXPORT in the Jet  templated class and you are not having issues there I think that might be your problem.

**Comment by oracle3001** [comment]
After rebuilding with that suggested change, I now get the following error messages,

```
1>ceresDeltaModelFit.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl ceres::ProductParameterization::ComputeJacobian(double const *,double *)const " (?ComputeJacobian@ProductParameterization@ceres@@UEBA_NPEBNPEAN@Z)
1>ceresDeltaModelFit.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl ceres::ProductParameterization::Plus(double const *,double const *,double *)const " (?Plus@ProductParameterization@ceres@@UEBA_NPEBN0PEAN@Z)

```

**Comment by ShakilAhmedDhaka** [comment]
Hi @oracle3001 I having the same problem (Unresolved External ceres::ProductParameterization). Have you solved this yet?

**Comment by oracle3001** [comment]
@ShakilAhmedDhaka no I haven't, other than to build as a static library.

However, I did see a mention of something on the ceres google source review.

https://ceres-solver-review.googlesource.com/c/ceres-solver/+/16580

**Comment by sandwichmaker** [comment]
Is this still open, I am not sure what to do here.

**Comment by sandwichmaker** [comment]
Closing because of no response, if there are more details on this, please feel free to reopen.
