### ISSUE TITLE
ceres solver build error

### ISSUE THREAD

**Issue by npd26** [ceres-solver/ceres-solver#550]
Hello,

I am building ceres-solver-1.12.0 using CMAKE GUI and visual studio 2019. I am getting below error in pose_graph_3d and sample_function,

`pose_graph_3d.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl ceres::EigenQuaternionParameterization::Plus(double const *,double const *,double *)const " (?Plus@EigenQuaternionParameterization@ceres@@UEBA_NPEBN0PEAN@Z)
2>sampled_function.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl ceres::CubicInterpolator<struct ceres::Grid1D<double,1,1> >::CubicInterpolator<struct ceres::Grid1D<double,1,1> >(struct ceres::Grid1D<double,1,1> const &)" (__imp_??0?$CubicInterpolator@U?$Grid1D@N$00$00@ceres@@@ceres@@QEAA@AEBU?$Grid1D@N$00$00@1@@Z) referenced in function main
2>sampled_function.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl ceres::CubicInterpolator<struct ceres::Grid1D<double,1,1> >::Evaluate(double,double *,double *)const " (__imp_?Evaluate@?$CubicInterpolator@U?$Grid1D@N$00$00@ceres@@@ceres@@QEBAXNPEAN0@Z) referenced in function "public: void __cdecl ceres::CubicInterpolator<struct ceres::Grid1D<double,1,1> >::Evaluate<struct ceres::Jet<double,1> >(struct ceres::Jet<double,1> const &,struct ceres::Jet<double,1> *)const " (??$Evaluate@U?$Jet@N$00@ceres@@@?$CubicInterpolator@U?$Grid1D@N$00$00@ceres@@@ceres@@QEBAXAEBU?$Jet@N$00@1@PEAU21@@Z)
2>sampled_function.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl ceres::CubicInterpolator<struct ceres::Grid1D<double,1,1> >::Evaluate(double const &,double *)const " (__imp_?Evaluate@?$CubicInterpolator@U?$Grid1D@N$00$00@ceres@@@ceres@@QEBAXAEBNPEAN@Z) referenced in function "public: bool __cdecl InterpolatedCostFunctor::operator()<double>(double const *,double *)const " (??$?RN@InterpolatedCostFunctor@@QEBA_NPEBNPEAN@Z)
2>C:\RoboWrapSVN4_build\VC16_64\dependencies\ceres-solver-1.12.0-build\build\bin\Debug\sampled_function.exe : fatal error LNK1120: 3 unresolved externals
1>pose_graph_3d.obj : error LNK2001: unresolved external symbol "public: virtual bool __cdecl ceres::EigenQuaternionParameterization::ComputeJacobian(double const *,double *)const " (?ComputeJacobian@EigenQuaternionParameterization@ceres@@UEBA_NPEBNPEAN@Z)
1>C:\RoboWrapSVN4_build\VC16_64\dependencies\ceres-solver-1.12.0-build\build\bin\Debug\pose_graph_3d.exe : fatal error LNK1120: 2 unresolved externals
1>Done building project "pose_graph_3d.vcxproj" -- FAILED.
2>Done building project "sampled_function.vcxproj" -- FAILED.`

any idea how can I solve this error?

Thanks and Regards.

**Comment by sandwichmaker** [comment]
Please use a more recent version of Ceres solver and let us know if you are
still having issues.

**Comment by npd26** [comment]
As I required both version (1.14.0 (already build) and 1.12.0) that is why I am trying for 1.12.0.

**Comment by sandwichmaker** [comment]
unfortunately 1.12.0 is more than three years old and we do not support it anymore.
