### ISSUE TITLE
FixedArray using deprecated way to define pointer alias.

### ISSUE THREAD

**Issue by Janos95** [ceres-solver/ceres-solver#551]
The FixedArray class defines a couple of type aliases as follows:

```
  using allocator_type = typename AllocatorTraits::allocator_type;
  using value_type = typename allocator_type::value_type;
  using pointer = typename allocator_type::pointer;
  using const_pointer = typename allocator_type::const_pointer;
  using reference = typename allocator_type::reference;
  using const_reference = typename allocator_type::const_reference;
```
The four latter type aliases were deprecated in C++17 and are removed in C++20.
In particular the head of gcc in C++20 mode fails to compile ceres.

**Comment by sandwichmaker** [comment]
@Janos95  thanks for letting us know, we currently only support c++11. c++20 is barely standardized so, so we should not be expecting ceres to compile in c++20 mode.

**Comment by Janos95** [comment]
well its deprecated in c++17 and the fix is trivial. I could provide a patch?

**Comment by sandwichmaker** [comment]
please do.

http://ceres-solver.org/contributing.html

**Comment by sandwichmaker** [comment]
@Janos95 gentle ping?

**Comment by alexsmac** [comment]
This should be fixed by [this CL](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/17383), it works with GCC 8.4 with CMAKE_CXX_STANDARD=20 (results in CMake passing `-std=gnu++2a`).  However, master also works with this configuration, so evidently the checks have been updated in GCC's master since 8.4.  @Janos95 please can you check that the CL works for you.

**Comment by Janos95** [comment]
Hey great so see this fixed :) Yes this patch works for me, although I am not on the exact same compiler as when submitting the issue ( I am using the latest gcc, e.g. gcc 11).

**Comment by alexsmac** [comment]
Closing as the CL has been merged into master
