### ISSUE TITLE
Alignment issue on quaternion

### ISSUE THREAD

**Issue by finostro** [ceres-solver/ceres-solver#552]
I am getting an [unaligned assertion](http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html) from eigenn, specifically on the quaternion. 

ceres-solver/internal/ceres/local_parameterization.cc:208

p.s. I am using the latest code , compiled with the following configuration (ccmake)
![image](https://user-images.githubusercontent.com/5446036/73183334-67290f80-40f9-11ea-8717-8046078f8e6d.png)

Cheers

**Comment by finostro** [comment]
Fixed it by compiling with c++17, honestly I am not sure if it was an issue with ceres or with the other project that uses it. Anyways Eigen alignment issues are apparently all solved by compiling with c++17.

**Comment by alexsmac** [comment]
The usual reason for this is that you are compiling Ceres and a client project using Ceres with different compile options that affect the compiled output of Eigen, in which case you can get subtle ODR violations as well as other issues.  I suspect that this is an incompatibility between the compile options of your project and Ceres.  However, as you have now resolved the issue I'm going to close this.
