### ISSUE TITLE
AngleAxisToRotationMatrix results does not math Eigen 

### ISSUE THREAD

**Issue by Computational-Camera** [ceres-solver/ceres-solver#560]
It seems the Rotation matrix output is a transpose of the output from Eigen 
i.e.
//===Ceres===
double angle_axis[3] = {0.1722057, -0.4814122, 0.3184683};
AngleAxisToRotationMatrix(angle_axis, R);
//===Eigen===
Eigen::AngleAxisd angle_axis_2 (0.6023575, Eigen::Vector3d(0.2858863, -0.7992134, 0.5287031));
cout<<angle_axis_2.toRotationMatrix()<<endl;

**Comment by sandwichmaker** [comment]
Check if you are expecting a row major or a column major matrix as output

**Comment by Computational-Camera** [comment]
I am expecting a row major matrix, so dose it mean the Rotation matrix in ceres is stored as column major format?

**Comment by sandwichmaker** [comment]
https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/rotation.h#L385

indicates that it returns a column major matrix. you can use the adapter to
get a row major matrix if you like.
