### ISSUE TITLE
Division Operation between parameters is needed in my costfuntion,but it doesn`t work

### ISSUE THREAD

**Issue by Wsdnuaa** [ceres-solver/ceres-solver#564]
a[ ] ,b[ ],sample,line are const .
How could  I to divide block include one parameter by another?
Thank for your watching!
`      struct checkResidual {

	checkResidual(double* sample, double* line,double* a,double* b, stereoAdjustment* sAdjust)
		: sAdjust_(sAdjust) ,a_(a),b_(b){
		sample_1 = sample[0];
		line_1 = line[0];
		sample_2 = sample[1];
		line_2 = line[1];
		sample_3 = sample[2];
		line_3 = line[2];
	}

	template <typename T> bool operator()(

		const T* const lat,
		const T* const lon,
		const T* const h,

		T* residual) const {

		const T NUMS = T(1)*lat[0] + T(2)*lon[0] + T(3)*h[0] + T(4)*lat[0] * lat[0] + T(5)*lon[0] * lon[0] + T(6)*h[0] * h[0];
		const T DENS = T(3)*lat[0] + T(5)*lon[0] + T(6)*h[0] + T(7) * lat[0] * lat[0] + T(11) * lon[0] * lon[0] + T(13) * h[0] * h[0];
		const T NUML = T(5)*lat[0] + T(13)*lon[0] + T(17)*h[0] + T(1)*lat[0] * lat[0] + T(3)*lon[0] * lon[0] + T(11)*h[0] * h[0];
		const T DENL = T(7)*lat[0] + T(5)*lon[0] + T(3)*h[0] + T(7) * lat[0] * lat[0] + T(13) * lon[0] * lon[0] + T(17) * h[0] * h[0];
		const T x1 = NUMS / DENS;
		const T x2 = NUML / DENL;

		//cout << "x = " << sAdjust__->x[0] << "sample = " << sample_1 << endl;

		residual[0] = a_[0] + a_[1] * sample_1 + a_[2] * line_1 - sample_1 + x1;
		residual[1] = b_[0] + b_[1] * sample_1 + b_[2] * line_1 - line_1 + x2;
		residual[2] = a_[3] + a_[4] * sample_2 + a_[5] * line_2 - sample_2 + x1;
		residual[3] = b_[3] + b_[4] * sample_2 + b_[5] * line_2 - line_2 +x2;
		residual[4] = a_[6] + a_[7] * sample_3 + a_[8] * line_3 - sample_3 + x1;
		residual[5] = b_[6] + b_[7] * sample_3 + b_[8] * line_3 - line_3 + x2;
		//cout << sAdjust_->displayRpcParameters << endl;
		return true;

	}
       private:
	stereoAdjustment* sAdjust_;

	double sample_1;
	double line_1;
	double sample_2;
	double line_2;
	double sample_3;
	double line_3;
	double *a_;
	double *b_;

}; `

The mistake information is:
`Error in evaluating the ResidualBlock.

There are two possible reasons. Either the CostFunction did not evaluate and fill all
residual and jacobians that were requested or there was a non-finite value (nan/infinite)
generated during the or jacobian computation.

Residual Block size: 3 parameter blocks x 6 residuals

For each parameter block, the value of the parameters are printed in the first column
and the value of the jacobian under the corresponding residual. If a ParameterBlock was
held constant then the corresponding jacobian is printed as 'Not Computed'. If an entry
of the Jacobian/residual array was requested but was not written to by user code, it is
indicated by 'Uninitialized'. This is an error. Residuals or Jacobian values evaluating
to Inf or NaN is also an error.`

**Comment by sandwichmaker** [comment]
your error message is truncated. it does not say anything about it not being possible to divide by a parameter, but rather that you are likely dividing by zero. look at the whole message it has details.

**Comment by sandwichmaker** [comment]
I am going to close this, please re-open if you believe there is a problem with ceres.
