### ISSUE TITLE
Optimize Away Zero Multiplications

### ISSUE THREAD

**Issue by darglein** [ceres-solver/ceres-solver#566]
I'm currently working on a few optimization passes and found that evaluating zero multiplications improves performance by at least 15%. In particular these optimizations are:

```
v_1 = 0 * v_0    ->    v_1 = 0
v_1 = v_0 * 0    ->    v_1 = 0
```

Such multiplications are extremely common in forward autodiff because the derivative part is initialized with 0. The compiler cannot apply this by itself, because it changes `nan correctness`. For example:

v_0 = nan
v_1 = 0 * v_0

evaluates to `v_1 = nan` instead of `v_1 = 0`.

**Do you think this could have a negative effect on any cost functors?**

My own answer to this question:

I don't think this optimization will have a negative effect, but I would probably add a `strict` flag to the optimizer, which forces codegen code exactly to autodiff code. This optimization might actually make forward AD more intuitive then before. For example:

```
// v_0 == -1
v_0 = parameters[1][2];
v_1 = sqrt(v_0);
// v_1 == nan
```

In old autodiff the complete derivative vector of parameter (1,2) would be nan because the initial 0 is multiplied with nan. With the optimization from above, only the residual and the respective partial derivative are nan.

**Comment by sandwichmaker** [comment]
I do not think this is right. If you do nan * 0, and propagate that zero, then you risk eliminating entirely fragements of code which maybe doing bad things no? for example where the nan is generated as an intermediate computation, gets multiplied by an explicit zero which we know at compile time and the result is then propagated.

**Comment by darglein** [comment]
Is this a problem in an actual case you can think of? Have you ever written an explicit zero multiplication and expected the result to not be zero?

I feel like we would waste a lot of potential by not applying this at all.

**Comment by sandwichmaker** [comment]
no thats not what I mean. if I understand you correctly, your optimization rests on the assumption that as long as one nan shows up in the final result, it is as good as all the nans showing up. I am saying this cannot be guaranteed, because once you start zeroing the nans out, you may actually end up eliminating them entirely, and the user may get the impression that their code is working correctly when it is not.

Further, yes we can have a strict mode, but no is going to use it, everyone wants performance.

**Comment by darglein** [comment]
Ah ok, I understand you now. There might be a weird case were all nans are removed and the user thinks the code is working fine. 

My suggestion would be to add a flag like this:
```
ENABLE_UNSAFE_OPTIMIZATIONS, default = OFF
    Enable compiler optimization, which do not conform to the IEEE 754 
    floating point standard. In particular, these optimizations are:
        - v_1 = 0 * v_0     ->     v_1 = 0
        - v_1 = 0 / v_0     ->     v_1 = 0
    These optimizations are not standard conform, because they do not propagate NaN correctly.
    If your code relies on correct NaN propagation or is used in a sensitive environment,
   we strongly recommend to disable these optimizations.
```

**Comment by sandwichmaker** [comment]
This goes back to my point earlier, people will use this without understanding the implications. Basically the effect of this is untestable, which means people have to guess and they will always choose faster..

**Comment by darglein** [comment]
I think we have different views on what this system actually is and what it should do.

For me, autodiff codegen is a tool that is able to create efficient derivatives which are mathematically correct. The optimizer applies symbolic transformations similar to other math tools (Matlab...).

For testing I'm using a Disney BRDF functor, for which I have a hand optimized analytic derivative. Interestingly, with all optimizations, the codegen code and the analytic code is almost exactly the same. This kind of matches the argument of a previous thread, where we discussed how forward and backward AD converges towards the same optimal code. Without the zero-optimization, the codegen code was 2-3 times slower because it consists of around 80% zero-multiplications.

This is also not the only optimization, which might be problematic from a c++ point of view, but totally fine in a mathematical context:
```
y = sin(x)         ->     y = sin(x)
z = sin(x)         ->     z = y
Not allowed because implementation not visible.
```
```
y = (a * b) * z         ->     y = (a * b) * z
z = a * (b * z)         ->     z = y
Not allowed because floating point is not associative.
```

**Conclusion**

The optimizer should operate on a symbolic level (like Matlab and co.). If we don't do that, all optimizations are kind of pointless, because modern C++ compilers already provide them. To make it more clear it should maybe be renamed to `SymbolicOptimizer`.

**Comment by darglein** [comment]
Here are some result for the Disney BRDF benchmark:
```
Jet AutoDiff                              1709 ns       1708 ns     409731
Codegen no optimizations                   210 ns        209 ns    2474645
Codegen all opt. except 0-mult removal     205 ns        205 ns    3397520
Codegen all opt.                           105 ns        105 ns    6638301
Analytic                                   105 ns        104 ns    6715742
```
Here we can see three things:

- With optimizations codegen AD is identical to analytic diff.
- Optimizations improve codegen code by a factor of 2
- Forward AD is dominated by zero mults
- If we do not optimize zero mults, all other optimizations are (almost) meaningless

**Comment by jkflying** [comment]
@darglein have you tried `Jet Autodiff` with putting the cost functions into their own compilation unit with `-ffast-math` enabled. This should get the *0 optimized out. It might be necessary to specify to Eigen to use `EIGEN_DONT_VECTORIZE` for that compilation unit too so that the compiler has visibility into the operations that are happening and can do algebraic simplification.

**Comment by darglein** [comment]
Thanks for the hint. Here are the results with GCC 9.2.1 and -O3:

```
BM_DisneyAutoDiff/Residual+Jacobian:1       1691 ns       1691 ns     414255
BM_DisneyAnalytic/Residual+Jacobian:1        102 ns        102 ns    6902948
BM_DisneyCodeGen/Residual+Jacobian:1         106 ns        106 ns    6626274
```

-ffast-math
```
BM_DisneyAutoDiff/Residual+Jacobian:1       1691 ns       1691 ns     412109
BM_DisneyAnalytic/Residual+Jacobian:1         95 ns         95 ns    7327647
BM_DisneyCodeGen/Residual+Jacobian:1          89 ns         88 ns    7917915
```

EIGEN_DONT_VECTORIZE

```
BM_DisneyAutoDiff/Residual+Jacobian:1       2371 ns       2371 ns     295020
BM_DisneyAnalytic/Residual+Jacobian:1        113 ns        113 ns    6567172
BM_DisneyCodeGen/Residual+Jacobian:1         111 ns        110 ns    6377158
```

EIGEN_DONT_VECTORIZE + -ffast-math

```
BM_DisneyAutoDiff/Residual+Jacobian:1       2367 ns       2366 ns     296223
BM_DisneyAnalytic/Residual+Jacobian:1         98 ns         98 ns    7010261
BM_DisneyCodeGen/Residual+Jacobian:1          88 ns         88 ns    7963344
```

**Comment by sandwichmaker** [comment]
Excellent, I like this path very much. We can add comments about compiling this code and the effect of -ffast-math.
