### ISSUE TITLE
Codegen Benchmarks

### ISSUE THREAD

**Issue by darglein** [ceres-solver/ceres-solver#567]
What are some good cost functors to benchmark forward AD?

Does it make sense to use synthetic functors?

The current benchmark results for angle-axis BA are:

```
-----------------------------------------------------------
Benchmark                    Time           CPU Iterations
-----------------------------------------------------------
BM_BAAutoDiff/R:0           35 ns         35 ns   19893698
BM_BAAutoDiff/R+J:1        218 ns        218 ns    3203069
BM_BACodeGen/R:0            35 ns         35 ns   20134726
BM_BACodeGen/R+J:1         111 ns        110 ns    6331586
```

**Comment by sandwichmaker** [comment]
I think a mix of synthetic and real functors would be nice. It would be worth asking on the mailinglist if people are willing to share some of their cost functors.

there is also a quaternion variant of the bundle adjustment error, which is also worth looking at.

**Comment by sandwichmaker** [comment]
Going to close this in light of the recent work.
