### ISSUE TITLE
RegionsAlias 

### ISSUE THREAD

**Issue by LeisureLei** [ceres-solver/ceres-solver#568]
I use ceres to optimize pose and I use quaternion to represent rotation.But the code failed.

WARNING: Logging before InitGoogleLogging() is written to STDERR
F0226 10:35:22.432909  7620 problem_impl.cc:82] Check failed: !RegionsAlias(existing_block, existing_block_size, new_block, new_block_size) Aliasing detected between existing parameter block at memory location 0x7f4561fff830 and has size 3 with new parameter block that has memory address 0x7f4561fff820 and would have size 4.
*** Check failure stack trace: ***
[1]    7586 abort (core dumped)

**Comment by sandwichmaker** [comment]
You are passing two different parameter blocks but they refer to the same memory.

**Comment by cyclojc** [comment]
`
ceres::CostFunction* vio_function = RelativeRTError::Create(iPj.x(), iPj.y(), iPj.z(),
                                                                                iQj.w(), iQj.x(), iQj.y(), iQj.z(),s_array[i][0],
                                                                                var[0], var[1], var[2]);
 vo_block_id = problem.AddResidualBlock(vio_function, NULL, q_array[i], t_array[i], q_array[i+1], t_array[i+1], s_array[i])`


I'm encountering almost the same issue, but I dont really understand why this does not happen all the time. 
Sometimes ceres went thru the whole bag file, processed all information without a problem. Sometimes it crashes with this check failed.

I also don't get how should I construct a relative constraint (binary) that binds two consecutive parameter blocks without refering to the same parameter block?
