### ISSUE TITLE
Is ceres solver 2.0 officially released yet?

### ISSUE THREAD

**Issue by Beck-Sisyphus** [ceres-solver/ceres-solver#570]
Dear ceres developer,

The current build demonstrate the ceres solver has marched to version 2.0, yet in your milestone it is still 55% complete. I wish to fetch the current version into my own project, so I am curious whether it is officially released, and if not when is the release date.

Sincerely,

Beck

**Comment by sandwichmaker** [comment]
No Ceres solver 2.0 is not released yet. There is a bunch of work that
still needs to be done.

**Comment by Beck-Sisyphus** [comment]
> No Ceres solver 2.0 is not released yet. There is a bunch of work that still needs to be done.
> […](#)

Thanks for your reply.
