### ISSUE TITLE
Possibly mistake in the document.

### ISSUE THREAD

**Issue by ymd-ponyai** [ceres-solver/ceres-solver#573]
http://ceres-solver.org/nnls_modeling.html#theory
If I use rho = log(1 + s), the \tilde f will equal \sqrt { \frac {1} {1-s} } f which is greater than f.

**Comment by sandwichmaker** [comment]
@ymd-ponyai I am not sure what you mean, are you saying the original triggs derivation is wrong or did I replicate it wrong?

**Comment by ymd-ponyai** [comment]
I was trying to hand-calculate the residual after applying `CauchyLoss(1.0)`. By following your document (and Triggs') I found a difference between ceres' `Evaluate` and my calculation.

**Comment by ymd-ponyai** [comment]
Without the loss function the output is trivial and I can verify easily.

**Comment by ymd-ponyai** [comment]
Hi @sandwichmaker , I think I found the reason.
In `corrector.cc` lines 81-85, if `rho''` < 0, then the scaling factor used does not contain the denominator `1-\alpha`.

I suggest this part is added to the web-page document with a reference to the nicely written code comments.

**Comment by sandwichmaker** [comment]
@ymd-ponyai I finally had a chance to look at this, as I suspected this is an empirical hack that we discovered when experimenting with the Triggs correction. I will add a pointer to the documentation.
