### ISSUE TITLE
when using SCHUR(DENSE_SCHUR or SPARSE_SCHUR), the solution is not quite the same in every time (bit inconsistent)，but the solution of SPARSE_NORMAL_CHOLESKY is consistent.  

### ISSUE THREAD

**Issue by luoyin500** [ceres-solver/ceres-solver#577]
when using multi-threading, in SCHUR(DENSE_SCHUR or SPARSE_SCHUR), the solution is not quite the same in every time (bit inconsistent)，but the solution of SPARSE_NORMAL_CHOLESKY is consistent.

**Comment by sandwichmaker** [comment]
are you using threading?

**Comment by luoyin500** [comment]
Year, multi-threading. I wander is there any way to reduce the bit inconsistence, thanks.

**Comment by luoyin500** [comment]
> are you using threading?
Year, multi-threading. I am searching the key function causing the bit-inconsistence. And I wander the is there any way to reduce bit-inconsistence.

**Comment by sandwichmaker** [comment]
The schur eliminator used in SPARSE_SCHUR or DENSE_SCHUR is threaded and threading can introduce non-determinism.
