### ISSUE TITLE
Preconditioning general unconstrained minimization problems

### ISSUE THREAD

**Issue by SteveMacenski** [ceres-solver/ceres-solver#578]
Hi,

I'm working on building an open-source general path smoothing technique for ROS2. On this journey, I've found that I require to work with an unconstrained minimization problem rather than the NLLS because the each waypoint on a robot's path depends on each other for smoothness and curvature in a way that I could not find a reasonable way to model in the residual block framework (e.g. each waypoint is a residual block, I need to find the current parameters for neighboring blocks' values as well).

As such, I'm working with the unconstrained minimization problem API to model the same thing but setting up the problem myself and I use the `FirstOrderFunction` evaluation looks like (I can provide actual links if you want):

```
for each point:
  get_neighbors();
  apply_term1();
  apply_term2();
  apply_termN();
  if (compute_jacobian):
    apply_term1_jacobian();
    apply_termN_jacobian();
```

Now I found that does a pretty "ok" job at smoothing my path and applying my terms. I'm currently using the CG optimizer, but I'm not married to any particular technique. I'm looking for consistent performance over technique since this will be running on robots in real-time maybe once a few seconds. However the most common form of termination is:

```
CONVERGENCE (Parameter tolerance reached. Relative step_norm: 0.000000e+00 <= 1.000000e-15.)
```

The `0e0` makes me believe its poorly conditioned, and that's not surprising. For awhile I assumed there was something intrinsically wrong with my problem but with the iterations it does accomplish, it does do quite a bit. Unexpectedly though, if I take the output and shove it back into another optimization run (or 3 runs), the result continues to get better and better, sometimes terminating with the `0e0` but more likely to terminate with some real value (e.g. `4.261397e-17`).

This further indicates to me its because of poor conditioning from reading this thread (https://groups.google.com/forum/#!topic/ceres-solver/SEtXIMQwq88).

My question is then: how can I precondition general unconstrained minimization problems with Ceres? And if its not possible, how "bad form" is it to shove the output into a new optimization run a few times to continuously refine the results? 

Edit: I figure you guys might get a kick out of a visual demonstration. The red with arrows is the 1 time run and the black is the output of 4 runs feeding into each other. Quite a bit smoother from a human view. This particular setting set was `BFGS` with `use_approximate_eigenvalue_bfgs_scaling = true` in line with suggestions here (https://groups.google.com/forum/#!msg/ceres-solver/L1aWSp_-qRg/oLPieCWcCQAJ) which did help have more "valid" convergences (e.g. non-`0e0`) but clearly running multiple times still refines the estimate and still had plenty of `0e0`s.

![image](https://user-images.githubusercontent.com/14944147/78322471-a58ce180-7523-11ea-8915-842d36ae38cb.png)

**Comment by sandwichmaker** [comment]
can you share the output of Summary::FullReport please? or better still run it with -v=2 and share the output. @alexsmac may have some insights.

**Comment by SteveMacenski** [comment]
See attached outputs, I included the `minimizer_progress_to_stdout` outputs as well so its a little messy so they're individual files. These 2 runs are 2 consecutive iterations of the path smoother, so there's only 2 waypoints difference as the robot is moving, one converges by a real cost change, the other from the `0e0`. 

[cost_change_converge.txt](https://github.com/ceres-solver/ceres-solver/files/4429997/cost_change_converge.txt)
[param_change_converge.txt](https://github.com/ceres-solver/ceres-solver/files/4429998/param_change_converge.txt)

Googlng shows that `-v=2` is a google logging thing - I'm not using google logging in the application in way I have control over, is there any way I can set that inside of C++? I cannot add arbitrary commandline arguments in ROS2.

**Comment by alexsmac** [comment]
Set GLOG_v=2 in the terminal prior to running the application, glog checks
for environment variables matching the glog gflag names but prefixed with
'GLOG_'.  You can also use SetVLOGLevel(), but I think the environment
variable route is better.

**Comment by SteveMacenski** [comment]
The issue is that ROS2 also uses glogging, when you set that in the environment, I receive thousands of messages a second from callback groups and other middleware communications debugging. I used the SetVLOG with  the attempts:

```
google::SetVLOGLevel("*", 2);
google::SetVLOGLevel("planner_server", 2);
google::SetVLOGLevel("", 2);
```

and none changed the output. Still the same output with `minimizer_progress_to_stdout` set to true and printing the full summary.

**Comment by sandwichmaker** [comment]
https://groups.google.com/g/google-glog/c/f8D7qpXLWXw
The vmodule behaviour does not work on non-gcc compilers it seems.

**Comment by sandwichmaker** [comment]
Closing this because glog is not used anymore and there hasn't been any further followup.
