### ISSUE TITLE
dllimport bug

### ISSUE THREAD

**Issue by ygwangmsra** [ceres-solver/ceres-solver#580]
I built ceres with shared library on VS2019, it can be successfully built. But when I try to import the library, the compiler trigers the error like:
 

> ceres 'ceres::LineParameterization<AmbientSpaceDimension>::Plus': definition of dllimport function not allowed

By the way, ceres can be built and used with static library under VS2019.  Is it a dll export bug?

**Comment by zengletian1491** [comment]
I meet the same quesion! Do you solve it ?

**Comment by zengletian1491** [comment]
Solution:
In "Release - 64" mode,  I add some commands in the "property - c/c++ -precompiler - precompiler definition"  in the following:
_CONCOLE
NDEBUG
WIN32
_WINDOWS
CERES_BUILDING_SHARED_LIBRARY
_USE_MATH_DEFINES
_VARIADIC_MAX=10
CERES_SUITESPARSE_VERSION="5.4.0"
GLOG_NO_ABBREVIATED_SEVERITIES
GOOGLE_GLOG_DLL_DECL=__declspec(dllimport)
GOOGLE_GLOG_DLL_DECL_FOR_UNITTESTS=__declspec(dllimport)
GFLAGS_IS_A_DLL=1
CMAKE_INTDIR="Release"
ceres_EXPORTS

**Comment by sandwichmaker** [comment]
https://ceres-solver-review.googlesource.com/c/ceres-solver/+/17201 is in flight to address this issue.

**Comment by sandwichmaker** [comment]
Should be fixed at head. If it is still open please re-open bug.
