### ISSUE TITLE
unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA) 

### ISSUE THREAD

**Issue by zengletian1491** [ceres-solver/ceres-solver#581]
I compiled the newest version of ceres-sover on Windows 10 system(64 bit) with CMake 3.16 and visual studio 2017. After "Configuring done" and "Generating done", I opened Ceres.sln and build solution with "Debug x64" and "Release x64" mode, repectively. Also, I added the include directory, the library directory and the added dependencies of ceres-solver. However, errors still occurred as follows:

**2>  Creating library F:/ceres-solver/build_/lib/Release/ceres.lib and object F:/ceres-solver/build_/lib/Release/ceres.exp
2>visibility_based_preconditioner.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>wall_time.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>suitesparse.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>trust_region_preprocessor.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>trust_region_minimizer.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>visibility.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>polynomial.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>reorder_program.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>schur_eliminator.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>solver.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>linear_least_squares_problems.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>low_rank_inverse_hessian.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>minimizer.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>partitioned_matrix_view.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>iterative_schur_complement_solver.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>line_search.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>line_search_direction.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>line_search_minimizer.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>detect_structure.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>dogleg_strategy.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>dynamic_sparse_normal_cholesky_solver.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>eigensparse.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>callbacks.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>compressed_row_sparse_matrix.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>covariance_impl.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>dense_qr_solver.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>block_random_access_diagonal_matrix.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>block_random_access_sparse_matrix.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>block_sparse_matrix.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>canonical_views_clustering.obj : error LNK2001: unresolved external symbol "int fLI::FLAGS_v" (?FLAGS_v@fLI@@3HA)
2>F:\ceres-solver\build_\bin\Release\ceres.dll : fatal error LNK1120: 1 unresolved external command**

Could you give me some suggestions? Thank you.

**Comment by alexsmac** [comment]
I think your version of glog was compiled with gflags, but that you did not provide the details to find gflags when Ceres was built so Ceres assumed that glog was built without gflags support.  However, when you try to link you are missing the corresponding gflags symbols referenced by glog.  The solution if that is the case is to set the paths for gflags s/t it is detected when Ceres is built (you should use the same version that was used to compile the version of glog you are linking).

**Comment by zengletian1491** [comment]
I used gflags-2.2.2 and glog-0.4.0, I give the right information to find gflags-2.2.2 when Ceres was built . Just now, I recompiled gflags-2.2.2, glog-0.4.0 and ceres-solver again, it works! Thank you very much!
