### ISSUE TITLE
Wrong destination of cmake configurations files when building with catkin

### ISSUE THREAD

**Issue by jcarius** [ceres-solver/ceres-solver#582]
Hi,
I'm building a [catkin](http://wiki.ros.org/catkin) package that depends on ceres-solver. If I install ceres on my system in the default way and then `find_package(Ceres)` everything works fine.
However, since I noticed that Ceres already contains a catkin `package.xml` manifest, I wanted to build it automatically in my catkin workspace. Unfortunately, when doing so (`catkin build ceres-solver`), the CMake configuration files end up in the wrong directory and cannot be found by the catkin package discovery process:

**Current behavior**
CMake configuration files end up in `catkin_ws/devel/lib/cmake/Ceres`.
**Expected behavior**
Cmake configuration files should end up in `catkin_ws/devel/share/ceres-solver/cmake/`

**Question**
* Is it possible to detect whether we're building in a catkin workspace and change the [`RELATIVE_CMAKECONFIG_INSTALL_DIR`](https://github.com/ceres-solver/ceres-solver/blob/57cf20aa5d3c1b2f25d255814f4fff5260db81c6/CMakeLists.txt#L723) variable in the top level ceres `CMakeLists.txt` accordingly?
* Should the package name in `package.xml` not match the project name in the `CMakeLists.txt`?

**Steps to reproduce on Ubuntu 18.04 LTS** (assuming catkin commandline tools are installed `apt-get install python-catkin-tools`)

1. Create a catkin workspace
1. Clone ceres into the source space
1.  `catkin build ceres-solver`

**Comment by sandwichmaker** [comment]
ping?

**Comment by NikolausDemmel** [comment]
> Is it possible to detect whether we're building in a catkin workspace and change the RELATIVE_CMAKECONFIG_INSTALL_DIR variable in the top level ceres CMakeLists.txt accordingly?

I think this is intended. Ceres is not packaged as a catkin package, but rather the package.xml allows it to build as a pure cmake package in your caktin workspace. You should also find it with `find_package(Ceres)` from your catkin package. That seems to work fine.

> Should the package name in package.xml not match the project name in the CMakeLists.txt?

No, I think `ceres-solver` is idiomatic for ros packages / dependency names.

> Steps to reproduce on Ubuntu 18.04 LTS

Works fine for me if I <..depend> on ceres-solver in another package and then `find_package(Ceres)`.

So IMHO this issue can be closed.
