### ISSUE TITLE
inquire about how to get the Jacobian matrix

### ISSUE THREAD

**Issue by weisongwen** [ceres-solver/ceres-solver#584]
@sergeyvfx 
First, thanks for the great work on Ceres. 

I am employing the Ceres solver to do optimization in robotics SLAM problem. How can I get the Jacobian matrix after the optimization converge?

I refer to the issue [here](https://groups.google.com/forum/#!topic/ceres-solver/2tBpYBgT9SM) . However, it is still not clear how the Jacobian matrix can be acquired. :-)

Thanks a lot in advance.

**Comment by sandwichmaker** [comment]
Problem::Evaluate is your friend.

**Comment by sandwichmaker** [comment]
http://ceres-solver.org/nnls_modeling.html#_CPPv2N5ceres7Problem8EvaluateERKN7Problem15EvaluateOptionsEPdP6vectorIdEP6vectorIdEP9CRSMatrix

**Comment by weisongwen** [comment]
@sandwichmaker Many thanks. I will try it accordingly :-)
