### ISSUE TITLE
Solver problem num_threads > 1 leads to non-reprodudible results

### ISSUE THREAD

**Issue by jkflying** [ceres-solver/ceres-solver#585]
If you add to the SolverOptions in libmv_bundle_adjuster.cc `options.num_threads = 4;`, and compile and run libmv on the sample data, it will give slightly different results for the camera intrinsics every time. With the default of `options.num_threads = 1;` it gives consistent results.

I thought this was related to pointer ordering of the cost function blocks, but it seems having the pointers in a consistent order doesn't fix it. Investigating further.

**Comment by jkflying** [comment]
Further investigation shows that restricting `options.max_linear_solver_iterations = 24;` or lower is able to make `libmv_bundle_adjuster` reproducible on `problem_02.bin`.

I'm not sure if this is just not exposing the case where some numerical issue occurs or if it is in the linear_solver_iterations logic somewhere, but it's the first other solver parameter I've tested which seems to influence this reproducibility issue.

**Comment by jkflying** [comment]
Confirmed this is something to do with the `ITERATIVE_SCHUR` linear solver. I've now tested:
```SPARSE_SCHUR
SPARSE_NORMAL_CHOLESKY
DENSE_SCHUR
CGNR
```
and none of them have any repeatability issues I see with the default ITERATIVE_SCHUR in libmv.

As an aside, on `problem_01.bin` `ITERATIVE_SCHUR` requires nearly 300 iterations to converge, whereas with `SPARSE_SCHUR` it converges in under 100. This means that libmv doesn't converge on it's own sample problems as-shipped with the 100 iteration limit, which is a pity. Not sure if this is a regression, but this is the current state at least.

**Comment by jkflying** [comment]
I've narrowed it down to the y block elimination loop in the Schur elimination. With that ParallelFor loop set to 1 thread it gives repeatable results, without it gives different results each run.

**Comment by sandwichmaker** [comment]
Is there a threading bug there?

**Comment by jkflying** [comment]
Not a threading bug as far as I can tell, I also tried running in TSAN and no warnings.

However, it seems sensitive to the ordering. Running the loop single-threaded from 0...(n-1) gives different results to running the loop from (n-1)...0. I haven't gone into the details of the math there, does this make sense though? Is there some possibility of a data dependency from previous iterations?

**Comment by sandwichmaker** [comment]
I will take a look.

**Comment by sandwichmaker** [comment]
Julian can you be more specific about he function name/line number you are
talking about?
Are you talking about the Eliminate function or are you talking about the
BackSubstitute function?

**Comment by jkflying** [comment]
It is the second ParallelFor in the Eliminate function. The one with the comment block above, starting with `// Eliminate y blocks one chunk at a time.  For each chunk, compute...`

**Comment by sandwichmaker** [comment]
Okay so this is the main work that the schur eliminator does.
Here I expect things to be different depending on threading since floating
point arithmetic is not associative.
For example, given an array of numbers, the final answer you get matters on
the order in which the numbers are summed (
https://en.wikipedia.org/wiki/Kahan_summation_algorithm).

Thats roughly whats going on here too. When you multithread an operation
like this, you can get numerically different answers.

I think for testing purposes you should think about running ceres in single
threaded mode. But regardless of that this also indicates that the
optimization problem you are solving is giving rise to some fairly poorly
conditioned optimization problems and that is also something worth paying
attention to in general.

**Comment by jkflying** [comment]
Ok, if we don't expect these to be independent and then merged in order (sort of map-reduce style) then that's fine. I generally prefer to use an exact solver anyways since my Jacobians fit in memory, I was just concerned there might be a bug here.

You bring up Kahan summation, I've used it elsewhere in several places with great success. I guess it would be possible to do that here as well, but if this is already the bottleneck then it would give a ~4x slowdown so wouldn't be practical.

About I'll formed problems, these results are from libmv on the sample datasets, so nothing particularly crazy. Libmv locks the first camera  which should at least make it full rank.
