### ISSUE TITLE
OpenMP with Ceres

### ISSUE THREAD

**Issue by XYWang-coder** [ceres-solver/ceres-solver#587]
Hi,

I have a problem when using openmp with ceres. If I use OpenMP, there will be a breakpoint in addrisudalblock. So I want to know how to use OpenMP correctly when constructing a problem and the corresponding residulblock. May I ask if there is any suggestion ？

-------------------------------------------------------------------------------------------------------------------------------------
      #pragma omp parallel for
        for (int i = 0; i < nv; i++)
        {
            if (V_visible(i, k) == 1)
            {
                double w_i_k = sqrt(W(i, k));
                Vector3dt V_i(double(points[3 * i]), double(points[3 * i + 1]), double(points[3 * i + 2]));
                for (int j = 0; j < image_num; j++)
                {
                    Vector3dt I_ij(double(I(i, j * image_num)), double(I(i, j * image_num + 1)), double(I(i, j * image_num + 2)));
                    ceres::CostFunction *costone = new ceres::AutoDiffCostFunction<PoseCostFunctionOne, 1, 3, 3>
                            (new PoseCostFunctionOne(I_ij, V_i, cam_0, cam_1, cam_2, cam_3, theight, twidth, color[j], w_i_k));
                    problem.AddResidualBlock(costone, NULL, euler, trans);
                }
            }
        }
-------------------------------------------------------------------------------------------------------------------------------------

**Comment by sandwichmaker** [comment]
ceres::Problem is not thread safe. You cannot use threading when constructing the problem.  Also problem construction is quite fast, so I am surprised that you are having to multithread it. If your problem is so large that you are having to multithread the construction, I suspect you are going to spend a lot more time solving it.
