### ISSUE TITLE
Residual -nan while using ceres::pow

### ISSUE THREAD

**Issue by XYWang-coder** [ceres-solver/ceres-solver#594]
Hello,

When I use ceres::pow(base, 1.0/2.2) I got -nan of the residual . If I use ceres::pow(base, 1.0/2.0) the residual is a normal number. May I ask the reason for generating -nan？Thank you very much for your reply.

Here is part of my cost function.
--------------------------------------------------------------------------------------------------------------------------------------
bool operator()(const T* const Ni, T *residual) const {
            T i_diff = Ni[0] * T(Lij_x) + Ni[1] * T(Lij_y) + Ni[2] * T(Lij_z);
            T i_spec = Ni[0] * T(Hijk_x) + Ni[1] * T(Hijk_y) + Ni[2] * T(Hijk_z);
            T base = T(rhod_il) * i_diff + T(rhos_il) * ceres::pow(i_spec, double(2.0));
            T I_hat_ijkl = ceres::pow(base, double(1.0 / 2.2));

            residual[0] = T(w_ik) * (I_hat_ijkl - T(I_ijkl));

            std::cout << w_ik << " " << I_hat_ijkl.a() << " " << I_ijkl << std::endl;

            return true;
        }

The ouput is
------------------------------------------------------------------------------------------------------------------------------------
0.302905 [0.471195 ; 0.0901918, -0.535998, 0.552469] 0.201789
0.302905 -nan 0.201789
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0524 16:04:31.435457 18450 residual_block.cc:131] 

Error in evaluating the ResidualBlock.

There are two possible reasons. Either the CostFunction did not evaluate and fill all    
residual and jacobians that were requested or there was a non-finite value (nan/infinite)
generated during the or jacobian computation. 

Residual Block size: 1 parameter blocks x 1 residuals

For each parameter block, the value of the parameters are printed in the first column   
and the value of the jacobian under the corresponding residual. If a ParameterBlock was 
held constant then the corresponding jacobian is printed as 'Not Computed'. If an entry 
of the Jacobian/residual array was requested but was not written to by user code, it is 
indicated by 'Uninitialized'. This is an error. Residuals or Jacobian values evaluating 
to Inf or NaN is also an error.  

Residuals:             -nan 

Parameter Block 0, size: 3

    -1.86917 | Not Computed  
    0.082879 | Not Computed  
    0.316824 | Not Computed  

W0524 16:04:31.438259 18450 trust_region_minimizer.cc:733] Step failed to evaluate. Treating it as a step with infinite cost
0.302905 -nan 0.201789
W0524 16:04:31.438285 18450 residual_block.cc:131] 

Error in evaluating the ResidualBlock.

There are two possible reasons. Either the CostFunction did not evaluate and fill all    
residual and jacobians that were requested or there was a non-finite value (nan/infinite)
generated during the or jacobian computation. 

Residual Block size: 1 parameter blocks x 1 residuals

For each parameter block, the value of the parameters are printed in the first column   
and the value of the jacobian under the corresponding residual. If a ParameterBlock was 
held constant then the corresponding jacobian is printed as 'Not Computed'. If an entry 
of the Jacobian/residual array was requested but was not written to by user code, it is 
indicated by 'Uninitialized'. This is an error. Residuals or Jacobian values evaluating 
to Inf or NaN is also an error.  

Residuals:             -nan 

Parameter Block 0, size: 3

    -1.86913 | Not Computed  
   0.0828734 | Not Computed  
    0.316829 | Not Computed  

W0524 16:04:31.438297 18450 trust_region_minimizer.cc:733] Step failed to evaluate. Treating it as a step with infinite cost
0.302905 -nan 0.201789
W0524 16:04:31.438313 18450 residual_block.cc:131] 

Error in evaluating the ResidualBlock.

There are two possible reasons. Either the CostFunction did not evaluate and fill all    
residual and jacobians that were requested or there was a non-finite value (nan/infinite)
generated during the or jacobian computation. 

Residual Block size: 1 parameter blocks x 1 residuals

For each parameter block, the value of the parameters are printed in the first column   
and the value of the jacobian under the corresponding residual. If a ParameterBlock was 
held constant then the corresponding jacobian is printed as 'Not Computed'. If an entry 
of the Jacobian/residual array was requested but was not written to by user code, it is 
indicated by 'Uninitialized'. This is an error. Residuals or Jacobian values evaluating 
to Inf or NaN is also an error.  

Residuals:             -nan 

Parameter Block 0, size: 3

    -1.86894 | Not Computed  
   0.0828399 | Not Computed  
    0.316862 | Not Computed  

W0524 16:04:31.438328 18450 trust_region_minimizer.cc:733] Step failed to evaluate. Treating it as a step with infinite cost
0.302905 -nan 0.201789
W0524 16:04:31.438350 18450 residual_block.cc:131] 

Error in evaluating the ResidualBlock.

There are two possible reasons. Either the CostFunction did not evaluate and fill all    
residual and jacobians that were requested or there was a non-finite value (nan/infinite)
generated during the or jacobian computation. 

Residual Block size: 1 parameter blocks x 1 residuals

For each parameter block, the value of the parameters are printed in the first column   
and the value of the jacobian under the corresponding residual. If a ParameterBlock was 
held constant then the corresponding jacobian is printed as 'Not Computed'. If an entry 
of the Jacobian/residual array was requested but was not written to by user code, it is 
indicated by 'Uninitialized'. This is an error. Residuals or Jacobian values evaluating 
to Inf or NaN is also an error.  

Residuals:             -nan 

Parameter Block 0, size: 3

    -1.86708 | Not Computed  
   0.0825279 | Not Computed  
    0.317164 | Not Computed  

W0524 16:04:31.438361 18450 trust_region_minimizer.cc:733] Step failed to evaluate. Treating it as a step with infinite cost
0.302905 -nan 0.201789
W0524 16:04:31.438374 18450 residual_block.cc:131] 

Error in evaluating the ResidualBlock.

There are two possible reasons. Either the CostFunction did not evaluate and fill all    
residual and jacobians that were requested or there was a non-finite value (nan/infinite)
generated during the or jacobian computation. 

Residual Block size: 1 parameter blocks x 1 residuals

For each parameter block, the value of the parameters are printed in the first column   
and the value of the jacobian under the corresponding residual. If a ParameterBlock was 
held constant then the corresponding jacobian is printed as 'Not Computed'. If an entry 
of the Jacobian/residual array was requested but was not written to by user code, it is 
indicated by 'Uninitialized'. This is an error. Residuals or Jacobian values evaluating 
to Inf or NaN is also an error.  

Residuals:             -nan 

Parameter Block 0, size: 3

    -1.83634 | Not Computed  
   0.0773546 | Not Computed  
    0.322183 | Not Computed  

W0524 16:04:31.438385 18450 trust_region_minimizer.cc:733] Step failed to evaluate. Treating it as a step with infinite cost
0.302905 0.317664 0.201789
0.302905 [0.317664 ; 0.13126, -0.835368, 0.807222] 0.201789
0.302905 0.21458 0.201789
0.302905 [0.21458 ; 0.200484, -1.31973, 1.23547] 0.201789
0.302905 0.202805 0.201789
0.302905 [0.202805 ; 0.213625, -1.41053, 1.3167] 0.201789
0.302905 0.201825 0.201789
0.302905 [0.201825 ; 0.214796, -1.41861, 1.32393] 0.201789
0.302905 0.201789 0.201789
0.302905 [0.201789 ; 0.21484, -1.41891, 1.3242] 0.201789
0.302905 0.201789 0.201789
0.302905 [0.201789 ; 0.21484, -1.41892, 1.32421] 0.201789
0.302905 0.201789 0.201789

**Comment by sandwichmaker** [comment]
I recommend printing out the value of base before you call pow on it to see what is going on.

**Comment by sandwichmaker** [comment]
Closing this issue as there is nothing actionable for us here. Please re-open if you have further questions.
