### ISSUE TITLE
libceres-dev on Ubuntu 20.04 Focal Fossa arm64 build is failing

### ISSUE THREAD

**Issue by emersonknapp** [ceres-solver/ceres-solver#599]
I'm trying to install libceres-dev on Ubuntu Focal, but it's not present in the apt archives because the build is failing, note here https://launchpad.net/ubuntu/+source/ceres-solver/1.14.0-4ubuntu1/+build/19091179 - it appears to be a single test failure 

```
99% tests passed, 1 tests failed out of 127

Total Test time (real) = 267.25 sec

The following tests FAILED:
	 30 - evaluation_callback_test (Failed)
```

**Comment by sandwichmaker** [comment]
This is fixed at head and in the upcoming ceres 2.0. This is a benign test failure from an overly strict test and can be ignored.

**Comment by emersonknapp** [comment]
Do the maintainers here own the launchpad Ubuntu packaging job? Maybe it just needs to be re-run? The package worked in Bionic and for now we just can't use it in Focal (on arm64) because there's been no successful build.

**Comment by emersonknapp** [comment]
Can we reopen this issue? We can't release 2.0 into Focal - which as LTS will exist for 5 years, we need to potentially backport the test fix patch to 1.14.x in order to support this platform.

**Comment by SteveMacenski** [comment]
@sandwichmaker when will 2.0 be available? Until that happens, there's no debian to install via apt on Focal which is a pretty bad state to be in for upstream projects.

**Comment by kyrofa** [comment]
Even if 2.0 becomes available it can't be SRU'd back to Ubuntu. @sandwichmaker can you point us at the patch required to make those tests pass?

**Comment by kyrofa** [comment]
Thank you @sandwichmaker. SRU is ongoing [here](https://bugs.launchpad.net/ubuntu/+source/ceres-solver/+bug/1882626).

**Comment by SteveMacenski** [comment]
Thanks Kyle for jumping in on this. Admittedly, the launch pad / ubuntu forums are a complete mystery to me. If you want to help fix some openVDB issues in 20.04 too, I won't complain :wink:

**Comment by kyrofa** [comment]
Alright, SRU has completed. ceres-solver should be available in all architectures on Ubuntu 20.04 now. Thanks for your help @sandwichmaker!

**Comment by SteveMacenski** [comment]
@kyrofa should we remove cartographer and slam toolbox from the blacklists?

**Comment by kyrofa** [comment]
@SteveMacenski yeah I say give it a try.
