### ISSUE TITLE
test ceres problem

### ISSUE THREAD

**Issue by onionysy** [ceres-solver/ceres-solver#601]
I want to test ceres by `bin/simple_bundle_adjuster ../ceres-solver-1.14.0/data/problem-16-22106-pre.txt`  command.However, the error arise `ERROR: unable to open file ../ceres-solver-1.14.0/data/problem-16-22106-pre.txt
*** Error in `bin/simple_bundle_adjuster': free(): invalid pointer: 0x0000000000845ab1 ***
` Can you help me about my problem. Below is the full command line when an error occurs.
`ysy@ubuntu:~/3rdparty/ceres-solver-1.14.0/build$ bin/simple_bundle_adjuster ../ceres-solver-1.14.0/data/problem-16-22106-pre.txt
ERROR: unable to open file ../ceres-solver-1.14.0/data/problem-16-22106-pre.txt
*** Error in `bin/simple_bundle_adjuster': free(): invalid pointer: 0x0000000000845ab1 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fd59863a7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fd59864337a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fd59864753c]
bin/simple_bundle_adjuster(_ZN10BALProblemD1Ev+0x12)[0x4531d2]
bin/simple_bundle_adjuster(main+0x220)[0x4529d0]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fd5985e3830]
bin/simple_bundle_adjuster(_start+0x29)[0x452ff9]
======= Memory map: ========
00400000-00642000 r-xp 00000000 08:01 1329122                            /home/ysy/3rdparty/ceres-solver-1.14.0/build/bin/simple_bundle_adjuster
00841000-00845000 r--p 00241000 08:01 1329122                            /home/ysy/3rdparty/ceres-solver-1.14.0/build/bin/simple_bundle_adjuster
00845000-00846000 rw-p 00245000 08:01 1329122                            /home/ysy/3rdparty/ceres-solver-1.14.0/build/bin/simple_bundle_adjuster
01eec000-01f0d000 rw-p 00000000 00:00 0                                  [heap]
7fd58c000000-7fd58c021000 rw-p 00000000 00:00 0 
7fd58c021000-7fd590000000 ---p 00000000 00:00 0 
7fd591b19000-7fd593b19000 rw-p 00000000 00:00 0 
7fd593b19000-7fd593b1a000 ---p 00000000 00:00 0 
7fd593b1a000-7fd59431a000 rw-p 00000000 00:00 0 
7fd59431a000-7fd594358000 r-xp 00000000 08:01 140960                     /usr/lib/x86_64-linux-gnu/libquadmath.so.0.0.0
7fd594358000-7fd594557000 ---p 0003e000 08:01 140960                     /usr/lib/x86_64-linux-gnu/libquadmath.so.0.0.0
7fd594557000-7fd594558000 r--p 0003d000 08:01 140960                     /usr/lib/x86_64-linux-gnu/libquadmath.so.0.0.0
7fd594558000-7fd594559000 rw-p 0003e000 08:01 140960                     /usr/lib/x86_64-linux-gnu/libquadmath.so.0.0.0
7fd594559000-7fd59457a000 r-xp 00000000 08:01 1050630                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7fd59457a000-7fd594779000 ---p 00021000 08:01 1050630                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7fd594779000-7fd59477a000 r--p 00020000 08:01 1050630                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7fd59477a000-7fd59477b000 rw-p 00021000 08:01 1050630                    /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7fd59477b000-7fd59477e000 r-xp 00000000 08:01 1050587                    /lib/x86_64-linux-gnu/libdl-2.23.so
7fd59477e000-7fd59497d000 ---p 00003000 08:01 1050587                    /lib/x86_64-linux-gnu/libdl-2.23.so
7fd59497d000-7fd59497e000 r--p 00002000 08:01 1050587                    /lib/x86_64-linux-gnu/libdl-2.23.so
7fd59497e000-7fd59497f000 rw-p 00003000 08:01 1050587                    /lib/x86_64-linux-gnu/libdl-2.23.so
7fd59497f000-7fd594d16000 r-xp 00000000 08:01 136304                     /usr/lib/atlas-base/libatlas.so.3.0
7fd594d16000-7fd594f16000 ---p 00397000 08:01 136304                     /usr/lib/atlas-base/libatlas.so.3.0
7fd594f16000-7fd594f1d000 rw-p 00397000 08:01 136304                     /usr/lib/atlas-base/libatlas.so.3.0
7fd594f1d000-7fd594f3e000 r-xp 00000000 08:01 136305                     /usr/lib/atlas-base/libcblas.so.3.0
7fd594f3e000-7fd59513e000 ---p 00021000 08:01 136305                     /usr/lib/atlas-base/libcblas.so.3.0
7fd59513e000-7fd59513f000 rw-p 00021000 08:01 136305                     /usr/lib/atlas-base/libcblas.so.3.0
7fd59513f000-7fd595268000 r-xp 00000000 08:01 139606                     /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
7fd595268000-7fd595467000 ---p 00129000 08:01 139606                     /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
7fd595467000-7fd595468000 r--p 00128000 08:01 139606                     /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
7fd595468000-7fd59546a000 rw-p 00129000 08:01 139606                     /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0
7fd59546a000-7fd5972ce000 r-xp 00000000 08:01 177148                     /usr/lib/libopenblasp-r0.2.18.so
7fd5972ce000-7fd5974cd000 ---p 01e64000 08:01 177148                     /usr/lib/libopenblasp-r0.2.18.so
7fd5974cd000-7fd5974d3000 r--p 01e63000 08:01 177148                     /usr/lib/libopenblasp-r0.2.18.so
7fd5974d3000-7fd5974e5000 rw-p 01e69000 08:01 177148                     /usr/lib/libopenblasp-r0.2.18.so
7fd5974e5000-7fd5974fe000 rw-p 00000000 00:00 0 
7fd5974fe000-7fd597500000 r-xp 00000000 08:01 142456                     /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so.4.4.6
7fd597500000-7fd5976ff000 ---p 00002000 08:01 142456                     /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so.4.4.6
7fd5976ff000-7fd597700000 r--p 00001000 08:01 142456                     /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so.4.4.6
7fd597700000-7fd597701000 rw-p 00002000 08:01 142456                     /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so.4.4.6
7fd597701000-7fd59770a000 r-xp 00000000 08:01 140043                     /usr/lib/x86_64-linux-gnu/libccolamd.so.2.9.1
7fd59770a000-7fd59790a000 ---p 00009000 08:01 140043                     /usr/lib/x86_64-linux-gnu/libccolamd.so.2.9.1
7fd59790a000-7fd59790b000 r--p 00009000 08:01 140043                     /usr/lib/x86_64-linux-gnu/libccolamd.so.2.9.1
7fd59790b000-7fd59790c000 rw-p 0000a000 08:01 140043                     /usr/lib/x86_64-linux-gnu/libccolamd.so.2.9.1
7fd59790c000-7fd597915000 r-xp 00000000 08:01 140042                     /usr/lib/x86_64-linux-gnu/libcamd.so.2.4.1
7fd597915000-7fd597b14000 ---p 00009000 08:01 140042                     /usr/lib/x86_64-linux-gnu/libcamd.so.2.4.1
7fd597b14000-7fd597b15000 r--p 00008000 08:01 140042                     /usr/lib/x86_64-linux-gnu/libcamd.so.2.4.1
7fd597b15000-7fd597b16000 rw-p 00009000 08:01 140042                     /usr/lib/x86_64-linux-gnu/libcamd.so.2.4.1
7fd597b16000-7fd597b1c000 r-xp 00000000 08:01 141507                     /usr/lib/x86_64-linux-gnu/libcolamd.so.2.9.1
7fd597b1c000-7fd597d1b000 ---p 00006000 08:01 141507                     /usr/lib/x86_64-linux-gnu/libcolamd.so.2.9.1
7fd597d1b000-7fd597d1c000 r--p 00005000 08:01 141507                     /usr/lib/x86_64-linux-gnu/libcolamd.so.2.9.1
7fd597d1c000-7fd597d1d000 rw-p 00006000 08:01 141507                     /usr/lib/x86_64-linux-gnu/libcolamd.so.2.9.1
7fd597d1d000-7fd597d25000 r-xp 00000000 08:01 133231                     /usr/lib/x86_64-linux-gnu/libamd.so.2.4.1
7fd597d25000-7fd597f24000 ---p 00008000 08:01 133231                     /usr/lib/x86_64-linux-gnu/libamd.so.2.4.1
7fd597f24000-7fd597f25000 r--p 00007000 08:01 133231                     /usr/lib/x86_64-linux-gnu/libamd.so.2.4.1
7fd597f25000-7fd597f26000 rw-p 00008000 08:01 133231                     /usr/lib/x86_64-linux-gnu/libamd.so.2.4.1
7fd597f26000-7fd597f81000 r-xp 00000000 08:01 177146                     /usr/lib/openblas-base/libblas.so.3
7fd597f81000-7fd598181000 ---p 0005b000 08:01 177146                     /usr/lib/openblas-base/libblas.so.3
7fd598181000-7fd598186000 r--p 0005b000 08:01 177146                     /usr/lib/openblas-base/libblas.so.3
7fd598186000-7fd598187000 rw-p 00060000 08:01 177146                     /usr/lib/openblas-base/libblas.so.3
7fd598187000-7fd598193000 r-xp 00000000 08:01 142551                     /usr/lib/x86_64-linux-gnu/libunwind.so.8.0.1
7fd598193000-7fd598392000 ---p 0000c000 08:01 142551                     /usr/lib/x86_64-linux-gnu/libunwind.so.8.0.1
7fd598392000-7fd598393000 r--p 0000b000 08:01 142551                     /usr/lib/x86_64-linux-gnu/libunwind.so.8.0.1
7fd598393000-7fd598394000 rw-p 0000c000 08:01 142551                     /usr/lib/x86_64-linux-gnu/libunwind.so.8.0.1
7fd598394000-7fd5983a2000 rw-p 00000000 00:00 0 
7fd5983a2000-7fd5983c2000 r-xp 00000000 08:01 175134                     /usr/lib/x86_64-linux-gnu/libgflags.so.2.1.2
7fd5983c2000-7fd5985c1000 ---p 00020000 08:01 175134                     /usr/lib/x86_64-linux-gnu/libgflags.so.2.1.2
7fd5985c1000-7fd5985c2000 r--p 0001f000 08:01 175134                     /usr/lib/x86_64-linux-gnu/libgflags.so.2.1.2
7fd5985c2000-7fd5985c3000 rw-p 00020000 08:01 175134                     /usr/lib/x86_64-linux-gnu/libgflags.so.2.1.2
7fd5985c3000-7fd598783000 r-xp 00000000 08:01 1050563                    /lib/x86_64-linux-gnu/libc-2.23.so
7fd598783000-7fd598983000 ---p 001c0000 08:01 1050563                    /lib/x86_64-linux-gnu/libc-2.23.so
7fd598983000-7fd598987000 r--p 001c0000 08:01 1050563                    /lib/x86_64-linux-gnu/libc-2.23.so
7fd598987000-7fd598989000 rw-p 001c4000 08:01 1050563                    /lib/x86_64-linux-gnu/libc-2.23.so
7fd598989000-7fd59898d000 rw-p 00000000 00:00 0 
7fd59898d000-7fd5989a3000 r-xp 00000000 08:01 1050601                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fd5989a3000-7fd598ba2000 ---p 00016000 08:01 1050601                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fd598ba2000-7fd598ba3000 rw-p 00015000 08:01 1050601                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fd598ba3000-7fd598cab000 r-xp 00000000 08:01 1050633                    /lib/x86_64-linux-gnu/libm-2.23.so
7fd598cab000-7fd598eaa000 ---p 00108000 08:01 1050633                    /lib/x86_64-linux-gnu/libm-2.23.so
7fd598eaa000-7fd598eab000 r--p 00107000 08:01 1050633                    /lib/x86_64-linux-gnu/libm-2.23.so
7fd598eab000-7fd598eac000 rw-p 00108000 08:01 1050633                    /lib/x86_64-linux-gnu/libm-2.23.so
7fd598eac000-7fd59901e000 r-xp 00000000 08:01 133492                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7fd59901e000-7fd59921e000 ---p 00172000 08:01 133492                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7fd59921e000-7fd599228000 r--p 00172000 08:01 133492                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7fd599228000-7fd59922a000 rw-p 0017c000 08:01 133492                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7fd59922a000-7fd59922e000 rw-p 00000000 00:00 0 
7fd59922e000-7fd59924f000 r-xp 00000000 08:01 140962                     /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fd59924f000-7fd59944e000 ---p 00021000 08:01 140962                     /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fd59944e000-7fd59944f000 r--p 00020000 08:01 140962                     /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fd59944f000-7fd599450000 rw-p 00021000 08:01 140962                     /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fd599450000-7fd599479000 r-xp 00000000 08:01 171483                     /usr/lib/x86_64-linux-gnu/libcxsparse.so.3.1.4
7fd599479000-7fd599678000 ---p 00029000 08:01 171483                     /usr/lib/x86_64-linux-gnu/libcxsparse.so.3.1.4
7fd599678000-7fd599679000 r--p 00028000 08:01 171483                     /usr/lib/x86_64-linux-gnu/libcxsparse.so.3.1.4
7fd599679000-7fd59967a000 rw-p 00029000 08:01 171483                     /usr/lib/x86_64-linux-gnu/libcxsparse.so.3.1.4
7fd59967a000-7fd59969a000 r-xp 00000000 08:01 136300                     /usr/lib/atlas-base/libf77blas.so.3.0
7fd59969a000-7fd599899000 ---p 00020000 08:01 136300                     /usr/lib/atlas-base/libf77blas.so.3.0
7fd599899000-7fd59989a000 rw-p 0001f000 08:01 136300                     /usr/lib/atlas-base/libf77blas.so.3.0
7fd59989a000-7fd599e7a000 r-xp 00000000 08:01 177147                     /usr/lib/openblas-base/liblapack.so.3
7fd599e7a000-7fd59a07a000 ---p 005e0000 08:01 177147                     /usr/lib/openblas-base/liblapack.so.3
7fd59a07a000-7fd59a07b000 r--p 005e0000 08:01 177147                     /usr/lib/openblas-base/liblapack.so.3
7fd59a07b000-7fd59a07d000 rw-p 005e1000 08:01 177147                     /usr/lib/openblas-base/liblapack.so.3
7fd59a07d000-7fd59a150000 r-xp 00000000 08:01 171481                     /usr/lib/x86_64-linux-gnu/libcholmod.so.3.0.6
7fd59a150000-7fd59a34f000 ---p 000d3000 08:01 171481                     /usr/lib/x86_64-linux-gnu/libcholmod.so.3.0.6
7fd59a34f000-7fd59a350000 r--p 000d2000 08:01 171481                     /usr/lib/x86_64-linux-gnu/libcholmod.so.3.0.6
7fd59a350000-7fd59a351000 rw-p 000d3000 08:01 171481                     /usr/lib/x86_64-linux-gnu/libcholmod.so.3.0.6
7fd59a351000-7fd59a369000 r-xp 00000000 08:01 1050709                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fd59a369000-7fd59a568000 ---p 00018000 08:01 1050709                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fd59a568000-7fd59a569000 r--p 00017000 08:01 1050709                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fd59a569000-7fd59a56a000 rw-p 00018000 08:01 1050709                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fd59a56a000-7fd59a56e000 rw-p 00000000 00:00 0 
7fd59a56e000-7fd59a58c000 r-xp 00000000 08:01 131843                     /usr/lib/x86_64-linux-gnu/libglog.so.0.0.0
7fd59a58c000-7fd59a78b000 ---p 0001e000 08:01 131843                     /usr/lib/x86_64-linux-gnu/libglog.so.0.0.0
7fd59a78b000-7fd59a78c000 r--p 0001d000 08:01 131843                     /usr/lib/x86_64-linux-gnu/libglog.so.0.0.0
7fd59a78c000-7fd59a78d000 rw-p 0001e000 08:01 131843                     /usr/lib/x86_64-linux-gnu/libglog.so.0.0.0
7fd59a78d000-7fd59a79d000 rw-p 00000000 00:00 0 
7fd59a79d000-7fd59a7c3000 r-xp 00000000 08:01 1050535                    /lib/x86_64-linux-gnu/ld-2.23.so
7fd59a967000-7fd59a975000 rw-p 00000000 00:00 0 
7fd59a9c0000-7fd59a9c2000 rw-p 00000000 00:00 0 
7fd59a9c2000-7fd59a9c3000 r--p 00025000 08:01 1050535                    /lib/x86_64-linux-gnu/ld-2.23.so
7fd59a9c3000-7fd59a9c4000 rw-p 00026000 08:01 1050535                    /lib/x86_64-linux-gnu/ld-2.23.so
7fd59a9c4000-7fd59a9c5000 rw-p 00000000 00:00 0 
7fff65eb3000-7fff65ed5000 rw-p 00000000 00:00 0                          [stack]
7fff65f9d000-7fff65fa0000 r--p 00000000 00:00 0                          [vvar]
7fff65fa0000-7fff65fa2000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
已放弃 (核心已转储)
`

**Comment by sandwichmaker** [comment]
Is the file actually present ? are you able to open the file yourself? This looks like a system issue on your side rather than a ceres error.
