### ISSUE TITLE
Expand the C API

### ISSUE THREAD

**Issue by ethanhs** [ceres-solver/ceres-solver#602]
Hi! I'd like to use Ceres from a Rust project, so I was hoping to use the C API, but I noticed that it is rather limited at this time. Would it be possible to expand it so one can set options for the problem?

**Comment by sandwichmaker** [comment]
Yes of course. Please send us a pull request based on the instructions on
ceres-solver.org.

**Comment by lucasw** [comment]
I've had success using calling a C++ function that runs ceres from a rust program through https://github.com/dtolnay/cxx.  The C++ `operator()` method can also call a rust function to get the residuals which works fine for numeric differentiation, but being able to use the Jet type in rust is going to be more difficult.  https://github.com/lucasw/rust_test/tree/cxx_ceres/ceres/ceres_cxx has a simple example.

**Comment by sandwichmaker** [comment]
Going to close this due to lack of follow up.
