### ISSUE TITLE
Using Eigen decompositions with ceres autodiff Jet data type

### ISSUE THREAD

**Issue by shirokobrod** [ceres-solver/ceres-solver#606]
I am using Eigen 3.3.7 release with ceres solver 1.14.0 with autodiff Jet data type 
and I have some problems. I need to solve linear least square subproblem 
within variable projection algorithm, namely I need to solve LLS equation
A(p)*x = b
Where matrix A(p) depends on nonlinear parameters p:
x(p) = pseudo-inverse(A(p))*b;
x(p) will be optimized in nonlinear least squares fitting, so I need Jcobian. 
Rhs b is measured vector of doubles, e.g. VectorXd. In order to use ceres's autodiff 
p must be of Jet type. Ceres provides corresponding traits for binary operations

#if EIGEN_VERSION_AT_LEAST(3, 3, 0)
// Specifying the return type of binary operations between Jets and scalar types
// allows you to perform matrix/array operations with Eigen matrices and arrays
// such as addition, subtraction, multiplication, and division where one Eigen
// matrix/array is of type Jet and the other is a scalar type. This improves
// performance by using the optimized scalar-to-Jet binary operations but
// is only available on Eigen versions >= 3.3
template <typename BinaryOp, typename T, int N>
struct ScalarBinaryOpTraits<ceres::Jet<T, N>, T, BinaryOp> {
  typedef ceres::Jet<T, N> ReturnType;
};
template <typename BinaryOp, typename T, int N>
struct ScalarBinaryOpTraits<T, ceres::Jet<T, N>, BinaryOp> {
  typedef ceres::Jet<T, N> ReturnType;
};
#endif  // EIGEN_VERSION_AT_LEAST(3, 3, 0)

There two problems.
1. Small problem. In an Eigen  function "RealScalar threshold() const" in SCDbase.h 
I have to replace 
"return m_usePrescribedThreshold ? m_prescribedThreshold
: diagSize* NumTraits<Scalar>::epsilon();" 
with 
"return m_usePrescribedThreshold ? m_prescribedThreshold
: Scalar(diagSize)* NumTraits<Scalar>::epsilon();"
This fix is similar Gael's fix of Bug 1403
____________________________________________________________________________
2. It is less trivial. I expect that x(p) = pseudo-inverse(A(p))*b; 
is vector of Jet. And it is actually true for e.g SVD decomposition
x(p) = VSU^T * b
where Jet traits for multiplication are in use. 
But if I use 
JcobySVD<Matrix<Jet<double, 2>, Dynamic, Dynamic>> svd(A);
x(p) = svd.solve(b),
I got an error message.
Here you are code for reproducing the error

// test_svd_jet.cpp
#include <ceres/jet.h>
using ceres::Jet;

int test_svd_jet()
{
    typedef Matrix<Jet<double, 2>, Dynamic, Dynamic> Mat;
    typedef Matrix<Jet<double, 2>, Dynamic, 1> Vec;
     Mat A = MatrixXd::Random(3, 2).cast <Jet<double, 2>>();
     VectorXd b = VectorXd::Random(3);
     JacobiSVD<Mat> svd(A, ComputeThinU | ComputeThinV);
     int l_rank = svd.rank();
     Vec c = svd.matrixV().leftCols(l_rank) 
         * svd.singularValues().head(l_rank).asDiagonal().inverse() 
         * svd.matrixU().leftCols(l_rank).adjoint() * b; // *
     Vec c1 = svd.solve(b.cast<Jet<double, 2>>()); // **
     Vec c2 = svd.solve(b); // ***
     return 0;
}
// End test_svd_jet.cpp

// * and // ** work fine an give the same results. // *** fails with VS 2019 error message
Eigen\src\Core\functors\AssignmentFunctors.h(24,1): 
error C2679: binary '=': no operator found which takes 
a right-hand operand of type 'const SrcScalar' (or there is no acceptable conversion)
The error points to line //***. 
I thing that solution is of type VectorXd instead of Vec and there is problem with assignment of double to Jet. 
Derivatives are lost either. It should work similar to complex type. 
If A is complex matrix and b is real vector, x must be complex. 
There is something wrong with Type deduction in SVD, QR or COD (complete orthogonal) decomposition in Eigen 3.3.7 library.
This is defect of Eigen decomposition module type reduction of result of solve method.  
If
 template <typename T> 
 Matrix<T, Dynamic, Dynamic>  A; and 
 ArraXd b;, 
 than x = A.solve(b) should be of type  <typename T> Matrix<T, Dynamic, 1.>. Result is right if decompostion is used.
____________________________________________________________________________________
3. Some notes.
    3.1 I added derivative of erf and erfc functions, which I use and which are part of C++11 standard, to Jet.h file. 
	3.2 Compileing ceres by VS 2019. I have to enclose in to pragmas
		#ifdef _MSC_VER
		#pragma optimize( "", off )
		#endif // _MSC_VER

		#ifdef _MSC_VER
		#pragma optimize( "", on )
		#endif // _MSC_VER

		class GOOGLE_GLOG_DLL_DECL CheckOpMessageBuilder and class GOOGLE_GLOG_DLL_DECL LogMessageVoidify in glog::logging.h 
		without this VS compiler in release mode optimizes out some member functions. It results linker error message "uresolved external".

**Comment by NikolausDemmel** [comment]
> Rhs b is measured vector of doubles, e.g. VectorXd. In order to use ceres's autodiff
p must be of Jet type. Ceres provides corresponding traits for binary operations

It won't give you the maximum possible performance, but have you tried casting `b` to Jet type? I.e. `b.cast<T>()`?

**Comment by shirokobrod** [comment]
Yes, I tried it. It works, but it degrades performance.

**Comment by sandwichmaker** [comment]
Closing because its not clear what is actionable here. This looks like an Eigen issue, if there is actionable things to be done on the ceres/jet side please reopen this issue.
