### ISSUE TITLE
Implement customized LossFunction

### ISSUE THREAD

**Issue by gogojjh** [ceres-solver/ceres-solver#610]
Thanks for your great work. 
I find that ceres support several loss functions in this link: http://ceres-solver.org/nnls_modeling.html?highlight=huber#_CPPv2N5ceres9HuberLossE
But could you please give some hints that how can I implement the customized loss function? Like implementing the **Geman-McClure** or **TLS**?

**Comment by sandwichmaker** [comment]
You can define your own subclass of LossFunction and use it in your problem.
