### ISSUE TITLE
Compilation failed with visual 2019

### ISSUE THREAD

**Issue by nosleduc** [ceres-solver/ceres-solver#611]
I'm trying to compile ceres (1.14 released version) with visual studio 2019 and it failed. If I'm using  the platform toolset v140, it succeeds. All my dependencies use v142

I'm using Visual Studio 2019 16.6.3 and latest version of Windows 10.
I'm building ceres without openmp. I'm building it with suitesparse, CXX11, CX11_Threads
The first error I get is
internal\ceres\thread_pool.h(92,27): error C2039: 'function' is not a member of 'std'

**Comment by sandwichmaker** [comment]
Perhaps there is a missing header in one of the files?

**Comment by sandwichmaker** [comment]
Closing because lack of follow up. Please feel free to repopen if there is something actionable.
