### ISSUE TITLE
Linker error when using CERES_EXPORT on class with variadic template on MSVC

### ISSUE THREAD

**Issue by kwaegel** [ceres-solver/ceres-solver#618]
Trying to use ProductParameterization on Windows with Ceres 2.0.0-rc1 currently produces the a LNK2109 linker error with Visual Studio 2019 (version 16.7.2)

```
error LNK2019: unresolved external symbol "__declspec(dllimport) const ceres::ProductParameterization::`vftable'" (__imp_??_7ProductParameterization@ceres@@6B@) referenced in function "public: __cdecl ceres::ProductParameterization::ProductParameterization<class ceres::EigenQuaternionParameterization,class ceres::IdentityParameterization>(class ceres::EigenQuaternionParameterization *,class ceres::IdentityParameterization *)" (??$?0VEigenQuaternionParameterization@ceres@@VIdentityParameterization@1@@ProductParameterization@ceres@@QEAA@PEAVEigenQuaternionParameterization@1@PEAVIdentityParameterization@1@@Z)
```

It appears this is caused by using `CERES_EXPORT` on the entire class, which causes the compiler to try finding an exported symbol for the template. I'm still unclear why the compiler can't handle this case (no success searching the MSVC docs yet), but it might be trying to find a template specialization.

To fix the error, I removed the annotation from the class declaration:
```
class CERES_EXPORT ProductParameterization : public LocalParameterization {
...
```

and added `CERES_EXPORT` annotations only on the non-template functions:

```
class ProductParameterization : public LocalParameterization {
 public:
  ProductParameterization(const ProductParameterization&) = delete;
  ProductParameterization& operator=(const ProductParameterization&) = delete;

  template <typename... LocalParams>
  ProductParameterization(LocalParams*... local_params)
      : local_params_(sizeof...(LocalParams)),
        local_size_{0},
        global_size_{0},
        buffer_size_{0} {
  ...
  }

  CERES_EXPORT bool Plus(const double* x,
                         const double* delta,
                         double* x_plus_delta) const override;
  CERES_EXPORT bool ComputeJacobian(const double* x, double* jacobian) const override;
  CERES_EXPORT int GlobalSize() const override { return global_size_; }
  CERES_EXPORT int LocalSize() const override { return local_size_; }
...
};
```

An alternate solution might be to define [WINDOWS_EXPORT_ALL_SYMBOLS](https://cmake.org/cmake/help/v3.5/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html) for the entire CMake project, and export all symbols (similar to GCC's `-fvisibility=default`). I've had success with this on other projects, but it exposes more symbols than necessary, and is a significantly larger change.

**Comment by sandwichmaker** [comment]
@alexsmac this seems to be related to the other patch you are looking at which also deals with symbols export.

**Comment by alexsmac** [comment]
@nocnokneo's CL [here](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/16580) is distinct, in that the purpose there is to prevent the export of all symbols everywhere.  However, I'm not wild about further propagation of the hateful MSVC-specific `CERES_EXPORT` macros within the public classes, but I'm also surprised that @nocnokneo didn't encounter this issue, Taylor can you shed any light on this ?

**Comment by sandwichmaker** [comment]
gentle ping? I'd like to resolve this before the next RC.

**Comment by nocnokneo** [comment]
I included a fix for this in https://ceres-solver-review.googlesource.com/c/ceres-solver/+/16580 by adding a virtual destructor for `LocalParameterization`

**Comment by sandwichmaker** [comment]
This should be fixed at head now. I am closing it, please let us know if this is still a problem.
