### ISSUE TITLE
error: no match for call to ‘(const ExponentialResidual) (const double* const&, double*&)’

### ISSUE THREAD

**Issue by thisisjaskaran** [ceres-solver/ceres-solver#620]
I get the following error while compiling my code. Stuck here for 2 days now...

Any help appreciated!

![Screenshot from 2020-08-31 04-31-06](https://user-images.githubusercontent.com/52422984/91671265-e7599c80-eb42-11ea-8626-656ad18f42d4.png)

**Comment by sandwichmaker** [comment]
Looks like your signature for AutoDiffCostFunction and the signature of operator() do not match.

**Comment by thisisjaskaran** [comment]
Could you please clarify what you mean by signature?

**Comment by alexsmac** [comment]
Your functor expects 10 arguments, 9 input parameter blocks and 1 output residual block, Ceres is trying to call it with 2 arguments (1 input parameter block, and 1 output residual block).  This means that you have not correctly instantiated AutoDiffCostFunction for your functor.  As explained [here](http://ceres-solver.org/nnls_modeling.html#_CPPv2N5ceres20AutoDiffCostFunctionE), the template signature needs to specify the dimensionality of each parameter block you are passing (unless you were using [DynamicAutoDiffCostFunction](http://ceres-solver.org/nnls_modeling.html#_CPPv2N5ceres27DynamicAutoDiffCostFunctionE), which you do not appear to need to do).  You are only specifying the size of the first parameter block which is inconsistent with the signature of your functor which has another 8 parameter blocks - their sizes also need to be specified in the template signature of AutoDiffCostFunction when you instantiate it.
