### ISSUE TITLE
clang-format mismatch

### ISSUE THREAD

**Issue by NikolausDemmel** [ceres-solver/ceres-solver#621]
I noticed that many source files don't adhere to the style specified in the `.clang-format` file. This is a bit irritating if your editor is set to run clang-format upon file save when a `.clang-format` file is present.

Most files have only small changes after running clang-format (notable exception are the examples, which differ substantially after running formatting). So maybe it is also to do with the clang-format version (mine is `10.0.1`) or and outdated config file?

Would you be inclined to address this? Maybe 2.0 would be a good time. I guess it can be mostly applied automatically, but some parts might need manual attention to tweak the formatting config or to add some `clang-format off/on`.

**Comment by sandwichmaker** [comment]
Yes some of the files predate clang-format. I will happily take changes.
May have to exclude some sections, especially in tests but otherwise feel
free to send em. I think the public facing headers are all clang formatted
though.

**Comment by NikolausDemmel** [comment]
This is the diff I get when I run clang format (version 10.0.1) on the public headers:

```
find include/ \( -name "*.h" -or -name "*.cc" \) -exec clang-format -i --verbose {} \;
```

https://github.com/NikolausDemmel/ceres-solver/commit/8b112a94acc0a1cfa76bec7024f3cf23e6ba167c

Could you have a look if this is what you want before I look into it more?

**Comment by NikolausDemmel** [comment]
(PS: I mean in general. Single specific changes we can review later on Gerrit)

**Comment by sandwichmaker** [comment]
The ordering of port.h I think is sensitive (or it used to be anyways, this is worth checking).
same for disable and re-enable warnings
in types.h the enums are better off one per line.
The rest seem fine.

**Comment by NikolausDemmel** [comment]
https://ceres-solver-review.googlesource.com/c/ceres-solver/+/17800

**Comment by NikolausDemmel** [comment]
@sandwichmaker, just letting you know that after the fix for public includes and examples, I have the same thing for the internal sources in the pipeline. It's just that there are a lot of little changes and I need to go through them file by file to check where to retain formatting with `clang-format off/on`. You can expect a CL on gerrit shortly.

**Comment by sandwichmaker** [comment]
fantastic, happy to review as one big CL or in pieces as you see fit!

**Comment by NikolausDemmel** [comment]
Fixed on master.
