### ISSUE TITLE
Clarifying safety of removing parameter blocks

### ISSUE THREAD

**Issue by mawallace** [ceres-solver/ceres-solver#622]
The [documentation](http://ceres-solver.org/nnls_modeling.html?highlight=remove#_CPPv2N5ceres7Problem19RemoveResidualBlockE15ResidualBlockId) for `RemoveResidualBlock` has a warning about the Jacobians and residuals from the solver becoming uninterpretable (see below).

> WARNING: Removing a residual or parameter block will destroy the implicit ordering, rendering the jacobian or residuals returned from the solver uninterpretable. If you depend on the evaluated jacobian, do not use remove! This may change in a future release. Hold the indicated parameter block constant during optimization.

Just to clarify, it is safe to remove them from a *problem*, right?

The flow that I'm trying to achieve is as follows:
1. Create a problem
2. Add some parameters and residuals
3. Create a solver and solve the problem
4. Add/*remove* some parameters/residuals to or from the *original* problem
5. Create a *new* solver and solve the problem

(Steps 4 and 5 may be repeated many times.)

Could someone please confirm that this is safe (given that I'm using a new solver each time)?

Thank you!

**Comment by sandwichmaker** [comment]
Yes this is safe. You do not need to create a new solver.

**Comment by mawallace** [comment]
Thank you!

Also, just realized this might have made more sense as a question in the Google group -- I'll do that next time.

Thanks again.
