### ISSUE TITLE
Setting parameters constant

### ISSUE THREAD

**Issue by rebellojason7** [ceres-solver/ceres-solver#623]
Hi all,

I'm trying to run a multi threaded visual inertial algorithm and had a question with regard to setting parameters constant (SetParameterBlockConstant). In particular does the solution change if I add some parameter blocks to the optimization and set them constant versus not adding the parameters at all to the optimization. 

The reason I ask if because I ran the first version where I didn't have the extra parameters and got a lower error compared to when I added some new parameters and set them constant. I have tested the extra parameters separately and therefore am fairly confident there aren't any bugs in the code.

Any help or thoughts would be appreciated. Thanks !

**Comment by sandwichmaker** [comment]
There should be no difference. Because constant parameter blocks are internally eliminated from the problem.

**Comment by rebellojason7** [comment]
Thanks

**Comment by IgorIlyin95** [comment]
@sandwichmaker  And how about the performance it this case? Will solving theses 2 problems take the same time?

**Comment by sandwichmaker** [comment]
Some minor cost in the preprocessor but not much else.
