### ISSUE TITLE
Handling degeneracies 

### ISSUE THREAD

**Issue by rebellojason7** [ceres-solver/ceres-solver#624]
Hi all,

Does anyone know how Ceres handles degeneracies ? Where some columns of the jacobians of the parameter blocks are related to each other ? I realize that with the LM optimizer one can add to the diagonal elements, but does Ceres pick up on the rank deficiency in the jacobian if one exists ? Any help would be appreciated. @sandwichmaker Thanks.

**Comment by sandwichmaker** [comment]
LM requires a diagonal which makes sure that the hessian is full rank. But I am not what you are looking for here. Also this is better discussed on the mailinglist.
