### ISSUE TITLE
Build.make:62: recipe for target 'examples/CMakeFiles/nist.dir/nist.cc.o' failed

### ISSUE THREAD

**Issue by CeccAnd** [ceres-solver/ceres-solver#627]
Hello

I am trying to MAKE Ceres-solver on UBUNTU 18.04. But always I got following feedback.

[100%] Built target bundle_adjuster
^Cexamples/CMakeFiles/nist.dir/build.make:62: recipe for target 'examples/CMakeFiles/nist.dir/nist.cc.o' failed
make[2]: *** [examples/CMakeFiles/nist.dir/nist.cc.o] Interrupt
CMakeFiles/Makefile2:7628: recipe for target 'examples/CMakeFiles/nist.dir/all' failed
make[1]: *** [examples/CMakeFiles/nist.dir/all] Interrupt
Makefile:140: recipe for target 'all' failed
make: *** [all] Interrupt

How to solve?

Thanks.

**Comment by alexsmac** [comment]
This:

```
^Cexamples/...
```

specifically *^C* means you used `<control> + <c>` to interrupt the compilation before it was complete, that's why the compilation of the translation unit shows has failed / Interrupt.
