### ISSUE TITLE
How to disable the log, please?

### ISSUE THREAD

**Issue by zhangkom** [ceres-solver/ceres-solver#634]
I want to disable the log of Ceres, but it failed. And my source code is following:
        ceres::Solver::Options options;
        options.linear_solver_type = ceres::DENSE_QR;
        options.minimizer_progress_to_stdout = false;
        options.logging_type = ceres::SILENT;
        ceres::Solver::Summary summary;
        ceres::Solve(options, &problem, &summary);

**The result is:**
DenseQRSolver::Solve
                                   Delta   Cumulative
                           Setup :    0.00000      0.00000
                           Solve :    0.00010      0.00011
                        TearDown :    0.00000      0.00011
                           Total :    0.00000      0.00011

**Comment by sandwichmaker** [comment]
Can you confirm that you are using miniglog? please use google-glog for full control. Otherwise you have to set a compiler flag to disable logging from miniglog (which I do not remember offhand).

**Comment by sandwichmaker** [comment]
Closing because of lack of response. Feel free to re-open if you have new info.

**Comment by CanCanZeng** [comment]
Hi @sandwichmaker and @zhangkom I'm also facing this problem, I'm sure that I do not use miniglog. And my code is like below:
```
google::InitGoogleLogging(argv[0]);
google::LogToStderr();
FLAGS_v = 2;
......

ceres::Solver::Options options;
options.minimizer_progress_to_stdout = false;
options.logging_type = ceres::SILENT;
ceres::Solver::Summary summary;
ceres::Solve(options, &problem, &summary);
```
there are still some log from ceres,
```
I0329 17:07:40.909061 14780 block_sparse_matrix.cc:81] Allocating values array with 569520 bytes.
I0329 17:07:40.909070 14780 detect_structure.cc:95] Dynamic f block size because the block size changed from 9 to 6
I0329 17:07:40.909072 14780 detect_structure.cc:63] Dynamic row block size because the block size changed from 15 to 2
I0329 17:07:40.909075 14780 detect_structure.cc:75] Dynamic e block size because the block size changed from 9 to 1
I0329 17:07:40.909076 14780 detect_structure.cc:113] Schur complement static structure <-1,-1,-1>.
I0329 17:07:40.911449 14780 detect_structure.cc:95] Dynamic f block size because the block size changed from 9 to 6
I0329 17:07:40.911454 14780 detect_structure.cc:63] Dynamic row block size because the block size changed from 15 to 2
I0329 17:07:40.911456 14780 detect_structure.cc:75] Dynamic e block size because the block size changed from 9 to 1
I0329 17:07:40.911458 14780 detect_structure.cc:113] Schur complement static structure <-1,-1,-1>.
I0329 17:07:40.911460 14780 schur_eliminator.cc:148] Template specializations not found for <-1,-1,-1>
```
so I find that there are some VLOG  code https://github.com/ceres-solver/ceres-solver/blob/facb199f3eda902360f9e1d5271372b7e54febe1/internal/ceres/detect_structure.cc#L113 that does not consider options.logging_type, is there any method to disable these log?

**Comment by sandwichmaker** [comment]
Why are you setting v=2, this will cause vlog(2)messages to be printed.

**Comment by sandwichmaker** [comment]
Yes you can use the vmodule flag to selectively enable vlog level per file.
