### ISSUE TITLE
Ceres Usage Problem

### ISSUE THREAD

**Issue by ShifanZhu** [ceres-solver/ceres-solver#635]
I'd like to compute the minimum result of the below first equation. But it seems that Ceres can only solve the minimum result of the second equation.

Is there anything I didn't understand? I would appreciate it if you can help me out. Thanks!
 
![WeChat Image_20201113204636](https://user-images.githubusercontent.com/55651391/99073701-5fd3e380-25f1-11eb-9d8c-0dd206c42786.png)
![2](https://user-images.githubusercontent.com/55651391/99073708-619da700-25f1-11eb-95c0-a8f213d6c3de.png)

**Comment by sandwichmaker** [comment]
@ShifanZhu Ceres can handle nonlinear problems just fine. Have you read the tutorial?
