### ISSUE TITLE
  Unknown threading model specified: 'CXX_THREADS'.

### ISSUE THREAD

**Issue by cristinaluna** [ceres-solver/ceres-solver#636]
Hello there,

I am trying to install ceres_solver using `catkin_make_isolated --install --use-ninja`

But I get this error

``` Cmake
-- Found SuiteSparse 4.4.6, building with SuiteSparse.
-- Found CXSparse version: 3.1.4, building with CXSparse.
-- Building without Apple's Accelerate sparse support.
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
-- Found Google Flags header in: /usr/include, in namespace: google
-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
CMake Error at cmake/CeresThreadingModels.cmake:77 (message):
  Unknown threading model specified: 'CXX_THREADS'.  Available threading
  models for this platform are: [CXX11_THREADS, OPENMP, NO_THREADS]
Call Stack (most recent call first):
  CMakeLists.txt:462 (set_ceres_threading_model)


-- Configuring incomplete, errors occurred!
See also "/root/REPO/catkin_ws/build_isolated/ceres-solver/install/CMakeFiles/CMakeOutput.log".
See also "/root/REPO/catkin_ws/build_isolated/ceres-solver/install/CMakeFiles/CMakeError.log".
<== Failed to process package 'ceres-solver': 
  Command '['/root/REPO/catkin_ws/install_isolated/env.sh', 'cmake', '/root/REPO/catkin_ws/src/ceres-solver', '-DCMAKE_INSTALL_PREFIX=/root/REPO/catkin_ws/install_isolated', '-G', 'Ninja']' returned non-zero exit status 1

Reproduce this error by running:
==> cd /root/REPO/catkin_ws/build_isolated/ceres-solver && /root/REPO/catkin_ws/install_isolated/env.sh cmake /root/REPO/catkin_ws/src/ceres-solver -DCMAKE_INSTALL_PREFIX=/root/REPO/catkin_ws/install_isolated -G Ninja

```

Do you know how can I solve it?

Thanks in advance

**Comment by sandwichmaker** [comment]
This looks like a version mismatch somewhere. What version of Ceres Solver are you trying to use?

**Comment by cristinaluna** [comment]
> This looks like a version mismatch somewhere. What version of Ceres Solver are you trying to use?

As said in [this comment](https://github.com/ceres-solver/ceres-solver/issues/541#issuecomment-662823031), I have done a hard reset after I found that Eigen3 issue. Now I'm facing this thread problem but I haven't found the solution

**Comment by sandwichmaker** [comment]
@cristinaluna these seem like two completely different problems. What version of ceres solver are you using?

**Comment by cristinaluna** [comment]
> @cristinaluna these seem like two completely different problems. What version of ceres solver are you using?

As I said earlier, I am using [this version](https://github.com/ceres-solver/ceres-solver/tree/e51e9b46f6ca88ab8b2266d0e362771db6d98067),  1.14

**Comment by sandwichmaker** [comment]
Back in 1.14 ceres used to accept CXX11_THREADS as the threading model. This changed in 

https://github.com/ceres-solver/ceres-solver/commit/7ef83e07592ead74eeacc227b642df1959d2a246

I suspect that the catkin file is passing CXX_THREADS as the threading model, why it is doing that I do not know (I know nothing about catkin).

**Comment by cristinaluna** [comment]
> Back in 1.14 ceres used to accept CXX11_THREADS as the threading model. This changed in
> 
> [7ef83e0](https://github.com/ceres-solver/ceres-solver/commit/7ef83e07592ead74eeacc227b642df1959d2a246)
> 
> I suspect that the catkin file is passing CXX_THREADS as the threading model, why it is doing that I do not know (I know nothing about catkin).

I don't know either. I'm quite new with ceres. Maybe I should install cpp14

**Comment by sandwichmaker** [comment]
ping?

**Comment by willem0** [comment]
@cristinaluna , I had the same issue while trying to get ceres installed for the sake of colmap, running Ubuntu 16.04. (Eigen3 not found by cmake.) and after doing a hard reset to e51e9b46f6 as suggested on that thread, started hitting this threading issue.

I was able to resolve this by rolling back to 1.4.0. It seems this threading refactor was made while transitioning to v2.0 in commit d656d34.
