### ISSUE TITLE
Full report should not start with newline

### ISSUE THREAD

**Issue by shaperilio** [ceres-solver/ceres-solver#639]
https://github.com/ceres-solver/ceres-solver/blob/66b4c33e817ec34d64c7513950e74a3382e06662/internal/ceres/solver.cc#L627

I'd think it would be best to let the user decide what spacing they want around a full report.

**Comment by sandwichmaker** [comment]
Sure, but this has been like this for many years now, I do not see a particularly strong reason to change it now.
