### ISSUE TITLE
issue about dynamic size of parameter when constructing cost function

### ISSUE THREAD

**Issue by weisongwen** [ceres-solver/ceres-solver#640]
Hi @sandwichmaker ,  thanks for sharing such a great package. I am using the ceres-solver to solve the sensor fusion of robot positioning. Since the size of the parameters that I am going to estimate is dynamic (e.g the size of the parameters to be estimated is 3 in some epochs, but the size of the parameters to be estimated is 10 in some epochs). However, when I construct the cost functions using the AutoDiffCostFunction, the size of the parameters should be given as constant (e.g. the cost function for [curve fitting](https://ceres-solver.googlesource.com/ceres-solver/+/master/examples/robust_curve_fitting.cc#148), the size of the parameter is 1). If I use some code like follows, the ceres-solver will get wrong...
```
new AutoDiffCostFunction<ExponentialResidual, 1, 1, 1>(
new ExponentialResidual(data[2 * i], data[2 * i + 1]));
```

Do you have any ideas taht how can I make the size change dynamically? 

Thanks a lot in advance,

**Comment by sandwichmaker** [comment]
If you do not know the parameter block size at compile time then you can
use DynamicAutoDiffCostFunction.

**Comment by weisongwen** [comment]
Hi @sandwichmaker , many thanks! I will try it then,

Best,
Weisong,
