### ISSUE TITLE
A question about the example "simple_bundle_adjuster.cc"

### ISSUE THREAD

**Issue by DYFeng** [ceres-solver/ceres-solver#642]
In the BAL dataset

> The camera is parameterized using 9 parameters: 3 for rotation, 3 for translation, 1 for focal length and 2 for radial distortion.

We should just optimize the first 6 parameters, instead of all 9 parameters.

https://github.com/ceres-solver/ceres-solver/blob/66b4c33e817ec34d64c7513950e74a3382e06662/examples/simple_bundle_adjuster.cc#L167

**Comment by sandwichmaker** [comment]
why?
