### ISSUE TITLE
Solver for Covariance Matrix

### ISSUE THREAD

**Issue by yinghuasha** [ceres-solver/ceres-solver#643]
I am a student studying to use Ceres. It is a great tool that helps me a lot. I recently use ceres for solving a standard Bundle Adjustment problem. I only need to calculate camera intrinsic parameters and distortion parameters covariance matrix, which only has 8 parameters interested. I pass the parameter blocks to the solver, which is pasted below. However, when the solver calculates the Jacobian Matrix, it takes all the parameters, including the 3D points and other paramters like camera orientations and positions, into account, which is far more larger than the parameters number I passed to the solver.  

ceres::Covariance covariance(options);
std::vector<std::pair<const double*, const double*>> covariance_blocks;
covariance_blocks.push_back(
std::make_pair(camera_parameters, camera_parameters));

    Then I tried to trace the original code, as pasted below. I found a interesting problem that bugs me.

vector<double*>& active_parameter_blocks =
      evaluate_options_.parameter_blocks;
active_parameter_blocks.clear();

    The code in is covariance_impl.cc file, from line 427 to line 429. I found that the evaluate_options_ is set to private and cannot access from outside. Even if I want to manually set the evaluate_options_.parameters_blocks, the line 429 code will clear it afterall, I wonder why you design the code like this. 

    That's all for my problems about the covariance matrix calculation. I am really appraciated with your help if you can answer my questions!

**Comment by sandwichmaker** [comment]
It is an internal struct by design. Why do you want to control the parameter blocks during evaluation? restricting them will give you a restricted Jacobian which is not a great idea.

**Comment by yinghuasha** [comment]
> It is an internal struct by design. Why do you want to control the parameter blocks during evaluation? restricting them will give you a restricted Jacobian which is not a great idea.

When the parameter size is huge, the calculation effeciency is really low. And I am not sure if the accuracy can be guaranteed to be good enough ? I use the restricted Jacobian and calculate the covariance matrix manually by 

C = (J^T* J)^(-1)

However the result from the above equation differs from the result using the covariance solver a lot, like in the magnitude of 10^9. I am not sure whether my approach is wrong or the solver that takes all the parameters into account has an accumulated error or something. 

The code blocks which calculate Jacobian is 

**_ceres::Problem::EvaluateOptions evalOpt;
evalOpt.parameter_blocks = camera_parameters;
evalOpt.num_threads = 8;
evalOpt.apply_loss_function = true;
ceres::CRSMatrix calib_jacobian;
problem_->Evaluate(evalOpt, &cost, NULL, NULL, &calib_jacobian);_**

The code blocks which calculate Covariance is 

_**EigenSparseMatrix sparse_jacobian =
   Eigen::MappedSparseMatrix<double, Eigen::RowMajor>(
			calib_jacobian.num_rows, calib_jacobian.num_cols,
   static_cast<int>(calib_jacobian.values.size()),
			calib_jacobian.rows.data(), calib_jacobian.cols.data(),
			calib_jacobian.values.data());
Eigen::MatrixXd WTW =  (sparse_jacobian.transpose()*sparse_jacobian);
Eigen::MatrixXd WTW_Inv=WTW.inverse();**_

**Comment by sandwichmaker** [comment]
Your approach is wrong. Here is why.

Suppose your full Jacobian is 
```
J= [A B]
```

then the Gauss-Newton Hessian is 

```
J'J = [A'][A B] = [A'A A'B]
         [B']            [B'A B'B]
```      

and the covariance will be 
```
C = (J'J)^{-1}
```

Now say you are interested in the covariance of the parameters in the first A columns, then that is given by the inverse of the matrix

```
S = [A'A - A'B (B'B)^{-1} B'A]^{-1}
```

but if you only evaluate part of the Jacobian matrix say A, and try and compute the covariance that way you will just get 

```
S = [A'A]^{-1}
```

in effect you will not be accounting for the correlation with the parmeters in the B part of your Jacobian.

**Comment by yinghuasha** [comment]
Thanks a lot for your detailed description about the partial covariance matrix compution.  I realize that my approach is totally wrong.
