### ISSUE TITLE
Leverage value for each residual block

### ISSUE THREAD

**Issue by MohamedAfifii** [ceres-solver/ceres-solver#650]
Hello,

I was trying to give weights to the residuals according to the formula used by LOAM (https://link.springer.com/content/pdf/10.1007/s10514-016-9548-2.pdf) in equation (11):
![loam2](https://user-images.githubusercontent.com/35625268/103169628-21635280-4846-11eb-8764-aa4523b8c7ea.png)

What is the right way to retrieve the value of <img src="https://render.githubusercontent.com/render/math?math=$J(J^TJ)^{-1}J^T$"> in Ceres Solver? Is it possible to use this weighting scheme inside the internal iterations of the optimizer? Or I can only assign those weights before starting the optimization process and cannot update them for each iteration?

**Comment by sandwichmaker** [comment]
@MohamedAfifii there is no (easy) way to access these values in a generic manner in ceres.

**Comment by MohamedAfifii** [comment]
@sandwichmaker can I do some modifications to the source code to make this possible? Which files should I modify then?

**Comment by sandwichmaker** [comment]
You can try hacking program_evaluator.h
