### ISSUE TITLE
ceres-solver 1.14.0 evaluation_callback_test failed.

### ISSUE THREAD

**Issue by arm7star** [ceres-solver/ceres-solver#651]
[ RUN      ] EvaluationCallback.WithLineSearchMinimizerWolfeLbfgsQuadratic
/opt/spack-stage/root/spack-stage-ceres-solver-1.14.0-gnmb2uxxvuzw46ebjcaasx2zvaiopobc/spack-src/internal/ceres/evaluation_callback_test.cc:91: Failure
Expected: (evaluate_last_parameter_hash) != (incoming_parameter_hash), actual: 1152674340896131432 vs 1152674340896131432
/opt/spack-stage/root/spack-stage-ceres-solver-1.14.0-gnmb2uxxvuzw46ebjcaasx2zvaiopobc/spack-src/internal/ceres/evaluation_callback_test.cc:92: Failure
Expected: (prepare_parameter_hash) != (incoming_parameter_hash), actual: 1152674340896131432 vs 1152674340896131432
/opt/spack-stage/root/spack-stage-ceres-solver-1.14.0-gnmb2uxxvuzw46ebjcaasx2zvaiopobc/spack-src/internal/ceres/evaluation_callback_test.cc:147: Failure
Expected: (evaluate_last_parameter_hash) != (incoming_parameter_hash), actual: 1152674340896131432 vs 1152674340896131432
[  FAILED  ] EvaluationCallback.WithLineSearchMinimizerWolfeLbfgsQuadratic (5 ms)

When I tested the ceres-solver 1.14.0 on ARM64 linux, the evaluation_callback_test failed. Is there some commit to fix it for  ceres-solver 1.14.0? Thank you!

**Comment by sandwichmaker** [comment]
This is a benign failure which has been fixed upstream in ceres 2.0.0
please upgrade to that.
Sameer

**Comment by arm7star** [comment]
ceres 2.0.0 has been checked ok. But small_blas_test tested faild. It perhaps there has some deviation on float operation on our ARM64 cpu. Thank you!

The difference between (c_assign_ref - c_assign).norm() and 0.0 is 6.7532230144642595e-16, which exceeds kTolerance, where
(c_assign_ref - c_assign).norm() evaluates to 6.7532230144642595e-16,
0.0 evaluates to 0, and
kTolerance evaluates to 6.6613381477509392e-16.
