### ISSUE TITLE
LINK : warning LNK4217

### ISSUE THREAD

**Issue by LiuPeiqi-CNHN** [ceres-solver/ceres-solver#653]
I have a single line cpp file "#include <ceres\ceres.h>", then 9 LNK4217 warning appear after compiling the project. I don't use any ceres funtion, I just only include ceres.h header file.

IDE:vs2019
ceres:install by vcpkg, x64-windows

`1>LINK : warning LNK4217: 符号“?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QEAAXH_N@Z (public: void __cdecl std::basic_ios<char,struct std::char_traits<char> >::setstate(int,bool))”(在“ opencv_calib3d451.lib(chessboard.obj)”中定义)已由“QtImageProcessing1.obj”(函数“"class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::operator<<<struct std::char_traits<char> >(class std::basic_ostream<char,struct std::char_traits<char> > &,char const *)" (??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z)”中)导入

1>LINK : warning LNK4217: 符号“?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAXXZ (public: void __cdecl std::basic_ostream<char,struct std::char_traits<char> >::_Osfx(void))”(在“ Algorithm.obj”中定义)已由“QtImageProcessing1.obj”(函数“"class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::operator<<<struct std::char_traits<char> >(class std::basic_ostream<char,struct std::char_traits<char> > &,char const *)" (??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z)”中)导入

1>LINK : warning LNK4217: 符号“??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@_N@Z (public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::operator<<(bool))”(在“ Algorithm.obj”中定义)已由“QtImageProcessing1.obj”(函数“"public: virtual void __cdecl cvflann::anyimpl::small_any_policy<bool>::print(class std::basic_ostream<char,struct std::char_traits<char> > &,void * const *)" (?print@?$small_any_policy@_N@anyimpl@cvflann@@UEAAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@PEBQEAX@Z)”中)导入

1>LINK : warning LNK4217: 符号“??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@H@Z (public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::operator<<(int))”(在“ Algorithm.obj”中定义)已由“QtImageProcessing1.obj”(函数“"public: virtual void __cdecl cvflann::anyimpl::small_any_policy<int>::print(class std::basic_ostream<char,struct std::char_traits<char> > &,void * const *)" (?print@?$small_any_policy@H@anyimpl@cvflann@@UEAAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@PEBQEAX@Z)”中)导入

1>LINK : warning LNK4217: 符号“??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@M@Z (public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::operator<<(float))”(在“ Algorithm.obj”中定义)已由“QtImageProcessing1.obj”(函数“"public: virtual void __cdecl cvflann::anyimpl::small_any_policy<float>::print(class std::basic_ostream<char,struct std::char_traits<char> > &,void * const *)" (?print@?$small_any_policy@M@anyimpl@cvflann@@UEAAXAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@PEBQEAX@Z)”中)导入

1>LINK : warning LNK4217: 符号“?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV12@XZ (public: class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::basic_ostream<char,struct std::char_traits<char> >::flush(void))”(在“ Algorithm.obj”中定义)已由“QtImageProcessing1.obj”(函数“"class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::operator<<<struct std::char_traits<char> >(class std::basic_ostream<char,struct std::char_traits<char> > &,char const *)" (??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z)”中)导入

1>LINK : warning LNK4217: 符号“?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHD@Z (public: int __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputc(char))”(在“ opencv_videoio451.lib(videoio_registry.obj)”中定义)已由“QtImageProcessing1.obj”(函数“"class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::operator<<<struct std::char_traits<char> >(class std::basic_ostream<char,struct std::char_traits<char> > &,char const *)" (??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z)”中)导入

1>LINK : warning LNK4217: 符号“?sputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAA_JPEBD_J@Z (public: __int64 __cdecl std::basic_streambuf<char,struct std::char_traits<char> >::sputn(char const *,__int64))”(在“ opencv_videoio451.lib(videoio_registry.obj)”中定义)已由“QtImageProcessing1.obj”(函数“"class std::basic_ostream<char,struct std::char_traits<char> > & __cdecl std::operator<<<struct std::char_traits<char> >(class std::basic_ostream<char,struct std::char_traits<char> > &,char const *)" (??$?6U?$char_traits@D@std@@@std@@YAAEAV?$basic_ostream@DU?$char_traits@D@std@@@0@AEAV10@PEBD@Z)”中)导入
`

**Comment by alexsmac** [comment]
None of the above warnings relate to Ceres, they relate to OpenCV and Qt, the docs for [LNK4217](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-warning-lnk4217?view=msvc-160) suggest that the issue is that one of those projects is erroneously using dllimport
