### ISSUE TITLE
ceres::acos giving back NaN

### ISSUE THREAD

**Issue by psalvaggio** [ceres-solver/ceres-solver#655]
I think this is a straightforward issue. I have the following code in my cost function:
```c++
vza = acos(cos_v);
```
when running, I get the following result:
```
vza[0 ; nan, nan, nan, nan, nan], cos_v = [1 ; -0, -0, -0, -0, -0]
```
this makes sense given the implementation of `acos` for `ceres::Jet`, as `tmp` will have a divide by 0:
```c++
template <typename T, int N>
inline Jet<T, N> acos(const Jet<T, N>& f) {
  const T tmp = -T(1.0) / sqrt(T(1.0) - f.a * f.a);
  return Jet<T, N>(acos(f.a), tmp * f.v);
}
```

**Comment by alexsmac** [comment]
As `acos(x)` is only defined for `|x| <= 1`, and as the magnitude of its derivative tends to infinity as `x -> +/- 1`, what are you proposing that the Jet should return instead?  The implementation correctly implements the algebraic form of the derivative, and the correct result is indeed not representable, and no subsequent operations using it will produce anything sensible, a returned value of NaN correctly represents this

**Comment by psalvaggio** [comment]
Right, the derivative of `acos(x)` goes to infinity at +/- 1, however, in this specific case, the input is just a constant 1, so it winds up being one of those `0 / 0` situations. In this case, I think `[0; 0, 0, 0, 0, 0]` would be the logical output of the function. I wound up just writing a wrapper that checks for this specific case, which makes my optimization work and this value is very unlikely to appear once this value starts getting changed due to the optimization.

**Comment by alexsmac** [comment]
Not really, if you erroneously return a derivative of zero you are implying a valid minima has been reached and the solver should terminate if this were the only term (which depending upon the conditions, it might).  That is not an accurate representation of the structure of the problem at that point

**Comment by sandwichmaker** [comment]
0 as the output when the actual quantity being computed is 0/0 is not a reasonable option.
