### ISSUE TITLE
Different memory footprint on pc and arm

### ISSUE THREAD

**Issue by ZhaoFireFireFire** [ceres-solver/ceres-solver#658]
Hi, great contributors.

I'm facing the problem of memory footprint on pose graph optimization problem. That's, I build and solve the non-linear optimization problem with 800 parameter blocks and around 600 residual blocks. But I saw the memory footprint is 20m on pc, and  its memory footprint is 100m on arm. What causes this to happen?

I'm on Ubuntu 16.04 with cmake version 3.5.1 and gcc version 5.4.0.

**Comment by sandwichmaker** [comment]
I haven't a clue. Are you using the same linear algebra libraries and the same linear solver in both cases? that would be the only difference that I can think of.

**Comment by ZhaoFireFireFire** [comment]
> I haven't a clue. Are you using the same linear algebra libraries and the same linear solver in both cases? that would be the only difference that I can think of.

Yeah, it's the same linear algebra libraries and the same linear solver. I try using the ceres-solver 2.0.1 and the memory usage is same on arm and on pc. It's puzzling.

**Comment by sandwichmaker** [comment]
so is this issue resolved with ceres 2.0?

**Comment by sandwichmaker** [comment]
Closing because of lack of response.
