### ISSUE TITLE
Compilng with non-standard Ceres location

### ISSUE THREAD

**Issue by alexandervakhitov** [ceres-solver/ceres-solver#659]
Hi!
I use ceres with ubuntu. Thank you for the library, use it for many years and find it very convenient.
Current issue: due to an important reason, I have ceres 1.14 installed in the default location in /usr/local. Now I wish to build COLMAP (https://colmap.github.io/). I install ceres into a custom location, and then I try to make colmap to use it. Tried two different ways without success:
1) using -DCMAKE_INSTALL_PREFIX
2) using -DEXPORT_BUILD_DIR
Ended up with specifying manually the library and include paths in the COLMAP's CMakeLists.txt. I believe it should not be done this way. What is your opinion on the matter?
Thank you.

**Comment by sandwichmaker** [comment]
@alexsmac ?

**Comment by NikolausDemmel** [comment]
Maybe have a look at cmake's documentation for `find_package`: https://cmake.org/cmake/help/v3.20/command/find_package.html#search-procedure (or select the version of cmake that you are using, as this has evolved over time). This is how Colmap finds Ceres.

I think what should work is either the `<PackageName>_ROOT` or `<PackageName>_DIR` variables, i.e. `Ceres_ROOT` and `Ceres_DIR`. This needs to be specified during the cmake call of Colmap.

**Comment by sandwichmaker** [comment]
Closing because lack of discussion for almost a year.
