### ISSUE TITLE
Question about floor'(x) == 0

### ISSUE THREAD

**Issue by BrannonKing** [ceres-solver/ceres-solver#663]
I recognize that the ceil/floor functions are flat, and that a zero derivative is technically correct. However, if you zoom out and look at the big picture, and consider the question of "which way should I go to make floor(x) smaller?", then having the derivative of floor(x) be x is not so unreasonable. x divided by its possible range is also a potential. Alternatively we could use a rotated cosine or stacked sigmoids to approximate the stair-step function. Have these other alternatives been considered or tested anywhere? 

This seems especially important if my step size is greater than 0.5. Are we able to query the step size (aka, learning rate) in the jet functions?

**Comment by sandwichmaker** [comment]
Brannon jets are not based on step size. it uses exact derivatives. That said, if you want to use a smooth approximation to floor/ceil you are free to use one.
