### ISSUE TITLE
Unable to run solver in parallel

### ISSUE THREAD

**Issue by dabosch** [ceres-solver/ceres-solver#665]
Hi all,

I newly discovered ceres solver and am trying to solve a rather huge problem on a high performance computer with 64 cores (pothentially I could use SMT too). While the function I want to minimize runs quite efficient on all cores (using openMP) I am unable to get the solver running multithreaded. I can see that most of the time is spent utilizing only one CPU core.

Even for a small example dataset ("only" 1600 parameters and 100 residuals) the time spent on 1 cpu only is significant (ca 90%). With more residuals and parameters this becomes worse. I'm aiming for 8k-20k parameters and 10k residuals, so using my cpu more efficiently is important for me.
I assume that this is **not** a bug in ceres-solver, but that I'm rather doing something wrong. So any advice on how to run this more efficiently is appreciated.
I tried this with ceres in the ubuntu sources as well as with self-compiled ceres. 

I would greatly appreciate any help with this.

I'm calling ceres like so:
<details>
<summary>
C++ code calling ceres
</summary>

``` C++
n = 1600;
p = 1600;
// Build the problem.
Problem problem;
// Set up the cost function
DynamicAutoDiffCostFunction<MyCostFunctor> *cost_function =
    new DynamicAutoDiffCostFunction<MyCostFunctor>(new MyCostFunctor(&mdata));
cost_function->AddParameterBlock(p);
cost_function->SetNumResiduals(n);
problem.AddResidualBlock(cost_function, NULL, b1v);

// Run the solver!
Solver::Options options;
options.minimizer_progress_to_stdout = true;
options.num_threads = 64;
omp_set_nested(1);
options.max_num_iterations = 15; /* for reasonable test times */
Solver::Summary summary;
Solve(options, &problem, &summary);
std::cout << summary.FullReport() << "\n";
```
</details>

As can be seen from the report, the linear solver takes the majority of the time:

<details>
<summary>
std::cout << summary.FullReport()
</summary>

```
Solver Summary (v 2.0.0-eigen-(3.3.7)-lapack-suitesparse-(5.7.1)-cxsparse-(3.2.0)-eigensparse-no_openmp)

                                     Original                  Reduced
Parameter blocks                            1                        1
Parameters                               1600                     1600
Residual blocks                             1                        1
Residuals                                 100                      100

Minimizer                        TRUST_REGION

Sparse linear algebra library    SUITE_SPARSE
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver          SPARSE_NORMAL_CHOLESKY   SPARSE_NORMAL_CHOLESKY
Threads                                    64                       64
Linear solver ordering              AUTOMATIC                        1

Cost:
Initial                          7.405975e-01
Final                            5.562523e-05
Change                           7.405418e-01

Minimizer iterations                       16
Successful steps                           10
Unsuccessful steps                          6

Time (in seconds):
Preprocessor                         0.017098

  Residual only evaluation           0.652027 (15)
  Jacobian & residual evaluation     4.266560 (10)
  Linear solver                     56.273994 (15)
Minimizer                           61.228495

Postprocessor                        0.000020
Total                               61.245614

Termination:                   NO_CONVERGENCE (Maximum number of iterations reached. Number of iterations: 15.)
```

</details>

This is how I build ceres:
<details>

```BASH
   # install ceres
   apt-get install -y git
   git clone https://ceres-solver.googlesource.com/ceres-solver
   cd ceres-solver
   git checkout 2.0.0
   # install dependencies
   apt-get install -y cmake
   apt-get install -y libgoogle-glog-dev libgflags-dev
   apt-get install -y libatlas-base-dev
   apt-get install -y libeigen3-dev
   apt-get install -y libsuitesparse-dev
   mkdir ceres-bin
   cd ceres-bin
   cmake -DBUILD_SHARED_LIBS=ON CERES_THREADING_MODEL=CXX_THREADS ../
   make -j12
   make install
```
note: building with openmp instead of CXX_THREADS didn't make any difference for me.
</details>

Some background info for those interested:
I'm trying to optimize the shape of electromagnetic pulse for a magnetic resonance experiment. During the time course of the pulse, the magnetization (3D vector) in each pixel is altered subject to varying magnetic fields, the pulse, distance to transmit antenna, etc. I have a target magnetization that I want to reach in all pixels at the end of the pulse, the residual for each pixel is described as `target - sqrt(mx^2+my^2)`
In pseudocode my function can be described as:

<details>

```
/*
param: parameters (np=1600)
res: residuals (nr=100) (1 residual per pixel)
dat: external data from file (np*nr)
mx,my,mz: 3-dim vector that is modified in my_function.

I iterate through all pixels (
*/
#pragma omp parallel for
for (r=0;r<nr;r++){
    for (p=0;p<np;p++){
        my_function (param(p),dat(p,r),&mx[r],&my[r],&mz[r]);
    }
    res[r] =sqrt( my**2+mz**2);
}

```
</details>

**Comment by NikolausDemmel** [comment]
Ceres should parallelize residual and jacobian evaluation very well. Probably you will see that runtime in the report increase a lot, if you set the number of threads for ceres to use to 1.

The biggest (remaining) runtime is spent on the linear solver, which doesn't really have good parallelization. The sparse linear algebra libraries that ceres uses don't have multithreading implemented, and for the iterative CG solver it is not that easy to get good parallelization out of a general solver like ceres, it seems. See a discussion and attempts to parallelize CG better here: https://groups.google.com/g/ceres-solver/c/-AC_9wsYrW0/m/KfPRo5JSBAAJ

**Comment by amy-tabb** [comment]
To get ceres to run with more than one thread enabled, you have to set it up such that OpenMP is enabled (which you mentioned) and also set the number of threads variable to be > 1. (The default value is 1, *even if you have OpenMP enabled*. It took me a long time to find this.)

Class reference, 

[Solver::Options::num_threads](http://ceres-solver.org/nnls_solving.html?highlight=openmp#_CPPv4N5ceres6Solver7Options11num_threadsE)

Example:

```C++
        Solver::Options options;
	options.linear_solver_type = ceres::DENSE_SCHUR;

	options.minimizer_progress_to_stdout = output_to_terminal;
	options.num_threads = omp_get_max_threads();
       ....
```
This snippet is extracted from some working, parallelized code, [here](https://github.com/amy-tabb/calico/blob/6c4fca1e55e00696067b4af4af0531bde1063af9/src/solving_structure.cpp#L488).

**Comment by alexsmac** [comment]
OpenMP is not required to use threads in recent versions of Ceres, and from
2.0 the default is actually to use C++11 threads which are more portable,
although OpenMP is still available if you want to use it.

Which threading model is used is configurable at build time via the
CERES_THREADING_MODEL variable.

-A

**Comment by sandwichmaker** [comment]
Closing because of lack of response.
