### ISSUE TITLE
levenberg_marquardt_strategy_test build issue on MSVC 2019 with miniglog

### ISSUE THREAD

**Issue by yiping** [ceres-solver/ceres-solver#668]
https://github.com/ceres-solver/ceres-solver/blob/542613c13d8b7469822aff5eec076f2cad4507ec/internal/ceres/levenberg_marquardt_strategy_test.cc#L156

If I build `levenberg_marquardt_strategy_test` in MSVC 2019 and use **miniglog**, the test fails to build with the following error

error C2065: 'GLOG_WARNING': undeclared identifier

If I change `'GLOG_WARNING` to `google::WARNING` on line 156, the test can build and runs without an issue.

**Comment by sandwichmaker** [comment]
@sergiud is this something you can look into?

**Comment by sergiud** [comment]
I was able to reproduce the problem. I'll update my current CL that fixes MSVC issues.

**Comment by sandwichmaker** [comment]
Thank you!
