### ISSUE TITLE
cmake script is not compatible with TBB 2021.1

### ISSUE THREAD

**Issue by bayandin** [ceres-solver/ceres-solver#669]
When I try to build `ceres-solver` with tbb [2021.1.1](https://github.com/oneapi-src/oneTBB/releases/tag/v2021.1.1) it fails an with error:
```
CMake Error at cmake/FindTBB.cmake:434 (file):
  file STRINGS file "/usr/local/include/tbb/tbb_stddef.h" cannot be read.
Call Stack (most recent call first):
  cmake/FindSuiteSparse.cmake:309 (find_package)
  CMakeLists.txt:282 (find_package)
```

It turns out, that file [`tbb/tbb_stddef.h`](https://github.com/oneapi-src/oneTBB/blob/v2020.3/include/tbb/tbb_stddef.h) was removed from tbb 2021.1, and now there's [`oneapi/tbb/version.h`](https://github.com/oneapi-src/oneTBB/blob/v2021.1.1/include/oneapi/tbb/version.h) with similar content though.

If I replace `tbb/tbb_stddef.h` with `oneapi/tbb/version.h` in `cmake/FindTBB.cmake` it builds without any error.

**Comment by alexsmac** [comment]
Thanks for the report, this should be fixed by [this CL](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/18500) that should be merged shortly

**Comment by bayandin** [comment]
Thanks!

**Comment by pzxdd** [comment]
Great job！

**Comment by zaidtahirbutt** [comment]
> When I try to build `ceres-solver` with tbb [2021.1.1](https://github.com/oneapi-src/oneTBB/releases/tag/v2021.1.1) it fails an with error:
> 
> ```
> CMake Error at cmake/FindTBB.cmake:434 (file):
>   file STRINGS file "/usr/local/include/tbb/tbb_stddef.h" cannot be read.
> Call Stack (most recent call first):
>   cmake/FindSuiteSparse.cmake:309 (find_package)
>   CMakeLists.txt:282 (find_package)
> ```
> 
> It turns out, that file [`tbb/tbb_stddef.h`](https://github.com/oneapi-src/oneTBB/blob/v2020.3/include/tbb/tbb_stddef.h) was removed from tbb 2021.1, and now there's [`oneapi/tbb/version.h`](https://github.com/oneapi-src/oneTBB/blob/v2021.1.1/include/oneapi/tbb/version.h) with similar content though.
> 
> If I replace `tbb/tbb_stddef.h` with `oneapi/tbb/version.h` in `cmake/FindTBB.cmake` it builds without any error.

Hi thanks, this solution solved the problem.

**Comment by tulingcheng86** [comment]
> When I try to build `ceres-solver` with tbb [2021.1.1](https://github.com/oneapi-src/oneTBB/releases/tag/v2021.1.1) it fails an with error:
> 
> ```
> CMake Error at cmake/FindTBB.cmake:434 (file):
>   file STRINGS file "/usr/local/include/tbb/tbb_stddef.h" cannot be read.
> Call Stack (most recent call first):
>   cmake/FindSuiteSparse.cmake:309 (find_package)
>   CMakeLists.txt:282 (find_package)
> ```
> 
> It turns out, that file [`tbb/tbb_stddef.h`](https://github.com/oneapi-src/oneTBB/blob/v2020.3/include/tbb/tbb_stddef.h) was removed from tbb 2021.1, and now there's [`oneapi/tbb/version.h`](https://github.com/oneapi-src/oneTBB/blob/v2021.1.1/include/oneapi/tbb/version.h) with similar content though.
> 
> If I replace `tbb/tbb_stddef.h` with `oneapi/tbb/version.h` in `cmake/FindTBB.cmake` it builds without any error.

thinks!
