### ISSUE TITLE
Does Ceres provide interface to user-defined linear least square problem solvers in, e.g., LM method?

### ISSUE THREAD

**Issue by AdrianTianyi** [ceres-solver/ceres-solver#670]
Hi all,

I want to use Ceres to solve a BA related problem. Though the solvers Ceres provides are excellent, I wonder if Ceres has provided an interface so that when I am using LM method, in each step, it can solve the linear least square problem with my solver?

Thanks a lot!

**Comment by alexsmac** [comment]
The linear solver is not part of the public API of Ceres, so doing this will require that you modify Ceres itself.  However, the API is defined by the internal class: [LinearSolver](https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/linear_solver.h#L104).  Provided that you implemented that API, and updated the [relevant factory method](https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/linear_solver.h#L291) used by the rest of Ceres then what you want to do should be possible.

**Comment by AdrianTianyi** [comment]
> The linear solver is not part of the public API of Ceres, so doing this will require that you modify Ceres itself. However, the API is defined by the internal class: [LinearSolver](https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/linear_solver.h#L104). Provided that you implemented that API, and updated the [relevant factory method](https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/linear_solver.h#L291) used by the rest of Ceres then what you want to do should be possible.

Thanks for your ideas! I will try this method.
