### ISSUE TITLE
Why does ceres allow cost function sharing?

### ISSUE THREAD

**Issue by whuaegeanse** [ceres-solver/ceres-solver#671]
Why does ceres allow sharing of cost function? Is it necessary? If two identical cost functions are allowed, does ceres work properly? Because, at this time, the error equations corresponding to the two cost functions are linearly related.
[code](https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/problem_impl.h#L209)

**Comment by alexsmac** [comment]
A residual block is formed from the combination of: {CostFunction, LossFunction, ParameterBlocks}, it is not true that if the same CostFunction instance is reused in multiple ResidualBlocks that the resulting costs (or the weighted residuals) are necessarily linearly related.

The LossFunction can be different, although more importantly the ParameterBlocks used to evaluate the CostFunction can be different.  If a CostFunction is solely a function of the input parameters passed to Evaluate, and therefore presumably has no internal state - or at least none that is specific to each residual block - then the same CostFunction instance can be reused with different parameter blocks equivalently to creating a new instance for each.  It's not a particularly common use-case (as any residual block that represents an observation error doesn't fit this model), but Ceres does support it.
