### ISSUE TITLE
Update comment for angleAxisRotatePoint in rotation.h

### ISSUE THREAD

**Issue by yiping** [ceres-solver/ceres-solver#672]
https://github.com/ceres-solver/ceres-solver/blob/66b4c33e817ec34d64c7513950e74a3382e06662/include/ceres/rotation.h#L626-L650

On line 627, `angle w` --> `angle theta`
On line 633, `hat(w)` --> `hat(angle_axis)`
On line 636, `w x pt` --> `angle_axis x pt`

The actual implementation is correct, just need to update the comment section.

**Comment by sandwichmaker** [comment]
Thanks @yiping, I will take a look, fix and credit you with the fix.
