### ISSUE TITLE
ceres-script is a python script to build ceres solver, simple and easy to use, especially on Windows platform

### ISSUE THREAD

**Issue by whuaegeanse** [ceres-solver/ceres-solver#677]
Building ceres solver on Windows platform is a very troublesome task, because it relies on third-party libraries such as glog, gflag, eigen, lapack, blas, suitesparse and so on. It may take several hours to download and configure these third-party libraries. The foundation of this project comes from the build script of colmap, which greatly reduces the difficulty of building on Windows platform. On the basis of the colmap build script, this project adds support for local glog, gflag, eigen, suitesparse and other third-party libraries. In other words, users can specify a local third-party library instead of a fixed version downloaded from the Internet. This will help the third-party library that ceres solver relies on to be consistent with the third-party library used locally by user.

The link is as follows:
[ceres-script](https://github.com/whuaegeanse/ceres-script)

**Comment by melhashash** [comment]
Thanks for sharing. For Windows, the easiest way I found is to use vcpkg.

**Comment by whuaegeanse** [comment]
@melhashash Thanks you for quick reply.
I just tried to build ceres with vcpkg, it is really very convenient. ceres-script provides another option, especially suitable for ceres solver developers and users on windows. Because the user can easily specify the version of ceres solver, whether it is the stable version or the master version. Of course, the version of the third-party libraries that ceres solver relies on can also be easily specified.
