### ISSUE TITLE
Building ceres with custom Eigen path + compatibility with Eigen 3.3.9

### ISSUE THREAD

**Issue by changh95** [ceres-solver/ceres-solver#678]
Hi,

I'm currently **trying to build Ceres with my pre-built Eigen library v3.3.9**. I also have Eigen v3.3.7 built in the /usr/, but my goal is to build Ceres with the Eigen v3.3.9 for a specific project. But I keep on getting the message `Found required Ceres dependency: Eigen version 3.3.7 in /usr/include/eigen3` when building my project with the Ceres which I tried to build with v3.3.9. 

**What am I doing wrong?** Below is the cmake comands I used to configure the build, and I confirm that Eigen 3.3.9 is actually in the path.

```
cmake ../ceres-solver-2.0.0 -DEXPORT_BUILD_DIR=ON -DCMAKE_INSTALL_PREFIX=../install -DEIGEN_INCLUDE_DIR_HINTS=../../Eigen/install/include -DEIGEN_LIBRARY_DIR_HINTS=../../Eigen/install/lib"
```

Also, on the side note, I noticed that ceres prefers to use Eigen v3.3.7 inside the CeresConfig.cmake. Does that mean I cannot use Eigen v3.3.9 with ceres?

Many thanks in advance.

**Comment by alexsmac** [comment]
What version of Ceres are you trying to use?  Assuming that it is either the latest 2.0.0 release (or master), then [as per the latest docs for specifying external dependencies](http://ceres-solver.org/installation.html#options-controlling-ceres-dependency-locations) you should be specifying `Eigen3_DIR`, *not* the legacy `EIGEN_<XXX>_DIR_HINTS` variables.  You should set `Eigen3_DIR` to the path to the directory containing the `Eigen3Config.cmake` configuration file that you want to use.  If you have installed Eigen to a non-standard location, then that is going to be: `<INSTALL_ROOT>/share/eigen3/cmake` if you have built Eigen locally and configured it to export its build directory to CMake, then you should set it equal to the Eigen build directory.  Either way, the directory must contain an  `Eigen3Config.cmake` file.

Ceres encodes the Eigen version with which it was built in its `CeresConfig.cmake` file to avoid one-definition-rule (ODR) violations which would occur if a client tried to link against Ceres and a different version of Eigen to the one Ceres was built with.  You can compile Ceres against Eigen 3.3.9, but you cannot compile Ceres against one version and then use it in code that links against a different Eigen version.

**Comment by changh95** [comment]
It worked, thank you! :)

**Comment by benghalensis** [comment]
The following worked for me:
`<build_folder>=path/eigen-3.3.7/build`
`cmake .. -DCMAKE_PREFIX_PATH=<build_folder>`
