### ISSUE TITLE
Using the cumulated probability function in BOOST for the Jet auto-differentiation

### ISSUE THREAD

**Issue by weisongwen** [ceres-solver/ceres-solver#679]
Thanks again for sharing such as good package for non-linear optimization. Currently, I wish to fit a curve with [Exponentially modified Gaussian distribution](https://en.wikipedia.org/wiki/Exponentially_modified_Gaussian_distribution) using the Ceres-solver. To achieve this, I wish to use the auto-differentiation function with Jet data format. However, the function [erfc()](https://en.wikipedia.org/wiki/Error_function#Complementary_error_function) is needed for calculating the cost function of the curve fitting. I use the implementation of the erfc() in the [boost library](https://www.boost.org/doc/libs/1_36_0/libs/math/doc/sf_and_dist/html/math_toolkit/dist/stat_tut/overview.html). Therefore, the state (parameters of the curve fitting to be estimated) with Jet type will be involved in the function of the boost library. This can cause an error as the Jet type is not applicable in the Boost library. The ```state[0]``` is the state that I wish to optimize. 
```c++
boost::math::normal s;
double pc =  0 * boost::math::pdf(s, state[0]);
```

Any suggestions to achieve this? :-)

Many thanks,
Weisong Wen,

**Comment by sandwichmaker** [comment]
why do you need to use the boost implementation of erfc ? just use the erfc in ceres ? since c++ already supports std::erfc.

**Comment by weisongwen** [comment]
Hi @sandwichmaker  Thanks for your suggestions! I did this but I got similar errors
```
error: no matching function for call to ‘erfc(ceres::Jet<double, 5>)’
```
As the Jet type is not applicable in the  std::erfc function. Meanwhile, I look into the jet.h file and I found that the erfc is not defined in the ceres::. Do you have any suggestions? :-)

Many thanks,
Weisong Wen,

**Comment by sandwichmaker** [comment]
What version of ceres are you using?

**Comment by weisongwen** [comment]
Hi @sandwichmaker  My ceres-solver version is as follows:
```
<package format="2">
<name>ceres-solver</name>
<version>1.14.0</version>
<description>A large scale non-linear optimization library.</description>
<maintainer email="ceres-solver@googlegroups.com"> The Ceres Solver Authors </maintainer>
<license>New BSD</license>
<url type="website">http://ceres-solver.org/</url>
<buildtool_depend>cmake</buildtool_depend>
<depend>atlas</depend>
<depend>eigen</depend>
<depend>gfortran</depend>
<depend>libgflags-dev</depend>
<depend>libgoogle-glog-dev</depend>
<depend>suitesparse</depend>
<export>
<build_type>cmake</build_type>
</export>
</package>
```

**Comment by sandwichmaker** [comment]
That's an ancient version of ceres.
Please use ceres 2.0

**Comment by weisongwen** [comment]
@sandwichmaker  Thanks, I will do this accordingly :-)
