### ISSUE TITLE
jacobians turn into nullptr after iteration once and segmentation fault happened

### ISSUE THREAD

**Issue by HP-Yin** [ceres-solver/ceres-solver#680]
Hi, I'm dealing with a weird problem when trying to optimize a problem, after  `ceres::Solve` ,segmentation fault happened after after iteration once, but no additional errors reported. After checking the `Evaluate` function and print the address of ` double **jacobians`, I found that the pointer turn into `nullptr`,
How to solve the problem.
Thanks.
![ceres error](https://user-images.githubusercontent.com/45333019/120445283-09769880-c3bb-11eb-8840-07a94fccb946.png)

**Comment by alexsmac** [comment]
This is expected, as per the documentation for CostFunction::Evaluate
<http://ceres-solver.org/nnls_modeling.html#_CPPv4N5ceres12CostFunction8EvaluateEPPCKdPdPPd>,
if jacobians or jacobians[i] are nullptr it means that Ceres does not
require them at that iteration and they do not need to be calculated.

**Comment by HP-Yin** [comment]
```
if(jacobians!=nullptr){
......
}
```
is used when calculating jacobians and peoblem solved, Thanks!
