### ISSUE TITLE
aparently can't set max_num_consecutive_invalid_steps

### ISSUE THREAD

**Issue by MrMabulous** [ceres-solver/ceres-solver#681]
I keep getting the following commandline output while solving problems:

`trust_region_minimizer.cc:97 Terminating: Number of consecutive invalid steps more than Solver::Options::max_num_consecutive_invalid_steps: 5`

Explicitly setting max_num_consecutive_invalid_steps higher doesn't change that, the messages still say that it was 5. That's how I setup the solver:

```
        ceres::Solver::Options options;
        options.linear_solver_type = ceres::SPARSE_NORMAL_CHOLESKY;
        options.sparse_linear_algebra_library_type = ceres::EIGEN_SPARSE;
        options.num_threads = 1;
        options.logging_type = ceres::LoggingType::SILENT;
        options.use_inner_iterations = true;  // default false
        options.use_nonmonotonic_steps = true;  // default false
        options.max_num_iterations = 300;  // default 50
        options.max_num_consecutive_invalid_steps = 30;  // default 5
        options.max_consecutive_nonmonotonic_steps = 20;  //default 5
        options.trust_region_strategy_type = ceres::DOGLEG;
        options.dogleg_type = ceres::SUBSPACE_DOGLEG;
        ceres::Solver::Summary summary;
        ceres::Solve(options, &problem, &summary);
```

it looks like the Solver::Options::max_num_consecutive_invalid_steps somehow doesn't get propperly propagated to the Minimizer::Options::max_num_consecutive_invalid_steps of the TrustRegionMinimizer.

Using ceres 2.0.0 with Eigen 3.3.8

Am I missing something?

**Comment by sandwichmaker** [comment]
Could you share the execution log and the output of Summary::FullReport please? Because I just tried injecting an error and it worked correctly.

**Comment by sandwichmaker** [comment]
gentle ping?

**Comment by sandwichmaker** [comment]
Closing because lack of response.
