### ISSUE TITLE
Windows build ceres using /MT but can not bulid helloworld sample, getting conflict between glog.lib with libcpmt.lib

### ISSUE THREAD

**Issue by Learningm** [ceres-solver/ceres-solver#683]
Hi, I download gflags and glogs the latest tag version (2.2.2 and 0.5.0) and ceres (1.13.0), and use Visual Studio 2015 to build ceres lib.

The project was setting /MD in default, due to the dependency of my other project was built in /MT, I need to build ceres in /MT mode.

![image](https://user-images.githubusercontent.com/13192241/122545838-e4438480-d060-11eb-9fc9-9767673f6625.png)

Also, the gflags library and glogs library were built in /MT mode.

Thought I am able to build ceres.lib, gflags.lib and glog.lib , I can not build any ceres sample and I am getting the conflict symbol error between glog.lib and libcpmt.lib, as following:

![image](https://user-images.githubusercontent.com/13192241/122546175-4603ee80-d061-11eb-80ca-ab01940c18c3.png)

I tried the following method but still can not get it to work.
https://groups.google.com/g/ceres-solver/c/Z8jhR8S0KN4 

Please help me figure out how to solve this problem, thank you!

**Comment by alexsmac** [comment]
Several points:
* Ceres 1.13 is *ancient* and no longer supported, the latest Ceres release is 2.0
* If you really want to build against the static runtime (implied by libcpmt), then you should enable the `MSVC_USE_STATIC_CRT` option in Ceres' CMake when building Ceres
* Why are you trying to build Ceres statically when glog (at least) appears to be built as a dynamic library?

**Comment by Learningm** [comment]
> Several points:
> 
> * Ceres 1.13 is _ancient_ and no longer supported, the latest Ceres release is 2.0
> * If you really want to build against the static runtime (implied by libcpmt), then you should enable the `MSVC_USE_STATIC_CRT` option in Ceres' CMake when building Ceres
> * Why are you trying to build Ceres statically when glog (at least) appears to be built as a dynamic library?

Thanks for your quick response.
* My project is stable using ceres 1.13.0 version on other platforms so I may not upgrade to the latest version.
* Got it.
* I miss checking default glog cmake configuration. You saved my day!

Thank you! The samples can be built and run successfully now!
