### ISSUE TITLE
Segmentation Fault with HelloWorld example

### ISSUE THREAD

**Issue by AustinMooreT** [ceres-solver/ceres-solver#685]
I've built the most recent stable release of ceres in ubuntu 20.04 docker image. All tests pass, but when I try to build my own hello world program I get a segmentation fault.

This is my code. Copied from the ceres tutorial.

```
struct CostFunctor {
   template <typename T>
   bool operator()(const T* const x, T* residual) const {
     residual[0] = 10.0 - x[0];
     return true;
   }
};

int main(int argc, char** argv) {
    google::InitGoogleLogging(argv[0]);

  // The variable to solve for with its initial value.
  double initial_x = 5.0;
  double x = initial_x;

  // Build the problem.
  ceres::Problem problem;

  // Set up the only cost function (also known as residual). This uses
  // auto-differentiation to obtain the derivative (jacobian).
  ceres::CostFunction* cost_function =
      new ceres::AutoDiffCostFunction<CostFunctor, 1, 1>(new CostFunctor);
  problem.AddResidualBlock(cost_function, nullptr, &x);

  // Run the solver!
  ceres::Solver::Options options;
  options.linear_solver_type = ceres::DENSE_QR;
  options.minimizer_progress_to_stdout = true;
  ceres::Solver::Summary summary;
  ceres::Solve(options, &problem, &summary);

  //std::cout << summary.BriefReport() << "\n";
  std::cout << "x : " << initial_x
            << " -> " << x << "\n";
  return 0;
 }
```

Note that I've commented out the BriefReport(). When I don't I end up with a linker error failing with an undefined reference to BriefReport.

Lastly I will attach my CMakeLists.txt for reference.

```cmake_minimum_required(VERSION 3.16)
set (CMAKE_CXX_STANDARD 14)
project(HellowWorld)
add_compile_options(-Wall -Wextra)
find_package(Ceres REQUIRED)
find_package(gflags REQUIRED)
add_executable(helloworld src/main.cpp)
target_link_libraries(helloworld Ceres::ceres)
target_link_libraries(helloworld Ceres::ceres gflags)
```

I've determined that the segfault occurs when calling Solve(), but I'm not sure of much else.

**Comment by NeroBurner** [comment]
`v2.0.0` is working for me here (compiling and running your example). Can you provide more info on how you built your ceres-solver binary

**Comment by sandwichmaker** [comment]
Since there is no further update on the issue I am closing it, please feel free to reopen if you have more details

**Comment by ssgari** [comment]
@ AustinMooreT can you please share an update on whether this was solved?

**Comment by AustinMooreT** [comment]
It's been a while, but if I remember correctly it had to do with mismatching gcc std::string abis I forget what library caused all of my headaches, but I ended up sorting it out. Sorry, forgot I even made an issue.
