### ISSUE TITLE
linker command failed when build helloworld.cc

### ISSUE THREAD

**Issue by tianhaoxie** [ceres-solver/ceres-solver#687]
Hi, I tried to build a simple ceres solver project with only helloworld.cc by cmake. The cmakelist is
`project(ceres_lab)

find_package(Ceres REQUIRED)
add_executable(ceres_lab main.cpp)

target_link_libraries( ceres_lab Ceres::ceres)`

**When I tried to make it, there were errors:**

`Undefined symbols for architecture x86_64:
  "google::kLogSiteUninitialized", referenced from:
      ceres::Solver::Solve(ceres::Solver::Options const&, ceres::Problem*, ceres::Solver::Summary*) in libceres.a(solver.cc.o)
      ceres::(anonymous namespace)::Minimize(ceres::internal::PreprocessedProblem*, ceres::Solver::Summary*)::vlocal__ in libceres.a(solver.cc.o)
      ceres::internal::DetectStructure(ceres::internal::CompressedRowBlockStructure const&, int, int*, int*, int*) in libceres.a(detect_structure.cc.o)
      ceres::internal::DetectStructure(ceres::internal::CompressedRowBlockStructure const&, int, int*, int*, int*)::vlocal__ in libceres.a(detect_structure.cc.o)
      ceres::internal::DetectStructure(ceres::internal::CompressedRowBlockStructure const&, int, int*, int*, int*)::vlocal__ in libceres.a(detect_structure.cc.o)
      ceres::internal::DetectStructure(ceres::internal::CompressedRowBlockStructure const&, int, int*, int*, int*)::vlocal__ in libceres.a(detect_structure.cc.o)
      ceres::internal::DetectStructure(ceres::internal::CompressedRowBlockStructure const&, int, int*, int*, int*)::vlocal__ in libceres.a(detect_structure.cc.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [ceres_lab] Error 1
make[1]: *** [CMakeFiles/ceres_lab.dir/all] Error 2
make: *** [all] Error 2
`
**The whole outputs are:**

`-- Found required Ceres dependency: Eigen version 3.3.9 in /opt/local/include/eigen3
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 2.0.0 installed in: /opt/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, AccelerateSparse, SchurSpecializations, Multithreading]
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.19)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Warning (dev) at CMakeLists.txt:5 (add_executable):
  Policy CMP0003 should be set before this line.  Add code such as

    if(COMMAND cmake_policy)
      cmake_policy(SET CMP0003 NEW)
    endif(COMMAND cmake_policy)

  as early as possible but after the most recent call to
  cmake_minimum_required or cmake_policy(VERSION).  This warning appears
  because target "ceres_lab" links to some libraries for which the linker
  must search:

    -lm, -ldl, -lm, -ldl

  and other libraries with known full path:

    /opt/local/lib/libceres.a

  CMake is adding directories in the second list to the linker search path in
  case they are needed to find libraries from the first list (for backwards
  compatibility with CMake 2.4).  Set policy CMP0003 to OLD or NEW to enable
  or disable this behavior explicitly.  Run "cmake --help-policy CMP0003" for
  more information.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/xietianhao/Desktop/ss_mls/ceres/build
Scanning dependencies of target ceres_lab
[ 50%] Building CXX object CMakeFiles/ceres_lab.dir/main.o
[100%] Linking CXX executable ceres_lab
ld: warning: directory not found for option '-F/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/System/Library/Frameworks'
ld: warning: dylib (/opt/local/lib/libglog.0.5.0.dylib) was built for newer macOS version (11.3) than being linked (11.0)
ld: warning: dylib (/opt/local/lib/libsuitesparseconfig.dylib) was built for newer macOS version (11.2) than being linked (11.0)
ld: warning: dylib (/opt/local/lib/libsuitesparseconfig.dylib) was built for newer macOS version (11.2) than being linked (11.0)
Undefined symbols for architecture x86_64:
  "google::kLogSiteUninitialized", referenced from:
      ceres::Solver::Solve(ceres::Solver::Options const&, ceres::Problem*, ceres::Solver::Summary*) in libceres.a(solver.cc.o)
      ceres::(anonymous namespace)::Minimize(ceres::internal::PreprocessedProblem*, ceres::Solver::Summary*)::vlocal__ in libceres.a(solver.cc.o)
      ceres::internal::DetectStructure(ceres::internal::CompressedRowBlockStructure const&, int, int*, int*, int*) in libceres.a(detect_structure.cc.o)
      ceres::internal::DetectStructure(ceres::internal::CompressedRowBlockStructure const&, int, int*, int*, int*)::vlocal__ in libceres.a(detect_structure.cc.o)
      ceres::internal::DetectStructure(ceres::internal::CompressedRowBlockStructure const&, int, int*, int*, int*)::vlocal__ in libceres.a(detect_structure.cc.o)
      ceres::internal::DetectStructure(ceres::internal::CompressedRowBlockStructure const&, int, int*, int*, int*)::vlocal__ in libceres.a(detect_structure.cc.o)
      ceres::internal::DetectStructure(ceres::internal::CompressedRowBlockStructure const&, int, int*, int*, int*)::vlocal__ in libceres.a(detect_structure.cc.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [ceres_lab] Error 1
make[1]: *** [CMakeFiles/ceres_lab.dir/all] Error 2
make: *** [all] Error 2
`

**My system is macos bigsur 11.4. Ceres-solver 2.00.
Thanks for everyone who read this question!**

**Comment by sandwichmaker** [comment]
you do not seem to be linking to glog.

**Comment by tianhaoxie** [comment]
Thanks for your reply. I have tried to add glog in the target_link_libraries, but it failed. What is the true way to link to glog? Really thanks!
