### ISSUE TITLE
 integer results

### ISSUE THREAD

**Issue by Y-pandaman** [ceres-solver/ceres-solver#689]
hello，Is it normal that I get integer results with ceres optimization? What is wrong with it?
I am going to optimize x and y. The result should be x=7.019328,y=149.3294324253,something like this, with decimals,But the result looks like this：
iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time
   0  1.378357e-03    0.00e+00    6.52e-07   0.00e+00   0.00e+00  1.00e+04        0    4.43e-02    6.62e-02
   1  1.021457e-03    3.57e-04    1.47e-05   1.45e+02   7.37e+00  3.00e+04        1    4.79e-02    1.14e-01
   2  1.011128e-03    1.03e-05    1.74e-05   6.80e-01   2.03e+00  9.00e+04        1    4.40e-02    1.58e-01
   3  9.996568e-04    1.15e-05    1.57e-05   7.14e-01   1.84e+00  2.70e+05        1    4.42e-02    2.02e-01
   4  9.882604e-04    1.14e-05    1.91e-05   5.83e-01   2.50e+00  8.10e+05        1    4.42e-02    2.47e-01
   5  9.844304e-04    3.83e-06    1.35e-05   2.64e-01   1.42e+00  2.43e+06        1    4.42e-02    2.91e-01
   6  9.799650e-04    4.47e-06    2.01e-05   2.59e-01   2.55e+00  7.29e+06        1    4.40e-02    3.35e-01
   7  9.671271e-04    1.28e-05    1.80e-05   5.44e-01   2.32e+00  2.19e+07        1    4.40e-02    3.79e-01
   8  9.646416e-04    2.49e-06    9.36e-06   1.82e-01   1.33e+00  6.56e+07        1    4.39e-02    4.23e-01
   9  9.635689e-04    1.07e-06    1.36e-05   9.32e-02   2.46e+00  1.97e+08        1    4.88e-02    4.72e-01
  10  9.601064e-04    3.46e-06    2.04e-05   1.97e-01   2.52e+00  5.90e+08        1    4.59e-02    5.17e-01
  11  9.517162e-04    8.39e-06    2.87e-05   3.37e-01   2.41e+00  1.77e+09        1    4.42e-02    5.62e-01
  12  9.445141e-04    7.20e-06    4.30e-05   2.37e-01   2.03e+00  5.31e+09        1    4.43e-02    6.06e-01
  13  9.378469e-04    6.67e-06    1.10e-04   9.17e-02   3.38e+00  1.59e+10        1    4.88e-02    6.55e-01
  14  9.230644e-04    1.48e-05    1.35e-03   3.57e-02   5.47e+00  4.78e+10        1    4.81e-02    7.03e-01
  15  8.996027e-04    2.35e-05    1.55e-02   3.78e-03   7.29e+00  1.43e+11        1    4.41e-02    7.47e-01
  16  8.992659e-04    3.37e-07    1.27e-06   3.29e-05   1.05e+00  4.30e+11        1    4.41e-02    7.91e-01
Ceres Solver Report: Iterations: 17, Initial cost: 1.378357e-03, Final cost: 8.992659e-04, Termination: CONVERGENCE
x: 7 y: 149

**Comment by sandwichmaker** [comment]
Ceres works on doubles so there is no reason why it should necessarily
return integers.

It is possible that your problem or your implementation of the problem has
a local minimum at the integer values you obtained but it is impossible to
say more without looking at your code.

**Comment by Y-pandaman** [comment]
Here is my main code:
```
 struct CostFunctor {
  CostFunctor(double x1, double y1, double x2, double y2)
      : x1_(x1), y1_(y1), x2_(x2), y2_(y2) {}
  template <typename T>
  bool operator()(const T *const a, T *residual) const {
    residual[0] = x1_ + a[1] - x2_;
    residual[1] = y1_ + a[0] - y2_;

    return true;
  }
  const double x1_, y1_, x2_, y2_;
};
```

```
 // 寻优参数的初始值
  double a[2] = {0, 0};

  // 构建寻优问题
  Problem problem;
  // 设置唯一的成本函数（也被称为残差）。这使用了数值微分法来获得导数（雅克比）。
  for (int i = 0; i < lineNum; i++) {
    // 残差的数量, 要优化目标的数量
    CostFunction *cost_function =
        new NumericDiffCostFunction<CostFunctor, CENTRAL, 2, 2>(
            new CostFunctor(vect[i][1], vect[i][2], vect[i][5], vect[i][6]));
    problem.AddResidualBlock(cost_function, new ceres::CauchyLoss(0.0001), a);
  }

  // 配置并运行求解器
  Solver::Options options;                      // 创建一个option
  options.minimizer_progress_to_stdout = true;  // 输出到cout
  Solver::Summary summary;                      // 优化信息
  Solve(options, &problem, &summary);           // 求解

  std::cout << summary.BriefReport() << "\n";
  std::cout << "x: " << a[0] << " y: " << a[1] << std::endl;
  return 0;
```

**Comment by sandwichmaker** [comment]
How do you know that the result should be x=7.019328,y=149.3294324253? 
do you still get an integer result if you terminate the solver early?

**Comment by sandwichmaker** [comment]
Closing because of no reply. Please re-open if you have more details.
