### ISSUE TITLE
compressed_row_sparse_matrix

### ISSUE THREAD

**Issue by cumtchenchang** [ceres-solver/ceres-solver#693]
When I use ceres, I encounter many logs about ceres::CRSMatrix:
compressed_row_sparse_matrix.cc:149 # of rows: 20 # of columns: 3 max_num_nonzeros: 63. Allocating 840
compressed_row_sparse_matrix.cc:149 # of rows: 16 # of columns: 6 max_num_nonzeros: 102. Allocating 1292
compressed_row_sparse_matrix.cc:149 # of rows: 20 # of columns: 3 max_num_nonzeros: 63. Allocating 840
compressed_row_sparse_matrix.cc:149 # of rows: 18 # of columns: 6 max_num_nonzeros: 114. Allocating 1444
compressed_row_sparse_matrix.cc:149 # of rows: 20 # of columns: 3 max_num_nonzeros: 63. Allocating 840
compressed_row_sparse_matrix.cc:149 # of rows: 18 # of columns: 6 max_num_nonzeros: 114. Allocating 1444
compressed_row_sparse_matrix.cc:149 # of rows: 20 # of columns: 3 max_num_nonzeros: 63. Allocating 840
compressed_row_sparse_matrix.cc:149 # of rows: 20 # of columns: 6 max_num_nonzeros: 126. Allocating 1596
compressed_row_sparse_matrix.cc:149 # of rows: 20 # of columns: 3 max_num_nonzeros: 63. Allocating 840
compressed_row_sparse_matrix.cc:149 # of rows: 20 # of columns: 6 max_num_nonzeros: 126. Allocating 1596
compressed_row_sparse_matrix.cc:149 # of rows: 20 # of columns: 3 max_num_nonzeros: 63. Allocating 840
compressed_row_sparse_matrix.cc:149 # of rows: 20 # of columns: 6 max_num_nonzeros: 126. Allocating 1596
compressed_row_sparse_matrix.cc:149 # of rows: 20 # of columns: 3 max_num_nonzeros: 63. Allocating 840
compressed_row_sparse_matrix.cc:149 # of rows: 20 # of columns: 6 max_num_nonzeros: 126. Allocating 1596

Could you tell me how to solver?

**Comment by sandwichmaker** [comment]
You are using miniglog. Use the full glog please.
