### ISSUE TITLE
Documentation about running with OpenMP

### ISSUE THREAD

**Issue by amy-tabb** [ceres-solver/ceres-solver#694]
The default value for [Solver::Options::num_threads](http://ceres-solver.org/nnls_solving.html?highlight=openmp#_CPPv4N5ceres6Solver7Options11num_threadsE) is 1.  Searching the documentation for 'OpenMP' or 'parallel' does not return the `num_threads` class member.  In my experience setting `num_threads > 1` is key for getting Ceres to run multi-threaded and/or efficiently on multi-core processors.  

In my case, I had been using Ceres for 4 years before I discovered this setting, by accident by looking through .h files.

I can add documentation if this is desirable.

**Comment by sandwichmaker** [comment]
Amy that would be great!

**Comment by amy-tabb** [comment]
(Belatedly) Ok, planned for in a couple weeks, I haven't used Gerrit and will have to get that set up. Anything not in [http://ceres-solver.org/contributing.html](http://ceres-solver.org/contributing.html) that I should know for a documentation contribution, please let me know.

**Comment by sandwichmaker** [comment]
I think you will need sphinx and the sphinx rtd theme installed to build. I
forget if that's included in the contributing docs (on my phone right now).

**Comment by sandwichmaker** [comment]
Hi Amy any update on this?

**Comment by amy-tabb** [comment]
Apologies, more than a year later -- I looked into adding this documentation, after I got bogged down with work, and now there is documentation of how to set the number of threads with OpenMP.  I recommend closing, unless you have other thoughts.

int Solver::[Summary](http://ceres-solver.org/nnls_solving.html?highlight=openmp#_CPPv4N5ceres6Solver7SummaryE)::num_threads_used[¶](http://ceres-solver.org/nnls_solving.html?highlight=openmp#_CPPv4N5ceres6Solver7Summary16num_threads_usedE)

    Number of threads actually used by the solver for Jacobian and residual evaluation. This number is not equal to [Solver::Summary::num_threads_given](http://ceres-solver.org/nnls_solving.html?highlight=openmp#_CPPv4N5ceres6Solver7Summary17num_threads_givenE) if none of OpenMP or CXX_THREADS is available.
