### ISSUE TITLE
Preparation step shared across cost functions

### ISSUE THREAD

**Issue by alexkaratarakis** [ceres-solver/ceres-solver#697]
I have a cost function with 10-20 residuals each of which can be calculated in parallel. Therefore, I am trying to leverage the solver's parallelism.
There is a somewhat expensive preparation step before getting to the embarrassingly parallel part, so I am trying to extract that out to avoid recalculation. In a nutshell, it looks like this:

```C++
    template <typename T>
    bool operator()(const T* const x,  T* residual) const
    {
        const auto common_struct = prepare(x);
        for (std::size_t = 0; i < RESIDUAL_COUNT; i++)
        {
            residual[i] = calculate(i, common_struct);
        }

        return true;
    }
```

I found [EvaluationCallback](http://ceres-solver.org/nnls_modeling.html#evaluationcallback) but it seems to not work in this case: the `common_struct` needs the current iterations Jacobians/values, but the signature of `EvaluationCallback` is not providing them:
```C++
  virtual void PrepareForEvaluation(bool evaluate_jacobians,
                                    bool new_evaluation_point) = 0;
```

According to the docs for `EvaluationCallback`:
```
// NOTE: Ceres provides no mechanism to share data other than the
// notification from the callback. Users must provide access to
// pre-computed shared data to their cost functions behind the scenes;
// this all happens without Ceres knowing.
```

However, I was unable to find a way to get access to the Jacobians/values. In fact, if I am reading the code correctly, the memory that hosts the Jets/doubles is not allocated yet at the time the `EvaluationCallback` is executed.

Is there a way to do a preparation step that depends on the iteration parameters?

**Comment by alexsmac** [comment]
Yes, in fact the original rationale behind EvaluationCallback was to support residuals that were evaluated en-masse on a GPU but represented as independent CostFunctions in a Ceres problem.  As per the docs [here](https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/evaluation_callback.h#L68) and [here](http://ceres-solver.org/nnls_modeling.html?highlight=evaluationcallback#_CPPv4N5ceres18EvaluationCallback20PrepareForEvaluationEbb) - which evidently could be clearer - when you specify an EvaluationCallback, Ceres will copy the parameter values to be evaluated into the user-supplied parameter pointers, set explicitly via AddParameterBlock() or implicitly via AddResidualBlock(), before the callback is invoked.  Therefore in the GPU example, the callback would actually do the residual evaluation by copying the parameters from the user-supplied pointers to the GPU, run some kernels and then copy the results back into some array that was shared with the CostFunctions (exact mechanism used entirely up to the user).

Note that what this does *not* do is provide the Jets, it only provides the parameter values with which the CostFunctions will next be evaluated (and whether they will be asked to generated jacobians or just residuals).

**Comment by sandwichmaker** [comment]
One more point, EvaluateCallback is called Once everytime before the whole problem is evaluated. So there is no i, what you need to do is evaluate and cache the whole Jacobian and then use the Evaluate() method of your costfunctions to copy from the cache into the residual vector and Jacobian matrices provided to Evaluate.

**Comment by alexkaratarakis** [comment]
I see! Thanks to both replies. I will go through the examples again with this new information.
