### ISSUE TITLE
cross compile can't find lapcak

### ISSUE THREAD

**Issue by cute-duck** [ceres-solver/ceres-solver#698]
i had cross compiled lapack ,which from https://github.com/Reference-LAPACK/lapack.this is my lapack library:
![2021-08-10 17-59-45屏幕截图](https://user-images.githubusercontent.com/20561247/128847841-7795d315-72d2-4bc0-a4c7-cfa9417c2e11.png)

when i use cmake-gui,to cross compile ceres ,can not find lapcak,should i write findlapck.cmake for find_packge(lapack),but it is difficult for me,or there maybe some easy method,here is my cmake-gui screenshot :
![2021-08-10 18-02-54屏幕截图](https://user-images.githubusercontent.com/20561247/128848223-d18c2f85-0146-45b5-a9b9-b8c54499689f.png)
thankyou give me some advice

**Comment by alexsmac** [comment]
This is not a Ceres-specific question, we use the stock FindBLAS and FindLAPACK scripts provided by CMake and so this question relates how to configure them to find a BLAS/LAPACK installation in a non-standard location.  You should be able to control this by setting [CMAKE_PREFIX_PATH](https://cmake.org/cmake/help/v3.21/variable/CMAKE_PREFIX_PATH.html) to include the custom install directory.  If that fails you would need to review the FindBLAS and FindLAPACK scripts to understand why.

**Comment by sergiud** [comment]
For cross-compiling you actually need [`CMAKE_FIND_ROOT_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_ROOT_PATH.html) not `CMAKE_PREFIX_PATH`.
