### ISSUE TITLE
Typo in example code in docs

### ISSUE THREAD

**Issue by tangobravo** [ceres-solver/ceres-solver#701]
http://ceres-solver.org/interfacing_with_autodiff.html

That page currently includes this example function:
```
template <typename T> T TemplatedComputeDistortion(const T r2) {
  const double k1 = 0.0082;
  const double k2 = 0.000023;
  return 1.0 + k1 * y2 + k2 * r2 * r2;
}
```

The undefined variable `y2` in the final line should I presume be `r2`.

**Comment by sandwichmaker** [comment]
Thanks @tangobravo, I will fix this and credit you.
