### ISSUE TITLE
dll - crt bug in CostFunction

### ISSUE THREAD

**Issue by Ubpa** [ceres-solver/ceres-solver#702]
`class CostFunction` has a member variable `std::vector<int32_t> parameter_block_sizes_`, which will be initialized by `mutable_parameter_block_sizes()`。

When using the shared library, `class CostFunction` will be exported, but template `class SizedCostFunction` isn't exported.
The ctor of `class SizedCostFunction` will initialize `parameter_block_sizes_`.

But the memory of `std::vector<int32_t> parameter_block_sizes_` is allocated outside the dll (because it's a template class and will not be exported), but the memory will be released inside the dll by `class CostFunction`. It will cause a memory problem.

**Comment by Ubpa** [comment]
When I try to push in Windows10, a window appears asking me to enter an account and a password, probably because the cookie is not in effect. After a few more attempts, it still doesn't work.

**Comment by sergiud** [comment]
It is not clear why releasing memory within the DLL is a problem. Isn't this done throughout Ceres solver?

**Comment by sergiud** [comment]
Given Ceres is built and successfully tested on Windows as a shared library now, I believe the issue can be closed.
