### ISSUE TITLE
Run time errors, while using ceres-solver in iOS app

### ISSUE THREAD

**Issue by ArMouReR** [ceres-solver/ceres-solver#708]
Hi,

I have compiled ceres in macOS in order to use for an iOS app.
Everything complied successfully, but when I try to use ceres::DENSE_NORMAL_CHOLESKY I am getting exceptions.
The exceptions differ depending on num_threads parameter.
When I set it to more then one I am getting EXC_BAD_ACCESS in inline line below:
```
template <int j, int N, int Offset, typename T, typename JetT>
struct Make1stOrderPerturbation {
 public:
  inline static void Apply(const T* src, JetT* dst) {
    if (j == 0) {
      DCHECK(src);
      DCHECK(dst);
    }
    dst[j] = JetT(src[j], j + Offset);
    Make1stOrderPerturbation<j + 1, N, Offset, T, JetT>::Apply(src, dst);
  }
};
```
And the log is quiet.

When I set it to one thread I am getting exception in the following lines (eigen_assert triggered):
```
EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE explicit variable_if_dynamic(T v) { EIGEN_ONLY_USED_FOR_DEBUG(v); eigen_assert(v == T(Value)); }
```
And in the log I see the following a few times:
```
objc[666]: Lazily named class 0x281c38cc0 wasn't named by lazy name handler
```

What I have tried:
1. Tryied to compile without therads - didn't helped
2. Noticed that sdk target version (14.3) not equal App target(11) - fixed, but still getting the same errors.

The same code but in Visual Studio on windows is running without any issues.

Any hints how to debug the problem are really appreciated...

**Comment by sandwichmaker** [comment]
what is the size of your parameter block >? (or did we already discuss this on the mailinglist that you are using too huge of a parameter block size and thats breaking the stack)

**Comment by ArMouReR** [comment]
Thanks, for reply! Indeed we already discussed it on the mailinglist, so I am closing the issue for now.
