### ISSUE TITLE
Run ceres with openmp was aborted by solve() with error of double free; 

### ISSUE THREAD

**Issue by rainlord** [ceres-solver/ceres-solver#709]
when I run ceres with openmp was aborted by solve() with error of double free; The stack trace as fellow:
so please tell me how should i to fix it? thanks  alot!   
Is this related with Macro of eigen,because i set the Macro of -DEIGEN_MALLOC_ALREADY_ALIGNED=0.if i do not set the DEIGEN_MALLOC_ALREADY_ALIGNED ,my program will have error which is  related with eigen alignment error.  
>double free or corruption (out)
*** SIGSEGV (@0x0) received by PID 9900 (TID 0x7efc7bfff700) from PID 0; stack trace: ***
SvoInterface::stereoCallback()44444444
    @     0x7efcb8540f20 (unknown)
    @     0x55cd9567d875 Eigen::internal::gemm_pack_lhs<>::operator()()
    @     0x55cd9569c758 Eigen::internal::general_matrix_matrix_product<>::run()
    @     0x7efcb671cc62 Eigen::internal::gemm_functor<>::operator()()
    @     0x7efcb671babf Eigen::internal::parallelize_gemm<>()
    @     0x7efcb671a859 Eigen::internal::generic_product_impl<>::scaleAndAddTo<>()
    @     0x7efcb6719010 Eigen::internal::generic_product_impl<>::evalTo<>()
    @     0x7efcb6717a26 Eigen::internal::Assignment<>::run()
    @     0x7efcb6715ede Eigen::internal::call_assignment_no_alias<>()
    @     0x7efcb6714352 Eigen::PlainObjectBase<>::_set_noalias<>()
    @     0x7efcb671216f Eigen::PlainObjectBase<>::_init1<>()
    @     0x7efcb671128e Eigen::Matrix<>::Matrix<>()
    @     0x7efcb6710912 Eigen::internal::call_assignment<>()
    @     0x7efcb670fc40 Eigen::internal::call_assignment<>()
    @     0x7efcb670f273 Eigen::MatrixBase<>::operator=<>()
    @     0x7efcb670e794 svo::ceres_backend::SpeedAndBiasError::EvaluateWithMinimalJacobians()
    @     0x7efcb670e5e8 svo::ceres_backend::SpeedAndBiasError::Evaluate()
    @     0x7efcae8e3735 ceres::internal::ResidualBlock::Evaluate()
    @     0x7efcae9058e1 _ZN5ceres8internal16ProgramEvaluatorINS0_21BlockEvaluatePreparerENS0_19BlockJacobianWriterENS0_21NullJacobianFinalizerEE8EvaluateERKNS0_9Evaluator15EvaluateOptionsEPKdPdSC_SC_PNS0_12SparseMatrixE._omp_fn.2
    @     0x7efcae1a0edf GOMP_parallel
    @     0x7efcae90737a ceres::internal::ProgramEvaluator<>::Evaluate()
    @     0x7efcae91a10d ceres::internal::TrustRegionMinimizer::EvaluateGradientAndJacobian()
    @     0x7efcae91aba2 ceres::internal::TrustRegionMinimizer::IterationZero()
    @     0x7efcae91f504 ceres::internal::TrustRegionMinimizer::Minimize()
    @     0x7efcae8f121d ceres::Solver::Solve()
    @     0x7efcae8f20a9 ceres::Solve()
    @     0x7efcb6563149 svo::ceres_backend::Map::solve()
    @     0x7efcb655e2ed svo::Estimator::optimize()
    @     0x7efcb64ecd06 svo::CeresBackendInterface::optimizationLoop()
    @     0x7efcb6504766 std::__invoke_impl<>()
    @     0x7efcb64fc9c3 std::__invoke<>()
    @     0x7efcb6556b55 _ZNSt6thread8_InvokerISt5tupleIJMN3svo21CeresBackendInterfaceEFvvEPS3_EEE9_M_invokeIJLm0ELm1EEEEDTcl8__invokespcl10_S_declvalIXT_EEEEESt12_Index_tupleIJXspT_EEE

**Comment by sandwichmaker** [comment]
Closing because of lack of response or details. Please feel free to re-open if there is more.
