### ISSUE TITLE
Dynamic number of variables and loops within function

### ISSUE THREAD

**Issue by JCCPort** [ceres-solver/ceres-solver#710]
Hi,

I'm trying to use ceres for a function that is trying to fit multiple waveforms in a dataset - there are no analytical solutions to this waveform so instead we match to an idealised, data-driven, waveform. 

This creates two demands:
- As the data can contain any number of these waveforms I need to be able to use a function that takes a dynamically sized number of variables, the first of which is the number of waveforms.
- Then I loop over the data I went to fit to for each waveform, comparing the difference with the "ideal" waveform that I pass as a constant argument to the function.

Worth noting is that whilst the number of waveforms is not known at compile time, it is known in advance of calling anything ceres related through an initial estimator.

Cheers,
Josh

**Comment by sandwichmaker** [comment]
Why not create one residual block per waveform?

**Comment by sandwichmaker** [comment]
Josh, There is a two dimensional bicubic interpolator.

https://github.com/ceres-solver/ceres-solver/blob/master/examples/bicubic_interpolation.cc

**Comment by sandwichmaker** [comment]
the number of variables in each cost function  are different? or across problems are different?

**Comment by sandwichmaker** [comment]
Closing because of lack of response.
