### ISSUE TITLE
ceres-solve broken with throw_std_bad_alloc()

### ISSUE THREAD

**Issue by cute-duck** [ceres-solver/ceres-solver#713]
Imitate the cartographer to achieve graph_based slam. When the optimized node exceeds 2000, ceres::solve() will apply for a very large and unreasonable memory, and then the program crashes in this place.I guess it is my ceres library compilation error, but I can’t find the possibility What's wrong.
![image](https://user-images.githubusercontent.com/20561247/139401456-76dfb7e3-69cf-4904-a4a5-2cba84a37f6e.png)

**Comment by sandwichmaker** [comment]
You are trying to solve a large problem. can you share some details about the size of the problem and what linear solver you are trying to use?

**Comment by cute-duck** [comment]
Non-linear optimization uses the LM framework,and here is some of my code about the problem construction and solve，same as cortograppher:
    ceres::Problem::Options problem_options;
    ceres::Problem problem(problem_options);
    // Set the starting point.
  // TODO(hrapp): Move ceres data into SubmapSpec.
    map<int, std::array<double, 3>> C_submaps;
    map<int, std::array<double, 3>> C_nodes;
    //std::map<std::string, CeresPose> C_landmarks;
    bool first_submap = true;
    FLOGD("set params submaps data");
    for (map<int, SubmapSpec2D>::iterator it = submap_data_.begin(); it != submap_data_.end(); it++) {
        FLOGD("submap_id = %d", it->first);
        C_submaps.insert(make_pair(it->first, FromPose(it->second.global_pose)));
        problem.AddParameterBlock(C_submaps.at(it->first).data(), 3);
        if (first_submap) {
            first_submap = false;
            // Fix the pose of the first submap or all submaps of a frozen
            // trajectory.
            problem.SetParameterBlockConstant(C_submaps.at(it->first).data());
        }
    }
    FLOGD("set params nodes data");
    for (map<int, NodeSpec2D>::iterator it = node_data_.begin(); it != node_data_.end(); it++) {
        C_nodes.insert(make_pair(it->first, FromPose(it->second.global_pose_2d)));
        problem.AddParameterBlock(C_nodes.at(it->first).data(), 3);
        if (first_submap) {
            first_submap = false;
            // Fix the pose of the first submap or all submaps of a frozen
            // trajectory.
            problem.SetParameterBlockConstant(C_nodes.at(it->first).data());
        }
    }
    //int test_nodeid = 0;
    //
    //for (auto it = constraints.begin(); it != constraints.end(); it++) {

    //    C_nodes.insert(make_pair(test_nodeid, FromPose(node_data_.at(it->node_id).global_pose_2d)));
    //    problem.AddParameterBlock(C_nodes.at(it->first).data(), 3);
    //    if (first_submap) {
    //        first_submap = false;
    //        // Fix the pose of the first submap or all submaps of a frozen
    //        // trajectory.
    //        problem.SetParameterBlockConstant(C_nodes.at(it->first).data());
    //    }
    //    problem.AddResidualBlock(
    //        CreateAutoDiffSpaCostFunction(it->pose),
    //        // Loop closure constraints should have a loss function.
    //        it->tag == ConstraintBuilder2D::Constraint::INTER_SUBMAP
    //        ? new ceres::HuberLoss(options_.huber_scale)
    //        : nullptr,
    //        C_submaps.at(it->submap_id).data(),
    //        C_nodes.at(it->node_id).data());
    //}
    // Add cost functions for intra- and inter-submap constraints.
    FLOGD("add constraints");
    FLOGD("C_submaps.size = %d C_nodes.size = %d",C_submaps.size(), C_nodes.size());
    for (auto it = constraints.begin(); it != constraints.end(); it++) {
        FLOGD("submap_id = %d node_id = %d", it->submap_id, it->node_id);
        problem.AddResidualBlock(
            CreateAutoDiffSpaCostFunction(it->pose),
            // Loop closure constraints should have a loss function.
            it->tag == ConstraintBuilder2D::Constraint::INTER_SUBMAP
            ? new ceres::HuberLoss(options_.huber_scale)
            : nullptr,
            C_submaps.at(it->submap_id).data(),
            C_nodes.at(it->node_id).data());
    }

    // Add cost functions for landmarks.
    //AddLandmarkCostFunctions(landmark_nodes, node_data_, &C_nodes, &C_landmarks,
    //    &problem, options_.huber_scale());

       // Add penalties for violating odometry or changes between consecutive nodes
       // if odometry is not available.
    FLOGD("add node interval constraints ");
    for (auto node_it = node_data_.begin(); node_it != node_data_.end();) {
        
        //problem.AddResidualBlock(
        //    CreateAutoDiffSpaCostFunction(
        //        ConstraintBuilder2D::Constraint::Pose{ Embed3D(node_it->second.global_pose_2d),
        //                         options_.local_slam_pose_translation_weight,
        //                         options_.local_slam_pose_rotation_weight }),
        //    nullptr /* loss function */, C_nodes.at(node_it->first).data(),
        //    C_nodes.at(node_it->first).data());
        //continue;
        auto prev_node_it = node_it;

        //int trajectory_end = 1000;//�����ģ����洫�������峤��
        for (++node_it; node_it != node_data_.end(); ++node_it) {
            const int first_node_id = prev_node_it->first;
            const NodeSpec2D& first_node_data = prev_node_it->second;
            prev_node_it = node_it;
            const int second_node_id = node_it->first;
            const NodeSpec2D& second_node_data = node_it->second;

            if (second_node_id != first_node_id + 1) {
                continue;
            }

            //Add a relative pose constraint based on the odometry (if available).
            //std::unique_ptr<Rigid3d> relative_odometry =
            //    CalculateOdometryBetweenNodes(trajectory_id, first_node_data,
            //        second_node_data); //��ע�ͺ���ӽӿ��Ȳ���odoԼ��
            //Rigid3d relative_odometry = Rigid3d::Identity();
            //if (1/*relative_odometry != nullptr*/) {
            //    problem.AddResidualBlock(
            //        CreateAutoDiffSpaCostFunction(ConstraintBuilder2D::Constraint::Pose{
            //            relative_odometry, options_.odometry_translation_weight,
            //            options_.odometry_rotation_weight }),
            //            nullptr /* loss function */,
            //            C_nodes.at(first_node_id).data(),
            //            C_nodes.at(second_node_id).data());
            //}

            // Add a relative pose constraint based on consecutive local SLAM poses.
            const Rigid3d relative_local_slam_pose =
                Embed3D(first_node_data.local_pose_2d.inverse() *
                    second_node_data.local_pose_2d);
            problem.AddResidualBlock(
                CreateAutoDiffSpaCostFunction(
                    ConstraintBuilder2D::Constraint::Pose{ relative_local_slam_pose,
                                     options_.local_slam_pose_translation_weight,
                                     options_.local_slam_pose_rotation_weight }),
                nullptr /* loss function */, C_nodes.at(first_node_id).data(),
                C_nodes.at(second_node_id).data());
        }

    }

      // Solve.
    FLOGD("start solve");
    ceres::Solver::Summary summary;
    ceres::Solver::Options ceres_solver_options;
    ceres_solver_options.linear_solver_type = ceres::DENSE_QR;
    ceres_solver_options.minimizer_progress_to_stdout = true;
    ceres_solver_options.max_num_iterations = 5;
    FLOGD("********************");
    ceres::Solve(ceres_solver_options, &problem, &summary);

**Comment by cute-duck** [comment]
my demo has 2000 node and 34 submaps,then it goes wrong.but when i use a few nodes and submaps it works well.

**Comment by sandwichmaker** [comment]
you are using DENSE_QR. Thats the wrong linear solver. It creates a dense jacobian which consumes an enormous amount of memory. Since this is a bundle adjustment problem, you should either use DENSE_SCHUR or SPARSE_SCHUR as your solver.
