### ISSUE TITLE
std::shared_ptr<ceres::Problem>() as class member

### ISSUE THREAD

**Issue by whu-lyh** [ceres-solver/ceres-solver#714]
Hi, guys, recently, i use the std::shared_ptr<ceres::Problem> m_problem as class(OptimizerCeres) member as following codes shown:
```
OptimizerCeres::OptimizerCeres(){
	m_problem = std::make_shared<ceres::Problem>();
	m_options = std::make_shared<ceres::Solver::Options>();
	m_summary = std::make_shared<ceres::Solver::Summary>();
}
OptimizerCeres::~OptimizerCeres(){}
```
and i calling `m_problem->AddParameterBlock()` to build a whole problem like tutorial saying. i finish the optimization but there is a pointer release memory leak while the program finished and my program crushed. Any body had met this problem ? or where i implement wrong? Thx.
I test that the `ceres::Solver::Options` doesn't support to be implemented as a std::shared_ptr, if i use the normal pointer with new operation, the program works well. But, why this happens?

**Comment by sandwichmaker** [comment]
Can you share a small example which causes the crash? I do not think it is the program thats causing the problem. I suspect you are holding onto a cost function or a loss function that you are passing to the Problem thats the issue.

**Comment by whu-lyh** [comment]
sorry, i am rushing to my project(i replace all std::shared_ptr with norm instantiation, all works fine) and can't produce a small example, but i will retest this latter.

**Comment by sandwichmaker** [comment]
Closing for now, please re-open when you have more details.

**Comment by whu-lyh** [comment]
```C++
#include <ceres/ceres.h>

#ifdef _DEBUG
#pragma comment(lib, "ceres-debug.lib")
#else
#pragma comment(lib, "ceres.lib")
#endif

class optimizer
{
public:
	typedef std::shared_ptr<optimizer> Ptr;
	optimizer()
	{
		m_problem = std::make_shared<ceres::Problem>();
		m_summary = std::make_shared<ceres::Solver::Summary>();
	}
	~optimizer(){}

	bool exec()
	{
		ceres::Solve(*m_options, m_problem.get(), m_summary.get());
		return true;
	}

public:
	ceres::Problem::Options m_problem_option;
	std::shared_ptr<ceres::Problem> m_problem;
	std::shared_ptr<ceres::Solver::Options> m_options; // do not use std::shared_ptr
	std::shared_ptr<ceres::Solver::Summary> m_summary;
};
int main()
{
	optimizer::Ptr op = std::make_shared<optimizer>();
	op->exec();
	std::cout << op->m_summary->FullReport();
	system("pause");
	return 1;
}
```
HI, i write a simple toy code testing the std::shared_ptr with ceres::Solver::Options, if i replace `std::shared_ptr<ceres::Solver::Options> m_options;` with `ceres::Solver::Options`, this program works fine. Waiting for your reply~

**Comment by sandwichmaker** [comment]
This is because you are not calling make_shared on options, so its a null ptr.

Adding the line

m_options = std::make_shared<ceres::Solver::Options>();

to the constructor fixes the problem.

**Comment by whu-lyh** [comment]
I am so cracked，such a low-level mistake
