### ISSUE TITLE
Jet issues, syntax error.

### ISSUE THREAD

**Issue by lukkio88** [ceres-solver/ceres-solver#716]
Hi, I have an issue with the `Jet` as well. I've followed the installation guide provided in the link. I am getting this error when building from visual studio 2019, windows 10:

```
183>D:\Git\ceres-solver\include\ceres/jet.h(932,1): error C2334: unexpected token(s) preceding ':'; skipping apparent function body
183>D:\Git\ceres-solver\include\ceres/jet.h(960,1): error C2143: syntax error: missing ')' before ';'
183>D:\Git\ceres-solver\include\ceres/jet.h(960,1): error C2059: syntax error: ')'
183>D:\Git\ceres-solver\include\ceres/jet.h(960,1): error C2238: unexpected token(s) preceding ';'
```

Don't know if there's something else I have to configure before building.

_Originally posted by @lukkio88 in https://github.com/ceres-solver/ceres-solver/issues/712#issuecomment-957961741_

**Comment by alexsmac** [comment]
What version of Eigen are you using?  It sounds similar to [this issue](https://gitlab.com/libeigen/eigen/-/issues/1603) in Eigen's bug tracker, but we aren't using any ternary operators in the definition of the `numeric_limits` for Jet [here](https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/jet.h#L901) which are the lines referenced by the errors.

**Comment by lukkio88** [comment]
As update, I just tried Eigen 3.3.9, I am still getting the same problem.
