### ISSUE TITLE
I want to change all the data types of ceres from double to float, is it feasible?

### ISSUE THREAD

**Issue by AiPanPan** [ceres-solver/ceres-solver#720]
I want to change all the data types of ceres to float, is it feasible?  could give me some suggestions? Thank you

**Comment by alexsmac** [comment]
Depending upon your configuration, you can already tell Ceres to solve using single-precision using [this option](https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/solver.h#L526) even though it continues to use double precision for I/O.  If you can tolerate reduced precision, then this can result in improved runtime performance and memory usage.  Usually the conversion to/from double precision for I/O is not a significant overhead relative to performing the solve itself

**Comment by sandwichmaker** [comment]
No it is not feasible. Your best bet is what Alex suggested. That said, what is it that you are trying to do?

**Comment by AiPanPan** [comment]
I want to accelerate ceres by NEON, but  my chip is ARM32，only can support float data. so I want to  change all the data types of ceres to float. or do you have any better suggestions？Thank you

**Comment by AiPanPan** [comment]
I want to accelerate ceres by NEON, but  my chip is ARM32，only can support float data. so I want to  change all the data types of ceres to float. or do you have any better suggestions？Thank you

**Comment by sandwichmaker** [comment]
Thanks @AiPanPan I understand your use case. What type/sized problems are you trying to solve?

**Comment by AiPanPan** [comment]
1. "No it is not feasible" means I cannot change all the data types of ceres to float? I use ceres to slove SLAM problem, but beacuse of my chip is cheap, ceres solver time is too long.( ceres solver time is 250ms but I want it to be less 130ms). So I want to  accelerate ceres by NEON, but my chip only support  NEON accleration on float data. I try to transform all double to float on ceres  2.0, it seems to be OK, but I still have some concerns. So  I want to you give me some suggestions.  2. If  use_mixed_precision_solves  = true, is data type float?  Thanks

**Comment by sandwichmaker** [comment]
when using mixed precision solves the key computational task is cholesky
factorization which is done in single precision, which should help
significantly.
that said, it will not give you all the performance.
you can try and change all doubles to floats and see how that works out for
you, but things like suitesparse won't work for you.
you maybe able to get eigen based stuff working for you.

**Comment by AiPanPan** [comment]
ok.Your help was greatly appreciated.
