### ISSUE TITLE
What is the way of UpdateRhs computing the term F'b - F'E(E'E)^(-1) E'b

### ISSUE THREAD

**Issue by whuaegeanse** [ceres-solver/ceres-solver#721]
@sandwichmaker 
After analyzing the code of the function [UpdateRhs](https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/schur_eliminator_impl.h#L377-L422), I did not find the calculation code of F'b. Did I miss something?
According to the [comment ](https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/schur_eliminator_impl.h#L377-L379)of the function UpdateRhs, F'b should be calculated.

**Comment by sandwichmaker** [comment]
it happens

https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/schur_eliminator_impl.h#L481

**Comment by whuaegeanse** [comment]
@sandwichmaker
Thanks, I got it.
