### ISSUE TITLE
Ceres with minilog

### ISSUE THREAD

**Issue by GeraldLodron** [ceres-solver/ceres-solver#722]
Putting global variables in global namespace like "ERROR" leads to some conflicts in many build environments. They are defined in minilog and lead to compiler errors in combination with other projects.

**Comment by sandwichmaker** [comment]
@GeraldLodron miniglog is a shallow clone of the google logging library and yes its possible that it leads to conflicts in some build environment, but I am not sure if there is any way around this either.

**Comment by sandwichmaker** [comment]
sure but we can't do that in the ceres source because that will break compatibility with google glog.

**Comment by GeraldLodron** [comment]
wouldnt it be possible to use a kind of Config header file generated from cmake with an log function which eighter calls google log or minilog with a better non breaking interface?

**Comment by sandwichmaker** [comment]
It is going to lead to a lot of churn in the code, but if you have a clean way to do this I am happy to look at a PR.

**Comment by sandwichmaker** [comment]
Closing because of lack of feasibility.
