### ISSUE TITLE
Link to patch for dealing with glog/gflags incompatability can't be found anymore

### ISSUE THREAD

**Issue by jcla1** [ceres-solver/ceres-solver#723]
This is just a documentation bug -- I was reading the installation page and came across the note describing problems compiling glog from source, when gflags 2.1 is already available:

https://github.com/ceres-solver/ceres-solver/blame/ec4f2995bbde911d6861fb5c9bb7353ad796e02b/docs/source/installation.rst#L75

The patch that is linked to there on Google Code doesn't exist anymore though.

**Comment by sandwichmaker** [comment]
Thanks @jcla1 for pointing this out.
@alexsmac can you look at this please, I think you were the one who added this pointer to begin with.

**Comment by sandwichmaker** [comment]
I removed this from the docs as we should be using a later version of glog anyways.
