### ISSUE TITLE
Head pose estimation using 3D vertices and ground truth 2D landmarks. 

### ISSUE THREAD

**Issue by Davar1990** [ceres-solver/ceres-solver#724]
Hello,

I have used Ceres `AutoDiffCostFunction` on easy fitting problems without any issues before. But now I'm trying to extend the functionalities to a problem of head pose estimation using 3D vertices from a head model and their corresponding ground truth 2D landmarks in the image. I have checked my inputs and have also used them in OpenCV `solvepnp` and the pose estimation works just fine. But in Ceres, it doesn't iterator more than once and returns the same initial values. I would appreciate any suggestions.

```
struct ProjectionError {
	
	ProjectionError(const easy3d::vec3& vert, const cv::Point2d& lm, const cv::Mat& intrinsicMatrix) {
		_cvVert = cv::Point3d(vert[0], vert[1], vert[2]);
		_gtLm = lm;
		_intrinsicMatrix = intrinsicMatrix;
	}

	template <typename T>
	bool operator()(const T* const w, T* residual) const {

		//------ filling the rotation vector
		cv::Mat rVec(3, 1, CV_64FC1);
		double* rPtr = (double*)rVec.data;
		std::memcpy(&rPtr[0], &w[0], sizeof(double));
		std::memcpy(&rPtr[1], &w[1], sizeof(double));
		std::memcpy(&rPtr[2], &w[2], sizeof(double));

		//------ filling the translation vector
		cv::Mat tVec(3, 1, CV_64FC1);
		double* tPtr = (double*)tVec.data;
		std::memcpy(&tPtr[0], &w[3], sizeof(double));
		std::memcpy(&tPtr[1], &w[4], sizeof(double));
		std::memcpy(&tPtr[2], &w[5], sizeof(double));

		//------ projecting the 3d points onto 2d image
		vector<cv::Point3d> vert = { _cvVert };
		vector<cv::Point2d> projectedLm;
		cv::projectPoints(vert, rVec, tVec, _intrinsicMatrix, cv::Mat(), projectedLm);

		//------ handling the residuals
		residual[0] = static_cast<T>(_gtLm.x - projectedLm[0].x);
		residual[1] = static_cast<T>(_gtLm.y - projectedLm[0].y);

		return true;
	}

private:
	cv::Point3d    _cvVert;    // 3d vertex
	cv::Point2d    _gtLm;      // 2d landmark
	cv::Mat        _intrinsicMatrix;
};
```

```
vector<double> w(6, 0.1);    // 6 parameters for rotation and translation
ceres::Problem problem;
for (int i = 0; i < numObservations; i++) {
	ProjectionError* pErr = new ProjectionError(verts[i], landmarks[i], intrinsicMatrix);
	ceres::CostFunction* costFunction = new ceres::AutoDiffCostFunction<ProjectionError, 2, 6>(pErr);
	problem.AddResidualBlock(costFunction, NULL, &w[0]);
}

ceres::Solver::Options options;
options.max_num_iterations = 125;
//options.linear_solver_type = ceres::DENSE_SCHUR;
ceres::Solver::Summary summary;
ceres::Solve(options, &problem, &summary);
cout << summary.BriefReport() << endl << endl;
for (int i = 0; i < w.size(); i++)
	cout << "i = " << i << ", w = " << w[i] << endl;
```

**Comment by sandwichmaker** [comment]
can you share the output from ceres and from Summary::FullReport()?

**Comment by Davar1990** [comment]
Thanks for the prompt response. Please find below. 
![Capture](https://user-images.githubusercontent.com/17028943/143496312-c3dd7b0a-387f-4cfc-9fdf-fc4b24982cad.PNG)

**Comment by sandwichmaker** [comment]
Observe that the solver says that gradient is zero, which means that something is wrong with the way your derivatives are being computed.

Looking at your functor

```
		cv::Mat rVec(3, 1, CV_64FC1);
		double* rPtr = (double*)rVec.data;
		std::memcpy(&rPtr[0], &w[0], sizeof(double));
		std::memcpy(&rPtr[1], &w[1], sizeof(double));
		std::memcpy(&rPtr[2], &w[2], sizeof(double));
```

is the problem. Where you are blindly copying w which could be a double or a jet into a cv::Mat which is doubles. In the process you are destroying how the autodiff functionality works. I recommend using the functions in ceres/rotation.h

if you are casting to or from the template typed T, then you are asking for trouble. Have a look at the SnavelyReprojectionError for how to rotate translate and project points.

**Comment by Davar1990** [comment]
I made the following changes and this time the optimization goes through 17 iterations and the error is reduced. But the error is still large and when I visualize the reprojected points they appear as a straight line and not like a human face. 

```
struct ProjectionError {
	
	ProjectionError(const easy3d::vec3& vert, const cv::Point2d& lm, double f, double cx, double cy) {
		_vert = cv::Point3d(vert[0], vert[1], vert[2]);
		_gtLm = lm;
		_f = f;
		_cx = cx;
		_cy = cy;
	}

	template <typename T>
	bool operator()(const T* const w, T* residual) const {
		
		//------------- rotation
		T vert[3] = { T(_vert.x), T(_vert.y), T(_vert.z) };
		T rotatedVert[3];
		ceres::AngleAxisRotatePoint(w, vert, rotatedVert);
		
		//------------- translation
		rotatedVert[0] += w[3]; 
		rotatedVert[1] += w[4]; 
		rotatedVert[2] += w[5];

		//------------- reprojection
		T xp = rotatedVert[0] / rotatedVert[2];
		T yp = rotatedVert[1] / rotatedVert[2];
		T predicted_x = T(_f) * xp + T(_cx);
		T predicted_y = T(_f) * yp + T(_cy);

		//------------- residual
		residual[0] = T(_gtLm.x) - predicted_x;
		residual[1] = T(_gtLm.y) - predicted_y;

		return true;
	}

private:
	cv::Point3d     _vert;
	cv::Point2d     _gtLm;
	double			_f;
	double			_cx;
	double			_cy;
};

```
![Capture](https://user-images.githubusercontent.com/17028943/143508992-17447604-be45-4f41-8623-e514997f38d5.PNG)

**Comment by sandwichmaker** [comment]
Now the problem has to do with the mathematical model you are optimizing.
Also remember Ceres can only find a local minima.

**Comment by Davar1990** [comment]
Because the final cost is around 140, I thought it was too large of an error and there should be something wrong. But, inside the functor, I printed the reprojected points next to their ground truth landmarks. 

```
		//------------- reprojection
		T xp = rotatedVert[0] / rotatedVert[2];
		T yp = rotatedVert[1] / rotatedVert[2];
		T predicted_x = T(_f) * xp + T(_cx);
		T predicted_y = T(_f) * yp + T(_cy);

		cout << "grnd_x = " << _gtLm.x << ", grnd_y = " << _gtLm.y << endl;
		cout << "pred_x = " << predicted_x << ", pred_y = " << predicted_y << endl << endl;
		
		//------------- residual
		residual[0] = T(_gtLm.x) - predicted_x;
		residual[1] = T(_gtLm.y) - predicted_y;
```
In the final iterations the values are very close to the ground truth landmarks. 

![Capture](https://user-images.githubusercontent.com/17028943/143513438-4136ef55-3a9e-4e95-b08a-e1c6fa90553c.PNG)

So I believe it's actually working pretty well. I will look into my visualization function when I get a chance and will confirm the results so this issue can be closed as resolved. Thanks for your help.

**Comment by sandwichmaker** [comment]
Awesome.
