### ISSUE TITLE
Ceres CMakeFile is picking up the wrong version of glog

### ISSUE THREAD

**Issue by trzy** [ceres-solver/ceres-solver#731]
I'm trying to build ceres but I think it is picking up the wrong location of glog, which I suspect is leading to a dependency on a non-existent libglog.so.1 being created. Here is what happens when I run cmake:

```
-- Found exported glog build directory: /home/bart/projects/ADOP/build/External/saiga/submodules/glog
```
This is wrong. I installed libgoogle-glog-dev already and it is not being picked up. Is there a magic cmake incantation to fix this? Thank you :)

**Comment by trzy** [comment]
Fixed: had to use -DGLOG_PREFER_EXPORTED_GLOG_CMAKE_CONFIGURATION=FALSE when running cmake. 

I do wish someone could explain how that ADOP path even got picked up in the first place?

**Comment by alexsmac** [comment]
The distinction is that projects built with CMake can optionally export their build directories to the user's CMake cache as well as (optionally) installing themselves to a specified location.  In this case, glog must have been exported when it was built.  By default, CMake checks the user's package cache as part of each `find_package()` call which is how it was detected when Ceres invokes `find_package(glog)`.

We discuss this in more detail [here](http://ceres-solver.org/installation.html#installing-a-project-with-cmake-vs-exporting-its-build-directory) in the Ceres docs, as Ceres is also able to export its build directory s/t it can be found (without installation) by other projects, but we do not do so by default.
