### ISSUE TITLE
 cannot declare variable ‘log’ to be of abstract type ‘testing::ScopedMockLog’

### ISSUE THREAD

**Issue by Lightolx** [ceres-solver/ceres-solver#735]
"ScopedMockLog" is a derived class of "LogSink", but it doesn't override the pure virtual function "send()", the 5th parameter of LogSink::send() is of type "LogMessageTime", while the 5th parameter of ScopedMockLog::send() is of type "tm". How to solve the problem
![1](https://user-images.githubusercontent.com/24823307/145981484-bd6e3711-fa5e-4aea-a9b3-3863ed56e59b.png)
![2](https://user-images.githubusercontent.com/24823307/145981494-faff1061-87e6-4e5a-9a74-a9d831f4ed9f.png)
![3](https://user-images.githubusercontent.com/24823307/145981498-3941db24-0b53-4640-bb0c-d5f72cc7266f.png)
?

**Comment by sergiud** [comment]
You are using a development version of glog. Please switch to a release version.

You should also report the issue on the glog issue tracker since the API changed only recently. Glog should ideally provide a method overload to avoid breaking the API too much.
