### ISSUE TITLE
Why is the weighted residual and Jacobian of identity matrix better when using Markov distance for optimization

### ISSUE THREAD

**Issue by 1ADZX** [ceres-solver/ceres-solver#736]
When using Ceres, I use Mahalanobis distance to build the least squares problem, so when I build the factor. Using sqrt_ Info weights the residual and the Jacobian of the corresponding state quantity, sqrt_ Info is obtained by LLT decomposition of the information matrix, and the code is as follows.
-------------------------------code------------------------------------------------------------------------------------------------
ProjectionFactor_onlyPose::sqrt_info =  Eigen::LLT<Eigen::Matrix2d>(ProjectionFactor_covariance.inverse()).matrixL().transpose();
--------------------------
bool ProjectionFactor_onlyPose::Evaluate(double const *const *parameters, double *residuals, double **jacobians) const{   
     ...
     residual = sqrt_info * residual;
if(jacobians){
      ...
  reduce << dU_dfsj_c, dV_dfsj_c;
  reduce = sqrt_info * reduce;
   if(jacobians[0]){
            
           Eigen::Map<Eigen::Matrix<double, 2, 7, Eigen::RowMajor>> jacobian_pose_i(jacobians[0]);
            Eigen::Matrix<double, 3, 6>jaco_i;

         ...

          jacobian_pose_i.leftCols<6>() = reduce * jaco_i;
            jacobian_pose_i.rightCols<1>().setZero();
      }

if(jacobians[1]){
           
           Eigen::Map<Eigen::Matrix<double, 2, 7, Eigen::RowMajor>> jacobian_pose_j(jacobians[1]);

            Eigen::Matrix<double, 3, 6>jaco_j;
            ...
            jacobian_pose_j.leftCols<6>() = reduce*jaco_j;
           jacobian_pose_j.rightCols<1>().setZero();

        }
if(jacobians[2]){
            Eigen::Map<Eigen::Vector2d> jacobian_feature(jacobians[2]);/
         ...
          jacobian_feature = reduce * ris.transpose() * Rj.transpose() * Ri * ris * dfsi_dtheta;
            
       }}

---------------------------------------------------------------end
-------------------------------------------------------------------------------------------------------------------------------------------

My question is, why is sqrt_info an identity matrix,projectionfactor_ onlyPose::sqrt_ info = Eigen::Matrix2d::Identity();

The optimization results are much better than the above results

**Comment by sandwichmaker** [comment]
@1ADZX I am not really sure what you are asking. Also your question is very poorly formatted making it quite hard to understand, I suspect this is because of markdown formatting. 

My sense is that you are trying to figure out how to model your problem and thats more a question about how to formulate problems rather than how to solve them using ceres.

**Comment by 1ADZX** [comment]
> @1ADZX I am not really sure what you are asking. Also your question is very poorly formatted making it quite hard to understand, I suspect this is because of markdown formatting.
> 
> My sense is that you are trying to figure out how to model your problem and thats more a question about how to formulate problems rather than how to solve them using ceres.

I'm sorry I didn't describe the problem clearly. I'll rearrange the problem as follows
The project I optimized with Ceres is Mahalanobis distance，that is, the form of r^t*P^(-1)*r，where P is the corresponding covariance.
Considering Ceres, the form of least squares optimization is min {e ^ t * e}.So I need to do an LLT decomposition of P ^ (- 1), that is, P ^ (- 1) = L * L ^ t.
Then the above Mahalanobis distance d = r^t*(L*L^t)^(-1)*r=(L^t*r)^t * (L^t*r)
Let e = L ^ t * r be the new optimization residual, that is, the corresponding code above is residual = sqrt_ info * residual;
Here, the matrix(sqrt_info) represents L ^ t.
At the same time, I also multiply the Jacobian in the iterative process by this value, such as reduce = sqrt_ info * reduce; jacobian_ pose_ i.leftCols<6>() = reduce * jaco_ i;
However, through the optimization results, I found that when the matrix(sqrt_info) is an identity matrix, the result is actually better than the matrix(sqrt_info) obtained by LLT decomposition
The covariance matrix used to obtain the matrix(sqrt_info) conforms to the theoretical derivation, and the elements and values are correct.
Therefore, I would like to ask why this matrix(sqrt_info) is an identity matrix and the result obtained is better than that when I use the covariance matrix for LLT decomposition. What are the reasons for this? The effect of the identity matrix is even better than that when I consider covariance.Thank you very much

**Comment by sandwichmaker** [comment]
There are two things one must consider when evaluating the result of an optimization problem.

The first has to do with modeling the problem. This is where accounting for the right mahalanobis distance comes in. 
The second has to do with the fact that generally speaking the solver will find a locally optimal solution.

The fact that you are not getting as good a solution as you want, can be because you did not model the problem correctly and/or the solver was unable to find a better solution. It is near impossible to say which without looking at the problem more closely. For the former it is worth looking at what you are trying to model and how. For the latter it is worth looking at the conditioning of the problem (which will cause the solver to make very slow progress) and better initialization which will get the starting point closer to the solution you are interested in.

I am sorry if this sounds like a vague answer, but this really is how non-linear optimization is done.

**Comment by 1ADZX** [comment]
> There are two things one must consider when evaluating the result of an optimization problem.
> 
> The first has to do with modeling the problem. This is where accounting for the right mahalanobis distance comes in. The second has to do with the fact that generally speaking the solver will find a locally optimal solution.
> 
> The fact that you are not getting as good a solution as you want, can be because you did not model the problem correctly and/or the solver was unable to find a better solution. It is near impossible to say which without looking at the problem more closely. For the former it is worth looking at what you are trying to model and how. For the latter it is worth looking at the conditioning of the problem (which will cause the solver to make very slow progress) and better initialization which will get the starting point closer to the solution you are interested in.
> 
> I am sorry if this sounds like a vague answer, but this really is how non-linear optimization is done.

Thank you very much for your detailed reply. I directly expressed the model of minimum residual in polar coordinates, and then combined with the Mahalanobis distance established by covariance in polar coordinates to solve the previous problem. At the beginning, I had the covariance in the polar coordinate system, but I first established the residual in the Cartesian system, and deduced the covariance in the polar coordinate system into the Cartesian system through variance and other formulas. But obviously, the covariance obtained in this way is obviously not good.
Although I still don't know why the corresponding covariance result under Cartesian system is not good, I know that under the existing covariance matrix, it's best to directly establish the residual model of corresponding variables. I don't know whether my so-called experience is appropriate.
