### ISSUE TITLE
error: 'CERES_GET_FLAG’ was not declared in this scope

### ISSUE THREAD

**Issue by SumoBBQ** [ceres-solver/ceres-solver#738]
Hi, I try to compile the **examples/powell.c** using Cmake in a separate project, and I place two below files in one folder: 
1) CMakeList.txt
> cmake_minimum_required(VERSION 2.5)
>project(powell)
>find_package(Ceres REQUIRED)
>add_executable(powell powell.cpp)
>target_link_libraries(powell Ceres::ceres gflags)
2) powell.c

Running `cmake .` is fine, but after running `make` above error is appeared”. Can someone help me please. 
![Screenshot from 2021-12-29 16-16-06](https://user-images.githubusercontent.com/18181691/147646261-fac4c3ba-8a3d-455d-9129-47bd9dd71b52.png)

**Comment by sandwichmaker** [comment]
CERES_GET_FLAG is defined in ceres/internal/port.h I am not sure why you are not getting it in your build. @alexsmac do you know?

**Comment by SumoBBQ** [comment]
@sandwichmaker Oh, thanks for your info. I think it's somehow weird because I search for the port.h **in my lap** and don't see any #define of CERES_GET_GLAG (ceres 2.0.0 downloaded from official website) (see pic below).

![Screenshot from 2021-12-30 08-54-58](https://user-images.githubusercontent.com/18181691/147715804-2500ed88-db53-4361-9430-203a17fd5f57.png)

but in the port.h **in GitHub** CERES_GET_FLAG is defined (see pic below).

![Screenshot from 2021-12-30 08-54-33](https://user-images.githubusercontent.com/18181691/147715809-7387259e-30fe-4e1e-8893-643e3f6c0094.png)

**Comment by SumoBBQ** [comment]
Update: Everything is ok now. I just inserted #define CERES_GET_FLAG into port.h. Thanks for your help @sandwichmaker
