### ISSUE TITLE
Problem when using ceres in "Debug" model on windows 10.

### ISSUE THREAD

**Issue by XJTUbopenghui** [ceres-solver/ceres-solver#743]
I successfully install ceres on my laptop.
The environments are windows 10, visual studio 2022, ceres-solver-2.0.0, eigen-3.4.0, gflags, glog and suitesparse-metis-for-windows.
It works ok under release model, while it meets some problem when working under debug model.
The error is that "problem_impl.cc:286] Check failed: num_parameter_blocks == cost_function->parameter_block_sizes().size() (2 vs. 18446744073709551256) ".

Did anyone meet this problem? I need some help now.

**Comment by sandwichmaker** [comment]
There is a bug in your code. Uninitialized memory maybe. Hard to say more
without looking at your code.

**Comment by sandwichmaker** [comment]
closing because of no response.
