### ISSUE TITLE
Covariance between residual blocks?

### ISSUE THREAD

**Issue by YangRiverJiang** [ceres-solver/ceres-solver#757]
Hi there,

I am a one-day-level starter of Ceres. After reading the docs and some examples, I have a question.
I noticed that when observations being fitted to x have a covariance matrix not equal to the identity, the user should apply a cost function with a scale of the inverse square root of the covariance matrix. That's really great, but how should I consider the non-identity covariances between different blocks, i.e., ResidualBlocks? This is often important for my application involved in multiple time-correlated time series, and it can be pretty expensive to merge these time-based blocks.
Thank you in advance for your help!

Best,
River

**Comment by sandwichmaker** [comment]
River there is no way in the ceres API to define the covariance between residual blocks. This means you have a fully dense Jacobian. How large are your problems in terms of number of variables and number of residuals?

**Comment by YangRiverJiang** [comment]
Thanks for the reply. For data of one hour, my problems are roughly 10,000 variables against 150,000 residuals. For each residual block, there are ~40 residuals, which are correlated to the ~40 residuals of the next block. Since it is to be implemented in real-time with the sensor, extending the past residual block is painful.
If it is not possible, my problem still can solve but not that accurate in terms of the covariances of the parameters. Thanks for your help.
