### ISSUE TITLE
Add support for GPU based iterative solvers.

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#760]
cc: @joydeep-b

**Comment by sandwichmaker** [comment]
cc: @jy

**Comment by sandwichmaker** [comment]
cc: @joydeep-b

**Comment by S-o-T** [comment]
Is there an ETA available? Would be interesting to compare with https://github.com/MegviiRobot/MegBA

**Comment by joydeep-b** [comment]
Work is under way: https://ceres-solver-review.googlesource.com/c/ceres-solver/+/21940

**Comment by joydeep-b** [comment]
CUDA CGNR Is now merged into master: 829089053e261f056dd72cd8c74e4c19ac445924
@sandwichmaker Let's close this issue and create new ones for the targeted follow-up items we discussed.
