### ISSUE TITLE
When using Ceres for nonlinear optimization, it works normally when optimizing 5 frames of data; When optimizing 6 or more frames of data, the optimization fails

### ISSUE THREAD

**Issue by 1ADZX** [ceres-solver/ceres-solver#763]
**Data description**:There are 15 common viewpoints in 5 consecutive frames of data;
                            There is no common viewpoint between the 6th frame data and the previous 5 frames data, and they are 15 feature 
                            points observed again;
I conducted nonlinear optimization based on the re projection error for the pose of these frames of data, but found that the above five frames of data can be subject to normal nonlinear optimization. After adding the sixth frame of data, the optimization failed, and the error is reported as follows:
--------------------------------------------------------------------------------------------------------------------------------------------------
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0228 15:31:32.364823  9859 residual_block.cc:131] 

Error in evaluating the ResidualBlock.

There are two possible reasons. Either the CostFunction did not evaluate and fill all    
residual and jacobians that were requested or there was a non-finite value (nan/infinite)
generated during the or jacobian computation. 

Residual Block size: 3 parameter blocks x 2 residuals

For each parameter block, the value of the parameters are printed in the first column   
and the value of the jacobian under the corresponding residual. If a ParameterBlock was 
held constant then the corresponding jacobian is printed as 'Not Computed'. If an entry 
of the Jacobian/residual array was requested but was not written to by user code, it is 
indicated by 'Uninitialized'. This is an error. Residuals or Jacobian values evaluating 
to Inf or NaN is also an error.  

Residuals:          7.38029      1.69365 

Parameter Block 0, size: 4

    0.996067 |         -nan         -nan 
  -0.0300342 |         -nan         -nan 
  -0.0493301 |         -nan         -nan 
  -0.0671961 |         -nan         -nan 

Parameter Block 1, size: 3

    -20.0864 | Not Computed  Not Computed  
    -5.85186 | Not Computed  Not Computed  
    -7.55326 | Not Computed  Not Computed  

Parameter Block 2, size: 3

      19.814 |         -nan         -nan 
     8.13496 |         -nan         -nan 
     5.99895 |         -nan         -nan 

E0228 15:31:32.364987  9859 trust_region_minimizer.cc:72] Terminating: Residual and Jacobian evaluation failed.
Ceres Solver Report: Iterations: 0, Initial cost: -1.000000e+00, Final cost: -1.000000e+00, Termination: FAILURE
-----------------------------------------------------------------------------------------------------------------------------------------
I don't know why this happens. The optimization can work normally when there are 5 frames of data, which shows that I have a correct cost_function, and the Ceres:: problem construction is correct. Why does the optimization fail when there is one more frame 6 data.Thank you very much for your help

**Comment by sandwichmaker** [comment]
This has nothing to do with number of images. You have a cost function which is being fed values

0.996067,  -0.0300342,  -0.0493301 ,  -0.0671961
-20.0864,  -5.85186, -7.55326 
 19.814,  8.13496,  5.99895

and is generating nans when computing the jacobians. so you should look at your code for computing the jacobians to see what might be giving rise to the nans.

**Comment by 1ADZX** [comment]
> This has nothing to do with number of images. You have a cost function which is being fed values
> 
> 0.996067, -0.0300342, -0.0493301 , -0.0671961 -20.0864, -5.85186, -7.55326 19.814, 8.13496, 5.99895
> 
> and is generating nans when computing the jacobians. so you should look at your code for computing the jacobians to see what might be giving rise to the nans.

I also think it has nothing to do with my feature tracking image.
But when I calculate Jacobi, I use Ceres's automatic derivation method, ceres:: Autodiffcostfunction. In this case, how can I view the code for calculating the Jacobian matrix?

**Comment by sandwichmaker** [comment]
I suggest evaluating the cost function on its own and add logging to the cost function to print out the intermediate values.
when automatic differentiation is used, logging the values that are computed will automatically print their derivatives also.
that will tell you where the nans are coming from.

**Comment by 1ADZX** [comment]
> I suggest evaluating the cost function on its own and add logging to the cost function to print out the intermediate values. when automatic differentiation is used, logging the values that are computed will automatically print their derivatives also. that will tell you where the nans are coming from.

Thank you very much for your help. Do you have the corresponding sample code here? To implement a separate evaluation of the cost function, and add the log record to the cost function to print out the intermediate value. At present, my use of Ceres is still at an early stage. I only know the three derivation methods of automatic derivation, numerical derivation and analytical derivation. I really don't know how to evaluate the cost function separately. Thank you again

**Comment by sandwichmaker** [comment]
Going to close this because there is not much to do here.
