### ISSUE TITLE
Dense covariance, fully dense Jacobian

### ISSUE THREAD

**Issue by weisongwen** [ceres-solver/ceres-solver#766]
Hi @sandwichmaker . Thank you very much for sharing such a great package. If the problem to be estimated is sparse for example the SLAM problem, the Solver can be very efficient. But now my problem is dense due to the correlation between the measurements used in my factor graph optimization. Specifically, the covariance of the measurements in my problem is highly correlated leading to a dense covariance matrix. As a result, the Jacobia is also dense. Now, the solver seems to be slow and I am not sure I have correctly select the best solver (e.g. Sparse_QR or Dense QR). Roughtly, I have 1000 residuals and 100 states. 

Q1: Can you kindly please suggest which solver should I use ((e.g. Sparse_QR or Dense QR) in GN, LM, Dogleg) which will be faster in solving my dense problem?

Q2: also when I evaluate the covariance, it is also very slow (10 seconds to get the covariance). I look into the tutorial and I found that only the SPARSE_QR can be used, am I correct or can you please kindly provide some suggestions on this?

Thank you very much for your help,

Best,
Weisong,

**Comment by sandwichmaker** [comment]
That's not a very large Jacobian. You should use denseqr, it should work well. Can you share the output of summary::fullreport()?

**Comment by sandwichmaker** [comment]
@weisongwen  this is using DENSE_SCHUR. Can you report back with DENSE_QR?

**Comment by sandwichmaker** [comment]
DENSE_NORMAL_CHOLESKY may also work for you. I would look into using that too.

**Comment by weisongwen** [comment]
> DENSE_NORMAL_CHOLESKY may also work for you. I would look into using that too.

Hi @sandwichmaker , Thank you very much for your reply. I carefully look into the problem I wish to solve. Finally, I found the most-time consuming part is the covariance calculation. Firstly, the brief report for the solve function is as below:
```
Solver Summary (v 2.0.0-eigen-(3.3.7)-lapack-suitesparse-(5.1.2)-cxsparse-(3.1.9)-eigensparse-no_openmp)

                                     Original                  Reduced
Parameter blocks                          690                      414
Parameters                               6900                     6072
Residual blocks                          8156                     8156
Residuals                               11298                    11298

Minimizer                        TRUST_REGION

Sparse linear algebra library    SUITE_SPARSE
Trust region strategy                  DOGLEG (TRADITIONAL)

                                        Given                     Used
Linear solver          SPARSE_NORMAL_CHOLESKY   SPARSE_NORMAL_CHOLESKY
Threads                                     8                        8
Linear solver ordering              AUTOMATIC                      414

Cost:
Initial                          5.845965e+12
Final                            2.068673e+03
Change                           5.845965e+12

Minimizer iterations                       18
Successful steps                           18
Unsuccessful steps                          0

Time (in seconds):
Preprocessor                         0.002773

  Residual only evaluation           0.011915 (18)
  Jacobian & residual evaluation     0.045564 (18)
  Linear solver                      0.269126 (18)
Minimizer                            0.352833

Postprocessor                        0.000338
Total                                0.355944

Termination:                      CONVERGENCE (Parameter tolerance reached. Relative step_norm: 9.575940e-09 <= 1.000000e-08.)
```
The setup of my solver is as below:
```
options.use_nonmonotonic_steps = false;
options.linear_solver_type = ceres::SPARSE_NORMAL_CHOLESKY;// how to solve the incremental equation
options.trust_region_strategy_type = ceres::DOGLEG;
```
Finally, I found that the solver itself is already very efficient. But the covariance spends about 8 seconds to get the covariance. I am thinking that the covariance estimation requires calculating the full jacobian concerning all the states which can be time-consuming. Do you have any suggestions on accelerating the covariance estimation? Following is the setup of the covariance estimation (default, the sparse_QR will be used for the covariance estimation).
```
ceres::Covariance::Options cov_options;
cov_options.apply_loss_function = true;
```
Also, I found that the Cuda is supported in latest Ceres-solver, do you think this can accelerate the calculation?

Looking forward to your reply and suggestions :-)
Best,
Weisong,

**Comment by weisongwen** [comment]
> @weisongwen this is using DENSE_SCHUR. Can you report back with DENSE_QR?

if the dense_QR is selected, the time used increases by several times as below:
```
Solver Summary (v 2.0.0-eigen-(3.3.7)-lapack-suitesparse-(5.1.2)-cxsparse-(3.1.9)-eigensparse-no_openmp)

                                     Original                  Reduced
Parameter blocks                          195                      117
Parameters                               1950                     1716
Residual blocks                          2300                     2300
Residuals                                3187                     3187

Minimizer                        TRUST_REGION

Dense linear algebra library            EIGEN
Trust region strategy                  DOGLEG (TRADITIONAL)

                                        Given                     Used
Linear solver                        DENSE_QR                 DENSE_QR
Threads                                     8                        8
Linear solver ordering              AUTOMATIC                      117

Cost:
Initial                          5.846495e+12
Final                            6.315795e+02
Change                           5.846495e+12

Minimizer iterations                       28
Successful steps                           12
Unsuccessful steps                         16

Time (in seconds):
Preprocessor                         0.018134

  Residual only evaluation           0.004033 (28)
  Jacobian & residual evaluation     0.034526 (12)
  Linear solver                     21.456960 (12)
Minimizer                           21.772092

Postprocessor                        0.000049
Total                               21.790275

Termination:                      CONVERGENCE (Parameter tolerance reached. Relative step_norm: 8.639065e-09 <= 1.000000e-08.)
```

**Comment by sandwichmaker** [comment]
You are right, I misread the dimensions. DENSE_NORMAL_CHOLESKY is likely going to give you better performance than SPARSE_NORMAL_CHOLESKY. 

As for covariance, I suspect there is no simple way of accelerating it. I think the fastest option for you is going to be SPARSE_QR with SUITE_SPARSE as the backend. Please make sure thats the case. You maybe accidentally using EIGEN_SPARSE, which is quite slow.

we do not have any gpu acceleration for covariance computation yet, though this maybe worth exploring by running rank revealing dense_qr on the GPU which can be quite fast.

cc: @joydeep-b this maybe worth looking at.

**Comment by weisongwen** [comment]
Hi @sandwichmaker , Thank you very much for your reply. I will look into those options and let you know if I got further updates. 

Best,
Weisong,

**Comment by sandwichmaker** [comment]
Closing for now, if you have further questions/comments feel free to re-open.
