### ISSUE TITLE
The expression of residual[0]

### ISSUE THREAD

**Issue by Eric-JH** [ceres-solver/ceres-solver#767]
&ensp;&ensp;&ensp;&ensp;I want to estimate the parameters of gamma distribution using simulated data. According to the code given by [Curve Fitting](http://www.ceres-solver.org/nnls_tutorial.html#curve-fitting), I wrote the following code.  
&ensp;&ensp;&ensp;&ensp;Then the error was reported because the unproper expression of residual[0]. I should use `ceres::pow` instead of `std::pow`. But what bothered me is there is no `ceres::tgamma` to replace `std::tgamma`. How can I solve the problem?
```
#include <cmath>
#include <ceres/ceres.h>

using namespace std;
using namespace ceres;
struct GammaResidual
{
	GammaResidual(double x, double y) : x_(x), y_(y) {}
	/*
	template <typename T>
	bool operator()(const T* const alpha, const T* const beta, T* residual) const
	{
		residual[0] = y_ - pow(x_, alpha[0] - 1) / exp(x_ / beta[0]) / (tgamma(alpha[0]) * pow(beta[0], alpha[0]));
		return true;
	}

private:
	const double x_;
	const double y_;
};

int main()
{
	double p[20] = {0.0};
	for (int i = 0; i < 20; i++)
	{
		double a = pow(double(i), 2.0 - 1) * exp(double(i) / 2.0);
		p[i] = i % 2 ? double(i) : double( a / (tgamma(2.0) * pow(2.0, 2.0)));
	}

	double alpha = 0.0, beta = 0.0;
	Problem problem;
	for (int i = 0; i < 40; i++)
	{
		CostFunction* cost_function = new AutoDiffCostFunction<GammaResidual, 1, 1, 1>(
			new GammaResidual(p[2 * i], p[2 * i + 1]));
		problem.AddResidualBlock(cost_function, nullptr, &alpha, &beta);
	}
}
```

**Comment by sandwichmaker** [comment]
@Eric-JH for this code (automatic differentiation to work), we will need an implementation of ceres:tgamma, which in turn would require an implementation of the polygamma function, which I believe is not part of the c++ standard library. 

The simplest thing to do would be to use numeric differentiation in this case. A more complicated thing to do would be to implement your own templated function that evaluates tgamma and its derivative using another library say boost.
