### ISSUE TITLE
Docs search broken?

### ISSUE THREAD

**Issue by patrikhuber** [ceres-solver/ceres-solver#770]
Sorry if this is just me, but I tried on three browsers / two devices, and without ad-blocker. I think the search on the docs pages might be broken? It just gives me "Searching...".

There is one error in the JavaScript console. I think it might be related, as it occurs in searchtools.js, at the very start of the `  query : function(query)` function.

![image](https://user-images.githubusercontent.com/4967343/158081444-1ff6d3e3-5285-44af-9e67-7b5be40d4c98.png)

I hope this isn't some embarrassing mistake of mine!

**Comment by patrikhuber** [comment]
I think it's not just me - it looks like an update to the Sphinx/RTD theme might be needed: https://github.com/sphinx-doc/sphinx/issues/8623

**Comment by sandwichmaker** [comment]
@patrikhuber thanks for reporting, I will update the website once 2.1 is out, (we don't maintain multiple versions of the doc) and that should fix this automatically I think. I will keep this bug open till then.

**Comment by patrikhuber** [comment]
Okay cool!

Yes I was actually just searching for the documentation of Manifold, and didn't find one of those cool version switcher dropdowns on the Ceres docs :) I found some useful comments in `manifold.h` for now.

**Comment by sandwichmaker** [comment]
If you know how to do the version switcher thing, I won't mind doing that TBH. But I have not invested too much into sphinx-doc so  I am a bit of a newbie. Any help there is appreciated.

**Comment by patrikhuber** [comment]
I don't know more about it either unfortunately - I'm still running plain old Doxygen on my projects. It's on my distant to-do list to have a closer look at sphinx-doc, but perhaps one of those items that I might never get to.

**Comment by patrikhuber** [comment]
The docs search works again!

**Comment by sandwichmaker** [comment]
Thanks for verifying!
