### ISSUE TITLE
Rank defficient matrix with EIGEN_SPARSE_QR algorithm for covariance computation

### ISSUE THREAD

**Issue by nicochampda** [ceres-solver/ceres-solver#777]
Hi,
I'm trying to compute covariance with the algorithm EIGEN_SPARSE_QR. 
With some conditions I get a Rank deficient error and I think it is due to the pivot threshold that is to low. 
Unfortunately, it is not possible to change this threshold via ceres interface, the eigen function is not callable.

In my case it would help to use the setPivotThreshold function from eigen, to change the threshold (see in the code
https://github.com/ceres-solver/ceres-solver/blob/ab9436cb9e67139f7dbee2f97d728f5b2f71630b/internal/ceres/covariance_impl.cc#L841). Cf eigen documentation : "If it failed, it usually helps to increase the threshold with setPivotThreshold."

Thanks

**Comment by sandwichmaker** [comment]
This is a good idea.  I will add this once 2.1 is released.

**Comment by sandwichmaker** [comment]
@nicochampda could you try out https://ceres-solver-review.googlesource.com/c/ceres-solver/+/21400 and let me know if this does the trick for you?
