### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by daydream-noquitter** [ceres-solver/ceres-solver#781]
when I run "make -j3"
/home/fan/ceres-solver-2.0.0/internal/ceres/covariance_impl.cc: In member function ‘bool ceres::internal::CovarianceImpl::ComputeCovarianceValuesUsingDenseSVD()’:
/home/fan/ceres-solver-2.0.0/internal/ceres/covariance_impl.cc:743:10: error: ‘BDCSVD’ is not a member of ‘Eigen’
   Eigen::BDCSVD<Matrix> svd(dense_jacobian,
          ^~~~~~
/home/fan/ceres-solver-2.0.0/internal/ceres/covariance_impl.cc:743:23: error: expected primary-expression before ‘>’ token
   Eigen::BDCSVD<Matrix> svd(dense_jacobian,
                       ^
/home/fan/ceres-solver-2.0.0/internal/ceres/covariance_impl.cc:743:25: error: ‘svd’ was not declared in this scope
   Eigen::BDCSVD<Matrix> svd(dense_jacobian,
                         ^~~
[ 18%] Building CXX object internal/ceres/CMakeFiles/ceres.dir/dense_normal_cholesky_solver.cc.o
[ 18%] Building CXX object internal/ceres/CMakeFiles/ceres.dir/dense_qr_solver.cc.o
internal/ceres/CMakeFiles/ceres.dir/build.make:467: recipe for target 'internal/ceres/CMakeFiles/ceres.dir/covariance_impl.cc.o' failed
make[2]: *** [internal/ceres/CMakeFiles/ceres.dir/covariance_impl.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:226: recipe for target 'internal/ceres/CMakeFiles/ceres.dir/all' failed
make[1]: *** [internal/ceres/CMakeFiles/ceres.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2
It report like this . 
Any help appreciated

**Comment by sandwichmaker** [comment]
What version of Eigen are you using?

**Comment by sandwichmaker** [comment]
Closing because lack of response, please feel free to reopen if you have more information.
