### ISSUE TITLE
Unable to build with c++17/20 on linux 

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#783]
Default build succeeds, but cmake exists with error when CMAKE_CXX_STANDARD=17 or CMAKE_CXX_STANDARD=20.  CMake output is attached.

[CMakeOutput.log](https://github.com/ceres-solver/ceres-solver/files/8357987/CMakeOutput.log)
[CMakeError.log](https://github.com/ceres-solver/ceres-solver/files/8357988/CMakeError.log)

@sergiud any idea what is going on here?

**Comment by sergiud** [comment]
You mean the CMake configuration step fails? Could you provide the output?

**Comment by sandwichmaker** [comment]
it is attached in the report above. I am generating the c++20 version.

**Comment by sandwichmaker** [comment]
[CMakeError.log](https://github.com/ceres-solver/ceres-solver/files/8357999/CMakeError.log)
[CMakeOutput.log](https://github.com/ceres-solver/ceres-solver/files/8358000/CMakeOutput.log)

Here are the c++20 output.

**Comment by sergiud** [comment]
Isn't the `CMakeOutput.log` taken from `CMakeFiles/` after CMake configuration already failed? By CMake output I mean the direct CMake output to stdout.

**Comment by sandwichmaker** [comment]
oops operator error, I misspecified the standard flag as -CMAKE_CXX_STANDARD instead of -DCMAKE_CXX_STANDARD. My bad :/
