### ISSUE TITLE
I made the following errors in compiling

### ISSUE THREAD

**Issue by ydragon719** [ceres-solver/ceres-solver#789]
I made the following errors in compiling:error: 
‘exclusive_scan’ is not a member of ‘std’
     std::exclusive_scan(values.begin(), values.end(), result.begin(), 0);
          ^~~~~~~~~~~~~~
examples/CMakeFiles/helloworld.dir/build.make:75: recipe for target 'examples/CMakeFiles/helloworld.dir/helloworld.cc.o' failed
make[2]: *** [examples/CMakeFiles/helloworld.dir/helloworld.cc.o] Error 1
CMakeFiles/Makefile2:288: recipe for target 'examples/CMakeFiles/helloworld.dir/all' failed
make[1]: *** [examples/CMakeFiles/helloworld.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

How can I solve it

**Comment by sergiud** [comment]
Your compiler does not fully support C++17. Either use Ceres Solver 2.1 or update your toolchain.
