### ISSUE TITLE
dataset.g2o

### ISSUE THREAD

**Issue by pooluut** [ceres-solver/ceres-solver#790]
I'm new to ceres-solver. In the example of pose_graph_2d, where can I find a sample dataset.g2o?

**Comment by sandwichmaker** [comment]
@pooluut we do not ship a dataset.g2o file. @mvitus contributed that code, perhaps he has suggestions.

**Comment by mvitus** [comment]
A couple places to find datasets are:

* https://lucacarlone.mit.edu/datasets/
* https://github.com/OpenSLAM-org/openslam_g2o/tree/master/data
