### ISSUE TITLE
error: ‘exclusive_scan’ is not a member of ‘std’

### ISSUE THREAD

**Issue by XJTUXYC** [ceres-solver/ceres-solver#791]
When I make Ceres, this error occurred:

In file included from /home/xyc/ceres-solver/include/ceres/ceres.h:67:0,
                 from /home/xyc/ceres-solver/examples/rosenbrock_numeric_diff.cc:31:
/home/xyc/ceres-solver/include/ceres/product_manifold.h: In static member function ‘static std::array<T, N> ceres::ProductManifold<Manifold0, Manifold1, ManifoldN>::ExclusiveScan(const std::array<T, N>&)’:
/home/xyc/ceres-solver/include/ceres/product_manifold.h:260:10: error: ‘exclusive_scan’ is not a member of ‘std’
     std::exclusive_scan(values.begin(), values.end(), result.begin(), 0);
          ^~~~~~~~~~~~~~

How can I fix this?

**Comment by sandwichmaker** [comment]
Ceres solver at head now requires c++17.

**Comment by XJTUXYC** [comment]
> 

Thanks a lot!

**Comment by XJTUXYC** [comment]
> Ceres solver at head now requires c++17.

Thanks a lot!
