### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by ishfaq333** [ceres-solver/ceres-solver#792]
Hello everyone.
I was trying to install Ceres-solver. But when using the command make -j3, it works up to 27% and then shows the errors as shown in the screenshot attached herewith.
Can anyone help me understand what's wrong here?

![Screenshot from 2022-04-17 00-12-13](https://user-images.githubusercontent.com/60423184/163687973-aa9bb893-fd5c-4d6c-be77-d286ac26a52b.png)

**Comment by sergiud** [comment]
Your setup looks broken.

**Comment by ishfaq333** [comment]
> Your setup looks broken.

Any suggestions as to what I should do?

**Comment by sergiud** [comment]
Probably avoid using Anaconda environment.
