### ISSUE TITLE
error: ‘exclusive_scan’ is not a member of ‘std’

### ISSUE THREAD

**Issue by Childish-Gambion** [ceres-solver/ceres-solver#793]
/ceres-solver/ceres-solver/include/ceres/product_manifold.h:260:10: error: ‘exclusive_scan’ is not a member of ‘std’
     std::exclusive_scan(values.begin(), values.end(), result.begin(), 0);
sorry i am so rookie to this.how can i compiling my application with a C++ standard >= 14 specifically? 
thank you so much!!!

**Comment by sergiud** [comment]
This has been discussed before: #791 #789

**Comment by Childish-Gambion** [comment]
so i need to upgrade C++?

**Comment by sergiud** [comment]
Please see the linked issues for possible resolutions, e.g., https://github.com/ceres-solver/ceres-solver/issues/789#issuecomment-1092782441.
