### ISSUE TITLE
Why ceres-solver doesn't perform quaternion normalization in struct QuaternionPlus?

### ISSUE THREAD

**Issue by Cc19245** [ceres-solver/ceres-solver#796]
Hi ! 
I'm confused about this. Why  ceres-solver doesn't perform **quaternion normalization** in struct QuaternionPlus? After each update, isn't the result not a unit quaternion? Therefore it cannot represent rotation.

<img width="438" alt="image" src="https://user-images.githubusercontent.com/82990771/164592934-508ae3ad-3959-439d-a266-2eb6ec1fb8e4.png">

**Comment by sandwichmaker** [comment]
x is a unit quaternion and q_delta is a unit quaternion. Their product is a also a unit quaternion (upto round off).
