### ISSUE TITLE
ceres-solver/2.0.0: can't build with mingw on Windows

### ISSUE THREAD

**Issue by AndreyMlashkin** [ceres-solver/ceres-solver#797]
Package Name/Version: ceres-solver/2.0.0:
Operating System+version: Windows 10
Compiler+version: GCC 11.2, installed with choco
build with conan v1.48.0

relates to https://github.com/conan-io/conan-center-index/issues/10610

actual error:

[ 19%] Building CXX object source_subfolder/internal/ceres/CMakeFiles/ceres.dir/covariance_impl.cc.obj
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles\ceres.dir\covariance_impl.cc.obj: too many sections (55134)
C:\Users\andy\AppData\Local\Temp\ccktloKx.s: Assembler messages:
C:\Users\andy\AppData\Local\Temp\ccktloKx.s: Fatal error: can't write 92 bytes to section .text of CMakeFiles\ceres.dir\covariance_impl.cc.obj: 'file too big'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles\ceres.dir\covariance_impl.cc.obj: too many sections (55134)
C:\Users\andy\AppData\Local\Temp\ccktloKx.s: Fatal error: CMakeFiles\ceres.dir\covariance_impl.cc.obj: file too big

**Comment by alexsmac** [comment]
It looks like we need to add the equivalent of MSVC's `/bigobj` on MinGW, [this CL](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/21480) should do that.  Please give it a try and report back if it fixes your issue

**Comment by sergiud** [comment]
@alexsmac OP is using Ceres 2.0. Is this still necessary for 2.1?

**Comment by alexsmac** [comment]
Good question, but given the classes that it is complaining about in the snippet above didn't change that much in the update to 2.1, my assumption would be yes, as I don't _think_ the changes to visibility would resolve this from what I have read about the issue.  @AndreyMlashkin can you confirm that vanilla 2.1 is broken in the same way as well as whether the CL above (which is > 2.1) addresses the issue.

I don't think we would patch the existing 2.0 release, but the change is sufficiently small that you could always do so in the Conan formulae directly (which you might still want to do for 2.1 assuming that suffers the same issue)

**Comment by sergiud** [comment]
You are probably right. Just comparing against [msys2 provided 32-bit package](https://github.com/msys2/MINGW-packages/tree/7db4218249ae81ae7e9b6ce7865cd54760f81cf6/mingw-w64-ceres-solver) of Ceres Solver 2.1, however, does not indicate that a MinGW patch is actually necessary.

**Comment by alexsmac** [comment]
From what I have read, this problem may be specifically for 64-bit builds,
I don’t know how accurate that is though and I have never used MinGW

**Comment by AndreyMlashkin** [comment]
I have a slight different error message after applying the patch:
```
[ 19%] Building CXX object source_subfolder/internal/ceres/CMakeFiles/ceres.dir/covariance_impl.cc.obj
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles\ceres.dir\covariance_impl.cc.obj: section .xdata$_ZNK5Eigen8internal15BlockImpl_denseIKNS_9TransposeIKNS_13CwiseBinaryOpINS0_17scalar_product_opIddEEKNS_14CwiseNullaryOpINS0_18scalar_constant_opIdEEKNS_6MatrixIdLi1ELin1ELi1ELi1ELin1EEEEEKNS2_IKNS_5BlockIKNSE_IKNS2_INSE_INS9_IdLin1ELin1ELi0ELin1ELin1EEELin1ELin1ELb0EEEEELin1ELi1ELb0EEELin1ELi1ELb0EEEEEEEEELin1ELi1ELb0ELb0EE8startColEv: string table overflow at offset 10000214
C:\Users\andy\AppData\Local\Temp\ccI4FB5K.s: Assembler messages:
C:\Users\andy\AppData\Local\Temp\ccI4FB5K.s: Fatal error: CMakeFiles\ceres.dir\covariance_impl.cc.obj: file too big
mingw32-make.exe[2]: *** [source_subfolder\internal\ceres\CMakeFiles\ceres.dir\build.make:496: source_subfolder/internal/ceres/CMakeFiles/ceres.dir/covariance_impl.cc.obj] Error 1
```

**Comment by sergiud** [comment]
You should consider upgrading to Ceres 2.1.

@alexmac I've added a [MinGW job](https://github.com/sergiud/ceres-solver/runs/6803334677?check_suite_focus=true) to the Windows workflow and can't reproduce the failures in any of configurations. As such, adding a `/bigobj` equivalent for MinGW does not seem to be necessary.

**Comment by alexmac** [comment]
It's been a while since I used MinGW @sergiud - I think you meant @alexsmac :)

**Comment by sergiud** [comment]
Yes, you are right. Sorry for that.

**Comment by sandwichmaker** [comment]
Is this still an issue?

**Comment by sergiud** [comment]
I don't believe it is. Our Windows Github workflow that runs both 32 and 64 bit MinGW jobs compile without any issues.
