### ISSUE TITLE
Using ceres and GTSAM at the same time, the program is stuck in the update function of the gtsam optimizer and cannot jump out.

### ISSUE THREAD

**Issue by Sonne-Zhu** [ceres-solver/ceres-solver#798]
Hello, I implemented a SLAM algorithm based on factor graph optimization on ubuntu18.04. I used GTSAM4.0.0 and ceres2.0.0 in one node at the same time. After compiling, when the algorithm is executed to the update( of the isam optimizer in gtsam ) function, it will be stuck in the update function and cannot be jumped out, as if it has fallen into an infinite loop, but the program does not report an error. If ceres is not compiled, the update function of gtsam can be used normally. Do you know what is the reason for this, or how to avoid it.

**Comment by sandwichmaker** [comment]
I am hard pressed to think of anything. One wild guess, are you using openmp for threading in both gtsam and Ceres? In that case there maybe some sort of deadlock in the underlying threadpool.
