### ISSUE TITLE
LocalParameterizations cause compilation failure

### ISSUE THREAD

**Issue by 1040624230** [ceres-solver/ceres-solver#802]
I compile the cere's helloworld instance at win10 in VS2022, but there are so many errors and all of that is about 

"error C4996: 'ceres::LocalParameterization': LocalParameterizations will be removed from the Ceres Solver API in version 2.2.0. Use Manifolds instead.". 

help please, and forgive me for my poor grammar

**Comment by hzzg0727** [comment]
Hello. I meet the same problem today, and I solve it by dealing with error C4996 (https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=msvc-170).
The way I use is to close SDL checks like this:
![image](https://user-images.githubusercontent.com/62739713/169276002-88f759ae-457d-428a-9186-61bf73145eca.png)
And it works.
I hope this will help you.

**Comment by 1040624230** [comment]
> Hello. I meet the same problem today, and I solve it by dealing with error C4996 (https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=msvc-170). The way I use is to close SDL checks like this: ![image](https://user-images.githubusercontent.com/62739713/169276002-88f759ae-457d-428a-9186-61bf73145eca.png) And it works. I hope this will help you.

bingo! thanks so much

**Comment by unclesammy** [comment]
> Hello. I meet the same problem today, and I solve it by dealing with error C4996 (https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=msvc-170). The way I use is to close SDL checks like this: ![image](https://user-images.githubusercontent.com/62739713/169276002-88f759ae-457d-428a-9186-61bf73145eca.png) And it works. I hope this will help you.

save my day
