### ISSUE TITLE
Hidden symbol error.

### ISSUE THREAD

**Issue by xuhao1** [ceres-solver/ceres-solver#804]
Hi there,
I am using ceres on my own project. When using v1.x version, everything works fine. After upgrade to 2.1.0, it raises
```bash
/usr/bin/ld: /home/xuhao/swarm_ws/devel/.private/d2vins/lib/d2vins/d2vins_node: hidden symbol `_ZTIN5ceres12CostFunctionE' in /usr/local/lib/libceres.a(cost_function.cc.o) is referenced by DSO
....
```
When compiling my project. One solution is changing CmakeLists of ceres 
```cmake
set(CMAKE_C_VISIBILITY_PRESET hidden)
set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN ON)
```
to 
```cmake
set(CMAKE_C_VISIBILITY_PRESET default)
set(CMAKE_CXX_VISIBILITY_PRESET default)
set(CMAKE_VISIBILITY_INLINES_HIDDEN ON)
```

My question is, why is this case? It looks like in the code(cost_function.cc) CostFunction is already marked as exported.

**Comment by sergiud** [comment]
From your description it is not exactly clear how you upgraded. My guess is that you intermixed several versions of Ceres and only partially upgraded some of the involved projects resulting in the above error. In either case, you need to consistently compile and link against the new version of Ceres in all (even indirect) dependencies.

**Comment by sandwichmaker** [comment]
closing because of lack of response.
