### ISSUE TITLE
Windows CI is broken.

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#808]
cc: @sergiud

**Comment by sergiud** [comment]
SuiteSparse on Windows is built without METIS whereas Ceres assumes METIS is available. Fixing the issue requires some adjustments of the CMake support for SuiteSparse as well as refactoring in Ceres directly since there's no METIS detection mechanism yet.

**Comment by sandwichmaker** [comment]
So for now just add a CERES_NO_METIS to the build? @alexsmac is planning on adding metis detection to the suitesparse cmake files.

**Comment by sergiud** [comment]
`CERES_NO_METIS` is an option, yes but not really necessary. METIS detection/availability indicator needs to be added to CMake SuiteSparse as well. Ideally, we synchronize to further ensure compatibility between `FindSuiteSparse.cmake` and CMake support for SuiteSparse.

I suggest adding a `Partition` component to `find_package (SuiteSparse)`. Its presence will indicate whether CHOLMOD was compiled with METIS support.

**Comment by sandwichmaker** [comment]
Thats fair, my suggestion was only meant as a stop gap while FindSuiteSparse.cmake is modified.

**Comment by sergiud** [comment]
Ah yes. Sounds reasonable.
