### ISSUE TITLE
Nvidia NX ceres2.1.0 build OK, test with error.

### ISSUE THREAD

**Issue by JACKLiuDay** [ceres-solver/ceres-solver#813]
![image](https://user-images.githubusercontent.com/30967867/170614438-38430ba0-8693-4e62-a139-2c94db59c01d.png)
my jetpack is 4.4.1. Nvidia NX, ceres 2.1.0. it looks like something wrong with test. I do know why as I know nothing about cuda.

**Comment by sandwichmaker** [comment]
cc: @joydeep-b can you take a look please?

**Comment by joydeep-b** [comment]
@JACKLiuDay Could you please share the results of running the test in verbose mode:
```
ctest -VV -R cuda_memcheck_dense_qr_test
```

**Comment by JACKLiuDay** [comment]
> @JACKLiuDay Could you please share the results of running the test in verbose mode:
> 
> ```
> ctest -VV -R cuda_memcheck_dense_qr_test
> ```
![Uploading image.png…]()

Hi, thank you for your reply. Here is my test.

**Comment by joydeep-b** [comment]
Correction: please use 
https://ceres-solver-review.googlesource.com/c/ceres-solver/+/21761

**Comment by JACKLiuDay** [comment]
> @JACKLiuDay Thanks, would you mind trying out this patch? https://ceres-solver-review.googlesource.com/c/ceres-solver/+/21760

Thank you for your reply.I just got back from vacation and I will try this patch with my classmate

**Comment by JACKLiuDay** [comment]
> Correction: please use https://ceres-solver-review.googlesource.com/c/ceres-solver/+/21761

Hi，I tried the solution while it still shows some error.
![微信图片_20220610154353](https://user-images.githubusercontent.com/30967867/173016326-f203ceda-53ab-4323-9ee6-8a392b7d7f8c.jpg)
![微信图片_20220610154346](https://user-images.githubusercontent.com/30967867/173016370-cb8158f2-accf-4b62-b274-cfdc441b42b1.jpg)
By the way, I did not install cuda toolkit or any  other cuda software. Just pure jetpack 4.4.1 installed.  After completing the jet 4.4.1 installation, we installed and tested ceres2.1. I do not know if we need to install other cuda component or dependency for the test.

**Comment by joydeep-b** [comment]
I see that it is still referring to `cuda-memcheck`, but in the latest patch it calls a full path.
I'm guessing this is still running the old patch. The latest version actually won't compile on linux until [21700](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/21700) is merged in.
Also, I see that you have a file write permissions issue that is unrelated to build issues - you should check what is going on there.

**Comment by joydeep-b** [comment]
As a workaround for now, you can specify the Cuda path in your environment variables as described in the post-installation steps of the Cuda installation guide:
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#environment-setup

**Comment by HomieRegina** [comment]
> As a workaround for now, you can specify the Cuda path in your environment variables as described in the post-installation steps of the Cuda installation guide:https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#environment-setupMake sure you modify it based on the version of L4T you are running.Here are my path configs on a Xavier AGX, for reference:
> 
> ```
> export PATH=/usr/local/cuda-10.2/bin:$PATH
> export LD_LIBRARY_PATH=/usr/local/cuda-10.2/lib64:$LD_LIBRARY_PATH
> ```

Hi, I tried the modified Ceres path and modefied the CUDA path configs, but still encountered the same issue.My board is Nvidia NX with jetpack 4.4.1. cuda 10.2.89.
![1](https://user-images.githubusercontent.com/107244263/173317218-468b95a2-c1be-4063-a628-88f2d8825e7d.jpg)

![2](https://user-images.githubusercontent.com/107244263/173317232-efc98fd0-4482-4342-bc0e-eb08544be6b4.jpg)

**Comment by joydeep-b** [comment]
No, it should be fine, as long as you did manage to successfully compile it with CUDA. However I'm not sure how you were able to compile it with CUDA without installing the CUDA toolkit.

**Comment by HomieRegina** [comment]
> 

Hi, I have installed cuda10.2. In addition to CUDA toolkit, which dependent libraries do I need to install?
![4b514e742b98403ba95e48ebcbaf5c4](https://user-images.githubusercontent.com/107244263/173475771-d4144c66-ee74-437f-8fcf-64d8408e0b6e.jpg)

![aadf7eee5ebd308c0bce33b6527e028](https://user-images.githubusercontent.com/107244263/173475781-c67c19fc-53e0-4bd3-8b72-ffb9a4eec42a.jpg)

![6afb6ca53221405570ce1da972946d2](https://user-images.githubusercontent.com/107244263/173475807-09f32680-3335-4923-95ba-b5cbe8b7db69.jpg)
I also found that after modifying the CUDA path, the error changed from 'not run' to 'failed'. I want to know the reason.

**Comment by joydeep-b** [comment]
The last screenshot you shared indicates that you don't have permissions to run cuda in debug mode on the Jetson. You can enable access either by adding your user to the `debug` group, or allowing access to everyone using:
```
sudo chmod 666 /dev/nvhost-dbg-gpu 
```

**Comment by HomieRegina** [comment]
> The last screenshot you shared indicates that you don't have permissions to run cuda in debug mode on the Jetson. You can enable access either by adding your user to the `debug` group, or allowing access to everyone using:
> 
> ```
> sudo chmod 666 /dev/nvhost-dbg-gpu 
> ```

Thank you for your reply. I have successfully made test. Thank you again for your help.
