### ISSUE TITLE
Use C++17 Bessel functions

### ISSUE THREAD

**Issue by sergiud** [ceres-solver/ceres-solver#814]
C++17 introduced many special mathematical functions which could allow to deprecate `BesselJ0`, `BesselJ1`, `BesselJN` and replace these by `std::cyl_bessel_j`. However, in [an effort](https://github.com/ceres-solver/ceres-solver/commit/e3254ed62d09c868e3f38788d525c79e40428662) to do so, it turns out that libc++ does not yet implement the special mathematical functions. Particularly affected are the Apple Clang toolset and NDK which prevent any adaptation at this point.

Related issues: #545 #588

**Comment by sandwichmaker** [comment]
Yeah I suspect this is going to have to wait a while.

**Comment by pagmatt** [comment]
Sorry for interjecting this, do you by any chance have any updates on the support for `std::cyl_bessel_j` in libc++, and thus in Apple Clang? I am experiencing a similar issue
