### ISSUE TITLE
Make error when installing ceres

### ISSUE THREAD

**Issue by kaitaotang** [ceres-solver/ceres-solver#817]
I suffer a error at "make" step. My gcc and g++ version is 11. 
Dear all,  How to solve this error please?

`In file included from /home/tang/tang/Library/ceres-solver-1.14.0/include/ceres/ordered_groups.h:34:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/map:60:
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_tree.h:685:4: error: 
      exception specification of explicitly defaulted move constructor does not
      match the calculated one
          _Rb_tree_impl(_Rb_tree_impl&&)
          ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_tree.h:706:31: note: 
      in instantiation of template class 'std::_Rb_tree<int, std::pair<const
      int, ceres::examples::Pose3d>, std::_Select1st<std::pair<const int,
      ceres::examples::Pose3d> >, std::less<int>,
      Eigen::aligned_allocator<std::pair<const int, ceres::examples::Pose3d> >
      >::_Rb_tree_impl<std::less<int>, true>' requested here
      _Rb_tree_impl<_Compare> _M_impl;
                              ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_map.h:153:17: note: 
      in instantiation of template class 'std::_Rb_tree<int, std::pair<const
      int, ceres::examples::Pose3d>, std::_Select1st<std::pair<const int,
      ceres::examples::Pose3d> >, std::less<int>,
      Eigen::aligned_allocator<std::pair<const int, ceres::examples::Pose3d> >
      >' requested here
      _Rep_type _M_t;
                ^
/home/tang/tang/Library/ceres-solver-1.14.0/examples/slam/pose_graph_3d/pose_graph_3d.cc:67:5: note: 
      in instantiation of template class 'std::map<int, ceres::examples::Pose3d,
      std::less<int>, Eigen::aligned_allocator<std::pair<const int,
      ceres::examples::Pose3d> > >' requested here
    MapOfPoses::iterator pose_begin_iter = poses->find(constraint.id_begin);
    ^
1 error generated.
examples/slam/pose_graph_3d/CMakeFiles/pose_graph_3d.dir/build.make:62: recipe for target 'examples/slam/pose_graph_3d/CMakeFiles/pose_graph_3d.dir/pose_graph_3d.cc.o' failed
make[2]: *** [examples/slam/pose_graph_3d/CMakeFiles/pose_graph_3d.dir/pose_graph_3d.cc.o] Error 1
CMakeFiles/Makefile2:6330: recipe for target 'examples/slam/pose_graph_3d/CMakeFiles/pose_graph_3d.dir/all' failed
make[1]: *** [examples/slam/pose_graph_3d/CMakeFiles/pose_graph_3d.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
tang@tang:~/tang/Library/ceres-solver-1.14.0/build$ 
`

**Comment by sergiud** [comment]
You should probably use Ceres Solver 2.1 instead of version 1.14.

**Comment by kaitaotang** [comment]
> You should probably use Ceres Solver 2.1 instead of version 1.14.

I try Ceres 2.1.0 again. Unfortunately, I encounter the same problem as above.

**Comment by sergiud** [comment]
Could you please post the full CMake and GCC output?

**Comment by kaitaotang** [comment]
Ok,  I use Ceres 2.1.0, Eigen version is 3.3.4, gcc and g++ version is 11.1.0
when "cmake .." step, the terminal is as below:
`tang@tang:~/tang/rover_slam/ceres-solver/build$ cmake ..
-- Detected Ceres version: 2.2.0 from /home/tang/tang/rover_slam/ceres-solver/include/ceres/version.h
-- Detected available Ceres threading models: [CXX_THREADS, OPENMP, NO_THREADS]
-- Found Eigen version 3.3.4: /usr/lib/cmake/eigen3
-- Enabling use of Eigen as a sparse linear algebra library.
-- Found CUDA version 11.1: /usr/local/cuda-11.1/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so;/usr/local/cuda-11.1/lib64/libcusolver.so;/usr/local/cuda-11.1/lib64/libcusparse.so
-- A library with BLAS API found.
-- Found LAPACK library: /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libf77blas.so;/usr/lib/x86_64-linux-gnu/libatlas.so
-- A library with BLAS API found.
-- Found CHOLMOD headers in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found SPQR headers in: /usr/include/suitesparse
-- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Found Config headers in: /usr/include/suitesparse
-- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Found AMD headers in: /usr/include/suitesparse
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found CAMD headers in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CCOLAMD headers in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found COLAMD headers in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found Intel Thread Building Blocks (TBB) library (2017.0 / 9107) include location: /usr/include. Assuming SuiteSparseQR was compiled with TBB.
-- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Found SuiteSparse 5.1.2, building with SuiteSparse.
-- Building without Apple's Accelerate sparse support.
-- Found Google Flags (gflags) version 2.2.1: /usr/lib/x86_64-linux-gnu/cmake/gflags
-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
-- Using Ceres threading model: CXX_THREADS
-- Building Ceres as a static library.
-- Enabling CERES_USE_EIGEN_SPARSE in Ceres config.h
-- Enabling CERES_NO_ACCELERATE_SPARSE in Ceres config.h
-- Enabling CERES_USE_CXX_THREADS in Ceres config.h
-- Build the examples.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tang/tang/rover_slam/ceres-solver/build
`

When at "make " step, the terminal as below:

`tang@tang:~/tang/rover_slam/ceres-solver/build$ ^C
tang@tang:~/tang/rover_slam/ceres-solver/build$ make
[ 26%] Built target ceres_internal
[ 28%] Built target ceres
[ 28%] Built target gtest
[ 29%] Built target test_util
[ 29%] Built target visibility_based_preconditioner_test
[ 30%] Built target trust_region_preprocessor_test
[ 30%] Built target trust_region_minimizer_test
[ 31%] Built target thread_pool_test
[ 31%] Built target tiny_solver_autodiff_function_test
[ 32%] Built target sparse_normal_cholesky_solver_test
[ 32%] Built target solver_test
[ 33%] Built target small_blas_test
[ 33%] Built target schur_eliminator_test
[ 33%] Built target schur_complement_solver_test
[ 33%] Built target single_linkage_clustering_test
[ 33%] Built target rotation_test
[ 34%] Built target residual_block_test
[ 34%] Built target program_test
[ 35%] Built target problem_test
[ 35%] Built target polynomial_test
[ 35%] Built target system_test
[ 35%] Built target parameter_dims_test
[ 35%] Built target triplet_sparse_matrix_test
[ 36%] Built target parameter_block_ordering_test
[ 37%] Built target ordered_groups_test
[ 37%] Built target numeric_diff_first_order_function_test
[ 38%] Built target numeric_diff_cost_function_test
[ 38%] Built target minimizer_test
[ 39%] Built target loss_function_test
[ 39%] Built target local_parameterization_test
[ 40%] Built target line_search_minimizer_test
[ 40%] Built target levenberg_marquardt_strategy_test
[ 40%] Built target conditioned_cost_function_test
[ 40%] Built target jet_traits_test
[ 40%] Built target residual_block_utils_test
[ 40%] Built target gradient_checking_cost_function_test
[ 40%] Built target cost_function_to_functor_test
[ 41%] Built target gradient_problem_solver_test
[ 41%] Built target iterative_refiner_test
[ 41%] Built target block_random_access_diagonal_matrix_test
[ 41%] Built target parallel_utils_test
[ 42%] Built target block_random_access_sparse_matrix_test
[ 42%] Built target covariance_test
[ 42%] Built target normal_prior_test
[ 42%] Built target autodiff_first_order_function_test
[ 43%] Built target c_api_test
[ 44%] Built target autodiff_cost_function_test
[ 44%] Built target autodiff_test
[ 44%] Built target dogleg_strategy_test
[ 45%] Built target cubic_interpolation_test
[ 46%] Built target visibility_test
[ 47%] Built target partitioned_matrix_view_test
[ 48%] Built target autodiff_manifold_test
[ 48%] Built target dynamic_numeric_diff_cost_function_test
[ 48%] Built target compressed_row_sparse_matrix_test
[ 48%] Built target array_utils_test
[ 48%] Built target graph_algorithms_test
[ 48%] Built target cuda_dense_cholesky_test
[ 49%] Built target cuda_dense_qr_test
[ 49%] Built target tiny_solver_cost_function_adapter_test
[ 49%] Built target reorder_program_test
[ 49%] Built target line_search_preprocessor_test
[ 50%] Built target concurrent_queue_test
[ 50%] Built target autodiff_local_parameterization_test
[ 50%] Built target block_jacobi_preconditioner_test
[ 51%] Built target householder_vector_test
[ 52%] Built target is_close_test
[ 52%] Built target array_selector_test
[ 52%] Built target parameter_block_test
[ 52%] Built target canonical_views_clustering_test
[ 52%] Built target fixed_array_test
[ 52%] Built target sparse_cholesky_test
[ 53%] Built target corrector_test
[ 53%] Built target manifold_test
[ 53%] Built target dense_qr_test
[ 53%] Built target dynamic_sparsity_test
[ 53%] Built target parallel_for_test
[ 54%] Built target block_random_access_dense_matrix_test
[ 55%] Built target dense_linear_solver_test
[ 56%] Built target evaluation_callback_test
[ 57%] Built target integer_sequence_algorithm_test
[ 57%] Built target dense_cholesky_test
[ 57%] Built target evaluator_test
[ 57%] Built target inner_product_computer_test
[ 57%] Built target subset_preconditioner_test
[ 57%] Built target conjugate_gradients_solver_test
[ 57%] Built target dense_sparse_matrix_test
[ 58%] Built target detect_structure_test
[ 59%] Built target tiny_solver_test
[ 59%] Built target dynamic_autodiff_cost_function_test
[ 60%] Built target jet_test
[ 61%] Built target dynamic_compressed_row_sparse_matrix_test
[ 61%] Built target block_sparse_matrix_test
[ 62%] Built target dynamic_sparse_normal_cholesky_solver_test
[ 62%] Built target compressed_col_sparse_matrix_utils_test
[ 63%] Built target gradient_checker_test
[ 63%] Built target gradient_problem_test
[ 64%] Built target graph_test
[ 64%] Built target implicit_schur_complement_test
[ 64%] Built target invert_psd_matrix_test
[ 64%] Built target iterative_schur_complement_solver_test
[ 65%] Built target ba_iterschur_acceleratesparse_clusttri_user_threads_test
[ 65%] Built target ba_iterschur_eigensparse_clusttri_user_threads_test
[ 65%] Built target ba_iterschur_acceleratesparse_clustjacobi_user_threads_test
[ 65%] Built target ba_iterschur_eigensparse_clustjacobi_user_threads_test
[ 65%] Built target ba_iterschur_suitesparse_clustjacobi_user_threads_test
[ 66%] Built target ba_iterschur_schurjacobi_auto_threads_test
[ 67%] Built target ba_sparseschur_acceleratesparse_auto_threads_test
[ 68%] Built target ba_denseschur_eigen_user_test
[ 68%] Built target ba_iterschur_acceleratesparse_clusttri_user_test
[ 68%] Built target ba_sparsecholesky_suitesparse_auto_threads_test
[ 69%] Built target ba_sparseschur_suitesparse_auto_threads_test
[ 69%] Built target ba_sparsecholesky_acceleratesparse_auto_threads_test
[ 69%] Built target ba_iterschur_schurjacobi_user_threads_test
[ 69%] Built target ba_iterschur_eigensparse_clustjacobi_auto_threads_test
[ 70%] Built target ba_denseschur_lapack_auto_threads_test
[ 71%] Built target ba_sparsecholesky_suitesparse_auto_test
[ 72%] Built target ba_denseschur_cuda_auto_threads_test
[ 73%] Built target ba_sparsecholesky_eigensparse_auto_threads_test
[ 73%] Built target ba_iterschur_eigensparse_clusttri_auto_test
[ 73%] Built target ba_sparseschur_eigensparse_user_test
[ 73%] Built target ba_iterschur_suitesparse_clustjacobi_auto_threads_test
[ 73%] Built target ba_denseschur_lapack_auto_test
[ 73%] Built target ba_iterschur_acceleratesparse_clustjacobi_auto_test
[ 73%] Built target ba_sparseschur_eigensparse_auto_threads_test
[ 73%] Built target ba_sparseschur_suitesparse_user_test
[ 73%] Built target ba_iterschur_acceleratesparse_clusttri_auto_test
[ 73%] Built target ba_iterschur_suitesparse_clusttri_auto_test
[ 73%] Built target ba_denseschur_cuda_auto_test
[ 73%] Built target ba_denseschur_eigen_auto_test
[ 74%] Built target ba_sparseschur_eigensparse_auto_test
[ 74%] Built target ba_sparseschur_suitesparse_auto_test
[ 74%] Built target ba_iterschur_jacobi_auto_threads_test
[ 75%] Built target ba_iterschur_jacobi_auto_test
[ 75%] Built target ba_iterschur_eigensparse_clustjacobi_auto_test
[ 75%] Built target ba_denseschur_eigen_auto_threads_test
[ 75%] Built target ba_denseschur_cuda_user_test
[ 76%] Built target ba_sparsecholesky_acceleratesparse_auto_test
[ 76%] Built target ba_iterschur_acceleratesparse_clustjacobi_auto_threads_test
[ 77%] Built target ba_iterschur_suitesparse_clusttri_auto_threads_test
[ 78%] Built target ba_iterschur_eigensparse_clusttri_auto_threads_test
[ 78%] Built target ba_sparsecholesky_eigensparse_user_threads_test
[ 78%] Built target ba_sparseschur_acceleratesparse_user_threads_test
[ 79%] Built target ba_iterschur_acceleratesparse_clusttri_auto_threads_test
[ 80%] Built target ba_iterschur_acceleratesparse_clustjacobi_user_test
[ 80%] Built target ba_denseschur_lapack_user_test
[ 80%] Built target ba_sparsecholesky_suitesparse_user_test
[ 80%] Built target ba_sparsecholesky_acceleratesparse_user_threads_test
[ 80%] Built target ba_sparsecholesky_eigensparse_user_test
[ 80%] Built target ba_iterschur_suitesparse_clusttri_user_threads_test
[ 81%] Built target ba_sparsecholesky_acceleratesparse_user_test
[ 81%] Built target ba_sparseschur_acceleratesparse_user_test
[ 82%] Built target ba_iterschur_suitesparse_clustjacobi_auto_test
[ 83%] Built target ba_sparseschur_eigensparse_user_threads_test
[ 83%] Built target ba_iterschur_schurjacobi_user_test
[ 83%] Built target ba_iterschur_jacobi_user_threads_test
[ 84%] Built target ba_iterschur_jacobi_user_test
[ 84%] Built target ba_iterschur_schurjacobi_auto_test
[ 84%] Built target ba_sparseschur_acceleratesparse_auto_test
[ 85%] Built target ba_iterschur_suitesparse_clustjacobi_user_test
[ 86%] Built target ba_iterschur_eigensparse_clustjacobi_user_test
[ 86%] Built target ba_iterschur_eigensparse_clusttri_user_test
[ 86%] Built target ba_denseschur_eigen_user_threads_test
[ 87%] Built target ba_denseschur_lapack_user_threads_test
[ 87%] Built target ba_iterschur_suitesparse_clusttri_user_test
[ 88%] Built target ba_denseschur_cuda_user_threads_test
[ 89%] Built target ba_sparsecholesky_suitesparse_user_threads_test
[ 89%] Built target ba_sparsecholesky_eigensparse_auto_test
[ 89%] Built target ba_sparseschur_suitesparse_user_threads_test
[ 89%] Built target bundle_adjuster
[ 89%] Built target libmv_homography
[ 90%] Built target circle_fit
[ 91%] Built target libmv_bundle_adjuster
[ 92%] Built target more_garbow_hillstrom
[ 92%] Built target nist
[ 92%] Built target powell
[ 92%] Built target helloworld_numeric_diff
[ 92%] Built target curve_fitting
[ 92%] Built target rosenbrock
[ 92%] Built target curve_fitting_c
[ 93%] Built target denoising
[ 93%] Built target bicubic_interpolation_analytic
[ 94%] Built target helloworld
[ 95%] Built target rosenbrock_analytic_diff
[ 96%] Built target simple_bundle_adjuster
[ 97%] Built target robot_pose_mle
[ 97%] Built target helloworld_analytic_diff
[ 97%] Built target ellipse_approximation
[ 97%] Built target robust_curve_fitting
[ 97%] Built target rosenbrock_numeric_diff
[ 98%] Built target bicubic_interpolation
[ 99%] Built target sampled_function
[100%] Built target pose_graph_2d
[100%] Building CXX object examples/slam/pose_graph_3d/CMakeFiles/pose_graph_3d.dir/pose_graph_3d.cc.o
In file included from /home/tang/tang/rover_slam/ceres-solver/examples/slam/pose_graph_3d/pose_graph_3d.cc:35:
In file included from /home/tang/tang/rover_slam/ceres-solver/include/ceres/ceres.h:65:
In file included from /home/tang/tang/rover_slam/ceres-solver/include/ceres/ordered_groups.h:34:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/map:60:
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_tree.h:685:4: error: exception specification of explicitly defaulted move constructor does not match the calculated one
          _Rb_tree_impl(_Rb_tree_impl&&)
          ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_tree.h:706:31: note: in instantiation of template class 'std::_Rb_tree<int, std::pair<const int, ceres::examples::Pose3d>,
      std::_Select1st<std::pair<const int, ceres::examples::Pose3d> >, std::less<int>, Eigen::aligned_allocator<std::pair<const int, ceres::examples::Pose3d> > >::_Rb_tree_impl<std::less<int>, true>'
      requested here
      _Rb_tree_impl<_Compare> _M_impl;
                              ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_map.h:153:17: note: in instantiation of template class 'std::_Rb_tree<int, std::pair<const int, ceres::examples::Pose3d>,
      std::_Select1st<std::pair<const int, ceres::examples::Pose3d> >, std::less<int>, Eigen::aligned_allocator<std::pair<const int, ceres::examples::Pose3d> > >' requested here
      _Rep_type _M_t;
                ^
/home/tang/tang/rover_slam/ceres-solver/examples/slam/pose_graph_3d/pose_graph_3d.cc:63:33: note: in instantiation of template class 'std::map<int, ceres::examples::Pose3d, std::less<int>,
      Eigen::aligned_allocator<std::pair<const int, ceres::examples::Pose3d> > >' requested here
    auto pose_begin_iter = poses->find(constraint.id_begin);
                                ^
1 error generated.
examples/slam/pose_graph_3d/CMakeFiles/pose_graph_3d.dir/build.make:62: recipe for target 'examples/slam/pose_graph_3d/CMakeFiles/pose_graph_3d.dir/pose_graph_3d.cc.o' failed
make[2]: *** [examples/slam/pose_graph_3d/CMakeFiles/pose_graph_3d.dir/pose_graph_3d.cc.o] Error 1
CMakeFiles/Makefile2:8083: recipe for target 'examples/slam/pose_graph_3d/CMakeFiles/pose_graph_3d.dir/all' failed
make[1]: *** [examples/slam/pose_graph_3d/CMakeFiles/pose_graph_3d.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
tang@tang:~/tang/rover_slam/ceres-solver/build$ 
`
Thank you.

**Comment by sergiud** [comment]
Your CMake output is incomplete. Please remove the build directory and run CMake again. Also please format the log using code tags. It's very hard to read.

**Comment by sandwichmaker** [comment]
Closing because of lack of further response. Please reopen or file another issue as needed.

**Comment by sandwichmaker** [comment]
Ceres solver 1.14 is an ancient version of Ceres solver not supported
anymore. Please use version 2.1.0.
