### ISSUE TITLE
Store temporaries in `FirstOrderFunction`

### ISSUE THREAD

**Issue by brunnerant** [ceres-solver/ceres-solver#819]
I am currently implementing a function to optimize a grid of vertices using the general unconstrained minimization framework. My grids usually have a large amount of vertices, so it means that I have a lot of parameters. To make evaluation faster, I would ideally like to store intermediate values in arrays between the forward and the backward pass, and keep those arrays as members of the `FirstOrderFunction` class so that I don't need to allocate them at every call to `Evaluate`. Unfortunately, the `const` qualifiers forbid this so I need to re-allocate the arrays in every call to `Evaluate`, which I am not very satisfied with...

Do you know of a solution to this problem ?

Thanks for your help !

**Comment by sandwichmaker** [comment]
The const qualifier is there to make sure that calling this function is idempotent on the same set of input values, this is necessary for things like line search. if you are doing things where these guarantees are violated things get problematic and buggy.  I suspect the sort of thing you are looking for is the equivalent of EvaluationCallback that we have for the nonlinear least squares solver, but does not exist for the gradientproblem yet.
