### ISSUE TITLE
`inner_product_computer_test` segfault in 32 bit MinGW build

### ISSUE THREAD

**Issue by sergiud** [ceres-solver/ceres-solver#820]
From the [log](https://github.com/sergiud/ceres-solver/runs/6804094359?check_suite_focus=true#step:8:106):
```
 47/165 Test  #48: inner_product_computer_test ...................................***Exception: SegFault  0.26 sec
Running main() from gmock_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from InnerProductComputer
[ RUN      ] InnerProductComputer.NormalOperation
[       OK ] InnerProductComputer.NormalOperation (82 ms)
[ RUN      ] InnerProductComputer.SubMatrix
```
It looks like the issue affects only the 32 bit build but not 64 bit.

**Comment by sandwichmaker** [comment]
any idea whats going on? this is a weird crash.

**Comment by sergiud** [comment]
Yes, it is. I'm not entirely sure yet but it is possible LTO is doing wild things.

**Comment by sandwichmaker** [comment]
does it go away without lto?

**Comment by sergiud** [comment]
Unfortunately, it [does not](https://github.com/sergiud/ceres-solver/runs/6915642211?check_suite_focus=true#step:7:106). Disabling optimizations [does not help either](https://github.com/sergiud/ceres-solver/runs/6916572324?check_suite_focus=true#step:7:106).

**Comment by sandwichmaker** [comment]
Is there a stack trace to be had in debug mode?

**Comment by sergiud** [comment]
I stepped through the test using `gdb` and got this:
```
$ gdb ./bin/inner_product_computer_test.exe
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "i686-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./bin/inner_product_computer_test.exe...
(gdb) r
Starting program: C:\devel\build-mingw32-ceres\bin\inner_product_computer_test.exe
[New Thread 20976.0x2e84]
[New Thread 20976.0x173c]
[New Thread 20976.0x296c]
Running main() from gmock_main.cc
←[0;32m[==========] ←[mRunning 2 tests from 1 test suite.
←[0;32m[----------] ←[mGlobal test environment set-up.
←[0;32m[----------] ←[m2 tests from InnerProductComputer
←[0;32m[ RUN      ] ←[mInnerProductComputer.NormalOperation
←[0;32m[       OK ] ←[mInnerProductComputer.NormalOperation (618 ms)
←[0;32m[ RUN      ] ←[mInnerProductComputer.SubMatrix

Thread 1 received signal SIGSEGV, Segmentation fault.
ceres::internal::InnerProductComputer::ComputeNonzeros (this=0x21da0f0, product_terms=std::vector of length 0, capacity 0, row_nnz=0xdfede8) at D:/Projects/ceres-solver/internal/ceres/inner_product_computer.cc:81
81        (*row_nnz)[product_terms[0].row] = blocks[product_terms[0].col].size;
```
For some reason, the `product_terms` vector is empty. Is this a threshold problem?

**Comment by sandwichmaker** [comment]
can you check what is happening in InnerProductComputer::Init() then?
is it the case that start_row_block = end_row_block somehow? or the rows themselves are empty?

**Comment by sandwichmaker** [comment]
actually start_row_block is guaranteed not to be equal to end_row_block in the test so thats not the problem. I bet the random matrix we create is not dense enough.

**Comment by sandwichmaker** [comment]
so at line 189 of inner_product_computer_test.cc we should check to see if there are actually any nonzeroes.

but more importantly the code itself should not crash on an empty matrix. so we should just add a test for that and update the code.

**Comment by sergiud** [comment]
`start_row_block_` is 3 and `end_row_block_` is 4. Referencing the rows of the start block gives this:
```
(gdb) p bs->rows[3]
$6 = (__gnu_cxx::__alloc_traits<std::allocator<ceres::internal::CompressedList>, ceres::internal::CompressedList>::value_type &) @0x253a1e4: {block = {size = 2, position = 7}, cells = std::vector of length 0, capacity 0}
```
which is why `product_terms.emplace_back` is never called.

**Comment by sergiud** [comment]
Interestingly, incrementing the PRNG seed to 29824 allows the test to pass.

**Comment by sergiud** [comment]
As an unrelated remark, I suggest deprecating `random.h` functionality which is based on notoriously low quality `std::rand` implementations (with global state) and replace it by `<random>`.

**Comment by sandwichmaker** [comment]
Yes that makes sense and he's I will remove random.h
