### ISSUE TITLE
Not find export.h

### ISSUE THREAD

**Issue by dbyoung720** [ceres-solver/ceres-solver#821]
/block_structure.h(44,10): fatal error C1083: not oopen : “ceres/internal/export.h”: No such file or directory [F:\..\ceres_internal.vcxproj]
......
......

WIN10X64 + VS2022 +CMake

**Comment by sandwichmaker** [comment]
Can you share your cmake logs please?

**Comment by sergiud** [comment]
This looks like OP's setup is broken. Not a Ceres issue.

**Comment by sandwichmaker** [comment]
Going to close it because of lack of response.
