### ISSUE TITLE
how can I set manual Schur structure in DENSE_SCHUR ?

### ISSUE THREAD

**Issue by chennuo0125-HIT** [ceres-solver/ceres-solver#822]
before, i solve BA problem by g2o solver, which can specify 3d point as marginalized, so solver can use schur method to optimized no marginalized pose, and then back-substituting to calculate marginalized 3d point. i want to implement above process by ceres-solver, but i dont know how to specify marginalized parameter block. hope for your reply :)

**Comment by sandwichmaker** [comment]
Marginalization is not possible in Ceres Solver right now. you have to marginalize variables yourself. We are working on it though.

**Comment by ShuangLiu1992** [comment]
> Marginalization is not possible in Ceres Solver right now. you have to marginalize variables yourself. We are working on it though.

Hi @sandwichmaker, is there anyone still working on marginalization?

**Comment by squirel2000** [comment]
Hi @sandwichmaker 
Is this marginalization function still in limbo? Or can we use the RemoveResidualBlock method to realize it? (However, the warning message in the document, "If you depend on the evaluated jacobian, do not use remove!", seems not to recommend it.)

**Comment by sandwichmaker** [comment]
Marginalization is not available yet.

**Comment by byrock** [comment]
Hi @sandwichmaker, is there anyone still working on marginalization?
Have you noticed this implementation of marginalization?

https://github.com/evanlev/ceres-solver
