### ISSUE TITLE
Error in evaluating the ResidualBlock. residual added twice. size of residue changed. 

### ISSUE THREAD

**Issue by wongkenchiang97** [ceres-solver/ceres-solver#823]
I've no idea why I got twice number of residue, and the size of residue have changed. Technically, I'll only have residue with size=1. From the STDERR, it reported the residue size is 2. 

The Optimization Converge only once.
![residual_block_error](https://user-images.githubusercontent.com/55145225/173827463-2f083fca-3479-490a-848a-090d8e6337c5.png)

 Defined my residue with size =1.  I used a for-loop to add residual to the problem. For this instance, I'll should only add 30 residues to the problem.
`ceres::CostFunction* cost_function = new ceres::AutoDiffCostFunction<GroundPlaneResidual,1,1,1,1,1>(
            new GroundPlaneResidual(static_cast<double>(ground_pts->points.at(i).x),
            static_cast<double>(ground_pts->points.at(i).y),
            static_cast<double>(ground_pts->points.at(i).z)));`
![implement](https://user-images.githubusercontent.com/55145225/173827122-5de5ff37-dcca-40b2-b4b2-ae3a64bebc2f.png)
 
residual definition:
![residual_definition](https://user-images.githubusercontent.com/55145225/173827355-848fe0cf-a067-4116-90e7-a9a1b96e118c.png)

found that the repeated residue is padded by a 1x4 array when printing out computed residue value:
![twice_residual_added](https://user-images.githubusercontent.com/55145225/173828112-f494ae4a-85fa-4c2e-94e7-3c2c74b9c37d.png)

Any Idea to make the residue right? @sandwichmaker

**Comment by sandwichmaker** [comment]
the second set of printouts are the jets being printed which are used by automatic differentiation to compute the derivatives. The four numbers after ";" are the derivative of the residual w.r.t. the four variables.

**Comment by wongkenchiang97** [comment]
@sandwichmaker Thanks for your reply. 
Why the size of residue will change to 2? I declared the residual size  as 1:
`ceres::CostFunction* cost_function = new ceres::AutoDiffCostFunction<GroundPlaneResidual,1,1,1,1,1>( new GroundPlaneResidual(static_cast<double>(ground_pts->points.at(i).x), static_cast<double>(ground_pts->points.at(i).y), static_cast<double>(ground_pts->points.at(i).z)));`

**Comment by sandwichmaker** [comment]
can you share the output of summary::FullReport() ?

**Comment by wongkenchiang97** [comment]
![image](https://user-images.githubusercontent.com/55145225/174429305-280316a7-2b34-42c1-b5e9-3ac65c3db927.png)

**Comment by wongkenchiang97** [comment]
I have added another non-linear optimization,  both problem will only converged once. 

This is the 2nd non-linear optimization sumary::FullReport()
![image](https://user-images.githubusercontent.com/55145225/174429479-e12da5a7-0c0b-4956-9c12-a0f5eae55e99.png)

**Comment by wongkenchiang97** [comment]
Still haven't solve the residual size and invalid jacobians issue. 
![image](https://user-images.githubusercontent.com/55145225/174429756-74e91049-6a4a-4588-b362-d048f0d6c99d.png)

**Comment by wongkenchiang97** [comment]
I guess it's the problem between Ceres-Solver and ros::ServiceServer. When I solve the optimization problem by calling a class-method instead of calling a ros::ServiceServer, It is running well.

the optimization keep on running without error
![image](https://user-images.githubusercontent.com/55145225/174565560-7ba6ac83-13ea-4080-82bc-8a653b8239bd.png)

**Comment by sandwichmaker** [comment]
okay I am going to close this issue assuming that this is an ROS issue. Please reopen it if you need further help.
