### ISSUE TITLE
after SetParameterLowerBound, solve time cost from 13ms rise to 21ms 

### ISSUE THREAD

**Issue by ChenLongquan** [ceres-solver/ceres-solver#825]
After SetParameterLowerBound and SetParameterUpperBound , solve time cost from 13ms rise to 21ms in same iteration num. Could someone tell this reason?

**Comment by sandwichmaker** [comment]
Adding bounds constraints requires Ceres Solver to do one or more line searches after computing the trust region step to make sure that the bounds constraints are satisfied. This requires computing the residuals and jacobians which takes up extra time. If you look at Summary::FullReport you will see the extra residual/jacobian evaluations show up.
