### ISSUE TITLE
how to opt negative cost

### ISSUE THREAD

**Issue by HeXu1** [ceres-solver/ceres-solver#826]

**Comment by HeXu1** [comment]
the residual square always positive,but I want opt opposite of it.but how to make it? thanks.

**Comment by sandwichmaker** [comment]
the objective function is the sum of squared residuals, so the nonlinear least squares solver cannot minimize a negative residual. For that you need to use GradientProblemSolver which can optimize arbitrary scalar functions.

**Comment by HeXu1** [comment]
thanks a lot.
