### ISSUE TITLE
How to eliminate ceres is the following log message？

### ISSUE THREAD

**Issue by Yaolang003** [ceres-solver/ceres-solver#830]
When I use the following code：
```
    options.minimizer_progress_to_stdout = false;   
    options.logging_type = SILENT;
```
Ceres blocks some of the log information.
However, the following information is still printed out：
![1655823081419](https://user-images.githubusercontent.com/35597652/174830033-a3487e1d-d44c-47ce-a7e6-4319f6ed3631.jpg)
Need to remove all the log information, please give some suggestions, thank you！

**Comment by sandwichmaker** [comment]
What platform are you on? If you can use full glog, otherwise look at changing the min logging level inside miniglog.

**Comment by Yaolang003** [comment]
> What platform are you on? If you can use full glog, otherwise look at changing the min logging level inside miniglog.

I use it in Qt5.12.5, using the MVSC compiler.
Your method I can try.

**Comment by Yaolang003** [comment]
> What platform are you on? If you can use full glog, otherwise look at changing the min logging level inside miniglog.

Do I need to modify and add the following code to recompile Ceres. And then use Ceres in my project?
```
    google::InitGoogleLogging(argv[0]);
    FLAGS_minloglevel  = 2;
```
I tried to set this level in my own project, which seems to have no effect.

**Comment by sandwichmaker** [comment]
Those are settings for full glog.
you are using miniglog, you need to set
