### ISSUE TITLE
How dose the ceres calculate the cost for multiple residuals

### ISSUE THREAD

**Issue by zhangzh103** [ceres-solver/ceres-solver#834]
I want to know how does the ceres calculate the initial cost when there is two or more residuals. I set the value of the two residuals to be both 1 and the cost is 29 and when I set one of them to 2 the cost became 79.5. What's the formular does ceres use to calculate this value?

**Comment by sandwichmaker** [comment]
cost is 1/2 (r1^2 + r^2). 
are you using any loss functions?
