### ISSUE TITLE
sparse_cholesky_test fails with Ubuntu 20.04

### ISSUE THREAD

**Issue by tasptz** [ceres-solver/ceres-solver#835]
[sparse_cholesky_test.log](https://github.com/ceres-solver/ceres-solver/files/9069518/sparse_cholesky_test.log)

Ceres compiled on Ubuntu 20.04 (as described [here](http://ceres-solver.org/installation.html#linux)) and all packages are default packages.

Git hash is `027e741a1ad6246c396b963dc73e51b4713c3d7c`.

**Comment by sandwichmaker** [comment]
Thanks for the report @tasptz let me take a look. @alexsmac maybe able to get to it before me.
I do not see a commit by the hash you have posted here, could you check to see which version of ceres solver you are using?

**Comment by sandwichmaker** [comment]
I am able to replicate this failure at head.  This appears to be a configuration problem because metis is not available by default on ubuntu yet the nested dissection based tests are being run.
cc: @sergiud

**Comment by sergiud** [comment]
CI fails with these changes.
