### ISSUE TITLE
calculate hessian matrix when evaluating jacobian

### ISSUE THREAD

**Issue by zhangrong1722** [ceres-solver/ceres-solver#837]
for dense-normal-cholesky solver, jacobian matrix is intermediate variable and hessian matrix(JTJ) is necessary. So how calculate hessian matrix when evaluating jacobian.

**Comment by alexsmac** [comment]
Where required, the Hessian approximation is computed internally within the Ceres back-end using the Jacobians returned by the CostFunctions (and any Manifolds).  There is no public API that allows CostFunctions to return (J^T * J)^{-1} as the manner in which this is computed and represented efficiently depends on the choice of linear solver, and part of Ceres' private (not public) APIs.

If you are actually asking whether you can obtain parts of (J^T * J)^{-1} calculated by Ceres for a complete Problem object (outside of an optimisation) then the answer is yes you can, see the documentation of the [Covariance](http://ceres-solver.org/nnls_covariance.html) object
