### ISSUE TITLE
Is there any way to add the relative constraints on the variables.

### ISSUE THREAD

**Issue by luoyin500** [ceres-solver/ceres-solver#841]
I want to add some relative constraints between the variables, such as:
x[i+1] > x[i]
I wander is there any way to approach it, thank you!

**Comment by hitdshu** [comment]
Well, with some tricks, you might.

For instance, if one wants x2 > x1, he could define x1 and dx as the optimization variable. And x2 is represented as x2 = x1 + exp(dx).

To summarize,
optimization variables: x1, dx
optimization function: origin f(x1, x2)--->Now: f(x1, x1 + exp(dx))

With these tricks, I think one can express relative constraints between two variables.

Deshun

**Comment by luoyin500** [comment]
@hitdshu this is a practical mathod, I will try it. Thanks for your help~
