### ISSUE TITLE
cuda_dense_qr_test failed

### ISSUE THREAD

**Issue by XinquanDu** [ceres-solver/ceres-solver#842]
when I make ceres_solver_2.1.0 on Ubuntu 18.04 , I follow the instruction on the website: www.ceres-solver.org/installatiion.html#linux, during which I failed in "make test".
I got:
 27/183 Test #27: cuda_dense_qr_test·······························································
***Failed    0.45sec

That's the only one failed test, other 182 tests passed

**Comment by sandwichmaker** [comment]
cc: @joydeep-b

**Comment by sandwichmaker** [comment]
Can you share the logs from the test please? I suspect it is a tolerance issue.

**Comment by sandwichmaker** [comment]
closing because of lack of update. Please reopen as needed.
