### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Metear** [ceres-solver/ceres-solver#843]
/usr/local/include/ceres/product_manifold.h:315:59: error: expected constructor, destructor, or type conversion before ‘;’ token
  315 |     -> ProductManifold<Manifold0, Manifold1, Manifolds...>;

When I ues the make to build my example, the error occured.

**Comment by sergiud** [comment]
What compiler do you use (including exact version)?

**Comment by Metear** [comment]
Ubuntu20 default version.

**Comment by sergiud** [comment]
You mean GCC 9.4.0? If this is the case, there's something wrong with you setup. Without a complete example it's hard to tell what exactly is wrong.

**Comment by Metear** [comment]
Sorry. I have solved this problem. I misspelled the parameter when using find_package.
