### ISSUE TITLE
Does ceres  can be used in QNX?

### ISSUE THREAD

**Issue by hitbuyi** [ceres-solver/ceres-solver#857]
I want to use ceres-solver in QNX environment, is it possible? any information on this issue is  appreciated

**Comment by sandwichmaker** [comment]
I have no idea. I suspect it will work. we do not depend on very many unix apis. I think the only thing is miniglog/glog.

**Comment by district10** [comment]
Yes, It works.

**Comment by Gygnus6** [comment]
hi how to do?

**Comment by district10** [comment]
@Gygnus6 Long time no touching on QNX. I'v forgot how we did it.

You may need to strip some dependencies. Here is some patch (but for Abseil, not Ceres): https://gist.github.com/district10/ab3c5bd7df0cabbb83f6e8b61fefbce8

**Comment by Gygnus6** [comment]
above link can`t open
