### ISSUE TITLE
Ceres Solver Report: Iterations: -2, Initial cost: -1.000000e+00, Final cost: -1.000000e+00, Termination: FAILURE

### ISSUE THREAD

**Issue by 44825762** [ceres-solver/ceres-solver#861]
I got a result like this:

==================================================================================

iter      cost      cost_change  |gradient|   |step|    tr_ratio  tr_radius  ls_iter  iter_time  total_time
   0  5.285684e+15    0.00e+00    2.54e+18   0.00e+00   0.00e+00  1.00e+04        0    4.19e-02    9.55e-02
   1  5.281679e+15    4.00e+12    2.54e+18   1.54e+01   1.00e+00  3.00e+04        1    9.55e-02    1.91e-01
   2  5.269684e+15    1.20e+13    2.53e+18   4.64e+01   9.99e-01  9.00e+04        1    8.69e-02    2.78e-01
   3  5.233867e+15    3.58e+13    2.50e+18   1.40e+02   9.96e-01  2.70e+05        1    8.89e-02    3.67e-01
   4  5.127929e+15    1.06e+14    2.42e+18   4.31e+02   9.89e-01  8.10e+05        1    9.26e-02    4.59e-01
   5  4.823316e+15    3.05e+14    2.19e+18   1.40e+03   9.69e-01  2.43e+06        1    9.87e-02    5.58e-01
   6  4.017857e+15    8.05e+14    1.62e+18   5.66e+03   9.13e-01  7.29e+06        1    9.25e-02    6.51e-01
   7  2.349769e+15    1.67e+15    6.64e+17   7.67e+04   7.89e-01  2.19e+07        1    9.11e-02    7.42e-01
   8  7.897150e+14    1.56e+15    1.65e+17   4.13e+06   7.12e-01  2.19e+07        1    9.60e-02    8.38e-01
   9  3.712995e+14    4.18e+14    1.55e+18   1.13e+09   6.61e-01  2.19e+07        1    9.38e-02    9.32e-01
  10  1.957855e+14    1.76e+14    1.57e+17   1.24e+09   7.51e-01  6.56e+07        1    1.12e-01    1.04e+00
  11  1.913690e+14    4.42e+12    1.44e+17   3.12e+09   5.96e-02  3.28e+07        1    8.95e-02    1.13e+00
  12  1.251826e+14    6.62e+13    1.54e+16   6.84e+08   7.88e-01  9.84e+07        1    9.03e-02    1.22e+00
  13  3.912193e+15   -3.79e+15    0.00e+00   2.47e+09  -1.36e+02  4.92e+07        1    6.45e-02    1.29e+00
  14  1.253362e+14   -1.54e+11    0.00e+00   1.23e+09  -5.62e-03  2.46e+07        0    6.56e-03    1.29e+00
  15  1.066236e+14    1.86e+13    2.93e+15   6.15e+08   6.85e-01  2.46e+07        0    3.69e-02    1.33e+00
  16  1.027251e+14    3.90e+12    1.02e+17   6.36e+08   2.59e-01  2.46e+07        1    9.63e-02    1.43e+00
  17  9.040800e+13    1.23e+13    1.31e+16   1.14e+08   7.87e-01  7.38e+07        1    9.62e-02    1.52e+00
  18  1.373351e+14   -4.69e+13    0.00e+00   3.14e+08  -4.17e+00  3.69e+07        1    6.83e-02    1.59e+00
  19  6.370895e+14   -5.47e+14    0.00e+00   1.57e+08  -4.97e+01  1.85e+07        0    1.06e-02    1.60e+00
  20  1.030480e+14   -1.26e+13    0.00e+00   7.79e+07  -1.16e+00  9.23e+06        0    8.14e-03    1.61e+00
Ceres Solver Report: Iterations: 21, Initial cost: 5.285684e+15, Final cost: 9.040800e+13, Termination: NO_CONVERGENCE
[POSEGRAPH]: pose optimization 
[POSEGRAPH]: creation 1218.280 ms | optimization 1614.899 ms 
Ceres Solver Report: Iterations: -2, Initial cost: -1.000000e+00, Final cost: -1.000000e+00, Termination: FAILURE
===================================================================================================
Would you mind tell me what cause "Iteration: -2"  ?

Is " Iteration: -2" makes Ceres return failure ?

**Comment by sandwichmaker** [comment]
This looks like an uninitialized summary object. If your optimization succeeded the. You should not get a summary like this.

**Comment by 44825762** [comment]
Yes, it looks like an uninitialized problem. The data used in whole process is not changed, and it is successful in the first optimization process.  In the second optimization, some data which in same format has been added in process, then it fails.

In the second optimization, some data in same format has been added in process, then it failed. 

There are three part we can change when using Ceres, problem.AddParameterBlock, ceres::CostFunction* cost_function, problem.AddResidualBlock, which one may lead to "Iteration: -2"?

**Comment by sandwichmaker** [comment]
so there are two solves being called?
so this has nothing to do with the first successful solve.
Please print Summary::FullReport it will tell you what is going on. also running the solver at higher verbosity will likely tell you the cause of failure.

**Comment by 44825762** [comment]
Ok, I got this:

=====
```c++
Solver Summary (v 1.14.0-eigen-(3.3.4)-lapack-suitesparse-(5.1.2)-cxsparse-(3.1.9)-eigensparse-openmp-no_tbb)

                                     Original                  Reduced
Parameter blocks                         9076                     9076
Parameters                              10120                    10120
Effective parameters                     9946                     9946
Residual blocks                         35757                    35757
Residuals                               71514                    71514

Minimizer                        TRUST_REGION

Dense linear algebra library            EIGEN
Trust region strategy                  DOGLEG (TRADITIONAL)

                                        Given                     Used
Linear solver                     DENSE_SCHUR              DENSE_SCHUR
Threads                                     1                        1
Linear solver ordering              AUTOMATIC                 8903,173
Schur structure                         2,d,6                    2,d,d

Cost:
Initial                          2.576251e+15
Final                            1.921487e+14
Change                           2.384102e+15

Minimizer iterations                       21
Successful steps                           15
Unsuccessful steps                          6

Time (in seconds):
Preprocessor                         0.073264

  Residual only evaluation           0.195149 (20)
  Jacobian & residual evaluation     0.586494 (15)
  Linear solver                      1.851763 (15)
Minimizer                            2.830538

Postprocessor                        0.001809
Total                                2.905613

Termination:                   NO_CONVERGENCE (Maximum number of iterations reached. Number of iterations: 20.)
```
=====
```c++
Solver Summary (v 1.14.0-eigen-(3.3.4)-lapack-suitesparse-(5.1.2)-cxsparse-(3.1.9)-eigensparse-openmp-no_tbb)

                                     Original                  Reduced
Parameter blocks                        11030                       -1
Parameters                              12266                       -1
Residual blocks                         40710                       -1
Residuals                               81420                       -1

Minimizer                        TRUST_REGION

Sparse linear algebra library    SUITE_SPARSE
Trust region strategy                  DOGLEG (TRADITIONAL)

                                        Given                     Used
Linear solver                     DENSE_SCHUR   SPARSE_NORMAL_CHOLESKY
Threads                                     1                        1
Linear solver ordering              AUTOMATIC                AUTOMATIC

Cost:
Initial                         -1.000000e+00

Minimizer iterations                       -2
Successful steps                           -1
Unsuccessful steps                         -1

Time (in seconds):
Preprocessor                         0.001240

  Residual only evaluation          -1.000000 (-1)
  Jacobian & residual evaluation    -1.000000 (-1)
  Linear solver                     -1.000000 (-1)
Minimizer                           -1.000000

Postprocessor                        0.001535
Total                                0.002776

Termination:                          FAILURE (ParameterBlock: 0x7fd4ad333e48 with size 1 has at least one invalid value.
First invalid value is at index: 0.
Parameter block values:         -nan )

```
====

It does show the reason.
Thank you.
