### ISSUE TITLE
Is there any way to get the variables to be optimized in each iteration step

### ISSUE THREAD

**Issue by dhmzdl** [ceres-solver/ceres-solver#872]
Hello everyone, when running ”std::cout << summary.BriefReport() << endl;”, I'm wonder if there is any way to get the variables to be optimized in each iteration step. 
I checked the Summary and IterationSummay, but I didn't find any clues.

**Comment by sandwichmaker** [comment]
I do not understand your question.

**Comment by dhmzdl** [comment]
您发的邮件我已经收到。

**Comment by dhmzdl** [comment]
> I do not understand your question.

double *rot = (double*)malloc(4 * sizeof(double));  // Quaternion
double *tra = (double*)malloc(3 * sizeof(double)); // Translation
...
problem.AddResidualBlock(cost, new ceres::HuberLoss(0.5), rot, tra);
...
ceres::Solver::Options options;
options.linear_solver_type = ceres::DENSE_SCHUR;
options.max_num_iterations = 150;
options.trust_region_strategy_type = ceres::LEVENBERG_MARQUARDT;
options.minimizer_progress_to_stdout = true;
ceres::Solver::Summary summary;

ceres::Solve(options, &problem, &summary);

What I mean is how to obtain the “rot” and “tra” after each iteration in the “sovle” function so that I can monitor the trajectory of the camera posture. Ideally, a set of pose data such as vector<mat> can be collected after “sovle” execution.

**Comment by sandwichmaker** [comment]
Solver::Options::update_state_every_iteration in conjunction with an IterationCallback is what you need.

**Comment by dhmzdl** [comment]
> Solver::Options::update_state_every_iteration in conjunction with an IterationCallback is what you need.

The problem has been solved，thanks!

**Comment by ZzJiachenchen** [comment]
Hi, I also want to monitor the state after each iteration. How to implement it in the IterationCallback function? I mean how to access the state, which is the parameter of the problem, in the IterationCallback function. Looking forward to your reply. Thank you very much!

**Comment by ZzJiachenchen** [comment]
> Hi, I also want to monitor the state after each iteration. How to implement it in the IterationCallback function? I mean how to access the state, which is the parameter of the problem, in the IterationCallback function. Looking forward to your reply. Thank you very much!

The problem is solved. Thanks!
