### ISSUE TITLE
CUSPARSE_SPMV_ALG_DEFAULT is too new for some versions of CUDA 

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#877]
even though CUSPARSE_MV_ALG_DEFAULT is deprecated, we may have to use that in our code depending on the version of CUDA being used. 

cc: @joydeep-b

**Comment by sandwichmaker** [comment]
This triggers a bug with 10.1

**Comment by joydeep-b** [comment]
Sigh. I was trying not to do cuda version-based code, but we might have to.

**Comment by sandwichmaker** [comment]
GitHub does not allow me to respond with a laugh cry emoji.

**Comment by aligholami** [comment]
Any updates on this? I am having issues compiling Ceres solver with CUDA 11.1 and I get the following error:
```
In file included from /1.14.0/internal/ceres/compressed_row_sparse_matrix.h:42,
                 from /1.14.0/internal/ceres/cuda_sparse_matrix.h:45,
                 from /1.14.0/internal/ceres/cuda_sparse_matrix.cc:38:
/1.14.0/internal/ceres/cuda_sparse_matrix.cc: In member function 'void ceres::internal::CudaSparseMatrix::SpMv(cusparseOperation_t, const ceres::internal::CudaVector&, ceres::internal::CudaVector*)':
/1.14.0/internal/ceres/cuda_sparse_matrix.cc:116:36: error: 'CUSPARSE_SPMV_ALG_DEFAULT' was not declared in this scope; did you mean 'CUSPARSE_SPMM_ALG_DEFAULT'?
  116 |                                    CUSPARSE_SPMV_ALG_DEFAULT,
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
/1.14.0/internal/ceres/cuda_sparse_matrix.cc:128:25: error: 'CUSPARSE_SPMV_ALG_DEFAULT' was not declared in this scope; did you mean 'CUSPARSE_SPMM_ALG_DEFAULT'?
  128 |                         CUSPARSE_SPMV_ALG_DEFAULT,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [internal/ceres/CMakeFiles/ceres_internal.dir/build.make:986: internal/ceres/CMakeFiles/ceres_internal.dir/cuda_sparse_matrix.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by sandwichmaker** [comment]
@joydeep-b could you look into fixing this ?

**Comment by joydeep-b** [comment]
@sandwichmaker I'll take a look, please assign to me.

@aligholami If you have the ability to upgrade the CUDA version, that would be a workaround for now until this is fixed.

**Comment by sandwichmaker** [comment]
It is already assigned to you :)

**Comment by joydeep-b** [comment]
@aligholami Could you please try patch [22761](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/22761)?

**Comment by sandwichmaker** [comment]
This should be fixed at head.

**Comment by GopiRajuMatta** [comment]
> Any updates on this? I am having issues compiling Ceres solver with CUDA 11.1 and I get the following error:
> 
> ```
> In file included from /1.14.0/internal/ceres/compressed_row_sparse_matrix.h:42,
>                  from /1.14.0/internal/ceres/cuda_sparse_matrix.h:45,
>                  from /1.14.0/internal/ceres/cuda_sparse_matrix.cc:38:
> /1.14.0/internal/ceres/cuda_sparse_matrix.cc: In member function 'void ceres::internal::CudaSparseMatrix::SpMv(cusparseOperation_t, const ceres::internal::CudaVector&, ceres::internal::CudaVector*)':
> /1.14.0/internal/ceres/cuda_sparse_matrix.cc:116:36: error: 'CUSPARSE_SPMV_ALG_DEFAULT' was not declared in this scope; did you mean 'CUSPARSE_SPMM_ALG_DEFAULT'?
>   116 |                                    CUSPARSE_SPMV_ALG_DEFAULT,
>       |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
> /1.14.0/internal/ceres/cuda_sparse_matrix.cc:128:25: error: 'CUSPARSE_SPMV_ALG_DEFAULT' was not declared in this scope; did you mean 'CUSPARSE_SPMM_ALG_DEFAULT'?
>   128 |                         CUSPARSE_SPMV_ALG_DEFAULT,
>       |                         ^~~~~~~~~~~~~~~~~~~~~~~~~
> make[2]: *** [internal/ceres/CMakeFiles/ceres_internal.dir/build.make:986: internal/ceres/CMakeFiles/ceres_internal.dir/cuda_sparse_matrix.cc.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> ```

I am having the same error while compiling with CUDA 11.7.

**Comment by sandwichmaker** [comment]
This is fixed at head no?

**Comment by GopiRajuMatta** [comment]
> 

I used the latest stable version, 2.1.0. For that I didn't face this problem. Now it is working. Thank you!
