### ISSUE TITLE
Windows Installation of ceres using CMake 

### ISSUE THREAD

**Issue by anas-abulehia** [ceres-solver/ceres-solver#879]
I have followed the instructions given in [http://ceres-solver.org/installation.html](url). However after several trials I couldn't install it. The CMake output error is 
LINK : fatal error LNK1104: cannot open file 'm.lib' [C:\Users\anasa\Desktop\ceres\ceres-bin\CMakeFiles\CMakeTmp\cmTC_52ebe.vcxproj]
![image](https://user-images.githubusercontent.com/49106882/187034327-bccfef54-67a4-4254-bc9f-5ad81aec0ff0.png)

**Comment by sandwichmaker** [comment]
what version of ceres solver are you using?

**Comment by anas-abulehia** [comment]
I just cloned the repository 2 days ago

**Comment by sandwichmaker** [comment]
@anas-abulehia @sergiud and @alexsmac are on vacation and they are the MSVC folks on the team, I know nothing about MSVC :/ I would wait for them to come back next week and offer some help.

**Comment by jasjuang** [comment]
Easiest way to install Ceres on Windows is through [vcpkg](https://github.com/microsoft/vcpkg)

**Comment by sergiud** [comment]
`CheckFunctionExists.c` is not something you would compile yourself, which is what you seem to be doing.

> I have followed the instructions given in [http://ceres-solver.org/installation.html](url). However after several trials I couldn't install it.

What instructions did you follow exactly? The instruction section is very comprehensive and we would need to guess what commands you actually executed.

Please provide the command-line arguments used to invoke CMake, the full CMake and compiler output. Without this information it is unlikely we can help you.

**Comment by sandwichmaker** [comment]
Closing because of lack of response.
