### ISSUE TITLE
Compiling Example Error: parameter_dims.h  error c2059:   “...”

### ISSUE THREAD

**Issue by liyhn** [ceres-solver/ceres-solver#881]
All The CC/C++ examples Compiling meets these  parameter_dims.h  error c2059 problem ,
And I Test it under Visual studio 2017 and 2019 ,result the same, how to deal with it?
1>curve_fitting.cc
1>D:\3DLineScanner\ceres-solver-master\include\ceres/covariance.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>D:\3DLineScanner\ceres-solver-master\include\ceres/internal/parameter_dims.h(58): error C2059: 语法错误:“...”
1>D:\3DLineScanner\ceres-solver-master\include\ceres/sized_cost_function.h(53): note: 参见对正在编译的 类 模板 实例化 "ceres::internal::ParameterDims<false,1,1>" 的引用
1>D:\3DLineScanner\ceres-solver-master\include\ceres/autodiff_cost_function.h(155): note: 参见对正在编译的 类 模板 实例化 "ceres::SizedCostFunction<1,1,1>" 的引用
1>D:\3DLineScanner\ceres-solver-master\examples\curve_fitting.cc(146): note: 参见对正在编译的 类 模板 实例化 "ceres::AutoDiffCostFunction<ExponentialResidual,1,1,1>" 的引用
1>D:\3DLineScanner\ceres-solver-master\include\ceres/internal/parameter_dims.h(58): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\3DLineScanner\ceres-solver-master\include\ceres/internal/parameter_dims.h(59): error C2065: “kIsValid”: 未声明的标识符
1>D:\3DLineScanner\ceres-solver-master\include\ceres/internal/parameter_dims.h(68): error C2059: 语法错误:“...”
1>D:\3DLineScanner\ceres-solver-master\include\ceres/internal/parameter_dims.h(68): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\3DLineScanner\ceres-solver-master\include\ceres/sized_cost_function.h(53): error C2039: “kIsValid”: 不是“ceres::internal::ParameterDims<false,1,1>”的成员
1>D:\3DLineScanner\ceres-solver-master\include\ceres/internal/parameter_dims.h(101): note: 参见“ceres::internal::ParameterDims<false,1,1>”的声明
1>D:\3DLineScanner\ceres-solver-master\include\ceres/sized_cost_function.h(53): error C2065: “kIsValid”: 未声明的标识符
1>已完成生成项目“curve_fitting.vcxproj”的操作 - 失败。

**Comment by liyhn** [comment]
![image](https://user-images.githubusercontent.com/31336348/188046187-76ef0501-5766-41a5-88ea-a270de8bc1c1.png)

**Comment by liyhn** [comment]
![image](https://user-images.githubusercontent.com/31336348/188046360-fed008c9-9399-4913-a756-b56a4dcd4a18.png)

**Comment by sandwichmaker** [comment]
This looks like some sort of parse error.  I do not know anything about MSVC but I suspect that the problem is your setup somehow, since we do not observe this as a problem in our CI. Sorry @sergiud and @alexsmac are on vacation, they know their way around MSVC issues.

**Comment by sandwichmaker** [comment]
@sergiud any ideas?

**Comment by sergiud** [comment]
My guess would be also that there's something wrong with the setup. The compiler does not seem to understand C++17 fold expressions, among others.

@liyhn Please install an English language pack for Visual Studio and provide the full CMake and compiler output as text instead of screenshots.

**Comment by liyhn** [comment]
Cmake Text:
Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19042.
Detected Ceres version: 2.2.0 from D:/3DLineScanner/ceres-solver-master/include/ceres/version.h
-- Detected available Ceres threading models: [CXX_THREADS, OPENMP, NO_THREADS]
-- Found Eigen version 3.3.7: D:/SDK/eigen-eigen-337/build
-- Enabling use of Eigen as a sparse linear algebra library.
-- Found CUDA version 8.0: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cudart_static.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cusolver.lib;C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/lib/x64/cusparse.lib
-- Building without LAPACK.
-- Building without SuiteSparse.
-- Building without CXSparse.
-- Building without Apple's Accelerate sparse support.
-- Use of gflags disabled - no tests or tools will be built!
No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
Found installed version of glog: D:\Source\glog-master
Detected glog version: 0.6.0
-- Found Google Log (glog). Assuming glog was NOT built with gflags support as gflags was not found.  If glog was built with gflags, please set the gflags search locations such that it can be found by Ceres.  Otherwise, Ceres may fail to link due to missing gflags symbols.
-- Using Ceres threading model: NO_THREADS
-- Building Ceres as a static library.
Enabling CERES_USE_EIGEN_SPARSE in Ceres config.h
Enabling CERES_NO_LAPACK in Ceres config.h
Enabling CERES_NO_SUITESPARSE in Ceres config.h
Enabling CERES_NO_CXSPARSE in Ceres config.h
Enabling CERES_NO_ACCELERATE_SPARSE in Ceres config.h
Enabling CERES_NO_THREADS in Ceres config.h
Enabling CERES_MSVC_USE_UNDERSCORE_PREFIXED_BESSEL_FUNCTIONS in Ceres config.h
-- Build the examples.
Configuring done
CMake Error at internal/ceres/CMakeLists.txt:141 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE:cuda_dense_qr_test>

  No target "cuda_dense_qr_test"


CMake Error at internal/ceres/CMakeLists.txt:141 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE:cuda_dense_qr_test>

  No target "cuda_dense_qr_test"


CMake Error at internal/ceres/CMakeLists.txt:141 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE:cuda_dense_qr_test>

  No target "cuda_dense_qr_test"


CMake Error at internal/ceres/CMakeLists.txt:141 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE:cuda_dense_qr_test>

  No target "cuda_dense_qr_test"


CMake Error at internal/ceres/CMakeLists.txt:145 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE:cuda_dense_cholesky_test>

  No target "cuda_dense_cholesky_test"


CMake Error at internal/ceres/CMakeLists.txt:145 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE:cuda_dense_cholesky_test>

  No target "cuda_dense_cholesky_test"


CMake Error at internal/ceres/CMakeLists.txt:145 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE:cuda_dense_cholesky_test>

  No target "cuda_dense_cholesky_test"


CMake Error at internal/ceres/CMakeLists.txt:145 (add_test):
  Error evaluating generator expression:

    $<TARGET_FILE:cuda_dense_cholesky_test>

  No target "cuda_dense_cholesky_test"


Generating done

**Comment by liyhn** [comment]
I Sorry I made a mistake it's the c++17 issue 
![image](https://user-images.githubusercontent.com/31336348/190039100-22ceb91c-bfeb-44e2-989b-d36762b3f44c.png)

**Comment by liyhn** [comment]
So this Issue Closed 
![image](https://user-images.githubusercontent.com/31336348/190039222-5bb12acd-1107-489a-ba4b-ba19523c534b.png)

**Comment by liyhn** [comment]
> My guess would be also that there's something wrong with the setup. The compiler does not seem to understand C++17 fold expressions, among others.
> 
> @liyhn Please install an English language pack for Visual Studio and provide the full CMake and compiler output as text instead of screenshots.

It's the compiler's C++17 parameter not set issue, it's done , thank you very much !!!
