### ISSUE TITLE
No CUDA type under dense_linear_algebra_library_type

### ISSUE THREAD

**Issue by leiwanporsche** [ceres-solver/ceres-solver#884]
Hello. I was trying to accelerate the solver process of ceres. According to the tutorial we can use CUDA as the type of the dense linear algebra type. But actually there are not this type under the dense_linear_algebra_library_type

![image](https://user-images.githubusercontent.com/108680208/190606102-50298176-6310-4ff5-b7ee-bf37c838397a.png)

![image](https://user-images.githubusercontent.com/108680208/190606210-53172dab-06b4-40e0-a318-6912cc44233a.png)

**Comment by leiwanporsche** [comment]
And I am using WSL2 Ubuntu 20.04, CUDA 11.2, Ceres 2.1.0

**Comment by sandwichmaker** [comment]
Pretty sure you have an older version of ceres solver lying around somewhere.

https://github.com/ceres-solver/ceres-solver/blame/6c27ac6d509554b6120f917e2669bb05794ca8de/include/ceres/types.h#L214

**Comment by leiwanporsche** [comment]
@sandwichmaker 
Therefore the stable version 2.1.0 doesn't support the CUDA right? Since the link is of the main branch. And I try to compile the source code on the branch, but it would fail. 

![image](https://user-images.githubusercontent.com/108680208/191457322-e56d5b30-31d7-4e9b-b976-44e4ab6ac057.png)

**Comment by sandwichmaker** [comment]
My point to giving that link was that if you follow the blame link you will see that this line exists in version 2.1.0. Its the sparse support which was added after 2.1.0.

**Comment by sandwichmaker** [comment]
that last compile error is fixed at head.
