### ISSUE TITLE
Typo in TrustRegionMinimizer::Init

### ISSUE THREAD

**Issue by anstaf** [ceres-solver/ceres-solver#885]
`x_norm_` member variable is correstly set in https://ceres-solver.googlesource.com/ceres-solver/+/refs/heads/master/internal/ceres/trust_region_minimizer.cc#168
but a few lines after it is set to -1: https://ceres-solver.googlesource.com/ceres-solver/+/refs/heads/master/internal/ceres/trust_region_minimizer.cc#182

`x_norm_` is read only in `TrustRegionMinimizer::ParameterToleranceReached`. It is unclear why this member variable even exists.: it is better to calculate it within `TrustRegionMinimizer::ParameterToleranceReached`.

If you want to verify that this issue do actually affects execution, you can add `CHECK_NE(x_norm_,  -1);` inside  `ParameterToleranceReached`

**Comment by sandwichmaker** [comment]
Thanks @anstaf. Yes this is a bug that affects the code till the first successful iteration. 

https://ceres-solver-review.googlesource.com/c/ceres-solver/+/22940 is out for review.
