### ISSUE TITLE
FullReport Question

### ISSUE THREAD

**Issue by ChenLongquan** [ceres-solver/ceres-solver#891]
![1663930281569](https://user-images.githubusercontent.com/20835824/191945518-4f9c960e-0c36-4843-ab11-1f0f481b070b.png)

this is my report, but I don't understand why residual and jacobian only cost 0.01s and 0.33s. However minimizer cost 4.35s?

**Comment by sandwichmaker** [comment]
That is an odd looking full report for sure. I have never seen a
discrepancy like this.
Is your code public that I can replicate it?

**Comment by sandwichmaker** [comment]
The only place I can imagine the time is going is inside the lbfgs update.

**Comment by sandwichmaker** [comment]
or if you can profile the code and share the results with me.

**Comment by ChenLongquan** [comment]
thank you for your reply! I have found the abnormal time cost's reason is log output in terminal blocking.

**Comment by ChenLongquan** [comment]
I have set     
option.minimizer_progress_to_stdout = true;
option.logging_type = ceres::LoggingType::SILENT;

But it still outputing log, how to disable this?

**Comment by sandwichmaker** [comment]
Are you using miniglog? or glog?

**Comment by ChenLongquan** [comment]
minilog. I add #define MAX_LOG_LEVEL -100 in ceres/miniglog/glog/logging.h. problem solved!
