### ISSUE TITLE
 error: ‘CX_SPARSE’ is not a member of ‘ceres’; did you mean ‘NO_SPARSE’?

### ISSUE THREAD

**Issue by JKViswanadham14** [ceres-solver/ceres-solver#895]
Hi,

I am trying to build OpenMVS and ran into this. any leads appreciated.

**Comment by sandwichmaker** [comment]
I think you are trying to use too new or a version of Ceres Solver.
Cx_sparse support was removed from Ceres sometime ago. I would ask the
openmvs folks which version of Ceres Solver they recommend.
Sameer

**Comment by JKViswanadham14** [comment]
Thanks for your reply. how do i check version of Ceres solver on my system?

**Comment by sandwichmaker** [comment]
include/ceres/version.h
