### ISSUE TITLE
How to store multiple ceres::Problem so that we can call each Problem.evaluate in other Functions or Class?

### ISSUE THREAD

**Issue by dhmzdl** [ceres-solver/ceres-solver#896]
Hello everyone, two quesitions:
Question A: as the title shows:
class A{

      struct ptr{
          ceres::Problem* myProblem;
	  double* para;
      };
      vector<ptr> problemSeqs;

      void freePtr(){
         for(int i = 0; i < .... i++){
              free(problemSeqs[i].para)
              problemSeqs[i].para = NULL;
              problemSeqs[i].myProblem = NULL;
         }
      }

      void func1(){
            for(int i = 0; i < .... i++){
                ptr newOne;
                double* para = ...
                ceres::Problem problem;
                problem.AddResidualBlock(...);
                ceres::Solve(...);

                // save this problem
                newOne.para = para;
                newOne.myProblem = &problem;
                problemSeqs.push_back(newOne)
            }
      }
      void func2(){}
};

I want to know whether the following code is correct if I run it in func2() or other Class (e.g. Class B)
...
problemSeqs[1].para = position11;
problemSeqs[1].myProblem.evaluate(....);  // evaluate the problem1 at position11;
...
problemSeqs[3].para = position32;
problemSeqs[3].myProblem.evaluate(....);  // evaluate this problem3 at position32;
...
freePtr();      // release all the problems and parameter pointers;

Question B: When a problem based on trust region strategy is sovled and we can record the value of “para” in each iteration step by "StatePerceptCallback" and calculate the Jacobi matrix by “evaluate”.  Then, whether ceres provide a function that can estimate the direction and step at any para, or can we only calculate by ourselves.

**Comment by sandwichmaker** [comment]
I think I would be able to answer your question better if you could tell me what is it that you are trying to achieve.

**Comment by sandwichmaker** [comment]
The problem is that in func1 you are allocating a problem object on the stack, storing a pointer to it, but when you exit func1 that problem is destroyed. You need to allocate on the heap rather than on the stack. Something along the lines of

```
 void func1(){
        for(int i = 0; i < .... i++){
            ptr newOne;
            double* para = ...
            auto problem = new ceres::Problem;
            problem->AddResidualBlock(...);
            ceres::Solve(...);

            // save this problem
            newOne.para = para;
            newOne.myProblem = problem;
            problemSeqs.push_back(newOne)
        }
  }
```
