### ISSUE TITLE
Cannot pass the test [dynamic_sparsity_test].

### ISSUE THREAD

**Issue by wystephen** [ceres-solver/ceres-solver#898]
Ceres version: 2.0.0
libsparsesuite: 5.7.1
System: Ubuntu 20.04

Details:
cmake .. && make -j16 && make 
show 'Start 31: dynmaic_sparsity_test' for more than 10 Minutes and then I closed the shell.
The test cannot pass if using suitesparse. 

When compiled use EigenSparse, then the solveproblem() function in another problem costs 57 s ( 8s for the same code in another compute compiled with suitesparse) and cannot use more than 1 thread.

**Comment by sandwichmaker** [comment]
This seems rather odd. is this specific to this version of suitesparse?

**Comment by wystephen** [comment]
I compare md5 of libsuitesparseconfig.so.5.7.1 with another computer which can pass the unit test. 
And the cmake-gui shows the SUITESPARSE_CONFIG_LIBRARY set to /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so.
MD5Sum as below:
5cb6bb98a48796cd0a90363274b248fe  /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so.5.7.1

Is there any other advise about this issue?

**Comment by sandwichmaker** [comment]
I suspect this is some sort of issue between suitesparse and your blas/lapack library. Does this problem happen if you compile suitesparse yourself?
what blas/lapack are you using?

**Comment by wystephen** [comment]
Sorry for the delay in reply. 
I am re-installed Ubuntu.

**Comment by sandwichmaker** [comment]
any updates here?

**Comment by wystephen** [comment]
I am solving this problem by re-install the operating system. 
And I can't reproduce the bug now.
