### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by SystemDiagnosticss** [ceres-solver/ceres-solver#899]
Try to run few SLAM alghorithms. cartographer and slam_toolbox 
And both libraries get same error:

`/lib/libceres.so.1: undefined symbol: _ZN6google21kLogSiteUninitializedE`

Any idea how to solve this?

**Comment by sandwichmaker** [comment]
Looks like you are missing glog.

**Comment by sandwichmaker** [comment]
Closing because lack of response, please feel free to reopen with more information.
