### ISSUE TITLE
Why Dosen't ceres support openCL?

### ISSUE THREAD

**Issue by ChenHuang20** [ceres-solver/ceres-solver#901]

**Comment by alexsmac** [comment]
OpenCL is just a low-level language, it does not itself provide the necessary (sparse) linear algebra operations that Ceres requires, i.e. equivalents of NVIDIA's cuBLAS and cuSOLVER libraries.  We're not aware of any equivalents to those that provide the same level of performance and functionality (and which are stable and actively maintained) using OpenCL
