### ISSUE TITLE
Active set method for BVLS

### ISSUE THREAD

**Issue by mrsandipandas** [ceres-solver/ceres-solver#904]
Hi @sandwichmaker! Thanks for open-sourcing ceras.

Please excuse my limited experience. I was wondering if you have considered putting in an [active set method](http://www.stat.berkeley.edu/~stark/Preprints/bvls.pdf) for Bounded-Variable Least-Squares as done in scipy? This might be helpful in some problems with nonsmooth constraints as it can take larger steps, which can speed up the process.

**Comment by sandwichmaker** [comment]
Yes, just haven't had time to implement it. Will happily accept patches.

**Comment by s-a-n-d-y** [comment]
Would you recommend [this](http://www.stat.berkeley.edu/~stark/Preprints/bvls.pdf) method as a standard BVLS solution? Or, do you have any other BVLS solution methods in mind?

**Comment by sandwichmaker** [comment]
@s-a-n-d-y I am not sure what you are trying to do. Are you asking what BVLS method I would recommend for solving BVLS problems independent of Ceres Solver, or are you asking what BVLS method I would recommend for implementing inside Ceres Solver as a sub routine?

**Comment by s-a-n-d-y** [comment]
I was asking on what BVLS would you recommend for implementing it within ceras (in case I plan to inplement it).

**Comment by sandwichmaker** [comment]
TBH I do not have a good answer for that. I suspect it will require some experimentation. The basic ceres solver loop is quite simple and easily implemented in a few lines of matlab/julia. I recommend doing that and sticking your bvls method of choice into it and see how that does before thinking about implementing it inside ceres.

**Comment by sandwichmaker** [comment]
I would be happy to work with on it though, point you to some benchmark problems etc and help design the integration.

**Comment by sandwichmaker** [comment]
Going to close this for now as there is no work planned here.
