### ISSUE TITLE
Segmantation fault occur at ceres::Solve()

### ISSUE THREAD

**Issue by TakuOkawara** [ceres-solver/ceres-solver#906]
Thank you for giving us a wonderful solver.

I am a beginner at ceres-solver. 
My environment is shown as follows.
- ubuntu.18.04
- ceres-solver-2.1.0
- ROS Melodic

I am implementing bundle adjustment with multiple RGB-D images with reference to [this link](https://github.com/Freeecode/ceres-solver-learning/tree/master/ceres_pnp). For implementing bundle adjustment, I use two for-loop: the first is the element of a camera pose. second is the element of a matched feature point.
However, **"segmentation fault" always occurs when two or more camera poses are added to ceres::problem and then ceres::Solve(options, &problem, &summary) is executed.**
My code using ceres-sover is PoseOptimizationByBA function in /learn_slam-with_solve_problem/bundle_adjustment/src/bundle_adjustment.cpp. Then, "ceres::Solve(options, &problem, &summary)" is at 231 line
This cpp file is included in [this zip file](https://drive.google.com/file/d/1sYAaYvW3y1F_OqCX2gdrqMrmepfpZoqx/view?usp=share_link).

![Screenshot from 2022-10-31 18-29-17](https://user-images.githubusercontent.com/105478884/198987270-2c37ef1b-ba9b-4a30-bff6-ed44b016d60d.png)

**In the case of estimating only one pose of a camera, the above code works correctly.** 
`for (int keyframe_id = 1; keyframe_id<2; keyframe_id++)`  <- 2 means the code estimate one pose of a camera.
**However, segmentation fault occurs when estimating multiple camera poses in my code.**
`for (int keyframe_id = 1; keyframe_id<3; keyframe_id++)`  <- 3 means the code estimate two pose of a camera.

According to similar issues on this repository such as [this link](https://github.com/ceres-solver/ceres-solver/issues/882) and [this one](https://github.com/ceres-solver/ceres-solver/issues/517), stack trace or traceback is needed for resolving this issue.
I can compile in debug mode. However, I am not familiar with these techniques. Would [this description](https://docs.google.com/document/d/1G9ZqS2jpDhieFb2h_jEYxsWyEZ8zJUjIBFqRvp-skk0/edit?usp=share_link) be stack trace or traceback?

To sum up, could you give me some advice for resolving this issue? And then, In what cases does segmentation fault at ceres::Solve() occur?

If my information is not sufficient, could you point out what is an insufficient description?

**EDIT**
Cost function is described in bundle_adjustment/include/bundle_adjustment/reprojection_factor.h

By the way, I found that segmentation fault occurred in the middle of optimization by ceres::Solve(). Please confirm the rotation element (this is shown in left side of the following images) in between before and after executing ceres::Solve(). 

Before executing ceres::Solve() 
![rotation_element_before_optimization](https://user-images.githubusercontent.com/105478884/199175518-b009b5bd-c570-4deb-b33d-04dbf680bda5.png)

After executing ceres::Solve() 
![rotation_element_after_optimization_with_segmentation_fault](https://user-images.githubusercontent.com/105478884/199175649-e3c61530-9964-4022-9539-d7ade359ac1e.png)

And then, I confirmed the cost function is reduced.
![cost function is reduced](https://user-images.githubusercontent.com/105478884/199176319-ea712ba3-7a5d-4026-bde5-185ced7cfe03.png)
![cost function is reduced2](https://user-images.githubusercontent.com/105478884/199176380-dc4da4d0-9d53-4784-859c-d5b9e1373a5c.png)

**Comment by sandwichmaker** [comment]
@saikyo-kotemen-master from your description it is not clear where the failure is.
I think you will need a ceres-solver build thats done in debug mode to be able to get a reasonable stacktrace.
I do not know how ros or catkin work, but as far as ceres solver goes, you should be able to make it by passing 

```
cmake -DCMAKE_BUILD_TYPE=Debug
```

when configuring ceres. that should work.

**Comment by alexsmac** [comment]
From what you are describing, your issue is that you were using `std::vector` to store parameters which you then passed to Ceres, but you were (implicitly) resizing the vector by calling `push_back()` *after* you had already passed pointers to elements of the vector to Ceres as parameter blocks.  Resizing a `std::vector` invalidates all pointers to its elements which included the pointers that you had already passed to Ceres, but which (post-resize) point to unallocated memory addresses.

You can either initialise all of the parameters first s/t the `std::vector` will not change size and thus will not invalidate pointers to its elements, or you can call `reserve()` prior to a loop involving `push_back()` which would have the same effect

**Comment by zombie-k** [comment]
> 

Can you tell me how to fix it? I encountered the same problem, but I didn’t understand the specific problem and how to fix it.
@TakuOkawara
