### ISSUE TITLE
MaxNumberThreadsAvailable always returns 1, as provided by std::thread::hardware_concurrency 

### ISSUE THREAD

**Issue by sirspudd** [ceres-solver/ceres-solver#907]
We are seeing this on both armv7 and aarch64

gcc version 12.2.0 (GCC) as provided by yocto

**Comment by sandwichmaker** [comment]
Hi @sirspudd could you say more. Are you saying that the underlying stdlib call is lying? or that ceres-solver is doing something wrong?

**Comment by sirspudd** [comment]
Groovy; to be clear, I initially suspected bugginess in std::thread (further fueled by mingw bugs which reported the same issue in 2015)

but we have actually established that the calling thread had an explicit cpu affinity set, and hence std::thread::hardware_concurrency was actually returning a sane value. (We have an affinity for a single core on a multi-core device)

Don't mind me
