### ISSUE TITLE
setParameterLowerBound, double free or corrucption

### ISSUE THREAD

**Issue by icantfly** [ceres-solver/ceres-solver#910]
hello, recently i met a bug, when i use setParameterLowerBound()/setParameterUpperBound()。if i set the lower or upper bound, the solve will break down, get the "double free ot corrucption" at the second iter，i use gdb to find it break down in FindPolynomialRoots() in file polynomial.cc, line 236. It seems to break in ~EigenSolver(). So, i really do not konw how to fix this problem.

ps: ceres-solver version   2.0.0           eigen_version:    eigen3
when i do not set the lower or upper bound, it works normal.

Can someone help me to solve this problem please?
Thank you in advance.

**Comment by sandwichmaker** [comment]
Can you share a small reproduction?

**Comment by icantfly** [comment]
sorry, but our work use eigen::matrix<T, 4, 4> in ceres for point transform and rotation。

**Comment by sandwichmaker** [comment]
Sorry that's not enough to reason about this bug.

**Comment by icantfly** [comment]
Thank you for your apply.

**Comment by icantfly** [comment]
Making with -march=native seems to fixing the problem i met.
