### ISSUE TITLE
cuda_kernels.cu.cc(33): error: qualified name is not allowed

### ISSUE THREAD

**Issue by yunfan258** [ceres-solver/ceres-solver#911]
when I run `cmake ..`,the followering detail occured

`-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_BIGOBJ
-- Performing Test HAVE_BIGOBJ - Failed
-- Looking for pow in m
-- Looking for pow in m - found
-- Detected Ceres version: 2.2.0 from /home/luofan/Downloads/ceres-solver-master/include/ceres/version.h
-- Detected available Ceres threading models: [CXX_THREADS, OPENMP, NO_THREADS]
-- Found Eigen version 3.3.7: /usr/lib/cmake/eigen3
-- Enabling use of Eigen as a sparse linear algebra library.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA version 10.1 installed in: /usr via legacy (< 3.17) CMake module. Using the legacy CMake module means that any installation of Ceres will require that the CUDA libraries be installed in a location included in the LD_LIBRARY_PATH.
-- The CUDA compiler identification is NVIDIA 10.1.243
-- Check for working CUDA compiler: /usr/bin/nvcc
-- Check for working CUDA compiler: /usr/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for dgemm_
-- Looking for dgemm_ - found
-- Found BLAS: /usr/lib/x86_64-linux-gnu/libf77blas.so;/usr/lib/x86_64-linux-gnu/libatlas.so  
-- Found LAPACK library: /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libf77blas.so;/usr/lib/x86_64-linux-gnu/libatlas.so
-- Found CHOLMOD headers in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found SPQR headers in: /usr/include/suitesparse
-- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Found Config headers in: /usr/include/suitesparse
-- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Found AMD headers in: /usr/include/suitesparse
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found CAMD headers in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CCOLAMD headers in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found COLAMD headers in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found Intel Thread Building Blocks (TBB) library (2020.1 / 11101) include location: /usr/include. Assuming SuiteSparseQR was compiled with TBB.
-- Looking for shm_open in rt
-- Looking for shm_open in rt - found
-- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Could NOT find METIS (missing: METIS_INCLUDE_DIR METIS_LIBRARY) 
-- Found SuiteSparse: /usr/include/suitesparse (found suitable version "5.7.1", minimum required is "4.5.6") found components: CHOLMOD SPQR Config AMD CAMD CCOLAMD COLAMD missing components: Partition
-- Found SuiteSparse 5.7.1, building with SuiteSparse.
-- Could NOT find METIS (missing: METIS_INCLUDE_DIR METIS_LIBRARY) 
-- Did not find METIS, disabling Eigen METIS support.
-- Building without Apple's Accelerate sparse support.
-- Found Google Flags (gflags) version 2.2.2: /usr/lib/x86_64-linux-gnu/cmake/gflags
-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
-- Found Glog: /usr/include  
-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
-- Using Ceres threading model: CXX_THREADS
-- Failed to find Google benchmark library, disabling build of benchmarks.
-- Building Ceres as a static library.
-- No build type specified; defaulting to CMAKE_BUILD_TYPE=Release.
-- Performing Test CHECK_CXX_FLAG_Wmissing_declarations
-- Performing Test CHECK_CXX_FLAG_Wmissing_declarations - Success
-- Performing Test CHECK_CXX_FLAG_Wno_unknown_pragmas
-- Performing Test CHECK_CXX_FLAG_Wno_unknown_pragmas - Success
-- Performing Test CHECK_CXX_FLAG_Wno_sign_compare
-- Performing Test CHECK_CXX_FLAG_Wno_sign_compare - Success
-- Performing Test CHECK_CXX_FLAG_Wno_unused_parameter
-- Performing Test CHECK_CXX_FLAG_Wno_unused_parameter - Success
-- Performing Test CHECK_CXX_FLAG_Wno_missing_field_initializers
-- Performing Test CHECK_CXX_FLAG_Wno_missing_field_initializers - Success
-- Creating configured Ceres config.h output directory: /home/luofan/Downloads/ceres-solver-master/build/include/ceres/internal
-- Enabling CERES_USE_EIGEN_SPARSE in Ceres config.h
-- Enabling CERES_NO_ACCELERATE_SPARSE in Ceres config.h
-- Enabling CERES_USE_CXX_THREADS in Ceres config.h
-- Enabling CERES_NO_CHOLMOD_PARTITION in Ceres config.h
-- Enabling CERES_NO_EIGEN_METIS in Ceres config.h
-- Performing Test CHECK_CXX_FLAG_Wno_missing_declarations
-- Performing Test CHECK_CXX_FLAG_Wno_missing_declarations - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Build the examples.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/luofan/Downloads/ceres-solver-master/build

`

then, I run `make -j3`

`
/home/luofan/Downloads/ceres-solver-master/internal/ceres/cuda_kernels.cu.cc(33): error: qualified name is not allowed

1 error detected in the compilation of "/tmp/tmpxft_00016f6a_00000000-6_cuda_kernels.cu.cpp1.ii".
make[2]: *** [internal/ceres/CMakeFiles/ceres_cuda_kernels.dir/build.make:63: internal/ceres/CMakeFiles/ceres_cuda_kernels.dir/cuda_kernels.cu.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3139: internal/ceres/CMakeFiles/ceres_cuda_kernels.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  0%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_2_3.cc.o
[  0%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_2_2.cc.o
[  0%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_2_4.cc.o
[  0%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_2_d.cc.o
[  0%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_3_3.cc.o
[  1%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_3_4.cc.o
[  1%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_3_6.cc.o
[  1%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_3_9.cc.o
[  1%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_3_d.cc.o
[  1%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_4_3.cc.o
[  2%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_4_4.cc.o
[  2%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_4_6.cc.o
[  2%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_4_8.cc.o
[  2%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_4_9.cc.o
[  2%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_4_d.cc.o
[  2%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_d_d.cc.o
[  3%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_3_3_3.cc.o
[  3%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_4_4_2.cc.o
[  3%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_4_4_3.cc.o
[  3%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_4_4_4.cc.o
[  3%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_4_4_d.cc.o
[  4%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_d_d_d.cc.o
[  4%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_2_2.cc.o
[  4%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_2_3.cc.o
[  4%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_2_4.cc.o
[  4%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_2_d.cc.o
[  4%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_3_3.cc.o
[  5%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_3_4.cc.o
[  5%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_3_6.cc.o
[  5%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_3_9.cc.o
[  5%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_3_d.cc.o
[  5%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_4_3.cc.o
[  6%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_4_4.cc.o
[  6%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_4_6.cc.o
[  6%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_4_8.cc.o
[  6%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_4_9.cc.o
[  6%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_4_d.cc.o
[  6%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_d_d.cc.o
[  7%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_3_3_3.cc.o
[  7%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_4_4_2.cc.o
[  7%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_4_4_3.cc.o
[  7%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_4_4_4.cc.o
[  7%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_4_4_d.cc.o
[  8%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_d_d_d.cc.o
[  8%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/parallel_for_cxx.cc.o
[  8%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/thread_pool.cc.o
[  8%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/accelerate_sparse.cc.o
[  8%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/array_utils.cc.o
[  8%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_evaluate_preparer.cc.o
[  9%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_jacobi_preconditioner.cc.o
[  9%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_jacobian_writer.cc.o
[  9%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_random_access_dense_matrix.cc.o
[  9%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_random_access_diagonal_matrix.cc.o
[  9%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_random_access_matrix.cc.o
[ 10%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_random_access_sparse_matrix.cc.o
[ 10%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_sparse_matrix.cc.o
[ 10%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_structure.cc.o
[ 10%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/callbacks.cc.o
[ 10%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/canonical_views_clustering.cc.o
[ 10%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/cgnr_solver.cc.o
[ 11%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/compressed_col_sparse_matrix_utils.cc.o
[ 11%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/compressed_row_jacobian_writer.cc.o
[ 11%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/compressed_row_sparse_matrix.cc.o
[ 11%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/conditioned_cost_function.cc.o
[ 11%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/context.cc.o
[ 12%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/context_impl.cc.o
[ 12%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/coordinate_descent_minimizer.cc.o
[ 12%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/corrector.cc.o
[ 12%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/cost_function.cc.o
[ 12%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/covariance.cc.o
[ 12%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/covariance_impl.cc.o
[ 13%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/cuda_sparse_matrix.cc.o
[ 13%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/cuda_vector.cc.o
[ 13%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dense_cholesky.cc.o
[ 13%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dense_normal_cholesky_solver.cc.o
[ 13%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dense_qr.cc.o
[ 14%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dense_qr_solver.cc.o
[ 14%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dense_sparse_matrix.cc.o
[ 14%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/detect_structure.cc.o
[ 14%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dogleg_strategy.cc.o
[ 14%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dynamic_compressed_row_jacobian_writer.cc.o
[ 14%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dynamic_compressed_row_sparse_matrix.cc.o
[ 15%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dynamic_sparse_normal_cholesky_solver.cc.o
[ 15%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/eigensparse.cc.o
[ 15%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/evaluation_callback.cc.o
[ 15%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/evaluator.cc.o
[ 15%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/fake_bundle_adjustment_jacobian.cc.o
[ 16%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/file.cc.o
[ 16%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/first_order_function.cc.o
[ 16%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/float_suitesparse.cc.o
[ 16%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/function_sample.cc.o
[ 16%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/gradient_checking_cost_function.cc.o
[ 17%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/gradient_problem_solver.cc.o
[ 17%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/implicit_schur_complement.cc.o
[ 17%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/inner_product_computer.cc.o
[ 17%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/is_close.cc.o
[ 17%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/iteration_callback.cc.o
[ 17%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/iterative_refiner.cc.o
^[[A[ 18%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/iterative_schur_complement_solver.cc.o
[ 18%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/levenberg_marquardt_strategy.cc.o
[ 18%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/line_search.cc.o
[ 18%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/line_search_direction.cc.o
[ 18%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/line_search_minimizer.cc.o
[ 19%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/line_search_preprocessor.cc.o
[ 19%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/linear_least_squares_problems.cc.o
[ 19%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/linear_operator.cc.o
[ 19%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/linear_solver.cc.o
[ 19%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/low_rank_inverse_hessian.cc.o
[ 19%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/minimizer.cc.o
[ 20%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/parallel_utils.cc.o
[ 20%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/parameter_block_ordering.cc.o
[ 20%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/partitioned_matrix_view.cc.o
[ 20%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/polynomial.cc.o
[ 20%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/power_series_expansion_preconditioner.cc.o
[ 21%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/preconditioner.cc.o
[ 21%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/preprocessor.cc.o
[ 21%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/problem_impl.cc.o
[ 21%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/program.cc.o
[ 21%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/reorder_program.cc.o
[ 21%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/residual_block.cc.o
[ 22%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/residual_block_utils.cc.o
[ 22%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/schur_complement_solver.cc.o
[ 22%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/schur_eliminator.cc.o
[ 22%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/schur_jacobi_preconditioner.cc.o
[ 22%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/schur_templates.cc.o
[ 23%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/scratch_evaluate_preparer.cc.o
[ 23%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/single_linkage_clustering.cc.o
[ 23%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/solver_utils.cc.o
[ 23%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/sparse_cholesky.cc.o
[ 23%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/sparse_matrix.cc.o
[ 23%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/sparse_normal_cholesky_solver.cc.o
[ 24%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/stringprintf.cc.o
[ 24%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/subset_preconditioner.cc.o
[ 24%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/suitesparse.cc.o
[ 24%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/thread_token_provider.cc.o
[ 24%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/triplet_sparse_matrix.cc.o
[ 25%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/trust_region_minimizer.cc.o
[ 25%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/trust_region_preprocessor.cc.o
[ 25%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/trust_region_step_evaluator.cc.o
[ 25%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/trust_region_strategy.cc.o
[ 25%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/visibility.cc.o
[ 25%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/visibility_based_preconditioner.cc.o
[ 26%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/wall_time.cc.o
[ 26%] Built target ceres_internal
make: *** [Makefile:141: all] Error 2

`

could you please tell me how to solve this problem?thank you very much

**Comment by sandwichmaker** [comment]
@joydeep-b more cuda fun. Please take a look.

**Comment by joydeep-b** [comment]
Yup, I am aware of this issue. IIRC this is the summary:
0. This is an issue with nested namespaces, which is a C++17 extension.
1. The nvcc compiler is technically supposed to support C++17, which includes nested namespaces.
2. However, in practice, some versions of the nvcc compiler, including on older Jetson devices, chokes on the nested namespace declaration.

The two resolutions I can see are:
1. Revert to non-nested namespaces
2. Break support for older nvcc versions - this will break support for older Jetson devices 
@sandwichmaker Which would you recommend?

**Comment by sandwichmaker** [comment]
I think it is unreasonable to go back on c++17 features. We should have a minimum nvcc version that is sane and restrict support to that.

**Comment by yunfan258** [comment]
(base) luofan@luofan-Precision-3630-Tower:~/Downloads/ceres-solver-master/build$ `nvidia-smi`

Thu Nov 10 13:11:38 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P4000        Off  | 00000000:01:00.0  On |                  N/A |
| 49%   48C    P0    27W / 105W |   6378MiB /  8111MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1231      G   /usr/lib/xorg/Xorg                 39MiB |
|    0   N/A  N/A      1720      G   /usr/lib/xorg/Xorg                261MiB |
|    0   N/A  N/A      1857      G   /usr/bin/gnome-shell               44MiB |
|    0   N/A  N/A      9225      G   ...RendererForSitePerProcess       34MiB |
|    0   N/A  N/A      9925      G   /usr/lib/firefox/firefox          145MiB |
|    0   N/A  N/A     22754      C   ...3/envs/pytorch/bin/python     1169MiB |
|    0   N/A  N/A     23018      G   ...nlogin/bin/sunloginclient        4MiB |
|    0   N/A  N/A     91903      G   gnome-control-center                2MiB |
|    0   N/A  N/A     97686      C   ...3/envs/pytorch/bin/python     4663MiB |
+-----------------------------------------------------------------------------+
WARNING: infoROM is corrupted at gpu 


(base) luofan@luofan-Precision-3630-Tower:~/Downloads/ceres-solver-master/build$ `nvcc -V`

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

=======================================================================================

my gcc and g++ version is 9.4.0. Is it the error of gcc or g++? If so, which version of gcc/g++ should I use?

**Comment by yunfan258** [comment]
**(base) luofan@luofan-Precision-3630-Tower:~/Downloads/ceres-solver-master/build$ `nvidia-smi`**

Thu Nov 10 13:11:38 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03 Driver Version: 470.141.03 CUDA Version: 11.4 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
| | | MIG M. |
|===============================+======================+======================|
| 0 Quadro P4000 Off | 00000000:01:00.0 On | N/A |
| 49% 48C P0 27W / 105W | 6378MiB / 8111MiB | 0% Default |
| | | N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes: |
| GPU GI CI PID Type Process name GPU Memory |
| ID ID Usage |
|=============================================================================|
| 0 N/A N/A 1231 G /usr/lib/xorg/Xorg 39MiB |
| 0 N/A N/A 1720 G /usr/lib/xorg/Xorg 261MiB |
| 0 N/A N/A 1857 G /usr/bin/gnome-shell 44MiB |
| 0 N/A N/A 9225 G ...RendererForSitePerProcess 34MiB |
| 0 N/A N/A 9925 G /usr/lib/firefox/firefox 145MiB |
| 0 N/A N/A 22754 C ...3/envs/pytorch/bin/python 1169MiB |
| 0 N/A N/A 23018 G ...nlogin/bin/sunloginclient 4MiB |
| 0 N/A N/A 91903 G gnome-control-center 2MiB |
| 0 N/A N/A 97686 C ...3/envs/pytorch/bin/python 4663MiB |
+-----------------------------------------------------------------------------+
WARNING: infoROM is corrupted at gpu

**(base) luofan@luofan-Precision-3630-Tower:~/Downloads/ceres-solver-master/build$ `nvcc -V`**

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

##################################################################################
@sandwichmaker @joydeep-b 

**My gcc and g++ version are 9.4.0. Is it the error of gcc or g++? If so, which version of gcc/g++ should I use?**

**Comment by joydeep-b** [comment]
@yunfan258 The issue is with the version of nvcc. From the logs, it seems you are using Cuda 10.1, which is quite old. Can you upgrade to the latest Cuda version (or at least 11.1+)?

**Comment by Cristian-wp** [comment]
Hello @joydeep-b, 
I am facing the same problem and I have read your solutions (https://github.com/ceres-solver/ceres-solver/issues/911#issuecomment-1308909863).
At the moment NVIDEA did not release an updated Jetpack with a Cuda version above the 10, and the last release was at 02/2022.
For what concern _Revert to non-nested namespaces_ there is a fork/branch of ceres with this retrocompatibility?
In case this is not existing, It can be done with some little changes by the user or is a complex thing to perform?

**Comment by joydeep-b** [comment]
The latest Nvidia Jetpack 5.0 actually runs Cuda 11.4: https://developer.nvidia.com/embedded/jetpack
However, it only supports the newer boards (Xavier +, as far as I can tell).

You can make local modifications to bypass this:
1. Change the namespace in `cuda_kernels.*` to not used nested namespaces (e.g. use `ceres_internal`)
2. Add the prefix `ceres_internal::` to all uses of the exported functions

This should suffice.

**Comment by Cristian-wp** [comment]
I know that some time ago CUDA 11 was released for some Jetson device, but at the moment mu Jetson Nano 4G is not supported and can not be upgraded manually.
I will try your procedure and let you know.
Thanks

**Comment by sandwichmaker** [comment]
I think if this problem is limited to cu.cc files, then I think it is okay to not use nested name spaces there. I would happily accept a patch to fix this.

**Comment by joydeep-b** [comment]
I'm testing it out, will send a patch your way accordingly, @sandwichmaker .

**Comment by Cristian-wp** [comment]
@sandwichmaker @joydeep-b  Thankyou very much

**Comment by sandwichmaker** [comment]
This is fixed at head now.
