### ISSUE TITLE
Autodiff and gradient check problem!

### ISSUE THREAD

**Issue by rick137-1** [ceres-solver/ceres-solver#917]
Hi，when i use autodiff built my cost function , and use gradient check , encountered a problem . My problem : use gradient check , Worst relative error was 0.202196 , is it a normal ? This problem use quaternion,will it have an impact?

![image](https://user-images.githubusercontent.com/54990141/201520941-f008b668-3a6c-43f6-a64c-b2fb50e243c6.png)
By the way, I didn't define jacobin by myself , and when i write the jacobin , the problem is worse！
I hope you can provide guidance and suggestions，thanks！

Here is my cost function and problem build.
![img_v2_1e3e6d4f-e846-453c-80dd-c1e17578c08g](https://user-images.githubusercontent.com/54990141/201520865-e5b75c4c-827a-4b55-8e7d-bd9439779cee.png)
![img_v2_48635633-2645-42b4-b4c9-96ae974f4ccg](https://user-images.githubusercontent.com/54990141/201520881-856ea6fb-6be2-4479-852c-734c60e89068.png)

**Comment by sandwichmaker** [comment]
I am not sure what you are asking here. Are you saying you have a jacobian with automatic differentiation which fails gradient checker?

**Comment by sandwichmaker** [comment]
Closing because of lack of followup.
