### ISSUE TITLE
Support for equality constraints

### ISSUE THREAD

**Issue by sandwichmaker** [ceres-solver/ceres-solver#92]
Original [issue 91](https://code.google.com/p/ceres-solver/issues/detail?id=91) created by sandwichmaker on 2013-03-05T21:03:22.000Z:

Allow Ceres Solver to deal with equality constraints using the augmented lagrangian.

**Comment by mojovski** [comment]
Are there any updates on this? On the other hand, can someone suggest a roadmap how to implement this? Is it possible to extend the cost function to achieve this?
The feature would be really helpful to enable sfm from fixed multiview camera rigs.

**Comment by sandwichmaker** [comment]
For fixed multiview camera rigs, consider using shared parameters across cameras. we do multiview rig calibration using ceres all the time and we have not found the need for equality constraints.

The correct roadmap for this involves some sort of Sequentual Quadratic Programming based solver. There is no way to extend the cost function to achieve this. The SQP based approach is a significant technical undertaking.

**Comment by mojovski** [comment]
@sandwichmaker, thanks for your comment! Could you provide some reference which ceres-api to use in order to inject constant relative rotation and translation between cameras?
Thanks alot!

**Comment by sandwichmaker** [comment]
This is the wrong place to have a discussion on ceres usage. I recommend you post this on the ceres mailinglist and we can discuss it there.

**Comment by mojovski** [comment]
Thanks! I will have a look here. https://groups.google.com/forum/#!searchin/ceres-solver/fixed$20relative$20rotation/ceres-solver/rcicQU5S5p0/3HBURSlfd5EJ

**Comment by sandwichmaker** [comment]
Closing because currently there is no plan to work on this.
