### ISSUE TITLE
how to implement factors with unkown number of parameters af compile time?

### ISSUE THREAD

**Issue by tanjunyao7** [ceres-solver/ceres-solver#920]
Is it possible to implement a residual which depends on varying number of parameters that can be determined only at run time?

**Comment by sandwichmaker** [comment]
Yes. Only autodiffcostfunction and numericdiffcostfunctions require static
parameter block sizes and numbers. If you are willing to compute your own
derivatives then you can use the costfunction interface which has no such
restrictions. Even for automatic derivatives you can use
dynamicautodiffcostfunction.

**Comment by tanjunyao7** [comment]
> 

oh, when was dynamicautodiffcostfunction added? I never saw it in the documentation. that's exactly what I need, thanks.
