### ISSUE TITLE
How to check if Ceres Solver is using NVIDEA GPU

### ISSUE THREAD

**Issue by Cristian-wp** [ceres-solver/ceres-solver#921]
Hello,
I am working on an NVIDEA Jetson Nano 4Gb with ceres.
I have manage to install it and run the tests.
Now I am using the board to run a ceres based slam system, that use as loss_function: CHAUCHY and as linear_solver_type: DENSE_QR.
There is a ceres utility to see when is using the GPU?
NVIDEA provide its utility but is really difficult to understand.
The setup of my board is reported in this question:  [https://github.com/ceres-solver/ceres-solver/issues/909](url)

**Comment by sandwichmaker** [comment]
cc: @joydeep-b

**Comment by joydeep-b** [comment]
@Cristian-wp If you look at the solver summary, it will tell you if it used the CUDA solver.

**Comment by Cristian-wp** [comment]
@joydeep-b where I can find the solver summary?
This is not a code that I write, I have to look in some particular folder or simply put a print in some point?
Sorry for the dummy questions.

**Comment by joydeep-b** [comment]
To use the GPU for your problem, you need to set the `dense_linear_algebra_library` to `CUDA`.
Please see the tutorials on how to print the Ceres solver summary.

**Comment by sandwichmaker** [comment]
I am going to close this issue, if you have further questions please feel free to open a new issue.
