### ISSUE TITLE
Collecting residual block for each iteration

### ISSUE THREAD

**Issue by Miuna26** [ceres-solver/ceres-solver#925]
I have a little question.Can I get the residual block(actually the residual vector about the whole problem) for each iteration?For example,I bulit up a problem with n dimension residual vector,and I want to get n dimension vector for each iteration so that I can know any one residual in vector for any one iteration.
Sincerely looking forward to your answer.

**Comment by alexsmac** [comment]
Not directly through the Ceres API, but you can create an [IterationCallback](http://ceres-solver.org/nnls_solving.html#iterationcallback) and set `Solver::Options::update_state_every_iteration` to true, then the current value of all parameter blocks will be copied back to the user-specified pointers before your IterationCallback is invoked (at the end of the iteration).  You can then log the parameter block values per iteration however you like from within your IterationCallback.  After completion of the optimisation, as a post-processing step you can then use Problem::Evaluate() to iterate back through the logged parameter block values per iteration and determine the residual values per iteration.

**Comment by Miuna26** [comment]
> Not directly through the Ceres API, but you can create an [IterationCallback](http://ceres-solver.org/nnls_solving.html#iterationcallback) and set `Solver::Options::update_state_every_iteration` to true, then the current value of all parameter blocks will be copied back to the user-specified pointers before your IterationCallback is invoked (at the end of the iteration). You can then log the parameter block values per iteration however you like from within your IterationCallback. After completion of the optimisation, as a post-processing step you can then use Problem::Evaluate() to iterate back through the logged parameter block values per iteration and determine the residual values per iteration.

Thanks a lot!I will give it a try and we'll see. Much appreciated again!
