### ISSUE TITLE
NumSuccessfulSteps is alway max_num_iteration + 1

### ISSUE THREAD

**Issue by dongyy1148** [ceres-solver/ceres-solver#926]
Hi team,

I used Ceres solver for solving non linear least squares problems and the optimization looks fine, However, there is a glitch that  NumSuccessfulSteps is alway num_iter + 1. For example, if I set the max_iteration to be 2, in the full report I can see iter 0 to iter 2. And the message "Terminating: Maximum number of iterations reached. Number of iterations: 2." which is correct. However, in the following parts, Minimizer iterations and Successful steps are both 3. Do they count the iter 0 in the Successful steps as well? Please help.

**Comment by sandwichmaker** [comment]
yes.
