### ISSUE TITLE
Building Ceres Fails.

### ISSUE THREAD

**Issue by vimalsheoranifcp** [ceres-solver/ceres-solver#931]
I've been trying to build Ceres on a VM using the instructions provided [here](http://ceres-solver.org/installation.html). Everything till the `cmake` steps seems to be working correctly. However, when I perform `make -j3` I get the following error.

```
/home/jupyter/ceres-solver/internal/ceres/cuda_vector.cc:55:3:   required from here
/usr/include/glog/logging.h:638:9: error: ambiguous overload for ‘operator<<’ (operand types are ‘std::ostream’ {aka ‘std::basic_ostream<char>’} and ‘std::nullptr_t’)
   (*os) << v;
   ~~~~~~^~~~
In file included from /usr/include/glog/logging.h:43,
                 from /home/jupyter/ceres-solver/internal/ceres/concurrent_queue.h:39,
                 from /home/jupyter/ceres-solver/internal/ceres/thread_pool.h:39,
                 from /home/jupyter/ceres-solver/internal/ceres/context_impl.h:52,
                 from /home/jupyter/ceres-solver/internal/ceres/cuda_vector.cc:40:
```

I have the following configurations,
OS: **Debian 10 (Buster)**
CUDA: **11.0.221**
g++: **8.3.0**

**Comment by alexsmac** [comment]
I think you're hitting [this problem](https://github.com/google/glog/issues/562) that was fixed in glog in [this PR](https://github.com/google/glog/pull/641).  If you're using the default glog package in Debian 10, I think that would be too old to get this fix, so you would need to use a newer version.

**Comment by bkkim** [comment]
I have occurred the same problem. so I changed the USE_CUDA option to OFF in the CMakeLists.txt. And I made it building without cuda. and Then the error was solved.
