### ISSUE TITLE
Is there any way to add weight to each residual block out of residual function?

### ISSUE THREAD

**Issue by ZhangZh3ng** [ceres-solver/ceres-solver#932]
I need to add weight to residual block, so the cost function may like this:
![image](https://user-images.githubusercontent.com/63040423/207554919-5a94ae7c-6e20-4b0f-8a67-08643b4c4d12.png)
It just has an additional weight (can be computed previously) item 'wi' compared with the original. Since I also need to use loss function,  if I add the weight into 'Evaluate' function when computing residual, it will has side-effect. So is that possible to add this weight out of residual function?

**Comment by sandwichmaker** [comment]
Have a look at `ScaledLoss`

https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/loss_function.h#L330
