### ISSUE TITLE
Building on Android issues - Cannot find definitions

### ISSUE THREAD

**Issue by lukkio88** [ceres-solver/ceres-solver#940]
Hello,

Related to this question:
https://stackoverflow.com/questions/74959616/cannot-find-identifiers-when-compiling-android-project-in-visual-studio

I can generate the visual studio solution using the line in the snippet. But when I try to build the examples in Visual Studio I get a bunch of errors.

I've tried few options (like changing the android API with several versions and the C++, like 'c++_shared, c++_static, system'). Still I cannot manage to build for Android (using Visual Studio).

Can anyone help?

Thank you

**Comment by sandwichmaker** [comment]
@sergiud @alexsmac any idea what maybe going on?

**Comment by sergiud** [comment]
This is a follow-up to #939. The warnings and errors still indicate that there's something wrong with the NDK environment.

@lukkio88 Are you even able to successfully cross-compile different projects using a comparable setup (e.g., gflags or glog)?

**Comment by lukkio88** [comment]
I can compile on desktop fine. I also run the bundle adjustment example you mention in your page.
I also suspect might be an issue with the NDK somewhat.

What I am trying to do now is to use MinGW rather than Visual Studio (though I would prefer visual studio).

I would appreciate some suggestions (links of whatever). Because I have android projects, not related to Ceres and android studio works fine and I can build projects fine. 

The ceres page you have to me doesn't give an example so it's really hard for me to figure out what the issue is.

I'll stick with my attempt in the meanwhile.

**Comment by sergiud** [comment]
> I can compile on desktop fine.

That is not what I'm asking. My question is whether you are able to compile projects other than Ceres using the Visual Studio+NDK combination?

> I would appreciate some suggestions (links of whatever). Because I have android projects, not related to Ceres and android studio works fine and I can build projects fine.

You totally lost me here. Are you trying to use Visual Studio or Android Studio? These are two completely different IDEs.

Regardless, there is not indication whatsoever that the issue you are experiencing is related to Ceres. In particular, our [Android CI pipeline](https://github.com/ceres-solver/ceres-solver/actions/workflows/android.yml) builds without problems. Therefore, posting your question on the Visual Studio community forums or CMake discourse might be a better idea.

**Comment by lukkio88** [comment]
I am trying on Visual studio+NDK. The Ceres Projects are the only ones I've tried on Visual Studio.

I'll try to build something simple using Visual Studio + NDK.

I'll ask the VS community for support. Thank you.

I would however make the Android Studio session of the ceres page a bit more verbose (this is a suggestion for what is worth).

**Comment by lukkio88** [comment]
I managed to build. Obviously I was doing something stupid with the NDK. This line made it work. Although you say it's not related to Ceres I'll leave the line here just a reference for someone else.

`cmake -G "Visual Studio 16" -A arm64 -DCMAKE_PREFIX_PATH=D:\DEV\ceres\gflags\build-gflags -DCMAKE_TOOLCHAIN_FILE="C:\Microsoft\AndroidNDK64\android-ndk-r16b\build\cmake\android.toolchain.cmake" -DEigen3_DIR=D:\DEV\ceres\eigen\build -DANDROID_ABI=arm64-v8a -DANDROID_STL=c++_shared -DANDROID_NATIVE_API_LEVEL=android-24 -DBUILD_SHARED_LIBS=ON -DMINIGLOG=ON -DCMAKE_CXX_STANDARD=14 D:\DEV\ceres\ceres-solver-2.1.0`

There's a project which however doesn't build `curve_fitting_c`. I don't know why. But the libraries for Ceres are generated.

How am I supposed to use these examples on Android? Should create an android project with JNI interface calling the C++?

**Comment by sergiud** [comment]
To make sure I understand: the resolution was not mix the toolchain file and the NDK distribution (i.e., NDK root directory)?

> There's a project which however doesn't build `curve_fitting_c`. I don't know why.

What output do you get when you try to compile this target?

> How am I supposed to use these examples on Android? Should create an android project with JNI interface calling the C++?

The examples are not meant to be executed directly on Android. You need to generate a corresponding APK first which drives the native code, e.g., using JNI bindings. However, this is out of the project's scope.

**Comment by lukkio88** [comment]
> To make sure I understand: the resolution was not mix the toolchain file and the NDK distribution (i.e., NDK root directory)?
> 
> > There's a project which however doesn't build `curve_fitting_c`. I don't know why.
> 
> What output do you get when you try to compile this target?
> 
> > How am I supposed to use these examples on Android? Should create an android project with JNI interface calling the C++?
> 
> The examples are not meant to be executed directly on Android. You need to generate a corresponding APK first which drives the native code, e.g., using JNI bindings. However, this is out of the project's scope.

I don't want the issue exactly is. Because regardless of the root directory been used it was r16b both cases. However changing the root directory for the toolchaing with the one visual studio comes with solved it.

As I said I am not an android expert and I am learning.

For the examples I think you confirmed my thought.

And again I know this was probably stupid therefore sorry for wasting your time.

**Comment by sergiud** [comment]
That's fine. I guess we can close the issue now since there's nothing to be done in Ceres.

In case you have a specific suggestion for improving the documentation, please open a new issue.
