### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by fsxy1063200037** [ceres-solver/ceres-solver#944]
![IMG20230117164438](https://user-images.githubusercontent.com/40689161/212850615-f1f0988d-cb33-403b-a7b9-70976f0b75fb.png)
This problem occurs when testing the HelloWorld.cc file. How can I solve it？

**Comment by sandwichmaker** [comment]
you have some kind of uninitialized memory. hard to debug it from just this stack trace.

**Comment by sandwichmaker** [comment]
Ignore my previous comment, is this with an unmodified helloworld.cc that ships with ceres?

**Comment by sandwichmaker** [comment]
I do not understand the stack trace, because why is residual call back resulting in iterationcallback being called. This looks like some kind of memory corruption.

**Comment by sandwichmaker** [comment]
Closing because lack of response. Please feel free to reopen if there are more details.
