### ISSUE TITLE
undefined reference to `google::base::CheckOpMessageBuilder::NewString()'

### ISSUE THREAD

**Issue by gitouni** [ceres-solver/ceres-solver#945]
Dear Authors:
        I found another possibility that can cause problem https://github.com/ceres-solver/ceres-solver/issues/291#issue-234908608. If you compile **Open3D** and **ceres** in **one** cpp file, it will cause `google::base::CheckOpMessageBuilder::NewString()` undefined error. It's a shame that I'm just a beginner at ceres -solver, but I can share my problem here to remind others of another possible cause of this error.
# Environment
Ubuntu 20.04
ceres 2.1.0
Open3D 0.16.0
CMake 3.25.0
gcc 9.4.0

# cpp file
```cpp
#include <iostream>
#include <opencv2/opencv.hpp>
#include <ceres/ceres.h>
#include <chrono>

using namespace std;
using namespace cv;

// 代价函数的计算模型
struct CURVE_FITTING_COST
{
    const double _x, _y;    // x,y数据

    CURVE_FITTING_COST(double x, double y) : _x(x), _y(y) {}
    // 残差的计算
    template <typename T>
    bool operator()(const T* const abc, T* residual) const     // 残差
    {
        residual[0] = T(_y) - ceres::exp(abc[0] * T(_x) * T(_x) + abc[1] * T(_x) + abc[2]); // y-exp(ax^2+bx+c)
        return true;
    }

};

int main( int argc, char** argv )
{
    double a = 1.0, b = 2.0, c = 1.0;           // 真实参数值
    int N = 100;                                // 数据点
    double w_sigma=1.0;                         // 噪声Sigma值
    RNG rng;                                    // OpenCV随机数产生器
    double abc[3] = {0, 0, 0};                  // abc参数的估计值

    vector<double> x_data, y_data;              // 数据

    cout << "generating data: " << endl;
    for(int i=0; i<N; i++)
    {
        double x = i / 100.0;
        double y = exp(a * x * x + b * x + c) + rng.gaussian(w_sigma);
        x_data.push_back(x);
        y_data.push_back(y);
        cout << x_data[i] << " " << y_data[i] << endl;
    }

    // 构建最小二乘问题
    ceres::Problem problem;
    for(int i=0; i<N; i++)
    {
        problem.AddResidualBlock(     // 向问题中添加误差项
                // 使用自动求导，模板参数：误差类型，输出维度，输入维度，维数要与前面struct中一致
                new ceres::AutoDiffCostFunction<CURVE_FITTING_COST, 1, 3>(
                        new CURVE_FITTING_COST(x_data[i], y_data[i])
                ),
                nullptr,            // 核函数，这里不使用，为空
                abc                 // 待估计参数
        );
    }

    // 配置求解器
    ceres::Solver::Options options;     // 这里有很多配置项可以填
    options.linear_solver_type = ceres::DENSE_QR;  // 增量方程如何求解
    options.minimizer_progress_to_stdout = false;   // 输出到cout

    ceres::Solver::Summary summary;                // 优化信息
    chrono::steady_clock::time_point t1 = chrono::steady_clock::now();
    ceres::Solve(options, &problem, &summary);  // 开始优化
    chrono::steady_clock::time_point t2 = chrono::steady_clock::now();
    chrono::duration<double> time_used = chrono::duration_cast<chrono::duration<double>>(t2-t1);
    cout << "solve time cost = " << time_used.count()<< " seconds. " << endl;

    // 输出结果
    cout << summary.BriefReport() << endl;
    cout << "estimated a,b,c = ";
    for(auto a:abc)
        cout << a << " ";
    cout << endl;

    return 0;
}
```
# CMakeLists.txt
```CMake
########### 设置版本
cmake_minimum_required(VERSION 3.13)
set(CMAKE_CXX_STANDARD 17)

set(Open3D_DIR /home/ouni/open3d_install/lib/cmake/Open3D)
find_package(Open3D HINTS REQUIRED)
########### 设置项目名称
project(curve_fitting_ceres)

########### 添加库
# opencv
find_package(OpenCV REQUIRED)

# Ceres
find_package(Ceres REQUIRED)
include_directories(${CERES_INCLUDE_DIRS}
${OpenCV_INCLUDE_DIRS}
${CERES_INCLUDE_DIRS}
)

########### 编译可执行文件
add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} ${OpenCV_LIBS} ${CERES_LIBRARIES} ${Open3D_LIBRARIES})
# No bug will emerge if this line is rewritten as "target_link_libraries(${PROJECT_NAME} ${OpenCV_LIBS} ${CERES_LIBRARIES} ) "
```
# Error
```
/usr/bin/ld: CMakeFiles/curve_fitting_ceres.dir/main.cpp.o: in function `main':
main.cpp:(.text+0x438): undefined reference to `ceres::Solver::Summary::BriefReport() const'
/usr/bin/ld: CMakeFiles/curve_fitting_ceres.dir/main.cpp.o: in function `std::string* google::MakeCheckOpString<int, int>(int const&, int const&, char const*)':
main.cpp:(.text._ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc[_ZN6google17MakeCheckOpStringIiiEEPSsRKT_RKT0_PKc]+0x7f): undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/curve_fitting_ceres.dir/build.make:163：curve_fitting_ceres] 错误 1
make[1]: *** [CMakeFiles/Makefile2:83：CMakeFiles/curve_fitting_ceres.dir/all] 错误 2
make: *** [Makefile:91：all] 错误 2
```

The error can be avoided if the Open3D Library is removed in the last line in CMakeLists.txt, although someone may want to use them together when processing some Point Cloud problems.

**Comment by sergiud** [comment]
I'm not sure I understand the problem. Isn't the issue in Open3D if linking without this library works?

**Comment by gitouni** [comment]
> Isn't the issue in Open3D if linking without this library works?

Thanks for your reply.

Simply to say, the issue will emerge if I link Ceres-solver and Open3D together in one cpp executable file:
`target_link_libraries(${PROJECT_NAME} ${OpenCV_LIBS} ${CERES_LIBRARIES} ${Open3D_LIBRARIES})`
 even this cpp file does not have any code about Open3D.  

I guess the problem may be a default CMake setting of Open3D library conflicts with Ceres.

**Comment by sergiud** [comment]
While some details are missing, my guess is that Open3D links against a different version of glog than the one used to compile Ceres which eventually causes the undefined reference. Consequently, the problem is in your setup and not in Ceres which can be easily verified if you exclude Open3D from your build.

**Comment by gitouni** [comment]
> While some details are missing, my guess is that Open3D links against a different version of glog than the one used to compile Ceres which eventually causes the undefined reference. Consequently, the problem is in your setup and not in Ceres which can be easily verified if you exclude Open3D from your build.

Thanks for replying in a timely manner. I will inquire the authors of the Open3D library to figure it out.

**Comment by gitouni** [comment]
> While some details are missing, my guess is that Open3D links against a different version of glog than the one used to compile Ceres which eventually causes the undefined reference. Consequently, the problem is in your setup and not in Ceres which can be easily verified if you exclude Open3D from your build.

I have found the solution to this issue. The default installation directory of Open3D is ${HOME}/open3d_install. Chaning it to `/usr/local` can ensure Open3D and ceres-solver use the same version of `glog` and `gflag`:

```
cd Open3D
mkdir build && cd build 
cmake \
    -DBUILD_SHARED_LIBS=ON \
    -DPYTHON_EXECUTABLE=$(which python3) \
    -DBUILD_CUDA_MODULE=ON \
    -DGLIBCXX_USE_CXX11_ABI=ON \
    -DBUILD_LIBREALSENSE=ON  \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DBUILD_PYTORCH_OPS=OFF \
    -DBUILD_TENSORFLOW_OPS=OFF \
    -DBUNDLE_OPEN3D_ML=OFF \
    ../
make -j4
sudo make install 
```

Hope this commit can help someone.

**Comment by sergiud** [comment]
Great, thanks!
