### ISSUE TITLE
Incorrect flag name in CeresConfig.cmake

### ISSUE THREAD

**Issue by tnr00071** [ceres-solver/ceres-solver#946]
The error that is thrown is below, I included a fix. This issue seems to just effect the Ubuntu Debian release from Canonical. And is not present is builds from source. I opened an Ubuntu ticket also https://bugs.launchpad.net/ubuntu/+source/ceres-solver/+bug/2004515 

1. Description: Ubuntu 20.04.5 LTS
   Release: 20.04 (focal)
2. libceres-dev 1.14.0-4ubuntu1.1
3. Expected cmake project to build and find_package() to work
4. find_package() failed

```
Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found required Ceres dependency: Eigen version 3.3.7 in /usr/include/eigen3
-- Found required Ceres dependency: glog
CMake Error at /usr/lib/cmake/Ceres/CeresConfig.cmake:88 (message):
  Failed to find Ceres - Missing required Ceres dependency: gflags. Searched
  using GFLAGS_INCLUDE_DIR_HINTS: and gflags_DIR:
  /usr/lib/x86_64-linux-gnu/cmake/gflags.
Call Stack (most recent call first):
  /usr/lib/cmake/Ceres/CeresConfig.cmake:312 (ceres_report_not_found)
  CMakeLists.txt:46 (find_package)
```

To fix this in `/usr/lib/cmake/Ceres/CeresConfig.cmake` replace `GFLAGS_FOUND` with `Gflags_FOUND`.

**Comment by sergiud** [comment]
@sandwichmaker Are there any plans for updating the 1.14.x branch? If not, the issue is no longer relevant.

**Comment by sandwichmaker** [comment]
good point, no there are no plans like that.

**Comment by sergiud** [comment]
@tnr00071 The only viable resolution here is to update to Ceres 2.1.0.

**Comment by tnr00071** [comment]
Thanks for the support guys
