### ISSUE TITLE
How to reduce preprocessor time?

### ISSUE THREAD

**Issue by wsakobe** [ceres-solver/ceres-solver#947]
Hi, I would like to establish Ceres on a real-time project to optimize line functions. The size of residues and blocks is quite small and the optimization time is pretty good. But the preprocessing time became the longest procedure in this project. I'm willing to know that if there is any method to reduce the preprocessor time. Thanks.

Here is the full report:
Solver Summary (v 2.2.0-eigen-(3.4.0)-lapack-suitesparse-(5.4.0)-eigensparse-no_openmp-cuda-(11060))

                                     Original                  Reduced
Parameter blocks                            1                        1
Parameters                                  3                        3
Residual blocks                            53                       53
Residuals                                  53                       53

Minimizer                        TRUST_REGION

Dense linear algebra library            EIGEN
Trust region strategy     LEVENBERG_MARQUARDT

                                        Given                     Used
Linear solver                        DENSE_QR                 DENSE_QR
Threads                                    16                       16
Linear solver ordering              AUTOMATIC                        1

Cost:
Initial                          7.558456e-01
Final                            3.697293e-01
Change                           3.861164e-01

Minimizer iterations                        7
Successful steps                            7
Unsuccessful steps                          0

Time (in seconds):
Preprocessor                         0.006938

  Residual only evaluation           0.000242 (7)
  Jacobian & residual evaluation     0.000245 (7)
  Linear solver                      0.000033 (7)
Minimizer                            0.000626

Postprocessor                        0.000003
Total                                0.007568

Termination:                      CONVERGENCE (Function tolerance reached. |cost_change|/cost: 1.418704e-10 <= 1.000000e-08)

**Comment by sandwichmaker** [comment]
Without some profiling information it is hard to say where in the
preprocessor the time is going.

That said, if you are not using any loss functions then you likely want to
look at using tinysolver, it is meant for small latency sensitive problems.

Sameer

**Comment by wsakobe** [comment]
Thanks for your kind reply.
               
I'd like to briefly describe the workflow of my code, so you can see if there are redundant or inappropriate steps.

for each frame:
      Set Ceres parameters;
      Do something to obtain the necessary variables;

      Problem problem;
      buildProblem(&problem, inlier_points, inlier_pixels);
      Solve(options, &problem, &summary);
end  

Here is the buildProblem() function:
  for (int i = 0; i < inlier_points.size(); i++) {
      CostFunction* cost_function;
      cost_function = EdgePixelError::Create(inlier_points[i], inlier_pixels[i], direction, pixel_high_low[0], pixel_high_low[1]);
      problem->AddResidualBlock(cost_function, NULL, line_function);
  }

Here is the cost function structure:
  struct EdgePixelError
  {
      Point edgepoint;
      float pixel;
      int direction;
      float high;
      float low;
  
      EdgePixelError(Point edge_point, float pixel, int direction, float pixel_high, float pixel_low) :edgepoint(edge_point), pixel(pixel), direction(direction), high(pixel_high), low(pixel_low) {}
  
      template <typename T>
      bool operator()(const T* const line_function, T* residuals)const {
          T prediction, dist;
  
          dist = (line_function[0] * T(edgepoint.x) + line_function[1] * T(edgepoint.y) + line_function[2]) / sqrt(line_function[0] * line_function[0] + line_function[1] * line_function[1]);
          prediction = (T(high) - T(low)) / (T(1) + exp(T(direction) * -dist * T(3))) + T(low);
          residuals[0] = prediction - T(pixel);
          return true;
      }
  
      static ceres::CostFunction* Create(Point edge_point, float pixel, int direction, float pixel_high, float pixel_low) {
          return (new ceres::AutoDiffCostFunction<EdgePixelError, 1, 3>(
              new EdgePixelError(edge_point, pixel, direction, pixel_high, pixel_low)));
      }
  };

Or is there any example of Ceres used in the real-time project? Maybe I can compare it with mine to find the problem. 
Thanks again.

Shaoan

**Comment by sandwichmaker** [comment]
Sorry for the delayed reply. I have two suggestions for you.
1. If you are not using a loss function or a bounds constraint, then you can combine all your residuals into a single cost function. this itself will reduce the preprocessing time.
2. if you are really latency sensitive, then I recommend using tinysolver instead of the main ceres Solver, your problem is small enough that it will make a difference.
