### ISSUE TITLE
Is it possible to mark irrelevance of residual block and parameter block at runtime?

### ISSUE THREAD

**Issue by zhixy** [ceres-solver/ceres-solver#949]
Assume that I have a optimization problem, the residual block of which is related to several parameter blocks. However, the residual is calculated by only part of the parameter blocks, which are determined at runtime. Then the jacobians of the unrelated paramater blocks must be given zero, right? But it is inefficient, because giving zero destroy the sparsity of the problem. My question is as the title saying, which could be more efficient to solve?

**Comment by sandwichmaker** [comment]
You can look at using DynamicSparsity.

See Problem::Options.

**Comment by zhixy** [comment]
@sandwichmaker Thank you for the reply, which indeed help me learn more about Ceres. I see dynamic_sparsity only work with SPARSE_NORMAL_CHOLESKY, how about other linear solver, especially schur complement solver? I think marking irrelevance will save much calculation during schur elimination.
