### ISSUE TITLE
How to get information matrix corresponding to the parameter block

### ISSUE THREAD

**Issue by zhenyu1024** [ceres-solver/ceres-solver#950]
Thank you for your sharing!
How can I get the information matrix or Jacobian matrix corresponding to the parameter block after optimization？

**Comment by sandwichmaker** [comment]
You can get the Jacobian using Problem::Evaluate.

**Comment by alexsmac** [comment]
You can also use the [Covariance](http://ceres-solver.org/nnls_covariance.html) class to compute blocks of the covariance matrix (subject to the assumptions of errors distributed according to a standard normal)
