### ISSUE TITLE
General linear & non-linear equality&  inequality constraints problem

### ISSUE THREAD

**Issue by fengweichangzi** [ceres-solver/ceres-solver#951]
In "FAQS, Tips & Tricks - Modeling" of Ceres Solver (http://ceres-solver.org/modeling_faqs.html)

One question is about how to solve general linear & non-linear equality &inequality constraints problem with Ceres Solver"

However, it sounds Ceres is not the best one for solving this problem. 

Could ayone recommend one open source library to solve this problem? Many thanks

**Comment by sandwichmaker** [comment]
IPOPT is a good place to start.
