### ISSUE TITLE
Documentation for EvaluationCallback seems incorrect.

### ISSUE THREAD

**Issue by rlabbe** [ceres-solver/ceres-solver#953]
http://ceres-solver.org/nnls_modeling.html#_CPPv4N5ceres18EvaluationCallbackE

States that the class signature is

```
class EvaluationCallback {
 public:
  virtual ~EvaluationCallback() = default;
  virtual void PrepareForEvaluation()(bool evaluate_jacobians
                                      bool new_evaluation_point) = 0;
};

```
I think there is an extra "()" in the signature for PrepareForEvaluation. The source code in evaluation_callback.h reads

```
class CERES_EXPORT EvaluationCallback {
 public:
  virtual ~EvaluationCallback();
  virtual void PrepareForEvaluation(bool evaluate_jacobians,
                                    bool new_evaluation_point) = 0;
};
```

There is also a missing comma between the two parameters.

**Comment by sandwichmaker** [comment]
Thanks @rlabbe I will take a look and fix.
