### ISSUE TITLE
‘LocalParameterization’ is not a member of ‘ceres’

### ISSUE THREAD

**Issue by LouxiDahu** [ceres-solver/ceres-solver#955]
/home/rm/sentry_ws/src/LIO-Livox/src/lio/PoseEstimation.cpp:190:10: error: ‘LocalParameterization’ is not a member of ‘ceres’
  190 |   ceres::LocalParameterization *quatParam = new ceres::QuaternionParameterization();
      |          ^~~~~~~~~~~~~~~~~~~~~
/home/rm/sentry_ws/src/LIO-Livox/src/lio/PoseEstimation.cpp:190:33: error: ‘quatParam’ was not declared in this scope
  190 |   ceres::LocalParameterization *quatParam = new ceres::QuaternionParameterization();
      |                                 ^~~~~~~~~
/home/rm/sentry_ws/src/LIO-Livox/src/lio/PoseEstimation.cpp:190:49: error: expected type-specifier
  190 |   ceres::LocalParameterization *quatParam = new ceres::QuaternionParameterization();

**Comment by sandwichmaker** [comment]
LocalParameterization has been deprecated. Use Manifolds instead.
