### ISSUE TITLE
error: expected type-specifier      ceres::Manifold *quatParam = new ceres::QuaternionParameterization();

### ISSUE THREAD

**Issue by LouxiDahu** [ceres-solver/ceres-solver#956]
sorry,i can't solve it.

**Comment by LouxiDahu** [comment]
the red line is drawn below ceres

**Comment by LouxiDahu** [comment]
sorry.now i know how to solve it.
QuaternionParameterization is deprecated. It will be removed in version 2.2.0 of Ceres Solver. Please use QuaternionManifold instead.

**Comment by zhouwuxiong** [comment]
@LouxiDahu Where did you find this information，I had the same problem for a long time，It bothered me for a long time
