### ISSUE TITLE
Can the memory usage be estimated before running program

### ISSUE THREAD

**Issue by Miuna26** [ceres-solver/ceres-solver#957]
First,for exemple,a data which is consisted of 20000 cameras,30000000 3D points and 160000000 2D observations will be used in program.
SecondlyI want to know if the program will be out of memory in advance.If will,how big the usage is will be considered normal.
And at last,is there any way to reduce the memory useage?

**Comment by sandwichmaker** [comment]
Sorry but no, because the memory usage depends on the linear solver and the sparsity pattern. For iterative solvers the memory usage is fairly linear in the size of the problem, but for sparse factorization based solvers like SPARSE_SCHUR it is not possible to estimate memory usage.

**Comment by Miuna26** [comment]
Thanks for your reply.I get it.
By the way,is it possible that a bal txt data sized of 8g that mentioned above cost 100g memory when solving the problem?The code is just as seem as the code in simple_bundle_adjustor.cc in exemple folder.
