### ISSUE TITLE
Error in #include<ceres/ceres.h>

### ISSUE THREAD

**Issue by CK-AK** [ceres-solver/ceres-solver#961]
This is my code:
```c++
//test_ceres
#include<iostream>
#include<ceres/ceres.h>

int main()
{
    
    return 0;
}
``` 
build it :make test_ceres
err:
In file included from /usr/local/include/ceres/ceres.h:46:0,
                 from /home/k/share/ceres-solver/examples/sampled_function/sampled_function.cc:34:
/usr/local/include/ceres/dynamic_autodiff_cost_function.h:280:48: error: expected constructor, destructor, or type conversion before ‘;’ token
     -> DynamicAutoDiffCostFunction<CostFunctor>;
                                                ^
In file included from /usr/local/include/ceres/ceres.h:65:0,
                 from /home/k/share/ceres-solver/examples/sampled_function/sampled_function.cc:34:
/usr/local/include/ceres/product_manifold.h:315:59: error: expected constructor, destructor, or type conversion before ‘;’ token
     -> ProductManifold<Manifold0, Manifold1, Manifolds...>;

What should I do about it？？

**Comment by sergiud** [comment]
The first thing you should always do is start reading the corresponding [documentation](http://ceres-solver.org/installation.html#using-ceres-with-cmake). Additionally, the Ceres version at head requires C++17 which is not enabled in your setup because you are not properly linking against Ceres.
