### ISSUE TITLE
Why is functor not available for DynamicAutoDiffCostFunction but is for AutoDiffCostFunction?

### ISSUE THREAD

**Issue by nmerrill67** [ceres-solver/ceres-solver#962]
Hello. I have a particular use case where I am doing a multi-step optimization, and would like to edit some members of the cost functor of DynamicAutoDiffCostFunction's CostFunctor, but the member is private. I noticed however that a reference is available for AutoDiffCostFunction https://github.com/ceres-solver/ceres-solver/blob/0315c6ca9ad3059d39975ada3565cf6c71d98ffa/include/ceres/autodiff_cost_function.h#L219

I am wondering if there is a reason it's not available for DynamicAutoDiffCostFunction? It would be useful and a very quick PR to add it. I have been creating the cost function outside of the CostFunctor class (i.e., outside of the useful Create function) which works but is not so concise, so I am wondering if there is any reasoning behind this discrepancy. Thanks.

**Comment by sandwichmaker** [comment]
This is likely just an oversight.  Please send me a change on Gerrit following http://www.ceres-solver.org/contributing.html I would happily approve it.
