### ISSUE TITLE
Why need to multiply 0.5 factor in ComputeSphereManifoldPlus function?

### ISSUE THREAD

**Issue by zpw6106** [ceres-solver/ceres-solver#963]
I found the sphere manifold plus function [implemented](https://github.com/ceres-solver/ceres-solver/blob/master/include/ceres/internal/sphere_manifold_functions.h) in ceres which multipy 0.5 factor into the $\delta$. This seems some differences with the parper "Integrating Generic Sensor Fusion Algorithms withSound State Representations through Encapsulation of Manifolds" in
Eq 107.  Can someone tell me why I need to do this ？
![image](https://user-images.githubusercontent.com/55874402/231397930-5cfb4215-33be-4116-b547-d60f624dcd69.png)

**Comment by sandwichmaker** [comment]
What version of Ceres Solver are you using?

The current implementation is 

https://github.com/ceres-solver/ceres-solver/blame/master/include/ceres/internal/sphere_manifold_functions.h#L77

which was made consistent in 

https://github.com/ceres-solver/ceres-solver/commit/f62dccdb37f2104856c621bce7fd79e7c92d5a9b

**Comment by zpw6106** [comment]
@sandwichmaker I am using version 2.1. Thank you for your reply. My problem has been resolved.
