### ISSUE TITLE
Encountering pointer truncation issue while running BA on Qualcomm Snapdragon 888 chipset

### ISSUE THREAD

**Issue by songshu-nreal** [ceres-solver/ceres-solver#964]
**error-record:**

> 04-11 15:11:59.351 21934 23031 I native  : I0411 15:11:59.351717 23031 trust_region_minimizer.cc:627] Terminating: Maximum number of iterations reached. Number of iterations: 5.
04-11 15:11:59.352 21934 23031 I native  : I0411 15:11:59.352150 23031 solver.cc:23] 
04-11 15:11:59.352 21934 23031 I native  : Solver Summary (v 1.13.0-eigen-(3.3.4)-no_lapack-eigensparse-no_openmp)
04-11 15:11:59.352 21934 23031 I native  : 
04-11 15:11:59.352 21934 23031 I native  :                                      Original                  Reduced
04-11 15:11:59.352 21934 23031 I native  : Parameter blocks                          396                      384
04-11 15:11:59.352 21934 23031 I native  : Parameters                               1254                     1196
04-11 15:11:59.352 21934 23031 I native  : Effective parameters                     1237                     1181
04-11 15:11:59.352 21934 23031 I native  : Residual blocks                          1515                     1515
04-11 15:11:59.352 21934 23031 I native  : Residual                                 3160                     3160
04-11 15:11:59.352 21934 23031 I native  : 
04-11 15:11:59.352 21934 23031 I native  : Minimizer                        TRUST_REGION
04-11 15:11:59.352 21934 23031 I native  : 
04-11 15:11:59.352 21934 23031 I native  : Sparse linear algebra library    EIGEN_SPARSE
04-11 15:11:59.352 21934 23031 I native  : Trust region strategy     LEVENBERG_MARQUARDT
04-11 15:11:59.352 21934 23031 I native  : 
04-11 15:11:59.352 21934 23031 I native  :                                         Given                     Used
04-11 15:11:59.352 21934 23031 I native  : Linear solver          SPARSE_NORMAL_CHOLESKY   SPARSE_NORMAL_CHOLESKY
04-11 15:11:59.352 21934 23031 I native  : Threads                                     8                        1
04-11 15:11:59.352 21934 23031 I native  : Linear solver threads                       8                        1
04-11 15:11:59.352 21934 23031 I native  : Linear solver ordering              AUTOMATIC                      384
04-11 15:11:59.352 21934 23031 I native  : 
04-11 15:11:59.352 21934 23031 I native  : Cost:
04-11 15:11:59.352 21934 23031 I native  : Initial                          9.204162e+03
04-11 15:11:59.352 21934 23031 I native  : Final                            2.623546e+03
04-11 15:11:59.352 21934 23031 I native  : Change                           6.580616e+03
04-11 15:11:59.352 21934 23031 I native  : 
04-11 15:11:59.352 21934 23031 I native  : Minimizer iterations                        6
04-11 15:11:59.352 21934 23031 I native  : Successful steps                            6
04-11 15:11:59.352 21934 23031 I native  : Unsuccessful steps                          0
04-11 15:11:59.352 21934 23031 I native  : 
04-11 15:11:59.352 21934 23031 I native  : Time (in seconds):
04-11 15:11:59.352 21934 23031 I native  : Preprocessor                           0.0027
04-11 15:11:59.352 21934 23031 I native  : 
04-11 15:11:59.352 21934 23031 I native  :   Residual evaluation                  0.0541
04-11 15:11:59.352 21934 23031 I native  :   Jacobian evaluation                  0.0236
04-11 15:11:59.352 21934 23031 I native  :   Linear solver                        0.0095
04-11 15:11:59.352 21934 23031 I native  : Minimizer                              0.0895
04-11 15:11:59.352 21934 23031 I native  : 
04-11 15:11:59.352 21934 23031 I native  : Postprocessor                          0.0001
04-11 15:11:59.352 21934 23031 I native  : Total                                  0.0923
04-11 15:11:59.352 21934 23031 I native  : 
04-11 15:11:59.352 21934 23031 I native  : Termination:                   NO_CONVERGENCE (Maximum number of iterations reached. Number of iterations: 5.)
04-11 15:11:59.352 21934 23031 F libc    : Pointer tag for 0x3f974538bf9edd93 was truncated, see 'https://source.android.com/devices/tech/debug/tagged-pointers'.
04-11 15:11:59.479  1946  3406 E OplusNetworkStatsNative: bpfGetAppPurStatsTotal return 0
04-11 15:11:59.502  1381  2677 E AudioFlingerExtImpl: updateAudioDetectState pid : 21934, get null buffer
=======================================================================================================

Platform: Android 13
cross-compile: NDK:android-ndk-r21e/build/cmake/android.toolchain.cmake

**Comment by sandwichmaker** [comment]
notice that ceres is done executing before the pointer truncation error. This is not a ceres solver related issue.
