### ISSUE TITLE
`RotationMatrixToEulerAngles` does not work with `Jet` type

### ISSUE THREAD

**Issue by ajaypbrt** [ceres-solver/ceres-solver#965]
I get a compilation error when trying to use automatic derivatives with `RotationMatrixToEulerAngles` and I believe it is due to
https://github.com/ceres-solver/ceres-solver/blob/77ad8bb4e53148ba0900a501c308b2df141a7d8a/include/ceres/rotation.h#L579-L581 and https://github.com/ceres-solver/ceres-solver/blob/77ad8bb4e53148ba0900a501c308b2df141a7d8a/include/ceres/rotation.h#L590-L592 where in both cases `ea[2] = 0;` should be `ea[2] = T(0);`

**Comment by sergiud** [comment]
cc @Hs293Go

**Comment by sandwichmaker** [comment]
actually changing it to 0.0 should work.

**Comment by sandwichmaker** [comment]
This should be fixed at head.  Can you check please?

**Comment by Hs293Go** [comment]
Glad to see someone has stepped in. I now realize that I did *not* write `*ForJets` tests for these conversion functions so this bug slipped through. I'll work on that and Ceres can expect a MR around the end of this month. (I also owe Ceres the docs for these functions...)

@sandwichmaker Maybe `T(0)` to be explicit? But I'm not familiar with implicit conversion ctors of Jets.

**Comment by sandwichmaker** [comment]
thanks for testing, let me see what is going on

**Comment by Hs293Go** [comment]
I am now writing `ForJets` tests for the euler angle conversions and hit snags in addition to `ea[2] = T(0);`.

Since Jets have no constexpr ctor, the following two lines also break when `T` is a Jet
```
constexpr T kPi = constants::pi_v<T>;
constexpr T kTwoPi(2.0 * kPi);
```
where a rough fix is 
```
const T kPi(constants::pi_v<double>);
const T kTwoPi(2.0 * kPi);
```
which makes the code compile. That aside I'm quite confident that the function is correct under autodiff but I'll submit the tests asap.

**Comment by sandwichmaker** [comment]
@ajaypbrt can you check if this works now?

**Comment by ajaypbrt** [comment]
It is working for me now, thank you!
