### ISSUE TITLE
Can't run SLAM pose_graph_2d.cc

### ISSUE THREAD

**Issue by mihany** [ceres-solver/ceres-solver#967]
I tried multiple times to pass the g2o filename, but this error shows up.

![Screenshot 2023-04-25 at 1 20 22 AM](https://user-images.githubusercontent.com/60690890/234136098-0e3e055c-73bc-4b5c-a84d-4008dd1b700a.png)

I followed the tutorial as it is. 

![Screenshot 2023-04-25 at 1 19 30 AM](https://user-images.githubusercontent.com/60690890/234135996-1c1047bf-5632-4968-8cd4-b2e4b44792cf.png)

**Comment by sandwichmaker** [comment]
--input=filename

**Comment by mihany** [comment]
Many Thanks 🙏🏻
