### ISSUE TITLE
adding planar constraints

### ISSUE THREAD

**Issue by navid-mahmoudian** [ceres-solver/ceres-solver#972]
Hello,

Thank you very much for this great library. I was wondering if there is a possibility to add planar constraints for some points in Bundle adjustment using Ceres, i.e., forcing the reconstruction of some point to lie on a plane. If yes, How to do it?

**Comment by sergiud** [comment]
You can add residual blocks that minimize orthogonal distances between each point and the plane being estimated.

**Comment by navid-mahmoudian** [comment]
Thank you for the quick reply. Does it at the same time update the 3D reconstructed points of the plane while forcing them in the optimization to be on a plane? 
Imagine in the initialization the 3D points are not really on a plane (due to noise in the data), but during update in bundle adjustment with Ceres, it forces these points to be on a plane while updating their 3D positions?

**Comment by sergiud** [comment]
You can refine the points as well if you add them as parameters.

**Comment by navid-mahmoudian** [comment]
OK. Thanks a lot. As for my last question before closing this issue: Is there any example with Ceres that imposes planar constraint?

**Comment by sergiud** [comment]
I'm not aware of any. However, `Eigen::Hyperplane` implementation might be a good starting point.

**Comment by navid-mahmoudian** [comment]
Thanks a lot. I closed the issue. If anyone else found any good example regarding this issue, feel free to share the link.
