### ISSUE TITLE
Adding pkg-config support to ceres-solver

### ISSUE THREAD

**Issue by kiplingw** [ceres-solver/ceres-solver#976]
Hello Maintainers,

Before I start working on it and submit a PR, I wanted to run the idea by you of adding pkg-config support to ceres-solver. Currently, at least on Debian based distros, the libceres-dev package does not ship a pkg-config manifest. This is helpful for developers who want to integrate your library into their build environment (which may not be CMake based).

**Comment by sandwichmaker** [comment]
@kiplingw we are happy to have this. Thank you. Please see the instructions at http://ceres-solver.org/contributing.html

**Comment by kiplingw** [comment]
Thanks @sandwichmaker. I've pushed my [suggested changes](https://ceres-solver-review.googlesource.com/c/ceres-solver/+/24360) to the Ceres Gerrit instance for your review.
