### ISSUE TITLE
how to set the parameter at position "index" constant?

### ISSUE THREAD

**Issue by Lightolx** [ceres-solver/ceres-solver#977]
while I have a list of parameters, for example, double body_pose[3*23], if I want to set the boundary of body_pose[10], I can use "problem.SetParameterLowerBound(body_pose, 10, -M_PI)", so how can I to set body_pose[10] constant? "problem.SetParameterBlockConstant(body_pose+10)" dose not work. Also, "problem.SetParameterLowerBound(body_pose, 10, 0.0); problem.SetParameterUpperBound(body_pose, 10, 0.0);" does not work
![Screenshot from 2023-06-13 15-53-26](https://github.com/ceres-solver/ceres-solver/assets/24823307/ec9e2b45-72ac-4bd9-ae32-67e3d805075b)

**Comment by sandwichmaker** [comment]
Use a subsetmanifold.
Sameer
