### ISSUE TITLE
LNK2005 cudaFree, which has been defined in cudart. lib (cudart64_110. dll)

### ISSUE THREAD

**Issue by Tomta10** [ceres-solver/ceres-solver#981]
Now I have encountered many errors while using vs2022 to regenerate the Ceres open source library. One of them is the severity LNK2005 cudaFree, which has already been defined in cudart. lib (cudart64_110. dll). My vs has reported many errors related to the name conflict of cudart. lib (cudart64_110. dll). I hope to receive help.
Cuda is version 11.7, vs is version 2022
![image](https://github.com/ceres-solver/ceres-solver/assets/98038949/7ff95270-a3a4-4f43-951e-d0de49ed970d)

**Comment by Tomta10** [comment]
cc: @joydeep-b

**Comment by sandwichmaker** [comment]
@DmitriyKorchemkin any ideas?

**Comment by Tomta10** [comment]
![Uploading 图片1.png…]()
