### ISSUE TITLE
Report error in "logging.h" and "logging.cc"

### ISSUE THREAD

**Issue by Followmeczx** [ceres-solver/ceres-solver#983]
In "logging.h"
`// Sink class used for integration with mock and test functions. If sinks are
// added, all log output is also sent to each sink through the send function.
// In this implementation, WaitTillSent() is called immediately after the send.
// This implementation is not thread safe.
class CERES_EXPORT LogSink {
 public:
  virtual ~LogSink() = default;
  virtual void send(LogSeverity severity,
                    const char* full_filename,
                    const char* base_filename,
                    int line,
                    const struct tm* tm_time,
                    const char* message,
                    size_t message_len) = 0;
  virtual void WaitTillSent() = 0;
};`
It report that "Incomplete types are not allowed". But when I delete CERES_EXPORT, the error will dimiss. So I guess that error is caused by "CERES_EXPORT". 
Can you give me some advice?

**Comment by sandwichmaker** [comment]
Can you describe how you are compiling ceres solver? in the first case you seem to be missing the definition of the macro CERES_EXPORT and in the second case it appears to be a linking problem.

**Comment by sandwichmaker** [comment]
something does not make sense to me here. Your cmake command does not enable miniglog, which means that cmake should be detecting and using glog installed in the system and should NOT be using the miniglog that comes with ceres solver. 

Are you sure 

```
git clone  https://github.com/ceres-solver/ceres-solver.git mkdir build cd build cmake .. -DCMAKE_CUDA_COMPILER:PATH=/usr/local/cuda/bin/nvcc make -j3 
```

is the command you used?

**Comment by Followmeczx** [comment]
> something does not make sense to me here. Your cmake command does not enable miniglog, which means that cmake should be detecting and using glog installed in the system and should NOT be using the miniglog that comes with ceres solver.

Yes, I'm sure.
This is what I do:
`(egocentric) CZX@inspur-NF5468M6:~/env$ git clone  https://github.com/ceres-solver/ceres-solver.git && cd ceres-solver && mkdir build && cd build && cmake .. -DCMAKE_CUDA_COMPILER:PATH=/usr/local/cuda/bin/nvcc && make -j3 
正克隆到 'ceres-solver'...
remote: Enumerating objects: 20567, done.
remote: Counting objects: 100% (430/430), done.
remote: Compressing objects: 100% (208/208), done.
remote: Total 20567 (delta 219), reused 302 (delta 182), pack-reused 20137
接收对象中: 100% (20567/20567), 16.44 MiB | 2.07 MiB/s, 完成.
处理 delta 中: 100% (14119/14119), 完成.
-- The C compiler identification is GNU 12.1.0
-- The CXX compiler identification is GNU 12.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAVE_BIGOBJ
-- Performing Test HAVE_BIGOBJ - Failed
-- Looking for pow in m
-- Looking for pow in m - found
-- Detected Ceres being used as a git submodule, adding commit hook for Gerrit to: /data/S221000776-CZX/env/ceres-solver/.git
-- Detected Ceres version: 2.2.0 from /data/S221000776-CZX/env/ceres-solver/include/ceres/version.h
-- Found Eigen version 3.3.7: /usr/local/share/eigen3/cmake
-- Enabling use of Eigen as a sparse linear algebra library.
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found CUDA version 11.1.105 installed in: /data/S221000776-CZX/env/cuda-11.1.1
-- The CUDA compiler identification is NVIDIA 11.7.64
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Setting CUDA Architecture to 50;60;70;80
-- Found LAPACK library: /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libblas.so;/usr/lib/x86_64-linux-gnu/libf77blas.so;/usr/lib/x86_64-linux-gnu/libatlas.so
-- Found CHOLMOD headers in: /usr/include/suitesparse
-- Found CHOLMOD library: /usr/lib/x86_64-linux-gnu/libcholmod.so
-- Found SPQR headers in: /usr/include/suitesparse
-- Found SPQR library: /usr/lib/x86_64-linux-gnu/libspqr.so
-- Found Config headers in: /usr/include/suitesparse
-- Found Config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Found AMD headers in: /usr/include/suitesparse
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found CAMD headers in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CCOLAMD headers in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found COLAMD headers in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found Intel Thread Building Blocks (TBB) library (2021.5 / 12050) include location: /usr/include. Assuming SuiteSparseQR was compiled with TBB.
-- Looking for shm_open in rt
-- Looking for shm_open in rt - found
-- Adding librt to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Could NOT find METIS (missing: METIS_INCLUDE_DIR METIS_LIBRARY) 
-- Found SuiteSparse: /usr/include/suitesparse (found suitable version "5.10.1", minimum required is "4.5.6") found components: CHOLMOD SPQR Config AMD CAMD CCOLAMD COLAMD missing components: Partition
-- Found SuiteSparse 5.10.1, building with SuiteSparse.
-- Could NOT find METIS (missing: METIS_INCLUDE_DIR METIS_LIBRARY) 
-- Did not find METIS, disabling Eigen METIS support.
-- Building without Apple's Accelerate sparse support.
-- Found Google Flags (gflags) version 2.2.2: /usr/lib/x86_64-linux-gnu/cmake/gflags
-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
-- Found installed version of glog: /usr/lib/x86_64-linux-gnu/cmake/glog
-- Detected glog version: 0.4.0
-- Found Glog: glog::glog  
-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
-- Failed to find Google benchmark library, disabling build of benchmarks.
-- Building Ceres as a static library.
-- No build type specified; defaulting to CMAKE_BUILD_TYPE=Release.
-- Performing Test CHECK_CXX_FLAG_Wmissing_declarations
-- Performing Test CHECK_CXX_FLAG_Wmissing_declarations - Success
-- Performing Test CHECK_CXX_FLAG_Wno_unknown_pragmas
-- Performing Test CHECK_CXX_FLAG_Wno_unknown_pragmas - Success
-- Performing Test CHECK_CXX_FLAG_Wno_sign_compare
-- Performing Test CHECK_CXX_FLAG_Wno_sign_compare - Success
-- Performing Test CHECK_CXX_FLAG_Wno_unused_parameter
-- Performing Test CHECK_CXX_FLAG_Wno_unused_parameter - Success
-- Performing Test CHECK_CXX_FLAG_Wno_missing_field_initializers
-- Performing Test CHECK_CXX_FLAG_Wno_missing_field_initializers - Success
-- Creating configured Ceres config.h output directory: /data/S221000776-CZX/env/ceres-solver/build/include/ceres/internal
-- Enabling CERES_USE_EIGEN_SPARSE in Ceres config.h
-- Enabling CERES_NO_ACCELERATE_SPARSE in Ceres config.h
-- Enabling CERES_NO_CHOLMOD_PARTITION in Ceres config.h
-- Enabling CERES_NO_EIGEN_METIS in Ceres config.h
-- Performing Test CHECK_CXX_FLAG_Wno_missing_declarations
-- Performing Test CHECK_CXX_FLAG_Wno_missing_declarations - Success
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Build the examples.
-- Configuring done (140.7s)
-- Generating done (2.7s)
-- Build files have been written to: /data/S221000776-CZX/env/ceres-solver/build
[  0%] Building CUDA object internal/ceres/CMakeFiles/ceres_cuda_kernels.dir/cuda_kernels_vector_ops.cu.cc.o
[  0%] Building CUDA object internal/ceres/CMakeFiles/ceres_cuda_kernels.dir/cuda_kernels_bsm_to_crs.cu.cc.o
[  0%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_2_2.cc.o
[  0%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_2_3.cc.o
[  1%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_2_4.cc.o
[  1%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_2_d.cc.o
[  1%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_3_3.cc.o
[  1%] Linking CUDA static library ../../lib/libceres_cuda_kernels.a
[  1%] Built target ceres_cuda_kernels
[  1%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_3_4.cc.o
[  1%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_3_6.cc.o
[  2%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_3_9.cc.o
[  2%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_3_d.cc.o
[  2%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_4_3.cc.o
[  2%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_4_4.cc.o
[  2%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_4_6.cc.o
[  2%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_4_8.cc.o
[  3%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_4_9.cc.o
[  3%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_4_d.cc.o
[  3%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_2_d_d.cc.o
[  3%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_3_3_3.cc.o
[  3%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_4_4_2.cc.o
[  4%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_4_4_3.cc.o
[  4%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_4_4_4.cc.o
[  4%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_4_4_d.cc.o
[  4%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/partitioned_matrix_view_d_d_d.cc.o
[  4%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_2_2.cc.o
[  4%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_2_3.cc.o
[  5%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_2_4.cc.o
[  5%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_2_d.cc.o
[  5%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_3_3.cc.o
[  5%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_3_4.cc.o
[  5%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_3_6.cc.o
[  5%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_3_9.cc.o
[  6%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_3_d.cc.o
[  6%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_4_3.cc.o
[  6%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_4_4.cc.o
[  6%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_4_6.cc.o
[  6%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_4_8.cc.o
[  7%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_4_9.cc.o
[  7%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_4_d.cc.o
[  7%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_2_d_d.cc.o
[  7%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_3_3_3.cc.o
[  7%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_4_4_2.cc.o
[  7%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_4_4_3.cc.o
[  8%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_4_4_4.cc.o
[  8%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_4_4_d.cc.o
[  8%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/generated/schur_eliminator_d_d_d.cc.o
[  8%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/accelerate_sparse.cc.o
[  8%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/array_utils.cc.o
[  9%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_evaluate_preparer.cc.o
[  9%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_jacobi_preconditioner.cc.o
[  9%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_jacobian_writer.cc.o
[  9%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_random_access_dense_matrix.cc.o
[  9%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_random_access_diagonal_matrix.cc.o
[  9%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_random_access_matrix.cc.o
[ 10%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_random_access_sparse_matrix.cc.o
[ 10%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_sparse_matrix.cc.o
[ 10%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/block_structure.cc.o
[ 10%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/callbacks.cc.o
[ 10%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/canonical_views_clustering.cc.o
[ 11%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/cgnr_solver.cc.o
[ 11%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/compressed_col_sparse_matrix_utils.cc.o
[ 11%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/compressed_row_jacobian_writer.cc.o
[ 11%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/compressed_row_sparse_matrix.cc.o
[ 11%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/conditioned_cost_function.cc.o
[ 11%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/context.cc.o
[ 12%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/context_impl.cc.o
[ 12%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/coordinate_descent_minimizer.cc.o
[ 12%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/corrector.cc.o
[ 12%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/cost_function.cc.o
[ 12%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/covariance.cc.o
[ 12%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/covariance_impl.cc.o
[ 13%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/cuda_block_sparse_crs_view.cc.o
[ 13%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/cuda_block_structure.cc.o
[ 13%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/cuda_sparse_matrix.cc.o
[ 13%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/cuda_vector.cc.o
[ 13%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dense_cholesky.cc.o
[ 14%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dense_normal_cholesky_solver.cc.o
[ 14%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dense_qr.cc.o
[ 14%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dense_qr_solver.cc.o
[ 14%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dense_sparse_matrix.cc.o
[ 14%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/detect_structure.cc.o
[ 14%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dogleg_strategy.cc.o
[ 15%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dynamic_compressed_row_jacobian_writer.cc.o
[ 15%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dynamic_compressed_row_sparse_matrix.cc.o
[ 15%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/dynamic_sparse_normal_cholesky_solver.cc.o
[ 15%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/eigensparse.cc.o
[ 15%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/evaluation_callback.cc.o
[ 16%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/evaluator.cc.o
[ 16%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/fake_bundle_adjustment_jacobian.cc.o
[ 16%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/file.cc.o
[ 16%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/first_order_function.cc.o
[ 16%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/float_suitesparse.cc.o
[ 16%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/function_sample.cc.o
[ 17%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/gradient_checking_cost_function.cc.o
[ 17%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/gradient_problem_solver.cc.o
[ 17%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/implicit_schur_complement.cc.o
[ 17%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/inner_product_computer.cc.o
[ 17%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/is_close.cc.o
[ 18%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/iteration_callback.cc.o
[ 18%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/iterative_refiner.cc.o
[ 18%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/iterative_schur_complement_solver.cc.o
[ 18%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/levenberg_marquardt_strategy.cc.o
[ 18%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/line_search.cc.o
[ 18%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/line_search_direction.cc.o
[ 19%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/line_search_minimizer.cc.o
[ 19%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/line_search_preprocessor.cc.o
[ 19%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/linear_least_squares_problems.cc.o
[ 19%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/linear_operator.cc.o
[ 19%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/linear_solver.cc.o
[ 19%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/low_rank_inverse_hessian.cc.o
[ 20%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/minimizer.cc.o
[ 20%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/parallel_for.cc.o
[ 20%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/parallel_invoke.cc.o
[ 20%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/parallel_utils.cc.o
[ 20%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/parameter_block_ordering.cc.o
[ 21%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/partitioned_matrix_view.cc.o
[ 21%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/polynomial.cc.o
[ 21%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/power_series_expansion_preconditioner.cc.o
[ 21%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/preconditioner.cc.o
[ 21%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/preprocessor.cc.o
[ 21%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/problem_impl.cc.o
[ 22%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/program.cc.o
[ 22%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/reorder_program.cc.o
[ 22%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/residual_block.cc.o
[ 22%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/residual_block_utils.cc.o
[ 22%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/schur_complement_solver.cc.o
[ 23%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/schur_eliminator.cc.o
[ 23%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/schur_jacobi_preconditioner.cc.o
[ 23%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/schur_templates.cc.o
[ 23%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/scratch_evaluate_preparer.cc.o
[ 23%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/single_linkage_clustering.cc.o
[ 23%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/solver_utils.cc.o
[ 24%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/sparse_cholesky.cc.o
[ 24%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/sparse_matrix.cc.o
[ 24%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/sparse_normal_cholesky_solver.cc.o
[ 24%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/stringprintf.cc.o
[ 24%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/subset_preconditioner.cc.o
[ 24%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/suitesparse.cc.o
[ 25%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/thread_pool.cc.o
[ 25%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/thread_token_provider.cc.o
[ 25%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/triplet_sparse_matrix.cc.o
[ 25%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/trust_region_minimizer.cc.o
[ 25%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/trust_region_preprocessor.cc.o
[ 26%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/trust_region_step_evaluator.cc.o
[ 26%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/trust_region_strategy.cc.o
[ 26%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/visibility.cc.o
[ 26%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/visibility_based_preconditioner.cc.o
[ 26%] Building CXX object internal/ceres/CMakeFiles/ceres_internal.dir/wall_time.cc.o
[ 26%] Built target ceres_internal
[ 26%] Building CXX object internal/ceres/CMakeFiles/ceres.dir/c_api.cc.o
[ 26%] Building CXX object internal/ceres/CMakeFiles/ceres.dir/gradient_checker.cc.o
[ 26%] Building CXX object internal/ceres/CMakeFiles/ceres.dir/gradient_problem.cc.o
[ 27%] Building CXX object internal/ceres/CMakeFiles/ceres.dir/loss_function.cc.o
[ 27%] Building CXX object internal/ceres/CMakeFiles/ceres.dir/manifold.cc.o
[ 27%] Building CXX object internal/ceres/CMakeFiles/ceres.dir/normal_prior.cc.o
[ 27%] Building CXX object internal/ceres/CMakeFiles/ceres.dir/problem.cc.o
[ 27%] Building CXX object internal/ceres/CMakeFiles/ceres.dir/solver.cc.o
[ 27%] Building CXX object internal/ceres/CMakeFiles/ceres.dir/types.cc.o
[ 28%] Linking CXX static library ../../lib/libceres.a
[ 28%] Built target ceres
[ 28%] Building CXX object examples/CMakeFiles/helloworld.dir/helloworld.cc.o
[ 28%] Building CXX object examples/CMakeFiles/helloworld_numeric_diff.dir/helloworld_numeric_diff.cc.o
[ 28%] Building CXX object internal/ceres/CMakeFiles/gtest.dir/gmock_gtest_all.cc.o
[ 28%] Linking CXX executable ../bin/helloworld
/usr/bin/ld: ../lib/libceres.a(solver.cc.o): in function `MessageLogger::~MessageLogger()':
solver.cc:(.text._ZN13MessageLoggerD2Ev[_ZN13MessageLoggerD5Ev]+0x139): undefined reference to `google::log_sinks_global'
/usr/bin/ld: solver.cc:(.text._ZN13MessageLoggerD2Ev[_ZN13MessageLoggerD5Ev]+0x140): undefined reference to `google::log_sinks_global'
/usr/bin/ld: solver.cc:(.text._ZN13MessageLoggerD2Ev[_ZN13MessageLoggerD5Ev]+0x2bd): undefined reference to `google::log_sinks_global'
/usr/bin/ld: solver.cc:(.text._ZN13MessageLoggerD2Ev[_ZN13MessageLoggerD5Ev]+0x2c4): undefined reference to `google::log_sinks_global'
/usr/bin/ld: ../lib/libceres.a(wall_time.cc.o): in function `ceres::internal::EventLogger::~EventLogger()':
wall_time.cc:(.text+0x988): undefined reference to `google::log_sinks_global'
/usr/bin/ld: ../lib/libceres.a(wall_time.cc.o):wall_time.cc:(.text+0xac1): more undefined references to `google::log_sinks_global' follow
[ 28%] Linking CXX executable ../bin/helloworld_numeric_diff
collect2: error: ld returned 1 exit status
make[2]: *** [examples/CMakeFiles/helloworld.dir/build.make:120：bin/helloworld] 错误 1
make[1]: *** [CMakeFiles/Makefile2:5681：examples/CMakeFiles/helloworld.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[ 28%] Building CXX object internal/ceres/CMakeFiles/gtest.dir/gmock_main.cc.o
/usr/bin/ld: ../lib/libceres.a(solver.cc.o): in function `MessageLogger::~MessageLogger()':
solver.cc:(.text._ZN13MessageLoggerD2Ev[_ZN13MessageLoggerD5Ev]+0x139): undefined reference to `google::log_sinks_global'
/usr/bin/ld: solver.cc:(.text._ZN13MessageLoggerD2Ev[_ZN13MessageLoggerD5Ev]+0x140): undefined reference to `google::log_sinks_global'
/usr/bin/ld: solver.cc:(.text._ZN13MessageLoggerD2Ev[_ZN13MessageLoggerD5Ev]+0x2bd): undefined reference to `google::log_sinks_global'
/usr/bin/ld: solver.cc:(.text._ZN13MessageLoggerD2Ev[_ZN13MessageLoggerD5Ev]+0x2c4): undefined reference to `google::log_sinks_global'
/usr/bin/ld: ../lib/libceres.a(wall_time.cc.o): in function `ceres::internal::EventLogger::~EventLogger()':
wall_time.cc:(.text+0x988): undefined reference to `google::log_sinks_global'
/usr/bin/ld: ../lib/libceres.a(wall_time.cc.o):wall_time.cc:(.text+0xac1): more undefined references to `google::log_sinks_global' follow
collect2: error: ld returned 1 exit status
make[2]: *** [examples/CMakeFiles/helloworld_numeric_diff.dir/build.make:120：bin/helloworld_numeric_diff] 错误 1
make[1]: *** [CMakeFiles/Makefile2:5708：examples/CMakeFiles/helloworld_numeric_diff.dir/all] 错误 2
[ 28%] Linking CXX static library ../../lib/libgtest.a
[ 28%] Built target gtest
make: *** [Makefile:146：all] 错误 2`

**Comment by sandwichmaker** [comment]
Sorry for the delayed reply, thank you for sharing the full log. Cmake is indeed detecting the system glog which is installed.
```
-- Found installed version of glog: /usr/lib/x86_64-linux-gnu/cmake/glog
-- Detected glog version: 0.4.0
-- Found Glog: glog::glog
-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
```

this has nothing to do with the miniglog files included in the source distribution. 

Yet the linking to glog is failing because it cannot find `google::log_sinks_global'`.

@alexsmac do you have any idea what maybe going on?

**Comment by sandwichmaker** [comment]
is this still an issue?

**Comment by sandwichmaker** [comment]
Closing because lack of response.
