### ISSUE TITLE
Undefined reference to 'METIS_EdgeND'

### ISSUE THREAD

**Issue by MMariia97** [ceres-solver/ceres-solver#986]
![image](https://github.com/ceres-solver/ceres-solver/assets/109080006/e7e30475-6dcf-4bc3-a686-4747540ce7d0)

**Comment by sandwichmaker** [comment]
I am sorry but this is not enough context to debug this problem. Please describe your build environment configuration and a bit more about the code fragment thats giving rise to this error.

**Comment by sandwichmaker** [comment]
Closing because lack of followup.
