### ISSUE TITLE
How to get Jacobian Matrix for every iterations?

### ISSUE THREAD

**Issue by Miuna26** [ceres-solver/ceres-solver#987]
Is there some way to get the Jacobian Matrix for every iterations ?

**Comment by sandwichmaker** [comment]
No. What are you trying to do?

**Comment by Miuna26** [comment]
My teacher wants to implement the process of LM algorithm, although I have written the program according to the paper, but my program solving results are not the same as ceres (I can accept that there is a gap in the solution because ceres has optimized some aspects), so I want to try to see if I can calculate same gain rate with the help of Jacobian matrix of ceres for each iteration to make sure that I have the same result of solving the normal equations in each case. So I want to try to see if I can calculate the gain rate with the help of the Jacobian matrix at each iteration of ceres to make sure that there is no problem with the implementation of my program if the result of the method equation is the same at each solving session, so that I can try to make changes in other aspects such as the radius of the confidence domain.
Another small question, according to the paper, the initial confidence domain radius of the LM method will be calculated based on the maximum value of the diagonal elements of the Hessian matrix, but the actual radius output from ceres is initially a fixed value no matter what the problem is (1e4 by default), is this value a small value multiplied by the maximum value of the diagonal elements in the paper?

**Comment by sandwichmaker** [comment]
So my suggestion in this case for you to study the code in tinysolver. It
is exactly the same algorithm as the full Ceres solver, but in a single
file and you can see all the implementation details that make the algorithm
work.
