### ISSUE TITLE
Solver returns 'Convergence' when cost is 'inf' and change is 'nan'

### ISSUE THREAD

**Issue by Ashray-g** [ceres-solver/ceres-solver#988]
<img width="987" alt="Screenshot 2023-08-01 at 7 09 01 PM" src="https://github.com/ceres-solver/ceres-solver/assets/43589795/d6e6efa7-dbc5-4216-a7b5-37fa56ca73b6">

**Comment by sandwichmaker** [comment]
Thanks @Ashray-g, this is definitely a bug, most likely having to do with a comparison with a nan. I will take a look.
