### ISSUE TITLE
Returning TinySolverCostFunctionAdapter

### ISSUE THREAD

**Issue by swapnilsayansaha** [ceres-solver/ceres-solver#989]
Suppose:
```
class FixVec3 {
public:
  FixVec3() {}

  template <typename T>
  bool operator()(const T* const p_ptr, T* residuals_ptr) const {
    Eigen::Map<const Eigen::Matrix<T, 3, 1> > p(p_ptr);

    Eigen::Map<Eigen::Matrix<T, 3, 1> > residuals(residuals_ptr);
    residuals.template block<3, 1>(0, 0) = p;

    return true;
  }

  static ceres::CostFunction* Create() {
    return new ceres::AutoDiffCostFunction<FixVec3, 3, 3>(new FixVec3());
  }
};
```

Now, suppose I want to modify the ``` static ceres::CostFunction* Create()``` to use Tinysolver. I suspect I have to use ```TinySolverCostFunctionAdapter```? How do I modify the function to accept ```TinySolverCostFunctionAdapter``` and return the cost function as shown above? 

Also on a side note, there is almost 0 documentation on tiny solver.

**Comment by sandwichmaker** [comment]
Sorry about the lack of documentation for `TinySolver.`  The header files have fairly detailed documentation though.

I think if just want to use TinySolver and not go back and forth between `ceres::Solver` and `ceres::TinySolver` then what you are really looking to use is `TinySolverAutoDiffFunction`.

Have a look at 

https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/tiny_solver_autodiff_function_test.cc

If you want to use `TinySolverCostFunctionAdapter`, then the trick is to first call FixVec3::Create, which will return a CostFunction object to you, which you then pass to a `TinySolverCostFunctionAdapter`.  

Have a look at 

https://github.com/ceres-solver/ceres-solver/blob/master/internal/ceres/tiny_solver_cost_function_adapter_test.cc
