### ISSUE TITLE
Setting bounds and manifolds in TinySolver

### ISSUE THREAD

**Issue by swapnilsayansaha** [ceres-solver/ceres-solver#990]
In Ceres, we can set bounds on parameters using the function ```problem.SetParameterLowerBound()``` and ```problem.SetParameterUpperBound()```. We can also use the ```EigenQuaternionManifold```` to set the bounds and behavior of quaternion vectors. 

Can we do the same thing when using TinySolver? Asking because tinysolver has a different template format over normal ceres cost functions.

**Comment by sandwichmaker** [comment]
No.

**Comment by swapnilsayansaha** [comment]
All right. That's sad because setting bounds on parameters is a basic feature of solvers.
