### ISSUE TITLE
Imprecision in Hello World

### ISSUE THREAD

**Issue by GasparPizarro** [ceres-solver/ceres-solver#991]
I am studying the [Hello World tutorial](http://ceres-solver.org/nnls_tutorial.html) where they minimize the function y = 0.5 * (10 - x) ^ 2. However, the residual is defined like this

    struct CostFunctor {
       template <typename T>
       bool operator()(const T* const x, T* residual) const {
         residual[0] = 10.0 - x[0];
         return true;
       }
    };

However, the function I see in the code is just y = 10 - x. Is that right, or do I have to pass the derivative to Ceres?

**Comment by sandwichmaker** [comment]
Dear @GasparPizarro there is no imprecision in the tutorial. You just have to read more or the tutorial. In the paragraph following the code fragment for `CostFunctor` it says and I quote:

The important thing to note here is that operator() is a templated method, which assumes that all its inputs and outputs 
are of some type T. The use of templating here allows Ceres to call CostFunctor::operator<T>(), with T=double when just
 the value of the residual is needed, and with a special type T=Jet when the Jacobians are needed. In [Derivatives]
(http://ceres-solver.org/nnls_tutorial.html#section-derivatives) we will discuss the various ways of supplying derivatives to Ceres in more detail.

So `helloworld.cc` uses the automatic differentiation abilities of Ceres to compute the derivatives. In the examples directory you will find two other variants of the same program. `helloworld_analytic_diff.cc` and `helloworld_numeric_diff.cc` which show you how to provide analytic derivatives yourself or use numeric differentiation (as opposed to automatic differentiation) to compute the derivatives.
