### ISSUE TITLE
Hack to include manifolds in tinysolver.

### ISSUE THREAD

**Issue by swapnilsayansaha** [ceres-solver/ceres-solver#994]
From previous discussion here, I got to know that Tinysolver has "no way" of including bounds or manifolds.

Is there any other way to include such bounds on parameter types like quaternions, perhaps through the residual? For example the norm of a quaternion should be 1, Maybe I can assign norm(q)-1 as one of the residuals?

**Comment by sandwichmaker** [comment]
use a 4-vector and normalize it before using it as a unit quaternion. Once the optimization is finished, normalize the output value again.

**Comment by swapnilsayansaha** [comment]
That worked. Thanks.
